files-community/Files

src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs

- Fixed DataGrid resize cursor when double clicking Grid Splitter
**Validation**

Fix: Fixed DataGrid resize cursor

---

src/Files.App/Actions/Show/ToggleShowHiddenItemsAction.cs
src/Files.App/UserControls/InnerNavigationToolbar.xaml
src/Files.App/Views/ColumnShellPage.xaml
src/Files.App/Views/ColumnShellPage.xaml.cs
src/Files.App/Views/ModernShellPage.xaml
src/Files.App/Views/ModernShellPage.xaml.cs

There was already a hotkey for ToggleShowHiddenItems, but not visible. This pr moves the hotkey into the existing command and adds the information to the button's tooltip.
**Validation**

RichCommand: HotKey for ToggleShowHiddenItems

---

src/Files.App/Views/WidgetsPage.xaml.cs

Sometimes a recent file is no longer available because its disk is unplugged. The homepage show an error dialog. It's annoying because the user does not try to access it but receives this message every time.
This pr no longer shows the dialog for recent files.
**Validation**

Fix: Don't show DriveUnpluggedDialog error for recent files

---

src/Files.App/BaseLayout.cs

Partially closes #10171
**Validation**
I have verified that drag-and-drop works for the following applications.
* Explorer
* Edge (working in the latest preview but #10949 breaks it)
* WordPad (working in the latest preview but #10949 breaks it)
* Visual Studio (not working in the latest preview)
* WhatsApp (not working in the latest preview)
**Details**
I was looking at #10949 and noticed that drag and drop works in many apps by setting the data to "Shell IDList Array" only.
This still does not allow drag and drop to Notepad or XShell, but there appears to be no regression. It may be necessary to create another data manually for these applications.
Also, #10949 only works for files that actually exist on the file system, so I …

Fix: Fixed drag and drop

---

src/Files.App/Strings/en-US/Resources.resw
src/Files.App/ViewModels/MainPageViewModel.cs
src/Files.App/Views/MainPage.xaml

The button NewTab (+) do not use the command. This pr fixes that.
**Validation**
Test the NewTab (+) button, its tooltip and its hotkey.

Use command NewTab for Button NewTab.

---

src/Files.App/Commands/Manager/CommandManager.cs

Remove the unused field manager of each RichCommand. This is a code cleanup.
**Validation**
No modification of the application, only a cleaning of the code.

CommandManager - Remove unused field

---

src/Files.App/Views/BaseShellPage.cs
src/Files.App/Views/ColumnShellPage.xaml.cs
src/Files.App/Views/LayoutModes/ColumnViewBrowser.xaml.cs

- Closes #11674 
**Details**
Now search results are displayed only in `DetailsLayout`
There's a limitation where you can't use `Double-Click-To-Go-Up` in search results opened from column view, still it works from the toolbar. This happens because of `ShellPage`s.
**Validation**

Fix: Fixed issue were clicking tags in columns layout would crash app

---

src/Files.App/Views/MainPage.xaml.cs

Related: #11737
**Changes**
- I added `Win key` cases in `OnPreviewKeyUp()` to remove them from modifiers
- `keyReleased` ensures that the shortcut is executed only once while the key is pressed
- **This PR does not address** all the use cases listed in the related Feature Request, since they have not yet been implemented as RichCommands. 
- I tested the behaviour of `Show Preview Pane` and `Open New Tab`
**Validation**

Feature: Only open single tab if user holds down ctrl + t

---

src/Files.App/Views/PaneHolderPage.xaml
src/Files.App/Views/PaneHolderPage.xaml.cs

Fixed: Selection isn't cleared when switching between panes

---

src/Files.App/Contexts/Page/PageContext.cs

When you activate a tab to the left of the current tab, the left tab becomes IsCurrentInstance = true before the right tab becomes IsCurrentInstance = false. As a result, there are 2 "current" instances at the same time. This case was mishandled by PageContext. This pr modifies PageContext so that this case is no longer an issue.
The consequence was that when switching tabs to the left, the actions no longer used the correct IShellPage and therefore everything was wrong.
I also removed the reaction to changing ActivePane, as it always involves changing ActivePaneOrColumn. This avoids triggering the change event twice.
Closes #11701
**Validation**
1. Open a second tab.
2. Reactive the first tab.
3. The icons in the toolbar react …

Fix PageContext

---

src/Files.App/IBaseLayout.cs
src/Files.App/Interacts/BaseLayoutCommandImplementationModel.cs

Fix: Fixed issue where the properties window opened from BaseContextMenuFlyout was hidden

---

src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml
src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs
src/Files.App/Views/LayoutModes/GridViewBrowser.xaml
src/Files.App/Views/LayoutModes/GridViewBrowser.xaml.cs

- Issue where unselecting a row hides checkbox instead of showing it unselected, supersedes #11715 @cinqmilleans FYI
Current issue is that the row is no longer highlighted when unselecting but I dont know a good workaround for this right now.
**Validation**

Fix: Fix Issue with unselecting row immediately hiding checkbox

---

src/Files.App/Actions/FileSystem/CreateShortcutFromDialogAction.cs

Fix: Fixed issue where it didn't work to create a shortcut unless an item is selected

---

src/Files.App/Filesystem/FilesystemOperations/ShellFilesystemOperations.cs
src/Files.App/Helpers/FileOperationsHelpers.cs

Closes #10755 
**Validation**
**Details**
The underlying issue was that `progress` was null, since the parameter was optional. I made it necessary so that we will avoid similar problems in the future

Fix: Fixed issue where transfer progress was always shown as 0%

---

src/Files.App/Filesystem/StorageFileHelpers/StorageFileExtensions.cs
src/Files.App/Helpers/FtpHelpers.cs
src/Files.App/Helpers/PathNormalization.cs
src/Files.App/ViewModels/ToolbarViewModel.cs
src/Files.App/Views/MainPage.xaml.cs

Closes #9808
Related #11575
**Validation**

Fix: Fixed issue with resolving paths containing dots

---

src/Files.App/Actions/FileSystem/CopyPathAction.cs
src/Files.App/Commands/CommandCodes.cs
src/Files.App/Commands/Manager/CommandManager.cs
src/Files.App/Commands/Manager/ICommandManager.cs
src/Files.App/Helpers/ContextFlyoutItemHelper.cs
src/Files.App/Interacts/BaseLayoutCommandImplementationModel.cs
src/Files.App/Interacts/BaseLayoutCommandsViewModel.cs
src/Files.App/Interacts/IBaseLayoutCommandImplementationModel.cs
src/Files.App/Views/ColumnShellPage.xaml.cs
src/Files.App/Views/ModernShellPage.xaml.cs

RichCommand: Copy path

---

src/Files.App/Filesystem/FilesystemOperations/FileSystemProgress.cs
src/Files.App/Helpers/RecycleBinHelpers.cs
src/Files.App/Interacts/IStatusCenterActions.cs
src/Files.App/ViewModels/StatusCenterViewModel.cs

Fix: Fixed issue where progress is shown in decimals

---

src/Files.App/Commands/HotKeyHelpers.cs
src/Files.App/Views/MainPage.xaml.cs

Some hotkeys should be disabled in textboxes, especially if there are no modifiers. This pr filters the keys that can trigger hotkeys in a textbox.
**Validation**
Test the hotkeys in the search field (ctrl+a, space, home, F11 ...)

Allow Textbox to use keyboard despite hotkeys

---

src/Files.App/UserControls/Widgets/QuickAccessWidget.xaml.cs

Closes #11794 
**Validation**
This pr changes the timing of icon loading. You will see icons are displayed during page loading, not after loaded.

Fix: Fixed icon loading delayed for quick access widget

---

src/Files.App/Actions/Content/InstallFontAction.cs
src/Files.App/Commands/CommandCodes.cs
src/Files.App/Commands/Manager/CommandManager.cs
src/Files.App/Commands/Manager/ICommandManager.cs
src/Files.App/Helpers/ShellContextMenuHelper.cs
src/Files.App/Interacts/BaseLayoutCommandImplementationModel.cs
src/Files.App/Interacts/BaseLayoutCommandsViewModel.cs
src/Files.App/Interacts/IBaseLayoutCommandImplementationModel.cs
src/Files.App/Shell/Win32API.cs
src/Files.App/UserControls/InnerNavigationToolbar.xaml
src/Files.App/ViewModels/ToolbarViewModel.cs
src/Files.App/Views/BaseShellPage.cs

Relates #11481 
**Validation**
1. Install a font from the toolbar
2. Install a font from the menu flyout
3. Install button is hidden if no item is selected or in recycle bin

RichCommand: InstallFont

---

src/Files.App/UserControls/AddressToolbar.xaml
src/Files.App/UserControls/AddressToolbar.xaml.cs
src/Files.App/UserControls/InnerNavigationToolbar.xaml
src/Files.App/UserControls/InnerNavigationToolbar.xaml.cs

Adds new AccessKeys to the toolbar.
* Some menus use automatically generated numbers. If necessary, these numbers have several digits.
* Added in New, Selection, Sort and Layout menus.
* The Layout menu is partial because the accesskeys on the button layouts do not always appear (to be investigated). They will be added later.
* Added for PreviewPane and SearchBox.
**Validation**
Test the accesskeys.
https://user-images.githubusercontent.com/46631671/226976170-a6678074-ddad-4e7e-8109-5c70b21fbb08.mp4

Add AccessKeys to InnerToolBar.

---

src/Files.App/BaseLayout.cs
src/Files.App/IShellPage.cs
src/Files.App/Views/BaseShellPage.cs

Closes #801
**Validation**
N/A

Feature: Always apply most current layout

---

src/Files.App/Actions/Content/Selection/ToggleSelectAction.cs
src/Files.App/Commands/CommandCodes.cs
src/Files.App/Commands/Manager/CommandManager.cs
src/Files.App/Commands/Manager/ICommandManager.cs

* Add Command ToggleSelect for (de)select distant items with the keyboard.
* Use hotkey Ctrl+Space.
* Works on all SelectorItem controls, including layout items.
* Works well with Ctrl+Up/Down/Left/Right to focus items with the keyboard without moving in the list/grid (native hotkeys).
**Validation**
Use Ctrl+Up/Down/Left/Right for moving in list/grid. Use Ctrl+Space for (de)select distant items.
https://user-images.githubusercontent.com/46631671/227733686-0fed1665-2ade-48df-9b87-9137f7cf4eff.mp4

Command ToggleSelect

---

src/Files.App/Strings/en-US/Resources.resw

Fix: Added missing `ToggleSelect` string resource

---

src/Files.App/MainWindow.xaml.cs

It's not approved yet, but I believe it should be fixed.
Closes #11858 
**Validation**
1. Open a terminal.
2. Type "files.exe" and press enter.
3. You will see that the startup settings are reflected.

Fix: Fixed issue where the startup settings was ignored when launched from terminal

---

src/Files.App/Actions/FileSystem/OpenItemAction.cs
src/Files.App/Views/LayoutModes/ColumnViewBase.xaml.cs
src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs
src/Files.App/Views/LayoutModes/GridViewBrowser.xaml.cs

Closes #11870 
**Validation**
**Notes**
This will fix same issue as #11871, but this one uses RichCommand to open item with Enter key.

Fix: Assigned Enter as a hotkey to open item.

---

src/Files.App/Views/MainPage.xaml.cs

Closes #11800 
**Validation**
1. Select an item.
2. Press Delete key.
3. You will see a dialog. Press Cancel button.
4. Press Delete key again.
5. You will see a dialog again. In 2.4.57.0, no dialog appears.

Fix: Fixed issue where hotkeys with dialog would not work

---

src/Files.App/Filesystem/FilesystemOperations/Helpers/FilesystemHelpers.cs
src/Files.App/ServicesImplementation/Settings/FoldersSettingsService.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/ViewModels/Settings/FoldersViewModel.cs
src/Files.App/Views/Settings/FoldersPage.xaml
src/Files.Backend/Services/Settings/IFoldersSettingsService.cs

Closes #10221...
**Validation**
2. Rename a file extension
3. Verify that the warning dialog is displayed 
4. Open setting, navigate to the folder page and turn off the option for displaying the warning
5. Rename a file extension and verify the warning isn't displayed

Feature: Added support for turning off file extension warning

---

src/Files.App/Shell/Win32Shell.cs

**Validation**
- If you run it in debug mode, you will see that NullReferenceException is no longer raised.

Fix: Fixed issue that caused NullReferenceException to be raised unnecessarily

---

src/Files.App/Views/LayoutModes/ColumnViewBase.xaml.cs
src/Files.App/Views/LayoutModes/ColumnViewBrowser.xaml.cs

This is a follow-up to #11898.
When a parent folder is selected in the column view, the item highlight in the last blade should be cleared.
**Validation**
Berfore:
After:

Fix: Clear highlight in the last blade

---

src/Files.App/Helpers/ItemListDisplayHelpers/BulkConcurrentObservableCollection.cs
src/Files.App/Helpers/ItemListDisplayHelpers/GroupingHelper.cs
src/Files.App/Strings/en-US/Resources.resw

Related #11759 
**Validation**
- [ x Did you implement any design changes to an existing feature?
1. Open a folder which contains both tagged and untagged items
2. Select `Group by Tag`
3. See that all items are grouped
4. Refresh the page
5. See that all items are under the `Untagged` group

Fix: Fixed issue where grouping by tags wouldn't show all items

---

src/Files.App/BaseLayout.cs
src/Files.App/Helpers/ItemModelListToContextFlyoutHelper.cs
src/Files.App/Helpers/ShellContextMenuHelper.cs
src/Files.App/Shell/ContextMenu.cs
src/Files.App/Shell/ContextMenuItem.cs
src/Files.App/UserControls/Widgets/FileTagsWidget.xaml.cs
src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml.cs
src/Files.App/ViewModels/ContextMenuFlyoutItemViewModel.cs

It loads main menu first, then loads Open with submenu, Send to submenu and other submenus in order.
Closes #11882 
**Validation**
**GIF (2.4.60 is light, this PR is dark)**

Feature: Improved shell extension loading

---

src/Files.App/Helpers/QuickLookHelpers.cs

`DetectQuickLookAvailability()` is called each time an item is selected, so this PR changes the log output timing to only when pressed space to try to launch QuickLook.
**Validation**

Fix: Log only when pressed space

---

src/Files.App/Actions/Content/Run/RunWithPowershellAction.cs
src/Files.App/Commands/CommandCodes.cs
src/Files.App/Commands/Manager/CommandManager.cs
src/Files.App/Commands/Manager/ICommandManager.cs
src/Files.App/UserControls/InnerNavigationToolbar.xaml
src/Files.App/ViewModels/ToolbarViewModel.cs
src/Files.App/Views/BaseShellPage.cs

Add a RichCommand to run script with powershell
- Related #11481
_None_

RichCommand: Run With Powershell

---

src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs
src/Files.App/Views/LayoutModes/GridViewBrowser.xaml.cs

Closes #11960...
**Validation**
2. Clear selection
3. Hover over and item and verify the checkbox isn't shown
4. Select the item and the checkbox should become visible
5. Hovering over other items should show the checkbox as long as at least one item is currently selected

Feature: Don't show checkbox when no items are selected

---

src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml

Closes #11195
**Validation**
1. Hover over an item in the details layout and verify that the tooltip doesn't show

Feature: Removed tooltip from details layout

---

src/Files.App/ViewModels/FolderSettingsViewModel.cs
src/Files.App/Views/BaseShellPage.cs

#11851 has caused some regressions. This PR will fix them.
* Fixed issue with layout changes sometimes not working properly
* Fixed "NotAFolder" error when returning to the home page with the back button after changing the layout
**Validation**
1. Layout changes should always work correctly. In 2.4.60, layout changes sometimes causes blank screen or no change.
2. "NotAFolder" error shouldn't occur when returning to the home page with the back button after changing the layout.

Fix: Fixed regressions caused by "Always apply most current layout"

---

src/Files.App/Views/MainPage.xaml.cs

Fix: Fixed issue with review Files dialog not working

---

src/Files.App/Dialogs/SettingsDialog.xaml
src/Files.App/UserControls/AddressToolbar.xaml

Closes #11982 
**Validation**
1. Open app
2. Hover `Settings` button

Fix: Changed the location of the "close" tooltip

---

src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml.cs
src/Files.App/Views/HomePage.xaml.cs

Feature: Added properties option when right clicking recent files

---

src/Files.App/Actions/BaseUIAction.cs
src/Files.App/Actions/Content/Archives/CompressIntoArchiveAction.cs
src/Files.App/Actions/Content/Archives/DecompressArchive.cs
src/Files.App/Actions/Content/Archives/DecompressArchiveHere.cs
src/Files.App/Actions/Content/Archives/DecompressArchiveToChildFolderAction.cs
src/Files.App/Actions/FileSystem/CreateFolderAction.cs
src/Files.App/Actions/FileSystem/CreateShortcutAction.cs
src/Files.App/Actions/FileSystem/CreateShortcutFromDialogAction.cs
src/Files.App/Actions/FileSystem/DeleteItemAction.cs
src/Files.App/Actions/FileSystem/EmptyRecycleBinAction.cs
src/Files.App/Actions/FileSystem/PasteItemToSelectionAction.cs
src/Files.App/Actions/FileSystem/RestoreAllRecycleBinAction.cs
src/Files.App/Actions/FileSystem/RestoreRecycleBinAction.cs
src/Files.App/Actions/Open/OpenSettingsAction.cs

Regression #11928
**Validation**
1. Open app and see if `Delete` icon is shown
2. Open context menu and if `Delete` and `Paste` icons are shown

Fix: Some icons are not displayed

---

src/Files.App/Contexts/DisplayPage/DisplayPageContext.cs
src/Files.App/Contexts/DisplayPage/IDisplayPageContext.cs

Closes #12048
**Validation**
1. Open the layout flyout in the toolbar and observe the state of the Adaptive toggle

Fix: Fixed issue where the adaptive layout toggle was always disabled

---

src/Files.App/Resources/PreviewPanePropertiesInformation.json
src/Files.App/Resources/PropertiesInformation.json

Fix: Fixed incorrect aperture values

---

src/Files.App/Views/LayoutModes/ColumnViewBase.xaml.cs
src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs
src/Files.App/Views/LayoutModes/GridViewBrowser.xaml.cs

Fix: Fixed Ctrl+A in the rename textbox

---

src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs
src/Files.App/Views/LayoutModes/GridViewBrowser.xaml.cs

This is slightly different from what we discussed in #11975, but I believe this is the best solution.
* In details view, unchecked checkboxes now appear only when the icon is hovered.
* In grid view, checkboxes appear when the item is hovered even if no item is selected (same as 2.4.60).
Closes #11975 
**Validation**
**Movie**
https://user-images.githubusercontent.com/66369541/230263831-da6436c1-bd37-48ef-a26d-c42aa3bc5c5c.mp4

Feature: Improved checkbox behavior

---

src/Files.App/Strings/en-US/Resources.resw

Fix: Fixed issue where some of the key names were not correct

---

src/Files.App/Contexts/DisplayPage/DisplayPageContext.cs

Closes (partially) #12045
NOTE: with this change sorting and grouping in column view work but the chosen sorting options do not "stick" (navigating to another folder and back will reset the options). I believe this always used to be the case, so perhaps we can merge this PR as is and work on saving the sorting options later.
**Validation**
1. Verify that sorting and gouping are correctly applied to the selected column

Fix: Fixed sorting and grouping not working in column view

---

src/Files.App/Filesystem/FilesystemOperations/ShellFilesystemOperations.cs
src/Files.App/Helpers/Convert/ErrorCodeConverter.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.Shared/Enums/CopyEngineResult.cs
src/Files.Shared/Enums/FileSystemStatusCode.cs

Closes #11570
Closes #9423
Closes #9772
**Validation**
1. Copy or move a file with a tag to a FAT32 formatted usb drive

Feature: Added support for copying files with ADS to FAT32

---

src/Files.App/Constants.cs
src/Files.App/DataModels/NavigationControlItems/DriveItem.cs
src/Files.App/DataModels/SidebarPinnedModel.cs
src/Files.App/Filesystem/ListedItem.cs
src/Files.App/Helpers/ElevationHelpers.cs
src/Files.App/Helpers/UIHelpers.cs
src/Files.App/ViewModels/ItemViewModel.cs
src/Files.App/ViewModels/SidebarViewModel.cs
src/Files.App/Views/LayoutModes/ColumnViewBase.xaml
src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml
src/Files.App/Views/LayoutModes/GridViewBrowser.xaml

Closes #4845 
**Validation**
- Tested for shortcuts as well.

Feature: Display "shield overlay" indicating when elevation is required

---

src/Files.App/Views/LayoutModes/ColumnViewBase.xaml
src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml
src/Files.App/Views/LayoutModes/GridViewBrowser.xaml
src/Files.App/Views/LayoutModes/GridViewBrowser.xaml.cs

This is necessary to identify hidden or cut items when checkboxes are displayed instead of icons.
**Validation**

Feature: Translucent hidden or cut item name

---

src/Files.App/ViewModels/MainPageViewModel.cs

Closes #11894 
**Validation**
1. Make Files the default file manager.
2. Set the startup settings to other than "Open a new tab".
3. Launch Files via "Open file location" in the Start menu.
4. You see tabs are opened according to the startup settings in addition to the specified location.

Fix: Fixed issue where the startup settings were ignored if a location is specified

---

src/Files.App/ServicesImplementation/Settings/FoldersSettingsService.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/ViewModels/ItemViewModel.cs
src/Files.App/ViewModels/Settings/FoldersViewModel.cs
src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs
src/Files.App/Views/Settings/FoldersPage.xaml
src/Files.Backend/Services/Settings/IFoldersSettingsService.cs

Feature: Added an option to hide checkboxes in the details layout

---

src/Files.App/BaseLayout.cs
src/Files.App/Helpers/ShellContextMenuHelper.cs
src/Files.App/Shell/ContextMenu.cs

Fix: Fixed issue where "Send To" submenu was sometimes not displayed on widgets

---

src/Files.App/Shell/ContextMenu.cs

Fix: A workaround to avoid AccessViolationException

---

src/Files.App/ServicesImplementation/Settings/FoldersSettingsService.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/ViewModels/ItemViewModel.cs
src/Files.App/ViewModels/Settings/FoldersViewModel.cs
src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs
src/Files.App/Views/LayoutModes/GridViewBrowser.xaml.cs
src/Files.App/Views/Settings/FoldersPage.xaml
src/Files.Backend/Services/Settings/IFoldersSettingsService.cs

I believe this is the last tweak about checkboxes.
**Validation**

Feature: Apply show checkboxes option to the grid view as well

---

src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml
src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs

Fix: Fixed issue where checkboxes might remain visible

---

specs/RichCommand/CommandList.md
src/Files.App/Actions/FileSystem/BaseDeleteAction.cs
src/Files.App/Actions/FileSystem/DeleteItemAction.cs
src/Files.App/Actions/FileSystem/DeleteItemPermanentlyAction.cs
src/Files.App/Actions/FileSystem/PermanentlyDeleteAction.cs
src/Files.App/Commands/CommandCodes.cs
src/Files.App/Commands/Manager/CommandManager.cs
src/Files.App/Commands/Manager/ICommandManager.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/Views/ColumnShellPage.xaml
src/Files.App/Views/ColumnShellPage.xaml.cs
src/Files.App/Views/ModernShellPage.xaml
src/Files.App/Views/ModernShellPage.xaml.cs

Related #11481
**Notes**
This PR also removes some `KeyboardAccelerators` leftovers (`Refresh` and `Delete`)
**Validation**
- [] Did you remove any strings from the en-us resource file?
1. Open app and select a file
2. Use `Shift + Del` to permanently delete it or `Ctrl + D` to delete it

RichCommand: PermanentlyDelete

---

src/Files.App/ResourceDictionaries/PathIcons.xaml

Closes #11956...
**Validation**
1. Open app
2. Switch to dark mode
3. Verify that the new, paste and rename icons have a semitransparent fill
4. Switch to light mode and verify they have a solid white fill

Feature: Added IconAltAccentBrush for toolbar icons

---

src/Files.App/Views/ColumnParam.cs
src/Files.App/Views/LayoutModes/ColumnViewBase.xaml.cs
src/Files.App/Views/LayoutModes/ColumnViewBrowser.xaml.cs

Closes #12090 
- I simplified the code to find the last column that should remain open (I don't know why I wrote that complex code in the first place). Now it looks for the blade with the same path as the requested one.
- As mentioned in #11898, there's a bug with double click to open
**Notes**
- Please, test these changes deeply since they may cause many regressions
- It may happen that the user creates a loop of columns (like: `C:\Users\username\Desktop\shortcut_to_Users\username\Desktop\something_else`). In this case, if the user clicks an item in `Desktop`, should we always close all columns after the first `Desktop`?
**Validation**
**Test 1**
1. Open app and a folder using colums view
2. Use `Open folders …

Fix: Fixed cannot select Files in columns view

---

src/Files.App/Actions/Content/Archives/DecompressArchive.cs

Fix: Fixed issue where the extract button on the toolbar was disabled in archives

---

src/Files.App/UserControls/Widgets/DrivesWidget.xaml.cs
src/Files.App/UserControls/Widgets/QuickAccessWidget.xaml.cs

In widgets, `thumbnailData.ToBitmapAsync()` is called on the same thread as `LoadCardThumbnailAsync()`, so `DispatcherQueue.EnqueueAsync()` is redundant.
**Validation**

Fix: Fixed possible NullReferenceException in widgets

---

src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml
src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml.cs

Fix: Fixed high CPU usage in the recent files widget

---

src/Files.App/Views/Settings/AboutPage.xaml
src/Files.App/Views/Settings/AdvancedPage.xaml
src/Files.App/Views/Settings/AppearancePage.xaml
src/Files.App/Views/Settings/FoldersPage.xaml
src/Files.App/Views/Settings/GeneralPage.xaml
src/Files.App/Views/Settings/TagsPage.xaml

**Changes**
Switched to RepositionThemeTransition animation in the settings dialog
**Validation**
3. Verified the RepositionThemeTransition is being used

Feature: Switched to RepositionThemeTransition

---

src/Files.App/Helpers/ThemeHelper.cs
src/Files.App/ViewModels/MainPageViewModel.cs

 Fix: Fixed possible System.NullReferenceException in ThemeHelper

---

src/Files.App/Helpers/ThemeHelper.cs

Fix: Fixed NullReferenceException in ThemeHelper part 2

---

src/Files.App/Dialogs/CreateArchiveDialog.xaml
src/Files.App/Dialogs/CreateArchiveDialog.xaml.cs
src/Files.App/Dialogs/CreateShortcutDialog.xaml
src/Files.App/Helpers/CloudDrivesDetector.cs
src/Files.App/Helpers/DynamicDialogFactory.cs
src/Files.App/ViewModels/Dialogs/CreateShortcutDialogViewModel.cs
src/Files.App/ViewModels/Settings/TagsViewModel.cs
src/Files.App/Views/Settings/TagsPage.xaml
src/Files.App/Views/Settings/TagsPage.xaml.cs

I think these changes should be merged into the servicing branch as well.
**Validation**

Fix: Cherry-pick recent changes into servicing

---

src/Files.App/Views/PaneHolderPage.xaml.cs

…h shortcuts
Closes #12202 
**Validation**
1. Open two panes (`Home` and `Home`, if the primary pane was not on `Home` it worked even before)
2. Click on the secondary pane
3. Use `Ctrl + Shift + W` to close it
4. Open a favorite from the sidebar (do not click on the primary pane)

Fix: Switch focus to the primary pane when closing dual pane mode

---

src/Files.App/Shell/ContextMenu.cs

I don't think this will solve all problems, but I believe it is important to prevent further problems.
* Fixed problem with COM objects not being properly discarded on context menu warm-up
* Fixed problem where ThreadWithMesssageQueue was being used unnecessarily for shell extensions with no submenu. This will improve performance
**Validation**

Fix: Refactored ContextMenu

---

src/Files.App/ViewModels/Properties/Items/BaseProperties.cs
src/Files.Backend/Services/SizeProvider/CachedSizeProvider.cs

Fix: Fixed folder size calculation

---

src/Files.App/Actions/Start/UnpinFromStartAction.cs

The `UnpinFromStartAction` calls currently the `TryPinFolderAsync` instead of the `UnpinFromStartAsync` method.
The bug was introduced in #11493 where the code was migrated to a RichCommand.
With this change it is again possible to unpin items from the start menu.
**Validation**
1. Unpin a single file
2. Unpin multiple files
3. Unpin single directory
4. Unpin multiple directories

Fix: Fixed issue where unpin from start didn't work

---

src/Files.App/UserControls/SidebarControl.xaml

Closes None
**Validation**
1. Open app 
2. Hover a drive such as `C:\`, see that the tooltip looks as before
3. Hover `Network` folder or any other that has no detail
Before/After
Before/After

Fix: Reduced tooltip size when only the drive name is available

---

src/Files.App/ViewModels/Dialogs/CreateShortcutDialogViewModel.cs

Related #12150 
The former code was blocking all the listeners subscribed to the change of `IsLocationValid`
**Validation**
1. Open app 
2. Right click on empty space
3. Click new > new shortcut
4. Enter an invalid path and then a valid one

Fix: create button is always disabled in new shortcut dialog

---

src/Files.App/ViewModels/ItemViewModel.cs

**Motivation**
When trying to access `ftp paths`, Files crashed because of a `stack overflow exception`. This PR prevents that 
**Validation**
1. Open app
2. Type and `ftp path` in the address bar

Fix: Fixed a crash with ftp connections

---

src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml

Closes #12085
Moved the hyperlink button after the SemanticZoom control to allow tap event to invoke the command. This also helps keep the control center in the window.
**Validation**
1. Confirm the hyperlink button in DetailsLayoutBrowser is clickable and the binding command is invoked
2. Confirm the search unindexed items hyperkink works as expected in GridViewBrowser

Fix: Fixed issue where search unindexed items wasn't clickable

---

src/Files.App/Helpers/UIFilesystemHelpers.cs

Closes #12249 
I'm wondering if we should implement `Esc to cancel cut` as in file explorer....
**Validation**
1. Open app
2. Cut some items
3. Select other items and select them
4. See that items opacity resets

Fix: Reset items opacity when copying other items

---

src/Files.App/Shell/ContextMenu.cs

Fix: Fixed issue where removing an item from the recent list didn't work

---

src/Files.App/BaseLayout.cs
src/Files.App/Helpers/DriveHelpers.cs

Closes #12227 
This PR also handles a null exception 
**Validation**
1. Open "Files"
2. Select "Documents"
3. Change View Layout to "Columns"
4. Enable Preview Panel
5. Click any items in the first level, the detail shows up correctly in the preview.
6. Select a folder and click on an item at the second level, the preview is not rendered. Select a different item or lose focus of the current selection and reselect the item will cause it to render correctly in the preview.

Fix: Fixed issue with file preview in column layout

---

src/Files.App/Helpers/BitmapHelper.cs

Fix: Fixed crash when creating bitmap images

---

src/Files.App/Helpers/GitHelpers.cs
src/Files.App/ViewModels/CurrentInstanceViewModel.cs

Closes #12292 
**IMPORTANT**
At the moment this PR only prevents the crash (branch name is still not displayed). The exception is raised because the repository belongs to a different user. We can't show the branch name/interact with the repository unless the user set it as "safe".
I think we should show a modal to warn the user about this. We might also provide the command to resolve the issue (`git config --global --add safe.directory = path`) or show a button to execute that
**Validation**
1. Open a git repository in WSL

Fix: Fixed crash that would occur in git directories on WSL drives

---

src/Files.App (Package)/Package.appxmanifest

**Changes in v2.4.81**
- Fixed issue where it didn't work to drag multiple files from the tags area.
- Fixed NullReferenceException in folder.GetThumbnailAsync.
- Fixed crash with Win32Exception.
- Fixed wrong total editing time format in the details pane.
- Fixed issue with file preview in column layout.
- Fixed crash when creating bitmap images.
- Fixed an issue where it wasn't possible to edit some file permissions.
- Fixed crash that would occur in git directories on WSL drives.

Preview: v2.4.81

---

src/Files.App/Data/Models/SidebarPinnedModel.cs

Fix: Fixed crash when trying to create bitmap from null IconData in `SidebarPinnedModel.cs`

---

src/Files.App/ViewModels/ItemViewModel.cs

Related #12010 
**Notes**
Removing `async` from that method would prevent the exception from being caught by the local `catch`
**Validation**
1. Open app
2. Try to access an ftp folder
3. See that the `Credentials dialog` is shown

Fix: Fixed issue where credentials dialog wasn't shown when accessing FTP

---

src/Files.App (Package)/Package.appxmanifest
src/Files.App/Helpers/DynamicDialogFactory.cs
src/Files.App/Helpers/GitHelpers.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/UserControls/StatusBarControl.xaml
src/Files.App/UserControls/StatusBarControl.xaml.cs
src/Files.App/ViewModels/DirectoryPropertiesViewModel.cs
src/Files.App/Views/Shells/BaseShellPage.cs
src/Files.Backend/Enums/GitCheckoutOptions.cs

Related #11014 
**Notes**
- The flyout is clipped because of #11713
- During the checkout the layout is updated more than once, I want to find a way to avoid that
**Validation**
1. Open folder with git repo with uncommitted changes
2. Try switching branches from the status bar flyout
3. Try all the available options

Feature: Added support for local branch checkout

---

src/Files.App/Data/Models/SidebarPinnedModel.cs
src/Files.App/ViewModels/ItemViewModel.cs

Fix: Fixed NullReferenceException with EnumerateItemsFromStandardFolderAsync

---

src/Files.App (Package)/Files.Package.wapproj

This makes it so Files actually uses 1.3 instead of 1.2 when running on the user's system.
**Validation**

Fix: Upgrade Files.Package to WinAppSDK 1.3

---

src/Files.App/Actions/FileSystem/AddItemAction.cs
src/Files.App/Actions/FileSystem/CreateFolderWithSelectionAction.cs
src/Files.App/Actions/Global/EditPathAction.cs
src/Files.App/Actions/Global/SearchUnindexedItemsAction.cs
src/Files.App/Commands/CommandCodes.cs
src/Files.App/Commands/Manager/CommandManager.cs
src/Files.App/Commands/Manager/ICommandManager.cs
src/Files.App/Helpers/ContextFlyoutItemHelper.cs
src/Files.App/Interacts/BaseLayoutCommandImplementationModel.cs
src/Files.App/Interacts/BaseLayoutCommandsViewModel.cs
src/Files.App/Interacts/IBaseLayoutCommandImplementationModel.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/UserControls/InnerNavigationToolbar.xaml
src/Files.App/Views/Shells/ColumnShellPage.xaml
src/Files.App/Views/Shells/ModernShellPage.xaml

Related #11481 
**Additional Notes**
- I added the `copyright section` to two files that were missing it
- I cleaned up some rich command leftovers from `ModernShellPage`, `ColumnShellPage` and `InnerNavigationToolbar`
**Validation**
1. Open app and navigate to a folder
2. Right click to open the context menu
3. See that `Create folder with selected items` is not visible
4. Select some items
5. Right click to open the context menu
6. See that `Create folder with selected items` is visible
7. Click on it

RichCommands: CreateFolderWithSelection

---

src/Files.App/Views/PaneHolderPage.xaml.cs
src/Files.App/Views/Shells/BaseShellPage.cs

Closes #12280 
Closes #12285  
**Validation**
#12285 is 100% reproducible with the following steps. This should be fixed once this PR is applied.
1. Start dual pane mode.
2. Open any folder that is not the home page in each pane.
3. Start renaming an item.
4. Click on the other pane while renaming.
5. The focus will keep switching between panes.

Fix: Fixed focus flickering between columns or panes

---

specs/RichCommand/CommandList.md
src/Files.App/Actions/FileSystem/CopyPathAction.cs
src/Files.App/ResourceDictionaries/PathIcons.xaml
src/Files.App/Strings/en-US/Resources.resw

The command list has also been updated to the latest information.
Closes #11945 
**Validation**

Feature: Renamed Copy location to Copy path

---

src/Files.App/Helpers/ArchiveHelpers.cs

This formats the banner at extracting in the same format as the banner at compressing.
#12362 occurs when the title and message are short enough to be displayed on one line.
This does not completely fix #12362 but reduce its occurrence.
**Validation**
Before:
After:
Banner at compression (for comparison):

Feature: Changed the format of the banner at extracting archives

---

src/Files.App/Helpers/FileOperationsHelpers.cs

Closes #11501
**Validation**
1. Try to delete a folder that contains one MP4 movie file only.
2. The confirmation dialog will show immediately. Without this fix, it will show after doing some operations.

Fix: Fixed issue where delete confirmation dialog sometimes did not appear immediately

---

src/Files.App/Filesystem/Search/FolderSearch.cs
src/Files.Shared/FileTagsDb.cs

Closes #12331
**Validation**
1. Assign tag on network drive ("\\\\localhost\\some_shared_folder" will work)
2. Check that it appears when clicking the same tag on the sidebar

Fix: Display tags on network drives when selecting tag

---

src/Files.App/UserControls/FilePreviews/BasicPreview.xaml
src/Files.App/UserControls/FilePreviews/FolderPreview.xaml
src/Files.App/UserControls/FilePreviews/ImagePreview.xaml
src/Files.App/UserControls/FilePreviews/PDFPreview.xaml

Thumbnail previews now stretch properly when more space is available.
**Validation**
1. Open preview pane and resize it

Feature: Stretch image previews

---

src/Files.App/UserControls/FilePreviews/HtmlPreview.xaml.cs
src/Files.App/ViewModels/Previews/HtmlPreviewViewModel.cs

References https://github.com/MicrosoftEdge/WebView2Feedback/issues/2281
Closes #12151
**Validation**

Fix: Fixed crash when previewing large html or svg files

---

src/Files.App/Data/Items/StatusBanner.cs
src/Files.App/UserControls/OngoingTasksFlyout.xaml

This will fix #12362 completely.
Closes #12362 
**Validation**
Before:
After:

Fix: Fixed issue where progress bar was overlapping text in ongoing operations

---

src/Files.App/ServicesImplementation/PreviewPopupProviders/SeerProProvider.cs

Related #8052... (this PR doesn't include switching between files)
**Validation**
1. Install and open SeerPro
2. Use space bar to toggle preview from Files

Feature: Added SeerPro support

---

src/Files.App/ServicesImplementation/DateTimeFormatter/ApplicationDateTimeFormatter.cs

**Validation**
1. Change language settings to a language other than the system language.
2. Open properties and select Details.
3. You will see the date is displayed in the set language. Without this fix, the date is displayed in the system language regardless of the setting.

Fix: Fixed issue with some date formats not reflecting language settings

---

src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml
src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs

Closes #12481 
**Validation**
1. When a text in the details view is trimmed, a tooltip will be displayed when hovering.
2. When a text in the details view is not trimmed, a tooltip will not be displayed.

Feature: Show a tooltip when a text in the details view is trimmed

---

src/Files.App/ResourceDictionaries/PathIcons.xaml
src/Files.App/Views/MainPage.xaml.cs

Closes #9902...
**Validation**
1. Open the preview pane
2. Make window as narrow as possible
3. Start reducing the window height until there is only enough space for around three items in the details layout
4. Confirm that the preview pane automatically hides
5. Make the window wider until the preview pane is visible on the right
6. Reduce the window height until there is just enough space to view the item details in the preview pane
7. Confirm that the preview pane hides if you continue to reduce the window height

Feature: Automatically hide the preview pane when the window is too small

---

src/Files.App/Views/LayoutModes/ColumnViewBase.xaml.cs
src/Files.App/Views/LayoutModes/ColumnViewBrowser.xaml.cs

Closes #12429...
**Validation**
1. Switch to column layout
2. Open a folder from the second column
3. Select al the items in the second column and verify that the third column is closed

Fix: Fixed issue with selecting multiple items in column layout

---

src/Files.App/App.xaml.cs
src/Files.App/Data/Models/AppModel.cs
src/Files.App/Helpers/FilePropertiesHelpers.cs

Fix: Fixed crash with properties window

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml

GitHub: Improved bug report template

---

src/Files.App/Actions/Content/Install/InstallCertificateAction.cs
src/Files.App/Commands/CommandCodes.cs
src/Files.App/Commands/Manager/CommandManager.cs
src/Files.App/Commands/Manager/ICommandManager.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/UserControls/InnerNavigationToolbar.xaml
src/Files.Backend/Helpers/FileExtensionHelpers.cs

Closes #12482 
**Validation**
2. Click on any .cer, .crt, .pfx, and .der files.

Feature: Added "install" toolbar button for certificate files

---

src/Files.App/Data/Models/SelectedItemsPropertiesViewModel.cs
src/Files.App/ViewModels/Properties/HashesViewModel.cs
src/Files.App/Views/Properties/DetailsPage.xaml
src/Files.App/Views/Properties/DetailsPage.xaml.cs
src/Files.App/Views/Properties/HashesPage.xaml
src/Files.Backend/Models/HashInfoItem.cs

In addition to during properties loading, a progress bar is now displayed during hash value calculation.
Closes #12532 
**Validation**
Details tab:
Hashes tab:

Feature: Show a progress ring or bar while loading in the properties window

---

src/Files.App/Constants.cs
src/Files.App/Helpers/AppThemeResourcesHelper.cs
src/Files.App/UserControls/Pane/PreviewPane.xaml
src/Files.App/ViewModels/Previews/FolderPreviewViewModel.cs

Fix: Fixed issue where custom font wasn't applied to the details pane

---

src/Files.App/Views/MainPage.xaml.cs
src/Files.App/Views/Shells/BaseShellPage.cs

Closes Issue reported on Discord
**Details**
- The issue was caused by the `Locals` radio button which was unchecked when changing tab, causing the app to try to checkout a branch on load
**Validation**
1. Open a git repository in one tab
2. Open another tab
3. Switch back to the first tab

Fix: Fixed crash when changing tab with one git repository open

---

src/Files.App/Views/LayoutModes/ColumnViewBase.xaml
src/Files.App/Views/LayoutModes/ColumnViewBase.xaml.cs

Closes #12456
Closes #12512 
**Validation**

Fix: Fixed issue with opening and closing folder in column layout

---

src/Files.App/UserControls/StatusBarControl.xaml

Closes #12589
There seem to be an issue with x:Bind so that you can't use a TwoWay x:Bind on an element that is inside an element with x:Load:
```cs
<StackPanel x:Load="{x:Bind ...}">
<RadioButton IsChecked="{x:Bind ..., Mode=TwoWay}" />
</StackPanel>
```
Workaround is to use Binding.
**Validation**
1. Open a non-git folder in left pane and set layout to Tiles
2. Open a git folder in right pane and set layout to Details
3. Switch focus between the two panes
4. Verify that you can still switch between local and remote branches in the Git flyout

Fix: Fixed crash in Dual Pane mode when switching away from Git folder

---

src/Files.App/Dialogs/ReorderSidebarItemsDialog.xaml

Closes #12596...
**Validation**
1. Open reorder sidebar items dialog
2. Resize window so that the dialog shrinks
3. Confirm that scrollbar is visible

Fix: Fixed issue where scrollbar wasn't visible when reordering pinned favorites

---

src/Files.App/Filesystem/Search/FolderSearch.cs
src/Files.App/Filesystem/StorageEnumerators/UniversalStorageEnumerator.cs

Closes #11043
**Validation**
Comment:
This pull request fixed the folder size appears blank in the recycle bin.
1. Tested recycle bin shows folders with their sizes
2. Tested folders with their sizes are correctly displayed when searching within the recycle bin.
3. Tested status bar at the bottom able to displays the total size of the recycle bin, whether all files and folders are selected or not.
Before
After

Fix: Fixed issue where folder sizes weren't shown in Recycle Bin

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
src/Files.App/Constants.cs
src/Files.App/ViewModels/Settings/AboutViewModel.cs

Closes #4635
**Validation**
**Comment**
Add `files_version` and `windows_version` query string to `BugReportUrl` or `FeatureRequestUrl` when user click on Submit Feature / Bug Request so that issue form able to auto populate their value to the form element with same `id` defined in `bug_report.yml` and `feature_request.yml`
Documentation reference:  [Syntax for GitHub's form schema (Keys section)](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema#keys)
To test this functionality, please use the [test-issue-4635](https://github.com/tanchekwei/Files/tree/test-issue-4635) branch, as I have updated the template URL to point to my repository's branch in …

Feature: Auto-Populate Files and Windows Version when submitting feedback

---

src/Files.App/Data/Models/ItemViewModel.cs

Fix: Fixed issue where navigating away from search wouldn't show the folders items

---

src/Files.App/Views/LayoutModes/BaseLayout.cs
src/Files.App/Views/LayoutModes/IBaseLayout.cs
src/Files.App/Views/PaneHolderPage.xaml.cs

Fix: Fixed issue where the preview pane didn't update when switching panes

---

src/Files.App/UserControls/Widgets/FileTagsWidget.xaml
src/Files.App/UserControls/Widgets/FileTagsWidget.xaml.cs

Closes #12650 
**Validation**
1. Item names now should have ellipsis if trimmed
2. A tooltip with the path now should be displayed
3. Right-clickable area of the item is now corrected

Fix: Fixed issue where item names in the Tags widget didn't have ellipsis

---

src/Files.App/Converters/Converters.cs
src/Files.App/UserControls/StatusBarControl.xaml

Fix: Fixed crash when switching away from Git folder

---

src/Files.App/Actions/Open/OpenInVSAction.cs
src/Files.App/Actions/Open/OpenInVSCodeAction.cs

Related #12645 
**Validation**
1. Navigate to a git repository that has a " " in the path
2. Use "Open in VS" or "Open in VS Code" button

Fix: Fixed issue where open in VS Code didn't work if there were spaces in the path

---

src/Files.App/Data/Models/GitItemModel.cs
src/Files.App/Data/Models/ItemViewModel.cs
src/Files.App/Filesystem/ListedItem.cs
src/Files.App/Helpers/GitHelpers.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml

Feature: Added tooltips to Git columns in the details layout

---

src/Files.App/Helpers/ShellContextMenuHelper.cs
src/Files.App/UserControls/Widgets/FileTagsWidget.xaml.cs
src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml.cs

Fix for widgets and sidebar

---

src/Files.App/Helpers/ContextFlyoutItemHelper.cs
src/Files.App/Helpers/ShellContextMenuHelper.cs
src/Files.App/ServicesImplementation/Settings/GeneralSettingsService.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/UserControls/Widgets/FileTagsWidget.xaml.cs
src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml.cs
src/Files.App/ViewModels/Settings/GeneralViewModel.cs
src/Files.App/Views/LayoutModes/BaseLayout.cs
src/Files.App/Views/Settings/GeneralPage.xaml
src/Files.Backend/Services/Settings/IGeneralSettingsService.cs

Closes #12546...
**Validation**
1. Confirm the Send To menu only shows when the setting is enabled
2. Test in the widgets as well

Feature: Added option to hide the Send To menu

---

src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs
src/Files.App/Views/LayoutModes/StandardLayoutMode.cs

Closes #12613...
**Validation**
1. Select folder
2. Middle click selected folder to open it in new tab
3. Confirm it doesn't cause a crash
4. Test in all the layouts

Fix: Fixed issue where middle clicking selected folders would cause crash

---

src/Files.App/Views/LayoutModes/GridViewBrowser.xaml.cs

References https://github.com/files-community/Files/pull/12683#pullrequestreview-1492479396
Related to #12683 
**Validation**

Fix: Fixed issue where a text box would remain visible in the tiles layout when returning from a new tab

---

src/Files.App/UserControls/StatusBarControl.xaml
src/Files.App/UserControls/StatusBarControl.xaml.cs

Closes #12701 
**Validation**
1. Start dual-pane mode.
2. Open a Git directory and the home page.
3. Focus the home page.

Fix: Fixed issue where Git buttons were incorrectly shown in the status bar

---

src/Files.App/Views/LayoutModes/ColumnViewBrowser.xaml.cs

Closes #12724 
**Validation**
1. Select an empty folder in column layout
2. Press right arrow key
3. Files doesn't crash

Fix: Fixed crash with moving into an empty folder in column layout

---

src/Files.App/Data/Models/ColumnsViewModel.cs
src/Files.App/Helpers/LayoutPreferences/LayoutPreferences.cs
src/Files.App/Services/Settings/FoldersSettingsService.cs

This also fixes the default widths of Git columns.
Closes #12730 
**Validation**

Fix: Fixed issue where widths of Git columns were not set correctly

---

src/Files.App/Views/HomePage.xaml.cs

This is one of the crashes that has become more frequent since 2.5. I don't know why this happens, but there is code that is needlessly changing the property that is causing this crash, and I would like to remove it and see if that solves the problem.
**Validation**

Code Quality: Removed unnecessary IsPageTypeNotHome changes

---

src/Files.App/UserControls/StatusBarControl.xaml
src/Files.App/Views/PaneHolderPage.xaml

Added dividers between status bar sections
**Validation**

Feature: Added dividers between status bar sections

---

src/Files.App/UserControls/Pane/PreviewPane.xaml

Closes #12781...
**Validation**
1. Open details pane
2. Confirm everything is displayed properly

Feature: Redesigned the way details are displayed in the details pane

---

src/Files.App/UserControls/StatusBarControl.xaml

Closes #12792...
**Validation**
1. Confirm spacing between status bar items is consistent

Fix: Fixed alignment issues on status bar

---

src/Files.App/ResourceDictionaries/PropertiesStyles.xaml
src/Files.App/Views/Properties/DetailsPage.xaml
src/Files.App/Views/Properties/HashesPage.xaml
src/Files.App/Views/Properties/SecurityAdvancedPage.xaml

Closes #12727...
**Validation**
1. Open properties window
2. Confirm the property names have the correct font color

Feature: Updated font colors in the Properties window

---

src/Files.App/Helpers/ArchiveHelpers.cs

Closes #12801 
**Validation**
1. Press Ctrl+E in Home
2. Crash will no longer occur

Fix: Fixed crash that would occur when pressing Ctrl+E on the Home page

---

src/Files.App/Actions/Git/GitFetchAction.cs
src/Files.App/Actions/Git/GitInitAction.cs
src/Files.App/Actions/Git/GitPullAction.cs
src/Files.App/Actions/Git/GitPushAction.cs
src/Files.App/Actions/Git/GitSyncAction.cs
src/Files.App/Commands/CommandCodes.cs
src/Files.App/Commands/Manager/CommandManager.cs
src/Files.App/Commands/Manager/ICommandManager.cs
src/Files.App/Helpers/GitHelpers.cs
src/Files.App/Strings/en-US/Resources.resw

Closes #12799 
**Validation**
1. Assign a custom shortcut to the action 
2. Open an empty folder
3. Use the shortcut to initialize the repo

Feature: Added support for initializing folders as Git repos

---

src/Files.App/Helpers/GitHelpers.cs
src/Files.App/Resources/PreviewPanePropertiesInformation.json
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/ViewModels/Previews/FolderPreviewViewModel.cs

Closes #12779 
**Validation**
1. Tried on a unsynchronized repository with no origin and no commit. No data is displayed.

Feature: Display Git details in the Details Pane

---

src/Files.App/Filesystem/StorageItems/ShellStorageFile.cs

Note: Date deleted of the shortcut is always displayed as Now because it can't be retrieved from system properties correctly.
Closes #12756 
**Validation**

Fix: Fixed issue where the columns were misaligned in Recycle Bin

---

src/Files.App/Filesystem/ListedItem.cs
src/Files.App/Services/Settings/FileTagsSettingsService.cs
src/Files.Backend/Services/Settings/IFileTagsSettingsService.cs

Closes #12814
**Validation**
1. Set "Home" tag and "Work" tag to a folder in the details layout.
2. Change the layout to the grid layout.
3. Change the layout back to the details layout.
4. Delete "Home" tag.
5. Delete "Work" tag.
6. The app will crash.
A part of the issue is caused by `Select` throwing exception with empty arrays, the other is related to this piece of code
Since `FileTagsUI` is empty `[0]` doesn't exist. I fixed setting it to null, but we could also create a `FirstTag` property

Fix: Fixed issue were removing a tag after changing the layout would cause a crash

---

src/Files.App/Helpers/ArchiveHelpers.cs

Closes #12809 
**Validation**
1. Select a small archive (extraction should take less than 6 seconds)
2. Extract it
3. Check the status center
4. Repeat using a big archive  (extraction time >= 6s)

Fix: Fixed issue where Status Center didn't update when archives were finished being extracted

---

src/Files.App/UserControls/Widgets/FileTagsWidget.xaml

Closes #12370 
Closes #12751 
Closes #12818 
**Validation**
1. Enable the tags widget.
2. Open the home page.
3. Adjust the window width so that the tags widgets are lined up vertically in a row.
4. Repeat scrolling up and down.
5. No more crash happens.

Fix: Fixed crash that would occur when enabling the tags widget

---

src/Files.App/Data/EventArguments/MainPageNavigationArguments.cs
src/Files.App/MainWindow.xaml.cs
src/Files.App/ViewModels/MainPageViewModel.cs

Closes #12812 
**Validation**
1. If you perform "Open in new window", the new window will contain a tab of selected item only.
2. If you launch the app from command line with a path to open, it will still follow the startup settings.

Fix: Fixed issue where "Open in new window" followed the startup settings

---

src/Files.App/Actions/Display/LayoutAction.cs
src/Files.App/Commands/Manager/CommandManager.cs
src/Files.App/Contexts/DisplayPage/DisplayPageContext.cs
src/Files.App/UserControls/InnerNavigationToolbar.xaml

**Validation**
1. Go to folder with adaptive mode enabled -> check that adaptive toggle is on
2. Go to folder with adaptive mode disabled -> check that correct layout is highlited

Fix: Fixed layout mode icon not reflecting current folder layout

---

src/Files.App/Views/LayoutModes/BaseLayout.cs

I don't know if this is the exact same problem as the one pointed out in #7864, but this should significantly reduce drop failures, including other than the column layout.
Closes #7864 (Maybe)
**Validation**

Fix: Fixed issue where dragged items sometimes could not be dropped

---

src/Files.App/UserControls/Pane/PreviewPane.xaml
src/Files.App/UserControls/Pane/PreviewPane.xaml.cs
src/Files.App/ViewModels/Previews/FolderPreviewViewModel.cs

Closes #12796 
**Validation**
1. Open the details pane
2. Click on `Properties`

Feature: Added "Properties" button to the Details Pane

---

src/Files.App/ResourceDictionaries/PathIcons.xaml
src/Files.App/UserControls/InnerNavigationToolbar.xaml
src/Files.App/ViewModels/UserControls/ToolbarViewModel.cs

Closes #12894 
**Validation**
1. Open app and navigate to a folder
2. Change layout

Feature: Reflect current layout in the Toolbar

---

src/Files.App/Data/Items/DriveItem.cs
src/Files.App/Files.App.csproj
src/Files.App/Helpers/Storage/DriveHelpers.cs
src/Files.App/Services/RemovableDrivesService.cs
src/Files.App/Utils/WindowsStorageDeviceWatcher.cs

Closes #12901
NB: added a new nuget dependency (DiscUtils.Udf) as winapi GetVolumeInformation only returns up to 32 chars. I won't raise a fuss if PR is refused due to this :)
**Validation**
1. Mount attached ISOs
2. Check UDF formatted ISO label is > 32 characters
[udf_long_name.zip](https://github.com/files-community/Files/files/12021489/udf_long_name.zip)

Feature: Increased maximum volume label length to 128 characters for UDF images

---

src/Files.App/Utils/Shell/ContextMenu.cs

Closes #12912
**Validation**
1. Install google drive and verify that all items appear in context menu
2. Verify that Files does not crash when right clicking an exe and you have an NVidia graphic card

Fix: Fixed issue where some options were missing in the Google Drive context menu

---

src/Files.App/Data/Models/ItemViewModel.cs
src/Files.App/Helpers/StorageItemCollection/BulkConcurrentObservableCollection.cs
src/Files.App/Helpers/StorageItemCollection/ConcurrentCollection.cs
src/Files.App/Helpers/StorageItemCollection/SortingHelper.cs

I believe this may avoid crashes like #12924.
Related to #12617 
**Validation**

Code Quality: Use thread-safe collections in ItemViewModel

---

src/Files.App/ViewModels/UserControls/PreviewPaneViewModel.cs

Closes #12878 
**Validation**
1. Show the details pane.
2. Switch the pane to Preview mode.
3. Select a file.
4. Switch the pane to Details mode.
5. Properties should load and display.

Fix: Fixed issue where properties were sometimes not displayed in the details pane

---

src/Files.App/Views/LayoutModes/BaseLayout.cs
src/Files.App/Views/LayoutModes/IBaseLayout.cs
src/Files.App/Views/MainPage.xaml.cs

Fix: Fixed issue where Details/Preview Pane didn't update when switching tabs

---

src/Files.App/Data/Models/CurrentInstanceViewModel.cs
src/Files.App/Utils/Git/GitHelpers.cs
src/Files.App/ViewModels/Previews/FolderPreviewViewModel.cs

Related #12737 
**Validation**
1. Open app 
2. Open a large git repository

Code Quality: Reduce git folders loading time

---

src/Files.App/MainWindow.xaml.cs
src/Files.App/Views/PaneHolderPage.xaml.cs

Fix: Fixed issue where opening folder from external source didn't honor dual pane settings

---

src/Files.App/App.xaml.cs
src/Files.App/Views/SplashScreenPage.xaml
src/Files.App/Views/SplashScreenPage.xaml.cs

This PR modifies the splash screen loading wait to end as soon as the image loading is complete, rather than fixed at 500 ms.
**Validation**

Code Quality: Reduce splash screen display time for faster startup

---

src/Files.App/MainWindow.xaml.cs

Closes #13019 
**Validation**
Launch the app from CMD with "files C:\". You will see the app launches successfully.

Fix: Fixed crash when launching from CMD with "Files"

---

src/Files.App/ResourceDictionaries/PathIcons.xaml

- Fixed high contrast support
**Validation**
1. Enable one of the high contrast themes in Windows
2. Confirm the icons display properly

Fix: Fixed support for High Contrast themes

---

src/Files.App/App.xaml.cs
src/Files.App/Views/SplashScreenPage.xaml.cs

This PR modifies the splash screen loading wait to use TaskCompletionSource instead of looping. @hishitetsu what do you think?
**Validation**

Code Quality: Use TaskCompletionSource for splash screen loading

---

src/Files.App/Helpers/UI/UIHelpers.cs
src/Files.App/UserControls/SidebarControl.xaml.cs
src/Files.App/UserControls/Widgets/DrivesWidget.xaml.cs
src/Files.App/Utils/Storage/Helpers/DriveHelpers.cs
src/Files.App/ViewModels/UserControls/ToolbarViewModel.cs

Fix: Fixed issue where the wrong notification was displayed when opening an optical drive tray

---

src/Files.App/Data/Items/DriveItem.cs
src/Files.App/Utils/Shell/Win32API.cs
src/Files.App/Views/Properties/GeneralPage.xaml.cs

Closes #6154 
**Validation**
1. Network drive letters no longer appear in duplicate.
2. Both regular and network drives can be renamed.

Feature: Added support for renaming network drives

---

src/Files.App/Data/Models/ItemViewModel.cs

LINQ operations are not thread-safe, so I added `ToList()` before each LINQ operations.
Related to #12617 
Related to #12949  
**Validation**

Code Quality: Copy collections before LINQ operations in ItemViewModel

---

src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml
src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs

- Updated icons in the Tag column in the Details layout
- Added background color when hovering over a tag
- Removed the border color
**Validation**
1. Enable the Details layout
2. Apply a tag to a file
3. Hover over the tag in the tag column
4. Confirm it matches the expect design
5. Click the icon to remove the tag and confirm it works as expected

Feature: Updated icons in the Tag column in the Details layout

---

src/Files.App/App.xaml.cs
src/Files.App/Dialogs/AddItemDialog.xaml.cs
src/Files.App/Helpers/MenuFlyout/ContextFlyoutItemHelper.cs
src/Files.App/Services/AddItemService.cs
src/Files.App/UserControls/InnerNavigationToolbar.xaml.cs
src/Files.Core/Services/IAddItemService.cs
src/Files.Core/ViewModels/Dialogs/AddItemDialog/AddItemDialogViewModel.cs

Closes #13015 
**Validation**
If you right-click immediately after launching the app, you may notice that the "New" submenu lacks some item, but anyway no crash happens.

Fix: Fixed freeze that occurred when right-clicking immediately after launching the app

---

src/Files.App/Data/Items/NavigationBarSuggestionItem.cs
src/Files.App/UserControls/AddressToolbar.xaml
src/Files.App/ViewModels/UserControls/ToolbarViewModel.cs

Related to #12977 
**Validation**

Feature: Highlight search string in the command palette

---

src/Files.App/UserControls/AddressToolbar.xaml

Fix: Restored the status icon for the ongoing tasks

---

src/Files.App/Data/Models/ColumnsViewModel.cs
src/Files.App/Data/Models/CurrentInstanceViewModel.cs
src/Files.App/Data/Models/DirectoryPropertiesViewModel.cs
src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs

- Closes #12927 
- **I hid the status bar as well for consistency reasons.**
**Validation**

Fix: Fixed an issue where Git columns were incorrectly shown in search results

---

src/Files.App/Data/Commands/HotKey/HotKeyHelpers.cs
src/Files.App/Views/MainPage.xaml.cs

Closes #12053
**Validation**
1. Start renaming an item
2. Try to use any shortcut (you should consider changing some shortcuts to `Shift + Letter` to test deeper)

Feature: Disabled keyboard shortcuts when renaming items

---

src/Files.App/Data/Models/ContextMenuFlyoutItemViewModelBuilder.cs
src/Files.App/Helpers/MenuFlyout/ItemModelListToContextFlyoutHelper.cs

Closes #13055 
When there's more than one shortcut, should the label display all of them?
There's a bug involving `Enter` and I'm working on it (if you hit `Enter`, which is the accelerator for `Open`, it will cut the item, since that's the first button in the menu)
**Validation**
1. Open app
2. Right click on a file / empty space

Feature: Display keyboard shortcuts in the right click menu

---

src/Files.App/Data/Models/ItemViewModel.cs
src/Files.App/Data/Models/SelectedItemsPropertiesViewModel.cs
src/Files.App/UserControls/Pane/PreviewPane.xaml.cs
src/Files.App/ViewModels/Previews/FolderPreviewViewModel.cs
src/Files.App/ViewModels/Properties/Items/BaseProperties.cs
src/Files.App/ViewModels/Properties/Items/FileProperties.cs
src/Files.App/ViewModels/Properties/Items/FileProperty.cs
src/Files.App/ViewModels/Properties/Items/FolderProperties.cs
src/Files.App/ViewModels/Properties/Items/LibraryProperties.cs
src/Files.App/ViewModels/UserControls/PreviewPaneViewModel.cs
src/Files.App/Views/LayoutModes/ColumnViewBase.xaml
src/Files.App/Views/LayoutModes/ColumnViewBase.xaml.cs
src/Files.App/Views/LayoutModes/GridViewBrowser.xaml
src/Files.App/Views/LayoutModes/GridViewBrowser.xaml.cs
src/Files.App/Views/MainPage.xaml
src/Files.App/Views/MainPage.xaml.cs
src/Files.App/Views/Properties/DetailsPage.xaml.cs
src/Files.App/Views/Properties/GeneralPage.xaml.cs
src/Files.App/Views/Shells/BaseShellPage.cs

Closes #13109 
**Validation**
Following date displays will automatically update:
- Date columns in the Details layout
- Tooltips in the Tile, Grid and Column layout (each time a tooltip pops up)
- Date displays in the General properties page
- Date displays in the preview pane
- Date displays in the Details properties page

Feature: Automatically update items when the date changes

---

src/Files.App/Actions/Content/Run/RunAsAdminAction.cs
src/Files.App/Actions/Content/Run/RunAsAnotherUserAction.cs

Closes #12457 
**Validation**
1. Open app
2. Right click a shortcut to an executable
3. Try `Run as administrator` and `Run as a different user`
4. Right click a shortcut to file/folder
5. Check that `Run as administrator` and `Run as a different user` are not visible

Feature: Added support for opening shortcut files as another user

---

src/Files.App/Data/Models/ItemViewModel.cs

Fix: Fixed an issue where the file area would sometimes lose focus when opening a folder

---

src/Files.App/Views/LayoutModes/ColumnViewBrowser.xaml.cs
src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs
src/Files.App/Views/Shells/ColumnShellPage.xaml.cs

Closes #9390
**Layout**
- Grid/Tiles -> Already implemented
- Details -> Implemented in this PR
- Columns ->Implemented in this PR
**Other fixes**
- `Open file location` was not selecting any item in columns layout
**Validation**
1. Open app
2. Right click a shortcut
3. Click on `Open item location`

Feature: Scroll to the selected file when using "Open file location"

---

src/Files.App/Actions/Content/Install/InstallFontAction.cs
src/Files.App/Actions/Content/Run/RunWithPowershellAction.cs
src/Files.App/Actions/FileSystem/FormatDriveAction.cs
src/Files.App/Actions/Open/OpenInVSAction.cs
src/Files.App/Actions/Open/OpenInVSCodeAction.cs
src/Files.App/Helpers/MenuFlyout/ShellContextMenuHelper.cs
src/Files.App/Utils/Shell/LaunchHelper.cs
src/Files.App/Utils/Shell/Win32API.cs
src/Files.App/ViewModels/Settings/AdvancedViewModel.cs

Closes #12474 
**Validation**
**Changes**
Created RunPowershellCommandAsync method which uses async/await to wait for the powershell command to complete.
I replaced the non async method wit the async method in all places where i knew how to test it. In 5 places the non async method is still used.
**Steps used to test the changed - noticeable freezes**
- Install Font
- Select multiple *.ttf files
- Install them with the Install button from the command bar or menu flyout
- Run With Powershell
- Select a powershell script
- Execute it with the button from the command bar
- Set Files as the default file manager
- (There was a noticeable freeze on the toggle button, animation is now smooth)
- Open Settings > Advanced
- Toggle ‘Set …

Fix: Fixed an issue were installing a font would freeze the app

---

src/Files.App/Views/LayoutModes/ColumnViewBase.xaml

Closes #12398...
**Validation**
1. Enable compact spacing
2. Switch to the columns layout
3. Confirm items have the correct vertical alignment

Fix: Fixed compact spacing alignment in the Column Layout

---

src/Files.App/App.xaml
src/Files.App/Services/ResourcesService.cs
src/Files.App/UserControls/Widgets/FileTagsWidget.xaml
src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml
src/Files.App/Views/LayoutModes/ColumnViewBase.xaml
src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml
src/Files.App/Views/Properties/SecurityAdvancedPage.xaml
src/Files.App/Views/Properties/SecurityPage.xaml

Closes #12012...
**Validation**
1. Enable compact spacing
2. Confirm there is no space between items in the details layout

Feature: Removed margin when using the Compact Spacing option

---

src/Files.App/Helpers/MenuFlyout/ContextFlyoutItemHelper.cs
src/Files.App/Helpers/MenuFlyout/ShellContextMenuHelper.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/UserControls/SidebarControl.xaml.cs
src/Files.App/UserControls/Widgets/DrivesWidget.xaml.cs
src/Files.App/Views/LayoutModes/BaseLayout.cs

Closes #11303 
**Moved options**
- Turn on BitLocker
- Manage BitLocker
**Validation**
1. Open app
2. Right click on a local drive (Home, Sidebar or root folder)
3. See that BitLocker options are visible in the main menu
4. Right click a cloud drive (e.g. Google Drive)
5. See that BitLocker options are not visible

Feature: Show BitLocker options in main menu for drives

---

src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml
src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs

Closes #12523 
**Validation**
1. Open a folder using `DetailsLayout`
2. Scroll down
3. Click on an empty space

Fix: Fixed an issue where clicking an empty space would scroll to the top of the file list

---

src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs

Related #13157
**Validation**
1. Open a folder using `Details Layout`
2. Click on the path bar or searchbox

Code Quality: Fixed issue with clicking search box

---

src/Files.App/ViewModels/Properties/MainPropertiesViewModel.cs

Closes #12277 
**Validation**
1. Open a properties window.
2. Click Security.
3. Click Advanced permissions.
4. Click the back button.
5. Click General.
6. Click Security.
7. The security page will be displayed properly.

Fix: Fixed issue where the back button in the Properties window wasn't working properly

---

src/Files.App/Data/Items/LocationItem.cs
src/Files.App/Data/Models/SidebarPinnedModel.cs

Closes #13192 
**Validation**
1. Deleting one or multiple files does not crash the app
2. Restoring a file from the recycle bin does not crash the app
3. Permanently deleting a file from the recycle bin does no crash the app
4. Deleting/Restoring a file updates the Tooltip of the Sidebar item

Fix: Fixed crash that would occur when deleting or restoring files

---

src/Files.App/Services/FileTagsService.cs
src/Files.App/Utils/Storage/Search/FolderSearch.cs

Closes #13193 
**Validation**
1. Deleted items are no longer displayed in the tags widget.
2. If you press `View more` buttons or `Tags` sidebar items, you will notice deleted items are no longer displayed in tag search results.

Fix: Fixed issue where deleted items were displayed in tag search results

---

src/Files.App/Helpers/Interop/InteropHelpers.cs
src/Files.App/MainWindow.xaml.cs

Closes #10767...
**Validation**
1. Toggle full screen mode
2. Confirmed taskbar is show when hovering the cursor at the bottom of the screen 

Fix: Fixed taskbar behavior in full screen mode

---

src/Files.App/Data/Items/ListedItem.cs
src/Files.App/Data/Models/GitItemModel.cs
src/Files.App/Data/Models/ItemViewModel.cs
src/Files.App/Services/Settings/FoldersSettingsService.cs
src/Files.App/Utils/Git/GitHelpers.cs
src/Files.App/Views/LayoutModes/BaseLayout.cs
src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs

Closes #13182 
**Validation**
Git properties will not be loaded in the following cases.
* The layout is other than the details layout.
* All Git columns are hidden in the details layout.
When the above cases are no longer met, Git properties loading will begin.

Feature: Lazy load Git properties for better performance

---

src/Files.App/Utils/Archives/ZipHelpers.cs
src/Files.App/Utils/Storage/StorageItems/ZipStorageFolder.cs

Closes #12672 
**Validation**
The problem occurs if the archive has a directory ending with space.
Here is a sample zip file, an excerpt from the attached one in #12672. This has `Lesson 06 ` (not `Lesson 06`) folder and it causes the problem.
[test.zip](https://github.com/files-community/Files/files/12395166/test.zip)
This archive will now be extracted properly.
This PR also fixes the issue where `Lesson06 ` is listed as a file aside from a folder when browsing inside the archive.

Fix: Fixed issue where some archives wouldn't be extracted properly

---

src/Files.App/Data/Items/DriveItem.cs

Closes #13219...
**Validation**
2. Confirm the network item has the correct icon

Feature: Load network icon instead of a folder icon

---

src/Files.App/App.xaml.cs
src/Files.App/Data/Contexts/Multitasking/MultitaskingContext.cs
src/Files.App/Data/Models/AppModel.cs
src/Files.App/Helpers/UI/UIHelpers.cs
src/Files.App/MainWindow.xaml
src/Files.App/MainWindow.xaml.cs
src/Files.App/Program.cs
src/Files.App/Services/Settings/GeneralSettingsService.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/Utils/Storage/Helpers/FilePropertiesHelpers.cs
src/Files.App/ViewModels/Settings/AdvancedViewModel.cs
src/Files.App/Views/Properties/MainPropertiesPage.xaml.cs
src/Files.App/Views/Settings/AdvancedPage.xaml
src/Files.Core/Services/Settings/IGeneralSettingsService.cs

Closes #12614 
**Validation**
1. Turn on "Leave app running in the background when the window is closed" in Advanced settings
2. Close and restart the app.
3. The app will launch quicker.
**Known Issues**

Feature: Added an option to keep Files running in the background for quicker startup time

---

src/Files.App/App.xaml.cs
src/Files.App/UserControls/Widgets/QuickAccessWidget.xaml
src/Files.App/UserControls/Widgets/QuickAccessWidget.xaml.cs

- This PR improves performance and memory leaks when the quick access widget is displayed multiple times.
**Validation**

Code Quality: Improved quick access widget

---

src/Files.App/Helpers/UI/ThemeHelper.cs
src/Files.App/ViewModels/MainPageViewModel.cs

- This solves the problem of the same event handler being subscribed to multiple times. This may solve a potential issue with the theme.
**Validation**

Fix: Fixed duplicate initialization when resuming

---

src/Files.App/Data/Factories/AppThemeResourcesFactory.cs
src/Files.App/Strings/en-US/Resources.resw

Closes #13256...
**Validation**
1. Open settings to the appearance page
2. Confirm the theme names are displayed correctly

Feature: Localized the theme names

---

src/Files.App/Dialogs/ReleaseNotesDialog.xaml
src/Files.App/Dialogs/ReleaseNotesDialog.xaml.cs
src/Files.App/Files.App.csproj
src/Files.App/Services/DialogService.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/UserControls/AddressToolbar.xaml
src/Files.App/ViewModels/UserControls/ToolbarViewModel.cs
src/Files.Core/ViewModels/Dialogs/ReleaseNotesDialogViewModel.cs

- Replace the What's new teaching tip with a popup
**Validation**
1. Hardcoded `IsReleaseNotesVisible` to true
2. Hard coded the markdown content
3. Opened the popup

Feature: What's new popup

---

src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs

Fix: Fixed issue where textbox for renaming wouldn't disappear after losing focus

---

src/Files.App/UserControls/Widgets/FileTagsWidget.xaml.cs
src/Files.App/UserControls/Widgets/HomePageWidget.cs
src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml.cs
src/Files.App/ViewModels/UserControls/SidebarViewModel.cs
src/Files.App/Views/LayoutModes/BaseLayout.cs

- Somehow, after updating WASDK to 1.4, a context menu would only show primary commands until shell extensions were loaded, so I worked around this issue by splitting the loading process.
**Validation**

Code Quality: Refactored context menu loading for WASDK 1.4

---

src/Files.App/Services/SideloadUpdateService.cs
src/Files.App/Services/UpdateService.cs

This occurs when you ignore Update button, close the app, and reopen it from the cache.
**Validation**

Fix: Fixed an issue where the update button didn't show

---

src/Files.App/UserControls/Settings/SettingsBlockControl.xaml

- Fixes pipeline failing due to a11y issues with the settings dialog
**Validation**

Code Quality: Fixed A11y issues in settings dialog

---

src/Files.App/Services/ImagingService.cs
src/Files.App/UserControls/Widgets/DrivesWidget.xaml.cs
src/Files.App/UserControls/Widgets/QuickAccessWidget.xaml.cs
src/Files.App/Utils/RecentItem/RecentItem.cs
src/Files.App/Utils/Shell/ContextMenu.cs
src/Files.App/Utils/Storage/Helpers/FileThumbnailHelper.cs
src/Files.App/Utils/Storage/Search/FolderSearch.cs
src/Files.App/ViewModels/MainPageViewModel.cs
src/Files.App/ViewModels/Properties/Items/FileProperties.cs
src/Files.App/ViewModels/Properties/Items/FolderProperties.cs

Closes #13218...
**Validation**
1. Open properties window for a folder
2. Confirm the thumbnail doesn't have a black background

Code Quality: UseCurrentScale for properties window

---

src/Files.App/ViewModels/MainPageViewModel.cs

This PR also fixes the issue of tab tooltips not updating in case of dual pane.
Closes #12939 
**Validation**
1. Open the home page.
2. Click a sidebar item (ex: Documents).
3. Quickly click Home on the sidebar.
4. The tab header is no longer displayed with the contents of 2.

Fix: Fixed issue where tab headers sometimes didn't match actual content

---

src/Files.Shared/Helpers/FileExtensionHelpers.cs

.lzh is pure archive file, so it should be browsable.
**Validation**

Code Quality: Support for browsing the contents of .lzh files

---

src/Files.App/Utils/Storage/Helpers/StorageFileExtensions.cs

Closes #13340 
**Validation**
**Note**
The path bar will display the correct location, but will not display its volume label. This is because the drive information has not yet been loaded immediately after startup. I leave it as is because waiting for the drive information to be loaded slows down the page loading.

Fix: Fixed issue where the path bar would display wrong location at app startup

---

src/Files.App/Dialogs/FilesystemOperationDialog.xaml
src/Files.App/Dialogs/FilesystemOperationDialog.xaml.cs

Closes #9057
**Details**
Please, note that the former line 121 (`conflictItem.CustomName = string.Empty;`) was removed from `EndRename()` as it was causing a crash.
Steps to reproduce (Stable or Preview):
- Reach the `Conflicts dialog`
- Click on an item to rename it and then click away
- Repeat until eventually Files crashes (the number of required iterations depends on the depth of the destination. e.g.  `C:\Users\USERNAME\Documents\files.txt` should take 5 cycles)
**Validation**
1. Copy & paste some files that require the `Conflict dialog`
2. Click on an item name
3. Use `Up` & `Down` arrows to move between the names
4. Mark some items with `Skip`
5. Check that you don't land on them using arrows …

Feature: Added support to switch between items using arrow keys in the conflicts dialog

---

src/Files.App/Data/Models/ItemViewModel.cs
src/Files.App/Utils/Git/GitHelpers.cs

This PR fixes an issue where app would crash with "stack overflow exception" when trying to detect Git repo in FTP folders.
**Validation**

Fix: Fixed crash in FTP folders

---

README.md
src/Files.App (Package)/Files.Package.wapproj

Code Quality: Bumped the version of WASDK in the app package

---

src/Files.App/Actions/Git/GitInitAction.cs
src/Files.App/Helpers/Dialog/DynamicDialogFactory.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/Utils/Git/GitHelpers.cs

Closes #13280 
**Notes**
There's an issue with WSL: trying to initialize a git repository will throw an exception (path not owned by current user), still the repo will be initialized. Should we notify the user about this "error"?
**Validation**
1. Try to digit `>Init` in the search bar of a drive root
2. Try to initialize a git repository in WSL

Fix: Display error when failing to initialize folder as git repo

---

src/Files.App/Data/Models/SelectedItemsPropertiesViewModel.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/ViewModels/Properties/Items/FileProperties.cs
src/Files.App/Views/Properties/GeneralPage.xaml
src/Files.App/Views/Properties/GeneralPage.xaml.cs

Feature: Added support for unblocking downloaded files

---

src/Files.App/Views/LayoutModes/BaseLayout.cs

This workaround is for WASDK 1.4, but it seems to be no longer necessary.
> Fixed an issue impacting context menu performance.
(from the release notes)
**Validation**

Code Quality: Deleted workaround for context menu loading

---

src/Files.App/UserControls/InnerNavigationToolbar.xaml.cs

Fix: Fixed an issue where new files were sometimes created in the wrong directory

---

src/Files.App/UserControls/AddressToolbar.xaml

**Validation**
1. Make window smaller
2. Confirm the mini search button is shown

Fix: Fixed the mini search button visual state

---

src/Files.App/Helpers/Navigation/NavigationHelpers.cs
src/Files.Shared/Helpers/FileExtensionHelpers.cs

Closes #13517...
**Validation**
1. Open screen saver file
2. Confirm the screen saver is opened in full screen mode

Fix: Fixed an issue with opening screen saver files

---

src/Files.App/UserControls/SideBar/SideBarView.xaml.cs

Closes #13548...
**Validation**
2. Use tab key until sidebar resizer is selected
3. Confirm using the tab & tab + shift key combination moves the focus off the sidebar

Fix: Fixed issue where tab selection got stuck on the sidebar

---

src/Files.App/UserControls/TabBar/TabBar.xaml.cs

Closes #11081...
**Validation**
1. Create multiple tabs
2. Drag a tab a few pixels and confirm it doesn't create a new window (you can also test with the stable version to see the previous behavior)
3. Drag a tab a little further and confirm that it creates a new window

Fix: Fixed an issue where slightly dragging a tab would create a new window

---

src/Files.App/Helpers/Interop/InteropHelpers.cs
src/Files.App/MainWindow.xaml.cs

Closes #10844...
**Validation**
1. Open app and set as the default file manager
2. Minimize window or switch focus to another window
3. Use the `open file location` option in another app and see if Files is brought to the foreground

Fix: Switch focus to Files when activating window

---

src/Files.App/Services/QuickAccessService.cs
src/Files.App/UserControls/Widgets/QuickAccessWidget.xaml.cs

Fix: Fixed crash when reordering sidebar favorites

---

src/Files.App/Views/LayoutModes/ColumnViewBase.xaml.cs

Closes #13418
**Validation**
https://github.com/files-community/Files/assets/59918974/6d086769-1fe8-4e15-a6d4-b3fb88821369

Fix: Don't open subfolders when using selection rectangle in column view

---

src/Files.App/MainWindow.xaml.cs
src/Files.App/Views/SplashScreenPage.xaml
src/Files.App/Views/SplashScreenPage.xaml.cs

During this few months tiral of initial splash screen, user have never complained about it. However, we noticed the blurry of the image and then @mdtauk suggested great idea to add the build branch name under the splash screen image.
_N/A_
2. See the splash screen, which will be shown in second you launched and only for few moments
[^2]: If you removed any en-US string resources, make sure that there are no references of those resources. When you add a new en-US string resources, do not make any changes on other languages' resources; [Crowdin](https://crowdin.com/project/files-app) will do that, …

Feature: Added app name to the splash screen

---

README.md

This PR removes a weird empty link in the README
**Validation**

GitHub: Remove empty link from readme

---

src/Files.App/Strings/en-US/Resources.resw
src/Files.App/Views/Settings/AdvancedPage.xaml

Closes #7679...
**Validation**
1. Open Files settings
2. Enable the option to open Files on Windows Startup
3. Open the startup settings in Windows (via the settings app)
4. Turn off the startup option for Files
5. Go back to Files and confirm there is an info bar explaining why the setting is disabled in Files

Fix: Fixed issue where Open on Startup didn't display a message when disabled

---

src/Files.App/Utils/StatusCenter/StatusCenterHelper.cs

Closes #13590...
**Validation**
1. Open any folder
2. Drag image from the browser into the folder
3. Confirm the image is copied without crashing the app

Fix: Fixed crash that would occur when dragging an image from the browser

---

src/Files.App/Data/Items/FileTagItem.cs
src/Files.App/UserControls/SideBar/ISideBarViewModel.cs
src/Files.App/UserControls/SideBar/SideBarItem.cs
src/Files.App/UserControls/SideBar/SideBarView.xaml.cs
src/Files.App/UserControls/SideBar/SidebarItemAutomationPeer.cs
src/Files.App/ViewModels/UserControls/SidebarViewModel.cs

Closes #13410
**Validation**
1. Middle click sidebar item
2. Confirm it opens in a new tab
3. Hold down `ctrl` key and click sidebar item
4. Confirm it opens in a new tab

Feature: Middle click sidebar item to open new tab

---

src/Files.App/UserControls/TabBar/TabBar.xaml.cs

Closes #10234...
**Validation**
1. Open multiple tabs
2. Drag tab outside the window and release mouse
3. Confirm tab was teared off
4. Drag tab outside window and press escape
5. Confirm the drag operation is canceled

Feature: Added support for canceling tab tear off

---

src/Files.App/Utils/Shell/Win32API.cs
src/Files.App/Utils/Storage/Operations/FileOperationsHelpers.cs

I cannot reproduce the crash myself, but it seems to occur in environments where explorer.exe is not running as a shell (e.g. RemoteApp).
Closes #13664
**Validation**

Fix: Fixed crash that would occur at the start of a file operation if Explorer wasn't running

---

src/Files.App/UserControls/StatusBarControl.xaml

- [ X ] Were these changes approved in an issue or discussion with the project maintainers? In order to prevent extra work, feature requests and changes to the codebase must be approved before the pull request will be reviewed. This prevents extra work for the contributors and maintainers.
Closes #13641
**Validation**
- [ X ] Did you build the app and test your changes?

Fix: Added tooltip when hovering over "Open in VS Code"

---

src/Files.App/Views/LayoutModes/ColumnViewBrowser.xaml.cs

https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/103315946u/overview
**Validation**

Fix: Fixed NullReferenceException with SetSelectedPathOrNavigate

---

src/Files.App/ViewModels/Properties/Items/FileProperties.cs

This does not solve the issue of the audio file not showing the play button, but it does solve the crashing issue.
Related to #13674 
**Validation**

Fix: Fixed crash that would occur when opening a large bitrate audio file

---

src/Files.App/Utils/Shell/Win32API.cs

https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/2815342931u/overview
```
System.Diagnostics
Process.StartWithCreateProcess (ProcessStartInfo startInfo)
System.ComponentModel.Win32Exception: An error occurred trying to start process 'powershell.exe' with working directory 'C:\Windows\system32'. Access is denied.
```

Fix: Fixed Win32Exception in SetAsDefaultExplorerAsync

---

src/Files.App/ViewModels/Properties/Items/FileProperty.cs

Closes (https://github.com/files-community/Files/issues/13663)
**Validation**
1. Tested code snippet in external test project to ensure System.FormatException was handled

Fix: Handle format exception raised by Convert.ToInt32

---

src/Files.App/Actions/FileSystem/CopyPathAction.cs

Fixed crash with copy path action if no items are selected
**Validation**
1. Use ctrl + shift + c shortcut when no items are selected and confirm app doesn't crash

Fix: Disable copy path when no items are selected

---

src/Files.App/ViewModels/UserControls/PreviewPaneViewModel.cs

**Validation**
1. Select folder
2. Toggle details pane
3. Confirm folder preview is shown

Fix: Fixed issue with viewing folder details

---

src/Files.App/Utils/Storage/Helpers/FilePropertiesHelpers.cs

https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/1504308570u/overview
```
Files.App.Utils.Storage
FilePropertiesHelpers.OpenPropertiesWindow (IShellPage associatedInstance)
Files.App.Actions
OpenPropertiesAction.ExecuteAsync ()
```

Fix: Fixed NullReferenceException with OpenPropertiesWindow

---

src/Files.App/Views/LayoutModes/ColumnViewBase.xaml.cs

https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/634160407u/overview
```
Files.App.Views.LayoutModes
ColumnViewBase.EndRename (TextBox textBox)
Files.App.Views.LayoutModes
StandardViewBase.CommitRenameAsync (TextBox textBox)
Files.App.Views.LayoutModes
StandardViewBase.RenameTextBox_LostFocus (Object sender, RoutedEventArgs e)
System.Threading.Tasks.Task
<>c.<ThrowAsync>b__128_0 (Object state)
```

Fix: Fixed NullReferenceException with ColumnViewBase.EndRename

---

src/Files.App/Actions/Navigation/OpenDirectoryInNewTabAction.cs

https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/1495782651u/overview
```
Files.App.Actions
OpenDirectoryInNewTabAction.ExecuteAsync ()
Files.App.ViewModels.UserControls
ToolbarViewModel.CheckPathInputAsync (String currentInput, String currentSelectedPath, IShellPage shellPage)
Files.App.Views.Shells
BaseShellPage.NavigationToolbar_QuerySubmitted (Object sender, ToolbarQuerySubmittedEventArgs e)
System.Threading.Tasks.Task
<>c.<ThrowAsync>b__128_0 (Object state)
```

Fix: Fixed NullReferenceException in OpenDirectoryInNewTabAction

---

README.md

This PR fixes the documentation's shield badge's link, which got messed up in #13621.
**Validation**
1. Checked the README's link in my fork

GitHub: Fixed broken documentation link in README

---

src/Files.App/Data/Items/ListedItem.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/ViewModels/Properties/HashesViewModel.cs
src/Files.App/ViewModels/Properties/Items/CombinedProperties.cs
src/Files.App/ViewModels/Properties/Items/FileProperties.cs
src/Files.App/ViewModels/Properties/Items/FolderProperties.cs

Closes #13006
Closes #13593
**Validation**
1. Open properties for a non OneDrive file/folder and confirm "Size on disk" is calculated
2. Open properties for a downloaded OneDrive file/folder and confirm "Size on disk" is calculated
3. Open properties for a non downloaded OneDrive file/folder and confirm "Size on disk" isn't calculated
4. Open hash page for online file and confirm the file isn't downloaded
5. Open hash page for offline file and confirm the hash is displayed

Fix: Fixed issue where opening properties would download OneDrive files

---

src/Files.App/Views/LayoutModes/ColumnViewBase.xaml
src/Files.App/Views/LayoutModes/GridViewBrowser.xaml

Closes #13796...
**Validation**
1. Rename file in the details layout & tiles layout and confirm the textbox background isn't transparent

Fix: Fixed TextBox background when renaming items

---

src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml

Reopening since this should remove the gap and still provide functionality for context menu/selection rectangle in the space to the left of the file list to work properly.
fixed https://github.com/files-community/Files/issues/13819

Fix: Removed gap between the divider line and details layout browser header

---

src/Files.App/Actions/FileSystem/OpenItemAction.cs
src/Files.App/Views/LayoutModes/BaseLayout.cs
src/Files.App/Views/LayoutModes/ColumnViewBase.xaml.cs
src/Files.App/Views/LayoutModes/ColumnViewBrowser.xaml.cs
src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs
src/Files.App/Views/LayoutModes/GridViewBrowser.xaml.cs

Switched `NavigationHelpers.OpenSelectedItemsAsync` to `Commands.OpenItem.ExecuteAsync` to take advantage of the checks in the action. It also makes the code a little more readable and gives us the confidence that the action will handle all the logic.

Code Quality: Use OpenItem action for better reliability

---

src/Files.App/Actions/Content/Background/SetAsLockscreenBackgroundAction.cs
src/Files.App/Actions/Content/Background/SetAsWallpaperBackgroundAction.cs
src/Files.App/ViewModels/UserControls/SidebarViewModel.cs
src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs
src/Files.App/Views/LayoutModes/GridViewBrowser.xaml.cs
src/Files.App/Views/LayoutModes/StandardLayoutMode.cs
src/Files.App/Views/MainPage.xaml.cs
src/Files.App/Views/Settings/AboutPage.xaml.cs
src/Files.App/Views/Shells/BaseShellPage.cs

Code Quality: Fix async warnings

---

src/Files.App/Actions/FileSystem/AddItemAction.cs

Closes #13787
**Validation**
2. Follow steps to reproduce issue
3. Verify issue no longer persists.
The issue was the  
```viewModel.ResultType.ItemType```  in the ```AddItemDIalog``` was not being reset to the default ```ResultType.ItemType.Cancel``` and was remaining whatever type was last selected before pressing cancel. If there is another place I should reset it to cancel please let me know and I will revise it.

Fixed: Fixed issue where the new item dialog cannot be canceled

---

src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml
src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs

Closes #13789 
**Validation**
1. Open app
2. Open a folder
3. Double click open space
4. Confirm that it navigates to parent folder
5. Double click column header
6. Confirm that only ascending/descending order is being changed

Fix: Fixed issue where double-clicking on column headers would navigate up

---

src/Files.App/Data/EventArguments/PaneNavigationArguments.cs
src/Files.App/ViewModels/MainPageViewModel.cs

Fix: Fixed issue where tab icons and labels are sometimes not displayed at app launch

---

src/Files.App/Actions/Content/Archives/Compress/CompressIntoArchiveAction.cs
src/Files.App/Services/UpdateService.cs
src/Files.App/Utils/Archives/DecompressHelper.cs
src/Files.App/Utils/RecycleBin/RecycleBinHelpers.cs
src/Files.App/Utils/Storage/Operations/FilesystemOperations.cs
src/Files.App/Views/MainPage.xaml.cs

- Fix potential crashes that could occur if the root isn't set

Fix: Always set content dialog root

---

src/Files.App/Data/Models/FolderSettingsViewModel.cs

Fix: Fixed issue where changing column widths would set the width of hidden columns to zero

---

src/Files.App/ViewModels/MainPageViewModel.cs

I don't know why an exception is thrown, but since this process only updates the window title, I ignore the exception when it is thrown.
https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/2912768630u/overview
**Validation**

Fix: Fixed NullReferenceException in MainPageViewModel.UpdateInstancePropertiesAsync

---

src/Files.App/Strings/en-US/Resources.resw
src/Files.App/Utils/RecycleBin/RecycleBinHelpers.cs

Fixes `System.Runtime.InteropServices.COMException: Error HRESULT E_FAIL has been returned from a call to a COM component`

Fix: Fixed potential crash when restoring from Recycle Bin

---

src/Files.App/Views/LayoutModes/BaseLayout.cs

- Fixed com exception when updating preview pane selection
`The WinUI Desktop Window object has already been closed`

Fix: Fixed potential COMException when updating preview pane selection

---

src/Files.App/Strings/en-US/Resources.resw
src/Files.App/Utils/Global/WallpaperHelpers.cs

- Fixed com exception when setting wallpaper
`System.Runtime.InteropServices.COMException: Retrieving the COM class factory for component with CLSID {C2CF3110-460E-4FC1-B9D0-8A1C0C9CC4BD} failed`

Fix: Fixed potential COMException when setting the wallpaper

---

src/Files.App/Utils/Shell/LaunchHelper.cs

Fixed `System.IO.IOException: The process cannot access the file 'C:\Users\USER\AppData\Local\Temp\CompatibilityTroubleshooterAnswerFile.xml' because it is being used by another process.`

Fix: Fixed IO Error in RunCompatibilityTroubleshooterAsync

---

src/Files.App/ViewModels/LayoutModes/BaseLayoutViewModel.cs

I don't believe it needs `deferral` in the first place since there are no events that should wait for the completion of the drop event.
Closes #13822 
**Validation**

Fix: Fixed COMException in BaseLayoutViewModel.DropAsync

---

src/Files.App/Views/PaneHolderPage.xaml.cs

- Fixes `System.Runtime.InteropServices.COMException: The operation identifier is not valid. The WinUI Desktop Window object has already been closed`

Fix: Fixed crash when calculating window bounds

---

src/Files.App/Data/Models/FolderSettingsViewModel.cs
src/Files.App/ViewModels/Settings/AboutViewModel.cs
src/Files.App/ViewModels/Settings/AdvancedViewModel.cs

Fix: Fixed warnings in settings

---

src/Files.App/ViewModels/UserControls/InfoPaneViewModel.cs

Closes #13817...
**Validation**
1. Select media file in FTP location
2. Confirm the media preview isn't shown

Fix: Disabled media preview for FTP

---

src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs

- Fixed null warnings in the details layout

Fix: Fixed null warnings in the details layout

---

src/Files.App/UserControls/AddressToolbar.xaml.cs
src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs
src/Files.App/Views/LayoutModes/GridViewBrowser.xaml.cs
src/Files.App/Views/LayoutModes/StandardLayoutMode.cs

- Fixed xamlRoot in GetFocusedElement

Fix: Fixed xamlRoot in GetFocusedElement

---

src/Files.App/UserControls/PathBreadcrumb.xaml
src/Files.App/UserControls/PathBreadcrumb.xaml.cs
src/Files.App/Views/Shells/BaseShellPage.cs

Closes #7587...
**Validation**
1. Confirm menu items are still displayed
2. Confirm touch target is bigger

Feature: Improved touch target for breadcrumbs

---

src/Files.App/Strings/en-US/Resources.resw
src/Files.App/ViewModels/Properties/HashesViewModel.cs

Closes #13564...
**Validation**
1. Open office document
2. Right click and open properties for that file
3. Switch to the hashes page and confirm it explains why the hashes can't be calculated

Feature: Display error when failing to calculate the hash of open files

---

src/Files.App/ResourceDictionaries/PathIcons.xaml
src/Files.App/Utils/Cloud/CloudDriveSyncStatusUI.cs

Closes #13991...
**Validation**
1. Confirm the "always keep on device" status is displaying correctly

Feature: Indicate "Always keep on device" status

---

src/Files.App/Data/Models/AppModel.cs
src/Files.App/Services/RemovableDrivesService.cs
src/Files.App/Utils/Cloud/Detector/GoogleDriveCloudDetector.cs
src/Files.Core/Services/Settings/IAppSettingsService.cs

Closes #6795...
**Validation**
1. Confirm Google Drive is only displayed under Cloud Drives

Feature: Only show Google Drive under cloud drives

---

.github/workflows/ci.yml
src/Files.App/App.xaml.cs

Previous check suite was ugly looking. So fixed.
_N/A_
_N/A_
Before:
After:

GitHub: Force to run tests regardless of the build job outcome

---

src/Files.App/Data/Models/AppModel.cs
src/Files.App/Utils/Storage/Helpers/FilePropertiesHelpers.cs
src/Files.App/Views/MainPage.xaml.cs
src/Files.App/Views/Properties/DetailsPage.xaml.cs
src/Files.App/Views/Properties/GeneralPage.xaml.cs
src/Files.App/Views/Shells/BaseShellPage.cs

Closes #13725 
**Validation**
1. Set the interval of `_updateDateDisplayTimer` to 0.1sec to increase the frequency of COMException.
2. Open Files, display the date, and close the window.
3. It crashes quite often without the fix, but it never crashes with the fix.

Fix: Fixed COMException in UpdateDateDisplayTimer_Tick

---

src/Files.App/Actions/Navigation/DuplicateCurrentTabAction.cs
src/Files.App/Actions/Navigation/DuplicateSelectedTabAction.cs
src/Files.App/Actions/Navigation/NewTabAction.cs
src/Files.App/Actions/Navigation/OpenDirectoryInNewTabAction.cs
src/Files.App/App.xaml.cs
src/Files.App/Helpers/Navigation/NavigationHelpers.cs
src/Files.App/MainWindow.xaml.cs
src/Files.App/UserControls/TabBar/BaseTabBar.cs
src/Files.App/UserControls/TabBar/TabBar.xaml.cs
src/Files.App/UserControls/TabBar/TabBarItem.cs
src/Files.App/ViewModels/MainPageViewModel.cs
src/Files.App/ViewModels/UserControls/ToolbarViewModel.cs
src/Files.App/Views/MainPage.xaml.cs

As the title
2. Add a new tab
3. Go to Home
4. Go to a folder
5. See tab info is being changed accordingly.
_N/A_
_N/A_

Code Quality: Moved static methods from MainPageViewModel to NavigationHelpers

---

src/Files.App/App.xaml
src/Files.App/Helpers/MenuFlyout/ItemModelListToContextFlyoutHelper.cs
src/Files.App/ResourceDictionaries/MenuFlyoutSubItemWithImageStyle.xaml
src/Files.App/UserControls/Menus/MenuFlyoutSubItemCustomProperties.cs

Fix: Fixed issue where icons were not displayed on submenus of shell extensions

---

src/Files.App/Utils/RecentItem/RecentItem.cs

Closes #11517 
**Validation**
1. Open app 
2. In Home page scroll to an archive in Recent files.
3. Open archive.
Archive in Recent files
Archive opened from Recent files

Feature: Open archives from the home page in the same tab

---

src/Files.App/Data/Models/AppModel.cs
src/Files.App/Services/RemovableDrivesService.cs
src/Files.App/Utils/Cloud/CloudDrivesDetector.cs

Closes #14081...
**Validation**

Feature: Hide pCloud from drives list

---

src/Files.App/Dialogs/SettingsDialog.xaml
src/Files.App/Dialogs/SettingsDialog.xaml.cs
src/Files.App/Files.App.csproj
src/Files.App/Helpers/CredentialsHelpers.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/Utils/Git/GitHelpers.cs
src/Files.App/ViewModels/Settings/GitViewModel.cs
src/Files.App/Views/Settings/GitPage.xaml
src/Files.App/Views/Settings/GitPage.xaml.cs
tests/Files.InteractionTests/Tests/SettingsTests.cs

Closes #13049...
**Validation**
1. Push commit from the stable version of Files to grant GitHub access
2. Checkout this branch and navigate to settings, there should be a new settings page for "Git".
3. Confirm the logout button removes the credentials and that the login button becomes visible
4. Confirm the login button opens the authentication prompt

Feature: Added support for logging in/out of GitHub

---

src/Files.App/Helpers/Environment/SoftwareHelpers.cs
src/Files.App/Helpers/Navigation/NavigationHelpers.cs
src/Files.App/Utils/Storage/Operations/FilesystemHelpers.cs
src/Files.App/Views/Layouts/BaseLayoutPage.cs

…also checks to see if python is installed on system before allowing the drop like in File Explorer.
*removed redundant code*
Closes #14033 
**Validation**
2. Create 4 types of files: test.py, test.bat, test.cmd, test.exe. Each created to test incoming arguments list.
Tested dragging and dropping multiple files to each of them to verify changes:
Also validated that when python is not installed, the user cannot drop files onto the python file.

Fix: Fixed an issue with dropping multiple items onto executable files

---

src/Files.App/UserControls/Pane/InfoPane.xaml
src/Files.App/UserControls/Pane/InfoPane.xaml.cs

Closes #13065...
**Validation**
1. Display info pane
2. Restart app and confirm the info pane displays the details for the current folder

Fix: Fixed info pane state when resuming

---

src/Files.App/Converters/MultiBooleanConverter.cs
src/Files.App/Data/Items/BranchItem.cs
src/Files.App/Data/Models/DirectoryPropertiesViewModel.cs
src/Files.App/Helpers/Dialog/DynamicDialogFactory.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/UserControls/StatusBarControl.xaml
src/Files.App/UserControls/StatusBarControl.xaml.cs
src/Files.App/Utils/Git/GitHelpers.cs
src/Files.App/Views/Shells/BaseShellPage.cs

Closes #13592 
**Important**
- Backup your repo before testing this feature
- Check this PR doesn't affect performance in Git folders
- I had to revert a change made in #13608 because `Ahead / Behind` wouldn't be update after `Pull`s (see `BaseShellPage.cs`)
**Validation**
1. Open a git repo
2. Click on the branch name in the status bar
3. Click on `Delete` to delete a local branch
4. Click on `Cancel` and make sure the branch is still there
5. Repeat but click on `Continue` and check that the branch is deleted

Feature: Allow deleting of local Git branches

---

src/Files.App/Actions/Content/Archives/Decompress/DecompressArchive.cs
src/Files.App/Utils/Archives/DecompressHelper.cs

Fix: Fixed some null ref warnings in decompress helper

---

src/Files.App/UserControls/Pane/InfoPane.xaml
src/Files.App/UserControls/Pane/InfoPane.xaml.cs
src/Files.App/ViewModels/UserControls/InfoPaneViewModel.cs
src/Files.App/Views/Layouts/BaseLayoutPage.cs
src/Files.App/Views/Layouts/ColumnsLayoutPage.xaml.cs
src/Files.App/Views/Layouts/IBaseLayoutPage.cs
src/Files.App/Views/MainPage.xaml.cs
src/Files.App/Views/PaneHolderPage.xaml.cs

Closes #12877...
**Validation**
1. Opened details pane and confirmed it displayed the details/preview for the selected item
2. Also confirmed it showed the info for the current folder when no items were selected
3. Switched tabs and confirmed the pane updated based on the selected tab
4. Switched focus between right & left pane and confirmed the info pane updated
5. Restarted app with the pane enabled & continue where you left off, and confirmed it displayed the correct preview
6. Confirmed the pane is only updated when it's enabled (confirmed by placing a breakpoint)

Code Quality: Refactor InfoPane selection

---

src/Files.App/Actions/Content/Install/InstallFontAction.cs
src/Files.App/Utils/Shell/Win32API.cs

Closes #13922...
**Validation**

Fix: Fixed crash that could occur when installing a lot of font files

---

src/Files.App/Data/Contexts/ContentPage/ContentPageContext.cs
src/Files.App/Data/Contexts/Page/PageContext.cs
src/Files.App/Views/MainPage.xaml.cs

Code Quality: Avoid redundant OnPropertyChanged calls in ContentPageContext

---

src/Files.App/UserControls/TabBar/TabBar.xaml
src/Files.App/UserControls/TabBar/TabBar.xaml.cs

Babies first pull request. So forgive me if I accidently something.
Closes [Feature: Cycle tabs via mouse scrolling #13550](https://github.com/files-community/Files/issues/13550)
**Validation**
2. Create multiple tabs.
3. Hover pointer over tab and use mousewheel to cycle tabs.
4. Use mousewheel everywhere else to make sure no other mousewheel behaviour is changed.

Feature: Added support for cycling tabs via mouse scrolling

---

src/Files.App/Dialogs/CreateArchiveDialog.xaml.cs
src/Files.App/Utils/Archives/CompressArchiveModel.cs
src/Files.Core/Data/Enums/ArchiveSplittingSizes.cs

Closes #14132...
**Validation**
1. Select some files and select the compress option
2. Change the splitting size to 2gb and confirm it works as intended

Feature: Added 2gb splitting size for archives

---

src/Files.App/Utils/Shell/Win32API.cs

```
Win32API.CreateTaskbarObject ()
System.IO.FileNotFoundException: Retrieving the COM class factory for component with CLSID {56FDF344-FD6D-11D0-958A-006097C9A090} failed due to the following error: 8007007e
```

Fix: Fixed crash when creating taskbar progress

---

src/Files.App/Actions/Content/Archives/Decompress/DecompressArchiveHereSmart.cs
src/Files.App/Data/Commands/CommandCodes.cs
src/Files.App/Data/Commands/Manager/CommandManager.cs
src/Files.App/Data/Commands/Manager/ICommandManager.cs
src/Files.App/Helpers/MenuFlyout/ContextFlyoutItemHelper.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/UserControls/InnerNavigationToolbar.xaml
src/Files.App/Utils/Archives/DecompressHelper.cs

Feature: Added an option for "smart" extract 

---

src/Files.App/ViewModels/MainPageViewModel.cs
src/Files.App/ViewModels/UserControls/InfoPaneViewModel.cs
src/Files.App/Views/MainPage.xaml
src/Files.App/Views/MainPage.xaml.cs

Fix: Fixed issue where resizing window would reload preview

---

src/Files.App/Utils/Storage/Helpers/StorageFileExtensions.cs
src/Files.App/ViewModels/UserControls/ToolbarViewModel.cs

Closes #14166 
**Validation**
1. Open app
2. Type the following cases into the toolbar: `~`, `~/`, `~\`
3. They should all reference the same user profile folder. The forward/backslash cases should show files inside
Standalone-tilde support:
Forward-slash with tilde support:
Example with sub-directories:
(Technically, this PR does two things, but it felt awkward without also supporting forward-slash.)

Feature: Recognize Tilde as %USERPROFILE%

---

src/Files.App/Strings/en-US/Resources.resw
src/Files.App/Utils/FileTags/FileTagsHelper.cs

Closes #14194...
**Validation**
1. Apply tag to files on non NTFS drives
**Known issues**
- Prompt will be displayed multiple times when trying to add a tag to multiple items at the same time

Feature: Prompt when applying tag on non NTFS drive

---

src/Files.App/Utils/Storage/Operations/FilesystemHelpers.cs

Closes #14242 
**Validation**
1. Open app
2. Copy an image (for example from google images)
3.  Paste it
4. Now the file name shows the correct date

Fix: Fixed file name when pasting clipboard content

---

src/Files.App/Actions/Display/SortFilesAndFoldersTogetherAction.cs
src/Files.App/Actions/Display/SortFilesFirstAction.cs
src/Files.App/Actions/Display/SortFoldersFirstAction.cs
src/Files.App/Data/Commands/CommandCodes.cs
src/Files.App/Data/Commands/Manager/CommandManager.cs
src/Files.App/Data/Commands/Manager/ICommandManager.cs
src/Files.App/Data/Contexts/DisplayPage/DisplayPageContext.cs
src/Files.App/Data/Contexts/DisplayPage/IDisplayPageContext.cs
src/Files.App/Data/Models/ItemViewModel.cs
src/Files.App/Helpers/Layout/LayoutPreferencesItem.cs
src/Files.App/Helpers/Layout/LayoutPreferencesManager.cs
src/Files.App/Helpers/MenuFlyout/ContextFlyoutItemHelper.cs
src/Files.App/Services/Settings/FoldersSettingsService.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/UserControls/InnerNavigationToolbar.xaml
src/Files.App/Utils/Storage/Collection/SortingHelper.cs
src/Files.App/ViewModels/Settings/FoldersViewModel.cs
src/Files.App/Views/Settings/FoldersPage.xaml
src/Files.App/Views/Shells/BaseShellPage.cs
src/Files.Core/Services/Settings/IFoldersSettingsService.cs

Feature: Added option to prioritize files when sorting

---

src/Files.App/Dialogs/FilesystemOperationDialog.xaml
src/Files.App/Dialogs/FilesystemOperationDialog.xaml.cs
src/Files.Core/ViewModels/Dialogs/FileSystemDialog/FileSystemDialogViewModel.cs

Fix: Fixed issue where options in the conflicts dialog could change when scrolling

---

src/Files.App/Helpers/Application/AppLifecycleHelper.cs
src/Files.App/Helpers/BitmapHelper.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/Utils/Global/WallpaperHelpers.cs

Closes #14025
**Validation**
1. Create a 0 byte file that has a .bmp extension.
2. Try to rotate the file.
3. Now an error dialog should be displayed.

Fix: Fixed crash when manipulating invalid images

---

src/Files.App/Data/Behaviors/StickyHeaderBehavior.cs

Fix: Fixed issue where details layout headers weren't always "sticky"

---

src/Files.App/Data/Contexts/HomePage/HomePageContext.cs
src/Files.App/Data/Contexts/HomePage/IHomePageContext.cs
src/Files.App/Data/EventArguments/WidgetsRightClickedItemChangedEventArgs.cs
src/Files.App/Helpers/Application/AppLifecycleHelper.cs
src/Files.App/UserControls/Widgets/DrivesWidget.xaml.cs
src/Files.App/UserControls/Widgets/FileTagsWidget.xaml.cs
src/Files.App/UserControls/Widgets/HomePageWidget.cs
src/Files.App/UserControls/Widgets/QuickAccessWidget.xaml.cs
src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml.cs

As the title.
2. Go to Home page
3. Right click an item on Home page
4. See no exception occur or menu flyout is shown normally
_N/A_

Code Quality: Introduced HomePageContext

---

src/Files.App/App.xaml.cs
src/Files.App/Program.cs

This doesn't fix the issue of occasional failures to resume the app, but it will allow resuming to work again without killing the process.
**Validation**
1. Turn "Leave app running" on.
2. Repeatedly exit and restart the application until the application fails to resume.
3. Start the app again. It will show the splash screen.
4. Exit the app.
5. Start the app one more time. 
6. The splash screen no longer appears and resuming works correctly. Without this fix, the splash spreen continues to appear.

Fix: Fixed issue where resuming didn't work once it failed

---

src/Files.App/Actions/Content/Share/ShareItemAction.cs
src/Files.App/Helpers/ShareItemHelpers.cs
src/Files.App/Strings/en-US/Resources.resw

- Fixes https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/601897681u/overview
```
Files.App.Helpers
IDataTransferManagerInterop.ShowShareUIForWindow (IntPtr appWindow)
Files.App.Helpers
ShareItemHelpers.ShareItems (IEnumerable`1 itemsToShare)
Files.App.Actions
ShareItemAction.ExecuteAsync ()
Files.App.Data.Commands.CommandManager
ActionCommand.ExecuteAsync ()
Files.App.Data.Commands.CommandManager
ActionCommand.Execute (Object parameter)
System.Threading.Tasks.Task
<>c.<ThrowAsync>b__128_0 (Object state)
```

Fix: Fixed exception that would sometimes occur when sharing items

---

src/Files.App/Services/Settings/GeneralSettingsService.cs
src/Files.App/Services/Settings/UserSettingsService.cs
src/Files.App/ViewModels/UserControls/ToolbarViewModel.cs
src/Files.Core/Services/Settings/IGeneralSettingsService.cs

Feature: Added support for displaying recently entered paths

---

docs/rich-commands.md
src/Files.App/Actions/Display/GroupAction.cs
src/Files.App/Data/Commands/CommandCodes.cs
src/Files.App/Data/Commands/Manager/CommandManager.cs
src/Files.App/Data/Commands/Manager/ICommandManager.cs
src/Files.App/Helpers/MenuFlyout/ContextFlyoutItemHelper.cs
src/Files.App/Services/DateTimeFormatter/AbstractDateTimeFormatter.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/UserControls/InnerNavigationToolbar.xaml
src/Files.App/ViewModels/Settings/FoldersViewModel.cs
src/Files.App/Views/Settings/FoldersPage.xaml
src/Files.Core/Data/Enums/GroupByDateUnit.cs

Closes #14249 
**Validation**
1. Tested the different grouping options (year, month, day)

Feature: Added an option to group by day

---

src/Files.App/App.xaml.cs
src/Files.App/Helpers/Application/AppLifecycleHelper.cs
src/Files.App/Utils/Taskbar/SystemTrayIcon.cs

**Validation**
1. If both "Open Files at startup" and "Leave app running" is on, Files will launch in the background at Windows startup.
2. If "Open Files at startup" is on but "Leave app running" is off, Files will launch in the foreground at Windows startup.

Feature: Open minimized window on Windows startup

---

src/Files.App/Helpers/MenuFlyout/ContextFlyoutItemHelper.cs
src/Files.App/Services/Settings/GeneralSettingsService.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/ViewModels/Settings/GeneralViewModel.cs
src/Files.App/Views/Settings/GeneralPage.xaml
src/Files.Core/Services/Settings/IGeneralSettingsService.cs

Closes #14305 
**Validation**
1. Compress/Extract get displayed in the context menu, when option is turned on (default behavior)
2. Compress/Extract is hidden in the context menu if the option has been deactivated in the settings

Feature: Added support for hiding compression options from the context menu

---

src/Files.App/Data/Parameters/PropertiesPageNavigationParameter.cs
src/Files.App/Helpers/UI/DragZoneHelper.cs
src/Files.App/Utils/Storage/Helpers/FilePropertiesHelpers.cs
src/Files.App/ViewModels/Properties/MainPropertiesViewModel.cs
src/Files.App/Views/MainPage.xaml.cs
src/Files.App/Views/Properties/CustomizationPage.xaml.cs
src/Files.App/Views/Properties/MainPropertiesPage.xaml.cs

Code Quality: Migrate to InputNonClientPointerSource

---

src/Files.App/Views/Shells/ColumnShellPage.xaml.cs

Fixed NullReferenceException in ColumnShellPage.NavigateToPath
```
Files.App.Views.Shells
ColumnShellPage.NavigateToPath (String navigationPath, Type sourcePageType, NavigationArguments navArgs)
Files.App.Views.Shells
ColumnShellPage.ShellPage_NavigationRequested (Object sender, PathNavigationEventArgs e)
Files.App.ViewModels.UserControls
ToolbarViewModel.PathBoxItem_Tapped (Object sender, TappedRoutedEventArgs e)
```

Fix: Fixed NullReferenceException in ColumnShellPage.NavigateToPath

---

src/Files.App/Views/Layouts/GridLayoutPage.xaml.cs

```
Files.App.Views.Layouts
GridLayoutPage.EndRename (TextBox textBox)
Files.App.Views.Layouts
BaseGroupableLayoutPage.CommitRenameAsync (TextBox textBox)
Files.App.Views.Layouts
GridLayoutPage.FileList_ItemTapped (Object sender, TappedRoutedEventArgs e)
```

Fix: Fixed NullReferenceException when renaming files

---

src/Files.App/App.xaml.cs
src/Files.App/UserControls/AddressToolbar.xaml.cs

`System.Runtime.InteropServices.COMException: The operation identifier is not valid. The WinUI Desktop Window object has already been closed`

Fix: Fixed COMException when removing focus from the path bar

---

src/Files.App/Actions/Start/PinToStartAction.cs
src/Files.App/Actions/Start/UnpinFromStartAction.cs
src/Files.App/Services/StartMenuService.cs
src/Files.Core/Services/IStartMenuService.cs

This is an excerpt from #14045 with the crash fix.
Closes #13947 
**Validation**

Fix: Fixed issue where the app would crash when pinning an executable file

---

src/Files.App/Helpers/Interop/NativeFileOperationsHelper.cs

It now uses FindFirstStreamW and FindNextStreamW rather than actually opening the file. Opening a file forces a file download which is a cause of #14224.
Issue #14224
**Validation**
1. Open app
2. Make sure alternate data streams are showing in settings
3. Open a OneDrive folder and verify that it does not download files
4. Open a folder with a file containing an alternate data stream and verify that it appears
4. Open a folder with a subfolder containing an alternate data stream and verify that it appears

Fix: Use the Stream API to list streams instead of opening the file

---

src/Files.App/Services/Settings/FoldersSettingsService.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/ViewModels/Settings/FoldersViewModel.cs
src/Files.App/Views/Settings/FoldersPage.xaml
src/Files.App/Views/Shells/BaseShellPage.cs
src/Files.Core/Services/Settings/IFoldersSettingsService.cs

Closes #14282...
**Validation**
1. Open folder and navigate up the file tree
2. Confirm the parent folders get selected and scrolled into view
3. Open `settings > folders` and turn off the option to auto scroll
4. Confirm the setting works as expected

Feature: Added an option to disable auto scroll when navigating up

---

src/Files.App/Utils/Shell/LaunchHelper.cs

Closes #14405 
**Validation**
1. Pin `C:\Windows\System32\WindowsPowerShell\v1.0\powershell_ise.exe`
2. Execute pinned powershell_ise.exe
3. The program will now be executed in `C:\Windows\System32\WindowsPowerShell\v1.0`, not `C:\Windows\System32`

Fix: Fixed issue where pinned applications were executed in %windir%\System32

---

src/Files.App/Helpers/Interop/InteropHelpers.cs
src/Files.App/ViewModels/Dialogs/CreateShortcutDialogViewModel.cs

Closes #14418...
**Validation**
1.  Click on new > shortcut
2. Click browse and confirm it works to choose files or folders

Fix: Fixed issue where it didn't work to pick files when creating new shortcuts

---

src/Files.App/Constants.cs
src/Files.App/Data/Items/DriveItem.cs
src/Files.App/Data/Models/ItemViewModel.cs
src/Files.App/Data/Models/SidebarPinnedModel.cs
src/Files.App/Helpers/Layout/LayoutPreferencesManager.cs
src/Files.App/UserControls/Widgets/DrivesWidget.xaml.cs
src/Files.App/UserControls/Widgets/QuickAccessWidget.xaml.cs
src/Files.App/Utils/Cloud/CloudDrivesManager.cs
src/Files.App/Utils/Library/LibraryLocationItem.cs
src/Files.App/Utils/RecentItem/RecentItem.cs
src/Files.App/Utils/Shell/Win32API.cs
src/Files.App/Utils/Storage/Helpers/FileThumbnailHelper.cs
src/Files.App/ViewModels/Properties/Items/DriveProperties.cs
src/Files.App/ViewModels/Properties/Items/LibraryProperties.cs
src/Files.App/ViewModels/UserControls/Previews/BasePreviewModel.cs
src/Files.App/ViewModels/UserControls/Previews/FolderPreviewViewModel.cs
src/Files.App/ViewModels/UserControls/Previews/ShortcutPreviewViewModel.cs
src/Files.App/Views/Layouts/ColumnLayoutPage.xaml.cs
src/Files.App/Views/Layouts/ColumnsLayoutPage.xaml.cs
src/Files.App/Views/Layouts/GridLayoutPage.xaml.cs

- Simplified the code and improved the thumbnail quality
- Closes #14071
- Closes #10067
**Validation**
1. Check that folder thumbnails display a preview of their contents (except for in the Details & Column layouts)
2. Clear the thumbnail cache in Windows
3. Check that opening a folder with images or office documents generates thumbnails (in OneDrive you might have to refresh the folder to display the thumbnails)
4. Open a location with a lot of images (in the grid layout) and confirm that all the thumbnails are loaded
5. Check that turning off the option to show thumbnails works as expected (it should auto refresh the current tab)
6. Check that the preview/details pane shows the thumbnail for folders and images
7. Check that …

Feature: Switched away from GetThumbnailAsync API

---

src/Files.App/Extensions/DispatcherQueueExtensions.cs
src/Files.Shared/Extensions/SafetyExtensions.cs

Most of the COMExceptions are caused by the unavailability of DispatcherQueue, so I ignored them in that case. It is not normal when DispatcherQueue is not available and it may not work correctly after ignoring the exception, but avoiding crashes may allow the user to continue using the application.
Related to #14439
**Validation**

Fix: Fixed COMException in ItemsAdded_CollectionChanged - part 2

---

src/Files.App/Views/Layouts/BaseLayoutPage.cs

This time I made sure to ignore the exception. Since this process only affects the size display on the status bar, ignoring it is not a major problem.
Related to #14431
**Validation**

Fix: Fixed COMException with BaseLayoutPage.GetAllItems - part 2

---

src/Files.App/Actions/Navigation/NewWindowAction.cs
src/Files.App/Data/Commands/CommandCodes.cs
src/Files.App/Data/Commands/Manager/CommandManager.cs
src/Files.App/Data/Commands/Manager/ICommandManager.cs
src/Files.App/Helpers/Navigation/NavigationHelpers.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/UserControls/InnerNavigationToolbar.xaml
src/Files.App/ViewModels/MainPageViewModel.cs
src/Files.App/Views/MainPage.xaml

Fix: Fixed issue where a new tab would open when trying to open a new window

---

src/Files.App/Data/Models/ItemViewModel.cs
src/Files.App/ViewModels/UserControls/SidebarViewModel.cs
src/Files.App/Views/HomePage.xaml.cs

Closes #13823
**Bug fixed in:**
- Sidebar
- Quick Access Widget
- Current folder (Toolbar or right-click context menu)
**Underlying issue**
Folders opened with one of the methods above were always classified as `FolderOnline` (default value)
**Validation**
1. Open app 
2. Open properties of a pinned folder
3. Open properties of a quick access folder from the `Home` widget
4. Open properties of the current folder (using the toolbar button or the right-click context menu)
5. Check size is being calculated by each `Properties` window

Fix: Fixed issue where folders sizes weren't calculated when opening Properties from the sidebar

---

src/Files.App/Views/Layouts/GridLayoutPage.xaml.cs

Added more null ref protections when renaming items

Code Quality: Added more null ref protections when renaming items

---

src/Files.App/Utils/Shell/Win32API.cs

```
System.InvalidOperationException: No process is associated with this object
System.Diagnostics
Process.WaitForExitAsync (CancellationToken cancellationToken)
Files.App.Utils.Shell
Win32API.RunPowershellCommandAsync (String command, Boolean runAsAdmin)
```

Fix: Handle InvalidOperationException in RunPowershellCommandAsync

---

src/Files.App/App.xaml.cs

Fix: Fixed issue where exiting from the system tray icon didn't save the tabs

---

src/Files.App/Data/Models/SelectedItemsPropertiesViewModel.cs
src/Files.App/Files.App.csproj
src/Files.App/Helpers/MediaFileHelper.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/ViewModels/Properties/BasePropertiesPage.cs
src/Files.App/ViewModels/Properties/Items/FileProperties.cs
src/Files.App/Views/Properties/GeneralPage.xaml
src/Files.App/Views/Properties/GeneralPage.xaml.cs

Closes #7585...
**Validation**
1. Open properties for media file
2. Hover over thumbnail and confirm the "change album cover" button is displayed
3. Select an image file and confirm the thumbnail changes
4. Click save and confirm the new thumbnail is applied to the file
5. Select multiple media files and repeat steps 1 - 4
6. Confirm this option is available only when the selected items are media files

Feature: Added support for editing album covers

---

src/Files.App/Services/PreviewPopupProviders/QuickLookProvider.cs

- Handle IOException in QuickLookProvider

Fix: Fixed IOException in QuickLookProvider

---

src/Files.App/Actions/Display/LayoutAction.cs
src/Files.App/Data/Commands/CommandCodes.cs
src/Files.App/Data/Commands/Manager/CommandManager.cs
src/Files.App/Data/Commands/Manager/ICommandManager.cs
src/Files.App/Data/Contexts/DisplayPage/DisplayPageContext.cs
src/Files.App/Data/Contexts/DisplayPage/LayoutTypes.cs
src/Files.App/Helpers/Layout/LayoutPreferencesManager.cs
src/Files.App/Helpers/MenuFlyout/ContextFlyoutItemHelper.cs
src/Files.App/ResourceDictionaries/PathIcons.xaml
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/UserControls/InnerNavigationToolbar.xaml
src/Files.App/ViewModels/UserControls/ToolbarViewModel.cs
src/Files.App/Views/Layouts/ColumnLayoutPage.xaml.cs
src/Files.App/Views/Layouts/GridLayoutPage.xaml
src/Files.App/Views/Layouts/GridLayoutPage.xaml.cs
src/Files.App/Views/Settings/FoldersPage.xaml
src/Files.Core/Data/Enums/FolderLayoutModes.cs

Closes #2509...
**Validation**
- Removed border from selected items in the Grid View layouts
1. Switch to List View using the toolbar flyout, context menu, `ctrl` + `shift` + `2` shortcut
2. Switch from the Details View to List View using `ctrl` + `+` and from the Grid View using `ctrl` + `-`
3. Set the default view to List and confirm it works as expected
4. Enable compact spacing and confirm it works as expected
5. Rename items in the List View and confirm it works as expected

Feature: Added a List View layout

---

src/Files.App/Views/Shells/BaseShellPage.cs

Closes #14511...
**Validation**
1. Set default layout to Tiles
2. Open tag from the sidebar and confirm it uses the Tiles layout
3. Set default layout to Columns
4. Open tag from the sidebar and confirm it uses Details

Fix: Fixed issue where opening tags from the sidebar would default to the Details View

---

src/Files.App/Utils/Storage/Helpers/StorageFileExtensions.cs
src/Files.App/Views/Layouts/BaseLayoutPage.cs
src/Files.App/Views/Shells/BaseShellPage.cs
src/Files.App/Views/Shells/ColumnShellPage.xaml.cs
src/Files.App/Views/Shells/IShellPage.cs
src/Files.App/Views/Shells/ModernShellPage.xaml.cs

Fix: Fixed issue where path bar didn't use localized name for system folders

---

src/Files.App/UserControls/Selection/RectangleSelection_ListViewBase.cs
src/Files.App/Views/Layouts/GridLayoutPage.xaml
src/Files.App/Views/Layouts/GridLayoutPage.xaml.cs
src/Files.App/Views/Shells/BaseShellPage.cs

Fix: Fixed crash when switching to the List View layout

---

src/Files.App/Data/Items/DriveItem.cs
src/Files.App/UserControls/Widgets/DrivesWidget.xaml.cs
src/Files.App/UserControls/Widgets/IWidgetCardItem.cs
src/Files.App/UserControls/Widgets/QuickAccessWidget.xaml.cs
src/Files.App/Utils/Shell/Win32API.cs
src/Files.App/ViewModels/UserControls/SidebarViewModel.cs

Code Quality: Use LoadIconWithoutOverlayAsync for Drives Widget

---

src/Files.App/UserControls/Widgets/QuickAccessWidget.xaml.cs

Code Quality: Use LoadIconWithoutOverlayAsync for Quick Access Widget

---

src/Files.App/Strings/en-US/Resources.resw
src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml.cs

Closes #14512...
**Validation**
1. Open file from removable storage device
2. Eject the storage device
3. Right click the recent file and try opening properties
4. Confirm that an error prompt is displayed

Fix: Fixed potential crash when opening properties for recent files

---

src/Files.App/Views/Shells/BaseShellPage.cs

This fixes a regression introduced in #14532.
Related to #14532 
**Validation**

Fix: Fixed issue where the path bar didn't display the query when searching

---

src/Files.App/Views/Shells/BaseShellPage.cs

Closes #13439...
**Validation**
1. Set folder location to use Columns View
2. Submit a search and confirm it uses the Details View to display the results
3. Submit another search and confirm it's still using the Details View
4. Go back to the original location and confirm it uses the Columns View

Fix: Fixed issue where search results would sometimes use the Columns View

---

src/Files.App/Utils/Storage/Collection/BulkConcurrentObservableCollection.cs

This reverts commit 4e6f024337f7defd7eb86a21f5545fd71c0d6f71 and adds another fix.
Sorry, part 3 doesn't seem to make sense, so I would like to revert and add another fix.

Code Quality: Fixed non-thread-safe code in BulkConcurrentObservableCollection.cs - part 4

---

src/Files.App/Data/Models/ItemViewModel.cs
src/Files.App/Utils/Shell/Win32API.cs
src/Files.App/Utils/Storage/Helpers/FileThumbnailHelper.cs

Closes #14437...
**Validation**
1. Confirm file icon is displayed and then replaced once the thumbnail is loaded

Fix: Fixed issue where thumbnails would sometimes fail to load in OneDrive

---

src/Files.App/Data/Models/ItemViewModel.cs

Closes #14469
Closes #14521
**Validation**

Fix: Fixed issue where the app would crash when displaying a large number of items

---

src/Files.App/Data/Models/ItemViewModel.cs

Closes #14169 
**Validation**
1. Open Downloads folder in Files.
2. Download several files at the same time that take about 10 seconds to download in Edge.
3. Delete downloaded files from the downloads list in Edge.
4. Repeat 2. and 3.
5. No longer crash.

Fix: Fixed issue where the app could crash when adding items from external apps

---

src/Files.App/Data/Models/ItemViewModel.cs

Related to #14559 
**Validation**

Code Quality: Improved loading speed of thumbnails

---

src/Files.App/Data/Models/ItemViewModel.cs

This prevents a loophole in #14567.
`ApplyFilesAndFoldersChangesAsync` is used even for a single file change in most cases, and there is no rational reason to leave `ApplySingleFileChangeAsync`.
Related to #14567 
**Validation**

Code Quality: Deleted ItemViewModel.ApplySingleFileChangeAsync

---

src/Files.App/Constants.cs

As the title.
2. Go to Settings
3. Go to About page
4. Click the link button
_N/A_

Fix: Fixed issue where the privacy policy link was broken

---

.github/README.md
tests/Files.InteractionTests/Files.InteractionTests.csproj

Code Quality: Update target framework of Files.InteractionTests to `net8.0`

---

src/Files.App/Data/Items/ListedItem.cs
src/Files.App/Data/Models/ItemViewModel.cs
src/Files.App/Views/Layouts/ColumnLayoutPage.xaml
src/Files.App/Views/Layouts/DetailsLayoutPage.xaml
src/Files.App/Views/Layouts/GridLayoutPage.xaml

Closes #14224...
**Validation**
1. Open OneDrive location and confirm files aren't automatically downloaded

Fix: Fixed issue where some OneDrive files were automatically downloaded

---

src/Files.App/Data/Models/ContextMenuFlyoutItemViewModelBuilder.cs
src/Files.App/Data/Models/OpacityIconModel.cs
src/Files.App/Helpers/MenuFlyout/ContextFlyoutItemHelper.cs
src/Files.App/Helpers/MenuFlyout/ShellContextMenuHelper.cs
src/Files.App/UserControls/Widgets/DrivesWidget.xaml.cs
src/Files.App/UserControls/Widgets/FileTagsWidget.xaml.cs
src/Files.App/UserControls/Widgets/QuickAccessWidget.xaml.cs
src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml.cs
src/Files.App/ViewModels/UserControls/SidebarViewModel.cs

Code Quality: Improved the way of instancing OpacityIconModel

---

src/Files.App/Data/Models/ItemViewModel.cs
src/Files.App/ViewModels/UserControls/InfoPaneViewModel.cs

- This fixes an issue where placeholders for Office Documents and other file formats were created based on the thumbnail instead of the icon.
- This PR also adds placeholders for images files

Fix: Fixed issue where placeholders used the thumbnail instead of the icon

---

src/Files.App/Data/Models/ItemViewModel.cs

Related to #14581 
**Validation**

Code Quality: Fixed semaphore release timing in ItemViewModel

---

src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml.cs

Fixed System.NullReferenceException in RecentFilesWidget.OpenProperties (RecentItem item)

Fix: Fixed null ref in OpenProperties

---

src/Files.App/Data/Models/ItemViewModel.cs

`BeginBulkOperation` suppresses `CollectionChanged` and allows changing the collection in non-UI threads. But changing the collection still needs to be done in UI threads, because changes in non-UI threads may not be seen from UI threads soon due to the memory cache.
This PR puts all `FilesAndFolders` operations into UI threads. This may affect UI performance, but `ArgumentOutOfRangeException` should no longer be thrown.
Closes #14169 
**Validation**

Fix: Fixed ArgumentOutOfRangeException in ItemViewModel

---

src/Files.App/Utils/Git/GitHelpers.cs

- Fixed crash that would occur when Git path contained an emoji
```
StrictFilePathMarshaler.MarshalManagedToNative (Object managedObj)
/_/LibGit2Sharp/Core/FilePathMarshaler.cs, line 76
System.Text.EncoderFallbackException: Unable to translate Unicode character \\uDC83 at index 24 to specified code page
```

Fix: Fixed crash that would occur when Git path contained an emoji

---

src/Files.App/Helpers/UI/UIFilesystemHelpers.cs
src/Files.App/Utils/Storage/Operations/FilesystemHelpers.cs
src/Files.App/ViewModels/Dialogs/CreateShortcutDialogViewModel.cs

Closes #8711...
**Validation**

Feature: Use File Explorer naming preferences when creating shortcuts

---

src/Files.App/Data/Models/ItemViewModel.cs
src/Files.App/Helpers/Layout/LayoutPreferencesManager.cs
src/Files.App/ViewModels/UserControls/ToolbarViewModel.cs
src/Files.App/Views/Layouts/BaseLayoutPage.cs
src/Files.App/Views/Layouts/DetailsLayoutPage.xaml.cs
src/Files.App/Views/Layouts/GridLayoutPage.xaml.cs
src/Files.App/Views/Shells/BaseShellPage.cs

Related #10492...
**Validation**

Code Quality: Return icon size based on current layout settings

---

src/Files.App/Services/Settings/FileTagsSettingsService.cs
src/Files.Core/ViewModels/FileTags/TagViewModel.cs

Closes #12535 
Related #14362 
**Notes**
When editing a tag, we need to instantiate a new `TagViewModel` so that `CachingJsonSettingsDatabase.SetValue() -> UpdateValueInCache()` will find a difference between the old and the new list, hence saving the changes.
Before we were making a shallow-copy of the tag, causing changes to affect the object in both the lists
**Validation**
1. Rename/Change the color of two or more tags
2. Save Changes
3. Restart the app 
4. Check that changes were applied

Fix: Fixed issue where renaming a tag wouldn't save the new name

---

src/Files.App/Data/Behaviors/StickyHeaderBehavior.cs

Closes #13220...
**Validation**
1. Open folder with a lot of items (using Details View)
2. Remove focus from window
3. Hover over window without focusing it and scroll
4. Refocus the window and confirm that it doesn't auto scroll

Fix: Fixed issue where refocusing Details View would sometimes scroll

---

src/Files.App/App.xaml.cs
src/Files.App/Services/Settings/AppSettingsService.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.Core/Services/Settings/IAppSettingsService.cs

Feature: Added a notification when the app goes to the background for the first time

---

src/Files.App/UserControls/SideBar/ISideBarViewModel.cs
src/Files.App/UserControls/SideBar/SideBarItem.cs
src/Files.App/UserControls/SideBar/SideBarView.xaml.cs
src/Files.App/ViewModels/UserControls/SidebarViewModel.cs

Fix: Fixed COMException in HandleLocationItemDroppedAsync

---

src/Files.App/App.xaml.cs
src/Files.App/Utils/Git/GitHelpers.cs

**Changes**
* SemaphoreSlim is used instead of ThreadWithMessageQueue
* Only GetRepositoryHead limits the number of concurrent operations. Limiting others may cause problems such as delay in displaying the item list.
**Validation**
1. Navigate to a Git repository from outside the repository.
2. Navigate immediately to a subfolder of the repository.
3. The delay in displaying items, which sometimes occurred especially in environments with weak networks, is now fixed.

Code Quality: Improved performance of Git operations

---

src/Files.App/Utils/Storage/Helpers/StorageFileExtensions.cs
src/Files.App/Views/Shells/BaseShellPage.cs

**Validation**
Before fix:
After fix:

Fix: Fixed issue where the path bar on the home page was not translated

---

src/Files.App/Data/Items/DriveItem.cs
src/Files.App/Data/Items/SidebarLibraryItem.cs
src/Files.App/Data/Items/WidgetDriveCardItem.cs
src/Files.App/Data/Items/WidgetFolderCardItem.cs
src/Files.App/Data/Models/ItemViewModel.cs
src/Files.App/Data/Models/SidebarPinnedModel.cs
src/Files.App/Utils/Cloud/CloudDrivesManager.cs
src/Files.App/Utils/RecentItem/RecentItem.cs
src/Files.App/Utils/Shell/Win32API.cs
src/Files.App/Utils/Storage/Helpers/FileThumbnailHelper.cs
src/Files.App/ViewModels/Properties/Items/DriveProperties.cs
src/Files.App/ViewModels/Properties/Items/LibraryProperties.cs
src/Files.App/ViewModels/UserControls/Previews/BasePreviewModel.cs
src/Files.App/ViewModels/UserControls/Previews/FolderPreviewViewModel.cs
src/Files.App/ViewModels/UserControls/Previews/ShortcutPreviewViewModel.cs

Fix: Fixed issue where exe icons were sometimes small

---

src/Files.App/Views/Shells/BaseShellPage.cs

```
System.Linq
ThrowHelper.ThrowNoElementsException ()
System.Linq
Enumerable.Last[TSource] (IEnumerable`1 source)
Files.App.Views.Shells
BaseShellPage.RemoveLastPageFromBackStack ()
Files.App.Views.Layouts
BaseLayoutPage.BaseFolderSettings_LayoutModeChangeRequested (Object sender, LayoutModeEventArgs e)
Files.App.Data.Models
LayoutPreferencesManager.set_GridViewSize (Int32 value)
Files.App.ViewModels.Layouts
BaseLayoutViewModel.PointerWheelChanged (PointerRoutedEventArgs e)
CommunityToolkit.Mvvm.Input
RelayCommand`1.Execute (Object parameter)
Microsoft.Xaml.Interactions.Core
InvokeCommandAction.Execute (Object sender, Object parameter)
```

Fix: Fixed InvalidOperationException when removing page from BackStack

---

src/Files.App/UserControls/Menus/FileTagsContextMenu.cs

Fixed `System.NullReferenceException: Object reference not set to an instance of an object`
**Stacktrace**
```csharp
Files.App.UserControls.Menus
FileTagsContextMenu.Item_Opening (Object sender, Object e)
```

Fix: Fixed NullReferenceException in Item_Opening

---

src/Files.App/Constants.cs
src/Files.App/Data/Contexts/DisplayPage/DisplayPageContext.cs
src/Files.App/Data/Items/DriveItem.cs
src/Files.App/Data/Items/SidebarLibraryItem.cs
src/Files.App/Data/Items/WidgetDriveCardItem.cs
src/Files.App/Data/Items/WidgetFolderCardItem.cs
src/Files.App/Data/Models/ItemViewModel.cs
src/Files.App/Helpers/Layout/AdaptiveLayoutHelpers.cs
src/Files.App/Helpers/Layout/LayoutPreferencesItem.cs
src/Files.App/Helpers/Layout/LayoutPreferencesManager.cs
src/Files.App/Services/Settings/LayoutSettingsService.cs
src/Files.App/Utils/Cloud/CloudDrivesManager.cs
src/Files.App/Utils/RecentItem/RecentItem.cs
src/Files.App/ViewModels/UserControls/Previews/BasePreviewModel.cs
src/Files.App/ViewModels/UserControls/Previews/FolderPreviewViewModel.cs
src/Files.App/ViewModels/UserControls/Previews/ShortcutPreviewViewModel.cs
src/Files.App/ViewModels/UserControls/ToolbarViewModel.cs
src/Files.App/Views/Layouts/ColumnLayoutPage.xaml.cs
src/Files.App/Views/Layouts/ColumnsLayoutPage.xaml.cs
src/Files.App/Views/Layouts/DetailsLayoutPage.xaml.cs
src/Files.App/Views/Layouts/GridLayoutPage.xaml
src/Files.App/Views/Layouts/GridLayoutPage.xaml.cs
src/Files.Core/Services/Settings/ILayoutSettingsService.cs

Code Quality: Differentiate between icon size & icon height

---

src/Files.App/Helpers/BitmapHelper.cs
src/Files.App/Utils/Shell/Win32API.cs

Closes #13901...
**Validation**

Fix: Fixed issue where icon overlays were cached

---

src/Files.App/Data/Items/WidgetFileTagCardItem.cs
src/Files.App/UserControls/Widgets/FileTagsWidget.xaml.cs

https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/526177982u/overview
**Validation**

Fix: Fixed crash that would occur when clicking an item on the Tags widget

---

src/Files.App/App.xaml.cs
src/Files.App/Helpers/Application/AppLifecycleHelper.cs
src/Files.App/Helpers/UI/UIHelpers.cs

https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/2052501578u/overview
**Validation**

Fix: Fixed COMException loop due to failure to generate notification

---

src/Files.App/Views/Layouts/ColumnLayoutPage.xaml.cs
src/Files.App/Views/Layouts/ColumnsLayoutPage.xaml.cs

https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/3264578409u/overview
**Validation**

Fix: Fixed InvalidOperationException in ColumnsLayoutPage

---

.github/workflows/ci.yml
.github/workflows/deploy-preview.yml

Nodejs 16 has been deprecated. v4 is preferable.
_None_
_None_

GitHub: Update CI's checkout step version to v4

---

src/Files.App/Actions/Navigation/DuplicateSelectedTabAction.cs

```
Files.App.Actions
DuplicateSelectedTabAction.ExecuteAsync ()
Files.App.Views
MainPage.OnPreviewKeyDownAsync (KeyRoutedEventArgs e)
Files.App.Views
MainPage.OnPreviewKeyDown (KeyRoutedEventArgs e)
System.Threading.Tasks.Task
<>c.<ThrowAsync>b__128_0 (Object state)
Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext
<>c__DisplayClass2_0.<Post>b__0 ()
WinRT
ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0 (Int32 hr)
ABI.Windows.ApplicationModel.Core
IUnhandledErrorMethods.Propagate (IObjectReference _obj)
Microsoft.AppCenter.Utils
ApplicationLifecycleHelperWinUI.<ctor>b__0_3 (Object sender, UnhandledErrorDetectedEventArgs eventArgs)
```
**Validation**

Fix: Fixed NullReferenceException in DuplicateSelectedTabAction.ExecuteAsync

---

src/Files.App/Data/Contexts/Multitasking/MultitaskingContext.cs

Closes #12624...
**Validation**
1. Open multiple tabs
2. Force close app from task manager
3. Confirm tabs are restored during the next session
**Notes***
This doesn't support multiple windows, the list of saved tabs will be from whichever window was last active.

Feature: Restore tabs when Files process is closed incorrectly

---

src/Files.App/Data/Items/DriveItem.cs
src/Files.App/Data/Items/SidebarLibraryItem.cs
src/Files.App/Data/Items/WidgetDriveCardItem.cs
src/Files.App/Data/Items/WidgetFolderCardItem.cs
src/Files.App/Data/Models/AppModel.cs
src/Files.App/Data/Models/ItemViewModel.cs
src/Files.App/Data/Models/SidebarPinnedModel.cs
src/Files.App/Helpers/Navigation/NavigationHelpers.cs
src/Files.App/Utils/Cloud/CloudDrivesManager.cs
src/Files.App/Utils/RecentItem/RecentItem.cs
src/Files.App/Utils/Shell/Win32API.cs
src/Files.App/Utils/Storage/Helpers/FileThumbnailHelper.cs
src/Files.App/Utils/Storage/Search/FolderSearch.cs
src/Files.App/ViewModels/Properties/BasePropertiesPage.cs
src/Files.App/ViewModels/Properties/Items/DriveProperties.cs
src/Files.App/ViewModels/Properties/Items/FileProperties.cs
src/Files.App/ViewModels/Properties/Items/FolderProperties.cs
src/Files.App/ViewModels/Properties/Items/LibraryProperties.cs
src/Files.App/ViewModels/UserControls/Previews/BasePreviewModel.cs
src/Files.App/ViewModels/UserControls/Previews/FolderPreviewViewModel.cs
src/Files.App/ViewModels/UserControls/Previews/ShortcutPreviewViewModel.cs
src/Files.Core/Data/Enums/IconOptions.cs

- added an IconOptions enum
- separated code for retrieving icons & icon overlays

Code Quality: Icon improvements

---

src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml
src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml.cs
src/Files.App/Utils/RecentItem/RecentItem.cs

**Validation**
1. Confirm Recent Item icons load correctly

Code Quality: Improve icon code for recent items

---

src/Files.App/Actions/Global/OpenHelpAction.cs
src/Files.App/Constants.cs
src/Files.App/Helpers/Application/AppLifecycleHelper.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/Utils/Taskbar/SystemTrayIcon.cs
src/Files.App/ViewModels/Settings/AboutViewModel.cs
src/Files.App/Views/Settings/AboutPage.xaml

Related to #14802 
**Validation**

Feature: Added Discord link to About page

---

src/Files.App/ResourceDictionaries/PathIcons.xaml
src/Files.App/UserControls/InnerNavigationToolbar.xaml

Feature: Add icon sizes to the layout flyout

---

src/Files.App/Actions/Display/LayoutAction.cs
src/Files.App/Helpers/Layout/LayoutSizeKindHelper.cs
src/Files.App/Services/Settings/LayoutSettingsService.cs
src/Files.App/UserControls/InnerNavigationToolbar.xaml
src/Files.App/ViewModels/UserControls/AddressToolbarViewModel.cs
src/Files.Core/Data/Enums/ColumnsViewSizeKind.cs
src/Files.Core/Data/Enums/DetailsViewSizeKind.cs
src/Files.Core/Data/Enums/GridViewSizeKind.cs
src/Files.Core/Data/Enums/ListViewSizeKind.cs

For #10492...
**Validation**
1. Confirm the selection state in the layout flyout is correct for each view and size

Feature: Update layout size selection state

---

src/Files.App/Data/Factories/ContentPageContextFlyoutFactory.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/Views/Settings/FoldersPage.xaml

Feature: Replaced string "Layout mode" with "Layout" for simplicity

---

src/Files.App/Data/Models/ItemViewModel.cs

Closes #14841 
**Validation**
1. Create a 0byte bitmap file and place it to a OneDrive folder.
2. Open that folder in the Grid layout.
3. The sync status now should be displayed.

Fix: Fixed issue where some files failed to load properties

---

src/Files.App/App.xaml.cs
src/Files.App/Data/Contexts/Multitasking/MultitaskingContext.cs
src/Files.App/Helpers/Application/AppLifecycleHelper.cs
src/Files.App/Helpers/Navigation/NavigationHelpers.cs
src/Files.App/Services/UpdateService.cs
src/Files.App/UserControls/TabBar/BaseTabBar.cs
src/Files.App/ViewModels/Settings/GeneralViewModel.cs

Closes #14856...
**Validation**

Fix: Fixed issue where tabs weren't restored when resuming from the background

---

src/Files.App/UserControls/InnerNavigationToolbar.xaml
src/Files.App/UserControls/InnerNavigationToolbar.xaml.cs

- Hide primary command bar on Home page
- Show "Home" string header instead.
1. Go to Home
2. See the requirements are met

Feature: Added a banner to the home page

---

src/Files.App/Data/Contexts/Multitasking/MultitaskingContext.cs
src/Files.App/Helpers/Navigation/NavigationHelpers.cs
src/Files.App/Views/MainPage.xaml.cs
src/Files.App/Views/PaneHolderPage.xaml.cs

Fix: Save tab list on path change

---

src/Files.App/Data/Models/ItemViewModel.cs
src/Files.App/Utils/Shell/Win32API.cs
src/Files.App/Utils/Storage/Enumerators/Win32StorageEnumerator.cs

Code Quality: Remove thumbnail cache to simplify logic and improve performance

---

src/Files.App/Utils/Global/NetworkDrivesAPI.cs

Closes #14903
**Validation**
1. Launch Files with a low-privileged user account
2. Access a server adminsitrative share (\\myserver\c$)

Fix: Prompt for credentials when a network share access is denied

---

src/Files.App/UserControls/InnerNavigationToolbar.xaml

As the title.
Closes #14880
1. Change language to Italian
2. Go to a folder in a Tiles layout
3. Open the Layout Picker
Before|After
---|---

Fix: Fixed an issue where the Layout Picker UI is broken up in a certain localization

---

src/Files.App/Data/Items/ListedItem.cs
src/Files.App/Data/Models/SelectedItemsPropertiesViewModel.cs
src/Files.App/UserControls/FileIcon.xaml
src/Files.App/Utils/Storage/Enumerators/UniversalStorageEnumerator.cs
src/Files.App/Utils/Storage/Enumerators/Win32StorageEnumerator.cs
src/Files.App/ViewModels/Properties/Items/FileProperties.cs
src/Files.App/Views/Layouts/ColumnLayoutPage.xaml
src/Files.App/Views/Layouts/DetailsLayoutPage.xaml
src/Files.App/Views/Layouts/GridLayoutPage.xaml

Removed web shortcut icon placeholder for consistency with other item types

Feature: Removed web shortcut icon placeholder

---

src/Files.App/Data/Models/ItemViewModel.cs

Code Quality: Changed asynchronous logic for loading icons

---

src/Files.App/Views/Layouts/ColumnLayoutPage.xaml
src/Files.App/Views/Layouts/ColumnLayoutPage.xaml.cs
src/Files.App/Views/Layouts/GridLayoutPage.xaml
src/Files.App/Views/Layouts/GridLayoutPage.xaml.cs

Feature: Keep scroll offset when changing item size

---

src/Files.App/ViewModels/Properties/Items/CombinedFileProperties.cs
src/Files.App/ViewModels/Properties/Items/FileProperties.cs

Closes #14892
1. Go to properties window of a video file
2. Go to Details tab
3. See the bitrate is shown in formatted text
_None_

Fix: Fixed an issue where video bitrate was displayed in plain text

---

src/Files.App (Package)/Package.appxmanifest
src/Files.Shared/Helpers/FileExtensionHelpers.cs

Closes #14938...
**Validation**
1. Confirmed that it works to browse and extract items from this file format

Feature: Added support for opening and extracting mrpack files

---

src/Files.App/Data/Models/ItemViewModel.cs
src/Files.App/Files.App.csproj
src/Files.App/Utils/Shell/Win32API.cs
src/Files.App/Utils/Storage/Helpers/FileThumbnailHelper.cs
src/Files.Core/Data/Enums/IconOptions.cs

Fix: Fixed issue where loading thumbnails sometimes took very long time

---

src/Files.App/Actions/FileSystem/OpenItemAction.cs
src/Files.App/Data/Factories/ContentPageContextFlyoutFactory.cs
src/Files.App/Data/Factories/ShellContextFlyoutHelper.cs
src/Files.App/Files.App.csproj
src/Files.App/Views/Layouts/BaseLayoutPage.cs

Code Quality: Added workaround for open with icon to display correctly

---

src/Files.App/Utils/Storage/Operations/FilesystemHelpers.cs
src/Files.App/ViewModels/Layouts/BaseLayoutViewModel.cs
src/Files.App/ViewModels/UserControls/AddressToolbarViewModel.cs
src/Files.App/ViewModels/UserControls/SidebarViewModel.cs
src/Files.App/Views/Layouts/BaseLayoutPage.cs

Closes #14008 
**Validation**
1. Download a file with Edge.
2. Drag the downloaded file from the Downloads flyout and drop it to Files.
3. The operation now works.

Fix: Fixed issue where drag and drop from Edge didn't work

---

src/Files.App/Data/Items/WidgetDriveCardItem.cs

Closes #14764 
**Validation**
1. Enable `Drives` widget
2. Connect a phone
3. Open Files Home page

Fix: Fixed issue where certain drive icons didn't load on the home page widget

---

src/Files.App/Helpers/EnumConversionHelpers.cs
src/Files.App/Utils/Storage/Operations/FilesystemOperations.cs

Fix: Fixed issue where coping or moving a folder would cause the contents of the destination folder to be empty

---

src/Files.App/UserControls/AddressToolbar.xaml
src/Files.App/ViewModels/UserControls/AddressToolbarViewModel.cs

Closes #11765...
**Validation**

Feature: Added support for Listary integration

---

src/Files.App/ViewModels/UserControls/SidebarViewModel.cs

Closes #15052 
**Validation**
Dark mode - Current Preview (3.3)
Light mode - Version of this PR
https://github.com/files-community/Files/assets/56681014/460dfdb0-68ee-4ccf-8390-1eba306de043

Fix: Fixed bug where the wrong item was shown as active in the sidebar

---

src/Files.App/Data/Models/SelectedItemsPropertiesViewModel.cs
src/Files.App/ViewModels/Properties/Items/CombinedProperties.cs
src/Files.App/ViewModels/Properties/Items/FileProperties.cs
src/Files.App/ViewModels/Properties/Items/FolderProperties.cs
src/Files.App/ViewModels/Properties/Items/LibraryProperties.cs
src/Files.App/Views/Properties/GeneralPage.xaml.cs

Closes #14900 
**Validation**
**Test Cases**
Hidden status is saved and displayed correctly directly in the UI if only one file is selected
- Select a file, open properties, select hidden + save
- The file is now displayed directly in the list as hidden
- Open properties again and check whether hidden status is set
Hidden status is saved and displayed correctly directly in the UI when multiple files are selected
- Select multiple files, select hidden + save
- The files are now displayed directly in the list as hidden
- Open properties again and check whether hidden status is set

Fix: Fixed issue with editing properties of multiple items at the same time

---

src/Files.App/Data/Models/ItemViewModel.cs
src/Files.Shared/Helpers/FileExtensionHelpers.cs

Closes #15072...
**Validation**
1. Enable svg thumbnails in PowerToys
2. Clear thumbnail cache in Windows
3. Open folder in Files with svgs and confirm a basic icon is displayed and then replaced with the thumbnail

Fix: Fixed conflict with svg thumbnails generated by PowerToys

---

src/Files.App/Utils/Cloud/CloudDrivesDetector.cs

I got a bit annoyed with Files only listing one of the Company SharePoint folders that I use, so I went and implemented this.
Closes #4966
**Validation**
1. Open app
2. Compare SharePoint listing between old and new versions and between the actual folders.

Feature: List all the SharePoint directories

---

.github/workflows/format-xaml.yml

It now authenticates properly with GitHub when pushing. Previously it was using `Personal Access Token` instead of `x-access-token` as the HTTP username. Also added some error handling
**Validation**
1. Add unformatted files to a PR and attempt to format (https://github.com/heftymouse/Files/pull/9#issuecomment-2036202437)

GitHub: Fixed formatting workflow

---

src/Files.App (Package)/Package.appxmanifest
src/Files.App.Server/Database/LayoutPreferencesDatabase.cs
src/Files.App/Helpers/Layout/LayoutPreferencesDatabaseManager.cs

Not approved, but I think a crash should be fixed👀, this closes #15124
**Validation**
1. Open settings
2. Toggle the option
https://github.com/files-community/Files/assets/52143624/f9e3f7c6-522d-48e9-af53-4a72fc379151
**Additional info**
This is the stacktrace of the crash
```cs
2024-04-05 20:19:11.0801|Error|System.Runtime.InteropServices.COMException (0x80131509)
at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
at ABI.Files.App.Server.Database.ILayoutPreferencesDatabaseClassMethods.ResetAll(IObjectReference _obj, LayoutPreferencesFilterPredicate predicate)
at Files.App.Server.Database.LayoutPreferencesDatabase.ResetAll(LayoutPreferencesFilterPredicate predicate)
at …
```

Fix: Crash caused by useless predicate.

---

src/Files.App/Views/Layouts/DetailsLayoutPage.xaml.cs

Fix: Fixed issue where items could not be sorted by clicking on the header of the details layout

---

src/Files.App/Data/Models/ItemViewModel.cs
src/Files.App/ViewModels/UserControls/AddressToolbarViewModel.cs
src/Files.App/Views/Shells/BaseShellPage.cs
src/Files.App/Views/Shells/ModernShellPage.xaml.cs

Feature: Added support for filtering current directory when typing into search box

---

src/Files.App/Helpers/Interop/NativeFileOperationsHelper.cs
src/Files.App/Helpers/NaturalStringComparer.cs
src/Files.App/NativeMethods.txt
src/Files.App/Utils/Storage/Helpers/FilesystemResult.cs
src/Files.App/Utils/Storage/Operations/FilesystemOperations.cs
src/Files.App/Utils/Storage/StorageItems/NativeStorageFile.cs
src/Files.App/Utils/Storage/StorageItems/ZipStorageFile.cs
src/Files.App/Utils/Storage/StorageItems/ZipStorageFolder.cs

Part of #14505, #15000 
**Validation**

Code Quality: Migrated CopyFileFromApp and MoveFileFromApp to CsWin32

---

src/Files.App/Helpers/Win32/Win32Helper.Shell.cs
src/Files.App/Services/QuickAccessService.cs
src/Files.App/Utils/RecentItem/RecentItems.cs
src/Files.App/Utils/RecycleBin/RecycleBinHelpers.cs
src/Files.App/Utils/Storage/StorageItems/ShellStorageFolder.cs

This avoids unnecessarily fetching its parent shell folder when retrieving recent items. If #13116 is caused by an exception when fetching the shell folder, the issue could be fixed.
Related to #13116
**Validation**

Code Quality: Avoid unnecessary shell folder fetching

---

src/Files.App/Data/Items/ListedItem.cs
src/Files.App/Data/Models/ItemViewModel.cs
src/Files.App/MainWindow.xaml.cs
src/Files.App/Utils/FileTags/FileTagsHelper.cs
src/Files.App/Utils/Storage/Operations/FileOperationsHelpers.cs

Fix: Fixed issue where some file operations would fail

---

src/Files.App/ViewModels/Properties/MainPropertiesViewModel.cs

Closes #13257 
**Validation**
1. Open a properties window
2. Navigate to Security
3. Go to Advanced permissions
4. Navigate back
5. Navigate to other pages and it works now.

Fix: Fixed issue where properties window could not navigate to other pages after returning from advanced settings

---

.gitignore
src/Files.App/Utils/Cloud/CloudProviders.cs
src/Files.App/Utils/Cloud/Detector/CloudDetector.cs
src/Files.App/Utils/Cloud/Detector/LucidLinkCloudDetector.cs

Closes #14612 
**Validation**
**Additional comments**
There one issue to note and I believe it's on Lucid Link side. When Lucid Links close the share won't exist, Files still shows it in the cloud drives section but will give the not a folder error when clicked on. Windows File Explorer will also do the same if it was pinned and lucid link doesn't show. 
I'm also not able to test if multiple shares would show.
There also the question if it should show the file share name, organization name or both. Right now I'm match Windows File Explorer behavior

Feature: Show Lucid Link in the cloud drives section

---

src/Files.App/Helpers/Interop/NativeFileOperationsHelper.cs
src/Files.App/NativeMethods.txt
src/Files.App/Utils/Serialization/Implementation/DefaultSettingsSerializer.cs

Part of #14505, #15000 
**Validation**
**Additional comments**
Also removed unused methods from a previous PR #15131

Code Quality: Migrated `CreateDirectoryFromApp` to CsWin32 

---

src/Files.App/Views/MainPage.xaml

Closes #15181...
**Validation**
1. Open app, hover over add tab button and confirm it doesn't overlap border

Fix: Fixed alignment of the add tab button

---

src/Files.App/Dialogs/GitHubLoginDialog.xaml.cs

```cs
WinRT
ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0 (Int32 hr)
ABI.Windows.ApplicationModel.DataTransfer
IClipboardStaticsMethods.Flush (IObjectReference _obj)
Files.App.Dialogs
GitHubLoginDialog.ContentDialog_PrimaryButtonClick (ContentDialog sender, ContentDialogButtonClickEventArgs args)
ABI.Windows.Foundation
TypedEventHandler`2.Do_Abi_Invoke[TSenderAbi,TResultAbi] (Void* thisPtr, TSenderAbi sender, TResultAbi args)
```

Fix: Fixed crash when closing the GitHub login modal

---

src/Files.App.Server/Database/FileTagsDatabase.cs
src/Files.App.Server/Database/LayoutPreferencesDatabase.cs
src/Files.App.Server/Files.App.Server.csproj
src/Files.App/ViewModels/Settings/AdvancedViewModel.cs

We hit https://github.com/mbdavid/LiteDB/issues/2435 which results in Files crashing. As a workaround, we may use `Shared` connection instead of `Direct`. It may slow down the query speed, but it no longer crashes.
Closes #15203
Closes #15172
Closes #15157
**Validation**

Code Quality: Downgrade LiteDB to fix transaction issue

---

src/Files.App.Server/NativeMethods.json
src/Files.App.Server/NativeMethods.txt
src/Files.App.Server/Program.cs
src/Files.App/Helpers/Layout/LayoutPreferencesManager.cs
src/Files.App/Program.cs
src/Files.App/Utils/Storage/StorageItems/SystemStorageFile.cs

- Do not call `RoUninitialize` as this will be automatically done on the process exit
- Correct the path for `tag:*` to `Home` while getting the layout preferences
- Kill hanging server at startup
**Validation**

Code Quality: Various fixes to the WinRT server call

---

src/Files.App/Services/QuickAccessService.cs
src/Files.App/Utils/RecentItem/RecentItems.cs
src/Files.App/Utils/RecentItem/RecentItemsManager.cs

Currently we load pinned folders and recent files from the quick access shell folder. It contains both pinned folders and recent files, but it causes both loads to be affected when one of them goes wrong.
So I changed it to load pinned folders and recent files separately. This should allow pinned folders to be displayed without having to do workarounds such as disabling recent files. Also, recent files should be displayed before pinned folders have finished loading.
Related to #13116 
Related to #13087 
**Validation**

Code Quality: Improved loading of pinned folders and recent files

---

src/Files.App/Utils/Shell/LaunchHelper.cs

Closes #15179
ShellExecute fails to open HWiNFO64.exe for some reason. The store version of powershell also has the same issue with that file. Here's a workarpund.
NB: will popup UAC prompt twice, but the app starts. Tested with portable version of HWiNFO64.exe.
**Validation**

Fix: Fixed an issue where HWiNFO64.exe wouldn't open

---

src/Files.App/Views/Layouts/ColumnLayoutPage.xaml.cs

Closes #15230
Removes double call to ItemInvoked on ItemTapped(). ItemInvoked is already called by SelectionChanged().
**Validation**

Fix: Fixed issue where changing focus in column view caused extra animation

---

src/Files.App/Services/Settings/AppearanceSettingsService.cs
src/Files.App/Services/Settings/IAppearanceSettingsService.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/ViewModels/MainPageViewModel.cs
src/Files.App/ViewModels/Settings/AppearanceViewModel.cs
src/Files.App/Views/MainPage.xaml
src/Files.App/Views/Settings/AppearancePage.xaml

Closes #12636
**Validation**
1. Open settings file and assign path to an image file.
2. Open Files and confirm the image is displayed.
3. Adjust the different properties in the settings UI, and confirm the different combinations work properly.
**ToDo**

Feature: Added a theming option to display a background image

---

src/Files.App/Utils/Storage/Operations/FilesystemHelpers.cs

Closes #15303 
**Validation**
1. Copied conflicting file
2. Renamed the file in the conflicts dialog
3. Confirmed the operation completed in the status center

Fix: Fixed issue where renaming in the conflict dialog would leave the copy status in process

---

src/Files.App/Helpers/Environment/ElevationHelpers.cs
src/Files.App/Helpers/Win32/Win32PInvoke.Methods.cs

Part of #15000 
**Validation**
**Additional Context**
[#865 is undocumented](https://github.com/microsoft/CsWin32/issues/1170), so it's impossible to use CsWin32.

Code Quality: Use `LibraryImportAttribute` at undocumented EntryPoint

---

src/Files.App/Utils/Storage/Helpers/FilePropertiesHelpers.cs

This may fix the following exception.
- Closes #
2. ...

Code Quality: Use constructor instead of collection expression for the properties window cache

---

src/Files.App.Server/AppInstanceMonitor.cs
src/Files.App.Server/Database/FileTagsDatabase.cs
src/Files.App.Server/Database/LayoutPreferencesDatabase.cs
src/Files.App/Helpers/Layout/LayoutPreferencesDatabaseManager.cs
src/Files.App/Utils/FileTags/FileTagsHelper.cs

Reverts files-community/Files#15324
This doesn't seem to fix the CsWinRT crashing issue.
In addition, make initialization of `LayoutPreferencesDatabase` lazy.

Revert "Code Quality: Pin WinRT server object to prevent object reference being invalid"

---

src/Files.App/Services/PreviewPopupProviders/SeerProProvider.cs

- Closes #14966
1. Install SeerPro
2. Confirm that the follow selection setting in SeerPro is reflected in Files
- This setting is only detected once, Files requires a restart after updating the setting in SeerPro

Feature: Added support for SeerPro's "Track selected file" setting

---

src/Files.App/Services/PreviewPopupProviders/SeerProProvider.cs

This fixes the reason why it didn't work well in my environment.
- Related to #15339 
2. ...

Code Quality: Gave priority to registry when loading Seer Pro settings

---

src/Files.App/Data/Contracts/INetworkDrivesService.cs
src/Files.App/Data/Items/DriveItem.cs
src/Files.App/Services/NetworkDrivesService.cs

- Closes #8304
1. Open Files.
2. Wait a moment. You can continue to use the app while loading network folders.
3. Network folders will be displayed on the sidebar.

Feature: Added support for displaying all network folders on the sidebar

---

src/Files.App/Services/AppThemeModeService.cs

- Closes #15332
2. Change the theme mode (I’m not sure this is reproducible even often)

Fix: Fixed an issue where the theme mode change would cause a crash

---

src/Files.App/Utils/Storage/Helpers/FilePropertiesHelpers.cs

I have no idea why NullReferenceException occurs, but it also occurs in v3.4.1, so I made it null safe.
- Related to #15337 
2. ...

Fix: Fixed NullReferenceException in FilePropertiesHelpers.DestroyCachedWindows

---

src/Files.App/Helpers/Application/AppLifecycleHelper.cs
src/Files.App/Services/DummyUpdateService.cs
src/Files.App/Services/StoreUpdateService.cs

Currently, the Dev build attempts to check for updates from the store on launch, which always fails and results in a native exception that pauses the app. This PR introduces a no-op implementation of IUpdateService used when running in Dev mode. It also renames UpdateService to StoreUpdateService for clarity.
1. Opened Files Dev
2. Checked for exception in kernelbase.dll on startup

Code Quality: Add Dummy update service for dev builds

---

src/Files.App/Data/Enums/BackdropMaterialType.cs
src/Files.App/Helpers/UI/AppSystemBackdrop.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/ViewModels/Settings/AppearanceViewModel.cs

This PR adds all the available system backdrop options - None, Mica non-alt, and base Acrylic in addition to the existing Mica Alt and Thin Acrylic (called just Acrylic in the UI) options. Design aside, this is mainly for completeness in theming. Mica Alt is still the default option.
- Closes #15045
2. …

Feature: Added support for "Thin acrylic" system backdrop

---

src/Files.App/ViewModels/Settings/AboutViewModel.cs

- Closes #15415
1. Opened Files > Settings > About
2. Clicked on "Open Log Location"
3. Confirmed the location opened in File Explorer, and that the Settings Dialog stayed open
4. Set Files as the default file manager
5. Clicked on "Open Log Location"
6. Confirmed the location opening in Files, and that the Settings …

Feature: Close settings dialog when opening the log location

---

src/Files.Shared/Helpers/FileExtensionHelpers.cs

- Closes #15250
1. Right clicked "AHK" (auto hot key) file and confirmed the run as options were displayed

Feature: Added "Run as admin" support for AHK files

---

src/Files.App/UserControls/Pane/InfoPane.xaml
src/Files.App/UserControls/SideBar/SideBarView.properties.cs
src/Files.App/UserControls/SideBar/SideBarView.xaml
src/Files.App/UserControls/SideBar/SideBarView.xaml.cs
src/Files.App/Views/MainPage.xaml
src/Files.App/Views/PaneHolderPage.xaml

- Updated the Status Bar design 
- This is prep work for completely floating panes
1. Confirmed the corner radius is set to `0` when the sidebar is collapsed
2. Confirmed the sidebar resizer height matches the border height
3. Confirmed the border thickness is correct when Dual Pane mode is enabled
4. Confirmed the …

Feature: Updated the Status Bar design

---

src/Files.App/Extensions/MessageFormatExtensions.cs
src/Files.App/Files.App.csproj
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/Views/Layouts/BaseLayoutPage.cs
src/Files.App/Views/Shells/BaseShellPage.cs

- For #15323
1. Testing plural implementation for text strings using ICU format
2. Adding for all necessary strings
**Screenshot**

Code Quality: Adding the possibility of plural translation using ICU format

---

src/Files.App/ViewModels/UserControls/AddressToolbarViewModel.cs

- Closes #15447
1. Enter `git clone https://github.com/files-community/Files` into address bar
2. Confirm the repo is cloned correctly

Fix: Fixed formatting bug when entering commands into the Address Bar

---

src/Files.App/Utils/Cloud/CloudDrivesDetector.cs

Hi, I'm a developer at the company [Nutstore](https://www.jianguoyun.com/), I've found out that the cloud drive detection logic for Nutstore in PR #10890 is incorrect. 
Searching all the sub-directories named "Nutstore" in `%userprofile%` can be extremely time-consuming and will likely cause the Files app the stop responding, it may also result in multiple incorrect Nutstore cloud drive entries. 
Querying the registry entries in `SyncRootManager` is a more efficient way to detect the root dir of the Nutstore cloud drive.

Fix: Fixed an issue with Nutstore cloud drive detection

---

src/Files.App/ViewModels/UserControls/Widgets/QuickAccessWidgetViewModel.cs

Fix: Fixed NullReferenceException in QuickAccessWidgetViewModel.NavigateToPath

---

src/Files.App/Actions/FileSystem/BaseDeleteAction.cs

Fix: Fixed NullReferenceException in BaseDeleteAction.DeleteItemsAsync

---

src/Files.App/Views/Shells/BaseShellPage.cs

- Closes #15464
1. Turn off file extension display setting
2. Execute search by a file extension (e.g. `txt`)
3. Switch to another tab
4. Switch back to the search result tab
5. The search result will be displayed correctly

Fix: Fixed issue where search result stopped showing when switching tabs

---

src/Files.App/ViewModels/Properties/Items/CombinedFileProperties.cs

- Closes #15468 
1. Select multiple media files.
2. Open properties window and select Details tab.
3. See duration.

Feature: Added support for displaying total duration when selecting multiple video files

---

src/Files.App/Views/Shells/ModernShellPage.xaml

This issue has been there but we’d never noticed because there’s splitter that had the same color and it’d overwritten.
- https://discord.com/channels/725513575971684472/725514946112127057/1245057778788208691

Code Quality: Fixed an issue where the forward icon was wrongly clipped

---

src/Files.App/Strings/en-US/Resources.resw
src/Files.App/ViewModels/Properties/Items/BaseProperties.cs
src/Files.App/ViewModels/UserControls/Previews/ArchivePreviewViewModel.cs

- From #15503 
TODO list: https://github.com/files-community/Files/issues/15503#issuecomment-2138404595
**Stage three**
<details ><summary>☑️ PropertiesFilesAndFoldersCountString ----> <b>PropertiesFilesAndFoldersCountString</b></summary>
<p>
https://github.com/files-community/Files/blob/af0ab75334fc38273042201bc73119dd4e470b26/src/Files.App/Strings/en-US/Resources.resw#L471-L473
</p>
</details>
<details ><summary>☑️ PropertiesFilesFoldersAndLocationsCountString ----> <b>PropertiesLocationsCountString</b></summary>
<p> …

Code Quality: Convert Multiple Localized Strings to ICU Message Format | Stage Three

---

src/Files.App/Extensions/MessageFormatExtensions.cs

Resolved / Related Issues
To prevent extra work, all changes to the Files codebase must link to an approved issue marked as Ready to build. Please insert the issue number following the hashtag with the issue number that this Pull Request resolves.
From #15503
TODO list: https://github.com/files-community/Files/issues/15503#issuecomment-2138404595
**Add custom number format**
Add better number format from default `1,000,000.000` to `1 000 000.000` via custom format for used this `{0, number}`

Code Quality: Convert Multiple Localized Strings to ICU Message Format | Add custom number format

---

src/Files.App/Views/PaneHolderPage.xaml.cs

https://discord.com/channels/725513575971684472/958783217941487616/1245094972043296848
- An issue where there is no switching between panels using the touch screen.
1. Switch between panels in Dual Pane mode via touch on touch screen

Fix: Fixed an issue where panes couldn't be switched via touch

---

src/Files.App/Strings/en-US/Resources.resw
src/Files.App/ViewModels/Dialogs/FileSystemDialog/FileSystemDialogViewModel.cs
src/Files.App/ViewModels/Properties/Items/BaseProperties.cs

- From #15503 
- From https://github.com/files-community/Files/pull/15507#discussion_r1621631346
- From https://github.com/files-community/Files/pull/15514#discussion_r1621613569
TODO list: https://github.com/files-community/Files/issues/15503#issuecomment-2138404595
**Fix word order problem**
<details><summary>☑️ ConflictingItemsDialogSubtitleMultipleConflictsMultipleNonConflicts, ConflictingItemsDialogSubtitleSingleConflictMultipleNonConflicts, ConflictingItemsDialogSubtitleSingleConflictNoNonConflicts, …

Code Quality: Convert Multiple Localized Strings to ICU Message Format | Fix word order problem

---

src/Files.App/Views/Settings/ActionsPage.xaml

**Fix when the description text is not displayed in full**
From:
To:

Fix: Fixed an issue where text on the Actions Settings page didn't wrap

---

src/Files.App/ViewModels/Dialogs/DecompressArchiveDialogViewModel.cs
src/Files.App/Views/Properties/LibraryPage.xaml.cs

- Closes #15550 
1. Right-click an archive.
2. Select Extract -> Extract files.
3. Click the Browse button and select a destination folder.
4. It no longer crashes and can be extracted normally.

Code Quality: Fixed an issue where folder selection dialog wouldn't work

---

src/Files.App/Dialogs/ReleaseNotesDialog.xaml
src/Files.App/Dialogs/ReleaseNotesDialog.xaml.cs

Code Quality: Added support for clinking links in the release notes

---

src/Files.App/Services/DateTimeFormatter/ApplicationDateTimeFormatter.cs
src/Files.App/Strings/en-US/Resources.resw

- Closes #15554
1. Try loading bigger folder e.g. `C:/Windows/System32`
2. It is now faster to load strings with formatting using `GetLocalizedFormatResource`

Code Quality: Reverting changes for DateTime formatting without ICU

---

src/Files.App/Utils/FileTags/FileTagsHelper.cs

Fix: Fixed NullReferenceException in RegistryHelpers.CombineKeys

---

src/Files.App/Actions/Content/Background/BaseSetAsAction.cs
src/Files.App/Actions/Content/ImageManipulation/BaseRotateAction.cs
src/Files.App/Data/Factories/ContentPageContextFlyoutFactory.cs
src/Files.App/Data/Items/ListedItem.cs
src/Files.App/Data/Models/SelectedItemsPropertiesViewModel.cs
src/Files.App/Utils/Storage/Enumerators/Win32StorageEnumerator.cs
src/Files.Shared/Helpers/FileExtensionHelpers.cs

- Closes #14975
2. Hover over an image file
3. See if it is corrupt image or dimention property is unavailable it wont be shown

Feature: Added dimensions to tooltip when hovering over image files

---

src/Files.App/UserControls/InnerNavigationToolbar.xaml
src/Files.App/UserControls/Pane/InfoPane.xaml
src/Files.App/UserControls/TabBar/TabBar.xaml
src/Files.App/UserControls/TabBar/TabBar.xaml.cs
src/Files.App/Views/MainPage.xaml
src/Files.App/Views/MainPage.xaml.cs

This makes the app content area look more appropriate when the window a bit stuck or hang on startup because background and border will be rendered actually loaded. Previously Inner toolbar background are rendered without inner controls are loaded, before it actually loaded.
- Assign background/border properties in respective controls
- Unwrap from `Border` element
- Removed unnecessary assignments to `d:DesignHeight`, `d:DesignWidth`, `TabStripVisibility (always true)` and so on.
- Closes #
Stability is a top priority for Files and all changes are required to go …

Code Quality: Assign background/border properties in respective controls

---

src/Files.App/ViewModels/UserControls/InfoPaneViewModel.cs
src/Files.App/Views/MainPage.xaml.cs

- Closes #15599
I'm not sure if this is the best fix, but it should at least prevent the crash.

Fix: Prevent issue "WinUI Desktop Window object has already been closed"

---

src/Files.App.Server/Files.App.Server.csproj
src/Files.App.Server/Helpers.cs
src/Files.App.Server/NativeMethods.txt
src/Files.App.Server/Program.cs
src/Files.App/Files.App.csproj
src/Files.App/Services/Storage/StorageNetworkService.cs

This simplifies some of our code, and eliminates the compiler warnings we saw from the `Files.App.Server` project due to that version being particularly old.
I'm actually volunteering this PR in response to an issue a Files community member filed against CsWin32, when it actually wasn't a bug there, but just old code in _this_ repo.
- Closes https://github.com/microsoft/CsWin32/issues/1214
I launched the program according to your README file, but the `Files.App.Server.dll` apparently never even loaded, so **I don't know how to test it.**

Code Quality: Bump CsWin32 to latest available

---

src/Files.App/Views/Layouts/DetailsLayoutPage.xaml.cs

- Closes #15665
2. Opened folder in Details View
3. Checked that the width of the column changes correctly according to the mouse move
4. Checked that column width auto align function is not broken by new changes

Fix: Fixed an issue where the cursor wasn't inline when resizing columns in Details View

---

src/Files.App/Utils/Storage/Search/FolderSearch.cs

- Closes #15602 
- Closes #15658 
2. ...

Fix: Fixed InvalidOperationException in FolderSearch.AddItemsForHomeAsync

---

src/Files.App/Utils/Storage/Search/FolderSearch.cs
src/Files.App/ViewModels/Properties/Items/FileProperty.cs

Fix: Fixed InvalidOperationException in FileProperty.RetrieveAndInitializePropertiesAsync

---

src/Files.App/Data/Items/ListedItem.cs
src/Files.App/Views/Layouts/ColumnLayoutPage.xaml
src/Files.App/Views/Layouts/GridLayoutPage.xaml

- Closes #
1. Put a breakpoint on ListedItem.cs line 49 and run Files in debug mode.
2. Confirm line 49 is executed only when the pointer is entered into an item.
3. Hover over an online image file.
4. Confirm that the tooltip doesn't show dimension.

Fix: Fixed an issue where online files were downloaded when loading tooltips

---

src/Files.App/UserControls/FilePreviews/MarkdownPreview.xaml
src/Files.App/UserControls/FilePreviews/MarkdownPreview.xaml.cs

https://discord.com/channels/725513575971684472/725514946112127057/1256186521124605962
2. Select a markdown
3. View preview of it
4. Click on a link

Feature: Added support for clicking links when previewing markdown files

---

src/Files.App/Views/Properties/MainPropertiesPage.xaml.cs

https://discord.com/channels/725513575971684472/725514946112127057/1256366789839818804
2. Open a properties window
3. Deactivate
4. See the right foreground (follow the same steps in stable build)

Fix: Fixed an issue where non-cached windows sometimes had the wrong theme

---

.github/workflows/cd-preview.yml
.github/workflows/cd-stable.yml
.github/workflows/ci.yml

GitHub: Update version of some actions

---

src/Files.App/ViewModels/ShellViewModel.cs

Code Quality: Fixed ArgumentNullException in ShellViewModel.CheckForBackgroundImage()

---

src/Files.App/Utils/RecycleBin/RecycleBinManager.cs

- https://files-org.sentry.io/issues/5610462140/events/0d15202895df4621bcde5b01ed4bc2e6/
2. ...

Fix: Fixed FileNotFoundException in Recycle Bin watcher

---

src/Files.App/ViewModels/ShellViewModel.cs

There's no need to perform reordering every time some files are loaded, because the interval between each reordering is 500ms, which is too short for users to see the sorted results before it's reordered again. This means that during the file loading process, the sorting results are useless to users, and it also causes a lot of extra CPU computational overhead, leading to lag in the file loading process. It's sufficient to perform a single sorting of all files only after the file list has finished loading completely.
- Closes #https://github.com/files-community/Files/issues/15830
- Opens #https://github.com/files-community/Files/issues/4180
Stability is a top priority for Files and all changes are required to go through …

Code Quality: Optimize the code logic for loading the file list

---

src/Files.App/Constants.cs
src/Files.App/Data/Items/DriveItem.cs
src/Files.App/Services/Storage/StorageDevicesService.cs
src/Files.App/Utils/Cloud/Detector/LucidLinkCloudDetector.cs
src/Files.App/Utils/Shell/ContextMenu.cs
src/Files.App/Utils/Storage/Helpers/StorageSenseHelper.cs
src/Files.App/ViewModels/Dialogs/CreateShortcutDialogViewModel.cs
src/Files.App/ViewModels/Properties/BasePropertiesPage.cs

Code Quality: Fallback to "C:\" when var doesn't work

---

src/Files.App/Helpers/Application/AppLifecycleHelper.cs

- Closes #15857
1. Opened Files (default settings)
2. Set Files as default file manager
3. Closed all tabs
4. Opened Files from third party app
5. Confirmed the correct location launched
6. Closed all tabs
7. Opened Files regularly
8. Confirmed the Home Page was opened
9. Opened a folder in Files
10. Restarted Files and …

Fix: Fixed issue where Home Page was opened when Files was launched with custom param

---

src/Files.App/ViewModels/ShellViewModel.cs
src/Files.App/Views/HomePage.xaml.cs

- Closes #
1. Open a folder that has a custom background image.
2. Navigate to Home.
3. See the background image disappears.

Code Quality: Fixed an issue where folder background image would remain when navigating to Home page

---

src/Files.App/Actions/Start/PinToStartAction.cs
src/Files.App/Actions/Start/UnpinFromStartAction.cs

Fix: Fixed DirectoryNotFoundException when pinning items to the start menu

---

src/Files.App/MainWindow.xaml.cs

- Closes https://files-org.sentry.io/issues/5543175351/events/41b136c83da54594ba620829b852ce17/
2. ...

Code Quality: Handle WinUI Desktop Window already closed

---

src/Files.App/Services/Windows/WindowsIniService.cs

- Closes #15875 
1. Add duplicate keys in desktop.ini.
2. Open the folder which contains that desktop.ini.
3. See the custom background feature works.

Code Quality: Fixed System.ArgumentException in WindowsIniService.GetData

---

src/Files.App/Views/Layouts/BaseLayoutPage.cs

- Closes #8534 
- Closes #15308 
These changes make the behavior of opening or dragging and dropping multiple files consistent with Files Explorer.
1. Prepare 6 video files, named 1-6
2. Select them in any order
3. Click play all on tool bar or enter on keyboard
4. The 6 files open in the player in the same order as they appear in the file list
5. Set sorting to "by name ascending"
6. Select the 6 files in any order
7. Right-click on file 3, choose "Open" from the menu
8. The 6 files open in the player in the order: 3 -> 4 -> 5 -> 6 -> 1 -> 2
9. Select the 6 files in any order
10. Drag file 3 and drop on a Windows Media Player window
11. The 6 files open in the player in the order: 3 -> 4 -> 5 -> 6 -> 1 -> 2

Fix: Fixed an issue where dragging or opening multiple items would use the wrong sort mode

---

src/Files.App/Actions/Show/ToggleDotFilesSettingAction.cs
src/Files.App/Data/Commands/Manager/CommandCodes.cs
src/Files.App/Data/Commands/Manager/CommandManager.cs
src/Files.App/Data/Commands/Manager/ICommandManager.cs
src/Files.App/Strings/en-US/Resources.resw

- Closes #15905
1. Confirmed the "Toggle dot files setting" works properly

Feature: Added an action to toggle the dot files setting

---

src/Files.App.Controls/ThemedIcon/ThemedIcon.xaml
src/Files.App.Controls/ThemedIcon/ThemedIconLayer/ThemedIconLayer.xaml

Set the TabStop to false, so ThemedIcon and ThemedIconLayers do not get included in tabbing
- Closes #
2. ...

Code Quality: Fixed tab navigation in ThemedIcon control

---

src/Files.App/ViewModels/UserControls/Widgets/DrivesWidgetViewModel.cs

Fix: Fixed NullReferenceException in DrivesWidgetViewModel.NavigateToPath

---

src/Files.App/Dialogs/CreateShortcutDialog.xaml
src/Files.App/Dialogs/CreateShortcutDialog.xaml.cs
src/Files.App/Helpers/UI/UIFilesystemHelpers.cs
src/Files.App/ViewModels/Dialogs/CreateShortcutDialogViewModel.cs
src/Files.Shared/Helpers/PathHelpers.cs

- Closes #15928
1. Right click in a folder
2. Click New -> Shortcut in the context menu
3. Type "cmd /?" in the textbox
4. Before: You got a prompt saying "Invalid location"
After: Shortcut successfully created
5. (After) Open the shortcut and see the cmd help text
**-- Update --**
These modifications make the behavior of creating shortcuts more consistent with File Explorer.
These modifications can be tested by creating the following shortcuts, all of which are supported by File Explorer but not supported by Files before:
1. `cmd`
2. `cmd.exe`
3. `cmd /?`
4. `  cmd`
5. `"C:\Windows\System32\cmd.exe" /?`
6. `C:\Windows\System32\cmd.exe /?`
7. `"C:\Program Files\PowerShell\7\pwsh.exe" -c cmd /?`
8. …

Fix: Fixed an issue where shortcuts couldn't be created for commands

---

src/Files.App/Data/Models/PinnedFoldersManager.cs

Fix: Fixed NullReferenceException in PinnedFoldersManager.CreateLocationItemFromPathAsync

---

.github/NOTICE.md
src/Files.App/Data/Contexts/Window/WindowContext.cs
src/Files.App/Data/Items/WindowEx.cs
src/Files.App/Files.App.csproj
src/Files.App/MainWindow.xaml
src/Files.App/MainWindow.xaml.cs
src/Files.App/NativeMethods.txt
src/Files.App/Utils/Storage/Helpers/FilePropertiesHelpers.cs
src/Files.App/ViewModels/Settings/AboutViewModel.cs

As WinAppSdk has been improved, thanks to its team, we have reached at a point where we can move to WinAppSdk with a little Win32 API. Shout out to outgoing WinUIEx, which has been giving us the fundamental and powerful features since our initial migration for almost two years.
Note to someone who are looking for the same achievement:
- **Backdrop**: replaced with WinAppSdk
- **Window Size**: replaced with WinAppSdk
- **IsMaximizable/IsMinimizable**: replaced with WinAppSdk
- **MinWidth/MinHeight**: Implemented custom WndProc via CsWin32 using MINMAXSIZEINFO in WindowEx
- **Last window placement**: Saved/restored to ApplicationDataContainer (WINDOWPLACEMENT as base64) in WindowEx
- Closes #12358
2. Resize to be minimum (see if min size info is set)
3. Terminate the app …

Code Quality: Removed WinUIEx dependency

---

src/Files.App/Services/Windows/WindowsDialogService.cs

- Related: #15000
1. Open Files
2. Go to Home
3. Enable Network section
4. Click Map network to show the network connection dialog

Code Quality: Removed Vanara from WindowsDialogService

---

src/Files.App/UserControls/FilePreviews/MediaPreview.xaml.cs

- Closes #14791
1. Confirmed the media player source is cleared when unloading media player

Fix: Fixed OutOfMemoryException in the preview pane

---

src/Files.App/Utils/Cloud/CloudDrivesDetector.cs
src/Files.App/Utils/Cloud/CloudProviders.cs

- Closes #15475
1. kDrive is displayed in Files and copying of files etc. is possible
Note: The Sync Status column is not displayed, but this does not work in Windows File Explorer either. I think kDrive does not set the property [“System.FilePlaceholderStatus”](https://github.com/files-community/Files/blob/main/src/Files …

Feature: Added support for Infomaniak kDrive

---

src/Files.App.CsWin32/NativeMethods.json

This prevents from triggering COMException inside of .NET marshal and helps me to check HRESULT

Code Quality: Force PreserveSig to all COM methods generated by CsWin32

---

src/Files.App/Helpers/Application/AppLifecycleHelper.cs
src/Files.App/Services/App/AppUpdateSideloadService.cs

- Closes #15688
1. Disable Windows Event Log service in Service applet.
2. Launch Files.
3. Now the app starts without crashing.

Fix: Fixed a crash when Windows Event Log service was not running

---

src/Files.App/App.xaml.cs
src/Files.App/Data/Items/WindowEx.cs
src/Files.App/Helpers/Application/AppLifecycleHelper.cs
src/Files.App/Helpers/UI/AppSystemBackdrop.cs

Fix: Fixed a crash that would occur when closing the main window

---

src/Files.App.CsWin32/Windows.Win32.ComPtr.cs

Code Quality: Introduced ComPtr for unmanaged COM pointers

---

src/Files.App/Services/PreviewPopupProviders/QuickLookProvider.cs

- https://files-org.sentry.io/issues/5525344341/events/a340edbf9c384ccb9675ce5dbf155c37/
2. ...

Code Quality: Use EncoderReplacementFallback in QuickLook preview provider

---

src/Files.App/UserControls/Menus/FileTagsContextMenu.cs

- https://files-org.sentry.io/issues/5811055100/events/59fdde21245e4ee6950305402b71bfc9/
2. ...

Fix: Fixed InvalidOperationException in FileTagsContextMenu

---

.gitignore

Updated the `.gitignore` file with the one in the head https://github.com/github/gitignore repo
This is not a strictly necessary change but contains some exclusions that add to the code quality.

Code Quality: Update `.gitignore`

---

src/Files.App/Data/Models/PinnedFoldersManager.cs

This could have occurred when many files were opened/copied/moved/deleted simultaneously.
https://files-org.sentry.io/issues/5835710720/?project=4507376940351488
2. ...

Fix: Fixed InvalidOperationException in SidebarViewModel.Manager_DataChanged

---

src/Files.App/Services/SizeProvider/CachedSizeProvider.cs
src/Files.App/ViewModels/ShellViewModel.cs

This could have occurred when folder size calculation is on and a folder containing many items is displayed
https://files-org.sentry.io/issues/5834287744/?project=4507376940351488
2. ...

Fix: Fixed InvalidOperationException in ShellViewModel.FolderSizeProvider_SizeChanged

---

src/Files.App/Files.App.csproj
src/Files.App/MainWindow.xaml
src/Files.App/MainWindow.xaml.cs
src/Files.App/Utils/Storage/Helpers/FilePropertiesHelpers.cs

Code Quality: Bring back WinUIEx

---

src/Files.App (Package)/Files.Package.wapproj
src/Files.App.Controls/Files.App.Controls.csproj
src/Files.App.Controls/ThemedIcon/ThemedIcon.cs
src/Files.App.Launcher/Files.App.Launcher.vcxproj
src/Files.App.Launcher/packages.config
src/Files.App/Files.App.csproj
src/Files.App/Utils/Storage/Operations/FileOperationsHelpers.cs
src/Files.App/Utils/Storage/Operations/FilesystemHelpers.cs
src/Files.App/Views/Layouts/BaseLayoutPage.cs
tests/Files.App.UITests/Files.App.UITests.csproj
tests/Files.InteractionTests/Files.InteractionTests.csproj
tests/Files.InteractionTests/Helper/AxeHelper.cs
tests/Files.InteractionTests/Tests/FolderTests.cs

WASDK 1.6: Fix build and tests

---

src/Files.App/Actions/FileSystem/RenameAction.cs
src/Files.App/Dialogs/BulkRenameDialog.xaml
src/Files.App/Dialogs/BulkRenameDialog.xaml.cs
src/Files.App/Services/App/AppDialogService.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/ViewModels/Dialogs/BulkRenameDialogViewModel.cs

- Closes #8191 
1. Triggered rename action for single file/folder and confirmed the existing workflow is used
2. Triggered rename with multiple items selected (both files and folders) and confirmed the name validation worked
3. Confirmed the new name doesn't replace the file extensions
4. Confirmed numbers are added when …

Feature: Added support for bulk rename

---

src/Files.App.CsWin32/NativeMethods.txt
src/Files.App.CsWin32/Windows.Win32.ComHeapPtr.cs

- Related #16071
- Related #15000
_None_

Code Quality: Introduced ComHeapPtr

---

src/Files.App/UserControls/Sidebar/SidebarItem.cs

> **Note:** The solution to the issue was a simple change: setting the `IsTabStop` attribute to `False`. This was necessary as we were excluding focus from each selected element.
- Closes #16145 
2. Press "Tab" (You can see focused element)
3. Use the 'Down' and 'Up' arrow keys (you won't be able to see the focused element, but it will change. When you press 'Tab' again, you will see the border on the element where the focus is. If you try to move to the next element, it will change, but without a visible border)."

Fix: Fixed an issue when navigating the sidebar with the tab key

---

.github/workflows/ci.yml

- *Planned internally*
The integration tests became very moody and fail frequently. Let's make it run 3 times at maximum when failed.
_None_

GitHub: Retry integration tests when failed

---

src/Files.Shared/Utils/Logger/FileLogger.cs

This change may prevent the following crash.
https://files-org.sentry.io/issues/5835250758/?project=4507376940351488
- Closes #
2. ...

Code Quality: Use lock statements in FileLogger

---

src/Files.App/ViewModels/Properties/CustomizationViewModel.cs
src/Files.App/Views/Properties/CustomizationPage.xaml

- Closes #15941
1. Confirmed entering path loads dll file in properties window

Feature: Enabled support for inputting custom icon path

---

src/Files.App/Helpers/Dialog/DynamicDialogFactory.cs
src/Files.App/Helpers/UI/UIFilesystemHelpers.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/ViewModels/Dialogs/CreateItemDialogViewModel.cs

- Closes #16239
1. Confirmed dialog displays the type of item being created

Feature: Improved UX for the "Create new item" dialog

---

src/Files.App/Actions/Open/OpenClassicPropertiesAction.cs

I did a wrong review to this PR and found there's a GC hole.
- Related: #16031
_None_

Code Quality: Fixed a GC hole in OpenClassicPropertiesAction

---

.gitattributes

Absolutely _miniscule_ change, but this makes the C++ header files in the Visual C++ projects detected as C++ rather than C as GitHub Linguist assumes.

GitHub: Make C++ headers actually detect as C++

---

.github/workflows/ci.yml
.github/workflows/format-xaml.yml
src/Files.App/Views/MainPage.xaml

GitHub: Fixed XAML formatting checker

---

src/Files.App/ViewModels/UserControls/Widgets/BaseWidgetViewModel.cs

- Closes #16404
1. Maximized the window
2. Right clicked an item on the home page (on the edge of the screen)
3. Confirmed the context menu was fully shown

Fix: Fixed context menu placement on the home page

---

.github/workflows/cd-store.yml

*Planned internally*
We have planned to move all CI/CD to GHA. However, the CD for Microsoft Store had a workflow that was incompatible with GHA and we haven't been able to migrate (StoreBroker ps module should work for us to upload a msix package).
This introduces a new workflow for the Store CD but doesn't contain steps to upload packages to Microsoft Store via StoreBroker yet. Hence, we still have to upload it manually.
1. Merge this
2. Run the CD and check if the msixupload will be generated.

GitHub: Introduce GHA CD to Microsoft Store

---

src/Files.App/Actions/FileSystem/CopyItemPathAction.cs
src/Files.App/Actions/FileSystem/CopyItemPathWithQuotesAction.cs
src/Files.App/Actions/FileSystem/CopyPathWithQuotesAction.cs
src/Files.App/Data/Commands/Manager/CommandCodes.cs
src/Files.App/Data/Commands/Manager/CommandManager.cs
src/Files.App/Data/Commands/Manager/ICommandManager.cs
src/Files.App/Data/Factories/ContentPageContextFlyoutFactory.cs
src/Files.App/Strings/en-US/Resources.resw

- Closes #
1. Confirmed that both the "Copy path" and "Copy path with quotes" actions work correctly

Feature: Added an action to copy the path of the current directory

---

src/Files.App/Actions/FileSystem/PasteItemAsShortcutAction.cs
src/Files.App/Data/Commands/Manager/CommandCodes.cs
src/Files.App/Data/Commands/Manager/CommandManager.cs
src/Files.App/Data/Commands/Manager/ICommandManager.cs
src/Files.App/Data/Factories/ContentPageContextFlyoutFactory.cs
src/Files.App/Helpers/UI/UIFilesystemHelpers.cs
src/Files.App/Strings/en-US/Resources.resw

- Closes #16371
1. Confirmed copied items are pasted as shortcuts

Feature: Added support for pasting items as shortcuts

---

src/Files.App/Actions/Navigation/CloseActivePaneAction.cs
src/Files.App/Actions/Navigation/CloseAllTabsAction.cs
src/Files.App/Actions/Navigation/CloseTabBaseAction.cs
src/Files.App/Data/Commands/Manager/CommandCodes.cs
src/Files.App/Data/Commands/Manager/CommandManager.cs
src/Files.App/Data/Commands/Manager/ICommandManager.cs
src/Files.App/Helpers/Navigation/MultitaskingTabsHelpers.cs
src/Files.App/Strings/en-US/Resources.resw

- Closes #16414
- Changed default shortcut for 'Close active pane' to `ctrl+alt+w` to prevent a conflict with the 'Close all tabs' action.
1. Confirmed the action closes all tabs

Feature: Added an action to close all tabs

---

src/Files.App.CsWin32/Windows.Win32.ComHeapPtr.cs
src/Files.App.CsWin32/Windows.Win32.ComPtr.cs

- Related #16071
- Related #15000
> [!NOTE]
> While I settled on this method to QI for now, we may want to use IDynamicInterfaceCastable, which is Hez let me know, after .NET 9 (stack allocation for classes) becomes GA. I need more exploration but this enables us to utilize `is` and `as` with QI called implicitly.
_None_

Code Quality: Introduced ComPtr.As() to QI easily

---

src/Files.App/Actions/FileSystem/CreateAlternateDataStreamAction.cs
src/Files.App/Data/Commands/Manager/CommandCodes.cs
src/Files.App/Data/Commands/Manager/CommandManager.cs
src/Files.App/Data/Commands/Manager/ICommandManager.cs
src/Files.App/Data/Contracts/IApplicationSettingsService.cs
src/Files.App/Data/Contracts/IGeneralSettingsService.cs
src/Files.App/Data/Factories/ContentPageContextFlyoutFactory.cs
src/Files.App/Helpers/Dialog/DialogDisplayHelper.cs
src/Files.App/Helpers/Dialog/DynamicDialogFactory.cs
src/Files.App/Services/Settings/ApplicationSettingsService.cs
src/Files.App/Services/Settings/GeneralSettingsService.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/ViewModels/Settings/GeneralViewModel.cs
src/Files.App/Views/Settings/GeneralPage.xaml

- Closes #16337
1. Confirmed the option is disabled in the root path
2. Confirmed the feature works for single and multiple items
3. Confirmed the menu option is only shown when the setting is enabled

Feature: Added support for creating alternate data streams

---

src/Files.App/Actions/Open/OpenSettingsAction.cs
src/Files.App/Data/Contracts/INavigationControlItem.cs
src/Files.App/Data/Parameters/SettingsDialogNavigationParams.cs
src/Files.App/Data/Parameters/SettingsNavigationParams.cs
src/Files.App/Dialogs/SettingsDialog.xaml.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/ViewModels/UserControls/SidebarViewModel.cs

- Closes #12146 12146
- Right click on `Tags` section header in the sidebar
- Click `Manage tags`
1. I used the steps described above
**Future Developments**
Should we add a *second-level* target (like a specific section of a page)?

Feature: Added an option to manage tags when right clicking on the sidebar

---

src/Files.App/Data/Contracts/ICommonDialogService.cs
src/Files.App/Services/Windows/WindowsDialogService.cs

- Fixed GC hole
- Fixed an issue where it throws an exception even though the method returns NO_ERROR (0).
1. Open the connection dialog
2. Close it

Code Quality: Fixed a GC hole in the network connection dialog

---

src/Files.App/UserControls/PathBreadcrumb.xaml
src/Files.App/UserControls/PathBreadcrumb.xaml.cs
src/Files.App/ViewModels/UserControls/AddressToolbarViewModel.cs

- Closes #16144 
1. Click the chevron on the address bar breadcrumb
2. Observe the dropdown appears only once (I suggest using a path containing many folders)
**After / Before**
https://github.com/user-attachments/assets/83eb2dbd-fd19-4f66-9dab-c8dadc8d0107

Fix: Fixed an issue where the address bar flyouts displayed duplicate items

---

src/Files.App/Views/MainPage.xaml.cs

Feature: Reduced frequency of the review Files prompt

---

src/Files.App/Helpers/Navigation/NavigationHelpers.cs

Feature: Removed number of open tabs from the app title

---

src/Files.App.CsWin32/Windows.Win32.Extras.cs
src/Files.App/App.xaml.cs
src/Files.App/Helpers/Win32/Win32Helper.WindowManagement.cs
src/Files.App/MainWindow.xaml.cs
src/Files.App/Views/Layouts/BaseLayoutPage.cs
src/Files.App/Views/Layouts/ColumnLayoutPage.xaml
src/Files.App/Views/Layouts/DetailsLayoutPage.xaml
src/Files.App/Views/Layouts/GridLayoutPage.xaml

- Added support for not focusing Files window when dragging a file/folder
- Closes #13255
1. Opened Files and File Explorer.
2. Select files in Files.
3. Move File Explorer on the top, which is topper than Files. Make sure it doesn't cover Files so that you can drag files from Files.
4. Drag the selected files to the File Explorer. And you can find the Files won't move to the top when dragging files.

Feature: Improved behavior when dragging items from an unfocused Files window

---

src/Files.App.CsWin32/NativeMethods.txt
src/Files.App.CsWin32/Windows.Win32.Extras.cs
src/Files.App/MainWindow.xaml.cs
src/Files.App/Views/Layouts/BaseLayoutPage.cs

Replaced private const & struct with CsWin32 & Improve comments following @0x5bfa 's comments for #16508.

Code Quality: Replaced private const & struct with CsWin32 & Improve comments

---

src/Files.App/Actions/Open/OpenReleaseNotesAction.cs
src/Files.App/Constants.cs
src/Files.App/Data/Commands/Manager/CommandCodes.cs
src/Files.App/Data/Commands/Manager/CommandManager.cs
src/Files.App/Data/Commands/Manager/ICommandManager.cs
src/Files.App/Data/Contracts/IUpdateService.cs
src/Files.App/Dialogs/ReleaseNotesDialog.xaml
src/Files.App/Dialogs/ReleaseNotesDialog.xaml.cs
src/Files.App/Helpers/Application/AppLifecycleHelper.cs
src/Files.App/Services/App/AppUpdateNoneService.cs
src/Files.App/Services/App/AppUpdateSideloadService.cs
src/Files.App/Services/App/AppUpdateStoreService.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/UserControls/AddressToolbar.xaml
src/Files.App/ViewModels/Dialogs/ReleaseNotesDialogViewModel.cs
src/Files.App/ViewModels/UserControls/AddressToolbarViewModel.cs

- Added action to open release notes
- The toolbar button now displays on all tabs (previously it only worked on the first tab opened after an update)
- Added WebView to display the blog post
2. ...

Feature: Added new format for displaying Release Notes

---

.github/scripts/Configure-AppxManifest.ps1
src/Files.App (Package)/Package.appxmanifest
src/Files.App.Launcher/FilesLauncher.cpp
src/Files.App.OpenDialog/FilesOpenDialog.cpp
src/Files.App.SaveDialog/FilesSaveDialog.cpp
src/Files.App/Actions/Navigation/OpenInNewWindow/BaseOpenInNewWindowAction.cs
src/Files.App/Helpers/Application/AppLifecycleHelper.cs
src/Files.App/Helpers/Navigation/NavigationHelpers.cs
src/Files.App/MainWindow.xaml.cs
src/Files.App/Program.cs
src/Files.App/Utils/Taskbar/SystemTrayIcon.cs
src/Files.App/ViewModels/Settings/GeneralViewModel.cs

Code Quality: Assigned execution alias and URI for each build

---

src/Files.App/Helpers/NaturalStringComparer.cs

New comparator is slightly faster than [DllImport(“api-ms-win-core-string-l1-1-0.dll”)].CompareStringEx. And supports Arm. Previously, a string comparer was used for Arm without proper support for natural comparison.
| Method                                 | Mean     | Error     | StdDev    | Allocated |
|--------------------------------------- |---------:|----------:|----------:|----------:|
| Test_api-ms-win-core-string-l1-1-0.dll | 1.185 ms | 0.0095 ms | 0.0084 ms |      89 B |
| Test_NaturalComparer                   | 1.072 ms | 0.0073 ms | 0.0065 ms |      89 B |

Code Quality: Improve string comparer performance

---

src/Files.App/Data/Items/LocationItem.cs

- Closes #14108
- Unpin Recycle Bin from the sidebar
- Create 25,000 blank text files from cmd line
- Delete all of the files via File Explorer
- Go back to Files and delete a single file, verify that the app does NOT stop responding
- Pin Recycle Bin to the sidebar again and restart Files and verify that the app does …

Fix: Resolved startup freeze issue caused by a heavily populated Recycle Bin

---

src/Files.App.Controls/ThemedIcon/ThemedIcon.Properties.cs
src/Files.App.Controls/ThemedIcon/ThemedIcon.cs
src/Files.App.Controls/ThemedIcon/ThemedIcon.xaml

- Closes #16548 
1. Open a folder containing some tagged items
2. Change sort order
3. Then, check that tag icons in the following controls are using the appropiate color : `Settings/Tags`, `Sidebar>Tags`, `Home>Tags Widget`, `Preview Pane`, `Right click context menu`
**Notes**
I changed the bindings (I think we may …

Fix: Fixed an issue where tags would sometimes display with the wrong color

---

src/Files.App/Views/Layouts/BaseLayoutPage.cs

- Closes #15564 
- Closes #16618 
- Related: #11735
This should help with drag&drop compatibility.
MPC, PowerDirector, XShell, Corel Photo-Paint, Phone Link, Visual Studio, WhatsApp, Unigram, Wordpad, Edge: OK
Notepad, Notepad++: not ok (OK when dropping outside text area)
1. Drag & drop file from Files to MPC or …

Fix: Fixed issues with drag & drop to other applications

---

src/Files.App/Data/Factories/ContentPageContextFlyoutFactory.cs
src/Files.App/ViewModels/UserControls/SidebarViewModel.cs
src/Files.App/ViewModels/UserControls/Widgets/DrivesWidgetViewModel.cs
src/Files.App/ViewModels/UserControls/Widgets/FileTagsWidgetViewModel.cs
src/Files.App/ViewModels/UserControls/Widgets/NetworkLocationsWidgetViewModel.cs
src/Files.App/ViewModels/UserControls/Widgets/QuickAccessWidgetViewModel.cs

- Closes #16626 
1. Enable the three `Show option to open folders in...` settings
2. Right click a file, see that none of the options are visible
3. Right click a folder
**Notes**
Please read the issue's comments.
I decided to go with the second option described there. Let me know if this is fine.
(Actually there's a …

Fix: Fixed issue where right clicking a file would display options to open in new tab

---

src/Files.App/Views/ShellPanesPage.xaml.cs

- Closes #15776
Added the same check that is present on right tapped event.
1. Click on empty space of column view and check the active column does not change

Fix: Fixed an issue which caused unexpected scrolling in the Columns Layout

---

src/Files.App/MainWindow.xaml.cs

- Closes #16641
1. Type "files-dev.exe ." and check it opens in current terminal folder

Fix: Fixed issue where launching Files from terminal didn't use the correct path

---

src/Files.App/ViewModels/UserControls/SidebarViewModel.cs

- Closes #16637
Added the missing code for setting a tag when a file is dropped on the tags sidebar section.
1. Drag&drop files from the file list to a tag on the sidebar

Feature: Added back support for applying tags by dropping files on the sidebar

---

src/Files.App/UserControls/AddressToolbar.xaml
src/Files.App/UserControls/AddressToolbar.xaml.cs

- Closes #7077
1. Pressing the Tab key when the Refresh button (or Home button) is focused will switch the focus to the breadcrumb bar and enable edit mode.
2. Pressing the Tab key again will turn off edit mode and allow navigation within the breadcrumb bar.

Fix: Fixed keyboard navigation in the address path bar

---

src/Files.App/Data/Contracts/IGeneralSettingsService.cs
src/Files.App/Services/Settings/GeneralSettingsService.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/UserControls/Pane/ShelfPane.xaml
src/Files.App/UserControls/Pane/ShelfPane.xaml.cs
src/Files.App/ViewModels/MainPageViewModel.cs
src/Files.App/ViewModels/Settings/AdvancedViewModel.cs
src/Files.App/Views/MainPage.xaml
src/Files.App/Views/Settings/AdvancedPage.xaml

Code Quality: Added feature flag to developer environment to enable 'Shelf Pane'

---

src/Files.App/Data/Contracts/ImagingService.cs
src/Files.App/Data/Items/ShelfItem.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/UserControls/Pane/ShelfPane.xaml
src/Files.App/UserControls/Pane/ShelfPane.xaml.cs
src/Files.App/Views/MainPage.xaml
src/Files.Shared/Utils/IAsyncInitialize.cs
src/Files.Shared/Utils/IWrapper.cs

This is a continuation for the Shelf feature #12490
- Dropped a couple of files and folders to validate they're being added to the list

Code Quality: Added design and basic functionality for the upcoming Shelf feature

---

src/Files.App/Utils/Storage/Search/FolderSearch.cs

- Closes #13185 
I know the related issue is not approved, but this bug was annoying me
1. Activate the Tag Widgets in the settings.
2. Assign a tag to an element.
3. Go to the homepage.
4. Click on the name of the tag assigned to this element.
5. Navigate to the properties of the element.

Fix: Fixed issue with displaying properties for tagged items

---

src/Files.App/Actions/Show/ToggleShelfPaneAction.cs
src/Files.App/Data/Commands/Manager/CommandCodes.cs
src/Files.App/Data/Commands/Manager/CommandManager.cs
src/Files.App/Data/Commands/Manager/ICommandManager.cs
src/Files.App/Data/Items/ShelfItem.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/UserControls/AddressToolbar.xaml
src/Files.App/ViewModels/UserControls/AddressToolbarViewModel.cs
src/Files.Shared/Utils/IAsyncInitialize.cs
src/Files.Shared/Utils/IWrapper.cs

Code Quality: Added action for toggling shelf pane

---

src/Files.App/UserControls/PathBreadcrumb.xaml
src/Files.App/UserControls/PathBreadcrumb.xaml.cs
src/Files.App/ViewModels/UserControls/AddressToolbarViewModel.cs
src/Files.App/Views/MainPage.xaml.cs

- Closes #16113
1. Select an item in the address bar breadcrumb via keyboard
2. Press `Space` or `Enter`
3. It goes to the corresponding path

Feature: Added support for opening breadcrumb items using the `space` and `enter` keys

---

src/Files.App.Controls/Files.App.Controls.csproj
src/Files.App/Files.App.csproj
tests/Files.App.UITests/Files.App.UITests.csproj

*Only a small dependency update.*
- Related: #4180
- Related: #16156 
2. Test various functionality
---
Upgrades WinAppSDK to 1.5.250108004. Upgrading winappsdk is always a good practice since it comes with bug fixes and performance improvements which is vital for an app like Files.

Code Quality: Upgrade `Microsoft.WindowsAppSDK` to 1.5.250108004

---

src/Files.App/Helpers/Layout/LayoutPreferencesManager.cs
src/Files.App/Helpers/Layout/LayoutSizeKindHelper.cs
src/Files.App/ViewModels/ShellViewModel.cs
src/Files.App/Views/Layouts/DetailsLayoutPage.xaml
src/Files.App/Views/Layouts/DetailsLayoutPage.xaml.cs
src/Files.App/Views/Layouts/GridLayoutPage.xaml
src/Files.App/Views/Layouts/GridLayoutPage.xaml.cs

Feature: Use DPI aware icons in the Details View and List View layouts

---

src/Files.App/Helpers/Layout/LayoutSizeKindHelper.cs
src/Files.App/ViewModels/ShellViewModel.cs
src/Files.App/Views/Layouts/ColumnLayoutPage.xaml
src/Files.App/Views/Layouts/ColumnLayoutPage.xaml.cs

Feature: Use DPI aware icons in the Columns View

---

LICENSE
src/Files.App.SaveDialog/Files.App.SaveDialog.Win32.vcxproj
src/Files.App.Server/Files.App.Server.csproj
src/Files.Core.SourceGenerator/Extensions/StringBuilderExtensions.cs

Fixes some small issues with:
- license header missing in some projects
- source generator was not updated
- removed "2025" from license file in favour of "2018-present"

GitHub: Updated license headers

---

src/Files.App/ViewModels/UserControls/Previews/ImagePreviewViewModel.cs
src/Files.Shared/Helpers/FileExtensionHelpers.cs

- Related: #10494 
- Related: #12133 
- Related: #12159
2. Downloaded the example JPEG-XR (`.jxr`) file to test:
[JXR example.zip](https://github.com/user-attachments/files/18480987/JXR.example.zip) (sorry this is in zip form because GitHub doesn't support JXR image upload directly)
3. Tested functionality in Files, including:
- Set as app/computer background
- Rotate left or right

Feature: Added support for rotating JPEG-XR images

---

src/Files.App/Extensions/ImageSourceExtensions.cs
src/Files.App/Services/App/AppUpdateSideloadService.cs
src/Files.App/Services/App/AppUpdateStoreService.cs
src/Files.App/Utils/Cloud/Detector/GoogleDriveCloudDetector.cs
src/Files.App/Utils/Cloud/Detector/SynologyDriveCloudDetector.cs
src/Files.App/Utils/Shell/LaunchHelper.cs
src/Files.App/Utils/Storage/Operations/ShellFilesystemOperations.cs
src/Files.App/Utils/Storage/StorageBaseItems/BaseStorageFile.cs
src/Files.App/Utils/Storage/StorageItems/FtpStorageFile.cs
src/Files.App/Utils/Storage/StorageItems/NativeStorageFile.cs
src/Files.App/Utils/Storage/StorageItems/SystemStorageFile.cs
src/Files.App/Utils/Storage/StorageItems/VirtualStorageFile.cs
src/Files.App/Utils/Storage/StorageItems/VirtualStorageItem.cs
src/Files.App/Utils/Storage/StorageItems/ZipStorageFile.cs
src/Files.App/Utils/Storage/StorageItems/ZipStorageFolder.cs
src/Files.App/ViewModels/Properties/HashesViewModel.cs

- Closes #15092
1. Opened Files with the updated code.
2. Verified that resources are disposed of asynchronously without blocking the UI.
3. Tested all affected scenarios for stability, including:
> - Opening and closing files
> - Performing file operations (e.g., move, copy, delete)
> - Handling zip files.

Code Quality: Convert into await using statement or declaration

---

src/Files.App/Data/Items/ListedItem.cs
src/Files.App/ViewModels/ShellViewModel.cs
src/Files.App/Views/Layouts/GridLayoutPage.xaml

Feature: Added storage information for phones and tablets

---

src/Files.App/ViewModels/ShellViewModel.cs

The problem is related to the fact that the archive, which is perceived as a folder, is not assigned a size in the `ShellViewModel.GetFileOrFolderUpdateInfoAsync()` method, unlike files, but we also do not want to assign a size to regular folders, for which this method is called, so for them the size should be left as null.
- Closes #11580
1. Create an archive using any available actions.
2. Make sure that the size is displayed correctly.

Fix: Fixed issue where the size wasn't displayed after creating a new archive

---

src/Files.App/Data/Items/WidgetFileTagsContainerItem.cs
src/Files.App/Utils/Storage/Operations/FilesystemOperations.cs
src/Files.App/Utils/Storage/Search/FolderSearch.cs
src/Files.App/Utils/Storage/StorageItems/NativeStorageFile.cs
src/Files.App/Utils/Storage/StorageItems/StreamWithContentType.cs
src/Files.App/Utils/Storage/StorageItems/SystemStorageFile.cs
src/Files.App/Utils/Storage/StorageItems/VirtualStorageFile.cs

Closes  #15095
- Reviewed all methods to ensure `CancellationToken` was correctly propagated and utilized where supported.
- Verified the following scenarios for proper handling of cancellations:
- Initializing tags using `InitAsync`.
- Canceling operations during file tag loading.
- Canceling long-running operations triggered by commands (e.g., `ViewMore`, `OpenAll`).
- Confirmed that cancellation improved responsiveness without breaking functionality.
- Tested all affected scenarios for stability, including:
- Loading file tags and icons.
- Navigating using the updated commands.
- Performing various file operations during cancellation scenarios.

Code Quality: Enhance cancellation handling in methods

---

src/Files.App/Actions/Content/Run/RunWithPowershellAction.cs
src/Files.App/Data/Factories/ShellContextFlyoutHelper.cs
src/Files.App/Helpers/Win32/Win32Helper.Storage.cs
src/Files.App/Utils/Shell/ContextMenu.cs

- Closes #16811 
1. Create a PS script that reference the working directory
2. Run it both using the toolbar's button and the context menu command

Fix: Use working directory when running PowerShell scripts

---

src/Files.App/Actions/FileSystem/EmptyRecycleBinAction.cs
src/Files.App/Actions/FileSystem/RestoreAllRecycleBinAction.cs
src/Files.App/Actions/FileSystem/RestoreRecycleBinAction.cs

This pull request aims to improve code quality and maintainability in the Files App by centralizing localization strings and replacing string literals with string constants. The changes enhance consistency, reduce the risk of typos, and streamline future updates and localization efforts.
#16718 
1. Created a centralized `Strings` class to manage all localization strings.
2. Refactored localization strings in the following actions:
- `EmptyRecycleBinAction`
- `RestoreAllRecycleBinAction`
- `RestoreRecycleBinAction`
3. Updated confirmation dialog titles, content, and button texts for improved user experience.
4. Replaced string literals with corresponding string constants throughout the Files App codebase.
- Improved maintainability: All strings are now managed in one place.
- Enhanced …

Code Quality: Update localization for recycle bin actions

---

src/Files.App/Views/Properties/SecurityPage.xaml

- Closes #16836 
**Changes**
Disabled text wrapping of the `TextBlock`
Did not add a margin as suggested [here](https://github.com/files-community/Files/issues/16836#issuecomment-2675037028), since there is already a margin of 4 at the bottom of the `ListView` https://github.com/files-community/Files/blob/92e87fbfe48c16fe48d754e516bfccb68144c2f8/src/Files.App/Views/Properties/SecurityPage.xaml#L129

Fix: Disabled text wrapping for the permissions list entries

---

src/Files.App/Dialogs/ReleaseNotesDialog.xaml.cs

- Closes #16786 
Opened and closed the What's New dialog, used Process Explorer to confirm the WebView process is terminated immediately
https://github.com/user-attachments/assets/129d2fff-3247-43a2-9f8a-063f94470ec5

Fix: Fixed issue where WebView process was left running in the background

---

Directory.Packages.props
src/Files.App.Controls/BladeView/BladeItem.Properties.cs
src/Files.App.Controls/BladeView/BladeItem.cs
src/Files.App.Controls/BladeView/BladeItemAutomationPeer.cs
src/Files.App.Controls/BladeView/BladeView.Properties.cs
src/Files.App.Controls/BladeView/BladeView.cs
src/Files.App.Controls/BladeView/BladeView.xaml
src/Files.App/Views/Layouts/ColumnsLayoutPage.xaml

`Expander` is buggy and its `OnApplyTemplate` is not usable. Retarget it to `ContentControl` and remove the unused titlebar and expand (enlarge) features.
Resolves the missing styles and crashing issue.

Code Quality: Retarget BladeView to ContentControl

---

src/Files.App/Actions/FileSystem/AddItemAction.cs
src/Files.App/Actions/FileSystem/CreateFolderAction.cs
src/Files.App/Actions/FileSystem/CreateFolderWithSelectionAction.cs
src/Files.App/Actions/FileSystem/CreateShortcutAction.cs
src/Files.App/Actions/FileSystem/CreateShortcutFromDialogAction.cs
src/Files.App/Actions/FileSystem/DeleteItemAction.cs
src/Files.App/Actions/FileSystem/DeleteItemPermanentlyAction.cs
src/Files.App/Actions/FileSystem/EmptyRecycleBinAction.cs
src/Files.App/Actions/FileSystem/FlattenFolderAction.cs
src/Files.App/Actions/FileSystem/OpenFileLocationAction.cs
src/Files.App/Actions/FileSystem/OpenItemAction.cs

This pull request aims to improve code quality and maintainability in the Files App by centralizing localization strings and replacing string literals with string constants. The changes enhance consistency, reduce the risk of typos, and streamline future updates and localization efforts.
Closes #16718 
- Created a centralized `Strings` class to manage all localization strings.
- Refactored localization strings in the following actions:
- `DeleteItemAction`
- `DeleteItemPermanentlyAction`
- `EmptyRecycleBinAction`
- `FlattenFolderAction`
- `OpenFileLocationAction`
- `OpenItemAction`
- `OpenItemWithApplicationPickerAction`
- `OpenParentFolderAction`
- Updated labels and descriptions for improved user experience.
- Replaced string literals with corresponding string constants throughout the …

Code Quality: Update localization strings in action classes

---

src/Files.App/Services/Windows/WindowsQuickAccessService.cs
src/Files.App/Utils/Global/QuickAccessManager.cs

- Closes #16676
1. Uninstalled Files Dev
2. Pinned `Shell:RecycleBinFolder` via File Explorer
3. Installed Files Dev (Launched with Visual Studio)
4. Checked that `Shell:RecycleBinFolder` is still pinned
Additionally i have checked that `Shell:RecycleBinFolder` gets pinned at the first start of Files and that pinning/unpinning of folders via the context menu still works

Fix: Fixed issue where the Recycle Bin was sometimes unpinned

---

src/Files.App/Actions/Content/Archives/Compress/CompressIntoArchiveAction.cs
src/Files.App/Actions/Content/Archives/Compress/CompressIntoSevenZipAction.cs
src/Files.App/Actions/Content/Archives/Compress/CompressIntoZipAction.cs
src/Files.App/Actions/Content/Archives/Decompress/DecompressArchive.cs
src/Files.App/Actions/Content/Archives/Decompress/DecompressArchiveHere.cs
src/Files.App/Actions/Content/Archives/Decompress/DecompressArchiveHereSmart.cs
src/Files.App/Actions/Content/Archives/Decompress/DecompressArchiveToChildFolderAction.cs

This pull request aims to improve code quality and maintainability in the Files App by centralizing localization strings for archive compression and decompression actions. The changes replace direct string literals with references to a new `Strings` class, enhancing consistency and streamlining future updates and localization efforts.
Closes #16718 
- Created a new `Strings` class to centralize localization strings for archive-related actions.
- Refactored localization strings in the following actions:
- `CompressIntoArchiveAction`
- `CompressIntoSevenZipAction`
- `CompressIntoZipAction`
- `DecompressArchive`
- `DecompressArchiveHere`
- `DecompressArchiveHereSmart`
- `DecompressArchiveToChildFolderAction`
- Updated the `ComputeLabel` method in `DecompressArchiveToChildFolderAction` for …

Code Quality: Update localization to use centralized Strings class 4

---

src/Files.App/Actions/Content/Archives/Compress/CompressIntoArchiveAction.cs
src/Files.App/Actions/Content/Archives/Compress/CompressIntoSevenZipAction.cs
src/Files.App/Actions/Content/Archives/Compress/CompressIntoZipAction.cs
src/Files.App/Actions/Content/Archives/Decompress/DecompressArchive.cs
src/Files.App/Actions/Content/Archives/Decompress/DecompressArchiveHere.cs
src/Files.App/Actions/Content/Archives/Decompress/DecompressArchiveHereSmart.cs
src/Files.App/Actions/Content/Archives/Decompress/DecompressArchiveToChildFolderAction.cs
src/Files.App/Actions/Content/Background/BaseSetAsAction.cs
src/Files.App/Actions/Content/Background/SetAsAppBackgroundAction.cs
src/Files.App/Actions/Content/Background/SetAsLockscreenBackgroundAction.cs
src/Files.App/Actions/Content/Background/SetAsSlideshowBackgroundAction.cs
src/Files.App/Actions/Content/Background/SetAsWallpaperBackgroundAction.cs
src/Files.App/Actions/Content/ImageManipulation/RotateLeftAction.cs
src/Files.App/Actions/Content/ImageManipulation/RotateRightAction.cs

This pull request refactors localization strings in several action classes within the `Files.App.Actions` namespace, replacing hardcoded string literals with references to a centralized `Strings` class. The changes improve maintainability and enhance localization support across the application.
#16718 
- Created a centralized `Strings` class for managing localization strings.
- Refactored localization strings in the following action classes:
- `SetAsAppBackgroundAction`
- `SetAsLockscreenBackgroundAction`
- `SetAsSlideshowBackgroundAction`
- `SetAsWallpaperBackgroundAction`
- `RotateLeftAction`
- `RotateRightAction`
- Updated error messages, labels, and descriptions to use the new `Strings` class.
- Improved maintainability: All localization strings are now managed in one place.
- …

Code Quality: Update localization to use centralized Strings class 5

---

src/Files.App/MainWindow.xaml.cs
src/Files.App/Utils/CommandLine/CommandLineParser.cs

- Closes #16707
**explanation**
The LaunchArgs are evaluated [here](https://github.com/files-community/Files/blob/2382d8168350939dd59522287beadab09dce9bed/src/Files.App/MainWindow.xaml.cs#L65) when Files is started. Here an explicit check is made for files-dev.exe or files-dev. (Or, depending on the environment, for files-stable, ...)
After the update, however, files-dev.exe is not called from the %localappdata%\Microsoft\WindowsApps folder, but rather Files.exe is called directly from the C:\Program Files\WindowsApps\<AppDirectory>\ folder.
Example: “C:\Program Files\WindowsApps\FilesPreview_3.8.0.0_x64__cnsc1k9bd01st\Files.App\Files.exe”
Since there is also a space at the end of the LaunchArgs, the TrimEnd is required so that no additional empty tab is …

Fix: Fixed error dialog from appearing after updates

---

src/Files.App.Controls/BladeView/BladeView.xaml
src/Files.App/Data/Contexts/ContentPage/ContentPageContext.cs
src/Files.App/Data/Contracts/IShellPage.cs
src/Files.App/UserControls/NavigationToolbar.xaml
src/Files.App/UserControls/NavigationToolbar.xaml.cs
src/Files.App/UserControls/PathBreadcrumb.xaml.cs
src/Files.App/UserControls/Toolbar.xaml
src/Files.App/UserControls/Toolbar.xaml.cs
src/Files.App/ViewModels/UserControls/NavigationToolbarViewModel.cs
src/Files.App/Views/Layouts/BaseLayoutPage.cs
src/Files.App/Views/MainPage.xaml
src/Files.App/Views/Shells/BaseShellPage.cs

_Planned internally. The name of both have been wrong in the design specs._
_None_
- AddressToolbar
- NavigationToolbar
- InnerNavigationToolbar
- Toolbar
1. Build and see the app working well.

Code Quality: Renamed AddressToolbar and InnerNavigationToolbaar

---

src/Files.App/Dialogs/SettingsDialog.xaml

- Closes #16949 
2. Checked that the glyph `&#xEC7A;` exists in both the **Segoe MDL2 Assets** and **Segoe Fluent Icons** fonts.
---
This changes the developer tools icon in the settings sidebar from sparkles to a wrench and screwdriver - not only to use the intended icon named "Developer Tools" in the Segoe font, but also to fix an issue where the sparkles icon is not available in the Windows 10 Segoe font (Segoe MDL2 Assets)

Fix: Fixed issue where the icon for "developer tools" didn't display properly on Windows 10

---

src/Files.App/Data/Models/ByteSize.cs
src/Files.App/Extensions/StringExtensions.cs

Closes #16919
Tried opening the Properties window, the size is correctly reported.

Fix: Fixed an issue where drive capacity was reported incorrectly

---

src/Files.App/Strings/en-US/Resources.resw
src/Files.App/ViewModels/Properties/HashesViewModel.cs
src/Files.App/Views/Properties/HashesPage.xaml
src/Files.App/Views/Properties/HashesPage.xaml.cs

- Closes #14891 
2. Opened properties of a file
3. Navigated to "hashes" tab
4. New functionality!

Feature: Added a comparison text box for hashes

---

src/Files.App.Controls/BreadcrumbBar/BreadcrumbBar.Properties.cs
src/Files.App.Controls/BreadcrumbBar/BreadcrumbBar.cs
src/Files.App.Controls/BreadcrumbBar/BreadcrumbBar.xaml
src/Files.App.Controls/BreadcrumbBar/BreadcrumbBarItem.Events.cs
src/Files.App.Controls/BreadcrumbBar/BreadcrumbBarItem.Properties.cs
src/Files.App.Controls/BreadcrumbBar/BreadcrumbBarItem.cs
src/Files.App.Controls/BreadcrumbBar/BreadcrumbBarItemAutomationPeer.cs
src/Files.App.Controls/BreadcrumbBar/BreadcrumbBarItemEventArgs.cs
src/Files.App.Controls/BreadcrumbBar/BreadcrumbBarLayout.cs
src/Files.App.Controls/Themes/Generic.xaml
tests/Files.App.UITests/Data/DummyItem2.cs
tests/Files.App.UITests/MainWindow.xaml
tests/Files.App.UITests/MainWindow.xaml.cs
tests/Files.App.UITests/Views/BreadcrumbBarPage.xaml
tests/Files.App.UITests/Views/BreadcrumbBarPage.xaml.cs

- #16029
1. Open Files UI tests app
2. Go to Breadcrumb page
3. Check the ellipsis behavior
4. Check the flyout behavior
5. Check the button click behavior
6. Check the behavior when the window size changed
7. Check the tabbing behavior (It only should XY navigation within the BreadcrumbBar)
Full:
With ellipsis:
Item chevron flyout:

Code Quality: Implemented Breadcrumb

---

.github/workflows/cd-store-preview.yml
src/Files.App/ViewModels/Properties/BasePropertiesPage.cs

None, approved manually by Yair on Discord.
Opened the Properties window of the OneDrive (Personal) Cloud Drive and OneDrive (Business) Cloud Drive, neither showed "Cleanup your drive contents" and "Format drive" as expected.

Feature: Hide Cleanup and Format on Properties for Cloud Drives

---

Files.slnx

Code Quality; Added global files to the solution file

---

src/Files.App/Actions/Content/Archives/Decompress/BaseDecompressArchiveAction.cs
src/Files.App/Actions/Content/Archives/Decompress/DecompressArchive.cs
src/Files.App/Actions/Content/Archives/Decompress/DecompressArchiveToChildFolderAction.cs
src/Files.App/UserControls/Toolbar.xaml
src/Files.App/ViewModels/UserControls/NavigationToolbarViewModel.cs

- Closes #15457
1. Set Files Dev as default application for .zip files
2. Opened .zip file via files explorer
3. .zip files gets opened in Files and the extract button is visible
I have also checked that the buttons are still displayed in the other cases
https://github.com/user-attachments/assets/41996f06-88af-43a4-a0a4-2ae747dd1900

Fix: Fixed issue where the extract button was sometimes not displayed in the toolbar

---

src/Files.App.Controls/Sidebar/SidebarView.xaml
src/Files.App.Controls/Sidebar/SidebarView.xaml.cs

Addresses the issue that right clicking the settings item would open the menu to choose the sidebar items.
Preparation for #16969
1. Opened Files and right clicked settings item -> no context menu
2. Right clicked on navigation items and empty space -> still opens context menu

Code Quality: Disable opening context menu on footer items

---

src/Files.App/Actions/Open/OpenSettingsFileAction.cs
src/Files.App/Data/Commands/Manager/CommandCodes.cs
src/Files.App/Data/Commands/Manager/CommandManager.cs
src/Files.App/Data/Commands/Manager/ICommandManager.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/ViewModels/Settings/AdvancedViewModel.cs
src/Files.App/Views/MainPage.xaml
src/Files.App/Views/MainPage.xaml.cs
src/Files.App/Views/Settings/AdvancedPage.xaml

- Closes #16969
1. Confirmed the action correctly opens the settings file

Feature: Added option to open settings file when right clicking settings button

---

src/Files.App/Data/Contracts/IFoldersSettingsService.cs
src/Files.App/Data/Enums/SizeUnitTypes.cs
src/Files.App/Data/Models/ByteSize.cs
src/Files.App/Extensions/StringExtensions.cs
src/Files.App/Services/Settings/FoldersSettingsService.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/ViewModels/Settings/FoldersViewModel.cs
src/Files.App/ViewModels/ShellViewModel.cs
src/Files.App/ViewModels/UserControls/Widgets/DrivesWidgetViewModel.cs
src/Files.App/Views/Settings/FoldersPage.xaml

- Closes #10075
1. Confirmed the size unit reflects the selected option in settings

Feature: Added support for changing the size format

---

src/Files.App/Data/Contracts/IGeneralSettingsService.cs
src/Files.App/Services/Settings/GeneralSettingsService.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/UserControls/NavigationToolbar.xaml
src/Files.App/ViewModels/Settings/AdvancedViewModel.cs
src/Files.App/ViewModels/UserControls/NavigationToolbarViewModel.cs
src/Files.App/Views/Settings/AdvancedPage.xaml

- Added setting to enable Omnibar
1. Confirmed setting hides existing breadcrumb bar and displays Omnnibar instead

Code Quality: Added setting to enable Omnibar

---

src/Files.App/Services/Storage/StorageNetworkService.cs
src/Files.App/Utils/Storage/Helpers/DriveHelpers.cs
src/Files.App/ViewModels/ShellViewModel.cs
src/Files.Shared/Helpers/PathHelpers.cs

Related to #12704
I'm not pro in c_sh,
This is only a temporary solution.
Because my work relies heavily on various mapped network drives,
Till now, this patch work for me.
1） Enter an smb that has been mapped as a network drive like "Y:\Download"
2）enter the directory containing a large number of large compressed files and wait for them to be lod.
3)  Observe whether the loading speed is the same with "\\192.168.0.1\nfs\Download"
ps:
The root cause may be the reading of the zip file，
Although it has not been tested, this is just a guess. Will huge files on slow devices have similar phenomena?
I also think that the compressed file recognition problem I mentioned in #12704 may aggravate this phenomenon.
Additionally, I …

Fix: Fixed performance issue with SMB shares

---

.github/NOTICE.md
src/Files.App/Helpers/NaturalStringComparer.cs
src/Files.App/ViewModels/Settings/AboutViewModel.cs

Fixes #17009
For the test, I have created another single file and copied the NaturalStringComparer code to it and tested the changes.

Fix: Fixed sorting issues with #-# numbered files

---

src/Files.App.Controls/AdaptiveGridView/AdaptiveGridView.Properties.cs
src/Files.App.Controls/AdaptiveGridView/AdaptiveGridView.cs

Closes https://files-org.sentry.io/issues/6450326995/

Code Quality: Added protection for System.DivideByZeroException

---

src/Files.App/Actions/Content/ImageManipulation/BaseRotateAction.cs
src/Files.App/UserControls/Toolbar.xaml
src/Files.App/ViewModels/UserControls/NavigationToolbarViewModel.cs

- Closes #16715 
1. Confirmed toolbar buttons have the correct icon state
**Comments**
The issue only occurs for files with additional actions in the toolbar. I discovered that changing from `x:Load` to `Visibility` resolves the issue. However, this introduces a different issue where the overflow button sometimes …

Fix: Fixed issue where toolbar button sometimes had the wrong icon state

---

src/Files.App/Services/App/AppUpdateSideloadService.cs

- Closes https://files-org.sentry.io/issues/5842278470/
2. ...

Fix: Fixed crash that would sometimes occur when updating

---

src/Files.App.CsWin32/IStorageProviderQuotaUI.cs
src/Files.App.CsWin32/IStorageProviderStatusUI.cs
src/Files.App.CsWin32/IStorageProviderStatusUISource.cs
src/Files.App.CsWin32/IStorageProviderStatusUISourceFactory.cs

Switch the Storage Provider Status UI APIs from the `Stdcall` calling convention to `MemberFunction`, for correctness.
Tested the Properties window of OneDrive, works as expected.

Code Quality: Switch Storage Provider Status UI APIs to use MemberFunction

---

src/Files.App/ViewModels/ShellViewModel.cs

- Follo-up #16812
2. Go to the Recycle Bin

Code Quality: Fixed an issue where shell locations wouldn't load

---

Directory.Packages.props
src/Files.App.CsWin32/ComPtr`1.cs
src/Files.App.CsWin32/Files.App.CsWin32.csproj
src/Files.App.CsWin32/IStorageProviderQuotaUI.cs
src/Files.App.CsWin32/IStorageProviderStatusUI.cs
src/Files.App.CsWin32/IStorageProviderStatusUISource.cs
src/Files.App.CsWin32/IStorageProviderStatusUISourceFactory.cs
src/Files.App.CsWin32/ManualGuid.cs
src/Files.App/Services/Storage/StorageTrashBinService.cs
src/Files.App/Services/Windows/WindowsDialogService.cs
src/Files.App/Services/Windows/WindowsRecentItemsService.cs
src/Files.App/Services/Windows/WindowsWallpaperService.cs
src/Files.App/Utils/Shell/LaunchHelper.cs
src/Files.App/Utils/Storage/Helpers/SyncRootHelpers.cs

This is a QOL PR for CsWin32.
- #15000
1. Build Files
2. Open Files
CC: @dongle-the-gadget I used your SG to do this; I'd like to request your review.

Code Quality: Replaced stack-allocated GUIDs with RVA-inlined GUIDs

---

src/Files.App.Controls/Sidebar/SidebarView.Properties.cs
src/Files.App.Controls/Sidebar/SidebarView.xaml
src/Files.App/Assets/Sidebar/EmptySidebar_100_ThemeDark.svg
src/Files.App/Assets/Sidebar/EmptySidebar_100_ThemeLight.svg
src/Files.App/Assets/Sidebar/EmptySidebar_200_ThemeDark.svg
src/Files.App/Assets/Sidebar/EmptySidebar_200_ThemeLight.svg
src/Files.App/Assets/Sidebar/EmptySidebar_48_ThemeDark.svg
src/Files.App/Assets/Sidebar/EmptySidebar_48_ThemeLight.svg
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/ViewModels/UserControls/SidebarViewModel.cs
src/Files.App/Views/MainPage.xaml
src/Files.App/Views/MainPage.xaml.cs

- Closes #7065
1. Confirmed the banner is displayed when all section are hidden
2. Confirmed banner is shown when other sections are hidden and wsl section is empty
3. Confirmed banner is hidden in compact mode

Feature: Display banner when all sections are hidden on the sidebar

---

Directory.Packages.props
src/Files.App/Actions/Content/Archives/Decompress/DecompressArchive.cs
src/Files.App/Data/Contracts/IStorageArchiveService.cs
src/Files.App/Data/Items/EncodingItem.cs
src/Files.App/Files.App.csproj
src/Files.App/Services/Storage/StorageArchiveService.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/ViewModels/Dialogs/DecompressArchiveDialogViewModel.cs

After this PR, when decompressing zip file and the encoding of zip file is undetermined, Files will detect the encoding autometically. 
Before this PR, SharpZipLib decompressing (decompressing with specified encoding) blocks the UI. After this PR, it no longers blocks the UI and works like SevenZipSharp.
All possible Windows system encodings are added into the encoding list.
- This PR is a part of #14937
Stability is a top priority for Files and all changes are required to go through testing before …

Feature: Automatically detect zip encoding

---

src/Files.App/Views/Settings/AppearancePage.xaml
src/Files.App/Views/Settings/DevToolsPage.xaml
src/Files.App/Views/Settings/GeneralPage.xaml
src/Files.App/Views/Settings/TagsPage.xaml

- Closes #17063
1. Confirmed the setting sections with setting headers have the correct background.

Code Quality: Add background to setting expanders

---

src/Files.App.CsWin32/Extras.cs
src/Files.App.CsWin32/NativeMethods.txt
src/Files.App.Storage/Storables/HomeFolder/HomeFolder.cs
src/Files.App.Storage/Storables/WindowsStorage/IWindowsStorable.cs
src/Files.App.Storage/Storables/WindowsStorage/WindowsFile.cs
src/Files.App.Storage/Storables/WindowsStorage/WindowsFolder.cs
src/Files.App.Storage/Storables/WindowsStorage/WindowsStorable.cs
src/Files.App.Storage/Storables/WindowsStorage/WindowsStorableHelpers.Icon.cs
src/Files.App.Storage/Storables/WindowsStorage/WindowsStorableHelpers.Shell.cs

Code Quality: Improved the new Windows thumbnail API

---

src/Files.App/ViewModels/MainPageViewModel.cs

- Closes #17082
1. Manually set `AppThemeBackgroundImageSource` to an invalid value (eg 'a')
2. Confirm Files starts correctly

Fix: Fixed crash that would occur when using an invalid background image

---

src/Files.App.Controls/Omnibar/Omnibar.Events.cs
src/Files.App.Controls/Omnibar/Omnibar.Properties.cs
src/Files.App.Controls/Omnibar/Omnibar.cs
src/Files.App.Controls/Omnibar/Omnibar.xaml
src/Files.App.Controls/Omnibar/OmnibarMode.Properties.cs
src/Files.App/Data/Items/NavigationBarSuggestionItem.cs
src/Files.App/Data/Models/BreadcrumbBarItemModel.cs
src/Files.App/Data/Models/OmnibarPathModeSuggestionModel.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/UserControls/NavigationToolbar.xaml
src/Files.App/UserControls/NavigationToolbar.xaml.cs
src/Files.App/UserControls/PathBreadcrumb.xaml.cs
src/Files.App/ViewModels/UserControls/NavigationToolbarViewModel.cs
src/Files.App/Views/Shells/BaseShellPage.cs

Introduced Omnibar and added support for the Path mode.
- #16029
2. Enable Omnibar from Settings > Advanced
3. Test the breadcrumb bar
1. Click on a breadcrumb item
2. Click on a breadcrumb item's chevron
3. Click on a flyout item of a breadcrumb item's chevron
4. Click on the root item (Home)
5. Click on a flyout item of the root item's chevron
4. Test the Omnibar's textbox
1. Enter test and see the suggestions being updated
2. Submit the entered text by tappping Enter key to see the navigation
5. Test the Omnibar's focus

Feature: Introduced Omnibar 1

---

src/Files.App.CsWin32/ComPtr`1.cs
src/Files.App.CsWin32/ManualGuid.cs
src/Files.App.CsWin32/NativeMethods.txt
src/Files.App.Storage/Storables/WindowsStorage/WindowsStorable.cs
src/Files.App.Storage/Storables/WindowsStorage/WindowsStorableHelpers.Shell.cs
src/Files.App/Data/Contexts/HomePage/HomePageContext.cs
src/Files.App/Data/Contexts/HomePage/IHomePageContext.cs
src/Files.App/Data/Items/WidgetFolderCardItem.cs
src/Files.App/UserControls/Widgets/QuickAccessWidget.xaml
src/Files.App/ViewModels/HomeViewModel.cs
src/Files.App/ViewModels/UserControls/Widgets/QuickAccessWidgetViewModel.cs
src/Files.App/Views/HomePage.xaml

Introducing speed improvements + possibly fixing two significant issues.
- Related: #4180
- Related: #15000
- Possibly: #15410
- Partially: #16447
2. Open Home
3. Play around Quick Access
1. Pin a folder.
2. Unpin a folder.
3. Pin or unpin a folder in File Explorer and see Files gets updated.

Code Quality: Introduced HomeFolder for Quick Access in Home

---

src/Files.App/Services/Windows/WindowsQuickAccessService.cs

Wraps `InvokeVerb` in an STA thread to fix COM threading issues when unpinning folders from sidebar. Ensures stable shell verb invocation while maintaining UI responsiveness.
**Test Steps**
Verified unpinning stability by:
1. Launching Files
2. Right-clicking pinned folders
3. Selecting "Unpin from Sidebar"
4. Confirming:
- Immediate removal from Pinned section
- No UI freezing
- No errors in debug output

Code Quality: Wrap InvokeVerb inside STA

---

src/Files.App/Views/Properties/MainPropertiesPage.xaml
src/Files.App/Views/Properties/MainPropertiesPage.xaml.cs

Code Quality: Improved visual states for Properties Window

---

src/Files.App/UserControls/Pane/ShelfPane.xaml
src/Files.App/UserControls/Pane/ShelfPane.xaml.cs
src/Files.App/Views/MainPage.xaml

- For #12490
1. Confirmed the context menu now opens when right clicking the container and not just the grid.
2. Confirmed the remove option works as expected.

Code Quality: Improved Shelf pane

---

src/Files.App/Utils/Cloud/CloudDrivesDetector.cs
src/Files.App/Utils/Cloud/CloudProviders.cs

- Closes #15999 
- Closes #16935 
1. Installed the cloud drives and made sure they are displayed in Files
There is no icon displayed for the Sync drive, but that is an error on their side because the program does not set the icon path in the registry
Sync:
Magenta:

Feature: Added support for Magenta & Sync cloud drive

---

src/Files.App.CsWin32/NativeMethods.txt
src/Files.App/Data/Models/AppModel.cs
src/Files.App/Helpers/Win32/Win32PInvoke.Methods.cs

- Related #15000 
1. Opened the app
2. Tested components that reference the migrated `AppModel.AppWindowDPI` property
---
`GetDpiForWindow` is already being used in some places however the legacy method pointing to a `DllImport` call remains in the Win32 PInvoke helper.
This PR removes it from the helper and replaces the final reference to `Win32PInvoke.GetDpiForWindow()` with the appropriate method generated by CsWin32.

Code Quality: Replaced DllImport calls with CsWin32 generations for DPI calculation operations

---

src/Files.App.BackgroundTasks/Files.App.BackgroundTasks.csproj
src/Files.App.CsWin32/Files.App.CsWin32.csproj
src/Files.App.CsWin32/NativeMethods.txt
src/Files.App.Storage/Files.App.Storage.csproj
src/Files.App.Storage/Storables/WindowsStorage/WindowsStorableHelpers.Icon.cs
src/Files.App.Storage/Watchers/RecycleBinWatcher.cs
src/Files.Core.Storage/Files.Core.Storage.csproj
src/Files.Shared/Files.Shared.csproj
src/Files.Shared/Helpers/PathHelpers.cs
src/Files.Shared/Utils/IAsyncInitialize.cs

Code Quality: Added IsAotCompatible to some class library projects

---

src/Files.App/Data/Items/NavigationBarSuggestionItem.cs
src/Files.App/UserControls/NavigationToolbar.xaml
src/Files.App/UserControls/NavigationToolbar.xaml.cs
src/Files.App/ViewModels/UserControls/NavigationToolbarViewModel.cs

- #16029
2. Enable Omnibar from Settings > Advanced
3. Test the Palette mode
1. Filter the commands
2. Click on a command

Code Quality: Implemented Command Palette mode in Omnibar 

---

src/Files.App/Data/Contracts/IAppearanceSettingsService.cs
src/Files.App/Data/Enums/StatusCenterVisibility.cs
src/Files.App/Services/Settings/AppearanceSettingsService.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/UserControls/NavigationToolbar.xaml
src/Files.App/ViewModels/Settings/AppearanceViewModel.cs
src/Files.App/ViewModels/UserControls/NavigationToolbarViewModel.cs
src/Files.App/Views/Settings/AppearancePage.xaml

Feature: Added support for always displaying the status center

---

src/Files.App.Controls/Omnibar/Omnibar.Events.cs
src/Files.App.Controls/Omnibar/Omnibar.Properties.cs
src/Files.App.Controls/Omnibar/Omnibar.cs
src/Files.App.Controls/Omnibar/OmnibarMode.Events.cs
src/Files.App.Controls/Omnibar/OmnibarMode.Properties.cs
src/Files.App.Controls/Omnibar/OmnibarMode.cs
src/Files.App/Actions/Global/EditPathAction.cs
src/Files.App/Actions/Global/SearchAction.cs
src/Files.App/Actions/Open/OpenCommandPaletteAction.cs
src/Files.App/Data/Contracts/IAddressToolbarViewModel.cs
src/Files.App/UserControls/NavigationToolbar.xaml
src/Files.App/UserControls/NavigationToolbar.xaml.cs
src/Files.App/ViewModels/UserControls/NavigationToolbarViewModel.cs

- #16029
1. Open Files app.
2. Go to Palette mode.
3. Invkoe a command.
4. See the mode changes to Path automatically.

Code Quality: Improved Omnibar UX

---

src/Files.App/Strings/en-US/Resources.resw
src/Files.App/UserControls/NavigationToolbar.xaml
src/Files.App/ViewModels/UserControls/StatusCenterViewModel.cs

- Closes #15183
1. Confirmed the status badge is cleared when opening the flyout

Feature: Auto clear Status Center badge when opening flyout

---

src/Files.App.Controls/Omnibar/Omnibar.Events.cs
src/Files.App.Controls/Omnibar/Omnibar.cs
src/Files.App/ViewModels/UserControls/NavigationToolbarViewModel.cs

- For #16029
1. Confirmed Command Palette flyout is opened with correct scroll position
2. Filtered out 'Open Command Palette' action

Code Quality: Improved Omnibar

---

src/Files.App/Strings/en-US/Resources.resw
src/Files.App/ViewModels/MainPageViewModel.cs
src/Files.App/Views/MainPage.xaml
src/Files.App/Views/MainPage.xaml.cs

- Closes #
1. Confirmed logic, however will need to test in release to ensure everything works properly.

Feature: Less annoying review prompt

---

src/Files.App.Controls/BreadcrumbBar/BreadcrumbBar.cs

- #16029
1. "Chevrons are disappearing after adding a new tab"
1. Navigate folders many times and see chevrons persist anyway

Code Quality: Improved Omnibar 5

---

src/Files.App/UserControls/NavigationToolbar.xaml.cs
src/Files.App/ViewModels/UserControls/NavigationToolbarViewModel.cs

- For #16029
1. Confirmed selecting suggestions in Command Palette sets text to the description
2. Confirmed that it works to invoke commands

Code Quality: Use action description when selecting via arrow keys

---

src/Files.App.Controls/Omnibar/Omnibar.xaml

- For #16029
1. Focused Omnibar textbox
2. Confirmed the clear button has the correct pointer states

Code Quality: Fixed pointer states on Omnibar clear button

---

src/Files.App/Constants.cs
src/Files.App/Data/Contracts/IApplicationSettingsService.cs
src/Files.App/Helpers/Application/AppLifecycleHelper.cs
src/Files.App/Services/Settings/ApplicationSettingsService.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/ViewModels/MainPageViewModel.cs
src/Files.App/Views/MainPage.xaml

Code Quality: Added sponsor flyout for sideload versions

---

src/Files.App.Controls/Omnibar/Omnibar.cs

- For #16029
1. Confirmed that cursor placement only moves to the end when choosing suggestions

Code Quality: Fixed Omnibar cursor placement when changing text

---

src/Files.App/UserControls/NavigationToolbar.xaml
src/Files.App/UserControls/NavigationToolbar.xaml.cs
src/Files.App/ViewModels/UserControls/NavigationToolbarViewModel.cs

- For #16029
1. Confirmed drag & drop events work with both Omnibar and the existing path bar

Code Quality: Connected drag events to Omnibar

---

src/Files.App.Controls/Omnibar/Omnibar.Events.cs

- For #16029
- Fixed 'Holding the arrow key in Command Palette mode sometimes removes focus from the suggestions and instead filters the commands'

Code Quality: Fixed selecting Omnibar suggestions via keyboard

---

src/Files.App/Utils/Cloud/CloudProviders.cs
src/Files.App/Utils/Cloud/Detector/CloudDetector.cs
src/Files.App/Utils/Cloud/Detector/OXDriveCloudDetector.cs

This PR adds support for detecting OX Drive as a cloud provider in the Files app.
Closes #16000
- Introduced `OXDriveCloudDetector` for identifying OX Drive installations
- Extracts sync folder path from `userConfig.json` using `MainFolderPath`
- Loads OX Drive icon from the registry or fallback installation path (under Program Files(x86))
- Registered OX Drive in `CloudProviders` enum
- Integrated OX Drive detector into the cloud detection pipeline
Tested locally with OX Drive installed and verified detection.

Feature: Add support for OX Drive integration

---

src/Files.App/UserControls/NavigationToolbar.xaml.cs
src/Files.App/UserControls/SearchBox.xaml.cs
src/Files.App/ViewModels/UserControls/NavigationToolbarViewModel.cs
src/Files.App/ViewModels/UserControls/SearchBoxViewModel.cs

- #16029
2. Load suggestions in Omnibar

Code Quality: Use UI thread when populating suggestions

---

src/Files.App.CsWin32/ComPtr`1.cs
src/Files.App.CsWin32/ManualGuid.cs
src/Files.App.CsWin32/NativeMethods.txt
src/Files.App.Storage/Storables/HomeFolder/HomeFolder.cs
src/Files.App.Storage/Storables/WindowsStorage/ContextMenuItem.cs
src/Files.App.Storage/Storables/WindowsStorage/ContextMenuType.cs
src/Files.App.Storage/Storables/WindowsStorage/IFolderSettings.cs
src/Files.App.Storage/Storables/WindowsStorage/IWindowsFile.cs
src/Files.App.Storage/Storables/WindowsStorage/IWindowsFolder.cs
src/Files.App.Storage/Storables/WindowsStorage/IWindowsStorable.cs
src/Files.App.Storage/Storables/WindowsStorage/JumpListDestinationType.cs
src/Files.App.Storage/Storables/WindowsStorage/JumpListManager.cs
src/Files.App.Storage/Storables/WindowsStorage/STATask.cs
src/Files.App.Storage/Storables/WindowsStorage/SystemTrayManager.cs
src/Files.App.Storage/Storables/WindowsStorage/WindowsBulkOperations.cs
src/Files.App.Storage/Storables/WindowsStorage/WindowsFile.cs
src/Files.App.Storage/Storables/WindowsStorage/WindowsFolder.cs
src/Files.App.Storage/Storables/WindowsStorage/WindowsStorable.cs
src/Files.App.Storage/Storables/WindowsStorage/WindowsStorableHelpers.Icon.cs
src/Files.App.Storage/Storables/WindowsStorage/WindowsStorableHelpers.Process.cs
src/Files.App.Storage/Storables/WindowsStorage/WindowsStorableHelpers.Shell.cs
src/Files.App.Storage/Storables/WindowsStorage/WindowsStorableHelpers.Storage.cs
src/Files.App/Helpers/Win32/Win32Helper.Process.cs
src/Files.App/ViewModels/ShellViewModel.cs
src/Files.App/ViewModels/UserControls/Widgets/QuickAccessWidgetViewModel.cs

- #15000
- Improved:
- STATask (not yet used but ready to use now)
- IWindowsStorable.ThisPtr
- IWindowsFolder.GetItemsAsync
- Introduced:
- ShellNew helpers
- SystemTrayIconManager
> The applicable method to test is `IWindowsFolder.GetItemsAsync`
- Launch the app
- Load Home page

Code Quality: Improved WindowsStorables

---

tests/Files.InteractionTests/Helper/AxeHelper.cs

Code Quality: Improved Axe assertion message

---

src/Files.App.Controls/BreadcrumbBar/BreadcrumbBar.Properties.cs
src/Files.App.Controls/BreadcrumbBar/BreadcrumbBar.xaml
src/Files.App.Controls/BreadcrumbBar/BreadcrumbBarItem.Properties.cs
src/Files.App.Controls/Omnibar/Omnibar.xaml
src/Files.App/Data/Items/PathBoxItem.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/UserControls/NavigationToolbar.xaml
src/Files.App/Utils/Storage/Helpers/StorageFileExtensions.cs
src/Files.App/Views/HomePage.xaml.cs
src/Files.App/Views/ReleaseNotesPage.xaml.cs
src/Files.App/Views/Shells/BaseShellPage.cs
tests/Files.App.UITests/Views/OmnibarPage.xaml

- #16029
2. Hover over chevron button of an item
3. Hover over chevron button of the root item

Code Quality: Improved tooltip UX in BreadcrumbBar

---

src/Files.App/ViewModels/Settings/AboutViewModel.cs

- Closes #17292
1. Copied Windows version
2. Confirmed it copied correctly

Fix: Fixed issue where the Windows version was copied incorrectly

---

src/Files.App/Strings/en-US/Resources.resw
src/Files.App/Utils/StatusCenter/StatusCenterHelper.cs

**Changes**
Update Status Center strings to include plural forms for `item(s)` and `font(s)`.
Use the `GetLocalizedFormatResource` instead of `GetLocalizedResource` and move the `headerString` and `subHeaderString` initialization to each corresponding case.
Also removed the redundant `if (headerString is not null)` checks, as the string cannot be null at that point.
- Closes #17295
Tested the changed strings in file operations.

Code Quality: Improved display of plural strings in Status Center

---

src/Files.App/Utils/Git/GitHelpers.cs
src/Files.App/Views/Shells/BaseShellPage.cs

LibGit2Sharp doesn't support asynchronous calls and cancellation, so git fetch may take long time even if it is canceled and we shouldn't wait it in the UI thread.
- May resolve [FILES-APP-1NH](https://files-org.sentry.io/issues/5834287744/?project=4507376940351488)
1. Confirm that opening multiple Git repositories …

Code Quality: Don't wait canceled git fetch

---

src/Files.App/UserControls/FilePreviews/MediaPreview.xaml.cs

- May fix [FILES-APP-3DE](https://files-org.sentry.io/issues/6382380872/?project=4507376940351488)
1. Confirm that the app does not crash when switching between previews of multiple video files.

Code Quality: Unsubscribe events in MediaPreview

---

src/Files.App/Views/Layouts/DetailsLayoutPage.xaml.cs
src/Files.App/Views/Layouts/GridLayoutPage.xaml.cs

- Closes #17298 
**Notes**
It seems the issue is caused by the checkbox, which when focused handles all `Key`-related events.
For some reason I don't understand, the bug affects only `Deselection` and not `Selection`
The code below removes the focus from the checkbox once its state is updated
1. Open a folder with …

Fix: Fixed issue where delete key wouldn't work after removing item from selection 

---

src/Files.App/Actions/Navigation/ArrangePanesHorizontallyAction.cs
src/Files.App/Actions/Navigation/ArrangePanesVerticallyAction.cs
src/Files.App/Actions/Navigation/SplitPaneHorizontallyAction.cs
src/Files.App/Actions/Navigation/SplitPaneVerticallyAction.cs
src/Files.App/Data/Commands/Manager/CommandCodes.cs
src/Files.App/Data/Commands/Manager/CommandManager.cs
src/Files.App/Data/Commands/Manager/ICommandManager.cs
src/Files.App/Services/Settings/GeneralSettingsService.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/UserControls/TabBar/TabBar.xaml
src/Files.App/ViewModels/Settings/GeneralViewModel.cs
src/Files.App/Views/Settings/GeneralPage.xaml
src/Files.App/Views/ShellPanesPage.xaml.cs

- Closes #17303
- Moved 'default pane direction' outside of expander to prepare for #16498

Feature: Reword 'add pane' to 'split pane'

---

src/Files.App/Actions/Show/ToggleDualPaneAction.cs
src/Files.App/Data/Commands/Manager/CommandCodes.cs
src/Files.App/Data/Commands/Manager/CommandManager.cs
src/Files.App/Data/Commands/Manager/ICommandManager.cs
src/Files.App/Data/Contracts/IShellPanesPage.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/Views/ShellPanesPage.xaml.cs

- Closes #16498
1. Assigned a keyboard shortcut to the 'Toggle dual pane mode' action
2. Confirmed that it adds second pane when dual pane is off
3. Confirmed that it closes the non-active pane when dual pane is on
4. Confirmed that the pane arrangement follows the default in settings

Feature: Added an action to toggle dual pane mode

---

src/Files.App.Controls/Omnibar/Omnibar.Events.cs
src/Files.App/Data/Contracts/IAddressToolbarViewModel.cs
src/Files.App/ViewModels/UserControls/NavigationToolbarViewModel.cs

- For #16029
- Fix `'Search' action doesn't work when triggered from the Command Palette`
- Fix `Switching to a different window while the flyout is open closes it, but it reopens when refocusing the window`
2. ...

Code Quality: Fixed Omnibar issues

---

src/Files.App/ViewModels/ShellViewModel.cs

- Closes #17427
1. Opened Dual Pane
2. Pasted item into one of the panes
3. Quickly switched focus to the other pane
4. Confirmed the focus stayed on the active pane

Fix: Fixed issue where inactive pane stole focus on file change

---

src/Files.App/Data/Models/CompressArchiveModel.cs

- Closes #17257
1. Trace the logic of 7z archive compression by Right-clicking the mouse and selecting "Create xxx.7z" under the "Compress" option in the context menu.
2. Upon step debugging, found out that adding the custom parameter `cu` was throwing an exception from the file with the error of `System.ArgumentException: Value does not fall within the expected range`
3. After applying the fixes, compress multiple files by selecting `Create xxx.7z` under the `Compress` option in the context menu and then extract the created `7z` archive.
**Fix Description**
- Upon checking the documentation from the [site](https://7-zip.opensource.jp/chm/cmdline/switches/method.htm#7Z), I noticed that the `7z` archive does not contain the …

Fix: Fixed issue where 7z archive files could not be previewed or compressed

---

src/Files.App/Utils/Git/GitHelpers.cs

- Closes #17386
1. Used the clone action from the command palette (or drag and drop the URL)
2. Pasted url `https://github.com/files-community/Files.git` or `https://github.com/files-community/Files` 
3. Verified that casing was preserved (uppercase F) and the .git suffix was removed.

Fix: Fixed issue where repository names lost casing and retained .git suffix

---

src/Files.App/Views/ShellPanesPage.xaml.cs

- Closes #15397
1. Add second pane
2. Focus on the left pane
3. Change layouts
4. Confirm focus remains on the left pane

Fix: Fixed issue where changing layouts focused the right pane

---

src/Files.App.Controls/ThemedIcon/ThemedIcon.Properties.cs
src/Files.App.Controls/ThemedIcon/ThemedIcon.cs
src/Files.App/UserControls/NavigationToolbar.xaml

- Closes #17347 
**Notes**
- It seems that `Style` changes do not invoke `OnApplyTemplate`, so this solution is basically a workaround.
- I can't remember if we have anything against `Finalizer`s... should I dispose the object in a different way?
1. Open a folder
2. Change the layout using the toolbar's button
3. See …

Fix: Fixed issue where the 'layout' icon didn't match the select layout

---

src/Files.App/Views/Layouts/DetailsLayoutPage.xaml.cs
src/Files.App/Views/Layouts/GridLayoutPage.xaml.cs

Code Quality: Properly dispose events in layout pages

---

src/Files.App/Views/Layouts/ColumnLayoutPage.xaml.cs
src/Files.App/Views/Layouts/DetailsLayoutPage.xaml.cs
src/Files.App/Views/Layouts/GridLayoutPage.xaml.cs

- Closes #15051
1. Select items
2. Tapped empty space using touch screen
3. Confirmed selection is cleared
4. Confirmed long touch and hold still opens right click menu
5. Confirmed clicking with mouse clears selection
6. Confirmed right clicking with mouse clears selection

Fix: Fixed issue with clearing selection via touch

---

src/Files.App/Views/Layouts/BaseLayoutPage.cs

Fix: Fixed issue where adaptive layout removed focus

---

src/Files.App/Actions/Navigation/NextTabAction.cs
src/Files.App/Actions/Navigation/PreviousTabAction.cs
src/Files.App/Data/Contracts/IShellPanesPage.cs
src/Files.App/UserControls/TabBar/TabBar.xaml
src/Files.App/UserControls/TabBar/TabBar.xaml.cs
src/Files.App/UserControls/Toolbar.xaml
src/Files.App/UserControls/Toolbar.xaml.cs
src/Files.App/ViewModels/MainPageViewModel.cs
src/Files.App/ViewModels/ShellViewModel.cs
src/Files.App/Views/Layouts/BaseLayoutPage.cs
src/Files.App/Views/MainPage.xaml
src/Files.App/Views/MainPage.xaml.cs
src/Files.App/Views/ShellPanesPage.xaml.cs

- Closes #17500
- Added a new solution for #15397 and #16530
- Fixed an issue where active pane changed when switching tabs via keyboard shortcuts
- Automatically close flyout after choosing a layout
1. Clicked Toolbar
2. Confirmed keyboard shortcuts work
3. Repeated test with TitleBar
4. Confirmed these changes don't …

Code Quality: Fixed keyboard shortcuts when refocusing window

---

src/Files.App/Utils/Git/GitHelpers.cs

Closes https://github.com/files-community/Files/issues/17385
_Method 1: Using Command Palette_
Opened the Files app and navigated to an available folder.
Pressed Ctrl + Shift + P to open the command palette.
Entered Clone and selected Clone Git Repository.
Pasted https://gitlab.com/es-de/emulationstation-de.git in the repository URL text box.
Verified that the Clone button was enabled.
Clicked the Clone button, and the repository was successfully cloned to the local folder.
_Method 2: Using Drag & Drop_
Opened the Files app and navigated to an available folder.
Dragged and dropped the repository link (https://gitlab.com/es-de/emulationstation-de.git) into the Files window.
Verified that the Clone button was enabled. …

Feature: Added support for cloning GitLab repository URLs

---

src/Files.App/ViewModels/HomeViewModel.cs

Closes #17539 
Fixed the crash by ensuring the WidgetItems is accessed only on the UI thread.
1. Open the Files app
2. Add a new tab
3. Immediately click on a pinned item in the left panel before the tab completes loading
4. Verify that no exception is thrown and the folder opens correctly
5. Verify that normal tab navigation and pinned item access work as expected

Fix: Fixed crash that sometimes occured when opening pinned items 

---

src/Files.App/Views/Settings/TagsPage.xaml

Replaces the critical background brush with the AccentButtonStyle for the delete button in the tag removal flyout, ensuring consistent styling with other accent buttons.
- Closes #17623
1. Open settings > tags
2. Clicked 'delete'
3. Hovered over 'delete' button and confirmed it no longer flashes

Fix: Fixed issue where the delete tag button had poor styling

---

tests/Files.App.UITests/Files.App.UITests.csproj

A small typo in `tests/Files.App.UITests/Files.App.UITests.csproj` prevents assets inside assets folder to be loaded
- Closes #17642
2. Was looking through the codebase and spotted it

Code Quality: Fixed typo in Files.App.UITests.csproj‎

---

src/Files.App/Views/Layouts/DetailsLayoutPage.xaml.cs
src/Files.App/Views/Shells/ColumnShellPage.xaml.cs

Closes #13311
Fixed issue where searches started from Columns view couldn't open results with double-click or Enter.
1. Open the Files app and navigate to a directory.
2. Switch to Columns view and start a search.
3. Confirm results render in Details layout.
4. From the search results, double-click an item or select it and press Enter to open it.
5. Verified the item opens.
Note:
It appears that navigation has issues with Columns view and does not correctly handle the context as it does for other layouts. Due to the complexity involved, I have modified the files specific to the Columns view and implemented an alternative approach.

Fix: Fixed issue with opening items from search results in Columns View

---

src/Files.App/Strings/en-US/Resources.resw
src/Files.App/Utils/StatusCenter/StatusCenterHelper.cs
src/Files.App/Utils/StatusCenter/StatusCenterItem.cs
src/Files.App/Utils/Storage/Operations/FileOperationsHelpers.cs
src/Files.App/Utils/Storage/Operations/FileSizeCalculator.cs
src/Files.App/Utils/Storage/Operations/ShellFilesystemOperations.cs

Fixed UX issues during large folder operations where Status Center appears doing nothing. Users now see real-time discovery progress showing the actual number of items being discovered during the enumeration phase.
Closes: #14057
1. Open the Files app and navigate to a directory containing a large number of files (100k+)
2. Initiate a copy, move, or delete operation on the large folder
3. Observe the Status Center popup during the operation:
- Initially shows "Discovered X items..." with real-time count updates during enumeration
- Transitions to "Copying/Moving/Deleting X items..." after enumeration completes
4. Verify the UI remains responsive during large folder operations without freezing
5. Test with different …

Feature: Added discovering phase to the Status Center

---

src/Files.App/Services/Storage/StorageArchiveService.cs

Fixed issue where multi-part RAR files failed to extract with "File is corrupted. Data error has occurred" exception. Changed SevenZipExtractor to use file path constructor instead of stream-based approach, allowing SevenZip to automatically locate and open subsequent archive parts (.part01.rar, .part02.rar, etc.). Also improved error logging by replacing Console.WriteLine with App.Logger.LogError.
Closes #14328
1. Create a multi-part RAR archive
2. Open the Files app
3. Navigate to the folder containing the multi-part RAR files
4. Right-click on the first part (eg: test.part01.rar) and select "Extract > Extract here"
5. Verify the extraction completes successfully without errors
6. Verify all files from all parts are …

Fix: Fixed multi-part RAR extraction failure and improved error logging

---

src/Files.App/Services/Storage/StorageArchiveService.cs

Fixed issue where Status Center doesn't show extraction progress when extracting archive files. Moved event handler registration to before the extraction call so progress events are properly captured and displayed. 
Closes #14974
1. Open the Files app
2. Navigate to any folder containing an archive file (ZIP, RAR, etc.)
3. Right-click on the archive and select "Extract > Extract here"
4. Open Status Center during extraction
5. Verify that extraction progress is shown (percentage, current file name, file count)
6. Verify progress updates in real-time as files are extracted

Fix: Fixed an issue where progress wasn't displayed when extracting archives
