Files UWP/FilesUWP.csproj, Files UWP/MainPage.xaml.cs, Launcher/App.config, Launcher/Launcher.csproj
Fixed visiblity issue for close, minimize, and maximize in light mode.
=> Fixed visiblity issue for close, minimize, and maximize in light mode.

Files UWP/PhotoAlbum.xaml
This adds a nice animation when resizing file-uwp in the photos page.
=> Added a ReorderGridAnimation to the photos page.

Files UWP/AddItem.xaml.cs, Files UWP/App.xaml.cs, Files UWP/ClassicMode.xaml, Files UWP/ClassicMode.xaml.cs, Files UWP/Filesystem/ItemViewModel.cs, Files UWP/GenericFileBrowser.xaml, Files UWP/GenericFileBrowser.xaml.cs, Files UWP/Interacts/Interaction.cs, Files UWP/MainPage.xaml, Files UWP/MainPage.xaml.cs, Files UWP/Navigation/NavigationActions.cs, Files UWP/Navigation/PhotoAlbumNavActions.cs, Files UWP/Navigation/UniversalPath.cs, Files UWP/PhotoAlbum.xaml, Files UWP/PhotoAlbum.xaml.cs, Files UWP/SettingsPages/Personalization.xaml, Files UWP/SettingsPages/Preferences.xaml, Files UWP/SettingsPages/Preferences.xaml.cs, Files UWP/YourHome.xaml.cs, FilesUwp.Package/FilesUwp.Package.wapproj
This builds off of @ashikns suggestion for better architecture by removing unnecessary statics. Furthermore, I eliminated the creation of ItemViewModel every single time, in favor of one instance that is referenced over and over.
=> Greatly Improve Code Architecture

ExecutableLauncher/ExecutableLauncher.csproj, Files UWP/ProHome.xaml.cs, Files UWP/Properties.xaml, Files UWP/Properties.xaml.cs
Reverts duke7553/files-uwp#155
=> Revert "Added Properties data Populated in the UI"

Files UWP/App.xaml.cs
https://github.com/duke7553/files-uwp/projects/1#card-23664632
=> Fixed app not detecting the system theme the first time launched

Files UWP/YourHome.xaml, Files UWP/YourHome.xaml.cs
Same effect as before, but with a confirmation dialog and also using the app's ui theme.
=> Added remove recent item option from flyout menu

Files UWP/ProHome.xaml.cs
=> Add support for environment variables

Files UWP/ProHome.xaml.cs
Reverts duke7553/files-uwp#194
=> Revert "Add support for environment variables"

Files UWP/App.xaml, Files UWP/App.xaml.cs, Files UWP/FilesUWP.csproj, Files UWP/Filesystem/DriveItem.cs, Files UWP/GenericFileBrowser.xaml, Files UWP/InstanceTabsView.xaml, Files UWP/InstanceTabsView.xaml.cs, Files UWP/ProHome.xaml, Files UWP/ProHome.xaml.cs, Files UWP/Settings.xaml, Files UWP/Settings.xaml.cs, Files UWP/SettingsPages/StartPageWidgets.xaml, Files UWP/SettingsPages/StartPageWidgets.xaml.cs, Files UWP/YourHome.xaml, Files UWP/YourHome.xaml.cs
This PR adds the following:
- Improvements to theme colors and materials, including the removal of Acrylic from the tab strip
- A fix to limit the opening of Settings from ribbon to one instance per app Window
- Changes to Removable Drive recognition
The following is still unimplemented:
- Dynamic updates of detected drive list
=> Several Tweaks

Files UWP/YourHome.xaml, Files UWP/YourHome.xaml.cs
Shows "Open File Location" for files only.
Related: #271
=> Show "Open File Location" on recent files only

Files/Assets/terminal/terminal.json
Fix #392
Crash if space in path
=> fix #392: crash if space in path;

Files/MultilingualResources/Files.fr-FR.xlf
Remaining TODO : `SettingsAppearanceAcrylicSidebar.Text`, + some [unclear details](https://github.com/duke7553/files-uwp/issues/37#issuecomment-583818576)
=> Perform french translations

Files/Files.csproj, Files/MultilingualResources/Files.nl-NL.xlf, Files/Strings/nl-NL/Resources.resw
Submission for Dutch Translation as discussed in #37 (reopened due to incorrect target/source branch in #411 )
=> Add Dutch translations

Files/Files.csproj, Files/MultilingualResources/Files.pl-PL.xlf, Files/Strings/pl-PL/Resources.resw
Added Polish (pl-PL) translation as part of #37
=> Add Polish Translation

Files/Views/Pages/Settings.xaml.cs
Sorry about the conflicts before, this time should work now. 🙇
=> Fixed the problem of Settings page when in non-English environment.

azure-pipelines-build-test.yml
=> Set up CI with Azure Pipelines

Files/Files.csproj
With current set up, it installs 2 apps. 1. Files, 2. Files UWP - Preview. This PR fixes that.
=> Fix to not install Multiple Packages.

Files/MultilingualResources/Files.pl-PL.xlf
Updated translation and tested.
=> Updated Files.pl-PL.xlf translation

Files/MultilingualResources/Files.de-DE.xlf
=> Updated German translation

Files/MultilingualResources/Files.es-ES.xlf
=> full translation into spanish Files.es-ES.xlf

Files/View Models/SettingsViewModel.cs
Improvements to work done by @tsvietOK 
In addition to his contributions, we now handle serialization exceptions during the deserialization process by reverting to the default config file's contents.
I'm leaving both PRs open for peer review purposes, but I happen to think mine is more complete unless anyone disagrees.
=> Improvements to work done by @tsvietOK 

Files/MultilingualResources/Files.zh-Hans.xlf, Files/Strings/zh-Hans/Resources.resw
Check may be needed for strings in RenameDialog.
=> Update translation to Chinese (Simplified) (zh-Hans)

Files/BaseLayout.cs, Files/UserControls/LayoutModes/GenericFileBrowser.xaml.cs, Files/UserControls/LayoutModes/PhotoAlbum.xaml.cs
=> Fix new folder/file creation looses focus with each letter

Files/MultilingualResources/Files.es-ES.xlf
=> Translation update [Spanish]

Files/Interacts/Interaction.cs, Files/MultilingualResources/Files.de-DE.xlf, Files/MultilingualResources/Files.es-ES.xlf, Files/MultilingualResources/Files.fr-FR.xlf, Files/MultilingualResources/Files.nl-NL.xlf, Files/MultilingualResources/Files.pl-PL.xlf, Files/MultilingualResources/Files.ru-RU.xlf, Files/MultilingualResources/Files.tr-TR.xlf, Files/MultilingualResources/Files.uk-UA.xlf, Files/MultilingualResources/Files.zh-Hans.xlf, Files/Properties.xaml, Files/Properties.xaml.cs, Files/ResourceDictionaries/ToolbarButtonStyle.xaml, Files/Strings/en-US/Resources.resw, Files/Strings/ru-RU/Resources.resw, Files/Strings/uk-UA/Resources.resw, Files/UserControls/NavigationToolbar/ModernNavigationToolbar.xaml
-MD5 field visible only for files properties
-Translated strings
-Added reveal button style to top navigation buttons like Back, Forward...
-Added checkboxes for future implementations of attributes change(currently disabled)
Prev PR #598
=> Redesign Properties window [2]

README.md
Users first check for screenshots. Include as early as possible
=> Moved image to top

Files/Files.csproj, Files/MultilingualResources/Files.de-DE.xlf, Files/MultilingualResources/Files.es-ES.xlf, Files/MultilingualResources/Files.fr-FR.xlf, Files/MultilingualResources/Files.it-IT.xlf, Files/MultilingualResources/Files.nl-NL.xlf, Files/MultilingualResources/Files.pl-PL.xlf, Files/MultilingualResources/Files.ru-RU.xlf, Files/MultilingualResources/Files.tr-TR.xlf, Files/MultilingualResources/Files.uk-UA.xlf, Files/MultilingualResources/Files.zh-Hans.xlf, Files/Strings/de-DE/Resources.resw, Files/Strings/en-US/Resources.resw, Files/Strings/it-IT/Resources.resw, Files/Strings/nl-NL/Resources.resw, Files/Strings/pl-PL/Resources.resw, Files/Strings/tr-TR/Resources.resw, Files/Strings/zh-Hans/Resources.resw, Files/UserControls/LayoutModes/GenericFileBrowser.xaml.cs, Files/View Models/SettingsViewModel.cs, Files/Views/Pages/Settings.xaml, Files/Views/Pages/Settings.xaml.cs, Files/Views/SettingsPages/Experimental.xaml, Files/Views/SettingsPages/Experimental.xaml.cs
- Added an experimental settings page
- Added new strings for the new page
- Added an experimental setting to turn off the double click to rename feature
=> Experimental settings

Files.Package/Package.appxmanifest, azure-pipelines-build-test.yml, azure-pipelines.yml
The app now has a different name for development and release packages.
=> Improved pipeline

Files/Files.csproj, Files/UserControls/ModernSidebar.xaml
Reverts duke7553/files-uwp#658
=> Revert "Upgrade to latest WinUI preview"

Files/View Models/ItemViewModel.cs
=> Disabled loading url files

Files/MultilingualResources/Files.de-DE.xlf, Files/Strings/de-DE/Resources.resw
Improvements on German Translation
=> Improvements on German Translation

Files/View Models/ItemViewModel.cs
This var hasn't been changed in PR #708
=> Fix file size calculation for var itemSizeBytes

Files/BaseLayout.cs, Files/View Models/InteractionViewModel.cs
Like .JPG, .PNG etc.
Fixed a crash when you right clicked a file without extension.
=> Add support for uppercase image extension

Files/Filesystem/Drives.cs
This requires testing to see if it fixes the crash.
=> Fix App Startup Crash By Deferring Adding Drives to UI

Files/App.xaml.cs, Files/Filesystem/DriveItem.cs, Files/Filesystem/Drives.cs, Files/Filesystem/INavigationControlItem.cs, Files/Filesystem/LocationItem.cs, Files/UserControls/ModernSidebar.xaml, Files/View Models/SettingsViewModel.cs
Removed unused vars
Optimized code
Attention to drive icons an their size
(Red line is center of column, just for example)
=> Fix blurred disk drive icons

Files/View Models/ItemViewModel.cs
TBA
Fixes #800 #810 
and might fix #799
=> Icon/Filesystem Fixes

Files/Files.csproj, Files/MultilingualResources/Files.ta.xlf, Files/Strings/ta/Resources.resw
Added Tamil (ta) translation as part of #37
Please note that the Multilingual App Toolkit recognizes four region variants of this language, however, I really don't see any difference so I created a generic resource file for all the variants.
=> Add Tamil translation

Files/MultilingualResources/Files.de-DE.xlf, Files/Strings/de-DE/Resources.resw, Files/Strings/ru-RU/Resources.resw, Files/Strings/uk-UA/Resources.resw
- Fixed: Files.de-DE.xlf
- Updated resources [de, uk, ru]
=> Updated resources [de, uk, ru] + fix

Files/MultilingualResources/Files.it-IT.xlf
=> Updates Files.it-IT.xlf

Files/MultilingualResources/Files.de-DE.xlf, Files/MultilingualResources/Files.es-ES.xlf, Files/MultilingualResources/Files.fr-FR.xlf, Files/MultilingualResources/Files.it-IT.xlf, Files/MultilingualResources/Files.nl-NL.xlf, Files/MultilingualResources/Files.pl-PL.xlf, Files/MultilingualResources/Files.ru-RU.xlf, Files/MultilingualResources/Files.ta.xlf, Files/MultilingualResources/Files.tr-TR.xlf, Files/MultilingualResources/Files.uk-UA.xlf, Files/MultilingualResources/Files.zh-Hans.xlf, Files/Strings/en-US/Resources.resw, Files/Strings/es-ES/Resources.resw, Files/UserControls/StatusBarControl.xaml
- Selection options
- Layout mode
**I'm not sure if they are the correct names for these buttons, let me know if it's ok**
=> ToolTip added for selection and layout mode button

Files/Views/InstanceTabsView.xaml.cs
Fix incorrect path while upward to root disk
=> Fix incorrect path while upward to root disk

Files.Launcher/Files.Launcher.csproj, Files/Files.csproj
Remove unnecessary Microsoft.Net.Compilers dependency
=> Remove Microsoft.Net.Compilers dependency

Files/Interacts/Interaction.cs
=> Check "permanently delete" automatically by pressing shift + Del

Files/DataModels/TerminalFileModel.cs
Which is not contain DefaultTerminalId field
=> Fix compatibility with old terminal.json file

Files/Filesystem/DriveItem.cs, Files/MultilingualResources/Files.de-DE.xlf, Files/MultilingualResources/Files.es-ES.xlf, Files/MultilingualResources/Files.fr-FR.xlf, Files/MultilingualResources/Files.it-IT.xlf, Files/MultilingualResources/Files.nl-NL.xlf, Files/MultilingualResources/Files.pl-PL.xlf, Files/MultilingualResources/Files.ru-RU.xlf, Files/MultilingualResources/Files.ta.xlf, Files/MultilingualResources/Files.tr-TR.xlf, Files/MultilingualResources/Files.uk-UA.xlf, Files/MultilingualResources/Files.zh-Hans.xlf, Files/Strings/en-US/Resources.resw, Files/Strings/es-ES/Resources.resw
- String added for the drivers tooltip
- Tooltip changed from "**.... of ....**" To "**.... free of ....**" since it is not clear to the user if it is free space or used
=> Updated drives tooltip + string added

Files/DataModels/TerminalFileModel.cs, Files/Files.csproj, Files/Helpers/PackageHelper.cs, Files/View Models/SettingsViewModel.cs
Add support for Fluent Terminal
=> Remove terminal from json if terminal app has been removed

Files/Interacts/Interaction.cs, Files/MultilingualResources/Files.de-DE.xlf, Files/MultilingualResources/Files.es-ES.xlf, Files/MultilingualResources/Files.fr-FR.xlf, Files/MultilingualResources/Files.it-IT.xlf, Files/MultilingualResources/Files.nl-NL.xlf, Files/MultilingualResources/Files.pl-PL.xlf, Files/MultilingualResources/Files.ru-RU.xlf, Files/MultilingualResources/Files.ta.xlf, Files/MultilingualResources/Files.tr-TR.xlf, Files/MultilingualResources/Files.uk-UA.xlf, Files/MultilingualResources/Files.zh-Hans.xlf, Files/Strings/en-US/Resources.resw, Files/Strings/it-IT/Resources.resw
=> Fix pasting to recycle bin - Issue 899

Files/View Models/SettingsViewModel.cs, Files/Views/SettingsPages/Experimental.xaml, Files/Views/SettingsPages/FilesAndFolders.xaml, Files/Views/SettingsPages/FilesAndFolders.xaml.cs, Files/Views/SettingsPages/OnStartup.xaml, Files/Views/SettingsPages/Preferences.xaml, Files/Views/SettingsPages/Preferences.xaml.cs
Currently some settings do not get applied. Some toggle buttons need to be toggled twice. This PR fixes this.
=> Fix settings

Files/UserControls/ModernSidebar.xaml, Files/UserControls/ModernSidebar.xaml.cs
=> Add ability to open sidebar drive in new window or tab

Files/MultilingualResources/Files.de-DE.xlf, Files/MultilingualResources/Files.es-ES.xlf, Files/MultilingualResources/Files.fr-FR.xlf, Files/MultilingualResources/Files.it-IT.xlf, Files/MultilingualResources/Files.nl-NL.xlf, Files/MultilingualResources/Files.pl-PL.xlf, Files/MultilingualResources/Files.ru-RU.xlf, Files/MultilingualResources/Files.ta.xlf, Files/MultilingualResources/Files.tr-TR.xlf, Files/MultilingualResources/Files.uk-UA.xlf, Files/MultilingualResources/Files.zh-Hans.xlf, Files/Strings/en-US/Resources.resw, Files/Strings/ru-RU/Resources.resw, Files/Strings/uk-UA/Resources.resw, Files/Views/SettingsPages/About.xaml, Files/Views/SettingsPages/About.xaml.cs
=> Added button to open debug.txt location in explorer

Files/Views/InstanceTabsView.xaml
=> Align tab button with close tab button

Files/UserControls/LayoutModes/GridViewBrowser.xaml
=> Add margin to gridview item

Files/Dialogs/PropertiesDialog.xaml, Files/Interacts/Interaction.cs, Files/Views/Pages/Properties.xaml.cs
Fixes #991 
Improved window design
Before:
After:
=> Properties: Fix Properties window crash on older systems

Files/App.xaml, Files/Views/Pages/Properties.xaml.cs
1. Fixed #645  issue with the help from microsoft support in [this thread](https://docs.microsoft.com/en-us/answers/questions/34670/basicpropertiesretrievepropertiesasyncnew-list-sys.html)
We can also improve the properties dialog by showing file owner, last accessed time like that using 
BasicProperties.RetrievePropertiesAsync()
2. Fixed #1003  It happens there is no known resources for High Contrast Resource Dictionary.
=> Fixed a crash when using the high contrast theme

Files/App.xaml.cs, Files/BaseLayout.cs, Files/Files.csproj, Files/MultilingualResources/Files.de-DE.xlf, Files/MultilingualResources/Files.es-ES.xlf, Files/MultilingualResources/Files.fr-FR.xlf, Files/MultilingualResources/Files.it-IT.xlf, Files/MultilingualResources/Files.ja-JP.xlf, Files/MultilingualResources/Files.nl-NL.xlf, Files/MultilingualResources/Files.pl-PL.xlf, Files/MultilingualResources/Files.ru-RU.xlf, Files/MultilingualResources/Files.ta.xlf, Files/MultilingualResources/Files.tr-TR.xlf, Files/MultilingualResources/Files.uk-UA.xlf, Files/MultilingualResources/Files.zh-Hans.xlf, Files/Strings/en-US/Resources.resw, Files/UserControls/StatusBarControl.xaml, Files/UserControls/StatusBarControl.xaml.cs, Files/View Models/SelectedItemsPropertiesViewModel.cs
- Added status for the selected items count
- Added the size of the selected item (right now it only shows the size if one item is selected)
=> Updated status bar

Files/MultilingualResources/Files.it-IT.xlf
- New translations
- Updated some translations
=> Updated italian translations

Files.Launcher/Program.cs, Files/App.xaml.cs, Files/View Models/SettingsViewModel.cs
Changes for the recycle bin support broke quicklook detection. This PR fixes this.
Fixes #969, #1058
=> Fix quicklook detection

Files/App.xaml.cs, Files/DataModels/SidebarPinnedModel.cs, Files/Files.csproj, Files/Interacts/Interaction.cs, Files/UserControls/ModernSidebar.xaml, Files/UserControls/ModernSidebar.xaml.cs, Files/View Models/SettingsViewModel.cs
Moved from "PinnedItems.txt" to "PinnedItems.json" (with back compatibility with "PinnedItems.txt")
Fixed "Unpin from Sidebar" menu displaying when right clicking on Drive item
Fixed #1022
=> ModernSidebar: Rework pinned to SideBar items model

Files/Interacts/Interaction.cs, Files/Views/Pages/Properties.xaml.cs
- Cancel hash computation after property window closed
=> Added ability to cancel hash computation

Files/DataModels/SidebarPinnedModel.cs, Files/Interacts/Interaction.cs, Files/MultilingualResources/Files.de-DE.xlf, Files/MultilingualResources/Files.es-ES.xlf, Files/MultilingualResources/Files.fr-FR.xlf, Files/MultilingualResources/Files.it-IT.xlf, Files/MultilingualResources/Files.ja-JP.xlf, Files/MultilingualResources/Files.nl-NL.xlf, Files/MultilingualResources/Files.pl-PL.xlf, Files/MultilingualResources/Files.ru-RU.xlf, Files/MultilingualResources/Files.ta.xlf, Files/MultilingualResources/Files.tr-TR.xlf, Files/MultilingualResources/Files.uk-UA.xlf, Files/MultilingualResources/Files.zh-Hans.xlf, Files/Strings/en-US/Resources.resw, Files/UserControls/LayoutModes/GenericFileBrowser.xaml, Files/UserControls/LayoutModes/GridViewBrowser.xaml
=> Added pin path to sidebar to right click context menu

Files/View Models/ItemViewModel.cs
=> Automatically refresh the itemCount of the status bar

Files/Views/Pages/Properties.xaml
=> Add margin to folder size progress ring

Files/Interacts/Interaction.cs, Files/View Models/ItemViewModel.cs, Files/View Models/SelectedItemsPropertiesViewModel.cs, Files/Views/Pages/Properties.xaml.cs
Fix opening properties for current directory
Code align
=> Properties: Fix progressRing displayed for files properties

Files/View Models/SelectedItemsPropertiesViewModel.cs, Files/Views/Pages/Properties.xaml
Files-uwp crashes when try to calculate hash for files which cannot be accessed.
This PR contains fix for it and will show an error on the ProgressBar if failed.
=> Properties: Prevent crash when access denied

Files.Launcher/Program.cs, Files/Assets/terminal/terminal.json, Files/Interacts/Interaction.cs, Files/View Models/SettingsViewModel.cs, Files/Views/SettingsPages/Appearance.xaml.cs
- Set WorkingDirectory for terminal so that cmd no longer need to execute `cd` command for switching directory.
=> Set WorkingDirectory for terminal

Files/Strings/ru-RU/Resources.resw, Files/Strings/uk-UA/Resources.resw, Files/View Models/SelectedItemsPropertiesViewModel.cs
=> Fix string loading 

Common/ShellFileItem.cs, Files.Launcher/Program.cs, Files/Filesystem/DriveItem.cs, Files/Filesystem/ListedItem.cs, Files/Helpers/StringExtensions.cs, Files/MultilingualResources/Files.de-DE.xlf, Files/MultilingualResources/Files.es-ES.xlf, Files/MultilingualResources/Files.fr-FR.xlf, Files/MultilingualResources/Files.it-IT.xlf, Files/MultilingualResources/Files.ja-JP.xlf, Files/MultilingualResources/Files.nl-NL.xlf, Files/MultilingualResources/Files.pl-PL.xlf, Files/MultilingualResources/Files.ru-RU.xlf, Files/MultilingualResources/Files.ta.xlf, Files/MultilingualResources/Files.tr-TR.xlf, Files/MultilingualResources/Files.uk-UA.xlf, Files/MultilingualResources/Files.zh-Hans.xlf, Files/Strings/en-US/Resources.resw, Files/Strings/ru-RU/Resources.resw, Files/Strings/uk-UA/Resources.resw, Files/View Models/ItemViewModel.cs, Files/View Models/SelectedItemsPropertiesViewModel.cs
Example: GiB -> GB
Fixed large file sizes
=> Add ability to convert size abbreviations and translate them

Files/App.xaml.cs, Files/Views/InstanceTabsView.xaml.cs
This PR fixes the right click + open in new window functionality.
Probably after 53ba1a87f2675a5dfd9a01a6c24ed44b3ed5341a I'm getting NullPointerException on `ThemeHelper.Initialize()`
=> Fix open in new window

Files/Filesystem/Drives.cs
=> Drives: Fixed drives loading when no letter assigned to partition

Files/BaseLayout.cs
=> Status bar: Show total size of selected files

Files/DataModels/SidebarPinnedModel.cs, Files/Views/InstanceTabsView.xaml.cs
Fixed self reference loop
Fixed NullReferenceException as mentioned [here](https://github.com/files-community/files-uwp/issues/1185#issuecomment-647189413)
=> Fixed app launch

Files/UserControls/StatusBarControl.xaml
Fix #1221 
------------------------------------------
sorry i forgot to update the status bar icon resources
=> Fix: Status bar is not visible

Files/Dialogs/PropertiesDialog.xaml, Files/Dialogs/PropertiesDialog.xaml.cs, Files/Views/Pages/Properties.xaml.cs
=> Retrieve Better Thumbnails for files in Properties Dialog

Files/Views/Pages/Properties.xaml
=> Use Fluent Folder Glyph for Properties Dialog

Files/Interacts/Interaction.cs, Files/Navigation/NavigationActions.cs, Files/UserControls/ModernNavigationToolbar.xaml.cs, Files/UserControls/SidebarControl.cs, Files/Views/InstanceTabsView.xaml.cs, Files/Views/ModernShellPage.xaml.cs
=> Added string for "New tab" that appears in path

Files/Views/SettingsPages/About.xaml, Files/Views/SettingsPages/Appearance.xaml, Files/Views/SettingsPages/Experimental.xaml, Files/Views/SettingsPages/FilesAndFolders.xaml, Files/Views/SettingsPages/OnStartup.xaml, Files/Views/SettingsPages/Preferences.xaml
=> Settings: Remove transition animations

Files/Views/LayoutModes/GenericFileBrowser.xaml, Files/Views/LayoutModes/GridViewBrowser.xaml
=> RecycleBin: Remove Properties menu item for the folder itself

Files/App.xaml, Files/App.xaml.cs, Files/UserControls/ModernNavigationToolbar.xaml, Files/UserControls/StatusBarControl.xaml, Files/UserControls/YourHome.xaml, Files/Views/InstanceTabsView.xaml, Files/Views/InstanceTabsView.xaml.cs, Files/Views/ModernShellPage.xaml
Hopefully this has a pronounced effect on startup time for some users, but I wouldn't get my hopes up.
=> Remove/Reduce Unnecessary Resources in App.xaml

Files/Interacts/Interaction.cs
Fixes #1348
Also restores fix for issue #1088 which was lost in e94bd59f6ab0e7dcb13c892f54b65e87d17eeccf
=> Fix app crashed when moving a file

Files/Strings/zh-Hans/Resources.resw, Files/View Models/ItemViewModel.cs, Files/Views/LayoutModes/GenericFileBrowser.xaml, Files/Views/LayoutModes/GridViewBrowser.xaml
=> RecycleBin: Disable Clear recycle bin context menu when it is empty

Files/MultilingualResources/Files.pt-BR.xlf
Translations corrections and typos fixes
=> pt-BR translation improvements

Files/App.xaml.cs, Files/Dialogs/ExceptionDialog.xaml.cs, Files/Interacts/Interaction.cs, Files/Views/InstanceTabsView.xaml.cs
=> Unified app close methods

Files/MultilingualResources/Files.it-IT.xlf, Files/Strings/it-IT/Resources.resw
=> Translation update [it-IT]

Files/Files.csproj, Files/MultilingualResources/Files.or-IN.xlf, Files/Strings/or-IN/Resources.resw
Added translation for or-IN(Odia, India).
=> Added translation for or-IN

Files/Enums/WallpaperType.cs, Files/Files.csproj, Files/Interacts/Interaction.cs
=> Interaction: Fixes setting an image as lock screen background

Files/Files.csproj, Files/MultilingualResources/Files.hi-IN.xlf, Files/Strings/hi-IN/Resources.resw
Added translation for hi-IN(Hindi, India).
=> Added translation for hi-IN

Files/Interacts/Interaction.cs, Files/UserControls/ModernNavigationToolbar.xaml, Files/UserControls/ModernNavigationToolbar.xaml.cs
Fixed #1229 and typo for environment variable.
=> Some typo and bug fixes

Files/CommandLine/CommandLineParser.cs, Files/Views/ModernShellPage.xaml.cs
=> Fix folder launch from cmd

Files/Filesystem/StorageFileHelpers/StorageFileExtensions.cs, Files/UserControls/ModernNavigationToolbar.xaml.cs
Travelling to folders with relative path are now allowed also added support for entering any environment variables in NavigationToolBar
=> Added relative path support and environmental variable support to NavigationToolBar

Files/App.xaml.cs
Added tracking of unhandled and unobserved exceptions.
=> Better exception handling and tracking

Files/UserControls/ModernNavigationToolbar.xaml.cs, Files/UserControls/VerticalTabView.xaml, Files/UserControls/VerticalTabView.xaml.cs, Files/Views/MainPage.xaml.cs
=> Fixed drag-drop and rearrange tabs

Files/MultilingualResources/Files.de-DE.xlf, Files/MultilingualResources/Files.es-ES.xlf, Files/MultilingualResources/Files.fr-FR.xlf, Files/MultilingualResources/Files.he-IL.xlf, Files/MultilingualResources/Files.hi-IN.xlf, Files/MultilingualResources/Files.it-IT.xlf, Files/MultilingualResources/Files.ja-JP.xlf, Files/MultilingualResources/Files.nl-NL.xlf, Files/MultilingualResources/Files.or-IN.xlf, Files/MultilingualResources/Files.pl-PL.xlf, Files/MultilingualResources/Files.pt-BR.xlf, Files/MultilingualResources/Files.ru-RU.xlf, Files/MultilingualResources/Files.ta.xlf, Files/MultilingualResources/Files.tr-TR.xlf, Files/MultilingualResources/Files.uk-UA.xlf, Files/MultilingualResources/Files.zh-Hans.xlf, Files/Strings/en-US/Resources.resw, Files/Strings/hi-IN/Resources.resw
Updated strings for hi-IN and fixed some strings.
=> Updated strings for hi-IN and fixed some strings

Files/Filesystem/StorageFileHelpers/StorageFileExtensions.cs
=> Ignore case for environment variables

Files/Files.csproj, Files/UserControls/SidebarControl.xaml.cs
=> Fixed sidebar renavigation issue

Files/UserControls/ModernNavigationToolbar.xaml.cs
=> Added support for launching URIs from the NavigationBar

Files/BaseLayout.cs, Files/Filesystem/StorageFileHelpers/StorageFileExtensions.cs, Files/MultilingualResources/Files.de-DE.xlf, Files/MultilingualResources/Files.es-ES.xlf, Files/MultilingualResources/Files.fr-FR.xlf, Files/MultilingualResources/Files.he-IL.xlf, Files/MultilingualResources/Files.hi-IN.xlf, Files/MultilingualResources/Files.it-IT.xlf, Files/MultilingualResources/Files.ja-JP.xlf, Files/MultilingualResources/Files.nl-NL.xlf, Files/MultilingualResources/Files.or-IN.xlf, Files/MultilingualResources/Files.pl-PL.xlf, Files/MultilingualResources/Files.pt-BR.xlf, Files/MultilingualResources/Files.ru-RU.xlf, Files/MultilingualResources/Files.ta.xlf, Files/MultilingualResources/Files.tr-TR.xlf, Files/MultilingualResources/Files.uk-UA.xlf, Files/MultilingualResources/Files.zh-Hans.xlf, Files/Strings/en-US/Resources.resw
=> Implemented dragging storage items from other apps into Files UWP

Files/UserControls/SidebarControl.xaml.cs
Fixed crash when dragging text to sidebar items.
Fixes #1619
=> Fixed crash when dragging text to sidebar

Files/View Models/Properties/FileProperties.cs, Files/Views/Pages/PropertiesShortcut.xaml
=> display "open file location" only for .lnk files in properties

Files/BaseLayout.cs
=> Add "open" to context menu for folders and shortcuts

Files/Interacts/Interaction.cs, Files/View Models/Properties/FileProperties.cs, Files/View Models/Properties/FolderProperties.cs, Files/View Models/SelectedItemsPropertiesViewModel.cs, Files/Views/Pages/Properties.xaml, Files/Views/Pages/Properties.xaml.cs, Files/Views/Pages/PropertiesGeneral.xaml.cs, Files/Views/Pages/PropertiesShortcut.xaml.cs
Fixes #659, fixes #1076, fixes #973
This PR  fixes the annoying issue of the app closing when a Properties window is closed.
It involves switching from AppWindow to ApplicationView... let me know if this is ok for you :)
=> Fix app crash on Properties window closing

Files/View Models/SelectedItemsPropertiesViewModel.cs
=> Fixed an issue where "Set as desktop background" would sometimes show on the context menu for shortcut files.

Files/Strings/ta/Resources.resw, Files/UserControls/HorizontalMultitaskingControl.xaml
=> Fixed the padding on the horizontal tab views scroll buttons

Files/MultilingualResources/Files.de-DE.xlf, Files/MultilingualResources/Files.es-ES.xlf, Files/MultilingualResources/Files.fr-FR.xlf, Files/MultilingualResources/Files.he-IL.xlf, Files/MultilingualResources/Files.hi-IN.xlf, Files/MultilingualResources/Files.it-IT.xlf, Files/MultilingualResources/Files.ja-JP.xlf, Files/MultilingualResources/Files.nl-NL.xlf, Files/MultilingualResources/Files.or-IN.xlf, Files/MultilingualResources/Files.pl-PL.xlf, Files/MultilingualResources/Files.pt-BR.xlf, Files/MultilingualResources/Files.ru-RU.xlf, Files/MultilingualResources/Files.ta.xlf, Files/MultilingualResources/Files.tr-TR.xlf, Files/MultilingualResources/Files.uk-UA.xlf, Files/MultilingualResources/Files.zh-Hans.xlf, Files/Strings/en-US/Resources.resw, Files/View Models/SettingsViewModel.cs, Files/Views/SettingsPages/About.xaml, Files/Views/SettingsPages/About.xaml.cs
=> Updated the about page

Files/UserControls/HorizontalMultitaskingControl.xaml, Files/UserControls/HorizontalMultitaskingControl.xaml.cs, Files/Views/ModernShellPage.xaml, Files/Views/ModernShellPage.xaml.cs
=> Fixed window dragging in different modes

Files/MultilingualResources/Files.de-DE.xlf, Files/MultilingualResources/Files.es-ES.xlf, Files/MultilingualResources/Files.fr-FR.xlf, Files/MultilingualResources/Files.he-IL.xlf, Files/MultilingualResources/Files.hi-IN.xlf, Files/MultilingualResources/Files.it-IT.xlf, Files/MultilingualResources/Files.ja-JP.xlf, Files/MultilingualResources/Files.nl-NL.xlf, Files/MultilingualResources/Files.or-IN.xlf, Files/MultilingualResources/Files.pl-PL.xlf, Files/MultilingualResources/Files.pt-BR.xlf, Files/MultilingualResources/Files.ru-RU.xlf, Files/MultilingualResources/Files.ta.xlf, Files/MultilingualResources/Files.tr-TR.xlf, Files/MultilingualResources/Files.uk-UA.xlf, Files/MultilingualResources/Files.zh-Hans.xlf, Files/Strings/en-US/Resources.resw, Files/Strings/it-IT/Resources.resw
Updated translations for it-IT for version 0.13
Added missing string resource for multitasking flyout
=> [it-IT] - Translation update

Files/MultilingualResources/Files.de-DE.xlf, Files/MultilingualResources/Files.es-ES.xlf, Files/MultilingualResources/Files.fr-FR.xlf, Files/MultilingualResources/Files.he-IL.xlf, Files/MultilingualResources/Files.hi-IN.xlf, Files/MultilingualResources/Files.it-IT.xlf, Files/MultilingualResources/Files.ja-JP.xlf, Files/MultilingualResources/Files.nl-NL.xlf, Files/MultilingualResources/Files.or-IN.xlf, Files/MultilingualResources/Files.pl-PL.xlf, Files/MultilingualResources/Files.pt-BR.xlf, Files/MultilingualResources/Files.ru-RU.xlf, Files/MultilingualResources/Files.ta.xlf, Files/MultilingualResources/Files.tr-TR.xlf, Files/MultilingualResources/Files.uk-UA.xlf, Files/MultilingualResources/Files.zh-Hans.xlf, Files/Strings/de-DE/Resources.resw, Files/Strings/en-US/Resources.resw, Files/Strings/es-ES/Resources.resw, Files/Strings/nl-NL/Resources.resw, Files/Strings/or-IN/Resources.resw, Files/Strings/pl-PL/Resources.resw, Files/Strings/pt-BR/Resources.resw, Files/Strings/ru-RU/Resources.resw, Files/Strings/ta/Resources.resw, Files/Strings/uk-UA/Resources.resw, Files/Views/SettingsPages/About.xaml
Fixes #1699 
UI elements spacing should be done from markup, don't change an actual element text.
=> Settings: Fix space at the end of string

Files.Launcher/Program.cs, Files/App.xaml.cs, Files/View Models/ItemViewModel.cs
Fix #1653, fix #1596
With this PR when an item is added or removed from the recycle-bin only that item is added/removed to the file list instead of reloading the whole folder content every time.
=> Improve recyclebin contents update

Files.Package/Package.appxmanifest
Use unified(4 dots) tabulation for the whole file.
=> Files.Package: Manifest: Fix tabulation

Files/Views/Pages/Properties.xaml, Files/Views/Pages/Properties.xaml.cs, Files/Views/Pages/PropertiesGeneral.xaml.cs
=> Added a cancel button to the properties dialog

Files/MultilingualResources/Files.de-DE.xlf
I added some German translations
=> Improve translation [de-DE]

Files/Filesystem/Drives.cs
=> Fix crash when connecting certain drives

Files/Views/Pages/Properties.xaml
=> Reordered buttons on the properties dialog

Files/Filesystem/Drives.cs
Fixes #1813
Sometimes an UnauthorizedAccessException error is thrown on some drives even if the app has been granted the FileSystem permission.
This PR shows the consent dialog only if no fixed drive could be loaded.
=> Fixed an issue where the file access consent dialog would sometimes show even after permission was already granted

Files/App.xaml.cs
=> Open github new issue page from crash notification

Files/UserControls/YourHome.xaml.cs, Files/View Models/ItemViewModel.cs
=> Fixed an issue where navigating away from the home page sometimes wouldn't work

Files/MultilingualResources/Files.de-DE.xlf
I fixed some typos and translated some strings.
=> Update German localization

Files.Launcher/Program.cs
=> Fix an issue where the "Empty Recycle Bin" menu entry was always disabled

Files/Commands/Paste.cs
Fixes a crash some users encountered with various items.
=> Fixed an issue where the progress status displayed as zero when pasting one item

README.md
=> Improvements to README.md wording

Files/Views/LayoutModes/GridViewBrowser.xaml
=> Fixed an issue with localized file types in tiles view

Files.Launcher/Program.cs, Files.Launcher/Win32API_ContextMenu.cs
This PR:
- Fixes an issue causing some menu items not to work
- Enables the WSL "Open linux shell here" command (now working)
- ~Enables the "Send To" menu (now working)~
=> Enabled the "Open linux shell here" context menu item

Files/Views/ModernShellPage.xaml.cs
=> Fixed an issue where trying to copy a files name would copy the file instead

Files.Extensions/Files.Extensions.vcxproj
=> Updated target platform version

Files/Views/LayoutModes/GenericFileBrowser.xaml, Files/Views/LayoutModes/GenericFileBrowser.xaml.cs, Files/Views/LayoutModes/GridViewBrowser.xaml
=> Fixed issues with sorting items from the right click context menu

Files/UserControls/MultitaskingControl/HorizontalMultitaskingControl.xaml.cs, Files/UserControls/MultitaskingControl/VerticalTabViewControl.xaml.cs
=> Switch to new tab when one is opened

Files/MultilingualResources/Files.ja-JP.xlf, Files/Strings/ja-JP/Resources.resw
- Update translations for ja-JP
=> Update translations for ja-JP

Files/Filesystem/ListedItem.cs, Files/View Models/Properties/FolderProperties.cs
=> Fixed an issue with the way dates were displayed in the app

Files.Launcher/Program.cs, Files/BaseLayout.cs, Files/Views/LayoutModes/GenericFileBrowser.xaml, Files/Views/LayoutModes/GenericFileBrowser.xaml.cs, Files/Views/LayoutModes/GridViewBrowser.xaml, Files/Views/LayoutModes/GridViewBrowser.xaml.cs
=> Display shell context menu items when right clicking on an empty space

Files/Views/ModernShellPage.xaml.cs
=> Do not show add item dialog when pressing ctrl+shift+n in recyclebin

Files.Launcher/Program.cs, Files.Launcher/Win32API.cs, Files/Interacts/Interaction.cs
Fixes a couple of issues that resulted in app/fulltrust process crash when trying to open files and folders
=> Fixed a crash that sometimes occurred when opening files and folders

Files/UserControls/ModernNavigationToolbar.xaml
=> Added AutomationProperties to the navigation menu

Files.Launcher/Win32API.cs, Files/View Models/ItemViewModel.cs
Changes in this PR:
- Do not show icon overlay for shortcut files
- Fix issue of icon overlay appearing way too small for some programs (e.g. MEGA client)
- Small refactor to remove code duplication
=> Fix issues with icon overlays

Files/UserControls/Widgets/RecentFiles.xaml.cs
=> Recent items now running in their directory.

Files/MultilingualResources/Files.ta.xlf
=> Update translation for Tamil

Files.Launcher/Program.cs, Files/BaseLayout.cs, Files/IShellPage.cs, Files/Interacts/Interaction.cs, Files/UserControls/SidebarControl.xaml.cs, Files/UserControls/YourHome.xaml, Files/UserControls/YourHome.xaml.cs, Files/View Models/ItemViewModel.cs, Files/Views/ModernShellPage.xaml.cs
This PR contains
- Proposal to fix the crash due to Disposed AppServiceConnection by making the Connection part of the IShellPage interface
- Fixes crash in HomePage due to changes to the widgets
- (Fixes a small mistake *I may have done* when merging master)
=> [AppCurrentInstance-bye-bye] Add AppServiceConnection to IShellPage

Files/MultilingualResources/Files.hu-HU.xlf
=> 📓 Updated HUN

Files/Views/MainPage.xaml.cs, Files/Views/ModernShellPage.xaml.cs
This PR adds some more cleanup of resources in ModernShellPage Dispose() method
=> [App current instance bye bye] Add some missing cleanup

Files/Filesystem/DriveItem.cs
Fixes #2249
Fixes #2260
Fixes (partially) #2245
=> Fixed an issue that would occur when a drive is connected/disconnected

Files/Commands/Paste.cs, Files/DataModels/SidebarPinnedModel.cs, Files/Filesystem/Drives.cs, Files/Filesystem/StorageFileHelpers/FilesystemResult.cs, Files/Interacts/Interaction.cs, Files/View Models/ItemViewModel.cs, Files/View Models/Properties/FileProperties.cs, Files/View Models/SettingsViewModel.cs, Files/Views/ModernShellPage.xaml.cs, Files/Views/SettingsPages/Preferences.xaml.cs
This PR fixes the crash you noticed when onedrive path is null.
=> Fix crash when onedrive is not detected

Files/UserControls/SidebarControl.xaml.cs, Files/Views/ModernShellPage.xaml.cs
=> Fixed an issue that would sometimes occur when moving tabs between windows

Files/Views/ModernShellPage.xaml.cs
=> Fixed an issue that would sometimes occur when opening a network drive path in a new tab

Files.Package/Files.Package.wapproj, Files.Package/priconfig.default.xml, Files.Package/priconfig.packaging.xml
This change will allow users to change the language even if the user did not install the region from the Windows settings app.
=> Include language resources in the app package

Files/Commands/Delete.cs, Files/Commands/Paste.cs, Files/Files.csproj, Files/Helpers/NativeDirectoryChangesHelper.cs, Files/Helpers/NativeFileOperationsHelper.cs, Files/Helpers/NativeFindStorageItemHelper.cs, Files/Interacts/Interaction.cs, Files/View Models/ItemViewModel.cs, Files/View Models/SelectedItemsPropertiesViewModel.cs, Files/Views/Pages/PropertiesGeneral.xaml
This PR adds support for setting a file/folder as hidden and read-only from properties page (it enables the checkboxes)
=> [Hidden files] - Enable setting file/folder as hidden in Properties page

Files/UserControls/Selection/RectangleSelection_DataGrid.cs, Files/UserControls/Selection/RectangleSelection_ListViewBase.cs
Fixes #2349 
This PR disables drag selection with touch input to not interfere with list scrolling
=> Do not trigger selection rectangle with touch

Files/Strings/hu-HU/Resources.resw, Files/UserControls/SidebarControl.xaml
=> Added a tooltip with the path for pinned items on the sidebar

Files/Interacts/Interaction.cs
=> Added a PersistentId to the properties window

Files/Interacts/Interaction.cs, Files/Views/LayoutModes/GenericFileBrowser.xaml, Files/Views/LayoutModes/GridViewBrowser.xaml.cs
Fixes #1343
This works in all the layout modes
=> Added support for opening folders in a new tab by clicking the middle mouse button

Files/UserControls/Widgets/DrivesWidget.xaml
=> Fixed an issue where the text would sometimes get cut off on the drive widget

Files/Strings/fr-FR/Resources.resw, Files/Views/LayoutModes/GenericFileBrowser.xaml
=> Improve theming of DataGrid column header separator line

Files/Filesystem/Drives.cs, Files/UserControls/Widgets/DrivesWidget.xaml
- Removed virtual drives from the drive widget
- Fixed the center point for the drive widgets cards
=> Removed virtual drives from the drive widget

Common/DeviceEvent.cs, Files.Launcher/DeviceWatcher.cs, Files.Launcher/Files.Launcher.csproj, Files.Launcher/Program.cs, Files/App.xaml.cs, Files/Filesystem/DriveItem.cs, Files/Filesystem/Drives.cs, Files/View Models/ItemViewModel.cs, Files/Views/Pages/PropertiesGeneral.xaml.cs
Fixes #2403
Fixes #1490
Fixes #1257
Refresh drive list when an ISO, VHD gets inserted or removed.
=> Refresh drives list when mounting/unmounting ISO file

Files/Views/ModernShellPage.xaml.cs
=> Allow navigating to hidden folders from path bar

Files/View Models/ItemViewModel.cs
Fixes #2435
Fixes #1857
Fixes #2362
=> Fix file watcher and order files on new item

Files/UserControls/Widgets/DrivesWidget.xaml
=> Fixed an issue where you cannot display more than 4 drives in a row on the home page

Files/Views/Settings.xaml.cs
=> Fixed an issue where clicking the back button on the settings page in tablet mode wouldn't work

Files/Dialogs/AddItemDialog.xaml, Files/Dialogs/RenameDialog.xaml
Fixes #2491 using DefaultButtonStyle
=> Fixed the rounded corners of the buttons in the RenameDialog & AddItemDialog

Files/MultilingualResources/Files.de-DE.xlf, Files/MultilingualResources/Files.es-ES.xlf, Files/MultilingualResources/Files.fr-FR.xlf, Files/MultilingualResources/Files.he-IL.xlf, Files/MultilingualResources/Files.hi-IN.xlf, Files/MultilingualResources/Files.hu-HU.xlf, Files/MultilingualResources/Files.it-IT.xlf, Files/MultilingualResources/Files.ja-JP.xlf, Files/MultilingualResources/Files.nl-NL.xlf, Files/MultilingualResources/Files.or-IN.xlf, Files/MultilingualResources/Files.pl-PL.xlf, Files/MultilingualResources/Files.pt-BR.xlf, Files/MultilingualResources/Files.ru-RU.xlf, Files/MultilingualResources/Files.ta.xlf, Files/MultilingualResources/Files.tr-TR.xlf, Files/MultilingualResources/Files.uk-UA.xlf, Files/MultilingualResources/Files.zh-Hans.xlf, Files/MultilingualResources/Files.zh-Hant.xlf, Files/Strings/en-US/Resources.resw, Files/UserControls/StatusBarControl.xaml, Files/UserControls/StatusBarControl.xaml.cs, Files/View Models/SettingsViewModel.cs
The goal of this teaching tip is to help improve discoverability of the status center.
=> Added a teaching tip that shows the first time someone pastes a file

Files/MultilingualResources/Files.de-DE.xlf, Files/MultilingualResources/Files.es-ES.xlf, Files/MultilingualResources/Files.fr-FR.xlf, Files/MultilingualResources/Files.he-IL.xlf, Files/MultilingualResources/Files.hi-IN.xlf, Files/MultilingualResources/Files.hu-HU.xlf, Files/MultilingualResources/Files.it-IT.xlf, Files/MultilingualResources/Files.ja-JP.xlf, Files/MultilingualResources/Files.nl-NL.xlf, Files/MultilingualResources/Files.or-IN.xlf, Files/MultilingualResources/Files.pl-PL.xlf, Files/MultilingualResources/Files.pt-BR.xlf, Files/MultilingualResources/Files.ru-RU.xlf, Files/MultilingualResources/Files.ta.xlf, Files/MultilingualResources/Files.tr-TR.xlf, Files/MultilingualResources/Files.uk-UA.xlf, Files/MultilingualResources/Files.zh-Hans.xlf, Files/MultilingualResources/Files.zh-Hant.xlf, Files/Strings/en-US/Resources.resw, Files/Strings/fr-FR/Resources.resw, Files/Strings/hu-HU/Resources.resw, Files/UserControls/StatusCenter.xaml, Files/UserControls/StatusCenter.xaml.cs
- Improved the responsiveness of status banners
- Added AutomationProperties for the dismiss banner button
- Added a tooltip to the dismiss banner button
=> Improved the status centers design

Files/UserControls/Widgets/RecentFiles.xaml
=> Fixed an issue where the recent files list is not accessible via the screen reader

Files/MultilingualResources/Files.de-DE.xlf, Files/MultilingualResources/Files.es-ES.xlf, Files/MultilingualResources/Files.fr-FR.xlf, Files/MultilingualResources/Files.he-IL.xlf, Files/MultilingualResources/Files.hi-IN.xlf, Files/MultilingualResources/Files.hu-HU.xlf, Files/MultilingualResources/Files.it-IT.xlf, Files/MultilingualResources/Files.ja-JP.xlf, Files/MultilingualResources/Files.nl-NL.xlf, Files/MultilingualResources/Files.or-IN.xlf, Files/MultilingualResources/Files.pl-PL.xlf, Files/MultilingualResources/Files.pt-BR.xlf, Files/MultilingualResources/Files.ru-RU.xlf, Files/MultilingualResources/Files.ta.xlf, Files/MultilingualResources/Files.tr-TR.xlf, Files/MultilingualResources/Files.uk-UA.xlf, Files/MultilingualResources/Files.zh-Hans.xlf, Files/MultilingualResources/Files.zh-Hant.xlf, Files/Strings/en-US/Resources.resw, Files/View Models/ItemViewModel.cs, Files/View Models/SettingsViewModel.cs, Files/Views/SettingsPages/FilesAndFolders.xaml
=> Added the option to list and sort directories alongside files

Files/Files.csproj, Files/ResourceDictionaries/CustomDataGridStyle.xaml, Files/UserControls/Selection/RectangleSelection_DataGrid.cs, Files/Views/LayoutModes/GenericFileBrowser.xaml
Fixes #1040
@XPoppyX could you verify whether this PR leads to the desired behaviour?
=> Added an empty space where there are no columns in the DataGrid layout

Files/MultilingualResources/Files.de-DE.xlf, Files/MultilingualResources/Files.es-ES.xlf, Files/MultilingualResources/Files.fr-FR.xlf, Files/MultilingualResources/Files.he-IL.xlf, Files/MultilingualResources/Files.hi-IN.xlf, Files/MultilingualResources/Files.hu-HU.xlf, Files/MultilingualResources/Files.it-IT.xlf, Files/MultilingualResources/Files.ja-JP.xlf, Files/MultilingualResources/Files.nl-NL.xlf, Files/MultilingualResources/Files.or-IN.xlf, Files/MultilingualResources/Files.pl-PL.xlf, Files/MultilingualResources/Files.pt-BR.xlf, Files/MultilingualResources/Files.ru-RU.xlf, Files/MultilingualResources/Files.ta.xlf, Files/MultilingualResources/Files.tr-TR.xlf, Files/MultilingualResources/Files.uk-UA.xlf, Files/MultilingualResources/Files.zh-Hans.xlf, Files/MultilingualResources/Files.zh-Hant.xlf, Files/Strings/en-US/Resources.resw, Files/UserControls/Widgets/DrivesWidget.xaml, Files/Views/SettingsPages/About.xaml
=> Fixed a couple of screen reader issues

Files/Filesystem/Drives.cs
This may/may not have an impact and requires testing.
=> Increase CoreDispatcherPriority of adding drive sidebar items to "Normal"

Files/BaseLayout.cs, Files/Views/LayoutModes/GenericFileBrowser.xaml.cs, Files/Views/LayoutModes/GridViewBrowser.xaml.cs
These changes could allow to remove some duplicated code in ColumnViewBrowser.xaml.cs in PR #2500
=> Cleanup: Moved duplicated code to the BaseLayout

Files/View Models/Properties/FolderProperties.cs
=> Fixed an issue where the properties dialog would sometimes show the properties of the wrong directory

Files/MultilingualResources/Files.pl-PL.xlf
Hi, as native I updated, fixed and checked translation for Polish language.
=> Update polish translation

Files/View Models/ItemViewModel.cs
Fixes #2614 
Fixes an issue where file icons are not shown on startup
Fixes an issue where file icons are not shown for connected phone storage
=> Fixes an issue where file icons are sometimes not shown

Files/Controllers/TerminalController.cs, Files/Helpers/RegistryHelper.cs
Fixes #2647
@Jaiganeshkumaran could you verify if this PR solves the issue you reported? Thanks!
=> Fixed crash on app launch

Files/Views/LayoutModes/GenericFileBrowser.xaml, Files/Views/LayoutModes/GridViewBrowser.xaml
=> Switched the color of the selection rectangle to the system accent color

Files/Dialogs/PropertiesDialog.xaml, Files/Enums/SidebarOpacity.cs, Files/UserControls/MultitaskingControl/HorizontalMultitaskingControl.xaml, Files/UserControls/SidebarControl.xaml, Files/View Models/SettingsViewModel.cs, Files/Views/Pages/Properties.xaml.cs, Files/Views/Settings.xaml, Files/Views/SettingsPages/Appearance.xaml
- Fixed an issue where changing a setting wouldn't save the setting correctly the first time the value was changed
- Improved the acrylic setting in SettingsViewModel
=> Fixed an issue where changing a setting wouldn't save the setting correctly the first time the value was changed

Files/View Models/SettingsViewModel.cs
- Added documentation to many of the settings
- Added regions for better code organization
- Moved all settings to local settings for consistency
=> Cleaned up some code in SettingsViewModel

Files/Views/LayoutModes/GenericFileBrowser.xaml, Files/Views/LayoutModes/GenericFileBrowser.xaml.cs
=> Details View: Unsubscribe from DataGrid LoadingRow event on layout mode change

Files/Views/Pages/PropertiesGeneral.xaml
=> Removed image in properties window from the control tree

Files/ResourceDictionaries/CustomHeaderStyle.xaml, Files/UserControls/Widgets/RecentFiles.xaml, Files/UserControls/Widgets/RecentFiles.xaml.cs
This change removes the confirm dialog when removing one item from the recent file widget.
=> Cleaned up the recent file widget

Files/Filesystem/Search/FolderSearch.cs, Files/MultilingualResources/Files.de-DE.xlf, Files/MultilingualResources/Files.es-ES.xlf, Files/MultilingualResources/Files.fr-FR.xlf, Files/MultilingualResources/Files.he-IL.xlf, Files/MultilingualResources/Files.hi-IN.xlf, Files/MultilingualResources/Files.hu-HU.xlf, Files/MultilingualResources/Files.it-IT.xlf, Files/MultilingualResources/Files.ja-JP.xlf, Files/MultilingualResources/Files.nl-NL.xlf, Files/MultilingualResources/Files.or-IN.xlf, Files/MultilingualResources/Files.pl-PL.xlf, Files/MultilingualResources/Files.pt-BR.xlf, Files/MultilingualResources/Files.ru-RU.xlf, Files/MultilingualResources/Files.ta.xlf, Files/MultilingualResources/Files.tr-TR.xlf, Files/MultilingualResources/Files.uk-UA.xlf, Files/MultilingualResources/Files.zh-Hans.xlf, Files/MultilingualResources/Files.zh-Hant.xlf, Files/Strings/en-US/Resources.resw, Files/View Models/SettingsViewModel.cs, Files/Views/SettingsPages/FilesAndFolders.xaml
=> Added an option to search unindexed items

FAQ.md, README.md
Additional resources can be added here
Closes #2666
=> Created FAQ.md

Files/Views/LayoutModes/GenericFileBrowser.xaml, Files/Views/LayoutModes/GridViewBrowser.xaml
=> Selection rectangle: Fixed stroke color

Files/View Models/FolderSettingsViewModel.cs
Fixes an issue for which the wrong layout mode is selected when navigating using the address bar (clicking on the path bar components)
=> Fixed layout selection when navigating using the address bar

Files/Views/LayoutModes/GenericFileBrowser.xaml.cs
Closes: https://github.com/files-community/Files/issues/1834
=> Prevent item edit from losing focus on right click

Files/Properties/Default.rd.xml
Fixes crash in release mode due to SQLite library
Fixes google drive not detected
Fixes exception notification appearing empty
=> Added missing references to rd.xml

Files/MultilingualResources/Files.de-DE.xlf, Files/MultilingualResources/Files.es-ES.xlf, Files/MultilingualResources/Files.fr-FR.xlf, Files/MultilingualResources/Files.he-IL.xlf, Files/MultilingualResources/Files.hi-IN.xlf, Files/MultilingualResources/Files.hu-HU.xlf, Files/MultilingualResources/Files.it-IT.xlf, Files/MultilingualResources/Files.ja-JP.xlf, Files/MultilingualResources/Files.nl-NL.xlf, Files/MultilingualResources/Files.or-IN.xlf, Files/MultilingualResources/Files.pl-PL.xlf, Files/MultilingualResources/Files.pt-BR.xlf, Files/MultilingualResources/Files.ru-RU.xlf, Files/MultilingualResources/Files.ta.xlf, Files/MultilingualResources/Files.tr-TR.xlf, Files/MultilingualResources/Files.uk-UA.xlf, Files/MultilingualResources/Files.zh-Hans.xlf, Files/MultilingualResources/Files.zh-Hant.xlf, Files/Strings/en-US/Resources.resw, Files/Strings/es-ES/Resources.resw, Files/UserControls/StatusBarControl.xaml, Files/UserControls/StatusCenter.xaml
Closes #2765 
-------------------------
The **x:Uid** is "**StatusCenterFlyoutTitle**", is this ok?
=> Add strings for "Ongoing Tasks"

Files/Views/Pages/Properties.xaml.cs
=> Fixed an issue where the properties window didn't support rtl languages

Files/Strings/en-US/Resources.resw
This PR makes the names for properties clearer.
=> Fixed text for some property names

Files/App.xaml.cs, Files/BaseLayout.cs, Files/IShellPage.cs, Files/UserControls/NavigationToolbar.xaml, Files/UserControls/NavigationToolbar.xaml.cs, Files/ViewModels/CurrentInstanceViewModel.cs, Files/Views/LayoutModes/GenericFileBrowser.xaml, Files/Views/LayoutModes/GridViewBrowser.xaml, Files/Views/ModernShellPage.xaml, Files/Views/ModernShellPage.xaml.cs
=> Fixes an issue where the paste menu option didn't always enable

Files.Launcher/QuickLook.cs, Files/ViewModels/SettingsViewModel.cs
Fixes [2759088390u](https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/2759088390u/overview)
=> Added exception handling for DetectQuickLook

Files/MultilingualResources/Files.de-DE.xlf, Files/MultilingualResources/Files.es-ES.xlf, Files/MultilingualResources/Files.fr-FR.xlf, Files/MultilingualResources/Files.he-IL.xlf, Files/MultilingualResources/Files.hi-IN.xlf, Files/MultilingualResources/Files.hu-HU.xlf, Files/MultilingualResources/Files.it-IT.xlf, Files/MultilingualResources/Files.ja-JP.xlf, Files/MultilingualResources/Files.nl-NL.xlf, Files/MultilingualResources/Files.or-IN.xlf, Files/MultilingualResources/Files.pl-PL.xlf, Files/MultilingualResources/Files.pt-BR.xlf, Files/MultilingualResources/Files.ru-RU.xlf, Files/MultilingualResources/Files.ta.xlf, Files/MultilingualResources/Files.tr-TR.xlf, Files/MultilingualResources/Files.uk-UA.xlf, Files/MultilingualResources/Files.zh-Hans.xlf, Files/MultilingualResources/Files.zh-Hant.xlf, Files/Strings/en-US/Resources.resw, Files/UserControls/Widgets/LibraryCards.xaml, Files/UserControls/Widgets/LibraryCards.xaml.cs, Files/Views/YourHome.xaml
=> Added desktop card to folders widget

Files/MultilingualResources/Files.de-DE.xlf, Files/MultilingualResources/Files.es-ES.xlf, Files/MultilingualResources/Files.fr-FR.xlf, Files/MultilingualResources/Files.he-IL.xlf, Files/MultilingualResources/Files.hi-IN.xlf, Files/MultilingualResources/Files.hu-HU.xlf, Files/MultilingualResources/Files.it-IT.xlf, Files/MultilingualResources/Files.ja-JP.xlf, Files/MultilingualResources/Files.nl-NL.xlf, Files/MultilingualResources/Files.or-IN.xlf, Files/MultilingualResources/Files.pl-PL.xlf, Files/MultilingualResources/Files.pt-BR.xlf, Files/MultilingualResources/Files.ru-RU.xlf, Files/MultilingualResources/Files.ta.xlf, Files/MultilingualResources/Files.tr-TR.xlf, Files/MultilingualResources/Files.uk-UA.xlf, Files/MultilingualResources/Files.zh-Hans.xlf, Files/MultilingualResources/Files.zh-Hant.xlf, Files/Strings/en-US/Resources.resw, Files/Strings/zh-Hans/Resources.resw, Files/ViewModels/SettingsViewModel.cs, Files/ViewModels/SettingsViewModels/AppearanceViewModel.cs, Files/Views/LayoutModes/GenericFileBrowser.xaml, Files/Views/LayoutModes/GridViewBrowser.xaml, Files/Views/SettingsPages/Appearance.xaml
=> Added a setting to disable the right click context menu animations

Files.Package/Package.appxmanifest, Files/ViewModels/SettingsViewModel.cs
Added analytics for the new AreRightClickContentMenuAnimationsEnabled setting
=> Added analytics for new setting

Files/Files.csproj, Files/MultilingualResources/Files.cs-CZ.xlf, Files/Strings/cs-CZ/Resources.resw
Sorry for duplicate request.
I have translated Files app to czech language. Added czech resources file and Files.cs-CZ.xfl to project.
=> Translated Files to czech

Files/Filesystem/FilesystemOperations/FilesystemOperations.cs
Fixes #2828
@d2dyno1 would this be enough to fix #2828?
=> Return null on failed copy

Files/MultilingualResources/Files.he-IL.xlf
A sample bunch. 
This job is much worse than I thought 😆
=> Add a bunch of translations to Hebrew

Files/BaseLayout.cs
=> Added the option to run cmd files as admin

Files/MultilingualResources/Files.ja-JP.xlf, Files/Strings/ja-JP/Resources.resw
This PR adds and fixes Japanese (ja-JP) translations.
=> Fix and add translations (ja-JP)

Files/BaseLayout.cs, Files/Filesystem/ListedItem.cs, Files/Interacts/Interaction.cs, Files/Strings/en-US/Resources.resw, Files/ViewModels/ItemViewModel.cs, Files/Views/LayoutModes/GenericFileBrowser.xaml, Files/Views/LayoutModes/GridViewBrowser.xaml
=> Added the option to the context menu to unpin an item from the sidebar when right clicking on a folder

Files/MultilingualResources/Files.cs-CZ.xlf, Files/MultilingualResources/Files.de-DE.xlf, Files/MultilingualResources/Files.es-ES.xlf, Files/MultilingualResources/Files.fr-FR.xlf, Files/MultilingualResources/Files.he-IL.xlf, Files/MultilingualResources/Files.hi-IN.xlf, Files/MultilingualResources/Files.hu-HU.xlf, Files/MultilingualResources/Files.it-IT.xlf, Files/MultilingualResources/Files.ja-JP.xlf, Files/MultilingualResources/Files.nl-NL.xlf, Files/MultilingualResources/Files.or-IN.xlf, Files/MultilingualResources/Files.pl-PL.xlf, Files/MultilingualResources/Files.pt-BR.xlf, Files/MultilingualResources/Files.ru-RU.xlf, Files/MultilingualResources/Files.ta.xlf, Files/MultilingualResources/Files.tr-TR.xlf, Files/MultilingualResources/Files.uk-UA.xlf, Files/MultilingualResources/Files.zh-Hans.xlf, Files/MultilingualResources/Files.zh-Hant.xlf, Files/Strings/en-US/Resources.resw, Files/UserControls/StatusBarControl.xaml
=> Fix Uid for Details y Tiles view buttons

Files/Views/LayoutModes/GenericFileBrowser.xaml.cs, Files/Views/LayoutModes/GridViewBrowser.xaml.cs, Files/Views/ModernShellPage.xaml.cs
=> Fixes an issue for which navigating to the settings page requires pressing the back button multiple times

Files/Dialogs/RestartDialog.xaml.cs
=> Fixed an issue where the app would crash on restart after changing the language

Files/UserControls/StatusBarControl.xaml.cs, Files/Views/ModernShellPage.xaml.cs
=> Fixes an issue for which status bar didn't update after switching layout

Files/Helpers/NativeWinApiHelper.cs, Files/Helpers/NaturalStringComparer.cs, Files/ViewModels/ItemViewModel.cs
Fixes #2724
Note: I can't promise this actually solves the issue as I don't have an ARM device.
=> Fix crash when enumerating folder contents on certain devices

Files/MultilingualResources/Files.pl-PL.xlf
I translated new strings and corrected the current ones slightly.
=> Update Polish Translation 

FAQ.md, README.md
- Changed some of the wording
- Linked to our new documentation website
=> Updated README.md

Files/Views/ModernShellPage.xaml.cs
=> Fixed a crash that would occur when entering empty path

Files/MultilingualResources/Files.fr-FR.xlf, Files/ResourceDictionaries/ToolbarButtonStyle.xaml, Files/Strings/fr-FR/Resources.resw, Files/UserControls/NavigationToolbar.xaml, Files/UserControls/StatusBarControl.xaml
- Fixed the font size and padding for items on the navigation toolbar
- Hid redundant "up" navigation button
=> Fixed padding around toolbar buttons on the nav bar and status bar

Files/ViewModels/ItemViewModel.cs, Files/Views/ModernShellPage.xaml.cs
=> Fix for files sorting before folders when using descending sorts.

Files/MultilingualResources/Files.tr-TR.xlf
Some sentences and words have been translated into Turkish.
=> Updated(güncellendi) - Files.tr-TR.xlf

Files/Enums/CloudProviders.cs, Files/Files.csproj, Files/Filesystem/Cloud/CloudProviderController.cs, Files/Filesystem/Cloud/Providers/AmazonDriveProvider.cs
=> Added support for Amazon Drive

Files/Filesystem/FilesystemOperations/FilesystemOperations.cs
=> Handle rename correctly when only case changes

Files/Filesystem/Cloud/Providers/DropBoxCloudProvider.cs
=> Added support for DropBox business accounts

Files/Views/SettingsPages/Appearance.xaml
Updated the link for the date format documentation.
=> Updated link to documentation

Files.Package/Files.Package.wapproj, Files/Files.csproj, Files/MultilingualResources/Files.ar.xlf, Files/Strings/ar/Resources.resw
=> Added Arabic translation

Files/Filesystem/Cloud/Providers/BoxCloudProvider.cs
Fixes #3100
Adds support for box sync in addition to box drive
=> Added support for Box Sync

Files/MultilingualResources/Files.fr-FR.xlf, Files/Strings/fr-FR/Resources.resw
=> Fix french translation

Files/Interacts/Interaction.cs
=> Fixes issue for which folder shortcuts open in explorer

Files/MultilingualResources/Files.es-ES.xlf, Files/Strings/es-ES/Resources.resw
Fixes #3254 
**Before:**
**After:**
=> Fix item size symbols showing in Arabic instead of Spanish

Files/Views/MainPage.xaml.cs
Implemented checks for all the drive types and assigned the relevant icons to them. Closes #3195
=> Tab header icon: Implemented checks for all drive types.

Files/MultilingualResources/Files.ar.xlf, Files/MultilingualResources/Files.cs-CZ.xlf, Files/MultilingualResources/Files.da-DK.xlf, Files/MultilingualResources/Files.da.xlf, Files/MultilingualResources/Files.de-DE.xlf, Files/MultilingualResources/Files.es-ES.xlf, Files/MultilingualResources/Files.fr-FR.xlf, Files/MultilingualResources/Files.he-IL.xlf, Files/MultilingualResources/Files.hi-IN.xlf, Files/MultilingualResources/Files.hu-HU.xlf, Files/MultilingualResources/Files.it-IT.xlf, Files/MultilingualResources/Files.ja-JP.xlf, Files/MultilingualResources/Files.nl-NL.xlf, Files/MultilingualResources/Files.or-IN.xlf, Files/MultilingualResources/Files.pl-PL.xlf, Files/MultilingualResources/Files.pt-BR.xlf, Files/MultilingualResources/Files.ru-RU.xlf, Files/MultilingualResources/Files.ta.xlf, Files/MultilingualResources/Files.tr-TR.xlf, Files/MultilingualResources/Files.uk-UA.xlf, Files/MultilingualResources/Files.zh-Hans.xlf, Files/MultilingualResources/Files.zh-Hant.xlf, Files/Strings/en-US/Resources.resw, Files/Strings/es-ES/Resources.resw, Files/Strings/it-IT/Resources.resw, Files/Strings/zh-Hans/Resources.resw, Files/Views/SettingsPages/Preferences.xaml
- New strings translated into Spanish
- Fixed string id for "Enable adaptive preview pane"
- ### Before: 
**String resources:** `SettingsEnableAdaptivePreviewPane`
**Preferences.xaml:** `SettingsFilesAndFoldersEnableAdaptivePreviewPane`
- ### After: 
`SettingsPreferencesEnableAdaptivePreviewPane`
=> Translation update [es-ES] + Fix

Files.Package/Files.Package.wapproj, Files/Files.csproj, Files/MultilingualResources/Files.ko-KR.xlf, Files/Strings/ko-KR/Resources.resw
1. Update Korean translation
2. The existing Korean translation was not added to the proj file. So I added it this time.
=> Update Korean Translation

Files/MultilingualResources/Files.fr-FR.xlf
File [Files/MultilingualResources/**Files.fr-FR.xlf**](https://github.com/files-community/Files/blob/main/Files/MultilingualResources/Files.fr-FR.xlf) have been edited by #3362 
I just translated the strings
=> Update French translation

Files.FulltrustCpp/FulltrustCpp.vcxproj, Files.FulltrustCpp/FulltrustCpp.vcxproj.filters, Files.FulltrustCpp/MsgHandler_BitLocker.cpp, Files.FulltrustCpp/MsgHandler_BitLocker.h, Files/ViewModels/ItemViewModel.cs
This is PR adds powershell BitLocker module to cpp_fulltrust.
=> Added BitLocker module to cpp_fulltrust

Files/MultilingualResources/Files.hu-HU.xlf, Files/Strings/hu-HU/Resources.resw
Fixes and additions to Hungarian translation.
~~*General review in progress, I'll mark this PR ready for review as soon as this is done.*~~
=> Update Hungarian translation

Files/BaseLayout.cs, Files/Controllers/SidebarPinnedController.cs, Files/DataModels/SidebarPinnedModel.cs, Files/Filesystem/Cloud/Providers/OneDriveCloudProvider.cs, Files/Filesystem/FilesystemOperations/FilesystemOperations.cs, Files/Filesystem/FilesystemOperations/Helpers/FilesystemHelpers.cs, Files/Helpers/AppServiceConnectionHelper.cs, Files/Helpers/AppUpdater.cs, Files/Helpers/FileListCache/PersistentSQLiteCacheAdapter.cs, Files/Helpers/JumpListManager.cs, Files/Helpers/PathNormalization.cs, Files/Interacts/Interaction.cs, Files/UserControls/NavigationToolbar.xaml.cs, Files/UserControls/Selection/RectangleSelection_DataGrid.cs, Files/UserControls/SidebarControl.xaml.cs, Files/ViewModels/ItemViewModel.cs, Files/Views/LayoutModes/GenericFileBrowser.xaml.cs, Files/Views/ModernShellPage.xaml.cs
Fixes #3430
The return of #3278. Fixes a few common issues reported on AppCenter.
=> Appcenter fixes 3

Files.Launcher/Program.cs
=> Properly sort shortcut items in Recycle Bin

Files/Interacts/Interaction.cs
=> Fixed a crash that would occur when opening a shortcut files location

Files/Views/ModernShellPage.xaml.cs
=> Fixed Ctrl+L on HomePage

Files/Filesystem/LocationItem.cs
=> Fixed tooltip for the Home and Recycle Bin sidebar items

Files/Views/ModernShellPage.xaml.cs
=> Ignore `Shift` + `Delete` shortcut if no items are selected

Files/Views/ModernShellPage.xaml.cs
=> Fixes back/forward mouse buttons in dual pane mode

Files/BaseLayout.cs, Files/UserControls/NavigationToolbar.xaml.cs, Files/UserControls/SidebarControl.xaml.cs
=> Fixes an issue for which folder changes after dropping an item

Files/BaseLayout.cs, Files/ViewModels/ItemViewModel.cs, Files/Views/LayoutModes/GenericFileBrowser.xaml, Files/Views/LayoutModes/GenericFileBrowser.xaml.cs, Files/Views/LayoutModes/GridViewBrowser.xaml, Files/Views/LayoutModes/GridViewBrowser.xaml.cs
Fixes #3447
Reverts part of #2669 to solve #3447.
=> Enable cache mode for LayoutModes

Files/Views/LayoutModes/GenericFileBrowser.xaml.cs
=> Fixed a cash when opening a folder in ListView

Files.Package/Files.Package.wapproj, Files/Files.csproj, Files/MultilingualResources/Files.sv-SE.xlf, Files/Strings/sv-SE/Resources.resw
Adds a new Swedish localization for all strings present at the time of translating.
=> Add Swedish localization

Files/MultilingualResources/Files.es-ES.xlf, Files/Strings/es-ES/Resources.resw, Files/Views/SettingsPages/Experimental.xaml
- New strings translated into Spanish
- Fixed Uid for: _Preemptive cache parallel limit (smaller numbers should work better for hard drives)_
---------------
_Builded without problems_
=> Translation Update [es-ES]

Files.Launcher/Program.cs, Files/Filesystem/Cloud/Providers/OneDriveCloudProvider.cs, Files/Filesystem/Cloud/Providers/OneDriveSharePointCloudProvider.cs, Files/Filesystem/FilesystemOperations/FilesystemOperations.cs, Files/Filesystem/NetworkDrivesManager.cs, Files/ViewModels/ItemViewModel.cs, Files/ViewModels/Properties/FileProperties.cs, Files/ViewModels/Properties/FolderProperties.cs, Files/Views/LayoutModes/GenericFileBrowser.xaml.cs, Files/Views/LayoutModes/GridViewBrowser.xaml.cs, Files/Views/ModernShellPage.xaml.cs, Files/Views/Pages/PropertiesGeneral.xaml.cs
Fixes an issue when renaming files with "open items with one click" enabled (fixes #3660)
Fixes an issue for which recyclebin is not working after #3564
Fixes an issue for which cloud drives appears only after 10s at startup (fixes #3664)
=> Fixes for version 1.3 (2)

Files/ViewModels/Bundles/BundleContainerViewModel.cs, Files/ViewModels/Bundles/BundlesViewModel.cs
=> Auto focus text box for Bundles widget

Files/MultilingualResources/Files.ja-JP.xlf
"Preemptive cache parallel limit" is difficult for me, but it means "amount of files to pre-cached," isn't it?
=> Update Japanese translation

Common/Extensions.cs, Files/BaseLayout.cs, Files/Filesystem/Drives.cs, Files/Filesystem/FilesystemOperations/FilesystemOperations.cs, Files/Filesystem/StorageEnumerators/Win32StorageEnumerator.cs, Files/Helpers/AppServiceConnectionHelper.cs, Files/Helpers/RecycleBinHelpers.cs, Files/Interacts/Interaction.cs, Files/UserControls/StatusCenter.xaml.cs, Files/UserControls/Widgets/DrivesWidget.xaml.cs, Files/ViewModels/ItemViewModel.cs, Files/ViewModels/Properties/FileProperties.cs, Files/ViewModels/Properties/FolderProperties.cs, Files/Views/ModernShellPage.xaml.cs, Files/Views/Pages/PropertiesGeneral.xaml.cs
Fixes a crash that occurs when filesystem permission is not given (#843677668u)
Fix object disposed exception on right click (#4233215062u, fixes #3680)
=> Fixes per version 1.3 (3)

README.md
=> Update Vision for Files

Files/ViewModels/FolderSettingsViewModel.cs
=> Fix crash when navigating to a path > 256 chars long

Files/Views/ModernShellPage.xaml.cs
Fix a crash when navigating back to homepage (after #3661)
=> Fix navigating back to home

Files/IShellPage.cs, Files/UserControls/MultitaskingControl/HorizontalMultitaskingControl.xaml, Files/Views/ModernShellPage.xaml, Files/Views/ModernShellPage.xaml.cs, Files/Views/PaneHolderPage.xaml, Files/Views/PaneHolderPage.xaml.cs
Also sidebar is now working for both panes.
=> Move TabStrib to PaneHolderPage and decouple Sidebar from IShellPage

Files/MultilingualResources/Files.ar.xlf, Files/MultilingualResources/Files.cs-CZ.xlf, Files/MultilingualResources/Files.da-DK.xlf, Files/MultilingualResources/Files.da.xlf, Files/MultilingualResources/Files.de-DE.xlf, Files/MultilingualResources/Files.es-ES.xlf, Files/MultilingualResources/Files.fr-FR.xlf, Files/MultilingualResources/Files.he-IL.xlf, Files/MultilingualResources/Files.hi-IN.xlf, Files/MultilingualResources/Files.hu-HU.xlf, Files/MultilingualResources/Files.it-IT.xlf, Files/MultilingualResources/Files.ja-JP.xlf, Files/MultilingualResources/Files.ko-KR.xlf, Files/MultilingualResources/Files.nl-NL.xlf, Files/MultilingualResources/Files.or-IN.xlf, Files/MultilingualResources/Files.pl-PL.xlf, Files/MultilingualResources/Files.pt-BR.xlf, Files/MultilingualResources/Files.ru-RU.xlf, Files/MultilingualResources/Files.sv-SE.xlf, Files/MultilingualResources/Files.ta.xlf, Files/MultilingualResources/Files.tr-TR.xlf, Files/MultilingualResources/Files.uk-UA.xlf, Files/MultilingualResources/Files.zh-Hans.xlf, Files/MultilingualResources/Files.zh-Hant.xlf, Files/UserControls/NavigationToolbar.xaml
This pull request continues to improve the nav bar design by updating the corner radius to match the new guidelines.
=> NavBar updates step 2

Files/Views/SettingsPages/OnStartup.xaml
=> Enable on startup pages reordering with drag

Files/Filesystem/ListedItem.cs, Files/Filesystem/StorageEnumerators/Win32StorageEnumerator.cs, Files/ViewModels/ItemViewModel.cs, Files/ViewModels/Properties/FileProperties.cs, Files/Views/LayoutModes/GenericFileBrowser.xaml, Files/Views/LayoutModes/GridViewBrowser.xaml
=> Show icons for url files

Files/ResourceDictionaries/ToolbarButtonStyle.xaml, Files/UserControls/NavigationToolbar.xaml, Files/UserControls/StatusBarControl.xaml, Files/Views/PaneHolderPage.xaml
- Removed extra shadow by nav bar
- Updated corner radius
- Moved over to command bar
=> Style tweaks to nav bar

Files.Launcher/Program.cs, Files.Launcher/Win32API.cs
=> Fix thumbnails sometimes not loaded

Files/Views/MainPage.xaml.cs
=> Fix Ctrl+N opening two windows

Files/Filesystem/ListedItem.cs
=> Fixed an issue where the date would sometimes display the wrong time zone

Files/MultilingualResources/Files.ja-JP.xlf
Updated Japanese Translation to more clear and natural.
=> Update Japanese Translation to more clear one

Files/UserControls/MultitaskingControl/HorizontalMultitaskingControl.xaml, Files/Views/ModernShellPage.xaml, Files/Views/ModernShellPage.xaml.cs, Files/Views/PaneHolderPage.xaml
=> Fixed tab margin

Files/Constants.cs, Files/Filesystem/FilesystemOperations/Helpers/FilesystemHelpers.cs, Files/Filesystem/Search/FolderSearch.cs, Files/UserControls/NavigationToolbar.xaml.cs, Files/ViewModels/FolderSettingsViewModel.cs, Files/ViewModels/SettingsViewModels/MultitaskingViewModel.cs, Files/Views/LayoutModes/GridViewBrowser.xaml.cs, Files/Views/ModernShellPage.xaml.cs, Files/Views/Pages/PropertiesGeneral.xaml.cs
Fixes #3802
This PR:
- Fixes a bug that caused issues when selecting a multitasking mode in settings (#3802)
- Adds some null checks to fix crashes seen on AppCenter
- Fixes an issue for which icons in search results were invisible
=> Fixes for 1.3.5

Files/Views/ModernShellPage.xaml, Files/Views/ModernShellPage.xaml.cs, Files/Views/PaneHolderPage.xaml
=> Fixed drop shadow on sidebar

Files/UserControls/StatusBarControl.xaml, Files/Views/ModernShellPage.xaml, Files/Views/ModernShellPage.xaml.cs, Files/Views/PaneHolderPage.xaml
=> Removed background from status bar control

Files/Filesystem/LibraryManager.cs, Files/Interacts/Interaction.cs, Files/UserControls/SidebarControl.xaml.cs
=> Restore saving pinned folders

Files/Strings/en-US/Resources.resw
=> Fixed typo

Files/Filesystem/LibraryManager.cs
Fix was overridden in #3881 ;)
=> Hide unpin from libraries

Files/ViewModels/PreviewPaneViewModel.cs, Files/ViewModels/Previews/FolderPreviewViewModel.cs
Closes #3978 
This fix should work fine, but shortcuts aren't working for me at all, so if someone could test this I would greatly appreciate it.
=> Fixed issue where previewing folder shortcut would cause a crash

Files/Assets/FolderIcon.svg, Files/Assets/FolderIcon2.svg, Files/Assets/FolderIcon2Large.svg, Files/Assets/FolderIconLarge.svg
Closes #3118
Any help to improve styling is welcome
--------------------
----------------------------
**Before:**
**After:**
=> Change the default folder icon

Files/Interacts/IStatusCenterActions.cs, Files/UserControls/StatusBarControl.xaml, Files/UserControls/StatusBarControl.xaml.cs, Files/UserControls/StatusCenter.xaml.cs
For #4082
Updates UI + fix ring forever spinning after delete
https://user-images.githubusercontent.com/9673091/111244027-65beed00-8602-11eb-80f5-f87f5d42abe2.mp4
=> Fix ongoing task progress ring

Files/App.xaml, Files/Dialogs/PropertiesDialog.xaml, Files/Files.csproj, Files/ResourceDictionaries/ToolbarButtonStyle.xaml, Files/UserControls/SidebarControl.xaml, Files/Views/Pages/Properties.xaml.cs
Reverts files-community/Files#4090
=> Revert "WinUI 2.6 Preview"

Files/App.xaml, Files/Dialogs/PropertiesDialog.xaml, Files/Files.csproj, Files/ResourceDictionaries/ToolbarButtonStyle.xaml, Files/UserControls/SidebarControl.xaml, Files/Views/Pages/Properties.xaml.cs
Reverts files-community/Files#4094
=> Revert "Revert "WinUI 2.6 Preview""

Files/UserControls/StatusCenter.xaml, Files/UserControls/Widgets/Bundles.xaml, Files/UserControls/Widgets/DrivesWidget.xaml, Files/UserControls/Widgets/LibraryCards.xaml
=> Fixed widgets background color

Files/Views/Pages/Properties.xaml
=> Added a background color to the properties dialog

Files/UserControls/Widgets/RecentFiles.xaml
=> Updated recent files widget UI

Files/Files.csproj, Files/MultilingualResources/Files.ja-JP.xlf, Files/MultilingualResources/Files.lv-LV.xlf, Files/MultilingualResources/Files.pt-PT.xlf, Files/Strings/ja-JP/Resources.resw, Files/Strings/tr-TR/Resources.resw, Files/UserControls/RestartControl.xaml, Files/UserControls/RestartControl.xaml.cs, Files/ViewModels/SettingsViewModels/AppearanceViewModel.cs, Files/ViewModels/SettingsViewModels/PreferencesViewModel.cs, Files/Views/SettingsPages/Appearance.xaml, Files/Views/SettingsPages/Preferences.xaml
- Updated the namespace
- Added a background color and border
=> Improved the restart control

Files/Views/LayoutModes/GenericFileBrowser.xaml.cs
=> Fix item renaming

Files/ViewModels/FolderSettingsViewModel.cs, Files/Views/ModernShellPage.xaml
Fixes #4104
Fixes an issue for which the folder contents where sometime invisible.
Fixes an issue for which the navigation bar did not reflect the current layout mode.
**Validation**
=> Fix folder contents not shown & selected layout mode not updated

Files/MultilingualResources/Files.ar.xlf, Files/MultilingualResources/Files.cs-CZ.xlf, Files/MultilingualResources/Files.da-DK.xlf, Files/MultilingualResources/Files.da.xlf, Files/MultilingualResources/Files.de-DE.xlf, Files/MultilingualResources/Files.es-ES.xlf, Files/MultilingualResources/Files.fr-FR.xlf, Files/MultilingualResources/Files.he-IL.xlf, Files/MultilingualResources/Files.hi-IN.xlf, Files/MultilingualResources/Files.hu-HU.xlf, Files/MultilingualResources/Files.it-IT.xlf, Files/MultilingualResources/Files.ja-JP.xlf, Files/MultilingualResources/Files.ko-KR.xlf, Files/MultilingualResources/Files.lv-LV.xlf, Files/MultilingualResources/Files.nl-NL.xlf, Files/MultilingualResources/Files.or-IN.xlf, Files/MultilingualResources/Files.pl-PL.xlf, Files/MultilingualResources/Files.pt-PT.xlf, Files/MultilingualResources/Files.ru-RU.xlf, Files/MultilingualResources/Files.sv-SE.xlf, Files/MultilingualResources/Files.ta.xlf, Files/MultilingualResources/Files.tr-TR.xlf, Files/MultilingualResources/Files.uk-UA.xlf, Files/MultilingualResources/Files.zh-Hans.xlf, Files/MultilingualResources/Files.zh-Hant.xlf, Files/UserControls/Widgets/DrivesWidget.xaml, Files/UserControls/Widgets/LibraryCards.xaml
- Added back the brushes for the widgets, this is a temporary change until WinUI 2.6 is out of preview.
**Validation**
=> Added back brushes for widgets

Files/Views/ModernShellPage.xaml
Fixes a tiny bit of #4211
Changed binding from one time to two way.
**Validation**
=> Fixed issue where multi select option wouldn't work

Files/Views/ModernShellPage.xaml, Files/Views/ModernShellPage.xaml.cs
- Closes #4211
Fixes selection commands binding. Can you confirm that everything is working correctly after this change? @winston-de
**Validation**
=> Fix selection options

Files/Helpers/ExternalResourcesHelper.cs
Fixes 
https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/3820898840u/overview
https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/3038526161u/overview
Use the ```CreationCollisionOption.OpenIfExists``` option instead of using ```TryGetItem``` to check if it already exists.
**Validation**
=> Improve theme folder loading code and fix crash

Files/MultilingualResources/Files.ko-KR.xlf, Files/Strings/ko-KR/Resources.resw
N/A
- Update Korean translation
**Validation**
=> Update ko-KR translation

Files/MultilingualResources/Files.da-DK.xlf
- Translated all new strings
- Reviewed remaining strings with review status
=> Update da-DK translation

Files/BaseLayout.cs, Files/Helpers/ContextFlyoutItemHelper.cs, Files/Helpers/ItemModelListToContextFlyoutHelper.cs, Files/ViewModels/ContextMenuFlyoutItemViewModel.cs
Closes #2342
Replaced the menu flyout with a command bar flyout, and added the necessary helpers to convert menu items to app bar elements.
**Validation**
=> Replaced item context menu with command bar flyout

Files/Helpers/ItemModelListToContextFlyoutHelper.cs
- Closes #4412
- Resolves bug where item separator could be shown even if there were no items below it
- Added tooltips to primary items
- Remove separator if it's at the end of the list
**Validation**
=> Command bar flyout improvements

Files/Interacts/BaseLayoutCommandImplementationModel.cs, Files/Interacts/BaseLayoutCommandsViewModel.cs
- Related #4421
- The share flyout is now using the app theme instead of the system theme
=> Use app theme for share flyout

Files/DataModels/SidebarPinnedModel.cs, Files/Filesystem/LibraryLocationItem.cs, Files/Filesystem/LocationItem.cs, Files/UserControls/SidebarControl.xaml
- The missing icons will be added in another PR
- There is currently an issue where the icon size is a little too small, this can be solved in another PR
=> Added colored icons to the library and favorites section on the sidebar

Files.Launcher/NLog.config, Files/NLog.config
- Changed log output file extension to .log
**Validation**
=> Make log files easier to identify #1550

Files/Resources/PreviewPanePropertiesInformation.json, Files/UserControls/PreviewPane.xaml
#4396 
Updated design, as discussed.
**Validation**
=> Improve preview pane design

Files/Views/LayoutModes/ColumnViewBase.xaml, Files/Views/LayoutModes/ColumnViewBrowser.xaml
Part of #290
This adds a binding on the selection mode property to the multiselect enabled property (with the converter).
**Validation**
https://user-images.githubusercontent.com/59544401/113213830-85bef500-922d-11eb-9646-82979f2f447f.mp4
=> Implemented multiselect in column view

Files/App.xaml.cs, Files/DataModels/SidebarPinnedModel.cs, Files/Filesystem/CloudDrivesManager.cs, Files/Filesystem/DriveItem.cs, Files/Filesystem/Drives.cs, Files/Filesystem/INavigationControlItem.cs, Files/Filesystem/LibraryLocationItem.cs, Files/Filesystem/LibraryManager.cs, Files/Filesystem/ListedItem.cs, Files/Filesystem/LocationItem.cs, Files/Filesystem/NetworkDrivesManager.cs, Files/Filesystem/WSLDistroManager.cs, Files/UserControls/FileIcon.xaml, Files/UserControls/SidebarControl.xaml, Files/UserControls/Widgets/DrivesWidget.xaml, Files/ViewModels/MainPageViewModel.cs, Files/ViewModels/Properties/DriveProperties.cs, Files/ViewModels/Properties/FileProperties.cs, Files/ViewModels/Properties/LibraryProperties.cs, Files/ViewModels/SelectedItemsPropertiesViewModel.cs
- For #4405, #4429
This PR implements some of the drive icons.
**Validation**
=> Added fluent icons for drives

Files/Views/LayoutModes/ColumnViewBase.xaml, Files/Views/LayoutModes/ColumnViewBase.xaml.cs, Files/Views/LayoutModes/ColumnViewBrowser.xaml, Files/Views/LayoutModes/ColumnViewBrowser.xaml.cs
- Related #4397 
- Fixed issue where unfocused listview item color wouldnt change
**Validation**
but no chevron
=> Column View Improvements #2

Files/MultilingualResources/Files.ar.xlf, Files/MultilingualResources/Files.cs-CZ.xlf, Files/MultilingualResources/Files.da-DK.xlf, Files/MultilingualResources/Files.da.xlf, Files/MultilingualResources/Files.de-DE.xlf, Files/MultilingualResources/Files.es-ES.xlf, Files/MultilingualResources/Files.fr-FR.xlf, Files/MultilingualResources/Files.he-IL.xlf, Files/MultilingualResources/Files.hi-IN.xlf, Files/MultilingualResources/Files.hu-HU.xlf, Files/MultilingualResources/Files.it-IT.xlf, Files/MultilingualResources/Files.ja-JP.xlf, Files/MultilingualResources/Files.ko-KR.xlf, Files/MultilingualResources/Files.lv-LV.xlf, Files/MultilingualResources/Files.nl-NL.xlf, Files/MultilingualResources/Files.or-IN.xlf, Files/MultilingualResources/Files.pl-PL.xlf, Files/MultilingualResources/Files.pt-BR.xlf, Files/MultilingualResources/Files.pt-PT.xlf, Files/MultilingualResources/Files.ru-RU.xlf, Files/MultilingualResources/Files.sv-SE.xlf, Files/MultilingualResources/Files.ta.xlf, Files/MultilingualResources/Files.tr-TR.xlf, Files/MultilingualResources/Files.uk-UA.xlf, Files/MultilingualResources/Files.zh-Hans.xlf, Files/MultilingualResources/Files.zh-Hant.xlf, Files/Strings/en-US/Resources.resw, Files/UserControls/NavigationToolbar.xaml
- Switched menu items for toggle switches
- Added a header to the flyout
- Fixed the strings
=> Improved widget flyout

Files/MultilingualResources/Files.fr-FR.xlf
Translated some texts into French.
=> Translated some texts into French. 

Files/Helpers/ContextFlyoutItemHelper.cs
Added create new file item (no type).
**Validation**
=> Added create new file item (no extension)

Files/Strings/en-US/Resources.resw
This fixes an issue where the restart dialog would say "language" when changing themes.
Before:
> The application needs to be restarted in order to apply the language setting, would you like to restart the app?
After:
> The application needs to be restarted in order to apply these settings, would you like to restart the app?
**Validation**
=> Update text for restart control

Files/App.xaml.cs, Files/Constants.cs, Files/Files.csproj, Files/Helpers/ExternalResourcesHelper.cs, Files/Helpers/OptionalPackageManager.cs, Files/Properties/Default.rd.xml, Files/ViewModels/SettingsViewModel.cs, Files/ViewModels/SettingsViewModels/AppearanceViewModel.cs, Files/Views/SettingsPages/Appearance.xaml
N/A
This PR allows for themes to be installed through an optional package. 
This goes with https://github.com/files-community/Custom-themes/pull/10.
**Validation**
=> Added support for themes through an optional package

Files/MultilingualResources/Files.ar.xlf, Files/MultilingualResources/Files.cs-CZ.xlf, Files/MultilingualResources/Files.da-DK.xlf, Files/MultilingualResources/Files.da.xlf, Files/MultilingualResources/Files.de-DE.xlf, Files/MultilingualResources/Files.es-ES.xlf, Files/MultilingualResources/Files.fr-FR.xlf, Files/MultilingualResources/Files.he-IL.xlf, Files/MultilingualResources/Files.hi-IN.xlf, Files/MultilingualResources/Files.hu-HU.xlf, Files/MultilingualResources/Files.it-IT.xlf, Files/MultilingualResources/Files.ja-JP.xlf, Files/MultilingualResources/Files.ko-KR.xlf, Files/MultilingualResources/Files.lv-LV.xlf, Files/MultilingualResources/Files.nl-NL.xlf, Files/MultilingualResources/Files.or-IN.xlf, Files/MultilingualResources/Files.pl-PL.xlf, Files/MultilingualResources/Files.pt-BR.xlf, Files/MultilingualResources/Files.pt-PT.xlf, Files/MultilingualResources/Files.ru-RU.xlf, Files/MultilingualResources/Files.sv-SE.xlf, Files/MultilingualResources/Files.ta.xlf, Files/MultilingualResources/Files.tr-TR.xlf, Files/MultilingualResources/Files.uk-UA.xlf, Files/MultilingualResources/Files.zh-Hans.xlf, Files/MultilingualResources/Files.zh-Hant.xlf
Update the state of texts to prepare translations and avoid polluting visual studio with automatically modified files.
=> update text state

Files/Constants.cs
The optional package name constant didn't match the new name, which prevented it from working.
Changed optional package name constant.
**Validation**
=> Fixed optional package name

Files/ViewModels/FolderSettingsViewModel.cs
https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/2353571889u/overview
- Added try-catch around deserializer
**Validation**
=> Fix crash that could occur when deserializing layout mode data from file

Files/Views/LayoutModes/GenericFileBrowser2.xaml, Files/Views/LayoutModes/GenericFileBrowser2.xaml.cs
- Sticky column headers
- Use debounce timer for double click to rename (still is janky though)
- Fix thumbnails not loading
- Vertically center the text blocks
- Fix resizing jank 
**Validation**
=> New details view improvements

Files/MultilingualResources/Files.fr-FR.xlf
Update fr_FR: new translations, more consistency, some minor fixes
=> Big update fr_FR

Files/App.xaml.cs
- Closes #3801 (not exactly it but it does the job)
Tabs are now more reliably saved by Continue where you left off. Now tabs are recovered even after a crash! 
**Validation**
=> More reliable Continue where you left off

Files/App.xaml
This PR fixes a bad merge, that snuck in in #4606 . Sorry about this.
=> Fix bad merge

Files/UserControls/SidebarControl.xaml.cs
=> Fix issue where properties and unpin was missing for pinned items

Files/MultilingualResources/Files.ar.xlf, Files/MultilingualResources/Files.cs-CZ.xlf, Files/MultilingualResources/Files.da-DK.xlf, Files/MultilingualResources/Files.da.xlf, Files/MultilingualResources/Files.de-DE.xlf, Files/MultilingualResources/Files.es-ES.xlf, Files/MultilingualResources/Files.fr-FR.xlf, Files/MultilingualResources/Files.he-IL.xlf, Files/MultilingualResources/Files.hi-IN.xlf, Files/MultilingualResources/Files.hu-HU.xlf, Files/MultilingualResources/Files.it-IT.xlf, Files/MultilingualResources/Files.ja-JP.xlf, Files/MultilingualResources/Files.ko-KR.xlf, Files/MultilingualResources/Files.lv-LV.xlf, Files/MultilingualResources/Files.nl-NL.xlf, Files/MultilingualResources/Files.or-IN.xlf, Files/MultilingualResources/Files.pl-PL.xlf, Files/MultilingualResources/Files.pt-BR.xlf, Files/MultilingualResources/Files.pt-PT.xlf, Files/MultilingualResources/Files.ru-RU.xlf, Files/MultilingualResources/Files.sv-SE.xlf, Files/MultilingualResources/Files.ta.xlf, Files/MultilingualResources/Files.tr-TR.xlf, Files/MultilingualResources/Files.uk-UA.xlf, Files/MultilingualResources/Files.zh-Hans.xlf, Files/MultilingualResources/Files.zh-Hant.xlf
Update all .xlf with new texts. This prevents these files from being changed automatically in Visual Studio.
=> Update all .xlf with new texts

Files/MultilingualResources/Files.fr-FR.xlf
=> New texts in french

Files/Filesystem/ListedItem.cs, Files/ViewModels/ColumnsViewModel.cs, Files/ViewModels/ItemViewModel.cs, Files/Views/LayoutModes/GenericFileBrowser2.xaml, Files/Views/LayoutModes/GenericFileBrowser2.xaml.cs
- Related #4643 
- Collapse status column outside of cloud drive folders
- Added recycle bin headers that collapse outside of the recycle bin
**Validation**
=> New details layout: recycle bin headers and collapse status column when not in cloud drive

Files/Views/ModernShellPage.xaml.cs
- Closes #4668
Fixed a small oversight with #4354. @winston-de 
**Validation**
=> Fix crash when collapsing sidebar item section

Files/Filesystem/FilesystemOperations/FilesystemOperations.cs, Files/Filesystem/FilesystemOperations/Helpers/FilesystemHelpers.cs, Files/Filesystem/FilesystemOperations/Helpers/IFilesystemHelpers.cs, Files/Filesystem/FilesystemOperations/IFilesystemOperations.cs, Files/Helpers/ContextFlyoutItemHelper.cs, Files/Helpers/UIFilesystemHelpers.cs, Files/Interacts/BaseLayoutCommandImplementationModel.cs, Files/Interacts/BaseLayoutCommandsViewModel.cs, Files/Interacts/IBaseLayoutCommandImplementationModel.cs, Files/Strings/en-US/Resources.resw
- Closes #283
- Added command and context menu item to create folder with selection
- Added storage item return to create item functions
**Validation**
https://user-images.githubusercontent.com/59544401/115191747-b660b480-a09e-11eb-8705-58f3f76cd09b.mp4
=> Added ability to create folder with current selection

Files/Views/LayoutModes/GenericFileBrowser2.xaml
- Fixed the background color of the header
- Fixed the transparent area above the header
=> Fixed header background and padding for the new details layout

Files/Strings/en-US/Resources.resw, Files/UserControls/NavigationToolbar.xaml, Files/ViewModels/SettingsViewModel.cs, Files/ViewModels/SettingsViewModels/ExperimentalViewModel.cs, Files/Views/SettingsPages/Experimental.xaml
- Closes #290 
- Removed option to enable multiselect from experiments page since it will soon be available for all layout modes
**Validation**
=> Remove multiselect from experiments, always enable

Files/MultilingualResources/Files.fr-FR.xlf
=> Translate new texts in french

Files/Strings/en-US/Resources.resw
The commit #4690 change id in files xlf. The fix change id in Resources.resw en-US.
Otherwise, in the compilation, the xlf files erase the translation to take the English text.
=> Fix commit #4690

Files/Views/Pages/Properties.xaml
- Closes #4226
- Added an acrylic background with an opacity of 0.90, based on the ```SystemControlAcrylicWindowBrush```
**Validation**
=> Updated properties dialog background design

Files/BaseLayout.cs, Files/MultilingualResources/Files.ja-JP.xlf, Files/Views/ModernShellPage.xaml.cs
- Closes #4132
Added navigation from root to homepage + fixed Japan translation
**Validation**
=> Added navigation from root to homepage

Files/BaseLayout.cs, Files/Filesystem/Search/FolderSearch.cs
- Closes #4515
- If the path is a library, add search results from each folder contained in the library
**Validation**
=> Added support for searching libraries

Files/Views/LayoutModes/GenericFileBrowser2.xaml, Files/Views/LayoutModes/GenericFileBrowser2.xaml.cs, Files/Views/ModernShellPage.xaml.cs
- Related #4643
- Implement text changed for name text box (which checks for invalid characters)
- Implement type-to-item feature
- Fix keyboard shortcuts not working
- Fix issue where column layout wouldn't be updated on resize
- Use thin grid splitter
- Fix content overflow
- Fix double click to rename
**Validation**
=> New details view fixes

Files/App.xaml.cs
Improves exception logging
**Validation**
=> Improve debug exception logging

Files/ViewModels/StatusCenterViewModel.cs
Fixes ArgumentOutOfRangeException in UpdateMedianProgress()
**Validation**
=> Fix ArgumentOutOfRangeException

Files/UserControls/NavigationToolbar.xaml, Files/UserControls/StatusBarControl.xaml, Files/Views/Pages/Properties.xaml, Files/Views/Settings.xaml
- Closes #4780
- Added access keys for common actions (Access keys aren't localized due to the complexity in reviewing translations to make sure there aren't any duplicate access keys.)
**Validation**
=> Added access keys

Files/Views/LayoutModes/GenericFileBrowser2.xaml
Adds missing AutomationProperties name to the xaml (the string was already localized)
=> Added AutomationProperties name to xaml file

Files.Launcher/Program.cs, Files.Launcher/Win32API_ContextMenu.cs
- Closes #4781
- Added "openinfiles" to known items list
**Validation**
Before:
After:
=> Hide the "open in files" shell context menu item

Files/Filesystem/ListedItem.cs, Files/ViewModels/ItemViewModel.cs, Files/Views/LayoutModes/GenericFileBrowser2.xaml, Files/Views/LayoutModes/GenericFileBrowser2.xaml.cs, Files/Views/ModernShellPage.xaml.cs
For #4643
In addition to the above I've removed the `ColumnsViewModel` property from ListedItem and used Binding+ElementName instead. I haven't found particular performance issues with this change and I personally prefer the code this way (actually I dislike both ways, I wish there was a better way to do this xD). Let me know what you think, reversing this would fine by me.
PS: @winston-de amazing work btw!
**Validation**
=> Small improvements for new details view 

Files/MultilingualResources/Files.de-DE.xlf, Files/Strings/de-DE/Resources.resw
- closes #4815 
- changed the wrong translation from #4815
- translated all "new" strings that had not been translated yet
- standardized some differing translations
**Validation**
=> enhanced german translation

Files/Filesystem/DriveItem.cs, Files/Filesystem/Drives.cs, Files/Filesystem/INavigationControlItem.cs, Files/MultilingualResources/Files.de-DE.xlf, Files/Strings/de-DE/Resources.resw
This changed behavior will fallback to getting the old icons when necessary.
**Validation**
=> Load DriveItem icons from filesystem

Files/Filesystem/LibraryManager.cs
- Fixes a crash in release introduced with #4819
**Validation**
=> Fix crash in release mode due to #4819

Files/MultilingualResources/Files.pt-PT.xlf
Proposal to update the Portuguese language due to new string introduced in the file.
=> Update pt-PT linguage

Files/App.xaml, Files/Helpers/AcrylicTheme.cs, Files/UserControls/SidebarControl.xaml, Files/Views/Settings.xaml
- Move sidebar acrylic values (eg tint opacity, tint luminosity opacity) to App.xaml to make them easier to theme
**Validation**
=> Move sidebar acrylic values to App.xaml to make them easier to theme

Files/UserControls/MultitaskingControl/HorizontalMultitaskingControl.xaml
- Code cleanup
- Remove unused resource
**Validation**
=> Remove unused resources from HorizontalMultitaskingControl

Files/ViewModels/AdaptiveSidebarViewModel.cs
=> Hide/show "open in new pane" item when toggling multipane option without app restart

Files/Helpers/ContextFlyoutItemHelper.cs
- Fixes #4610
- Use correct Command for pinning current folder to sidebar
**Validation**
=> Fixes option to pin current directory to the sidebar

Files/UserControls/FilePreviews/HtmlPreview.xaml, Files/UserControls/FilePreviews/HtmlPreview.xaml.cs, Files/UserControls/FilePreviews/RichTextPreview.xaml, Files/UserControls/FilePreviews/RichTextPreview.xaml.cs, Files/ViewModels/Previews/BasePreviewModel.cs
- Fixed issue where previews would not load for html files
- Fixed issue where previews would not load for rtf files
- Remove obsolete model loaded event
Issue was due to previews depending on the model being loaded after the control, but that is no longer the case. 
**Validation**
=> Fix issue where previews would not load for html and rtf files

Files/Interacts/ItemManipulationModel.cs, Files/Views/LayoutModes/ColumnViewBase.xaml.cs, Files/Views/LayoutModes/ColumnViewBrowser.xaml.cs, Files/Views/LayoutModes/GenericFileBrowser.xaml.cs, Files/Views/LayoutModes/GenericFileBrowser2.xaml.cs, Files/Views/LayoutModes/GridViewBrowser.xaml.cs
- Fixes #4662
- Dumb method to improve the speed of "invert selection" command in most cases
**Validation**
=> Improve invert selection performance

Files/INavigationToolbar.cs, Files/Strings/en-US/Resources.resw, Files/UserControls/NavigationToolbar.xaml, Files/UserControls/NavigationToolbar.xaml.cs, Files/Views/ModernShellPage.xaml, Files/Views/ModernShellPage.xaml.cs
- For #2447
Code taken from #3558
- Adds "Ctrl + F" keyboard shortcut to open the searchbox and "Esc" to close it
**Validation**
=> Add Ctrl+F shortcut to open search box

Files/ViewModels/SidebarViewModel.cs
- Make ``ActivePane`` a toolkit property so that the status bar text visibility binding to ``IsPageNotTypeHome`` updates
**Validation**
=> Fix issue where status bar text wouldn't show

Files/App.xaml, Files/UserControls/NavigationToolbar.xaml, Files/UserControls/StatusBarControl.xaml, Files/UserControls/Widgets/DrivesWidget.xaml, Files/UserControls/Widgets/WidgetsListControl.xaml, Files/Views/LayoutModes/GenericFileBrowser2.xaml, Files/Views/ModernShellPage.xaml, Files/Views/WidgetsPage.xaml
- Added a background brush for the file browser control
- Added a background brush for the status bar
- Fixed the margins on the navigation toolbar and status bar
=> Updated styles

Files/App.xaml, Files/ResourceDictionaries/TabView_themeresources.xaml, Files/UserControls/MultitaskingControl/VerticalTabViewControl.xaml, Files/UserControls/NavigationToolbar.xaml, Files/UserControls/StatusCenter.xaml, Files/UserControls/Widgets/DrivesWidget.xaml, Files/UserControls/Widgets/LibraryCards.xaml, Files/UserControls/Widgets/RecentFiles.xaml, Files/Views/LayoutModes/ColumnViewBase.xaml, Files/Views/LayoutModes/ColumnViewBrowser.xaml, Files/Views/LayoutModes/GenericFileBrowser.xaml, Files/Views/LayoutModes/GenericFileBrowser2.xaml, Files/Views/LayoutModes/GridViewBrowser.xaml, Files/Views/MainPage.xaml, Files/Views/Settings.xaml
- Added missing brush to high contrast resources
- Removed extra resources from app.xaml
Fixes #4319
=> Fixed an issue where Files would crash when using high contrast themes

Files/Filesystem/FilesystemOperations/FilesystemOperations.cs, Files/Filesystem/FilesystemOperations/Helpers/FilesystemHelpers.cs, Files/Helpers/NavigationHelpers.cs, Files/Views/Pages/PropertiesGeneral.xaml.cs
https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/2619919200u/overview
- Fixed the cause of the linked appcenter issue: issue was due to `await null`. Fixed usage in another couple of places.
- Reverted #4586 -> optional, but this should be a more "precise" fix for the issue.
**Validation**
=> Fix a possible crash due to await-ing null

Files/Filesystem/FilesystemOperations/Helpers/FilesystemHelpers.cs, Files/MultilingualResources/Files.ar.xlf, Files/MultilingualResources/Files.cs-CZ.xlf, Files/MultilingualResources/Files.da-DK.xlf, Files/MultilingualResources/Files.da.xlf, Files/MultilingualResources/Files.de-DE.xlf, Files/MultilingualResources/Files.es-ES.xlf, Files/MultilingualResources/Files.fr-FR.xlf, Files/MultilingualResources/Files.he-IL.xlf, Files/MultilingualResources/Files.hi-IN.xlf, Files/MultilingualResources/Files.hu-HU.xlf, Files/MultilingualResources/Files.it-IT.xlf, Files/MultilingualResources/Files.ja-JP.xlf, Files/MultilingualResources/Files.ko-KR.xlf, Files/MultilingualResources/Files.lv-LV.xlf, Files/MultilingualResources/Files.nl-NL.xlf, Files/MultilingualResources/Files.or-IN.xlf, Files/MultilingualResources/Files.pl-PL.xlf, Files/MultilingualResources/Files.pt-BR.xlf, Files/MultilingualResources/Files.pt-PT.xlf, Files/MultilingualResources/Files.ru-RU.xlf, Files/MultilingualResources/Files.sv-SE.xlf, Files/MultilingualResources/Files.ta.xlf, Files/MultilingualResources/Files.tr-TR.xlf, Files/MultilingualResources/Files.uk-UA.xlf, Files/MultilingualResources/Files.zh-Hans.xlf, Files/MultilingualResources/Files.zh-Hant.xlf, Files/Strings/en-US/Resources.resw
=> Added strings for the rename file dialog

Files/UserControls/Widgets/LibraryCards.xaml
=> Updated font weight for library widget

Files/Views/LayoutModes/GenericFileBrowser2.xaml
This should fix some of the issues related to styling the ListView's ItemTemplate by using the new WinUI styles. **This change also needs to be validated on non-dev channel builds before merging.**
**Validation**
=> Make GenericFileBrowser2 use new ListView styling

Files/Files.csproj, Files/INavigationToolbar.cs, Files/ISearchBox.cs, Files/UserControls/NavigationToolbar.xaml, Files/UserControls/NavigationToolbar.xaml.cs, Files/UserControls/SearchBox.xaml, Files/UserControls/SearchBox.xaml.cs, Files/Views/ColumnShellPage.xaml.cs, Files/Views/ModernShellPage.xaml, Files/Views/ModernShellPage.xaml.cs
Move the SearchRegion code to a specific control.
This simplify the code of the navigation bar.
This pr does not provide any functionality and prepares issue #4813 which improves the search bar.
=> Refactor search bar

Files/Views/LayoutModes/DetailsLayoutBrowser.xaml, Files/Views/LayoutModes/GridViewBrowser.xaml
=> Fixed margins on the different layout modes

Files/Filesystem/Search/FolderSearch.cs, Files/Views/ColumnShellPage.xaml.cs, Files/Views/ModernShellPage.xaml.cs
Refactors the FolderSearch class.
Less static, less arguments, more object.
=> Refactor FolderSearch

Files/BaseLayout.cs, Files/Converters/IntToGroupOption.cs, Files/Converters/IntToSortDirection.cs, Files/Converters/IntToSortOption.cs, Files/Enums/SortOption.cs, Files/Filesystem/ListedItem.cs, Files/Helpers/ContextFlyoutItemHelper.cs, Files/Helpers/ItemListDisplayHelpers/GroupingHelper.cs, Files/Helpers/ItemListDisplayHelpers/SortingHelper.cs, Files/Strings/en-US/Resources.resw, Files/UserControls/ArrangementOptions.xaml, Files/UserControls/ArrangementOptions.xaml.cs, Files/UserControls/PreviewPane.xaml, Files/UserControls/SidebarControl.xaml.cs, Files/ViewModels/ContextMenuFlyoutItemViewModel.cs, Files/ViewModels/FolderSettingsViewModel.cs, Files/ViewModels/ItemViewModel.cs, Files/ViewModels/SettingsViewModel.cs, Files/Views/ColumnShellPage.xaml, Files/Views/LayoutModes/ColumnViewBase.xaml, Files/Views/LayoutModes/DetailsLayoutBrowser.xaml, Files/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs, Files/Views/ModernShellPage.xaml
- For #4643
- Fixes an issue for which sometimes an empty context menu is shown when right-clicking in details view
- Allow to sort and group by cloud sync status
- Fixes an issue for which dragging over sidebar items did not trigger navigation
**Validation**
=> Details view improvements 2

Files.Launcher/Program.cs, Files/Helpers/ShellContextMenuHelper.cs
- Fixes #5080 
- Fixes #3708
- Fixes veery strange issue with pCloud context menu items
- Enable showing icons for shell context menu items in sub menus
**Validation**
=> Fix pCloud context menu, show icons in sub menu

Files/MultilingualResources/Files.id-ID.xlf
Update translation id-ID (Bahasa Indonesia)
=> Update translation: id-ID

Files/Filesystem/Drives.cs, Files/Strings/en-US/Resources.resw
- Closes #5084
- Fixes an issue for which pCloud drive was not shown in sidebar
**Validation**
=> Fix pCloud drive not shown in sidebar

Files/DataModels/NavigationControlItems/DriveItem.cs, Files/DataModels/NavigationControlItems/LocationItem.cs, Files/DataModels/SidebarPinnedModel.cs, Files/Filesystem/CloudDrivesManager.cs, Files/Filesystem/LibraryLocationItem.cs, Files/Filesystem/LibraryManager.cs, Files/Helpers/ContextFlyoutItemHelper.cs, Files/Helpers/PathNormalization.cs, Files/UserControls/SidebarControl.xaml, Files/UserControls/Widgets/LibraryCards.xaml.cs, Files/ViewModels/ItemViewModel.cs, Files/ViewModels/Pages/YourHomeViewModel.cs, Files/ViewModels/Properties/DriveProperties.cs, Files/ViewModels/Properties/FileProperties.cs, Files/ViewModels/Properties/FolderProperties.cs, Files/ViewModels/Properties/LibraryProperties.cs, Files/ViewModels/SelectedItemsPropertiesViewModel.cs, Files/Views/WidgetsPage.xaml.cs
- Closes #5055
- Fixes drive icon not loaded in properties
- Fixes folder icon not loaded in properties when clicking on empty space
- Fixes library icons not loaded in sidebar
**Validation**
=> Fixes a few issues related to icons not being loaded in properties and sidebar

Files/ISearchBox.cs, Files/UserControls/NavigationToolbar.xaml, Files/UserControls/NavigationToolbar.xaml.cs, Files/UserControls/SearchBox.xaml, Files/UserControls/SearchBox.xaml.cs, Files/Views/ColumnShellPage.xaml.cs, Files/Views/ModernShellPage.xaml.cs
The suggestions of SearchBox are erased at each key change and displayed again, even if the results are the same.
This pr modifies the display instead of redoing it entirely. This will be very useful for #4813. 
**Validation**
Here is a before/after video.
https://user-images.githubusercontent.com/46631671/120709568-488d1280-c4bd-11eb-9b49-c942ccd5ebd0.mp4
=> Improves suggestions

Files/MultilingualResources/Files.de-DE.xlf, Files/Strings/de-DE/Resources.resw
Fixed a typo in the German translation
=> Fix typo in German translation

Files/UserControls/NavigationToolbar.xaml
- Fixes #5134 
- Change `NavToolbarLayoutMode` to `NavToolbarLayout`
**Validation**
=> Fixed the Uid of a textblock

README.md
Update README in net6 preview ftp upgrade work
=> Update README.md for .NET 6 previews

Files/Views/SettingsPages/Appearance.xaml
- Closes #5099 
- Replaced theme combo box with radio buttons
**Validation**
=> Appearance: Replace combo box with radio buttons

.github/FUNDING.yml, Files/MultilingualResources/Files.pt-PT.xlf, Files/Strings/pt-PT/Resources.resw, Files/Views/MainPage.xaml, Files/Views/MainPage.xaml.cs, Files/Views/Pages/Properties.xaml, Files/Views/SettingsPages/Appearance.xaml
- Closes #5126 
- Added F11 `KeyboardAccelerator` and implemented full-screen toggle command
**Validation**
=> For #5126. Add F11 shortcut for full-screen view

Files/MultilingualResources/Files.hu-HU.xlf
- Fixed two wrong states in xlf file [hu-HU]
**Validation**
=> Fixed some wrong states in files.hu-HU.xlf

Files/MultilingualResources/Files.nl-NL.xlf, Files/Strings/nl-NL/Resources.resw
I've checked and updated all Dutch translations to better match Microsoft's terminology ([https://www.microsoft.com/en-us/language/Search](https://www.microsoft.com/en-us/language/Search)). I also added any missing strings. (I hope everything went OK with Resources.resw, I kind of messed up at first by translating it all manually. -_-)
=> Updated Dutch translations

Files.Launcher/Program.cs, Files.Launcher/Win32API.cs, Files.Launcher/Win32API_ContextMenu.cs, Files/ViewModels/ItemViewModel.cs
- Closes #3490
- Closes #4714
- Closes #3576
- Uses powershell to mount vhd/vhdx so mounting works
- Uses windows dialog to enter bitlocker password since current method stopped working
**Validation**
=> Fix vhd/vhdx disk mounting and unlocking bitlocker drives

Files/ViewModels/ItemViewModel.cs
- Fix thumbnails appearing blurry when loading items caused by the queue using the default item size
- Save requested thumbnail size as well as the item in the load queue
**Validation**
=> Fix issue where thumbnails would appear blurry

Files/Files.csproj, Files/Helpers/WidgetsHelpers.cs, Files/Strings/en-US/Resources.resw, Files/UserControls/Widgets/BundlesWidget.xaml, Files/UserControls/Widgets/BundlesWidget.xaml.cs, Files/UserControls/Widgets/DrivesWidget.xaml, Files/UserControls/Widgets/RecentFilesWidget.xaml, Files/UserControls/Widgets/RecentFilesWidget.xaml.cs, Files/Views/WidgetsPage.xaml.cs
- Added tooltip to create bundle button (closes #4993)
- Fixed padding on widgets
=> Updated code for widgets

Files/Constants.cs, Files/Helpers/AdaptiveLayoutHelpers.cs
- For #4540 
- This PR changes the Adaptive Layout behavior to match users feedback.
**Validation**
=> Don't use tiles layout for Adaptive Layout

Files/App.xaml, Files/ResourceDictionaries/TabView_themeresources.xaml, Files/UserControls/DataGridHeader.xaml, Files/UserControls/MultitaskingControl/TabItem/TabItemControl.xaml, Files/UserControls/NavigationToolbar.xaml, Files/UserControls/SidebarControl.xaml
- Closes #5025 
Fix sidebar background brush issue, make HC work, and remove old style
**Validation**
=> Fix sidebar background brush, make HC work, and remove old style

Files/BaseLayout.cs, Files/Helpers/ItemModelListToContextFlyoutHelper.cs, Files/Helpers/ShellContextMenuHelper.cs, Files/INavigationToolbar.cs, Files/Interacts/BaseLayoutCommandImplementationModel.cs, Files/UserControls/MenuFlyoutItemWithImage.xaml.cs, Files/UserControls/Widgets/RecentFilesWidget.xaml.cs, Files/ViewModels/ItemViewModel.cs, Files/Views/WidgetsPage.xaml.cs
- Closes #5278
- Focus file after invoking Open File Location command from Recent Files
- Fix icon sometimes overlapping text in context menu
**Validation**
=> Focus file after Open File Location command

Files.Launcher/Win32API.cs, Files.Launcher/Win32API_ContextMenu.cs, Files/ViewModels/PreviewPaneViewModel.cs
- Fixed an issue with preview pane causing crash when dragging files
- Fixed an issue causing fulltrust process to crash with AccessViolationException when loading icons
**Validation**
=> Fix crash when dragging files quickly

Files/Files.csproj, Files/Helpers/ZipHelpers.cs, Files/Strings/en-US/Resources.resw, Files/ViewModels/PreviewPaneViewModel.cs, Files/ViewModels/Previews/ArchivePreviewViewModel.cs
Adds the item count and uncompressed size to the preview pane details for zip files.
**Validation**
=> Added details for zip files

Files/MultilingualResources/Files.pt-PT.xlf
=> pt-PT language update

Files/MultilingualResources/Files.pt-PT.xlf
=> Little pt-PT update

Files.Launcher/LogWriter.cs, Files/Helpers/UniversalLogWriter.cs
- Switched from using FileIO to writing directly to the file stream, since FileIO operations will create tmp files
**Validation**
=> Fix issue where tmp files would be generated from the logger

Files/MultilingualResources/Files.pt-BR.xlf, Files/MultilingualResources/Files.pt-PT.xlf
Correction and introduction of new translations for Portuguese Brazil and Portuguese Portugal.
=> Languages Update - pt_PT and pt_BR

Common/ILogWriter.cs, Common/Logger.cs, Files.Launcher/LogWriter.cs, Files.Launcher/Program.cs, Files/App.xaml.cs, Files/Helpers/NativeFileOperationsHelper.cs, Files/Helpers/UniversalLogWriter.cs
- Fixes an issue where unhandled exceptions are not logged to the log files.
- Write to log file synchronously when logging an unhandled exception to avoid app terminating before log completes
**Validation**
=> Log exception syncronously on unhandled exception

Files/MultilingualResources/Files.de-DE.xlf
This fixes a number of mistakes in the German translation and also improves the wording of some translations.
**Validation**
=> Multiple fixes and tweaks in German translation

Files/DataModels/SidebarPinnedModel.cs, Files/Views/Pages/PropertiesGeneral.xaml.cs
- Closes #5386
- Added null check on SlimContentPage which is null on homepage
- Fix icon not shown on sidebar for hidden folders
**Validation**
=> Add null check on saving properties

Files.Launcher/MessageHandlers/FileOperationsHandler.cs, Files/Filesystem/FilesystemOperations/Helpers/FilesystemHelpers.cs
=> Allow to change or remove file extension when renaming

Files/MultilingualResources/Files.es-ES.xlf
- Added remaining translations.
- Improved some strings to keep consistency with Windows.
- Marked some as "needs review", so others could check and maybe improve them.
I used Windows and [Microsoft terminology collection](https://www.microsoft.com/en-us/language/Search) as a base for the translations.
**Validation**
=> Update Files.es-ES.xlf (Spain Spanish)

Files/UserControls/MultitaskingControl/TabItem/TabItem.cs
Improve JSON parsing
Tweak [TypeNameHandling setting](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2326)
**Validation**
=> Improve JSON parsing

Files/Extensions/StringExtensions.cs, Files/Files.csproj, Files/Strings/pt-PT/Resources.resw
- Removed JetBrains annotations
**Validation**
=> Removed JetBrains annotations

Files/MultilingualResources/Files.es-419.xlf, Files/Strings/es-419/Resources.resw
- New strings were translated into Latin American Spanish
- Some translations were modified
**Validation**
=> Translation update (es-Latam)

Files/UserControls/NavigationToolbar.xaml, Files/UserControls/NavigationToolbar.xaml.cs
- Use new style for radiobutton with togglebutton theme
- Remove unused code
**Validation**
=> Use new ToggleButton style

Files/MultilingualResources/Files.pt-PT.xlf
Minor fixes in existing translations
=> pt-PT translation

Files/UserControls/PreviewPane.xaml, Files/Views/MainPage.xaml.cs
- Fix issue where file previews are shown when multiple items are selected
- Also fixes issue where preview pane doesn't work when multi pane is in use
**Validation**
=> Fix issue where file previews are shown when multiple items are selected

Files/BaseLayout.cs, Files/Extensions/LinqExtensions.cs, Files/Helpers/ContextFlyoutItemHelper.cs, Files/Helpers/ShellContextMenuHelper.cs
**Fixes issues**
- Fixes #5481
- Change the "empty space" context menu to load shell menu items asynchronously (same as items menu)
**Validation**
PS: great job with #5358 btw. Hope you were not already working on this.
=> Load empty space menu dynamically

Files/BaseLayout.cs, Files/Extensions/LinqExtensions.cs, Files/Helpers/ContextFlyoutItemHelper.cs, Files/ViewModels/ItemViewModel.cs
- Fixes a small issue of #5480
- Fixes an issue for which deleted files appear when browsing the Network folder
- Fixes an issue where the overflow menu item was shown even if the option was turned off
**Validation**
=> Fix small issue with context menu

Files/DataModels/FilesystemItemsOperationDataModel.cs, Files/Filesystem/FilesystemOperations/Helpers/FilesystemHelpers.cs, Files/ViewModels/Dialogs/FilesystemOperationItemViewModel.cs
- Closes #5302
- Show display name in delete dialog for items in recycle bin
**Validation**
=> Show display name in delete dialog for items in recycle bin

Files/ViewModels/ColumnsViewModel.cs, Files/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs
- Fir #4643
- Fix columns squished to the left on navigation
- Focus file list upon navigation instead of header
- Reduce width so that it doesn't horizontal scroll when the window is already large enough
**Validation**
=> Details view improvements

Files/App.xaml, Files/MultilingualResources/Files.ar.xlf, Files/MultilingualResources/Files.cs-CZ.xlf, Files/MultilingualResources/Files.da-DK.xlf, Files/MultilingualResources/Files.da.xlf, Files/MultilingualResources/Files.de-DE.xlf, Files/MultilingualResources/Files.es-419.xlf, Files/MultilingualResources/Files.es-ES.xlf, Files/MultilingualResources/Files.fr-FR.xlf, Files/MultilingualResources/Files.he-IL.xlf, Files/MultilingualResources/Files.hi-IN.xlf, Files/MultilingualResources/Files.hu-HU.xlf, Files/MultilingualResources/Files.id-ID.xlf, Files/MultilingualResources/Files.it-IT.xlf, Files/MultilingualResources/Files.ja-JP.xlf, Files/MultilingualResources/Files.ko-KR.xlf, Files/MultilingualResources/Files.lv-LV.xlf, Files/MultilingualResources/Files.nl-NL.xlf, Files/MultilingualResources/Files.or-IN.xlf, Files/MultilingualResources/Files.pl-PL.xlf, Files/MultilingualResources/Files.pt-BR.xlf, Files/MultilingualResources/Files.pt-PT.xlf, Files/MultilingualResources/Files.ru-RU.xlf, Files/MultilingualResources/Files.sv-SE.xlf, Files/MultilingualResources/Files.ta.xlf, Files/MultilingualResources/Files.tr-TR.xlf, Files/MultilingualResources/Files.uk-UA.xlf, Files/MultilingualResources/Files.zh-Hans.xlf, Files/MultilingualResources/Files.zh-Hant.xlf
- #5500
- #5498 (?)
- switched to layer fill color default for content area
- updated strings
**Validation**
=> Improve mica in content area

Files/ViewModels/Properties/FileProperties.cs, Files/ViewModels/Properties/FolderProperties.cs
- Closes #5519
- Open shortcut location from properties in new tab instead of new window
**Validation**
=> Open shortcut location in new tab

Files/ViewModels/MainPageViewModel.cs
- Closes #5520
- Add glyph on tab for libraries
**Validation**
=> Add glyph on tab for libraries

Files/BaseLayout.cs
- Closes #5508
- Close the context menu when clicking primary items (workaround for winui issue)
**Validation**
=> Close context menu when clicking on primary buttons

Files/UserControls/ColoredIcon.xaml, Files/UserControls/InnerNavigationToolbar.xaml
- Move copy to be before paste
=> Reordered options on nav toolbar

Files/Filesystem/FilesystemOperations/ShellFilesystemOperations.cs, Files/Filesystem/NetworkDrivesManager.cs, Files/ViewModels/Properties/FileProperties.cs, Files/ViewModels/Properties/FolderProperties.cs
- Closes #5565
- Call AddNewTabFromPathAsync on UI thread (fixes #5565)
- Added a couple of null checks for issues seen on AppCenter
**Validation**
=> Fixes an issue preventing "open file location" from working in Properties

Files/Dialogs/DynamicDialog.xaml, Files/Dialogs/DynamicDialog.xaml.cs
- The interaction events weren't invoking the command, instead manually invoke them from event handlers
**Validation**
=> Fix issue where creating new item wouldn't work

Files/Filesystem/FilesystemOperations/ShellFilesystemOperations.cs
- Fixes an issue for which non-conflicting files are not copied if there's any conflict
**Validation**
=> Fixes an issue for which non-conflicting files are not copied if there's any conflict

Files/MultilingualResources/Files.es-ES.xlf
- Added remaining strings to Files.es-ES
**Validation**
=> Update Es-Es (Spain spanish)

Files/MultilingualResources/Files.el.xlf, Files/MultilingualResources/Files.pt-PT.xlf
- Translation of new strings to pt-PT
- Translation of new strings to el
**Validation**
=> Translations - update 29/07

Files/Views/LayoutModes/ColumnViewBase.xaml.cs, Files/Views/LayoutModes/ColumnViewBrowser.xaml.cs, Files/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs, Files/Views/LayoutModes/GridViewBrowser.xaml.cs
- Lately I've been unable to drag/drop items into folders. Not sure what has changed but this PR fixes this.
**Validation**
=> Fix drag drop into folders

Files/MultilingualResources/Files.es-419.xlf
- New strings translated into Latin American Spanish
- Some translations were modified
**Validation**
Without updating the resw file this time, for some reason the resw files of any language are not updating in visual studio 2022
=> Translation update [es-Latam]

Files/MultilingualResources/Files.zh-Hans.xlf
=> Update Chinese Translation

Files/MultilingualResources/Files.hu-HU.xlf
- Removed duplicate resource in hu-HU.xlf preventing build (after #5572)
**Validation**
=> Fix build error due to duplicate resource in hu-HU

Files/MultilingualResources/Files.lv-LV.xlf
- Added...
- Fixed...
**Validation**
=> Updated latvian translation

Files/MultilingualResources/Files.ka.xlf, Files/Strings/ka/Resources.resw
Translated new strings.
- Added...
- Fixed...
- Translated new strings.
- Imrpoved translation.
**Validation**
=> Improved Georgian translation.

Files/Views/LayoutModes/GridViewBrowser.xaml
- Closes https://github.com/files-community/Files/issues/5684
- Fix: Renaming Box on Grid View is Broken
**Validation**
=> Fixed Renaming Box on Grid View is Broken

Files/DataModels/SidebarPinnedModel.cs, Files/Filesystem/Search/FolderSearch.cs, Files/Helpers/DriveHelpers.cs, Files/Helpers/FileThumbnailHelper.cs, Files/MultilingualResources/Files.ka.xlf, Files/UserControls/MultitaskingControl/HorizontalMultitaskingControl.xaml, Files/UserControls/MultitaskingControl/VerticalTabViewControl.xaml, Files/UserControls/Widgets/FolderWidget.xaml.cs, Files/ViewModels/ItemViewModel.cs, Files/ViewModels/MainPageViewModel.cs, Files/ViewModels/Previews/BasePreviewModel.cs, Files/ViewModels/Previews/ShortcutPreviewViewModel.cs, Files/ViewModels/Properties/DriveProperties.cs, Files/ViewModels/Widgets/Bundles/BundleItemViewModel.cs
- Closes #5524
- Show folder icon instead of glyph on tabs
- Reduce code duplication for loading files thumbnail
**Validation**
=> Show directory icon on the tab control

Files/Helpers/ContextFlyoutItemHelper.cs
- Related #5713
- use new colored icon for blank space properties and new item icons
**Validation**
=> Fix inconsistent properties and new item icons

Files/Helpers/ExternalResourcesHelper.cs, Files/UserControls/Settings/ThemeSampleDisplayControl.xaml.cs
- Closes #5736
- Fixed a bug introduced in #5719 (restored the try-catch around `MergedDictionaries.Add` that can throw exceptions)
**Validation**
=> Fix exception handling on theme load

Files.Launcher/MessageHandlers/FileOperationsHandler.cs, Files.Launcher/MessageHandlers/RecycleBinHandler.cs, Files/Filesystem/FilesystemOperations/FilesystemOperations.cs, Files/Filesystem/FilesystemOperations/Helpers/FilesystemHelpers.cs, Files/Filesystem/FilesystemOperations/ShellFilesystemOperations.cs, Files/Helpers/RecycleBinHelpers.cs
- Closes #1768
- Show system permanent deletion warning if a file is going to be permanently deleted instead of recycled (e.g in case of full recycle bin)
**Validation**
=> Show permanent deletion warning if bin is full

Files/Filesystem/FilesystemOperations/FilesystemOperations.cs, Files/Helpers/UIFilesystemHelpers.cs, Files/Models/Settings/BaseJsonSettingsModel.cs
- Closes #5754
- Fixed not getting asked to perform delete operation as admin
**Validation**
=> Fix delete as admin

Files/MultilingualResources/Files.el.xlf, Files/MultilingualResources/Files.fr-FR.xlf, Files/MultilingualResources/Files.pt-PT.xlf
- Closes #5721  
- Update pt-PT translation
- Update el translation
- Update fr-FR translation
**Validation**
None
=> Translation Updates

Files/Views/MainPage.xaml
=> Set focus to nav toolbar on app launch

Files/MultilingualResources/Files.ka.xlf
Improved Georgian translation.
Translated new strings.
- Added...
- Fixed...
**Validation**
=> Translated new strings.

Files/MultilingualResources/Files.pt-BR.xlf
- Added...
- Fixed...
**Validation**
=> Update translation of new pt-BR strings

Files/Filesystem/ListedItem.cs, Files/ViewModels/SettingsViewModels/OnStartupViewModel.cs, Files/Views/SettingsPages/OnStartup.xaml
- Closes #5079
- Closes #5766
**Validation**
=> Do not read item path in narrator

Files/DataModels/NavigationControlItems/DriveItem.cs, Files/Strings/en-US/Resources.resw, Files/UserControls/SidebarControl.xaml.cs, Files/UserControls/Widgets/DrivesWidget.xaml.cs, Files/ViewModels/MainPageViewModel.cs, Files/ViewModels/NavToolbarViewModel.cs, Files/Views/ModernShellPage.xaml.cs
- Closes #4550
- Closes #5503
- Added a dialog that get shown when there isn't a disc on disc drive
**Validation**
=> Add a dialog that say to insert a disc

Files/MultilingualResources/Files.he-IL.xlf
- Hebrew translation improvments
**Validation**
=> Hebrew translation improvments

Files/Helpers/UIFilesystemHelpers.cs
=> Fix crash when creating folders in libraries

Files/MultilingualResources/Files.he-IL.xlf
- Hebrew translation updates
**Validation**
=> Hebrew translation updates

Files/UserControls/FilePreviews/MediaPreview.xaml, Files/UserControls/FilePreviews/MediaPreview.xaml.cs, Files/ViewModels/SettingsViewModel.cs
- <none>
- Added: remember MediaVolume in MediaPreview
**Validation**
https://user-images.githubusercontent.com/17952364/129282114-9d4b5e6e-6c8e-4ab4-bcde-f720719ff086.mp4
=> MediaPreview Panel - Remember MediaVolume

Files/Views/LayoutModes/ColumnViewBase.xaml.cs, Files/Views/LayoutModes/ColumnViewBrowser.xaml.cs, Files/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs, Files/Views/LayoutModes/GridViewBrowser.xaml.cs
- Closes #5807
- Fix rename starting on Space when Quicklook is enabled
**Validation**
=> Fix rename starting on Space when Quicklook is enabled

Files/Dialogs/DynamicDialog.xaml, Files/Dialogs/FilesystemOperationDialog.xaml, Files/Dialogs/FilesystemOperationDialog.xaml.cs, Files/Helpers/DynamicDialogFactory.cs, Files/Strings/en-US/Resources.resw, Files/ViewModels/Dialogs/FilesystemOperationDialogViewModel.cs
- Closes #5729
- Autofocus text box for new item dialog
- Add apply to all right click option in filesystem dialog to apply the selected option to all items
- improve filesystem dialog right click reliability and keyboard accessibility by moving context flyout to the item container
- allow pressing continue even if not all conflicts have been resolved, and apply the default option for all items that have not had an option applied to reduce amount of clicks needed
**Validation**
=> Dialog improvements

Files/MultilingualResources/Files.nl-NL.xlf
=> Updated Dutch translation

Files/MultilingualResources/Files.el.xlf, Files/MultilingualResources/Files.fr-FR.xlf, Files/MultilingualResources/Files.pt-PT.xlf
- Updated el translation;
- Updated pt-PT translation;
- Updated fr-FR translation;
=> Translations Update

Files/MultilingualResources/Files.ka.xlf, Files/Strings/ka/Resources.resw
- Added...
- Fixed...
**Validation**
=> Updated ka translations

Files/MultilingualResources/Files.ka.xlf
- Removed a duplicated string on files.ka.xlf that throw an error while compiling.
**Validation**
=> Removed a duplicated string that caused a deploy failure

Files/App.xaml, Files/Files.csproj
- Closes #5858 
- Bump Microsoft.UI.Xaml to 2.6.2
- Reverts #5844 since this version includes those fixes.
**Validation**
=> Bump Microsoft.UI.Xaml to 2.6.2

Files/MultilingualResources/Files.ka.xlf, Files/Strings/ka/Resources.resw
- Added...
- Fixed...
**Validation**
=> Updated ka

Files/Views/LayoutModes/ColumnViewBase.xaml.cs, Files/Views/LayoutModes/ColumnViewBrowser.xaml.cs, Files/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs, Files/Views/LayoutModes/GridViewBrowser.xaml.cs
- Closes #5895 
- Commit rename when clicking outside textbox
**Validation**
=> Commit rename when clicking outside textbox

Files.Launcher/MessageHandlers/LibrariesHandler.cs, Files.Launcher/MessageHandlers/NetworkDrivesHandler.cs
- For #5556
- Added a null check to ftp, should help with #5556 but needs to be verified by the user
**Validation**
=> Tentative fix for ftp crash

Files/ResourceDictionaries/DefaultGridSplitterStyle.xaml, Files/UserControls/PreviewPane.xaml, Files/Views/ColumnShellPage.xaml, Files/Views/MainPage.xaml, Files/Views/ModernShellPage.xaml, Files/Views/PaneHolderPage.xaml
- For #4180
- Removed duplicate xaml style definitions for GridSplitter
This PR should not cause any visible changes.
**Validation**
=> Remove duplicate definitions of GridSplitter style

Files/Filesystem/Search/FolderSearch.cs, Files/UserControls/NavigationToolbar.xaml
- Closes #5931
- Enable search on home to search all (fixed) drives
**Validation**
=> Enable search on home to search all drives

Files/UserControls/NavigationToolbar.xaml, Files/ViewModels/ItemViewModel.cs, Files/ViewModels/StatusCenterViewModel.cs
- Closes #2857
- As discussed some time ago, keep showing the ongoing tasks button if there are any banners
- Auto refresh items when toggling "show hidden items" option
**Validation**
=> Show ongoing tasks button if there are any banners

Files.Launcher/MessageHandlers/FileOperationsHandler.cs, Files/Filesystem/FilesystemOperations/FilesystemOperations.cs
- Closes #5956
- Added possibility to create files and folders as admin. This was the last file operation missing this ability.
**Validation**
=> Create files and folder as admin

Files/MultilingualResources/Files.ka.xlf, Files/Strings/ka/Resources.resw
- Added...
- Fixed...
**Validation**
=> New strings translated.

Files/MultilingualResources/Files.el.xlf, Files/Strings/el/Resources.resw
=> Greek Language

Files/MultilingualResources/Files.es-ES.xlf
- Added last strings to spanish spain translation.
**Validation**
=> Update Files.es-ES (Spanish Spain)

Files/UserControls/Widgets/RecentFilesWidget.xaml.cs, Files/ViewModels/ItemViewModel.cs
- Closes #5986 
- Fixed wrong cast preventing recent items load
**Validation**
=> Fix recent files not showing

Files/Helpers/ContextFlyoutItemHelper.cs, Files/Views/SettingsPages/FilesAndFolders.xaml
- Closes #5968
- Closes #5994
- Fixed the glyph icons for open in terminal and protected SO files setting.
**Validation**
=> Added missing icons glyphs for open in terminal and hide protected SO files setting.

Files/Views/MainPage.xaml
- Fixed issue where RootBackgroundBrush wouldn't show over mica, breaking themes
**Validation**
=> Fix issue where root background brush wouldn't show

Files/ViewModels/ColumnsViewModel.cs, Files/Views/LayoutModes/DetailsLayoutBrowser.xaml, Files/Views/PaneHolderPage.xaml
=> Added border to status bar to match design spec

Files/App.xaml, Files/Views/MainPage.xaml, Files/Views/MainPage.xaml.cs
=> Updated preview pane background and border

Files/UserControls/Widgets/FolderWidget.xaml.cs
=> Fixed library cards not opening on click

Files/Helpers/ContextFlyoutItemHelper.cs
NOTE: Although the issue is labeled as "bug", I'm not sure if this is a bug or an enhancement. Feel free to leave this unreviewed until V2 is oficially released.
- Closes #4259
- Added Open With to Zip files context menu.
**Validation**
=> Added Open with to Zip files

Files/BaseLayout.cs
=> Fix crash when entering network path

Files/ViewModels/ItemViewModel.cs
- Closes #6054
- Check workingdir not home before refreshing
**Validation**
=> Do not show error message when toggling hidden files

Files/MultilingualResources/Files.fr-FR.xlf
Add last missing texts in French.
=> Add last missing texts in FR-fr

Files/Extensions/DateTimeExtensions.cs
- Closes #5217
- Fixed showing wrong files in "Today" and "Yesterday" section when grouping by date
**Validation**
=> Fix for grouping by date issues #5217

Files/Helpers/NativeWinApiHelper.cs, Files/ViewModels/ItemViewModel.cs
=> Add version check before accessing HasThreadAccess property

Files/Filesystem/FileTagsHelper.cs
- Fixes an issue where the modified datetime for tagged files would always be changed when listing the files.
**Validation**
=> Do not change last modified time for tagged files

Files/Helpers/PathNormalization.cs, Files/ViewModels/FolderSettingsViewModel.cs, Files/Views/ModernShellPage.xaml.cs
- Closes #6200
- Clicking up from network root will now navigate to Home
**Validation**
=> Fix going up from network root path

Files/Views/LayoutModes/ColumnViewBase.xaml.cs, Files/Views/LayoutModes/ColumnViewBrowser.xaml.cs
- Should fix AppCenter issue 4106604129u
- Added null check in ColumnView ItemTapped event
**Validation**
=> Bug fix for column view

Files/ViewModels/MainPageViewModel.cs
- Related to PR #5985
- Added a null checking to avoid an exception that were happening on Visual Studio on Files fresh installations since LastSessionPages is null on that scenario.
**Validation**
=> Fixed an exception on fresh installing

Files/ViewModels/ItemViewModel.cs
- Closes #6233 
- Fixes SyncUI not being updated: SyncUI need to be constructed on the main thread
**Validation**
=> Fix SyncUI not being updated

Files/MultilingualResources/Files.fr-FR.xlf
Small improvements to existing French texts. This pr is based on #6007 (closed for inactivity), but with an analysis of each text.
=> Small improvements to existing French texts

Files/BaseLayout.cs, Files/Filesystem/FilesystemOperations/FilesystemOperations.cs, Files/Filesystem/FilesystemOperations/Helpers/FilesystemHelpers.cs, Files/Filesystem/StorageItems/ZipStorageFolder.cs, Files/Helpers/UIFilesystemHelpers.cs, Files/Helpers/UIHelpers.cs, Files/Helpers/ZipHelpers.cs, Files/Interacts/BaseLayoutCommandImplementationModel.cs, Files/UserControls/MultitaskingControl/HorizontalMultitaskingControl.xaml.cs, Files/UserControls/MultitaskingControl/VerticalTabViewControl.xaml.cs, Files/UserControls/Selection/RectangleSelection.cs, Files/UserControls/SidebarControl.xaml.cs, Files/ViewModels/Dialogs/DynamicDialogViewModel.cs, Files/ViewModels/ItemViewModel.cs, Files/ViewModels/MainViewModel.cs, Files/ViewModels/NavToolbarViewModel.cs, Files/ViewModels/Properties/FileProperties.cs, Files/ViewModels/SettingsViewModel.cs, Files/ViewModels/SettingsViewModels/AboutViewModel.cs, Files/Views/MainPage.xaml.cs, Files/Views/ModernShellPage.xaml.cs, Files/Views/Pages/PropertiesDetails.xaml.cs, Files/Views/Pages/PropertiesLibrary.xaml.cs
- Fixes for some issues seen on AppCenter
- Closes #5966
**Validation**
=> Bugfixes 3

Files/MultilingualResources/Files.zh-Hans.xlf
- None 
- Fixed (Most of the) Untranslated Items
**Validation**
=> Update Chinese(Simplified) Translation

Files/ViewModels/PreviewPaneViewModel.cs, Files/ViewModels/Previews/MediaPreviewViewModel.cs
- fixes issue where preview would be shown unexpectedly when quickly selecting then unselecting a file
- Closes #6291
- Added .flac to supported media preview extensions
- add check for cancellation after loading the basic preview
**Validation**
=> fix issue where preview would be shown unexpectedly when quickly selecting then unselecting a file

Files/UserControls/DataGridHeader.xaml
=> Made slight adjustments to data grid header to match design spec

Files/DataModels/NavigationControlItems/DriveItem.cs
- Added a null check on unit properties to avoid an exception when you have an unit that doesn't have properties (for example when you have an android connected without transferring data)
**Validation**
=> Added a null check to avoid an exception when an unit doesn't have properties

Files/MultilingualResources/Files.es-419.xlf
**Translated functions:**
Export settings
Choose a custom folder icon
Customization
=> Fix: Translation of some functions into Spanish

Files/MultilingualResources/Files.hu-HU.xlf
=> Updated Files.hu-HU.xlf

Files/ViewModels/MainPageViewModel.cs, Files/Views/MainPage.xaml.cs
- Closes #6214
- Set current tab header as window title so it appears on the taskbar
**Validation**
=> Set window title to be the same as the selected tab name

Files/MultilingualResources/Files.zh-Hant.xlf
- Translated new strings
- Fixed several translation problems
**Validation**
=> Update Chinese Traditional Translations

README.md
N/A
Specifies target OS.
**Validation**
N/A
N/A
N/A
=> Add the target OS to the readme file

Files/MultilingualResources/Files.fr-FR.xlf
I updated some french translations
=> Update French Translations

Files/MultilingualResources/Files.en-GB.xlf
Removed incorrect automatic translations and translated missing translations
As above, Updating EN-GB translation
**Validation**
- [Yes ] Built and ran the app
- [ Yes] Tested the changes for accessibility
=> Update EN-GB translation

Files/MultilingualResources/Files.hr-HR.xlf
Updated Croatian language with new Compatibility strings
=> Updated Croatian translations

Files/MultilingualResources/Files.pt-BR.xlf
Fixed many old strings, translated all missed ones and solved all warnings.
=> Updated PT-BR

Files/Dialogs/SettingsDialog.xaml, Files/Dialogs/SettingsDialog.xaml.cs, Files/Files.csproj
=> Updated the nav view style on the setting dialog

Files/Views/CustomFolderIcons.xaml
Hello there! Please let me know any way that I can improve the quality of this pull request; it is my first Github pull request. 
Thanks guys for the opportunity to contribute!
- Closes #6809
- Changed the WPF Grid control's Height and Width values from 16 to 32
**Validation**
Before changes:
After changes:
=> Increased Icon Size for Folder Properties Customization

Files/ViewModels/StatusCenterViewModel.cs
- Closes #6367 
- Reversed the order in which tasks are added to the Ongoing tasks flyout.
**Validation**
=> Made active ongoing task appear on the top in Ongoing tasks flyout

Files/Filesystem/Drives.cs
- Closes #7026
- Added exception catching when loading drives thumbnails
**Validation**
=> Catch GetThumbnailAsync() exceptions

Files/UserControls/SidebarControl.xaml.cs, Files/Views/WidgetsPage.xaml.cs
Remove useless `String.ToString()` calls
=> Remove useless string.ToString()

Files/Filesystem/StorageItems/FtpStorageFolder.cs, Files/Views/ColumnShellPage.xaml.cs, Files/Views/ModernShellPage.xaml.cs
=> Remove empty statements

Files/UserControls/Selection/RectangleSelection.cs, Files/ViewModels/NavToolbarViewModel.cs
=> Use EventArgs.Empty when applicable

Files.Launcher/Helpers/ShellNewMenuHelper.cs
=> Reuse key.GetValueNames

Files/DataModels/SidebarPinnedModel.cs, Files/DataModels/TerminalFileModel.cs, Files/Filesystem/FilesystemOperations/ShellFilesystemOperations.cs, Files/UserControls/SidebarControl.xaml.cs, Files/ViewModels/NavToolbarViewModel.cs, Files/ViewModels/SettingsViewModels/PreferencesViewModel.cs, Files/Views/LayoutModes/ColumnViewBase.xaml.cs, Files/Views/LayoutModes/ColumnViewBrowser.xaml.cs, Files/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs, Files/Views/LayoutModes/GridViewBrowser.xaml.cs
- Replace `Count()` with `Count` when applicable
- Remove useless `Cast<T>`
- Replace `FirstOrDefault() == null` with `Any()`
=> Optimize some LINQ calls

Files.Launcher/Win32API.cs, Files/Helpers/RecycleBinHelpers.cs
=> Regex optimizations

Files/Filesystem/FilesystemOperations/Helpers/FilesystemHelpers.cs
=> Replace regex with string operations

Files/Views/ColumnShellPage.xaml, Files/Views/ColumnShellPage.xaml.cs, Files/Views/ModernShellPage.xaml, Files/Views/ModernShellPage.xaml.cs
Hello, this is my very first pull request so please let me know if I can improve it in any way. I think the issue has been solved correctly.
- Closes #6867 
- Added a keyboard shortcut (Ctrl+H) which shows/hides hidden files
**Validation**
=> Fix #6867: added keyboard shortcut (Ctrl+H) to show/hide hidden files

Files/App.xaml.cs, Files/Views/MainPage.xaml.cs
- Resolves issue discussed in discord server where the sidebar items are only loaded after the main page has loaded, which causes an unnecessary delay. 
**Validation**
Tested in release mode and didn't see much of a difference. 
=> Remove delay of loading sidebar items and other services on startup

Files/MultilingualResources/Files.ko-KR.xlf
None
As above, I updated and improve ko-Kr.xlf ;)
This is my first pull request... So I hope it would be fine :D
=> Update and improve ko-KR

Files.Launcher/Win32API.cs, Files.Package/Files.Package.wapproj, Files/Files.csproj, Files/MultilingualResources/Files.af.xlf, Files/Strings/af/Resources.resw
Afrikaans Translation
- Added Afrikaans translation
**Validation**
=> Afrikaans Translation

Files/Helpers/AppServiceConnectionHelper.cs
Follow-up of https://github.com/files-community/Files/pull/7110
=> Use ReadAsync in NamedPipeServerStream

Files/Services/Implementation/AppearanceSettingsService.cs, Files/Services/Implementation/MultitaskingSettingsService.cs, Files/Services/Implementation/PreferencesSettingsService.cs, Files/Services/Implementation/PreviewPaneSettingsService.cs, Files/Services/Implementation/WidgetsSettingsService.cs
- Fixes app center reports of settings.
**Validation**
=> Fix bad setting names reported by AppCenter

Files/Helpers/NativeFileOperationsHelper.cs, Files/Views/ModernShellPage.xaml.cs
- Fixes 3469205863u
- Fixes 1360953327u
- As it was pointed out in #7110, PR changes ReadStringFromFile to not rely on the assumption that 1byte = 1character
**Validation**
=> Fix ReadStringFromFile

Files.Launcher/DeviceWatcher.cs
Addresses the issue pointed out in this comment by @gave92 here: https://github.com/files-community/Files/pull/6901#issuecomment-986070191
**Validation**
=> Address DeviceWatcher not getting properties for device events correctly

Files.Launcher/DeviceWatcher.cs, Files/Filesystem/StorageItems/SystemStorageFile.cs, Files/Helpers/AppServiceConnectionHelper.cs, Files/Helpers/ContextFlyoutItemHelper.cs
- Closes #7206
- Fixed an issue preventing files to be copied to MTP/phone storage
- Disable new file context menu in MTP, matching the toolbar "new" button behavior
**Validation**
=> Workaround for copying to MTP

Files.Package/Package.appxmanifest, Files/Files.csproj
- Updated to WinUI pre release to fix store build
=> Bumped version number to 2.0.42

Files/MultilingualResources/Files.el.xlf
- Added...
- Fixed...
**Validation**
=> Update Greek Translation

Files/MultilingualResources/Files.de-DE.xlf
none
I reviewed the German translation file (`Files/MultilingualResources/Files.de-DE.xlf`).
* looked for all occurences of `state="needs-review-translation"` in the file  and reviewed them, editing if necessary
* deleted all `<note>` entries, when no longer relevant
* Added translations to all occurences of `state="new"`
**Validation**
- ~Built and ran the app~
- ~Tested the changes for accessibility~
=> Update German Translation

README.md
*README.md is one of the most important files on GitHub<br>and needs to approve this PR and repair immediately.*
- a5c7331563a7ff937d63aa0a8312542007a4b3dc: Fix broken links due to path changes made by commit: 14d4aab.
- fb059316bb89f53ba6b2892fda572bfe27a118ef: Change the app icon path from absolute path to relative path.
Added
```
src/*
```
**Validation**
Before:
After:
=> [very important!!!!] Fix image path in README.md

src/Files/Strings/en-US/Resources.resw, src/Files/UserControls/Settings/SettingsBlockControl.xaml, src/Files/UserControls/Settings/SettingsBlockControl.xaml.cs, src/Files/UserControls/Settings/SettingsDisplayControl.xaml, src/Files/Views/SettingsPages/About.xaml, src/Files/Views/SettingsPages/About.xaml.cs, src/Files/Views/SettingsPages/Experimental.xaml, src/Files/Views/SettingsPages/Preferences.xaml
- Closes #7260
- The click area of actionable settings' blocks has been extended
**Validation**
=> Extended click area to whole settings' block

src/Files/Views/PaneHolderPage.xaml.cs
Hey there! This is my first PR so let me know of any improvements I can make! Thanks for the patience! 😄 
- Closes #7331 
- Use current navigation args instead of previously stored selection in left pane when possible
**Validation**
=> Update tab titles using current navigation arguments

src/Files/Helpers/FilePropertiesHelpers.cs, src/Files/ResourceDictionaries/PropertiesStyles.xaml, src/Files/Strings/en-US/Resources.resw, src/Files/Views/Pages/Properties.xaml, src/Files/Views/Pages/Properties.xaml.cs, src/Files/Views/Pages/PropertiesGeneral.xaml, src/Files/Views/Pages/PropertiesGeneral.xaml.cs, src/Files/Views/Pages/PropertiesShortcut.xaml
- Added new layout to the general tab in the properties window
**Validation**
=> Redesigned general tab in properties window

src/Files.Launcher/Helpers/ShellFolderHelpers.cs, src/Files.Launcher/MessageHandlers/FileOperationsHandler.cs, src/Files/Filesystem/FilesystemOperations/Helpers/FilesystemHelpers.cs, src/Files/Filesystem/StorageEnumerators/Win32StorageEnumerator.cs, src/Files/Helpers/ItemListDisplayHelpers/SortingHelper.cs
- Closes #7284
- Fixes an issue for which shortcuts (.lnk) to a folder open in explorer
**Validation**
=> Fix folder shortcuts opening in explorer

src/Common/CloudProvider.cs, src/Files.Launcher/Helpers/CloudDrivesDetector.cs
- Closes #4420 
- Make Nextcloud appear under cloud drives section
**Validation**
=> Add support for nextcloud

src/Common/CloudProvider.cs, src/Files.Launcher/Helpers/CloudDrivesDetector.cs
- Closes #6940
- Added support for Yandex cloud drive
**Validation**
=> Detect Yandex.Disk cloud drive

src/Files/Extensions/DateTimeExtensions.cs, src/Files/ViewModels/NavToolbarViewModel.cs
- Closes #7412
- Closes #7396
**Validation**
=> Fix for issues #7412, #7396

src/Files/Dialogs/SettingsDialog.xaml, src/Files/Strings/en-US/Resources.resw, src/Files/ViewModels/SelectedItemsPropertiesViewModel.cs, src/Files/Views/Pages/PropertiesGeneral.xaml
=> Properties improvements

tests/Files.InteractionTests/SessionManager.cs
- Running interaction tests locally would not work as expected
- Update app id in SessionManager
**Validation**
=> Update app id for interaction tests

src/Files.Launcher/Program.cs, src/Files.Launcher/Win32API.cs
- Fixes an issue for which browsing Control Panel always open new windows
**WARNING: obscure code ahead**
- Check if there is an open ShellWindow, if so navigate it to new path.
**Validation**
=> [Default explorer] Open control panel in existing window

src/Files.Launcher/Win32API.cs
Just noticed that in #7456 I've introduced a lot of unnecessary interfaces definitions.
- Remove unnecessasry definitions, code should behave exactly the same
**Validation**
=> Remove unnecessary definitions from control panel fix

src/Files/Strings/zh-Hans/Resources.resw, src/Files/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs
- Closes #7471
- Closes (maybe) #7477 
- Do not set negative MaxWidth
**Validation**
=> Check negative textbox width

src/Files/Views/LayoutModes/ColumnViewBase.xaml.cs, src/Files/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs, src/Files/Views/LayoutModes/GridViewBrowser.xaml.cs
- Closes #7442
- Check for null parent when setting ColumnSpan
- Restored a change from #7425 lost when merging main
**Validation**
=> Fix crash if navigation is triggered while renaming

src/Files/Views/LayoutModes/ColumnViewBase.xaml.cs
=> Open new columns in the column layout on a single click

src/Files/Helpers/ItemListDisplayHelpers/BulkConcurrentObservableCollection.cs, src/Files/Views/PaneHolderPage.xaml.cs
- Closes Appcenter issue [1773535228u](https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/1773535228u/overview)
- Tentative fix for Appcenter issue [759876355u](https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/1773535228u/overview)
- Fix crash when deleting items from bin & bin is grouped (1773535228u)
=> Fix crash when deleting items from bin & bin is grouped

src/Files/MultilingualResources/Files.de-DE.xlf, src/Files/MultilingualResources/Files.it-IT.xlf, src/Files/MultilingualResources/Files.nl-NL.xlf, src/Files/Strings/de-DE/Resources.resw, src/Files/Strings/it-IT/Resources.resw, src/Files/Strings/nl-NL/Resources.resw, src/Files/Strings/pt-BR/Resources.resw
- Fixed an issue in de-DE xlf causing crash when displaying copy dialog
- Fixed a couple of wrong strings in it-IT
- Also updated resw files
**Validation**
=> Fix german translations causing crash

src/Files/ViewModels/ItemViewModel.cs
- Closes #7474
- Use safe wrapper when fetching synstatus properties
**Validation**
=> Fix crash when checking cloud sync status

src/Files/Views/PaneHolderPage.xaml
- Resolves https://github.com/files-community/Files/issues/6883
- Changed left panel width from `1.5*` to `1.0*`
- Fixed...
**Validation**
=> Changed default dual pane width to 50%

src/Files/UserControls/InnerNavigationToolbar.xaml
- Closes #7581 
- Fixed Inconsistency between file creation flyouts
**Validation**
=> Fixed Inconsistency between file creation flyouts

src/Files/MultilingualResources/Files.es-419.xlf
Some of the latest files features have been translated into Latin American Spanish.
=> Update Spanish translations

src/Files.Launcher/global.json
Reverts files-community/Files#7656
=> Revert "Add global.json to force sdk 6.0.100"

src/Files/MultilingualResources/Files.pl-PL.xlf
Add missing Polish translations
**Validation**
=> Update translations [pl-PL]

src/Files/UserControls/InnerNavigationToolbar.xaml
- Added...
- Fixed...
**Validation**
=> Fixed string resource for properties button

src/Files/UserControls/InnerNavigationToolbar.xaml
- Added...
- Fixed...
**Validation**
=> Added access keys to the toolbar

src/Common/CloudProvider.cs, src/Files.Launcher/Helpers/CloudDrivesDetector.cs
- Added support for [Jottacloud](https://jottacloud.com/) cloud drive.
**Validation**
=> Detect Jottacloud cloud drive

src/Files/MultilingualResources/Files.vi.xlf
- Update translations for Vietnamese (vi).
**Validation**
=> Update Vietnamese translation

src/Files/Constants.cs
Reduced minimum sidebar width
Resolved / Related Issues
- Related #7385
Details of Changes
- Changed the constant responsible for the minimum width of the sidebar
Validation
=> Reduced minimum sidebar width from 250 to 180

src/Files/UserControls/Widgets/BundlesWidget.xaml
=> Fixed an issue preventing users from creating multiple bundles

src/BackgroundTasks/BackgroundTasks.csproj, src/Files.Launcher/Files.Launcher.csproj, src/Files.Package/Files.Package.wapproj, src/Files/Files.csproj
- Closes #7773...
**Validation**
=> Added support for Segoe UI Variable on Windows 11

src/Files/MultilingualResources/Files.lv-LV.xlf
- Added...
- Fixed...
**Validation**
=> Latvian translation updated

src/Files/MultilingualResources/Files.ar.xlf
- Fixed a bug that makes the project to fail to compile.
**Validation**
=> Fixed an issue that avoid compiling the project

src/Files/Helpers/JumpListManager.cs
- Closes #1468
- Fixed issue where JumpListItem would remain in the JumpList after being deleted. 
**Validation**
=> Fixed an issue where folders weren't removed from the JumpList

src/Files.Launcher/Helpers/CloudDrivesDetector.cs
- Closes #7687
- Related #7401
- Fixed Nextcloud detection #7687
- Using name of folder instead of CloudProvider 'Nextcloud'
**Validation**
=> Fixed Nextcloud detection

src/Files/ResourceDictionaries/TabView_themeresources.xaml
- Closes #5492
- Tweaked the padding of the scroll buttons.
**Validation**
=> Adjusted padding of TabViewScrollButtons

src/Files/UserControls/ColoredIcon.xaml
- Added...
- Fixed...
**Validation**
=> Swapped grid for canvas

src/Files/UserControls/StatusBarControl.xaml
- Added...
- Fixed...
**Validation**
=> Removed extra items from the status bar visual tree

src/Files/UserControls/Selection/RectangleSelection_ListViewBase.cs
- Added...
- Fixed...
**Validation**
=> Switched to SizeChanged for better performance

src/Files/UserControls/InnerNavigationToolbar.xaml, src/Files/UserControls/NavigationToolbar.xaml, src/Files/Views/PaneHolderPage.xaml
- Removed unused resource from inner navigation toolbar
- Removed extra control from pane holder page
- Removed extra control from navigation toolbar
=> Removed extra controls from visual tree

src/Files/MultilingualResources/Files.zh-Hant.xlf
- Completed traditional Chinese translation
- Fixed some previously inaccurate translations
=> Updated and completed traditional Chinese translation (Files.zh-Hant.xlf)

src/Files/MultilingualResources/Files.zh-Hant.xlf
Reverts files-community/Files#7955 as the translation states weren't set correctly
=> Revert "Updated and completed traditional Chinese translation (Files.zh-Hant.xlf)"

src/Files/UserControls/PathBreadcrumb.xaml
- Added...
- Fixed...
**Validation**
=> Improved visual tree for breadcrumb control

src/Files/MultilingualResources/Files.ko-KR.xlf
In this work, I literally 'add and fix' the korean translation.
- Added: I added new translation string which are about added new.
- Fixed... And also I fixed some string for more naturally and also tried to provide better UX than before.
**Validation**
I couldn't test it. Because I don't have way to how can I test translated stuff 😓  But I almost sure - and hope - it will work well.
I hope this PR would be helpful for Files! Thanks for your work :)
=> Translated ko-kr

src/Files/Views/MainPage.xaml
=> Added support for expanding the preview pane further than 400px

src/Files/MultilingualResources/Files.zh-Hant.xlf
- Updated traditional Chinese translation Files.zh-Hant.xlf
- Fixed some previously inaccurate translations
- Set the state to translated
=> Updated Traditional Chinese Files.zh-Hant.xlf

src/Files/App.xaml, src/Files/Themes/Acrylic.xaml, src/Files/Themes/Black Pixel.xaml, src/Files/Themes/Glass.xaml, src/Files/Themes/Mica Imitation.xaml, src/Files/UserControls/PreviewPane.xaml, src/Files/UserControls/StatusBarControl.xaml, src/Files/UserControls/Widgets/RecentFilesWidget.xaml, src/Files/Views/ModernShellPage.xaml, src/Files/Views/PaneHolderPage.xaml, src/Files/Views/SettingsPages/Appearance.xaml
Removed resources that weren't doing anything.
**Validation**
=> Removed extra resources to improve performance 

src/Files/UserControls/NavigationToolbar.xaml
- Added...
- Fixed...
**Validation**
=> Fixed an issue where the status center badge was always visible

src/Files/Dialogs/FilesystemOperationDialog.xaml.cs
=> Fixed a crash when opening the conflicts dialog

src/Files/ViewModels/NavToolbarViewModel.cs
=> Fixed a crash when clicking pathbox items

src/Files/Views/LayoutModes/ColumnViewBrowser.xaml.cs
- Closes AppCenter 3772455981u
**Validation**
=> Fixed back button in columns view (again)

src/Files/Helpers/ContextFlyoutItemHelper.cs, src/Files/UserControls/InnerNavigationToolbar.xaml, src/Files/ViewModels/NavToolbarViewModel.cs
=> Fix weird open in terminal label

src/Files/MultilingualResources/Files.vi.xlf
=> Update vi-VN translations

src/Files/Themes/Acrylic.xaml, src/Files/Themes/Blue Acrylic.xaml, src/Files/Themes/Glass.xaml, src/Files/Themes/Mica Imitation.xaml
- Added...
- Fixed...
**Validation**
=> Fixed acrylic themes

src/Files/Helpers/MultitaskingTabsHelpers.cs, src/Files/Strings/en-US/Resources.resw, src/Files/UserControls/MultitaskingControl/BaseMultitaskingControl.cs, src/Files/UserControls/MultitaskingControl/HorizontalMultitaskingControl.xaml, src/Files/UserControls/MultitaskingControl/HorizontalMultitaskingControl.xaml.cs
- Related #8015 
Changed "Close others" to "Close other tabs" in code and english resources.
**Validation**
=> Change "Close others" to "Close other tabs"

src/Files/Filesystem/ListedItem.cs
Fix error in LitedItem. The unsubscribe use the new value instead the old value.
=> Fix ListedItem unsubscribe

src/Files/MultilingualResources/Files.pl-PL.xlf
- Updated Polish language
**Validation**
=> Update Polish language

src/Files/Views/Pages/PropertiesGeneral.xaml.cs
- Closes #7918
- Closes #7958
- Fixed an issue causing crash when clicking OK button in Combined properties
**Validation**
=> Fix crash when closing combined properties

src/Files/UserControls/PathBreadcrumb.xaml
- Closes #8096...
- Added...
- Fixed...
**Validation**
=> Fixed breadcrumb hit target

src/Files/Files.csproj
- Added...
- Fixed...
**Validation**
=> Updated WinUI

src/Files/MultilingualResources/Files.it-IT.xlf
https://github.com/files-community/Files/issues/8134
Arround line 970 changed risolutione with risouluzione. Probably a typing error
**Validation**
=> Italian Translation minor  fix

src/Files/MultilingualResources/Files.de-DE.xlf
I saw this typo in the app and couldn't leave it like that
No
- Fix typo
**Validation**
=> Fix typo in de-DE

src/Files/MultilingualResources/Files.ja-JP.xlf
- Added Japanese translations for recently added texts. ( FYI: Recent contributors to Japanese translations @inductor @akihironagai  )
**Validation**
=> Update translations in `Files.ja-JP.xlf`.

src/Files/MultilingualResources/Files.id-ID.xlf
- Added some words 
- And changed a few typo
=> Update lang id-ID

src/Files/DataModels/SidebarPinnedModel.cs
- Added...
- Fixed...
**Validation**
=> Fixed usage of home string

src/Files/UserControls/InnerNavigationToolbar.xaml
- Added...
- Fixed...
**Validation**
=> Removed alt + d access key to fix conflict with address bar

src/Files/ViewModels/ItemViewModel.cs
- Fixes a bug introduced in #7900 where the ProcessOperationQueue would not be canceled when switching directory or refreshing.
This should fix the warning/error seen in recent debug logs:
`2022-02-05 09:53:16.3558|WARN|ApplyFilesAndFoldersChangesAsync|The application called an interface that was marshalled for a different thread. (Exception from HRESULT: 0x8001010E)`
**Validation**
=> Correctly cancel ProcessOperationQueue

src/Files/Helpers/ExternalResourcesHelper.cs
Adds the foundation for adding an edit and delete option for imported themes
- Added...
- Fixed...
**Validation**
=> Added IsImportedTheme property

src/Files/Services/Implementation/PreferencesSettingsService.cs
=> Changed default value for showing files starting with '.'

src/Files/MultilingualResources/Files.id-ID.xlf
Added some choice words and fixed Indonesian errors.
Menambahkan beberapa kata pilihan dan memperbaiki kesalahan bahasa Indonesia.
>English
**Information in English**
- Added words in the language
- Fixed typo and Incorrect language
**Validation**
>Indonesia
**Informasi dalam Indonesia**
**Rincian Perubahan**
- Menambahkan kata-kata dalam bahasa
- Memperbaiki kesalahan ketik dan bahasa yang salah
**Validasi**
Bagaimana Anda menguji perubahan ini?
=> Updated Indonesia Lang

src/Files/ViewModels/FolderSettingsViewModel.cs, src/Files/ViewModels/StatusCenterViewModel.cs
My previous PR #8115 prevented command calls from sending a new instance on each call by initializing them in the constructor. However, I forgot some initializations in classes with multiple constructors. This pr fixes that.
**Validation**
=> Fixed commands refactor code

src/Files.Package/Package.appxmanifest
- Added...
- Fixed...
**Validation**
=> Update Package.appxmanifest 2.1.13

src/Files/Views/ColumnShellPage.xaml.cs, src/Files/Views/ModernShellPage.xaml.cs
- Closes #5607
- Added shortcut key of ctrl + \`  in PreviewKeyDown as KeyboardAccelerator events don't detect the VirtualKey for `
**Validation**
=> Added a shortcut to open folders in Terminal

src/Files/MultilingualResources/Files.es-ES.xlf
- Missing Spanish translations
- Translated missing strings to Spanish
**Validation**
_None_
=> Updated es-ES translation

src/Files/Strings/en-GB/Resources.resw, src/Files/Strings/en-US/Resources.resw
Closes #8221 
- I changed to capital letter in en-GB and en-US.
**Validation**
=> Update capitalization in nav pane en-GB & en-US

src/Files/Views/Pages/Properties.xaml
- Closes #7685
- Added...
- Fixed...
**Validation**
=> Fixed crash that would occur when scrolling down in the properties window

src/Files/MultilingualResources/Files.zh-Hant.xlf
- Fixed translation error in Files.zh-Hant.xlf
=> Fix translation error in Files.zh-Hant.xlf

src/Files/Filesystem/FilesystemOperations/ShellFilesystemOperations.cs
- Closes [2315712683u](https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/2315712683u/overview)
- Restore fix for #5771 mistakenly removed in #8046 
**Validation**
=> Fix crash when deleting files

src/Files/Helpers/RecycleBinHelpers.cs
- Closes #8432 
- The button to confirm the empty recycle bin action is now highlighted. 
**Validation**
=> Auto select primary button in empty recycle bin dialog

src/Files/MultilingualResources/Files.fr-FR.xlf, src/Files/Strings/fr-FR/Resources.resw
Revert changes from @Gurgarath
=> Revert changes

src/Files/Files.csproj, src/Files/IsExternalInit.cs
This pr enables the "init" and "record" functionality in C#.
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/init
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/record
**Validation**
=> Add c# functionality "init" and "record"

src/Files/BaseLayout.cs, src/Files/Filesystem/FolderSizeProvider.cs
- Added...
- Fixed...
**Validation**
=> Properly dispose event in FolderSizeProvider

README.md
**Related Issues**
Items related issues by this PR.
- Related #8467
Update readme with all required Individual components to install with VIsual studio to be able to build this project
**Validation**
=> Added required individual components of VS to readme

src/Files.Uwp/MultilingualResources/Files.ru-RU.xlf
- Improves Russian localization
Details of Changes
- Added ru-Ru translations for units with 'new' state
- Reviewed ru-Ru translations for units with 'needs-review-translation' state
=> Updated ru-RU

src/Files.Uwp/MultilingualResources/Files.ko-KR.xlf
- Updates Korean (ko-KR) translations
- Add translations for untranslated texts marked as 'new'
- Proofread existing translations
- Also edit some translations to match Korean texts in Windows Explorer
=> Updated ko-KR

src/Files.Uwp/ViewModels/ColumnsViewModel.cs
- Added...
- Fixed...
**Validation**
=> Removed behavior of auto resizing columns

src/Files.Launcher/MessageHandlers/QuickLookHandler.cs, src/Files.Launcher/Program.cs, src/Files.Shared/Extensions/SafetyExtensions.cs, src/Files.Shared/ILogger.cs, src/Files.Shared/Logger.cs, src/Files.Uwp/App.xaml.cs, src/Files.Uwp/Filesystem/CloudDrivesManager.cs, src/Files.Uwp/Filesystem/Drives.cs, src/Files.Uwp/Filesystem/NetworkDrivesManager.cs
This PR adds an ILogger interface to replace direct calls to Shared.Logger. This is done with a view to getting a better backend, which is currently under construction. I take this opportunity to improve the style of Logger. 
**Validation**
=> Added ILogger interface

src/Files.Uwp/UserControls/InnerNavigationToolbar.xaml
- Closes #8466 
- Fixed close icon in context menu
**Validation**
=> Fixed the close pane icon

src/Files.Uwp/Views/LayoutModes/ColumnViewBase.xaml, src/Files.Uwp/Views/LayoutModes/ColumnViewBase.xaml.cs, src/Files.Uwp/Views/LayoutModes/DetailsLayoutBrowser.xaml, src/Files.Uwp/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs, src/Files.Uwp/Views/LayoutModes/GridViewBrowser.xaml, src/Files.Uwp/Views/LayoutModes/GridViewBrowser.xaml.cs
=> Added pull to refresh gesture

builds/azure-pipelines-release.yml
- Added...
- Fixed...
**Validation**
=> Fixed release pipeline

src/Files.Uwp/UserControls/SidebarControl.xaml
=> Reduced sidebar items height to match default ListViewItem

src/Files.Uwp/UserControls/PathBreadcrumb.xaml
- Closes #8755
- Adjusted padding on path bar items to match existing search padding.
**Validation**
=> Increased padding on Pathbar

src/Files.Uwp/UserControls/NavigationToolbar.xaml
=> Added chevron to pathbar to match design spec

src/Files.Launcher/MessageHandlers/Win32MessageHandler.cs, src/Files.OpenDialog/CustomOpenDialog/CustomOpenDialog.vcxproj, src/Files.OpenDialog/FilesLauncher/FilesLauncher.vcxproj
- Closes #8749
- Some paths didn't have quotes around
**Validation**
=> Fix default & build in case of usernames with spaces

src/Files.Launcher/MessageHandlers/Win32MessageHandler.cs, src/Files.OpenDialog/CustomOpenDialog/CustomOpenDialog.vcxproj, src/Files.OpenDialog/FilesLauncher/FilesLauncher.vcxproj
Backported #8779 to 2.1.24 branch
=> [Backport] - Fix default & build in case of usernames with spaces

src/Files.Uwp/Themes/Acrylic.xaml, src/Files.Uwp/Themes/Glass.xaml
- Added...
- Fixed...
**Validation**
=> Updated themes to work with new tab design

src/Files.Uwp/ViewModels/ItemViewModel.cs
- Closes #7428
- Fixed constant refresh in Box folder -> do not watch for directory changes in Box Drive (same as network folders)
- Fixed subfolders in Box appearing empty -> change the check for the Box folder path to include subfolders
**Validation**
=> Fix box drive

src/Files.Uwp/App.xaml, src/Files.Uwp/UserControls/SidebarControl.xaml, src/Files.Uwp/ViewModels/SettingsViewModels/AppearanceViewModel.cs
- Added...
- Fixed...
**Validation**
=> Added compact mode support to the sidebar

src/Files.Uwp/Helpers/FilePropertiesHelpers.cs
Items resolved/related issues by this PR.
- Closes #6066
- Added Proper Theme Handling for the Properties Dialog
(This respects system and app theme settings properly)
**Validation**
=> Fixed an issue where the properties window used the wrong theme

src/Files.Uwp/ViewModels/Previews/CodePreviewViewModel.cs
- Closes #8824
- Use case insensitive comparison for extension match
**Validation**
=> Fix crash when previewing XML files

src/Files.Uwp/Views/ModernShellPage.xaml.cs
=> Fix Ctrl+L on homepage

src/Files.Uwp/ViewModels/NavToolbarViewModel.cs
- Closes #8859
- Adds null check to avoid throwing NRE when clicking navigation path from home
**Validation**
=> Avoid throwing NRE when getting path suggestions on Home

src/Files.Uwp/IShellPage.cs, src/Files.Uwp/Views/LayoutModes/ColumnViewBase.xaml.cs, src/Files.Uwp/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs, src/Files.Uwp/Views/LayoutModes/GridViewBrowser.xaml.cs
- Related #2355
- Navigate to parent folder when double clicking on a folder empty space
**Validation**
=> Add double click to go up gesture

src/Files.Uwp/DataModels/NavigationControlItems/LocationItem.cs, src/Files.Uwp/DataModels/SidebarPinnedModel.cs, src/Files.Uwp/UserControls/SidebarControl.xaml, src/Files.Uwp/UserControls/SidebarControl.xaml.cs
- Closes #4128
**Validation**
https://user-images.githubusercontent.com/9673091/162537439-a5acfc1c-8508-4e65-b16b-083093077e7c.mp4
=> Remember sidebar items state when sidebar is collapsed/extended

src/Files.Uwp/ViewModels/ItemViewModel.cs
- Fix refresh in mapped network drives
**Validation**
=> Fix refresh in mapped network drives

src/Files.Uwp/App.xaml.cs, src/Files.Uwp/Helpers/ExternalResourcesHelper.cs, src/Files.Uwp/Helpers/ThemeHelper.cs, src/Files.Uwp/ViewModels/SettingsViewModels/AppearanceViewModel.cs
- Closes [#621427454u](https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/621427454u/overview )
**Validation**
=> Fix crash when setting compact style on app start

src/Files.Uwp/Filesystem/StorageItems/SystemStorageFile.cs, src/Files.Uwp/Filesystem/StorageItems/SystemStorageFolder.cs, src/Files.Uwp/Filesystem/StorageItems/ZipStorageFile.cs, src/Files.Uwp/Filesystem/StorageItems/ZipStorageFolder.cs
Improve the style of 4 files
**Validation**
=> Improves storage (next)

src/Files.Uwp/Views/LayoutModes/DetailsLayoutBrowser.xaml
- Use correct resource for "show item type column" menu item in Details view
**Validation**
=> Use correct resource for "show item type column" menu item in Details view

src/Files.Uwp/MultilingualResources/Files.fr-FR.xlf
FR-Fr translated 100%.
**Validation**
=> Fr-fr update

src/Files.Uwp/BaseLayout.cs, src/Files.Uwp/Files.Uwp.csproj, src/Files.Uwp/Helpers/NavigationHelpers.cs, src/Files.Uwp/Helpers/UIFilesystemHelpers.cs, src/Files.Uwp/IAddressToolbar.cs, src/Files.Uwp/IShellPage.cs, src/Files.Uwp/UserControls/AddressToolbar.xaml, src/Files.Uwp/UserControls/AddressToolbar.xaml.cs, src/Files.Uwp/UserControls/InnerNavigationToolbar.xaml.cs, src/Files.Uwp/UserControls/PathBreadcrumb.xaml.cs, src/Files.Uwp/ViewModels/NavToolbarViewModel.cs, src/Files.Uwp/ViewModels/ToolbarViewModel.cs, src/Files.Uwp/Views/ColumnShellPage.xaml.cs, src/Files.Uwp/Views/LayoutModes/ColumnViewBase.xaml.cs, src/Files.Uwp/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs, src/Files.Uwp/Views/LayoutModes/GridViewBrowser.xaml.cs, src/Files.Uwp/Views/MainPage.xaml, src/Files.Uwp/Views/MainPage.xaml.cs, src/Files.Uwp/Views/ModernShellPage.xaml.cs, src/Files.Uwp/Views/WidgetsPage.xaml.cs
- Closes #5470
- Renames NavigationToolbar user control to AddressToolbar.
**Validation**
=> Codebase: Rename NavigationToolbar to AddressToolbar

src/Files.Launcher/MessageHandlers/FileTagsHandler.cs, src/Files.Uwp/Filesystem/FileTagsHelper.cs, src/Files.Uwp/Helpers/NativeFileOperationsHelper.cs
- Closes #8965
- Restores file date modified after setting file tag
**Validation**
=> Do not change file date modified when setting tag

src/Files.Uwp/BaseLayout.cs, src/Files.Uwp/Filesystem/ListedItem.cs, src/Files.Uwp/Filesystem/StorageItems/FtpStorageFile.cs, src/Files.Uwp/Filesystem/StorageItems/FtpStorageFolder.cs, src/Files.Uwp/Helpers/UIFilesystemHelpers.cs
Improves style in FtpStorage. The ListedItem dependency has been removed to prepare for the move to the backend.
**Validation**
=> Refactor FtpStorage

src/Files.Uwp/Filesystem/StorageHistory/Helpers/StorageHistoryHelpers.cs, src/Files.Uwp/Filesystem/StorageHistory/IStorageHistory.cs, src/Files.Uwp/Filesystem/StorageHistory/StorageHistory.cs, src/Files.Uwp/Filesystem/StorageHistory/StorageHistoryWrapper.cs
Refactor Storage History
Improves styles of files.
**Validation**
=> Refactor Storage History

src/Files.Launcher/MessageHandlers/LibrariesHandler.cs, src/Files.Uwp/Serialization/Implementation/CachingJsonSettingsDatabase.cs, src/Files.Uwp/Serialization/Implementation/DefaultJsonSettingsDatabase.cs, src/Files.Uwp/ViewModels/SidebarViewModel.cs
- Closes #8968
- Refresh settings cache when importing settings
- Applies compact style option without restart
**Validation**
=> Fixes an issue for which settings are not imported

src/Files.Uwp/Strings/en-US/Resources.resw, src/Files.Uwp/ViewModels/SettingsViewModels/AboutViewModel.cs, src/Files.Uwp/Views/SettingsPages/About.xaml, src/Files.Uwp/Views/SettingsPages/Preferences.xaml
- Moved sponsor button out of the useful links section
- Organized file and folder settings section
**Validation**
=> Minor tweaks to settings dialog

src/Files.Uwp/MultilingualResources/Files.lv-LV.xlf
- Added...
- Fixed...
**Validation**
=> Updated LV translation

builds/azure-pipelines-release.yml, src/Files.Package/Package.appxmanifest
This will enable switching between release branches using the same pipeline.
=> Added parameters to the release pipeline

src/Files.FullTrust/MessageHandlers/Win32MessageHandler.cs
- Closes #9083
- Updated paths still pointing to "files.launcher" to "files.fulltrust"
**Validation**
=> Fix path for setting files as default

src/Files.Uwp/MultilingualResources/Files.pt-PT.xlf
- Updated PT-PT translations
**Validation**
=> PT-PT Update

src/Files.Uwp/Views/PaneHolderPage.xaml.cs
- Closes #7896
- Fixed setting focus of new pane from the ... menu. 
**Validation**
=> Automatically focus new pane

src/Files.Uwp/MultilingualResources/Files.fr-FR.xlf
Translates new texts into French. There are few texts, but the goal is to have complete coverage for v2.3.
=> Updated FR-fr

builds/azure-pipelines-release.yml, src/Files.Package/Package.appinstaller
Fixed an issue where the sideload version didn't work on offline devices
**Validation**
Tested locally
=> Removed check for update on app startup

src/Files.Uwp/MultilingualResources/Files.id-ID.xlf
=> Update Bahasa Indonesia

src/Files.FullTrust/Helpers/CloudDrivesDetector.cs
- Improve cloud drives detection speed. Cloud drives section appears faster on startup.
- Loop over Namespace subkeys instead of CLSID subkeys. There are a lot less keys under Namespace.
**Validation**
=> Improve cloud drives detection speed

src/Files.Uwp/ViewModels/ToolbarViewModel.cs
- Closes #9175
- Any forward slash input in path box is replaced with escaped backslashes.
**Validation**
=> Forward slash path input fix

src/Files.Uwp/Helpers/WidgetsHelpers.cs, src/Files.Uwp/UserControls/AddressToolbar.xaml, src/Files.Uwp/UserControls/Widgets/BundlesWidget.xaml.cs, src/Files.Uwp/UserControls/Widgets/DrivesWidget.xaml.cs, src/Files.Uwp/UserControls/Widgets/FolderWidget.xaml.cs, src/Files.Uwp/UserControls/Widgets/RecentFilesWidget.xaml.cs, src/Files.Uwp/ViewModels/Pages/YourHomeViewModel.cs, src/Files.Uwp/ViewModels/Widgets/IWidgetItemModel.cs, src/Files.Uwp/Views/ColumnShellPage.xaml.cs, src/Files.Uwp/Views/ModernShellPage.xaml.cs, src/Files.Uwp/Views/WidgetsPage.xaml.cs
- Closes #2242 
- Added ability to refresh the widgets using the Refresh toolbar button on homepage.
- Updates drives occupied space and recent items.
**Validation**
=> Enable refresh button on homepage

src/Files.Uwp/ServicesImplementation/SideloadUpdateService.cs
- Fixed issue with version check
**Validation**
=> Fix for sideload version check

src/Files.Uwp/ServicesImplementation/SideloadUpdateService.cs
- Added logging to sideload update service to help diagnose problems.
**Validation**
=> Added logging to sideload update service.

src/Files.Uwp/Properties/Default.rd.xml
- Closes #9242
- Fixed paths in the default.rd.xml file that may have been overlooked after project structure change.
**Validation**
=> Default.rd.xml Update

src/Files.Backend/Services/IUpdateService.cs, src/Files.Uwp/App.xaml.cs, src/Files.Uwp/ServicesImplementation/SideloadUpdateService.cs, src/Files.Uwp/ServicesImplementation/UpdateService.cs
- Changed packageManager update method. 
- Added download percentage property to the IUpdateService that can hopefully be used in future for UI.
**Validation**
=> Sideload UpdateService Download fix

src/Files.Uwp/ServicesImplementation/SideloadUpdateService.cs
- Added...
- Fixed...
**Validation**
=> Fixed URI download path.

src/Files.Uwp/Helpers/ContextFlyoutItemHelper.cs
- Closes #6333
- File extension was missing a "."
**Validation**
=> Fix show open as admin on CMD files

src/Files.Backend/Services/IUpdateService.cs, src/Files.Uwp/App.xaml.cs, src/Files.Uwp/ServicesImplementation/SideloadUpdateService.cs, src/Files.Uwp/ServicesImplementation/UpdateService.cs
- Changed update service to download available update in the background before showing the Update button. When the update has finished downloading the button shows to install the update.
- MSIX bundle is downloaded to the application folder.
**Validation**
=> Download update in background

src/Files.Uwp/Filesystem/StorageEnumerators/UniversalStorageEnumerator.cs
Fix conflict between #9163 and #9053 in the file UniversalStorageEnumerator.
The current main is broken.
=> Fix main branch

src/Files.Uwp/MultilingualResources/Files.af.xlf, src/Files.Uwp/MultilingualResources/Files.de-DE.xlf, src/Files.Uwp/MultilingualResources/Files.en-GB.xlf, src/Files.Uwp/MultilingualResources/Files.es-419.xlf, src/Files.Uwp/MultilingualResources/Files.es-ES.xlf, src/Files.Uwp/MultilingualResources/Files.nb-NO.xlf, src/Files.Uwp/MultilingualResources/Files.nl-NL.xlf, src/Files.Uwp/MultilingualResources/Files.sk-SK.xlf, src/Files.Uwp/MultilingualResources/Files.vi.xlf
Converstation from discord https://discord.com/channels/725513575971684472/725514946112127057/967812764682825738
Fixed some languages having the turn off set as default before uninstalling note since its not relevent anymore with the launcher
**Validation**
=> Removed "Uninstalling Files will not undo these changes" in some languages

README.md, crowdin.yml
- Added...
- Fixed...
**Validation**
=> Added Crowdin badge to readme

crowdin.yml
- Added...
- Fixed...
**Validation**
=> Added proper mapping for translations

src/Files.FullTrust/Program.cs
- Closes #9572
- Adds try/catch in TerminateProcess to fix the crash present in the log files of the linked issue.
**Validation**
=> Add exception handling to TerminateProcess

src/Files.Uwp/Helpers/WindowDecorationsHelper.cs
Fixed an issue where the minimize and maximize buttons were visible in the properties window for the sideload preview build.
**Validation**
=> Fixed properties window in sideload preview

src/Files.Uwp/Properties/Default.rd.xml
Trimmed rd.xml file to reduce binary size and improve startup time. We'll have to verify that everything works correctly in release mode.
=> Optimized RD file

src/Files.Uwp/Properties/Default.rd.xml
Optimized rd.xml file
**Validation**
=> Optimized rd.xml

src/Files.Package/Files.Package.wapproj, src/Files.Package/Package.appxmanifest, src/Files.Uwp/Files.Uwp.csproj
=> Release: v2.3.5

src/Files.Uwp/Helpers/CommonPaths.cs, src/Files.Uwp/Helpers/UIHelpers.cs, src/Files.Uwp/Views/Pages/PropertiesCustomization.xaml.cs
- Closes #9307
- Related #9306
- So far, we have assumed the OS directory to be "C:\"
- Fixed by using `%systemroot%` env path to get the OS root directory
**Validation**
=> Fix for hardcoded OS drives  

src/Files.Uwp/Filesystem/Search/FolderSearch.cs
- Closes #issue #9671
- Related #issue #9671
- Fixed - FolderSearch to look up for exact tags
**Validation**
=> Feature: Added support for multiple tag search

README.md, crowdin.yml
=> Fixed Crowdin config

src/Files.App/Files.App.csproj, src/Files.Package/Package.appxmanifest
Fixed an issue where app center wasn't copied to the build directory
**Validation**
=> Fix: Fixed appcenter reporting

src/Files.App/App.xaml
- Fixed an issue where the tab control had an extra shadow
Credits @chingucoding 
**Validation**
=> Fix: Fixed an issue where the tab control had an extra shadow

src/Files.App/Extensions/StringExtensions.cs
It turns out that `ResourceMap` is incredibly slow in a WinUI 3 app. On my computer it needs almost 15ms for a single `TryGetValue` call.
Add a cache to fix the performance issue.
=> Fix performance issue with WinUI 3

src/Files.App/Views/LayoutModes/ColumnViewBase.xaml, src/Files.App/Views/LayoutModes/ColumnViewBase.xaml.cs, src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml, src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs, src/Files.App/Views/LayoutModes/GridViewBrowser.xaml, src/Files.App/Views/LayoutModes/GridViewBrowser.xaml.cs
The refresh container was causing issues with scrolling and wasn't really being used so I decided to remove it.
**Validation**
=> Feature: Removed refresh container

src/Files.App/Shell/ShellFolderExtensions.cs, src/Files.App/Shell/Win32API.cs
- Fix two exceptions in shell
```
System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
at System.Convert.FromBase64String(String s)
at Files.App.Shell.ShellFolderExtensions.<>c.<GetStringAsPidl>b__5_0(String x)
at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)
at Files.App.Shell.ShellFolderExtensions.GetStringAsPidl(String pathOrPidl, PIDL& pidl)
at Files.App.Shell.Win32API.GetFileIconAndOverlay(String path, Int32 thumbnailSize, Boolean isFolder, Boolean getOverlay, …
```
=> Fix two exceptions in shell

src/Files.App/Files.App.csproj
Updated to 1.2-preview1
**Validation**
=> Feature: WinAppSDK 1.2-preview1
