files-community/Files

Files UWP/AddItem.xaml.cs, Files UWP/Filesystem/ItemViewModel.cs, Files UWP/Filesystem/ListedItem.cs, Files UWP/GenericFileBrowser.xaml.cs, Files UWP/Interacts/Interaction.cs, Files UWP/MainPage.xaml.cs, Files UWP/Navigation/NavigationActions.cs, Files UWP/Navigation/PhotoAlbumNavActions.cs, Files UWP/PhotoAlbum.xaml.cs
This PR aims to fix #6, fix #55.Filesystem changes will be automatically reflected. There are also some code refactors, some were necessary others are just good practices like reducing publicly accessible things.
Performance is good enough for a moderately sized folder. However it's not optimal. There are two broad changes that can be made to improve performance (not just for auto refresh but in general):
1) Expose files and folders as separate lists. UWP treats file and folder as very different types and provides separate api to work with them so it makes sense to split them in the code as well.
2) Use a different observable collection like dictionary or hashset. Of course these don't exist by default so we'll have to write one ourselves.
=> Auto refresh files and folders

Files UWP/Filesystem/ItemViewModel.cs, Files UWP/YourHome.xaml.cs
Changed the arrow icon between items in the PathBar
=> Fixed font size for the PathBar

Files UWP/App.xaml.cs, Files UWP/Enums/ThemeStyle.cs, Files UWP/Enums/TimeStyle.cs, Files UWP/FilesUWP.csproj, Files UWP/Filesystem/ListedItem.cs, Files UWP/SettingsPages/Personalization.xaml, Files UWP/SettingsPages/Personalization.xaml.cs
This also improves settings page to use Enums instead of string values for comparision.
Linked Issue #186
=> Implement Date Format on File Lists as settings

Files UWP/AddItem.xaml.cs, Files UWP/GenericFileBrowser.xaml, Files UWP/GenericFileBrowser.xaml.cs, Files UWP/Interacts/Interaction.cs
Adds "New folder", "New Text Document" and "New Bitmap Image" to the right click menu. Once clicked, they trigger the same `RenameDialog` as when creating the items from the "Add Item" button in the ribbon.
| Before | After |
|--------|-------|
|  ![image](https://user-images.githubusercontent.com/8487294/67417228-e4288280-f5fa-11e9-9bd0-f19935db616a.png) | ![image](https://user-images.githubusercontent.com/8487294/67416855-2dc49d80-f5fa-11e9-8f73-bb439c19f7a1.png) |
Related to:
- #49 
- #220
=> Add new file/folder buttons in right-click context menu

Files UWP/Enums/SortOption.cs, Files UWP/FilesUWP.csproj, Files UWP/Filesystem/ItemViewModel.cs, Files UWP/GenericFileBrowser.xaml.cs, Files UWP/Interacts/Interaction.cs, Files UWP/PhotoAlbum.xaml, Files UWP/PhotoAlbum.xaml.cs
- Adds "Sort by" to right click menu in PhotoAlbum.
- Adds `SortOption` enum to represent current file attribute to sort by
- Moves sorting logic to `ItemViewModel` from `GenericFileBrowser`. This allows sorting options to persist through folder navigation
- Sort button not yet added in ribbon
- Navigating to another folder currently
sorts its files only after all of them
are loaded.
=> Add sorting to PhotoAlbum

Files UWP/Filesystem/ItemViewModel.cs, Files UWP/GenericFileBrowser.xaml, Files UWP/GenericFileBrowser.xaml.cs, Files UWP/Interacts/ItemInteractions.cs, Files UWP/Interacts/RibbonActions/Home.cs, Files UWP/Interacts/RibbonActions/Layout.cs, Files UWP/Interacts/RibbonActions/Share.cs, Files UWP/LoadingIndicator.cs, Files UWP/Navigation/BackState.cs, Files UWP/Navigation/ForwardState.cs, Files UWP/Navigation/UniversalPath.cs, Files UWP/PhotoAlbum.xaml, Files UWP/PhotoAlbum.xaml.cs, Files UWP/ProHome.xaml, Files UWP/ProHome.xaml.cs, Files UWP/SettingsPages/Personalization.xaml.cs, Files UWP/YourHome.xaml.cs
This commit **completes the implementation of sorting in Files** by adding a "Sort by" button to the ribbon.
- Moves all sorting-related properties (e.g. `IsSortedByName`) to `ItemViewModel` from `GenericFileBrowser` and `PhotoAlbum`
- Refactors all instances of `NotifyPropertyChanged` to use the `CallerMemberName` attribute
- Removes some unused namespace references
#20
=> Add sort button to app ribbon

Files/App.xaml.cs, Files/Assets/terminal/terminal.json, Files/DataModels/TerminalFileModel.cs, Files/DataModels/TerminalModel.cs, Files/Files.csproj, Files/Interacts/Interaction.cs, Files/SettingsPages/Preferences.xaml, Files/SettingsPages/Preferences.xaml.cs
- Creates a `terminals.json` in the "local"-AppFolder with terminal profiles ([file](https://github.com/lampenlampen/files-uwp/blob/feat/Terminal/Files/Assets/terminal/terminal.json)). As default profile the "cmd"-profile is included. A second commented profile for powershell is also included. It seems the new Windows Terminal currently does not support launching in a specific directory from commandline ([link](https://github.com/microsoft/terminal/pull/4023#issue-355223599)).
- Includes a combobox in the settings to choose between the profiles.
Light | Dark
------------ | -------------
1. [JSON.Net](https://www.newtonsoft.com/json) as dependency?
2. `terminal.json`-schema? At the moment you can specify a name, a description, the executable path, arguments and an icon, but only the name, …
=> Choose Terminal Applications

Files/Files.csproj, Files/ProHome.xaml, Files/ProHome.xaml.cs, Files/Properties.xaml, Files/Settings.xaml, Files/SettingsPages/About.xaml, Files/SettingsPages/Appearance.xaml, Files/SettingsPages/FilesAndFolders.xaml, Files/SettingsPages/OnStartup.xaml, Files/SettingsPages/Preferences.xaml, Files/Strings/en-US/Resources.resw, Files/YourHome.xaml
This pull request is not ready to merge yet.
=> Translations

Files/App.xaml.cs, Files/Files.csproj, Files/NLog.config
I implemented a logger and used NLog.
Until now only unhandled Exception are logged and the app start.
I would suggest as development continues we gradually update the app with logging statements.
Edit 1: The output is directed into a file `debug.txt` in the app's local folder.
Edit 2: It seems Exceptions in the App constructor are not handled.
=> NLog (Logger)

Files/MultilingualResources/Files.es-ES.xlf
- Changed translation for "Browse" from file extraction window and "Clear Selection" to a more appropriate one.
- Changed the status of all new translations from "new" to "translated"
=> Fixed all new translations not being in "translated" state

Files/Files.csproj, Files/Helpers/NaturalStringComparer.cs, Files/View Models/ItemViewModel.cs
Adds a `NaturalStringComparer` class which is used in `ItemViewModel` when sorting by file name.
Resolves #352.
=> Sort filenames naturally using CompareStringEx

Files/Interacts/Interaction.cs, Files/UserControls/ModernSidebar.xaml.cs, Files/UserControls/YourHome.xaml.cs, Files/View Models/ItemViewModel.cs, Files/Views/InstanceTabsView.xaml.cs
Compares the start of the folder path with the special folder paths, instead of a direct comparison. This allows for nested folders to be recognized as part of the "special folders" as well.
Also fixes a spelling error "Naviagtion" and removes extraneous assignment of `SidebarSelectedItem` which is already done in the `set` function of `WorkingDirectory`.
Resolves #525
=> Improve tab behavior when in special folders

Files/BaseLayout.cs, Files/Interacts/Interaction.cs, Files/Navigation/NavigationActions.cs, Files/UserControls/LayoutModes/GenericFileBrowser.xaml.cs, Files/UserControls/LayoutModes/PhotoAlbum.xaml.cs, Files/View Models/ItemViewModel.cs
The app now refreshes when items are pasted (it wasn't doing so for me), and focuses on the pasted items.
Resolves #211.
=> Focus on items after they are pasted

Files/BaseLayout.cs, Files/Helpers/NaturalStringComparer.cs, Files/Interacts/Interaction.cs, Files/MultilingualResources/Files.de-DE.xlf, Files/MultilingualResources/Files.es-ES.xlf, Files/MultilingualResources/Files.fr-FR.xlf, Files/MultilingualResources/Files.nl-NL.xlf, Files/MultilingualResources/Files.pl-PL.xlf, Files/MultilingualResources/Files.ru-RU.xlf, Files/MultilingualResources/Files.tr-TR.xlf, Files/MultilingualResources/Files.uk-UA.xlf, Files/MultilingualResources/Files.zh-Hans.xlf, Files/Strings/en-US/Resources.resw, Files/UserControls/LayoutModes/GenericFileBrowser.xaml.cs, Files/UserControls/LayoutModes/PhotoAlbum.xaml.cs, Files/UserControls/StatusBarControl.xaml
Resolves #601.
Resolves #274.
Previously, when the user navigates into the folder using double click, sometimes it may register as a drag. The program then tries to take the selected files and put it into a `DataPackage` to start the drag process. But when there are no selected files, the `DataPackage` throws an error.
This commit adds a check to see if the selected items list is empty. If it is, cancel the drag gesture.
There's also a bug that causes a folder to delete itself, when it is dragged into itself and "skip" is pressed on the dialog that comes afterwards.
Also adds an Invert Selection and some icons to the menu in the status bar.
=> Add Invert Selection, icons to status bar, fix folder navigation and remove space before .dll

Files/BaseLayout.cs, Files/Dialogs/AddItemDialog.xaml.cs, Files/Dialogs/RenameDialog.xaml, Files/Dialogs/RenameDialog.xaml.cs, Files/Helpers/NaturalStringComparer.cs, Files/Interacts/Interaction.cs, Files/MultilingualResources/Files.de-DE.xlf, Files/MultilingualResources/Files.es-ES.xlf, Files/MultilingualResources/Files.fr-FR.xlf, Files/MultilingualResources/Files.nl-NL.xlf, Files/MultilingualResources/Files.pl-PL.xlf, Files/MultilingualResources/Files.ru-RU.xlf, Files/MultilingualResources/Files.tr-TR.xlf, Files/MultilingualResources/Files.uk-UA.xlf, Files/MultilingualResources/Files.zh-Hans.xlf, Files/Strings/en-US/Resources.resw, Files/UserControls/LayoutModes/GenericFileBrowser.xaml.cs, Files/UserControls/LayoutModes/PhotoAlbum.xaml.cs, Files/UserControls/StatusBarControl.xaml, Files/View Models/ItemViewModel.cs, Files/View Models/SelectedItemPropertiesViewModel.cs, Files/View Models/SettingsViewModel.cs, Files/Views/InstanceTabsView.xaml, Files/Views/InstanceTabsView.xaml.cs
Fixes on top of the previous v0.7.6 work that ended up unreleased.
=> v0.7.6 with fixes

Files/Strings/es-ES/Resources.resw, Files/Views/Pages/ModernShellPage.xaml.cs
=> Fixed OneDrive selection in the sidebar

Files/Interacts/Interaction.cs, Files/Views/Pages/Properties.xaml, Files/Views/Pages/Properties.xaml.cs
Crash caused by MD5 hash algorithm calculation, it did not support large files.
Now file properties are shown before MD5 calculation. Added indeterminate progress bar.
Fixes #704
=> Fix properties window crash

Files/Files.csproj, Files/Helpers/DispatcherHelper.cs, Files/View Models/ItemViewModel.cs, Files/View Models/SettingsViewModel.cs
- Fix a potential crashing at startup due to null reference
- Display already loaded entries while loading files in a directory (akas. Display As You Go), which got user experience improved a lot
- Sorting entries won't take current position to the top of the list
=> Display already loaded entries while loading files in a directory

Files/View Models/InteractionViewModel.cs
Remove try-catch block
The problem has not been solved in PR #770 because of try-catch block which is "handle" exception caused app not crashed if `ItemExtension==null`.
=> Fix null detection of file extension

Files/Interacts/Interaction.cs
Fixed a bug that caused QuickLook to open when pressing spacebar while renaming a file.
Before:
After:
**To Reproduce In Current Version**
Steps to reproduce the behavior:
1. Make sure you have QuickLook installed.
2. Right click on a file and choose "Rename"
3. Give the file any name with a space in it. As soon as spacebar is pressed, QuickLook opens, the file name textbox loses focus and the file name is committed without allowing the user to finish typing.
=> Fixed file rename with space added opening QuickLook

Files/UserControls/LayoutModes/PhotoAlbum.xaml, Files/UserControls/LayoutModes/PhotoAlbum.xaml.cs
Added support for ctrl + click deselection. (#752)
Also changed the behavior of a left click without ctrl to match that of the list view i.e. If you have a few selected items and click one of them without holding ctrl, then that item is selected and the others are deselected. (The end of the below gif is an example of this)
Here's a demo:
=> Added support for ctrl + click deselection in grid view.

Files/Filesystem/DriveItem.cs, Files/Filesystem/Drives.cs, Files/UserControls/ModernSidebar.xaml, Files/UserControls/ModernSidebar.xaml.cs, Files/UserControls/YourHome.xaml.cs, Files/View Models/ItemViewModel.cs, Files/View Models/SettingsViewModel.cs, Files/Views/Pages/ModernShellPage.xaml.cs
Fixes #559 
Removed unused Tag var
=> Fixed OneDrive selection

Files/App.xaml
Before:
After:
Now it is easier to differ what tab is selected, what tab is in pointer over state and unselected tab
=> Fix tab background color in dark mode when pointer over

Files/View Models/ItemViewModel.cs
**Issue**
Currently Files UWP does not display files last modified date correctly: on my system where the timezone is UTC+2 a newly created file shows "Modified: 2 hours ago" (both in properties dialog and in "Date modified" column).
This pull request fixes this so it shows "Modified: 0 seconds ago".
**Fix**
The issue is due to the fact that the [`FileTimeToSystemTime`](https://docs.microsoft.com/en-us/windows/win32/api/timezoneapi/nf-timezoneapi-filetimetosystemtime) function returns an UTC time, but then a new DateTime object is constructed from the returned value without specifying the DateTimeKind as UTC.
```cs
var itemDate = new DateTime(
systemTimeOutput.Year,
systemTimeOutput.Month,
systemTimeOutput.Day,
systemTimeOutput.Hour,
systemTimeOutput.Minute,
systemTimeOutput.Second, …
```
=> Fix files last modified date

Files/UserControls/LayoutModes/GridViewBrowser.xaml
Fixed a bug that caused tall icons to go over the borders and in turn hide the file name.
Thanks @xPoppyx for noticing this👍
Before:
After:
=> Fixed grid view height for tall icons

Files/MultilingualResources/Files.de-DE.xlf, Files/MultilingualResources/Files.es-ES.xlf, Files/MultilingualResources/Files.fr-FR.xlf, Files/MultilingualResources/Files.it-IT.xlf, Files/MultilingualResources/Files.nl-NL.xlf, Files/MultilingualResources/Files.pl-PL.xlf, Files/MultilingualResources/Files.ru-RU.xlf, Files/MultilingualResources/Files.ta.xlf, Files/MultilingualResources/Files.tr-TR.xlf, Files/MultilingualResources/Files.uk-UA.xlf, Files/MultilingualResources/Files.zh-Hans.xlf, Files/Strings/en-US/Resources.resw, Files/Strings/es-ES/Resources.resw, Files/Views/Pages/Properties.xaml
- Added strings for "Read-only" and "Hidden"
- RowSpacing increased from 8 to 11
- Properties Items FontWeight changed to semi-bold
- Aligned item name textbox
=> Properties dialog: Added strings and some changes

Files/Dialogs/RenameDialog.xaml, Files/Dialogs/RenameDialog.xaml.cs, Files/Interacts/Interaction.cs, Files/MultilingualResources/Files.de-DE.xlf, Files/MultilingualResources/Files.es-ES.xlf, Files/MultilingualResources/Files.fr-FR.xlf, Files/MultilingualResources/Files.it-IT.xlf, Files/MultilingualResources/Files.nl-NL.xlf, Files/MultilingualResources/Files.pl-PL.xlf, Files/MultilingualResources/Files.ru-RU.xlf, Files/MultilingualResources/Files.ta.xlf, Files/MultilingualResources/Files.tr-TR.xlf, Files/MultilingualResources/Files.uk-UA.xlf, Files/MultilingualResources/Files.zh-Hans.xlf, Files/Strings/en-US/Resources.resw, Files/Strings/ru-RU/Resources.resw, Files/Strings/uk-UA/Resources.resw, Files/UserControls/LayoutModes/GenericFileBrowser.xaml, Files/UserControls/LayoutModes/GenericFileBrowser.xaml.cs, Files/UserControls/LayoutModes/GridViewBrowser.xaml, Files/UserControls/LayoutModes/GridViewBrowser.xaml.cs
Fixes #630 
Fixes [this](https://github.com/files-community/files-uwp/pull/898#issuecomment-639617546)
How it looks when user types restricted character:
The same in rename dialog:
=> Fix creating a folder or file with restricted names or characters

Files/UserControls/LayoutModes/GenericFileBrowser.xaml.cs, Files/UserControls/LayoutModes/GridViewBrowser.xaml.cs
fixed for grid view and list view
**Before:**
**After:**
=> fixed auto selection when renaming if extensions are hidden

Files/Views/Pages/Properties.xaml, Files/Views/Pages/Properties.xaml.cs
Fix Properties check boxes spacing
Before
After
=> Fixed md5 visibility and check boxes spacing

Files/Filesystem/Drives.cs, Files/Helpers/ThemeHelper.cs, Files/Interacts/Interaction.cs, Files/Views/SettingsPages/Preferences.xaml.cs
This PR:
- may fix the issue of drives not appearing on the sidebar #930 
- *fixes* the issue of removable drives not always appearing/disappearing from the sidebar when connected/disconnected
Basically it changes how to get the UI Dispatcher
- CoreApplication.MainView.Dispatcher -> this often results in `System.Exception` even when app has started
- CoreApplication.MainView.CoreWindow.Dispatcher -> seems ok
Can someone confirm this? (and explain me what the difference is? 😅)
This PR also makes sure that async methods inside a try-catch are always awaited as I don't think that exceptions are caught if the method is not awaited.
```cs
try
{
StorageFolder.GetFolderFromPathAsync(App.AppSettings.OneDrivePath); ----> async without await
}
catch (Exception) ----> the exception can't be caught
{ …
```
=> Change how to get Dispatcher

Files/MultilingualResources/Files.de-DE.xlf, Files/MultilingualResources/Files.es-ES.xlf, Files/MultilingualResources/Files.fr-FR.xlf, Files/MultilingualResources/Files.it-IT.xlf, Files/MultilingualResources/Files.nl-NL.xlf, Files/MultilingualResources/Files.pl-PL.xlf, Files/MultilingualResources/Files.ru-RU.xlf, Files/MultilingualResources/Files.ta.xlf, Files/MultilingualResources/Files.tr-TR.xlf, Files/MultilingualResources/Files.uk-UA.xlf, Files/MultilingualResources/Files.zh-Hans.xlf, Files/Strings/en-US/Resources.resw, Files/Strings/es-ES/Resources.resw, Files/UserControls/NavigationToolbar/ModernNavigationToolbar.xaml, Files/Views/InstanceTabsView.xaml
- A tooltip was also added for the add tab button (@yaichenbaum take a look at the Uid of this button)
-------------------------------
- Back (Alt + Left Arrow)
- Forward (Alt + Right Arrow)
- Up (Alt + Up Arrow)
- Refresh (F5)
- Create a new item (Ctrl + Shift + N)
- New tab (Ctrl + T)
=> Added keyboard shortcuts to the tooltip of buttons in the navigation bar

Files/Assets/terminal/terminal.json, Files/DataModels/TerminalFileModel.cs, Files/DataModels/TerminalModel.cs, Files/View Models/SettingsViewModel.cs, Files/Views/SettingsPages/Preferences.xaml.cs
Fixed issue when terminal Id hasn't been found
=> Terminal: Use path as terminal identifier

Files/Interacts/Interaction.cs
This happens because when a new window is created  "Clipboard.Flush()" can't able to release the datapackage it's holding.
Solved it based on the StackTrace Below:
```
CloseClipboard Failed (Exception from HRESULT: 0x800401D4 (CLIPBRD_E_CANT_CLOSE))|System.Exception: CloseClipboard Failed (Exception from HRESULT: 0x800401D4 (CLIPBRD_E_CANT_CLOSE))
at Windows.ApplicationModel.DataTransfer.Clipboard.Flush()
at Files.Interacts.Interaction.CopyItem_ClickAsync(Object sender, RoutedEventArgs e)
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__7_0(Object state)
at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()
at Windows.ApplicationModel.Core.UnhandledError.Propagate()
at Microsoft.AppCenter.Utils.ApplicationLifecycleHelper.<.ctor>b__17_1(Object …
```
=> [Fixed]   #1034 Multi-Windows Cut Copy crash

Files/Helpers/NativeDirectoryChangesHelper.cs, Files/View Models/ItemViewModel.cs
Proposal for #1001
\- Use `CancelIoEx` to cancel previous watcher: watcher is started on a background thread so `CancelIo` has no effect.
\- Close overlapped.hEvent handle
\- Close hWatchDir handle
=> Cancel previous watcher

Files/Helpers/NativeDirectoryChangesHelper.cs, Files/View Models/ItemViewModel.cs
Under certain conditions, execution of blocks of code inside the file watching loop continues although the loop's condition is false, causing unwanted actions to be performed (e.g. using the closed directory handle) 
This PR aims to:
- Prevent a crash from occurring upon changing the working directory quickly
- Remove unneeded checks before adding/removing files during the watcher operation
- Convert any direct uses of the FilesAndFolders property to use a "snapshot" list instead
Please test this PR by doing the following:
1. Removing/Adding/Renaming a file after refreshing the directory multiple times
2. **RELEASE MODE:** Changing the WorkingDirectory by rapidly invoking various sidebar locations
=> Prevent the file watching loop from still being alive after we kill it

Files/Files.csproj, Files/Helpers/BulkObservableCollection.cs, Files/UserControls/LayoutModes/GenericFileBrowser.xaml.cs, Files/View Models/ItemViewModel.cs
- Added BulkObservableCollection: support bulk operations based on ObservableCollection, and make sorting process faster
- Optimize SelectAll: call non-public method `DataGrid.SelectAll()` to make Select All operation as fast as Ctrl+A
A further question:
How to optimize Invert Selection? DataGrid used `SetRowsSelection()` internally for fast selection operation, I think we can make it use for implementing faster Invert Selection.
https://github.com/windows-toolkit/WindowsCommunityToolkit/blob/4aca25975f3cec90d4f86d5b5239aa6bc185880b/Microsoft.Toolkit.Uwp.UI.Controls.DataGrid/DataGrid/DataGridRows.cs#L797
=> Improve performance on selection operations

Files.Launcher/Program.cs, Files.Launcher/Win32API.cs, Files/Interacts/Interaction.cs
Currently if you click [enter] after selecting multiple e.g. ".mp3" files only the last one will be played in the associated program (e.g. Groove Music). Same goes with multiple picture files, etc..
This PR fixes this.
Fixes #1057
=> Improved support for opening multiple files at a time

Files/Interacts/Interaction.cs, Files/Views/InstanceTabsView.xaml.cs
This pull request changes the way the app is closed when the last tab is closed either with Ctrl+W or tab close button.
In the current implementation the ```Application.Current.Exit()``` method is called which results in an "ugly" closing animation: the app briefly shows an empty window and than the window closes abruptly looking like the app has crashed.
Instead this pull request uses the ```StartTerminateAsync()``` of the [diagnostic API](https://docs.microsoft.com/en-us/uwp/api/windows.system.appresourcegroupinfo.startterminateasync?view=winrt-18362) which results in the standard closing animation (like clicking the exit button on the titlebar) The method exists from the 1809 version and does not require additional app cababilities.
I do find this solution a bit of an overkill but I …
=> Improved "last tab closing" behavior

Files/Interacts/Interaction.cs, Files/Views/Pages/Properties.xaml, Files/Views/Pages/Properties.xaml.cs
=> Properties: Show progress when calculating MD5 hash

Files/Views/InstanceTabsView.xaml.cs
This PR fixes an issue where we would only show the parent folder name instead of the folders actual name in the tab.
=> Fixed issue where the folder name wouldn't display on tabs

Files/Filesystem/DriveItem.cs, Files/MultilingualResources/Files.de-DE.xlf, Files/MultilingualResources/Files.es-ES.xlf, Files/MultilingualResources/Files.fr-FR.xlf, Files/MultilingualResources/Files.it-IT.xlf, Files/MultilingualResources/Files.ja-JP.xlf, Files/MultilingualResources/Files.nl-NL.xlf, Files/MultilingualResources/Files.pl-PL.xlf, Files/MultilingualResources/Files.ru-RU.xlf, Files/MultilingualResources/Files.ta.xlf, Files/MultilingualResources/Files.tr-TR.xlf, Files/MultilingualResources/Files.uk-UA.xlf, Files/MultilingualResources/Files.zh-Hans.xlf, Files/Strings/en-US/Resources.resw, Files/View Models/ItemViewModel.cs, Files/View Models/SelectedItemsPropertiesViewModel.cs
Fix incorrect drive space calculation
Show item size in bytes in properties window.
Before
After
=> Fix incorrect item size value

Files/View Models/ItemViewModel.cs, Files/Views/InstanceTabsView.xaml.cs
Fixes:
- Tag will lost prefixed `\\` if it's a network path, and will crash if try to navigate by clicking PathItemBox
- Path.GetRootPath() may return null or empty string, which leads to crash in NormalizePath()
=> Bug fixes for handling network path

Files/View Models/SelectedItemsPropertiesViewModel.cs, Files/Views/Pages/Properties.xaml, Files/Views/Pages/Properties.xaml.cs
=> Properties: Fix some properties loading on older systems

Files/BaseLayout.cs, Files/Views/LayoutModes/GenericFileBrowser.xaml, Files/Views/LayoutModes/GridViewBrowser.xaml
Fixing an issue with assigning the wrong method to the right click menuflyout.
=> 1185: "Open", "Open with", "open in new tab / window" and "pin to sidebar" no longer appear in the item context menu

Files/BaseLayout.cs, Files/Enums/PropertiesType.cs, Files/Files.csproj, Files/Interacts/Interaction.cs, Files/MultilingualResources/Files.de-DE.xlf, Files/MultilingualResources/Files.es-ES.xlf, Files/MultilingualResources/Files.fr-FR.xlf, Files/MultilingualResources/Files.it-IT.xlf, Files/MultilingualResources/Files.ja-JP.xlf, Files/MultilingualResources/Files.nl-NL.xlf, Files/MultilingualResources/Files.pl-PL.xlf, Files/MultilingualResources/Files.ru-RU.xlf, Files/MultilingualResources/Files.ta.xlf, Files/MultilingualResources/Files.tr-TR.xlf, Files/MultilingualResources/Files.uk-UA.xlf, Files/MultilingualResources/Files.zh-Hans.xlf, Files/Strings/de-DE/Resources.resw, Files/Strings/en-US/Resources.resw, Files/Strings/es-ES/Resources.resw, Files/Strings/ru-RU/Resources.resw, Files/Strings/uk-UA/Resources.resw, Files/UserControls/StatusBarControl.xaml, Files/View Models/SelectedItemsPropertiesViewModel.cs, Files/View Models/SettingsViewModel.cs, Files/Views/Pages/Properties.xaml, Files/Views/Pages/Properties.xaml.cs, Files/Views/SettingsPages/Experimental.xaml
New combined properties:
New drive properties:
Thanks: #1097 
Fixes #259
=> Properties: Add support for combined and drive properties

Files/View Models/SettingsViewModel.cs
It could happen, when previous app version crashing leaving json file empty.
When deserializing an empty file, it returns null object, which is caused an exception.
=> Fix JSON loading when it's empty

Files/Views/ModernShellPage.xaml, Files/Views/ModernShellPage.xaml.cs
This PR should improve the reliability of many keyboard accelerators.
Fixes #963
=> Remove Uses of CoreWindow GetKeyState to Improve Keyboard Accelerators

Files/Views/LayoutModes/GenericFileBrowser.xaml
Fixes #737 
I think this change, while small, will make a difference for users' perception of our UI. We can tweak from here if needed.
=> Apply Tweaks to DataGrid FontSize, ColumnHeaders

Files.Launcher/Program.cs, Files/Dialogs/ConfirmDeleteDialog.xaml, Files/Dialogs/ConfirmDeleteDialog.xaml.cs, Files/Interacts/Interaction.cs, Files/View Models/InteractionViewModel.cs, Files/View Models/Properties/FolderProperties.cs, Files/Views/LayoutModes/GenericFileBrowser.xaml.cs, Files/Views/LayoutModes/GridViewBrowser.xaml.cs, Files/Views/ModernShellPage.xaml.cs
This PR fixes a few issues related to dialogs.
In particular:
- Pressing 'Space' to activate QuickLook only works in List View #1322
-> GridView seems to "swallow" the Space key, for `GridViewBrowser` the Space key is now handled in `FileList_PreviewKeyDown`
- Properties window not working for recycle bin #1263
-> Properties dialog for recycle bin was removed in #1264, this removes the code causing the exception in #1263
- Pressing space key while focused on the "permanently delete" checkbox in the "delete item(s)" modal dialog breaks keyboard navigation #1323
-> When a key is pressed the file list is focused only if no dialog is currently displayed
- After canceling a permanent deletion, if you press "shift + del" again in the same file, "permanently delete" is no longer checked again …
=> Fix dialog-related issues

Files.Launcher/Program.cs, Files.Launcher/Win32API.cs
Use Vanara instead of DLLImport
=> Files.Launcher: Code cleanup

Files/Views/Pages/Properties.xaml
Fixes #1405 
--------------------
**Before:**
Local drive: ![Anotación 2020-07-12 174404](https://user-images.githubusercontent.com/61259627/87257683-ed000380-c46a-11ea-8359-e2893f363dc6.png)
Network drive: ![Anotación 2020-07-12 174418](https://user-images.githubusercontent.com/61259627/87257684-ed989a00-c46a-11ea-9f04-0c1c22b72843.png)
--------------------------------
**After:**
Local drive: ![Anotación 2020-07-12 181109](https://user-images.githubusercontent.com/61259627/87257698-1c167500-c46b-11ea-9e32-4dc9a7e40f7f.png)
Network drive: ![Anotación 2020-07-12 181121](https://user-images.githubusercontent.com/61259627/87257699-1caf0b80-c46b-11ea-910d-9c6e76c2d6a8.png)
=> Properties: Fix missing font family for drives icon

Files.Launcher/Files.Launcher.csproj, Files.Launcher/Program.cs
Fixes compile error when updating library.
This update is useful for context-menu implementation
=> Bump Vanara.Windows.Shell from 3.2.11 to 3.2.12

Files/DataModels/DefaultLanguageModel.cs, Files/MultilingualResources/Files.de-DE.xlf, Files/MultilingualResources/Files.es-ES.xlf, Files/MultilingualResources/Files.fr-FR.xlf, Files/MultilingualResources/Files.he-IL.xlf, Files/MultilingualResources/Files.hi-IN.xlf, Files/MultilingualResources/Files.it-IT.xlf, Files/MultilingualResources/Files.ja-JP.xlf, Files/MultilingualResources/Files.nl-NL.xlf, Files/MultilingualResources/Files.or-IN.xlf, Files/MultilingualResources/Files.pl-PL.xlf, Files/MultilingualResources/Files.pt-BR.xlf, Files/MultilingualResources/Files.ru-RU.xlf, Files/MultilingualResources/Files.ta.xlf, Files/MultilingualResources/Files.tr-TR.xlf, Files/MultilingualResources/Files.uk-UA.xlf, Files/MultilingualResources/Files.zh-Hans.xlf, Files/Strings/en-US/Resources.resw, Files/View Models/SettingsViewModel.cs, Files/Views/SettingsPages/Preferences.xaml, Files/Views/SettingsPages/Preferences.xaml.cs
=> Fixed language options

Files/Filesystem/StorageFileHelpers/StorageFileExtensions.cs, Files/UserControls/ModernNavigationToolbar.xaml, Files/UserControls/ModernNavigationToolbar.xaml.cs, Files/View Models/SettingsViewModel.cs
Made changes requested in #182 and #534. Also, fixed renavigation problems in NavigationBar.
=> Made some requested changes and fixes for NavigationBar

Files/Interacts/Interaction.cs, Files/Views/Pages/Properties.xaml, Files/Views/Pages/Properties.xaml.cs
Added the ability to use the escape key to exit the file properties window as requested in issue #1409.
=> Added the ability to use the escape key to exit the properties window

Files/BaseLayout.cs
Attempted to fix issue #1379.
Make it do nothing when drag a folder and drop it on itself and when drag some files and folders and drop them on one of the dragged folder.
=> Cancel Action Without Error Message When Drag One Or More Folders and Drop on itself (themselves) 

Files/Helpers/JumpListManager.cs
Saving to jumplist may fail randomly with error: ERROR_UNABLE_TO_REMOVE_REPLACED. In that case app should just catch the error and proceed as usual.
=> Fix for random error when saving to jumplist

Files/MultilingualResources/Files.de-DE.xlf, Files/MultilingualResources/Files.es-ES.xlf, Files/MultilingualResources/Files.fr-FR.xlf, Files/MultilingualResources/Files.he-IL.xlf, Files/MultilingualResources/Files.hi-IN.xlf, Files/MultilingualResources/Files.it-IT.xlf, Files/MultilingualResources/Files.ja-JP.xlf, Files/MultilingualResources/Files.nl-NL.xlf, Files/MultilingualResources/Files.or-IN.xlf, Files/MultilingualResources/Files.pl-PL.xlf, Files/MultilingualResources/Files.pt-BR.xlf, Files/MultilingualResources/Files.ru-RU.xlf, Files/MultilingualResources/Files.ta.xlf, Files/MultilingualResources/Files.tr-TR.xlf, Files/MultilingualResources/Files.uk-UA.xlf, Files/MultilingualResources/Files.zh-Hans.xlf, Files/Strings/en-US/Resources.resw, Files/UserControls/ModernNavigationToolbar.xaml, Files/UserControls/ModernNavigationToolbar.xaml.cs
As requested by @mdtauk, implemented clicking on any path items chevron to get a drop-down list of all folders in that directory:
=> Implemented folder dropdown list for Navigationbar

Files/Views/LayoutModes/GenericFileBrowser.xaml.cs
This PR fixes #1542 
The error occurred when setting the SelectedItems. Instead of adding all items to the SelectedItems Property, only the SelectedItem property was updated
=> Fixed a bug where invert selection didn't work

Files/Controllers/TerminalController.cs
Tries fixing #710. If parsing fails app uses the default values while keeping user's copy intact (doesn't override user's copy).
=> Fixed app crashing when parsing terminal.json file

Files/Filesystem/StorageFileHelpers/StorageFileExtensions.cs
Re-implement path components calculation with a clearer logic.
- Fix bugs in handling network path, eg. `\\192.168.1.1\test`, `\\wsl$\Ubuntu\home`, existing implementation lost the prefixed `\\` in the path
- Make the logic clearer for maintainability
=> Improve path components calculation

Files/View Models/SettingsViewModel.cs, Files/Views/SettingsPages/Preferences.xaml.cs
=> Settings: Fix crash when OneDrive path is null or doesn't exists

Files/Interacts/Interaction.cs
Possible fix for #1636 
Only difference is the selected items are retrieved before the deletion prompt is shown, hence any changes to the selection after the prompt is confirmed have no effect on the items listed for deletion.
=> Fixed incorrect file deletion bug

Files/BaseLayout.cs, Files/Helpers/AcrylicTheme.cs, Files/UserControls/ModernNavigationToolbar.xaml.cs, Files/UserControls/SidebarControl.xaml.cs, Files/UserControls/Widgets/RecentFiles.xaml.cs, Files/View Models/ItemViewModel.cs, Files/Views/MainPage.xaml.cs
Issue #1729 Code Improvement
String property names are now replaced with nameof()
=> Replaced string property names with nameof()

Files/View Models/CurrentInstanceViewModel.cs
Fixes #1729 
This is just an addition to the PR from @d2dyno1.
This class was probably forgotten because `RaisePropertyChanged` is used instead of `NotifyPropertyChanged`.
But we should use nameof() wherever possible
=> replaced hardcoded property names with nameof()

Files/Interacts/Interaction.cs, Files/MultilingualResources/Files.de-DE.xlf, Files/MultilingualResources/Files.es-ES.xlf, Files/MultilingualResources/Files.fr-FR.xlf, Files/MultilingualResources/Files.he-IL.xlf, Files/MultilingualResources/Files.hi-IN.xlf, Files/MultilingualResources/Files.it-IT.xlf, Files/MultilingualResources/Files.ja-JP.xlf, Files/MultilingualResources/Files.nl-NL.xlf, Files/MultilingualResources/Files.or-IN.xlf, Files/MultilingualResources/Files.pl-PL.xlf, Files/MultilingualResources/Files.pt-BR.xlf, Files/MultilingualResources/Files.ru-RU.xlf, Files/MultilingualResources/Files.ta.xlf, Files/MultilingualResources/Files.tr-TR.xlf, Files/MultilingualResources/Files.uk-UA.xlf, Files/MultilingualResources/Files.zh-Hans.xlf, Files/Strings/en-US/Resources.resw, Files/Strings/it-IT/Resources.resw, Files/Strings/ta/Resources.resw, Files/UserControls/ModernNavigationToolbar.xaml.cs
String resource for `InvalidItemDialogContent` contained empty lines.
As suggested by @tsvietOK this PR changes it to string.Format("...{0}...", Environment.NewLine)
=> Remove empty lines in resources

Files/Filesystem/Drives.cs, Files/View Models/SettingsViewModel.cs, Files/Views/ModernShellPage.xaml.cs
Fixes #1747
This PR makes sure that the consent dialog for the broadFileSystemAccess permission is shown on app start.
=> Show consent dialog for broadFileSystemAccess

Files/UserControls/Widgets/RecentFiles.xaml.cs
Fixes #1645
Loading recent files list may cause files to be downloaded from OneDrive.
Trying to read a file with `streamReader.Peek();` will trigger the download of the file if such file is in OneDrive and marked "online-only". 
That piece of code was added to remove files opened from a disconnected android/MTP phone, so this PR adds a check to only call `streamReader.Peek();` if the file was on a MTP phone. This will avoid to risk downloading the file.
This PR also adds handling for a couple more exceptions in `PopulateRecentsList()` that were seen in crash reports on AppCenter (at this point it might make sense to just `catch (Exception) {`..
=> Fixed an issue loading recent items on the home page

Files/App.xaml.cs
Fixes #1799 
Fixed an issue where an exception would occur when closing tab with continue where you left off
=> Fixed closing last tab causes an exception with continue where you left off

Files/View Models/ItemViewModel.cs, Files/Views/MainPage.xaml.cs
Fix #1767
This PR allows to eject a connected USB drive without closing the app. It's sufficient to close the tab or navigate away.
Please check if you agree on how to detect when a tab was closed, I don't know much about how tabs are handled.
=> Fixed an issue where external devices cannot be removed while app is opened

Files/App.xaml.cs, Files/Filesystem/Drives.cs
Fixes #1817
The device watcher was stopped in OnSuspending but not resumed when the app was restored.
=> Resume devicewatcher after suspending

Files/App.xaml.cs, Files/Filesystem/Drives.cs
Fix #1829
Fix removable drives appearing twice in the sidebar, bug introduced by #1819
Explanation: the same drive was being added in both `DeviceAdded()` and `GetDrives()` functions. This PR adds a flag that indicates if `GetDrives()` is running.
=> Fix duplicate removable drives in sidebar

Files/Filesystem/ListedItem.cs, Files/Views/LayoutModes/GenericFileBrowser.xaml, Files/Views/LayoutModes/GenericFileBrowser.xaml.cs, Files/Views/LayoutModes/GridViewBrowser.xaml, Files/Views/LayoutModes/GridViewBrowser.xaml.cs
Fixes #1816, fixes #1400
GridView and ListView virtualize items so for example `ContainerFromItem(...)` returns null for items outside the rendered range and this was causing the reported exception.
This PR adds a "IsDimmed" property to ListedItem and setting the opacity is now done through binding instead of directly accessing the UI item.
=> Fixed a crash that would sometimes occur when cutting an item

Files/Views/Pages/Properties.xaml.cs
Fix #1771
Do not set the AcrylicBrush's TintLuminosityOpacity property on 1903/1909 as it makes the app crash (only in Release mode).
Funny since TintLuminosityOpacity should be supported in 1903.
@Jaiganeshkumaran could you test this and confirm?
=> Fixed an issue where opening the properties window would sometimes crash the app on 1903/1909

Files.Launcher/Program.cs, Files.Launcher/Win32API_ContextMenu.cs
Fixes #1869
This PR hides the "pin to start" context menu option which is not working. Also it avoids fulltrust process crash in case the same happens with other menu items.
=> Fixed a crash that would sometimes occur when selecting some options on the right click context menu

Files/UserControls/SidebarControl.xaml.cs, Files/Views/ModernShellPage.xaml.cs
Fixes #1908
Since drives are loaded asynchronously, a matching sidebar item may not be present at the time ModernShellPage/Page_Loaded is called on startup (especially if the "continue where you left off feature" is enabled.
=> Fixed a crash that would sometimes occur on startup

Files/UserControls/MultitaskingControl/HorizontalMultitaskingControl.xaml.cs
=> Fix crash when dropping tab outside tabstrip

Files.Launcher/Program.cs
=> Hide windows explorer's paste command from context menu

Files/UserControls/Widgets/LibraryCards.xaml, Files/UserControls/YourHome.xaml
This PR has the following effects:
- No more unnecessary scrollbar for YourHome cards
- No weird double press effect when long-pressing the cards
- Improved adaptive behavior of cards during window resize
Most users won't notice any difference.
=> Use ItemsRepeater control for YourHome library cards

Files/BaseLayout.cs, Files/Views/SettingsPages/Multitasking.xaml
Fixes #1961, fixes #1971, fixes #1936, fixes #1939, maybe fixes #1958
Appcenter: [2431183698u](https://appcenter.ms/orgs/Files-UWP/apps/Files/crashes/errors/2431183698u/overview)
Sometimes after changing multitasking setting (adaptive, horizontal, vertical) all 3 multitasking options get disabled/deselected.
If this happens, from there on, app crashes with NullPointerException in BaseLayout, with a stacktrace similar to:
>2020-09-18 00:24:03.6905|ERROR|Files.App|Object reference not set to an instance of an object.|System.NullReferenceException: Object reference not set to an instance of an object. at Files.BaseLayout.OnNavigatedTo(NavigationEventArgs eventArgs) at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()
=> Fix a crash that would occur when no multitasking option was selected

Files.Launcher/Files.Launcher.csproj, Files.Launcher/Win32API_ContextMenu.cs
Fixes #1944 
Issue was due to a memory access error that was for some reason happening when parsing the "Run with graphic processor" context-menu item that appears on PCs with NVidia graphic cards.
This bug was hard to track down because it was happening only on azure release builds: this was because azure builds the Files.Launcher project as x64 while local build uses x86. This PR changes the "Prefer32Bit" option to false in order to have consistent behavior when building locally and on azure. Let me know if it's ok to include this change.
=> Fixed and issue with the context menu not appearing when right clicking on exe files

Files/Views/LayoutModes/GenericFileBrowser.xaml, Files/Views/LayoutModes/GenericFileBrowser.xaml.cs
Fixes #1208 
I implemented an event handler at `AllView` on `Holding` event.
To avoid code duplication, I moved the code from `AllView_RightTapped` to a new method called `HandleRightClick`.
=> Fixed a crash that would sometimes occur when right clicking an item using a touch screen

Files/MultilingualResources/Files.de-DE.xlf, Files/MultilingualResources/Files.es-ES.xlf, Files/MultilingualResources/Files.fr-FR.xlf, Files/MultilingualResources/Files.he-IL.xlf, Files/MultilingualResources/Files.hi-IN.xlf, Files/MultilingualResources/Files.it-IT.xlf, Files/MultilingualResources/Files.ja-JP.xlf, Files/MultilingualResources/Files.nl-NL.xlf, Files/MultilingualResources/Files.or-IN.xlf, Files/MultilingualResources/Files.pl-PL.xlf, Files/MultilingualResources/Files.pt-BR.xlf, Files/MultilingualResources/Files.ru-RU.xlf, Files/MultilingualResources/Files.ta.xlf, Files/MultilingualResources/Files.tr-TR.xlf, Files/MultilingualResources/Files.uk-UA.xlf, Files/MultilingualResources/Files.zh-Hans.xlf, Files/Strings/en-US/Resources.resw
fixes #1988 
I removed the colon of the following string: `BaseLayoutItemContextFlyoutQuickLook.Text`.
=> Remove colon from QuickLook in context menu

Files/Commands/Paste.cs, Files/Dialogs/BitlockerDialog.xaml.cs, Files/Interacts/Interaction.cs, Files/Views/LayoutModes/GenericFileBrowser.xaml.cs, Files/Views/LayoutModes/GridViewBrowser.xaml.cs
Fixes #1982
- Fix crash when clicking ctrl-x and no file is selected
- Fix crash when clicking ctrl-v and clipboard does not contain files
- Fix crash when clicking ctrl- c/v/x and windows version is 1809
=> Fixed a crash that sometimes occurs when pressing Ctrl + C / V / X

Files/Views/LayoutModes/GenericFileBrowser.xaml.cs
Fixes #1727 
I fixed it by setting the property `e.Column.SortDirection` to the opposite direction of its previous value.
=> Fixed an issue with sorting items

Files/MultilingualResources/Files.de-DE.xlf, Files/MultilingualResources/Files.es-ES.xlf, Files/MultilingualResources/Files.fr-FR.xlf, Files/MultilingualResources/Files.he-IL.xlf, Files/MultilingualResources/Files.hi-IN.xlf, Files/MultilingualResources/Files.it-IT.xlf, Files/MultilingualResources/Files.ja-JP.xlf, Files/MultilingualResources/Files.nl-NL.xlf, Files/MultilingualResources/Files.or-IN.xlf, Files/MultilingualResources/Files.pl-PL.xlf, Files/MultilingualResources/Files.pt-BR.xlf, Files/MultilingualResources/Files.ru-RU.xlf, Files/MultilingualResources/Files.ta.xlf, Files/MultilingualResources/Files.tr-TR.xlf, Files/MultilingualResources/Files.uk-UA.xlf, Files/MultilingualResources/Files.zh-Hans.xlf, Files/Strings/en-US/Resources.resw, Files/Views/LayoutModes/GenericFileBrowser.xaml, Files/Views/LayoutModes/GridViewBrowser.xaml
=> Added the option to change the layout mode by right clicking on a blank space

Files/UserControls/SidebarControl.xaml, Files/UserControls/YourHome.xaml, Files/Views/LayoutModes/GenericFileBrowser.xaml.cs, Files/Views/LayoutModes/GridViewBrowser.xaml.cs
=> Fixed two issues with keyboard navigation

Files/Views/Pages/Properties.xaml.cs
I fixed #1879 by hiding the dialog when it gets closed.
Additionally, I noticed that the class `PropertyNavParam` is nested inside the class `Properties`. Shall I move this class out to the namespace?
=> Fixed an issue where the content of the man window isn't interactable after the properties window is closed

Files/Filesystem/ListedItem.cs, Files/View Models/ItemViewModel.cs, Files/View Models/Properties/BaseProperties.cs, Files/View Models/Properties/FileProperties.cs, Files/View Models/Properties/FolderProperties.cs
Slightly improve CPU usage by making some property checks less repetitive in the enumeration loop by being optional arguments.
=> Make optional/move repetitive checks of property values outside item enumeration loop

Files/App.xaml.cs, Files/Helpers/JumpListManager.cs, Files/View Models/ItemViewModel.cs
This PR includes:
- Don't add `Home` to `JumpList`
- Prevent crash that would occur if `JumpList` was `null`
- Refactoring in `App.xaml.cs`
=> Refactoring + JumpList fixes

Files/Files.csproj, Files/Interacts/Interaction.cs, Files/UserControls/SidebarControl.xaml, Files/UserControls/SidebarControl.xaml.cs, Files/View Models/Properties/FolderProperties.cs
This PR implements #1212 
In this issue, it was suggested to add properties for pinned items as well. I implemented this capability but the `FolderProperties` view model causes several issues. I fixed a thrown exception when the use is on the home page. But I was not able to fix an issue where the properties of the current folder in the file browser are shown.
As a result, implementing properties context menu for pinned items requires breaking to the `FolderProperties` view model which are beyond the range of this PR.
=> Added properties to the context menu for items in the sidebar

Files.Launcher/Program.cs, Files/Filesystem/ListedItem.cs, Files/UserControls/FileIcon.xaml, Files/View Models/ItemViewModel.cs, Files/View Models/Properties/FolderProperties.cs, Files/Views/LayoutModes/GenericFileBrowser.xaml, Files/Views/LayoutModes/GridViewBrowser.xaml, Files/Views/Pages/PropertiesDetails.xaml
=> Added support to display custom folder icons

Files/App.xaml, Files/ResourceDictionaries/TabView_themeresources.xaml, Files/UserControls/ModernNavigationToolbar.xaml, Files/UserControls/MultitaskingControl/HorizontalMultitaskingControl.xaml, Files/UserControls/SidebarControl.xaml, Files/UserControls/SidebarControl.xaml.cs, Files/UserControls/Widgets/LibraryCards.xaml, Files/Views/ModernShellPage.xaml, Files/Views/Pages/Properties.xaml.cs, Files/Views/Settings.xaml
Switch many areas of the app to use the provided SystemColor* universal resources for HighContrast themes. 
Before vs After:
Final result:
=> Improved support for HighContrast themes

Files.Launcher/Win32API_ContextMenu.cs
Fixes #2140
This PR changes how to get the context menu items icon to solve the issue of some icons appearing flipped.
I got the code from [here](https://stackoverflow.com/a/9291151) and I admit I have little experience with Win32/GDI programming.
Let me know if you spot anything amiss :)
=> Fix flipped context menu icons (e.g winrar)

Files/UserControls/RectangleSelection.cs
App version 0.18 crashes when using selection rectangle in empty folders
Issue seen in AppCenter -> https://appcenter.ms/orgs/Files-UWP/apps/Files/crashes/errors/3577933249u/overview
This PR fixes this
=> Fixed a crash that would occur when using the selection rectangle in an empty folder

Files.Launcher/Program.cs, Files.Launcher/Win32API.cs, Files.Launcher/Win32API_ContextMenu.cs
=> Fixed an issue where the 'Empty Recycle Bin' context menu entry was always grayed out

Files/Filesystem/StorageFileHelpers/StorageFileExtensions.cs
[#2190] - Checked for UnauthorizedAccessException on a selected directory. When the exception occurs, GetFolderWithPathFromPathAsync will be called recursively each time with a parent path of the folder for which we don't have necessary access rights.
=> [#2190] - Checked for UnauthorizedAccessException on a selected directory

Files/App.xaml.cs, Files/Commands/Delete.cs, Files/View Models/ItemViewModel.cs
Fixes #2172
Fixes [2428289282u](https://appcenter.ms/orgs/Files-UWP/apps/Files/crashes/errors/2428289282u/overview)
@duke7553 this PR hopes to solve a couple of issues in ItemViewModel that cause app crash. I'd be happy if you could take a look at it as well.
1) Fix crash when temporary files are quickly created and deleted (e.g. when saving a Word file in Onedrive folder as in #2172)
Changed the functions AddFileOrFolder, UpdateFileOrFolder, RemoveFileOrFolder from `async void` to `async Task` so the `catch` statement in WatchForDirectoryChanges can actually work (exceptions are not caught if not awaited).
2) Fix files/folders with funny/garbled names appearing in the file list in the same above situation
What happens is that sometimes WIN32_FIND_DATA seems to contain garbage data, this …
=> Fixed a couple issues in ItemViewModel

Common/Extensions.cs, Files.Launcher/Program.cs, Files/Filesystem/DriveItem.cs, Files/UserControls/SidebarControl.xaml, Files/View Models/ItemViewModel.cs
Fixes #2174
This PR solves the issue of app hanging on start if a network drive is disconnected.
This is done by:
- loading drive properties in an async method (with timeout) -> fix hang  on app start
- adding a timeout to `EnumerateItemsFromStandardFolder` after which a "Drive disconnected" dialog is shown -> fix hang is the user navigates to a disconnected drive
=> Fixed an issue that would occur when network drives were disconnected

Files/MultilingualResources/Files.de-DE.xlf, Files/MultilingualResources/Files.es-ES.xlf, Files/MultilingualResources/Files.fr-FR.xlf, Files/MultilingualResources/Files.he-IL.xlf, Files/MultilingualResources/Files.hi-IN.xlf, Files/MultilingualResources/Files.hu-HU.xlf, Files/MultilingualResources/Files.it-IT.xlf, Files/MultilingualResources/Files.ja-JP.xlf, Files/MultilingualResources/Files.nl-NL.xlf, Files/MultilingualResources/Files.or-IN.xlf, Files/MultilingualResources/Files.pl-PL.xlf, Files/MultilingualResources/Files.pt-BR.xlf, Files/MultilingualResources/Files.ru-RU.xlf, Files/MultilingualResources/Files.ta.xlf, Files/MultilingualResources/Files.tr-TR.xlf, Files/MultilingualResources/Files.uk-UA.xlf, Files/MultilingualResources/Files.zh-Hans.xlf, Files/Strings/de-DE/Resources.resw, Files/Strings/en-US/Resources.resw, Files/Strings/es-ES/Resources.resw, Files/Strings/hu-HU/Resources.resw, Files/Strings/it-IT/Resources.resw, Files/Strings/ja-JP/Resources.resw, Files/Strings/pt-BR/Resources.resw, Files/Strings/ta/Resources.resw, Files/Views/SettingsPages/Appearance.xaml
- Fixed the Uid for "CopyLocationToggleSwitch" in string resources
_In **Preferences.xaml** the Uid was correct, but in the string resources an incorrect id was used_
Changes to **Resources.resw** :
**Before:**
**After:**
-----------------------------------------
Changes to **Appearance.xaml:**
- Added missing Uid for "AcrylicSidebarSwitch"
=> Fixes for some Uid

Files/BaseLayout.cs, Files/Commands/Delete.cs, Files/Commands/Paste.cs, Files/DataModels/SidebarPinnedModel.cs, Files/Files.csproj, Files/Filesystem/Drives.cs, Files/Filesystem/StorageFileHelpers/FilesystemResult.cs, Files/Filesystem/StorageFileHelpers/StorageFileExtensions.cs, Files/Helpers/PathNormalization.cs, Files/Interacts/Interaction.cs, Files/View Models/ItemViewModel.cs, Files/View Models/Properties/DriveProperties.cs, Files/View Models/Properties/FileProperties.cs, Files/View Models/SettingsViewModel.cs, Files/Views/ModernShellPage.xaml.cs, Files/Views/SettingsPages/Preferences.xaml.cs
Fixes #1831
Fixes #2164
Fixes #2265
Fixes #1707
Hi all, this PR contains a proposal on how to improve exception handling/reliability for filesystem operations.
This PR wraps all filesystem operations in a `FilesystemResult` object which contains the operation result (e.g. a StorageFolder) and an error code. In case of error, instead of throwing an exception, the error is returned in the `ErrorCode` field and the result is set to `null`.
Examples:
1) Where we don't care about *why* the function has failed we can simply check if the result is `null`
```cs
StorgeFile file = await ParentShellPageInstance.FilesystemViewModel.GetFileFromPathAsync(PATH);
if (file != null)
{
// Succeeded
selectedStorageItems.Add(file);
}
```
or shorter
```cs
await …
```
=> Rework filesystem exception handling

Files/Filesystem/CloudProvider.cs
After #2311 this PR adds support also for Box Drive and Apple iCloud
Both are pretty simple to detect because:
- Box stores the sync path in a text file
- iCloud... does not allow the user to change the sync path
=> Add support for Box and iCloud

Files/View Models/Properties/CombinedProperties.cs, Files/View Models/Properties/FileProperties.cs, Files/View Models/Properties/FolderProperties.cs, Files/View Models/SelectedItemsPropertiesViewModel.cs, Files/Views/Pages/PropertiesGeneral.xaml
Fixes #2340
Hidden checkbox -> enabled for File, Folder and Combined properties
Read-Only checkbox -> enabled for File and Combined (if all items are files) properties as folders do not have a read-only property themselves
=> Fix crash when viewing properties for drives and multiple items

Files/Views/LayoutModes/GenericFileBrowser.xaml.cs
This fixes an issue where double clicking an item would sometimes trigger the rename option.
=> Increased the delay required to trigger double tap to rename

Files/UserControls/Widgets/DrivesWidget.xaml
=> Reduced font size for the drives widget space text

Files/Interacts/Interaction.cs, Files/View Models/ItemViewModel.cs, Files/Views/ModernShellPage.xaml.cs
For #2303
Fixes #2376
Fixes the following open points in #2303:
=> [Hidden files] - Fix opening hidden folder in new tab

Files/Helpers/NativeIoDeviceControlHelper.cs
Hi @tsvietOK 
In the current master version I get an immediate crash when trying to eject drives from Files.
Crash only happens in Release mode.
This PR solves this by defining the correct DLL for the `NativeIoDeviceControlHelper.cs->CloseHandle` function, dll taken from [here](https://docs.microsoft.com/en-us/uwp/win32-and-com/win32-apis).
Do you agree with this solution?
=> Fix CloseHandle definition

Files/View Models/ItemViewModel.cs
Fixes #2456
Fixes #2480
If the last item in a folder is hidden, no items are shown
=> Fix files not showing when show hidden items is not enabled

Files/Interacts/Interaction.cs
DefaultQuery doesn't work because it's always overwritten(?) with null property* from sortEntry.PropertyName.
Might be necessary to write custom replacement in the future to achieve full functionality.
*(or just adding null causes problems)
Fixes #2475
=> Fixed an issue where opening files wouldn't work when the directory was sorted by size or by file type

Files/Views/LayoutModes/GenericFileBrowser.xaml, Files/Views/LayoutModes/GenericFileBrowser.xaml.cs, Files/Views/LayoutModes/GridViewBrowser.xaml, Files/Views/LayoutModes/GridViewBrowser.xaml.cs
For the DataGrid layout (ListView) we no longer fire the EffectiveViewportChanged event on every item whenever they are scrolled into view. Since we now use the built-in LoadingRow event instead, this has the implication of reducing unneeded calculations for each item. It wouldn't be unreasonable to predict this change has a small, albeit positive impact on scrolling in directories with lots of rows loaded. 
Additionally, we reduce unnecessary casts with both layouts and use the FluentUI asset for the uninitialized thumbnail icon in GridView.
=> Reduce unnecessary work during extended property initialization and use new item icon in GridView

Files/Interacts/Interaction.cs
=> Fixed an issue where previously empty directories would still display "This folder is empty" after pasting an item

Files/ResourceDictionaries/PropertiesStyles.xaml, Files/UserControls/FileIcon.xaml, Files/Views/Pages/PropertiesGeneral.xaml
- Fixed file icon preview alignment
- Rounded disk space markers corners in drive properties
Fixes #2531 
Before:
After:
=> Properties: Fixed elements alignment

Files/Filesystem/FilesystemOperations/FilesystemOperations.cs, Files/Filesystem/FilesystemOperations/Helpers/FilesystemHelpers.cs
Fixed `NullReferenceException` in `IFilesystemOperations.DeleteAsync()`? (It does not crash for me but adding `?` should do the trick)
...and fixed an issue where undoing/redoing copy/move operation would only undo/redo one item
Closes #2496
=> Fixes with IFilesystemOperations

Files/Filesystem/DriveItem.cs
I've fixed annoying `NullReferenceException` not being caught in `DriveItem.UpdatePropertiesAsync()` and needed to be always Continued.
Now I can finally sleep well.
BEFORE:
AFTER:
No `NullReferenceException`
=> Improved the exception handling when updating drive properties

Files/View Models/SettingsViewModel.cs, Files/Views/LayoutModes/GenericFileBrowser.xaml
Please note, hiding a column won't work unless you toggle the item and then hide it again afterwards, this is a known issue with the setup of the SettingsViewModel and it shouldn't hold up merging this pull request.
Fixes #380
=> Added the option to hide columns in the details layout

Files/Views/Settings.xaml, Files/Views/Settings.xaml.cs
- Remove AdaptiveTrigger for window width in favor of using the `PaneDisplayMode="Auto"` setting with `CompactModeThresholdWidth="0"` for identical behavior
- Fix bug where the titlebar (custom drag region) was only set when the Settings page is first created (fixes #1498)
=> Settings: Use documented NavigationView adaptive behavior and always set title bar

Files/UserControls/SidebarControl.xaml, Files/Views/ModernShellPage.xaml
Now scrollbar is visible independently from sidebar width.
Before:
After:
=> SidebarControl: Adapt pane width to AppSettings SidebarWidth

Files/BaseLayout.cs, Files/Views/LayoutModes/GenericFileBrowser.xaml.cs, Files/Views/LayoutModes/GridViewBrowser.xaml.cs
Fixes #2510 
This PR sets the focus on the file list when changing directory so arrow keys work without the need to press TAB or click on the file list first
=> Set focus on file list when changing folder

Files.Launcher/Program.cs, Files/Filesystem/FilesystemOperations/FilesystemOperations.cs, Files/Filesystem/Search/FolderSearch.cs, Files/MultilingualResources/Files.de-DE.xlf, Files/MultilingualResources/Files.es-ES.xlf, Files/MultilingualResources/Files.fr-FR.xlf, Files/MultilingualResources/Files.he-IL.xlf, Files/MultilingualResources/Files.hi-IN.xlf, Files/MultilingualResources/Files.hu-HU.xlf, Files/MultilingualResources/Files.it-IT.xlf, Files/MultilingualResources/Files.ja-JP.xlf, Files/MultilingualResources/Files.nl-NL.xlf, Files/MultilingualResources/Files.or-IN.xlf, Files/MultilingualResources/Files.pl-PL.xlf, Files/MultilingualResources/Files.pt-BR.xlf, Files/MultilingualResources/Files.ru-RU.xlf, Files/MultilingualResources/Files.ta.xlf, Files/MultilingualResources/Files.tr-TR.xlf, Files/MultilingualResources/Files.uk-UA.xlf, Files/MultilingualResources/Files.zh-Hans.xlf, Files/MultilingualResources/Files.zh-Hant.xlf, Files/Strings/en-US/Resources.resw, Files/Strings/it-IT/Resources.resw, Files/View Models/ItemViewModel.cs, Files/View Models/SettingsViewModel.cs, Files/Views/SettingsPages/FilesAndFolders.xaml
Fixes #2590
Fixes #2307
Add an option in settings to show files/folder marked as "system". Same behavior as explorer:
- Switch has no effect unless hidden items are shown
- You can still show hidden items without showing system files
Fix an issue in which an item is removed from the list after a failed delete operation
=> Added an option to show system files

Files.Package/Files.Package.wapproj, Files.Package/priconfig.default.xml, Files.Package/priconfig.packaging.xml, Files/Files.csproj, Files/priconfig.default.xml, Files/priconfig.packaging.xml
This change might fix an issue where resource files are not installed with the app unless the user has the language pack already installed on their device.
=> Updated priconfig

Files/Filesystem/FilesystemOperations/FilesystemOperations.cs, Files/Helpers/JumpListManager.cs, Files/Helpers/RegistryHelper.cs, Files/View Models/ItemViewModel.cs, Files/View Models/SelectedItemsPropertiesViewModel.cs, Files/Views/ModernShellPage.xaml.cs, Files/Views/Pages/Properties.xaml.cs, Files/Views/SettingsPages/About.xaml.cs
Fixes #2652
This PR fixes a few crashing bugs that were detected by AppCenter for version 0.23.
Each commit fixes a specific appcenter issue, the commit name is the appcenter error number.
These has been lumped in a single PR since they are mostly one-line fixes/exception handling, let me know if this is acceptable or if should I open a PR for each of them.
6e99d4f / [681497578u](https://appcenter.ms/orgs/Files-UWP/apps/Files/crashes/errors/681497578u/overview)
Fixes an issue where the app crashes when updating the jump list
376cfbd / [1346245124u](https://appcenter.ms/orgs/Files-UWP/apps/Files/crashes/errors/1346245124u/overview)
Fixes an issue where the app crashes when navigating up
462aad7 / [2134525649u](https://appcenter.ms/orgs/Files-UWP/apps/Files/crashes/errors/2134525649u/overvie …
=> Appcenter fixes

Files/Helpers/RegistryHelper.cs, Files/Interacts/Interaction.cs, Files/UserControls/Selection/RectangleSelection_DataGrid.cs, Files/UserControls/Widgets/RecentFiles.xaml.cs, Files/View Models/ItemViewModel.cs, Files/Views/LayoutModes/GenericFileBrowser.xaml.cs, Files/Views/ModernShellPage.xaml.cs
Fixes #2680
Fixes #2652 (again)
This PR fixes some more crashing bugs that were detected by AppCenter for versions 0.23 and 0.23.1.
Each commit fixes a specific appcenter issue, the commit name is the appcenter error number.
They are mostly one-line fixes/null-checking/exception handling
ae7a748 / [1800236206u](https://appcenter.ms/orgs/Files-UWP/apps/Files/crashes/errors/1800236206u/overview)
Fixes an issue where the app crashes when loading the recent file list
41ee5bf / [3096666166u](https://appcenter.ms/orgs/Files-UWP/apps/Files/crashes/errors/3096666166u/overview)
Fixes an issue where the app crashes when enumerating folder contents
3ed4a4f / [1862552362u](https://appcenter.ms/orgs/Files-UWP/apps/Files/crashes/errors/1862552362u/overview)
Fixes an issue where the app crashes when …
=> Appcenter fixes 2

Files/BaseLayout.cs, Files/Views/LayoutModes/GridViewBrowser.xaml, Files/Views/LayoutModes/GridViewBrowser.xaml.cs
Please test GridView layout behavior (especially dragging and dropping) against the current builds to find regressions. I'm also wondering if this improves responsiveness and resource consumption in large directories.
=> GridView: Remove inefficient code and eliminate EffectiveViewportChanged event

Files/Interacts/Interaction.cs, Files/Views/LayoutModes/GenericFileBrowser.xaml.cs, Files/Views/LayoutModes/GridViewBrowser.xaml.cs
- Fixed an issue where when renaming a shortcut, its extension is cleared.
- Fixed selected name range when trying to rename shortcut.
Before:
After:
=> Shortcut: Fixed selected range and renaming

Files.Launcher/Win32API.cs, Files.Launcher/Win32API_ContextMenu.cs, Files/BaseLayout.cs, Files/UserControls/NavigationToolbar.xaml
Fixes #2695
Fixes #2683
Fixes an issue for which the "Create New File" option in the navigation bar wasn't working
Fixes an issue for which the fulltrust process crashed when querying the context menu
=> Fixes an issue with the "Create New File" option and the context menu

Files/UserControls/Selection/RectangleSelection_ListViewBase.cs
There is a race in RectangleSelection_ListViewBase where we try to
find ScrollViewer in the VisualTree upon uiElement.Loaded.
Unfortunately, Loaded might be handled before all the children
of uiElement are loaded, and in this case ScrollViewer is still not found.
When this happens we actually don't have rectangle selection available.
The idea in this PR is to register for LayoutUpdated if scroll viewer is
not found upon Loaded (and to unregister once found).
=> Make ScrollViewer lookup in Rectangle Selection robust

Files/Files.csproj, Files/UserControls/Selection/IgnorePreviousItemSelectionStrategy.cs, Files/UserControls/Selection/InvertPreviousItemSelectionStrategy.cs, Files/UserControls/Selection/ItemSelectionStrategy.cs, Files/UserControls/Selection/RectangleSelection_DataGrid.cs, Files/UserControls/Selection/RectangleSelection_ListViewBase.cs, Files/Views/LayoutModes/GridViewBrowser.xaml.cs
This PR contains several modifications:
1. Shift + Select Rectangle - will extend the existing selection as in Windows Explorer
(unlike Ctrl + Select Rectangle that inverts the existing selection).
If both Shift and Ctrl are selected, Control wins (like in Windows Explorer)
2. The decision on the strategy is done upon mouse click:
you can release Shift, Ctrl afterwards
3. The logic of Clearing Selection was removed from GridViewBrowserViewer,
so the selection strategy can make the relevant decision
=> Teach rectangle selection to extend existing selection when the Shift key is pressed

Files/Filesystem/FilesystemOperations/FilesystemOperations.cs, Files/Filesystem/FilesystemOperations/Helpers/FilesystemHelpers.cs, Files/Helpers/RecycleBinHelpers.cs
Fixes #2672
Fixes #2732
There is a significant lag on deletion, especially when numerous files are deleted.
This is significantly impacted by checking whether the file is in Recycle Bin.
This PR somewhat helps by:
* Delaying the check until the dialog presentation
(resolves the issue for those who disabled the dialog)
* Instead of searching in recycle bin just use path to decide
if the item is under recycle bin
=> Fixed an issue where there was a delay when deleting items

Files/Filesystem/FilesystemOperations/FilesystemOperations.cs, Files/Interacts/Interaction.cs
Closes: https://github.com/files-community/Files/issues/1546
Closes: https://github.com/files-community/Files/issues/1545
Breaking change: do not proceed to Deletion during Move
if Copy failed (to prevent data loss)
=> Fixed an issue where trying to move a parent directory to a child directory would crash the app

Files/Helpers/RecycleBinHelpers.cs
For some reason items in recycle bin have path in upper case:
```
C:\$Recycle.Bin\S-1-5-21-2705651487-3556957933-866194168-1001\$RHYMD0V.tdesktop-theme
V:\$RECYCLE.BIN\S-1-5-21-2705651487-3556957933-866194168-1001\$R2QN0MI.exe
```
=> Recycle Bin: Fixed recycle bin path detection

Files/UserControls/NavigationToolbar.xaml
=> Path bar: Fixed hover color in light app theme when enabled dark system theme

Files/UserControls/NavigationToolbar.xaml, Files/Views/PaneHolderPage.xaml.cs
The add pane menu in the navigation bar currently displays "ctrl + right" to open the right pane, the correct shortcut is instead *alt + shift + "+"* (or *ctrl + shift + right*)
=> Fixed suggested keyboard shortcut in navbar menu

Files/UserControls/Selection/RectangleSelection_DataGrid.cs, Files/Views/LayoutModes/GenericFileBrowser.xaml, Files/Views/LayoutModes/GenericFileBrowser.xaml.cs
Closes: https://github.com/files-community/Files/issues/2231
Root cause:
* When the user clicks outside of the AllView datagrid we manually clean the selection
* But from the datagrid perspective the "current cell" did not change
* Hence clicking on this "current cell" again triggers editing
(as per data grid specification)
Some implementation notes:
* To deselect the current cell we are forced to use reflection
as the relevant method is internal
* The PR removes "edit protections" that are not needed anymore
* The remaining protections are moved to BeginningEdit
=> Ensure current cell is deselected when clicking outside of DataGrid

Files/ViewModels/ItemViewModel.cs
When we get notified about new item we call `AddFileOrFolderAsync` 
to add the item to the view model. 
However, by the time we run, the file might not exist already
(e.g., temporary lock file created by different programs).
In this case our call to `FindFirstFileExFromApp` fails and returns
uninitialized find data. Unfortunately, we were not checking this
failure and used the invalid find data to populate the item.
As a result we got what looked like unexpected and very 
suspicious folders / files in Chinese 
(and we all know that only unexpected files in Russian are scarier).
Resolves (at least partially): https://github.com/files-community/Files/issues/2109
=> Prevent addition of item if failed to retrieve find data

Files/BaseLayout.cs, Files/Views/LayoutModes/GenericFileBrowser.xaml.cs, Files/Views/ModernShellPage.xaml.cs
This PR sets the file name column as the active DataGrid column on folder navigation, so pressing "F2" works without the need to click the list with the mouse first.
(thanks @Don-Vito for the SetCurrentCellCore method)
=> Select first DataGrid column when pressing F2

Files.Launcher/Program.cs
Fixes an issue for which deleting hidden files/folders doesn't work and make the fulltrust process crash (#2638 whopsie)
=> Fixed an issue where the full trust process would crash when deleting hidden items

Files/ViewModels/FolderSettingsViewModel.cs, Files/Views/LayoutModes/GridViewBrowser.xaml.cs
Small change after #2887
Avoid reloading icons when going from tilesview to gridview small (icon size is the same)
Use small icon size for gridview small
Increase max icon size to GridViewSizeMax
Revert changes to FolderSettingsViewModel.cs
=> Improve layout mode switching 2

Files/INavigationToolbar.cs, Files/UserControls/NavigationToolbar.xaml, Files/UserControls/NavigationToolbar.xaml.cs, Files/Views/ModernShellPage.xaml.cs
Issue was that settings it's visibility for the first time resulted in a race condition where the focus was set before the rendering cycles necessary were finished.
This PR also renames "SearchReigon" to "SearchRegion" as this was a typo.
Fixes #2982
=> Search area: Fix bug where opening the search ASB for the first time would fail to move focus

Files/Filesystem/FilesystemOperations/FilesystemOperations.cs
Fixes #2955
Currently move operation is actually a Copy + Delete.
With this PR we'd use a Move operation when possible
Also it tries *first* with the **FromApp methods and falls back to StorageFolder/File on fail
=> Improved file transfer operations

Files/Filesystem/StorageFileHelpers/StorageFileExtensions.cs, Files/ViewModels/ItemViewModel.cs, Files/Views/ModernShellPage.xaml.cs
Fixes #3073. Also fixes going up when using '/' path separators.
=> Fixed an issue where paths separated by '/' were not displaying properly

Files/BaseLayout.cs, Files/Views/LayoutModes/GenericFileBrowser.xaml, Files/Views/LayoutModes/GenericFileBrowser.xaml.cs, Files/Views/LayoutModes/GridViewBrowser.xaml, Files/Views/LayoutModes/GridViewBrowser.xaml.cs, Files/Views/ModernShellPage.xaml
We may never ship this, but these changes are reasonable and won't hurt in my opinion. This PR shouldn't break anything, but memory usage and scrolling performance should still be compared to master for potential regressions.
Addresses the part of #2843 that doesn't involve TabView at all, but item instances instead.
=> Un-initialize Drag and Drop events on items

Files/Interacts/Interaction.cs, Files/Views/ModernShellPage.xaml
Fixes #3124
Also fixes  the "copy location" button in the navigation bar being always disabled.
=> Fixed a crash that would sometimes occur when invoking the "copy location" command

Files/Views/Pages/PropertiesGeneral.xaml
=> Use accent color in drive allocation chart

Files/Interacts/Interaction.cs, Files/Views/Pages/PropertiesGeneral.xaml.cs
The PR works for single files only so far... Still no refresh when setting multiple files to hidden at once (or vice versa).
Another issue is also not fixed yet. Deletion of hidden files. The .NET library cannot directly delete hidden files and / or folders, we would need WIN32 API for that. But we can remove the hidden flag prior deletion ;-).
Fixes #2785
=> Automatically refresh view when an item visibility is changed

Files.Launcher/Program.cs
Fixes #3230
Fix for OneDrive error in FullTrust log file of issue #3230
=> Fix: Ensure OneDrive Accounts registry key is not null

Files/Views/LayoutModes/GenericFileBrowser.xaml
The bug was caused by the DataGrid being placed in the wrong row.
Also removed row/column definitions, as they are unused.
=> Fixed issue where scrolling in details view was broken

Files/App.xaml.cs, Files/Filesystem/Cloud/CloudProviderController.cs, Files/Filesystem/Cloud/ICloudProviderDetector.cs, Files/Filesystem/Cloud/Providers/AmazonDriveProvider.cs, Files/Filesystem/Cloud/Providers/AppleCloudProvider.cs, Files/Filesystem/Cloud/Providers/BoxCloudProvider.cs, Files/Filesystem/Cloud/Providers/DropBoxCloudProvider.cs, Files/Filesystem/Cloud/Providers/GoogleDriveCloudProvider.cs, Files/Filesystem/Cloud/Providers/MegaCloudProvider.cs, Files/Filesystem/Cloud/Providers/OneDriveCloudProvider.cs, Files/Filesystem/CloudDrivesManager.cs, Files/Filesystem/Drives.cs, Files/Interacts/Interaction.cs, Files/ViewModels/ItemViewModel.cs, Files/ViewModels/SettingsViewModel.cs, Files/Views/MainPage.xaml.cs, Files/Views/ModernShellPage.xaml.cs, Files/Views/YourHome.xaml.cs
This PR improves startup performance and gets the user to an interactive state quicker by making the following changes:
- `CloudDrivesManager` and `DrivesManager` have been removed from `SettingsViewModel` to allow app settings to be loaded and made available to launch the app as early as possible.
- `CloudDrivesManager` and `DrivesManager` are instantiated using an async singleton pattern with them being constructed as early as possible, while not delaying the launch of the UI should one of them require longer to complete.
- Certain initial dependencies are created in parallel to shave off a little more startup time.
- `ICloudProviderDetector`'s are loading asynchronously in parallel so that `CloudDrivesManager` only takes as long as the slowest `ICloudProviderDetector`. This is mainly …
=> Improve startup performance

Files/App.xaml.cs, Files/Filesystem/FilesystemOperations/Helpers/FilesystemHelpers.cs
Closes #3029
Images pasted are saved as pngs with the current date and time as the name.
=> Added ability to paste images from clipboard directly into folder

Files/App.xaml.cs, Files/Filesystem/DriveItem.cs, Files/Filesystem/INavigationControlItem.cs, Files/Filesystem/LocationItem.cs, Files/UserControls/SidebarControl.xaml
=> Fixed an issue where the devices FullPath would show instead of FullName on hover

Files/Filesystem/Drives.cs
Moved handling to A: and B: drives under unknown case. This will set the icons of A: (or B:) drive(s) as floppy drive if the connected media is not recognized by files. #3054 #3195
=> Changed handling of drives with letter A: or B:

Files/UserControls/PreviewPane.xaml.cs, Files/ViewModels/CurrentInstanceViewModel.cs, Files/ViewModels/Previews/HtmlPreviewViewModel.cs, Files/Views/ModernShellPage.xaml, Files/Views/ModernShellPage.xaml.cs
Closes #3252 
The issue was caused by the VisualStateManager attempting to change the properties of the Pane while it was closed, which would load it in.
Changing the layout programmatically instead fixes this issue.
This PR also includes a fix for an issue where Html previews would not load.
=> Fixed issue where preview pane would open itself after switching tabs or closing settings

Files/ViewModels/ItemViewModel.cs
Instead of calling `ApplyFilesAndFoldersChangesAsync` directly after each filesystem change, accumulate those changes and update them one time with an interval sampler to improve performance while occurring a large set of entries changes.
=> Improve performance while occurring a large set of entry changes

Files/Helpers/BulkConcurrentObservableCollection.cs, Files/UserControls/Selection/RectangleSelection_ListViewBase.cs, Files/Views/LayoutModes/GridViewBrowser.xaml.cs
Make use of SyncRoot to reduce unnecessary semaphores in BulkConcurrentObservableCollection.
I found there's no need to implement lock manually, there's already built-in `SyncRoot` for this (inspired by `SynchronizedCollection<T>`).
Fixes #3371
Note: it's no longer safe if you try to enumerate it without neither `lock (list.SyncRoot)` nor `.ToList()`
=> Reduce scrolling stutters

.github/workflows/codeql-analysis.yml
After stumbling over this project recently and seeing that #3346 was closed, I decided to give this a try. (I like CI)
This PR adds a basic CodeQL workflow with the default scanning queries for `c++` and `c#`.
It utilizes a basic dependency cache to slightly speed up the workflow, however still has a runtime of ~25min as a whole.  
* adds a CodeQL workflow
* n/a?
=> ci(code-scanning): add CodeQL workflow

Files/Helpers/FileListCache/PersistentSQLiteCacheAdapter.cs
New PR for the bug in #3381 with @gave92's suggested alternative changes.
This pr fixes an issue where Shortcut items would not be cached properly.
The issue was caused by the Json converter serializing and de-serializing the shortcut as a ```ListedItem```, not as a ```ShortcutItem```. When the cache was then read, Files would treat the shortcut like a normal file, instead of as a shortcut. 
This would cause the details page instead of the shortcut page to be shown in the properties window when a shortcut was selected, and also caused a minor issue with #3349. 
Attempting to navigate to the details page would then cause a crash, since StorageFile doesn't work with shortcuts.
This PR fixes that by adding the preserve type setting to the Json serializer.
=> Fixed issue where shortcut items would not be cached properly

Files/UserControls/FilePreviews/ImagePreview.xaml
This PR is about to wrap Image in a Viewbox with `StretchDirection="DownOnly"` in the image preview control to allow images stretch just until their size is downscaled.
Scaling an image over the size degrades recognizability of its content.
=> Don't scale image previews over their size

Files/Interacts/Interaction.cs
=> Fixes an issue that prevented some folders from opening

Files/Helpers/FileListCache/PersistentSQLiteCacheAdapter.cs
It turns out I was very wrong, the de-serializer does need a type setting specified in order for the shortcuts to be read from cache properly.
I apologize for this mistake.
=> Added type setting for de-serializer

Files/UserControls/Selection/RectangleSelection.cs, Files/UserControls/Selection/RectangleSelection_DataGrid.cs, Files/UserControls/Selection/RectangleSelection_ListViewBase.cs
=> Limit selection rectangle width based on the actual size of the grid/list view

Files/ViewModels/ItemViewModel.cs
This PR is for hiding some texts at the beginning of the loading process of directory contents.
They represent a temprorary state when items are about to load, and can confuse users – maybe make them exit a directory without waiting enough time to load if it was slow for some reason. The loading progress bar is visible on the top, but the "This folder is empty." text around the center is easier to notice.
The second change is about hiding the item counter at the bottom, but this might be not so important.
Affected texts:
- *This folder is empty.* - visible on the main panel, when the actual directory is empty
- *0 items* - item counter on the status bar
=> Hide This folder is empty text on load

Files/Filesystem/FilesystemOperations/FilesystemOperations.cs
Fixes #3355 
Fixes (maybe) #3530
Avoid freezing app when copying/moving big files.
=> Execute copy/move on background thread

Files/Files.csproj, Files/ViewModels/ItemViewModel.cs, Files/Views/Pages/Properties.xaml.cs
After some investigation, there's no need to dispose CancellationTokenSource manually if `LinkedTokenSource` was not used, so just let GC dispose CancellationTokenSource to prevent ObjectDisposedException.
=> Fix ObjectDisposedException in CancellationTokenSource

Files/Views/ModernShellPage.xaml, Files/Views/ModernShellPage.xaml.cs
=> F1 shortcut now opens the Files Wiki

Files/Interacts/Interaction.cs, Files/ViewModels/ItemViewModel.cs, Files/Views/LayoutModes/GenericFileBrowser.xaml.cs, Files/Views/LayoutModes/GridViewBrowser.xaml.cs
Fixes #3623
Grrr this one keeps eluding me -> #3531
Is anyone able to reproduce it consistently? @XPoppyX I've seen you are getting the stacktrace below?
```cs
2021-02-10 16:23:36.7113|ERROR|.ctor|Index larger than max value.
Parameter name: index|System.ArgumentOutOfRangeException: Index larger than max value.
Parameter name: index
at System.Runtime.InteropServices.WindowsRuntime.IVector_CCWAdapter.EnsureIndexInt32(UInt32, Int32) + 0x74
at System.Runtime.InteropServices.WindowsRuntime.IBindableVector_CCWAdapter.GetAt(IList, UInt32) + 0x26
at System.Collections.IList__Impl.Vtbl.GetAt__n(IntPtr, UInt32, Void**) + 0x3e
at System.Runtime.InteropServices.McgMarshal.ThrowOnExternalCallFailed(Int32, RuntimeTypeHandle) + 0x21
at __Interop.ComCallHelpers.Call(__ComObject, RuntimeTypeHandle, …
```
=> Fixes for version 1.3

Files/Views/LayoutModes/GenericFileBrowser.xaml.cs, Files/Views/LayoutModes/GridViewBrowser.xaml.cs
Fixes #2463
Do not move selection to the next file on Alt+Enter (#2463)
Fixes Alt + Arrow shortcuts to navigate back/forward/up which are not working (at least for me)
=> Fix some issues with keyboard shortcuts

Files/Helpers/DynamicDialogFactory.cs
1. Open a folder in Files.
2. Right click and select `New -> anything` in context menu.
3. The dialog that request the item name is pop up.
We have to click the text box or press `Tab` key to move the focus.
The text input is auto focused.
=> Focus text input when dialog opened.

Files/UserControls/PreviewPane.xaml
This changes the preview pane content alignment from center to stretch.
Having it center aligned looks bad with text.
=> Fix preview pane content alignment

Files/ViewModels/PreviewPaneViewModel.cs, Files/ViewModels/Previews/BasePreviewModel.cs
This bug was introduced in #3639 which changed from fire-and-forget in the constructor to awaiting a load function after initialization. This was not done for extensions, which lead to them not being loaded.
=> Fixed bug where details wouldn't be loaded from extensions in the preview pane

Files/MultilingualResources/Files.de-DE.xlf
This PR corrects a wrong translation in German ("QuickLook" was translated as "Links") in the context menu.
---
Closes #3839
=> Correct wrong translation for QuickLook in German (Closes #3839)

Files/UserControls/NavigationToolbar.xaml, Files/UserControls/StatusBarControl.xaml, Files/Views/LayoutModes/GenericFileBrowser.xaml, Files/Views/LayoutModes/GridViewBrowser.xaml
Closes #3870
**Changes:**
- New icons for layout modes (Status bar + Context menu)
- New icon for Preview / Details button (Navigation bar)
- New icon for "Open in Terminal..." in context menu
- New icon for "Open with" in context menu
- New icon for "Invert selection" (Status Bar)
- Fixed alignment of layout mode icons
-----------------------
Preview/Details pane
Context menu/ Open in Terminal...
Layout mode icons
Layout mode icons alignment
Invert selection
Context menu/Open with
---------------
Preview/Details pane
Context menu/ Open in Terminal...
Layout mode icons
Layout mode icons alignment
Invert selection
Context menu/Open with
---------
All icons are from **"Segoe fluent icons"**
-----------------
_I would like to update other icons such as "open in new tab / window" and others …
=> Update some icons

Files/UserControls/PreviewPane.xaml
One of the icons currently is not present in the new Segoe Fluent Icons. 
This switches the icon to the fluent gripper icons.
New icons:
=> Switched icon for preview pane gripper

Files/App.xaml, Files/UserControls/MultitaskingControl/HorizontalMultitaskingControl.xaml, Files/UserControls/Widgets/DrivesWidget.xaml, Files/UserControls/Widgets/LibraryCards.xaml
(After vs Before) We switch away from adding a drop shadow panel to every tab and instead use a border which simulates elevation.
Will remove commented markup shortly...
=> Use WinUI shadow border with selected TabViewItems

Files/Constants.cs
Having it so high can cause an out of memory exception on lower end devices and takes up a lot of resources in general.
Likely fixes this:
https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/3565178931u/overview
=> Lowered PDF preview page limit 

Files/Helpers/FileThumbnailHelper.cs
Before it was loading a new one each time, which I think may have caused other issues after continued use.
=> Use single instance of AppServiceConnection for preview pane thumbnails

Files/UserControls/StatusCenter.xaml.cs
Fix for https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/3768192674u/overview:
```
StatusCenter_obj17_Bindings.Update_FullTitle (String obj, Int32 phase)
D:\a\1\s\Files\obj\x64\Release\UserControls\StatusCenter.g.cs at 566, line 29
System.ArgumentNullException: Null strings may not be marshaled in Windows Runtime arguments. Parameter name: sourceString
```
I believe the issue was caused by a null value being passed to AutomationProperties.Name, which binds to FullTitle.
=> Prevent FullTitle string from being null in StatusCenter.cs

Files/Helpers/FileThumbnailHelper.cs
Reverts files-community/Files#4014
As @gave92 pointed out, a new connection was not being created each time, which was the motive for the original pr, and also that the new method would cause more issues when the app is restored from suspension.
I apologize for this mistake.
=> Revert "Use single instance of AppServiceConnection for preview pane thumbnails"

Files/Views/LayoutModes/GenericFileBrowser.xaml.cs
I noticed that this would, on occasion, throw something like ```Argument Exception: Row index could not be found```, which would cause a crash.
This PR adds a catch for that.
=> Fixed issue where ScrollIntoView could throw argument exception

Files/ViewModels/PreviewPaneViewModel.cs
This fixes an issue where wrong content would be shown if the user selected another item before the current item finished loading.
=> Implement preview load cancellation

Files/Filesystem/NetworkDrivesManager.cs
Closes #3924 
I just added an additional check before creating the network drive LocationItem.
This is my first PR, feedback is appreciated 🙂
=> Hide network section in sidebar when no drives are detected

Files/Views/Pages/PropertiesDetails.xaml
Closes #3444 
Moved the clear properties button from the bottom of the list to the bottom of the page.
**Validation**
=> Moved clear all properties button to bottom of page

Files/Filesystem/Drives.cs
Fixes #4152
Fixes #4088
Fixes an issue for which drives are not removed from sidebar / homepage when disconnected.
Adds a check in `SyncSideBarItemsUI` to remove drives when syncing `MainPage.SideBarItems` to the `Drives` list.
**Validation**
=> Fixes an issue for which drives are not removed from sidebar when disconnected

Files/Filesystem/WSLDistroManager.cs
Fixes #4164
Fixes an issue for which duplicate WSL sections appeared on sidebar.
Adds a check in `WSLDistroManager\SyncSideBarItemsUI()` to skip adding WSL section if already exists.
To reproduce the bug: open Files and then launch a folder from the taskbar,
**Validation**
=> Fixes an issue for which duplicate WSL sections appeared on sidebar

Files/BaseLayout.cs, Files/UserControls/NavigationToolbar.xaml.cs, Files/UserControls/SidebarControl.xaml.cs, Files/Views/LayoutModes/GenericFileBrowser.xaml.cs
Dragging and hovering on a folder / sidebar item is currently broken since timers actions are not invoked on the UI thread.
This caused, among others, #4158.
Properly create timers so they invoke the action on the UI thread.
**Validation**
=> Fix crash due to wrong thread exception

Files/App.xaml.cs, Files/UserControls/MultitaskingControl/HorizontalMultitaskingControl.xaml, Files/UserControls/MultitaskingControl/HorizontalMultitaskingControl.xaml.cs, Files/UserControls/SidebarControl.xaml, Files/UserControls/SidebarControl.xaml.cs, Files/Views/MainPage.xaml.cs
Fixes #4062
Fixes an issue for which "close tab to the right" was sometimes improperly enabled by moving the enable logic from the `Opening` to the `DataContextChanged` event.
This PR also moves the `RightClickedItem` from App to SidebarControl (RightClickedItem does not need to be global/static).
**Validation**
=> Fixes an issue for which "close tab to the right" was sometimes improperly enabled 

Files.Launcher/Program.cs, Files/BaseLayout.cs
Fixes #4114
Fixes an issue for which the UAC prompt was shown when opening .url shortcuts.
Does not seem to be breaking anything else (e.g opening exe files)
**Validation**
=> Fixes an issue for which the UAC prompt was shown when opening .url shortcuts

Files.Launcher/Program.cs, Files/Filesystem/ListedItem.cs, Files/Helpers/AppServiceConnectionHelper.cs, Files/Views/LayoutModes/GenericFileBrowser.xaml.cs, Files/Views/LayoutModes/GridViewBrowser.xaml.cs
- Fixes an issue for which the FTP remains open when the UWP app terminates.
- Fixes an issue that causes a lot of warnings to be written to the log files ("No parameterless constructor for object..")
- Fixes an issue that sometimes causes a crash when switching folder
**Validation**
=> Exit fulltrust process on UWP crash

Files/ViewModels/PreviewPaneViewModel.cs
Seemed too minor to make an issue for. 
Basically, the selected items list would register a change when there wasn't one when scrolling, which caused the preview pane to reload.
Prevents the property changed notification for SelectedItems from being raised when the selection is the same.
**Validation**
=> Fixed issue where file preview could reload while scrolling

Files/ViewModels/Previews/ShortcutPreviewViewModel.cs
The wrong string was being shown in the preview pane for arguments.
Changed referenced resource name.
**Validation**
=> Fixed wrong text shown for item arguments

Files/Helpers/StorageItemHelpers.cs
This PR improves the code and speed of `ToStorageItem<TOut>()`.
Since getting instances of `StorageFile` and `StorageFolder` is resource heavy and slow, this PR mitigates the performance hole as much as possible.
Bundles widget heavily relies on this function and the performance increase is ***very*** noticeable (It's "you could test debug app against release app" noticeable)
For #4180
**Validation**
=> Improved the code and speed of ToStorageItem<TOut>()

Files/Helpers/ContextFlyoutItemHelper.cs
Fixed issue mentioned in #4190.
Added command parameters (true), which were required.
**Validation**
=> Fixed issue where layout mode options would be disabled

Files/Constants.cs, Files/Filesystem/DriveItem.cs, Files/Strings/en-US/Resources.resw, Files/UserControls/Widgets/DrivesWidget.xaml, Files/UserControls/Widgets/DrivesWidget.xaml.cs
- Closes #3540 
This PR adds a button to a drive that's nearly full (<10%) that opens Storage Sense
**Validation**
=> Added the option to open Storage Sense on drives widget

Files/Helpers/ContextFlyoutItemHelper.cs
Fixed issue where empty recycle bin option would not be shown.
Also fixed glyph.
Added prop to show empty recycle bin in recycle bin. 
**Validation**
=> Fixed issue where empty recycle bin option would not be shown

Files/Files.csproj, Files/Helpers/Fractions.cs, Files/Resources/PreviewPanePropertiesInformation.json, Files/Resources/PropertiesInformation.json, Files/Strings/en-US/Resources.resw, Files/UserControls/PreviewPane.xaml, Files/ViewModels/Previews/TextPreviewViewModel.cs, Files/ViewModels/Properties/FileProperty.cs
- Fixes an issue I noticed where empty files would be loaded as text files, even if they were not text files. 
- Moves the date taken property down with the date modified and date created property.
- Displays the exposure property as a fraction
- Fix alignment of gripper icon in horizontal layout
- Show exposure time as fraction instead of as a decimal 
- Closes #4444
- Don't run ```TryLoadAsText``` on empty files, as it will always think the file is a text file, instead just show the thumbnail.
- Move "date taken" below date modified and date created
- Show exposure time as a fraction instead of as a decimal, and add helper extensions to convert doubles to a fraction (the fractions are inaccurate, I think the storage file properties …
=> Preview pane improvements & fixes

Files/Views/LayoutModes/ColumnViewBase.xaml.cs, Files/Views/LayoutModes/ColumnViewBrowser.xaml.cs, Files/Views/LayoutModes/GenericFileBrowser.xaml.cs, Files/Views/LayoutModes/GridViewBrowser.xaml.cs
Resolves a NullReferenceException that could be thrown when quickly switching through several directories.
```
2021-04-02 21:02:42.8482|ERROR|.ctor|Object reference not set to an instance of an object.|System.NullReferenceException: Object reference not set to an instance of an object.
at Files.Views.LayoutModes.GenericFileBrowser.AddSelectedItem(ListedItem) + 0x5a
at Files.BaseLayout.SetSelectedItemOnUi(ListedItem) + 0x25
at Files.Views.ModernShellPage.FilesystemViewModel_ItemLoadStatusChanged(Object, ItemLoadStatusChangedEventArgs) + 0x403
at Microsoft.Toolkit.Uwp.UI.Controls.InAppNotificationOpeningEventHandler.Invoke(Object, InAppNotificationOpeningEventArgs) + 0x2e
at Files.ViewModels.ItemViewModel.<RapidAddItemsToCollectionAsync>d__104.MoveNext() + …
```
=> Fix for NullReferenceException in AddSelectedItem that could occur when quickly switching directories

Files/BaseLayout.cs, Files/ViewModels/SelectedItemsPropertiesViewModel.cs
Fixed issue where set as options wouldn't show for images
The function that updates ```IsItemImage``` in ```SelectedItemsPropertiesViewModel``` wasn't getting called. This PR calls it in the flyout opening function, and also removes the unnecessary await task.
**Validation**
- [N/A] Tested the changes for accessibility
=> Fixed issue where set as options wouldn't show for images

Files/Views/LayoutModes/GridViewBrowser.xaml.cs
In MultiSelect mode, a double tap/click on a item opens the item.
The expected behavior is to click twice on the selection checkbox.
#4437
Add a test in the DoubleTap event for to do nothing in multiselect mode.
=> Fixed MultiSelect DoubleTap (#4437)

Files/BaseLayout.cs, Files/Filesystem/Search/FolderSearch.cs, Files/IShellPage.cs, Files/Interacts/BaseLayoutCommandImplementationModel.cs, Files/Interacts/BaseLayoutCommandsViewModel.cs, Files/Interacts/IBaseLayoutCommandImplementationModel.cs, Files/Strings/en-US/Resources.resw, Files/ViewModels/CurrentInstanceViewModel.cs, Files/Views/ColumnShellPage.xaml.cs, Files/Views/LayoutModes/ColumnViewBrowser.xaml, Files/Views/LayoutModes/GenericFileBrowser.xaml, Files/Views/LayoutModes/GridViewBrowser.xaml, Files/Views/ModernShellPage.xaml.cs
- Closes #4278 
- Added parameter for searching unindexed items to folder search helper
- Moved search navigation code to a single function to invoke a search
- Added button to bottom of search results to search unindexed items, that is shown when the previous search was not unindexed
**Validation**
https://user-images.githubusercontent.com/59544401/113669666-ed7ba280-9668-11eb-8072-62d9a4b26bf4.mp4
=> Added search unindexed items option at bottom of search results

Files/UserControls/Widgets/LibraryCards.xaml
The library card text was overlapping its item image
Changed whole word wrapping to text truncating in library card text.
**Validation**
=> Fixed text overlapping in library card

Files/UserControls/Widgets/DrivesWidget.xaml, Files/UserControls/Widgets/DrivesWidget.xaml.cs
Middle click opens drives in new tab.
CTRL + Left click opens drives in new tab.
In widget page only
Not yet implemented in the SideBar.
CTRL + Left click is implemented for drives only.
=> open drive in new tab with middle click

Files/UserControls/MultitaskingControl/HorizontalMultitaskingControl.xaml.cs, Files/UserControls/MultitaskingControl/VerticalTabViewControl.xaml.cs, Files/ViewModels/InteractionViewModel.cs, Files/ViewModels/MainPageViewModel.cs, Files/Views/ColumnShellPage.xaml.cs, Files/Views/ModernShellPage.xaml.cs
Opening a new tab keeps you on the current tab.
Opening a standard new tab (button add new tab, ctrl+t) active the new tab immediately.
#4506 and closes #2512
The new tab is loaded only when it becomes visible. We can change this later, probably managed by a user parameter.
=> Improved behavior when opening new tabs

Files/UserControls/Widgets/LibraryCards.xaml, Files/UserControls/Widgets/LibraryCards.xaml.cs
Middle click opens libraries in new tab.
CTRL + Left click opens libraries in new tab.
In widget page only.
Not yet implemented in the SideBar.
CTRL + Left click is implemented for libraries only.
=> Library widgets new tab button

Files/App.xaml
- Closes nothing, no corresponding issue found
- Related https://github.com/microsoft/microsoft-ui-xaml/issues/4759
- Seems that in our configuration, the Version 2 styles are causing issues, so we are removing them now and as such fix the release build crashing on launch
**Validation**
=> Fix crash in release by switching to version 1 WinUI styles

Files/Helpers/ContextFlyoutItemHelper.cs, Files/Helpers/SecondaryTileHelper.cs, Files/Interacts/BaseLayoutCommandImplementationModel.cs
- Closes #4567 
- Windows will throw an error if the tile id is too long, so if the tile ID is too long, split it in half.
- Also resolves an issue where you couldn't pin folders with very long paths
- Added the pin to start option to the base menu items
**Validation**
In the future we may want to show the colored icon, but that should get it's own PR later.
=> Allow libraries to be pinned to Start

Files/Files.csproj, Files/Filesystem/ListedItem.cs, Files/Strings/en-US/Resources.resw, Files/ViewModels/ColumnsViewModel.cs, Files/ViewModels/FolderSettingsViewModel.cs, Files/ViewModels/ItemViewModel.cs, Files/ViewModels/SettingsViewModel.cs, Files/ViewModels/SettingsViewModels/ExperimentalViewModel.cs, Files/Views/ColumnShellPage.xaml.cs, Files/Views/LayoutModes/GenericFileBrowser2.xaml, Files/Views/LayoutModes/GenericFileBrowser2.xaml.cs, Files/Views/ModernShellPage.xaml.cs, Files/Views/SettingsPages/Experimental.xaml
This could probably solve some of the Needs-Winui-DataGrid issues.
This PR adds a list view based details view, which can be enabled in the experiments settings page. 
For now I think this should be kept as an experiment until it reaches feature parity with the DataGrid and the bugs are worked out, but I believe it should be ready by 2.0.
**Validation**
- double click name to rename
- click header to sort, click again to toggle direction
- resize columns
- context menus
- Hide status column in non-cloud drive folders
- Recycle bin sort options
- virtualized
- smooth scrolling
- will be updated with WinUI 2.6 styles
- DataGrid doesn't allow for automation properties
- multiselect …
=> Experimental list view based details view

Files/UserControls/SidebarControl.xaml, Files/UserControls/SidebarControl.xaml.cs
In sidebar, middle click opens item in new tab.
#4510
Ctrl+Left is not active because this was causing unexplained crashes. 
It may be related to #4551, because the crashes always concerned the documents.
=> In sidebar, middle click opens item in new tab

Files/Helpers/ContextFlyoutItemHelper.cs, Files/Helpers/ItemModelListToContextFlyoutHelper.cs, Files/Interacts/BaseLayoutCommandImplementationModel.cs
- Resolves #2952
Added "paste" to the item menu items as described in the mentioned issue.
The option is only displayed if a single folder is selected.
If multiple folders or e.g. a file are selected, then the option is not displayed.
If the clipboard is empty then the option is disabled.
The "Ctrl + V" command is not affected by this change.
https://user-images.githubusercontent.com/56681014/114279764-8da14500-9a36-11eb-9d93-c29a49751678.mp4
=> Add "paste" to the item menu items

Files/Helpers/ShellContextMenuHelper.cs
- Fixes #3855
- This adds a 10 second timeout to the operation that gets the shell context menu items. This should prevent Files from completely freezing up if the operation hangs
**Validation**
- I have tested this by adding a ```Task.Delay()``` in the ```SendMessageForResponseAsync``` function to make sure it times out properly
=> Fix Files sometimes freezing after right clicking an item

Files/BaseLayout.cs, Files/Views/LayoutModes/ColumnViewBase.xaml, Files/Views/LayoutModes/ColumnViewBrowser.xaml, Files/Views/LayoutModes/GenericFileBrowser.xaml, Files/Views/LayoutModes/GenericFileBrowser2.xaml, Files/Views/LayoutModes/GridViewBrowser.xaml, Files/Views/LayoutModes/GridViewBrowser.xaml.cs
- Closes #673
- For all list view based layout modes (aka all but DataGrid), use built in drag and drop instead of the custom one currently used
This does not work with the DataGrid, but if we plan to switch to the ListView one anyway I don't think it's an issue.
**Validation**
**Note**
Most of the column view file changes are the xaml auto formatter (that's also why this PR is so large xD).
=> Allow dragging items without selecting them first

Files/Filesystem/FilesystemOperations/Helpers/FilesystemHelpers.cs
https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/2619919200u/overview
- I believe this will solve [this](https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/2619919200u/overview) crash, and make it easier to figure out the root cause of the issue in the future.
- Added try catch around delete operations, and log any exceptions caught to the app log
**Validation**
=> Fix crash that can occur when deleting items

Files/Converters/VisiblityInvertConverter.cs, Files/UserControls/NavigationToolbar.xaml, Files/UserControls/NavigationToolbar.xaml.cs
Fix Text overlapping on search bar. 
Fixes #4369
When a popup is open, the search bar is close.
When the searchbar is visible, the adressbar is collapsed.
=> Fix search region visual (#4369)

Files/ViewModels/PreviewPaneViewModel.cs, Files/ViewModels/Previews/ShortcutPreviewViewModel.cs
N/A
- Don't try and use backup item preview if the item is a shortcut or folder, as it can cause an unhandled exception 
- Only use FTP to load shortcut thumbnails (since trying to use the StorageFile one would blow up for obvious reasons)
**Validation**
=> Fix potential crash when initial shortcut or folder preview loading fails

Files/Helpers/NavigationHelpers.cs
- https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/985932119u/overview
- Added try catch around OpenPath, and log the exception to the logger to make it easier to debug in the future
- Added null check to app service connection when opening shortcuts (I doubt this caused the crash, however I believe it's a good change anyway)
**Validation**
- [N/A] Tested the changes for accessibility
=> Fix NullReferenceException in Files.Helpers.NavigationHelpers.OpenSelectedItems

Files/DataModels/SidebarPinnedModel.cs, Files/Extensions/ImageSourceExtensions.cs, Files/Files.csproj, Files/Filesystem/DriveItem.cs, Files/Filesystem/LibraryLocationItem.cs, Files/Filesystem/ListedItem.cs, Files/Filesystem/LocationItem.cs, Files/Filesystem/StorageEnumerators/UniversalStorageEnumerator.cs, Files/Helpers/GlyphHelper.cs, Files/UserControls/FileIcon.xaml, Files/UserControls/FileIcon.xaml.cs, Files/UserControls/Widgets/LibraryCards.xaml.cs, Files/ViewModels/ItemViewModel.cs, Files/ViewModels/Properties/DriveProperties.cs, Files/ViewModels/Properties/FileProperties.cs, Files/ViewModels/Properties/FolderProperties.cs, Files/ViewModels/Properties/LibraryProperties.cs, Files/ViewModels/SelectedItemsPropertiesViewModel.cs, Files/Views/Pages/PropertiesGeneral.xaml, Files/Views/Pages/PropertiesShortcut.xaml
- Closes #4639 
- closes #4628 
- closes #4591
- Remove all calls to ImageSource properties in the properties dialog as they are not thread safe and would cause a crash
- obtain images from uri source or byte array
**Validation**
=> Fixed crashes when opening properties dialog

Files/Files.csproj, Files/Filesystem/FilesystemOperations/Helpers/FilesystemHelpers.cs, Files/Helpers/SaveImageToFile.cs
- Closes #4609
- Encode images as pngs before saving them as png files
**Validation**
=> Fix issue where images wouldn't always be saved with the right encoding

Files/Views/LayoutModes/GridViewBrowser.xaml
Fix rename background in grid view. #4229
Before, the original name was visible behind the new name. 
The initial text is collapsed in rename mode.
=> Fix rename background #4229

Files/MultilingualResources/Files.ar.xlf, Files/MultilingualResources/Files.cs-CZ.xlf, Files/MultilingualResources/Files.da-DK.xlf, Files/MultilingualResources/Files.da.xlf, Files/MultilingualResources/Files.de-DE.xlf, Files/MultilingualResources/Files.es-ES.xlf, Files/MultilingualResources/Files.fr-FR.xlf, Files/MultilingualResources/Files.he-IL.xlf, Files/MultilingualResources/Files.hi-IN.xlf, Files/MultilingualResources/Files.hu-HU.xlf, Files/MultilingualResources/Files.it-IT.xlf, Files/MultilingualResources/Files.ja-JP.xlf, Files/MultilingualResources/Files.ko-KR.xlf, Files/MultilingualResources/Files.lv-LV.xlf, Files/MultilingualResources/Files.nl-NL.xlf, Files/MultilingualResources/Files.or-IN.xlf, Files/MultilingualResources/Files.pl-PL.xlf, Files/MultilingualResources/Files.pt-BR.xlf, Files/MultilingualResources/Files.pt-PT.xlf, Files/MultilingualResources/Files.ru-RU.xlf, Files/MultilingualResources/Files.sv-SE.xlf, Files/MultilingualResources/Files.ta.xlf, Files/MultilingualResources/Files.tr-TR.xlf, Files/MultilingualResources/Files.uk-UA.xlf, Files/MultilingualResources/Files.zh-Hans.xlf, Files/MultilingualResources/Files.zh-Hant.xlf
The translations of the MultiSelect menu do not use the correct id.
These translation texts are not used and this menu always appears in English. 
Change id in all files xlf.
=> Fix texts of multiselect menu

Files.Launcher/Program.cs
The folder Recycle.Bin use the bad case.
This prevents name comparison (in RemoveFileOrFolderAsync)
Recycle bin doesn't refresh when deleting.
#4640 #4733
Change case of folder Recycle.Bin
=> fix recycle bin case

Files/Views/Pages/PropertiesLibrary.xaml
In the menu Library Properties, the  label "No locations" is always visible.
It should only be visible if the library is empty.
Change mode of binding of the property IsLibraryEmpty.
**Validation**
before
after
=> Fix LibraryNoLocations Visibility

Files/BaseLayout.cs, Files/IShellPage.cs, Files/Views/ColumnShellPage.xaml, Files/Views/ColumnShellPage.xaml.cs, Files/Views/ModernShellPage.xaml, Files/Views/ModernShellPage.xaml.cs, Files/Views/WidgetsPage.xaml.cs
- Closes #4752 
- Add local field for preview pane enabled so that the state can vary across panes 
- Don't load preview pane on the home page instead of collapsing it (may improve startup speed slightly)
- Move x:load to the preview pane drop shadow from the preview pane itself
**Validation**
=> Fix unexpected behavior when toggling preview pane in dual pane mode

Files/UserControls/MultitaskingControl/HorizontalMultitaskingControl.xaml
- Switched from ```SolidBackgroundFillColorQuarternary``` to ```SolidBackgroundFillColorTertiary``` brushes for the tab background
- Hide tab separator when in selected state
**Validation**
Before:
After:
Dark mode:
=> Fix selected tab header background color in light mode and hide separator when selected 

Files/Views/ModernShellPage.xaml.cs
- Update the layout when ```LoadPreviewPaneChanged()``` is called
**Validation**
After:
Before:
=> Fix issue where preview pane row/column would not be collapsed after navigating to the home page

Files/Views/LayoutModes/ColumnViewBase.xaml.cs, Files/Views/LayoutModes/ColumnViewBrowser.xaml.cs
Fixes an issue for which double clicking on a folder in columnview does not add a new column.
Changes the check to test if an item is a folder to use the PrimaryItemAttribute property instead of ItemType which only works if windows language is set as English.
**Validation**
=> Fixes an issue for which opening a folder in ColumnView did not add a new column

Files/Filesystem/LibraryManager.cs, Files/UserControls/Widgets/DrivesWidget.xaml.cs, Files/UserControls/Widgets/LibraryCards.xaml.cs
Fixes #4800
Does not reset the Libraries collection when syncing sidebar items
Fixes a few warnings related to async methods not being awaited
**Validation**
=> Do not reload sidebar library items

Files.Launcher/Program.cs, Files.Launcher/Win32API.cs, Files/UserControls/Widgets/LibraryCards.xaml.cs, Files/ViewModels/ItemViewModel.cs, Files/Views/WidgetsPage.xaml.cs
Loads library icons from the shell faster by getting them in a smaller size without much difference in quality. Also, never look for overlays for the library widget.
**Validation**
=> Get smaller size icons (48 vs 128), never look for overlays

Files/UserControls/SidebarControl.xaml.cs
In the sidebar, ctrl + click opens the items in the current tab instead of a new tab.
#4511
In the sidebar, opens the item in a new tab with ctrl + click.
This version fix the crash with the group headers.
**Validation**
=> Open new tab with ctrl + click in sidebar

Files/BaseLayout.cs, Files/Converters/DateTimeOffsetToString.cs, Files/Converters/DoubleToString.cs, Files/Converters/UInt32ToString.cs, Files/Dialogs/BitlockerDialog.xaml, Files/Helpers/StorageItemHelpers.cs, Files/Helpers/WidgetsHelpers.cs, Files/Interacts/BaseLayoutCommandImplementationModel.cs, Files/UserControls/FileIcon.xaml, Files/UserControls/FilePreviews/FolderPreview.xaml, Files/UserControls/SidebarControl.xaml, Files/UserControls/Widgets/LibraryCards.xaml, Files/ViewModels/BaseJsonSettingsViewModel.cs, Files/ViewModels/Widgets/Bundles/BundleContainerViewModel.cs, Files/ViewModels/Widgets/Bundles/BundlesViewModel.cs, Files/Views/LayoutModes/ColumnViewBase.xaml.cs, Files/Views/LayoutModes/ColumnViewBrowser.xaml.cs
Fix easy warnings
Fix warnings:
- Unused variables
- Unused exceptions
- Unused binding mode OneWay
- Obsolete property IsPasswordRevealButtonEnabled is contained in PasswordRevealMode
- default(type) -> default
=> Fix easy warnings

Files/App.xaml, Files/DataModels/NavigationControlItems/LocationItem.cs, Files/DataModels/SidebarPinnedModel.cs, Files/Filesystem/CloudDrivesManager.cs, Files/Filesystem/LibraryLocationItem.cs, Files/Filesystem/ListedItem.cs, Files/Filesystem/WSLDistroManager.cs, Files/Helpers/FileThumbnailHelper.cs, Files/UserControls/SidebarControl.xaml, Files/ViewModels/SelectedItemsPropertiesViewModel.cs
- Fixed issue with NavigationView having a large margin set for its ContentPresenter
- Get filesystem thumbnails for pinned items
- Increases icon size to 20px for navigation surfaces like the sidebar
- Get custom icons for SyncFolder of cloud-based storage providers
**Validation**
=> Assorted sidebar icons work

Files/App.xaml.cs, Files/BaseLayout.cs, Files/Filesystem/FilesystemOperations/Helpers/FilesystemHelpers.cs, Files/Helpers/PostBannerHelpers.cs, Files/IBaseLayout.cs, Files/IShellPage.cs, Files/UserControls/StatusBarControl.xaml, Files/UserControls/StatusBarControl.xaml.cs, Files/UserControls/StatusCenter.xaml, Files/ViewModels/AdaptiveSidebarViewModel.cs, Files/ViewModels/StatusCenterViewModel.cs, Files/Views/ColumnShellPage.xaml, Files/Views/ColumnShellPage.xaml.cs, Files/Views/MainPage.xaml, Files/Views/MainPage.xaml.cs, Files/Views/ModernShellPage.xaml, Files/Views/ModernShellPage.xaml.cs, Files/Views/PaneHolderPage.xaml
- Closes #4600
- Move StatusBarControl to MainPage.xaml
- Move StatusCenterViewModel to App.xaml.cs from IShellPage so that it's accessible throughout the app
- Make StatusCenterViewModel.StatusBannersSource not static since it's now the same instance across the app
- Defer status bar loading until after the page has loaded
~~All that's left for this PR is to fix an issue where bindings aren't updated when navigating and switching the active pane (currently it's only updated after switching tabs)~~
**Validation**
=> Move StatusBarControl to MainPage

Files.Launcher/NetworkDrivesAPI.cs, Files.Launcher/Program.cs, Files/UserControls/Widgets/DrivesWidget.xaml.cs, Files/ViewModels/ItemViewModel.cs, Files/Views/Pages/PropertiesGeneral.xaml.cs
- Fixes #4912
- Fixes #4911
- Fixes an issue for which files were not renamed from Properties if the user did not click outside the textbox before clicking "OK":
Forces the `ViewModel.ItemName` to update when clicking "OK"
- Fixes an issue for which the Map  Network Drive dialog opened behind Files:
Pass the HWND of Files when creating the dialog
- Fixes an issue for which unlocking a Bitlocker drive did not wait for password input
Note: with this the Files window goes one level back when the dialog is closed, arguably this is still a little better then the current behavior.
**Validation**
=> Fix network drive dialog opening behind Files

Files/ViewModels/ItemViewModel.cs
- Fixes #4629
For mysterious reasons `FindFirstFileExFromApp/FindNextFile` only returns the first file in the Box Drive folder, enumerating using StorageFolder methods instead works ok.
**Validation**
=> Fixes an issue for which only the first file was shown in Box Drive folder

Files/Views/LayoutModes/ColumnViewBase.xaml, Files/Views/LayoutModes/ColumnViewBrowser.xaml, Files/Views/LayoutModes/GenericFileBrowser.xaml, Files/Views/LayoutModes/GenericFileBrowser2.xaml, Files/Views/LayoutModes/GridViewBrowser.xaml
- For #4643
- Fixed too small file icons and overlays (now same size as "old" details view)
- Removed content animation when the list is reset to avoid flickering when loading directories larger than 32 elements
- Left aligned the headers except for the cloud drive status column
**Validation**
=> Fix icon size in new details view

Files/Behaviors/StretchedGridViewItems.cs, Files/Constants.cs, Files/Files.csproj, Files/Views/LayoutModes/GridViewBrowser.xaml, Files/Views/LayoutModes/GridViewBrowser.xaml.cs
- Closes #4940 
- Added and implemented behavior to change item size so that the entire page with is filled
**Validation**
https://user-images.githubusercontent.com/59544401/118571291-93bfcb00-b732-11eb-809d-30464ff418e1.mp4
Note: while resizing, the reordering animation seems to be slowed down. Not sure why.
=> Stretch GridView items to fit page width

Files/Views/LayoutModes/GridViewBrowser.xaml
- Closes #3837
- Hard code width for status glyph and bind visibility to ```InstanceViewModel.IsPageTypeCloudDrive``` so that the space is reserved until it is loaded (if that occurs)
**Validation**
=> Reserve space for status glyph in cloud drive directories

Files/DataModels/SidebarPinnedModel.cs
- Fix issue discussed in Discord server caused by awaiting a null task
- Added a null check for the thumbnail task before awaiting it
**Validation**
=> Fix null exception in AddItemToSidebarAsync when item StorageFolder is null

Files/BaseLayout.cs, Files/Views/LayoutModes/ColumnViewBase.xaml.cs, Files/Views/LayoutModes/ColumnViewBrowser.xaml.cs, Files/Views/LayoutModes/GenericFileBrowser.xaml.cs, Files/Views/LayoutModes/GenericFileBrowser2.xaml.cs, Files/Views/LayoutModes/GridViewBrowser.xaml.cs
N/A
- Fix crash that could occur when ``ItemManipulationModel.RefreshItemsOpacity`` was invoked
- Fix crash that could occur when calling ``GetAllItems`` by updating it to work with grouped collections
- Consolidate some repetitive layout mode code into ``BaseLayout`` (specifically ``GetAllItems`` and the ``RefreshItemsOpacity`` event handler)
**Validation**
=> Fix a few crashes caused by grouping PR

Files.Launcher/Program.cs, Files/Enums/FileSystemStatusCode.cs, Files/Filesystem/FilesystemOperations/FilesystemOperations.cs, Files/Filesystem/StorageFileHelpers/FilesystemResult.cs
- Fixes #2513
- Add support for copy, move, rename file operation as admin
TODO:
**Validation**
=> Add support for copy, move, rename as administrator

Files/UserControls/SidebarControl.xaml.cs
- Fixed a crash when resizing the sidebar too quickly to the left. The crash was caused by passing a negative pixel value to the ``GridLength`` constructor, which in turn would throw an invalid argument exception. 
**Validation**
=> Fix crash when resizing the sidebar too quickly

Files/ViewModels/ItemViewModel.cs
- Fixes #2042
- Adds support for automatically refresh a network folder when a file is created/deleted/renamed..
Done using the "old" method of watching for folder changes (code taken from 0.9.2) only in case of network folders
Note: triggers a full refresh of the folder on any change <- @duke7553 there's no way to get what's changed is there?
- Fixes some issues with recycle bin updating:
- Crash when the recycle bin is open in one tab and multiple files are deleted from another tab
- "Folder empty" text sometimes not appearing/disappearing
- Contents not updated when emptying the recycle bin
**Validation**
=> Auto refresh network folders on change

Files/Dialogs/DynamicDialog.xaml
- Use ``DefaultContentDialogStyle`` for the ``DynamicDialog`` control so that it has WinUI 2.6 styles
**Validation**
After:
Before:
=> Use new ContentDialog style in DynamicDialog

Files.Launcher/Win32API_ContextMenu.cs
- Fixes #4554
Integration to #5009 to fix issue #4554 which was merged with #985 but was slightly different since it was related to windows opened when invoking context menu items and not when double clicking on something.
This should be easier to test since (for me at least) right clicking on zip file and selecting "Extract all.." consistently opens the window behind Files (fixed with this PR).
- Foreground windows opened when invoking context menu items
**Validation**
=> Foreground windows opened when invoking context menu items

Files/Filesystem/CloudDrivesManager.cs, Files/Filesystem/NetworkDrivesManager.cs
- Closes #4247
- Closes #3912
- Auto hide cloud section when no cloud drives are detected
- Show sidebar network item
**Validation**
=> Auto hide cloud section when no cloud drives are detected

Files/Filesystem/Search/FolderSearch.cs, Files/Filesystem/StorageEnumerators/Win32StorageEnumerator.cs, Files/ViewModels/ItemViewModel.cs
- Closes #1245
- Windows explorer does not hide file/folders which are only marked as "system", to be hidden an item must have the "hidden" attribute set. Currently items marked as system but not hidden (e.g Nextcloud folder) are not shown in Files which is not expected.
**Validation**
=> Change "show hidden files" and "hide system files" behavior to match explorer

Files/Dialogs/SettingsDialog.xaml, Files/Dialogs/SettingsDialog.xaml.cs, Files/Views/MainPage.xaml.cs
- Closes #5101
- Added oneway binding from the content dialog's ``RequestedTheme`` property to the window root element ``RequestedTheme`` property
I'm not sure why this content dialog in particular is affected and not other ones, however it may turn up again.
**Validation**
=> Fix issue where requested theme was not respected in settings dialog

Files/UserControls/NavigationToolbar.xaml, Files/UserControls/NavigationToolbar.xaml.cs
- Closes #4879
- Allows to trigger navigation by clicking anywhere on the path components and not just on the text
**Validation**
=> Fix for navigationbar: click anywhere on the path components to navigate

Files/Views/LayoutModes/DetailsLayoutBrowser.xaml
- Fixes invalid cast ``GridLength`` to ``double`` binding error in details layout
- Bind to ``StatusColumn.Length.Value`` instead of ``StatusColumn.Length``
**Validation**
=> Fix binding error in details layout

Files/UserControls/DataGridHeader.xaml
- Closes #5078
- Added missing binding for AutomationProperties.Name property on button inside datagrid header control
**Validation**
=> Add necessary UIA name binding for datagrid header control

Files/ViewModels/SidebarViewModel.cs, Files/Views/MainPage.xaml, Files/Views/MainPage.xaml.cs
- Fix issue where hamburger button would overlay tabs when window was opened with the sidebar in minimal mode
- Check pane display mode when sidebar is loaded and update tab margin accordingly
**Validation**
Before:
After:
=> Fix issue where hamburger button could overlay tabs

Files/MultilingualResources/Files.pt-PT.xlf
Added new translations for pt-PT language.
I add an observation that the word skins in Portuguese is "pele", that is, it is human skin. Therefore, I left the word skin as a foreign word, which makes it easier for end users to understand.
=> Update pt-PT translation

Files/ViewModels/MainPageViewModel.cs, Files/Views/MainPage.xaml
Now you can select previous tab as easy as select next tab.
- Closes #5235
Added the Ctrl + Shift + Tab keybinding to select previous tab, similar to Ctrl + Tab to select next tab.
I copied and adapted the code used to handle new tabs (Ctrl + T and Ctrl + Shift + T).
**Validation**
=> Add Ctrl + Shift + Tab to select previous tab

Files/ViewModels/Widgets/Bundles/BundlesViewModel.cs
- Closes #5258
Fixes NullReferenceException caused by setting `Items = null;` in Dispose() method. After the change tested it multiple times and it never crashed unlike before.
**Validation**
=> Fix null reference exception in Bundles

Files/Strings/en-US/Resources.resw
Continuation of PR #5122
- Removed accidentally kept strings for restoration status messages
*These were added with the previously implemented method, but not removed in the end. Should be removed from all language files ASAP to spare work of translators.*
**Validation**
=> Remove unused strings of library restoration status messages

Files/App.xaml.cs, Files/ViewModels/ItemViewModel.cs, Files/Views/ColumnShellPage.xaml.cs, Files/Views/ModernShellPage.xaml.cs
- Closes #5261
- Closes #2025
- Fixes appcenter [822925445u](https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/822925445u/overview)
- Separated AppserviceConnection used in IShellPage from ItemViewModel's connection
- Refresh connection before enumerating folder
**Validation**
=> Fixes an issue where recyclebin folder appears empty on start or new tab opening

Files/UserControls/Widgets/DrivesWidget.xaml
- Closes #5216
Remove hardcoded row and column size values to properly support text scaling.
**Validation**
At 130% text scaling
=> DrivesWidget: Remove hardcoded row size values

Files/ViewModels/PreviewPaneViewModel.cs
- Changed ``IsItemSelected`` to ``!IsItemSelected`` for no item selected state check
**Validation**
=> Fix issue where the preview pane wouldn't show the proper visual state when no item is selected

Files.Launcher/Program.cs, Files.Launcher/Win32API.cs, Files/DataModels/SidebarPinnedModel.cs, Files/Extensions/ImageSourceExtensions.cs, Files/Filesystem/Drives.cs, Files/Filesystem/Search/FolderSearch.cs, Files/Filesystem/StorageEnumerators/UniversalStorageEnumerator.cs, Files/Helpers/ExternalResourcesHelper.cs, Files/Helpers/FileThumbnailHelper.cs, Files/Helpers/RegistryHelper.cs, Files/UserControls/Widgets/FolderWidget.xaml.cs, Files/UserControls/Widgets/RecentFilesWidget.xaml.cs, Files/ViewModels/ItemViewModel.cs, Files/ViewModels/Previews/BasePreviewModel.cs, Files/ViewModels/Previews/ShortcutPreviewViewModel.cs, Files/ViewModels/Properties/DriveProperties.cs, Files/ViewModels/Widgets/Bundles/BundleItemViewModel.cs
- Always load thumbnails for folders widget except if FullTrustProcess is available
- Use Windows.Storage for thumbnails unless unavailable
- Provide a simplified way to get icon overlays only when needed
**Validation**
=> Always use Windows.Storage to load thumbnails

Files/Converters/DateTimeOffsetToString.cs, Files/Extensions/DateTimeExtensions.cs, Files/ViewModels/Previews/FolderPreviewViewModel.cs
- Closes #5269
- Fixed a bug that caused files or folders without creation or modification date to show "01/01/1601". For this, I added a new if case to check if the year is 1601 return an empty string, as Windows explorer does:
- Now preview files and folder uses getfriendlydate format, to fix that bug and to keep consistency while showing dates also.
- Also files and folders properties and details uses getfriendlydate format.
- Fixed a bug that causes that "1 hour" was showed as "1 hours" and "1 minute" as "1 minutes".
**Validation**
- Before:
- - File properties of #5269 :
- -  Preview pane:
- - - Bug #5269:
- - - Friendly date on …
=> Now preview dates uses getfriendlydate format / Fixed a bug with files and folders without creation or modification date

Files/Views/Pages/Properties.xaml, Files/Views/Pages/Properties.xaml.cs
Now that https://github.com/microsoft/microsoft-ui-xaml/issues/3822 has been resolved, the muxc nav view can now be used again in the properties dialog. This PR switches back to the muxc nav view.
Switching to the muxc navview changes the design, so feedback on that would be appreciated.
**Validation**
=> Switch to muxc navigation view for properties dialog

Files/Helpers/RegistryHelper.cs, Files/UserControls/Selection/ExtendPreviousItemSelectionStrategy.cs, Files/UserControls/Selection/IgnorePreviousItemSelectionStrategy.cs, Files/UserControls/Selection/InvertPreviousItemSelectionStrategy.cs, Files/ViewModels/ItemViewModel.cs
- Fixes #5332
**Changes**
- Fixes an issue introduced in #5242 which affects the "new" menu and folder empty-space menu
- Fixes an issue with the filewatcher for which a crash can occur when temp files are quickly created/deleted
- Fixes an issue with the selection rectangle for which a crash can occur when temp files are quickly created/deleted
**Validation**
=> Fix new context menu

Files/BaseLayout.cs, Files/Filesystem/NetworkDrivesManager.cs, Files/ViewModels/PreviewPaneViewModel.cs, Files/Views/MainPage.xaml.cs
- Added check that the preview pane is loaded before loading the content
**Validation**
=> Fix issue where preview pane content would be loaded even if the preview pane is closed

Files/Filesystem/CloudDrivesManager.cs, Files/Filesystem/Drives.cs, Files/Filesystem/LibraryManager.cs, Files/Filesystem/NetworkDrivesManager.cs, Files/Filesystem/WSLDistroManager.cs
Just cloned the repo for the first time and got the ArgumentOutOfRangeException on startup.
Caused by yesterday's merged PR: https://github.com/files-community/Files/pull/5328
To reproduce just need to enable the "_Show network drives section on the sidebar_" option.
=> Fix crash when the network drives section on the sidebar is shown

Files/Filesystem/StorageEnumerators/UniversalStorageEnumerator.cs, Files/ViewModels/ItemViewModel.cs
Fixed a bug that caused that creation dates were showed on properties as "01/01/0001"
- Closes #5277
- Change the way of getting the creation date on UniversalStorageEnumerator. I don't see any change on creation date of any other files than smb files, which now show their properly date.
**Validation**
Before:
After:
=> Smb files will show their date creation on properties properly

Files/ViewModels/ItemViewModel.cs, Files/Views/ColumnShellPage.xaml.cs, Files/Views/ModernShellPage.xaml.cs
- Closes #3502
- Readme files are now selected when entering a directory. Additionally, replaced `INotifyPropertyChanged` interface in `ItemViewModel` with toolkit's `ObservableObject`
**Validation**
=> Automatically preview readme files when no file is selected

Files/UserControls/DataGridHeader.xaml, Files/ViewModels/ColumnsViewModel.cs, Files/Views/LayoutModes/DetailsLayoutBrowser.xaml, Files/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs
- Related #4643
- Closes #5360 (scrollbar now hidden until hovered over or horizontal scrolling is invoked)
- Fix issue where the header wouldn't always show when scrolling vertically
- Update header buttons to use winui 2.6 styling
- Update column sizes when the view area is resized
**Validation**
=> Fix broken sticky header in details view

Files/App.xaml
App on main currently crashes on startup due to missing resource key.
- Changed `RootBackgroundBrush` from ThemeResource to StaticResource
**Validation**
=> Fix crash due to missing resource key

Files/Views/MainPage.xaml.cs
- Add a null check to ActivePane.TabItemArguments
**Validation**
=> Fix null reference exception crash on startup when the window is small

Files/Extensions/DateTimeExtensions.cs
Now when you check the creation or modification date on preview or on detailed properties, you will see also the time of creation / modification.
I realized the other day that when you want to know the exactly time when you did something it's very difficult right now, so added this little change to make things easier.
- Added creation and modification time on preview and detailed properties, so you can know exactly when you made something.
**Validation**
=> Added time to preview and detailed properties

Files/Models/Settings/BaseJsonSettingsModel.cs, Files/ViewModels/ItemViewModel.cs, Files/Views/ColumnShellPage.xaml.cs, Files/Views/ModernShellPage.xaml.cs
- Closes #5255
- Fixes an issue with recyclebin count mentioned by @BanCrash in #1089
**Validation**
=> Fixes an issue for which changes to Bundles are not saved

Files/Helpers/XamlHelpers/DependencyObjectHelpers.cs, Files/UserControls/Selection/RectangleSelection_ListViewBase.cs, Files/Views/LayoutModes/DetailsLayoutBrowser.xaml
- For #4643
- Fixes #5453
- Add empty space to the right of the last column instead of stretching
- Fix details view not scrolling when using selection rectangle (not perfect but better than nothing)
**Validation**
=> Add empty space to the right of the last column instead of stretching

Files/Helpers/ContextFlyoutItemHelper.cs, Files/Interacts/BaseLayoutCommandImplementationModel.cs, Files/Interacts/BaseLayoutCommandsViewModel.cs, Files/Interacts/IBaseLayoutCommandImplementationModel.cs, Files/Strings/en-US/Resources.resw, Files/UserControls/SidebarControl.xaml, Files/UserControls/SidebarControl.xaml.cs
- Closes #5447 
- Related to #5370
- Renamed unpining strings to keep consistency with 'Pin to Favorites'
- Renamed Pin recycle bin string of sidebar settings to keep consistency with 'Pin to Favorites'
- Renamed methods from Pin/UnpinDirectoryToSidebar to Pin/UnpinDirectoryToFavorites -> Internal minor change using the same base, since you don't pin the folders to sidebar, but to Favorites. I didn't remove the "directory" part just in case in the future Files needs a method like PinFileToFavorites.
**Validation**
Sidebar:
Right click menu:
Settings:
=> Renamed strings and methods related to Pin to favorites to keep consistency

Files/App.xaml, Files/Dialogs/SettingsDialog.xaml, Files/Files.csproj, Files/Helpers/ExternalResourcesHelper.cs, Files/MultilingualResources/Files.pt-PT.xlf, Files/UserControls/Settings/ThemeSampleDisplayControl.xaml, Files/UserControls/Settings/ThemeSampleDisplayControl.xaml.cs, Files/ViewModels/SettingsViewModels/AppearanceViewModel.cs, Files/Views/SettingsPages/Appearance.xaml, Files/Views/SettingsPages/Appearance.xaml.cs, Files/Views/SettingsPages/FilesAndFolders.xaml, Files/Views/SettingsPages/Multitasking.xaml, Files/Views/SettingsPages/Preferences.xaml, Files/Views/SettingsPages/Sidebar.xaml
This PR replaces the existing theme choose UI with a theme sample preview grid:
=> New theme selection UI

Files/Strings/en-US/Resources.resw, Files/UserControls/Widgets/BundlesWidget.xaml, Files/ViewModels/Widgets/Bundles/BundleContainerViewModel.cs, Files/ViewModels/Widgets/Bundles/BundleItemViewModel.cs, Files/ViewModels/Widgets/Bundles/BundlesViewModel.cs
- Closes #5256
This PR adds a context menu option in bundles to directly select and add file/folder to a bundle. This PR also improves performance by utilizing `{x:Bind}` and `x:Load` replacing `{Binding}` and `Visibility`, respectively. Further improvements have been made to code as well, featuring use of `AsyncRelayCommand` and `Task.WaitAll()` for better stability.
**Validation**
=> Added context menu option in Bundles to add items directly to a Bundle

Files/Helpers/XamlHelpers/DependencyObjectHelpers.cs, Files/ViewModels/ColumnsViewModel.cs, Files/Views/LayoutModes/DetailsLayoutBrowser.xaml, Files/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs
- For #4643
- Double clicking the header divider should fit the column to width
@winston-de I was looking into implementing the above change and this is what I came up with.
This seems to work fine when the items are not too many (until list virtualization kicks in). What do you think?
**Validation**
=> Double click gridsplitter to resize columns to fit content

Directory.Build.props, Files.Launcher/Files.Launcher.csproj, Files/Files.csproj
Ever wanted to EASILY clean all binaries? Fear no more as the build output now is not spread in different bin folders but rather in a single location, the `artifacts`
- Removed old build output locations from project files
- Add directory.build.props file to inject new output path into project files
Fun fact, this file also allows to add a reference to packages in every project or add code analyzers for all projects more easily.
**Validation**
=> Update build output paths

Files/UserControls/NavigationToolbar.xaml
- Related #5502 (@winston-de comment)
- Added an access key for accessing settings. I went with "O" since "S" is already used by selection menu. Also, I figured out that it should be an access key that is also used on settings, to avoid a possible exception when you are already on settings and click the access key for opening them again.
I tried to also add a shortcut for entirely closing #5502, but it's throwing an odd exception about the impossibility of opening more than 1 Content Dialog, so until someone implemented it well or I figure out what it's going on at least you will be able to open settings using keyboard via access keys.
**Validation**
Before:
After:
=> Added Access key to open settings

Files/DataModels/SidebarPinnedModel.cs, Files/UserControls/NavigationToolbar.xaml
- Closes #5423
- Added thumbnail fallback for fixing #5423 . Some folders doesn't have an icon on ListView but they have on SingleItem, so with this change more folders will have thumbnail icons when pinned. I added as a fallback because some folders have a bad thumbnail on SingleItem style (they have a black background).
**Validation**
Before:
After:
=> Added thumbnail fallback for obtaining icons for some pinned folders

Files/UserControls/InnerNavigationToolbar.xaml, Files/Views/MainPage.xaml
- set ``ShouldConstrainToRootBounds="False"`` for flyouts so that the full ui can be shown at smaller window sizes, and to prevent overlap with the secondary commands flyout when the command bar is overflowing
**Validation**
=> Use windowed flyouts to improve accessibility at smaller window sizes

Files/Helpers/FilePropertiesHelpers.cs, Files/Views/Pages/Properties.xaml.cs, Files/Views/Pages/PropertiesSecurity.xaml.cs, Files/Views/Pages/PropertiesSecurityAdvanced.xaml.cs
- Closes #2714
- The consolidated lambdas appear to have been causing the exception, removing it fixes it
- also removes the app view consolidated cleanup event handlers because the whole process gets nuked from orbit anyway
**Validation**
For reference, the exception stack trace seemed to lead back to Windows_UI_Xaml!DirectUI::Window::get_SystemBackdrop+0x59
=> Fix crash when closing properties dialog

Files/ViewModels/ItemViewModel.cs
- Fixes an issue causing icons of shortcuts and hidden items appearing blurry after layout change
**Validation**
=> Fix icons of shortcuts appearing blurry after layout change

Files/Converters/MultiBooleanConverter.cs, Files/Dialogs/FilesystemOperationDialog.xaml, Files/UserControls/InnerNavigationToolbar.xaml, Files/UserControls/NavigationToolbar.xaml, Files/UserControls/Widgets/BundlesWidget.xaml
The control VisiblePath and ClickablePath are not visible when SearchBox is focused by CTRL+F.
This should only be done in compact mode, since the search bar is always displayed in normal mode. 
The control VisiblePath and ClickablePath are visible when ShowSearchBox or not IsSearchBoxVisible.
**Validation**
Before/After
=> Fix Path visibility

Files/Views/MainPage.xaml, Files/Views/MainPage.xaml.cs, Files/Views/Pages/Properties.xaml, Files/Views/Pages/Properties.xaml.cs, Files/Views/Pages/PropertiesSecurityAdvanced.xaml, Files/Views/Pages/PropertiesSecurityAdvanced.xaml.cs
- Closes #5518
- This PR fixes an annoying issue with app background appearing solid white / black in light / dark theme on Windows 10.
Could someone test this on Windows 11 and confirm whether it causes issues?
**Validation**
=> Fix background appearing fully white on Windows 10 light theme

Files/BaseLayout.cs
- Closes #5646
- Call SetBitmap() when the dragged file is an image so dropping the file in CorelDraw works.
**Validation**
=> Fix dragdrop image to CorelDraw

Files/DataModels/SidebarPinnedModel.cs, Files/Helpers/ContextFlyoutItemHelper.cs, Files/Strings/en-US/Resources.resw, Files/UserControls/SidebarControl.xaml.cs, Files/ViewModels/SettingsViewModel.cs, Files/ViewModels/SettingsViewModels/SidebarViewModel.cs, Files/Views/SettingsPages/Sidebar.xaml
- Closes #5589
- Related to #5328 , which I used as a base to this PR.
- Added a setting for show or hide Favorites section
- Remove Pin to Favorites option on rightclicking when Favorites section is hidden
- Disabled Pin Recycle bin to Favorites if Favorites section is hidden
**Validation**
No Pin to favorites option when Favorites section is hidden:
Disable Pin Recycle Bin to favorites when Favorites section is hidden:
=> Added a setting to hide or show Favorites sidebar section

Files.Launcher/MessageHandlers/ContextMenuHandler.cs, Files/BaseLayout.cs, Files/Helpers/ContextFlyoutItemHelper.cs, Files/Helpers/ItemModelListToContextFlyoutHelper.cs, Files/Helpers/ShellContextMenuHelper.cs, Files/ViewModels/ContextMenuFlyoutItemViewModel.cs
- After shell items are loaded, the standard open with option is replaced by one with a list of apps that the file can be opened with
**Validation**
=> Add "open with" flyout with app list to context menu

Files/App.xaml, Files/UserControls/FilePreviews/BasicPreview.xaml, Files/ViewModels/ItemViewModel.cs, Files/ViewModels/Previews/BasePreviewModel.cs, Files/ViewModels/Previews/ShortcutPreviewViewModel.cs, Files/Views/LayoutModes/ColumnViewBase.xaml, Files/Views/LayoutModes/ColumnViewBrowser.xaml, Files/Views/LayoutModes/DetailsLayoutBrowser.xaml, Files/Views/LayoutModes/GridViewBrowser.xaml
- Closes #5682
- Closes #5631 
- Switch to single item thumbnail mode and change resize mode
- Round corners for grid view thumbnails
- Show proper file preview images in preview pane and grid view
- Fix issue where file name would sometimes be cut off in tiles view
**Validation**
=> Fix file thumbnail cropping and rounded thumbnail corners

Files/BaseLayout.cs, Files/ViewModels/MainPageViewModel.cs
- Alternative workaround for issue #5555
- Fixes #5720 (4092406467u)
- Current workaround for #5555 is to set the context menu AppBarButtons MinWidth to a large value. This results in a context menu being always large. This solution only sets MinWidth if needed.
**Validation**
=> Workaround for cut context menu

Files/BaseLayout.cs, Files/Helpers/ItemModelListToContextFlyoutHelper.cs, Files/UserControls/SidebarControl.xaml.cs
- Closes #5767
- Closes #5578
- Fix an issue where middle click on sidebar would open two tabs
- Fix a few issues with context menu (workarounds for WinUI issues)
- Fix menu cut off (#5767)
- Fix menu jumping around when loading shell items
- Fix menu remaining open when clicking on subitems (#5578)
- Fix primary items hidden when shown at the bottom of the menu
Let me know if the new menu behavior is acceptable.
**Validation**
=> Fix issues with context menu

Files/Resources/PreviewPanePropertiesInformation.json, Files/Resources/PropertiesInformation.json, Files/Strings/en-US/Resources.resw, Files/UserControls/MultitaskingControl/HorizontalMultitaskingControl.xaml, Files/UserControls/MultitaskingControl/HorizontalMultitaskingControl.xaml.cs, Files/UserControls/PreviewPane.xaml, Files/ViewModels/ItemViewModel.cs, Files/ViewModels/Previews/BasePreviewModel.cs, Files/ViewModels/Previews/FolderPreviewViewModel.cs, Files/Views/LayoutModes/ColumnViewBase.xaml.cs, Files/Views/LayoutModes/ColumnViewBrowser.xaml.cs, Files/Views/LayoutModes/DetailsLayoutBrowser.xaml, Files/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs, Files/Views/LayoutModes/GridViewBrowser.xaml, Files/Views/LayoutModes/GridViewBrowser.xaml.cs
- Closes #5730
- https://github.com/files-community/Files/pull/5717#discussion_r684726948
- Updated font style in details layout, grid view, and preview pane to use caption text style
- added file tag to preview pane
- Fix issue where right clicking text in rename box would commit rename
- add part of set property
- fix issue where tab item would not be selected on load
- fix alignment issue with tags in tiles view
**Validation**
=> Update font style 

Files/Helpers/NavigationHelpers.cs
- Currently when the OpenFoldersNewTab option is enabled, double-clicking a file results in a new tab opening. A new tab should be opened only if the selected item is a folder (or a shortcut to a folder).
- Fixes an issue with the OpenFoldersNewTab setting
- Refactor OpenPath function into more manageable OpenLibrary, OpenDirectory, OpenFile
**Validation**
=> Open only directories in new tab when OpenFoldersNewTab is enabled

Common/Extensions.cs, Files.Launcher/MessageHandlers/FileOperationsHandler.cs, Files.Launcher/MessageHandlers/FileTagsHandler.cs, Files/Filesystem/FilesystemOperations/ShellFilesystemOperations.cs
- Closes #5771 (probably)
- Fixes an issue where, after dropping a file into a folder, renaming that folder will result in a "Folder is in use" error dialog (depends on the moved file type, e.g DOCX files have this issue)
**Validation**
=> Fix "folder is in use" error after moving a file

Files/ViewModels/MainPageViewModel.cs
- Fix home page not loading on app start
I don't know if it's just me but I'm getting this issue where on app startup the homepage doesn't load. This happens if I select "continue where you left off" and I close the app with only the homepage being open.
Added `App.MainViewModel.TabStripSelectedIndex = index;` in `AddNewTabByParam` to match `AddNewTabByPathAsync`.
Since I don't understand why the solution works, can you confirm that it makes sense?
@BanCrash perhaps you've seen this too?
**Validation**
=> Fix home page not loading on app start

Files/ViewModels/ItemViewModel.cs, Files/Views/MainPage.xaml.cs
\-
A readme file will be selected only when preview pane is opened.
**Validation**
=> Focus readme files only when preview pane is open

Files/Files.csproj, Files/Helpers/AppUpdater.cs, Files/Helpers/ContextFlyoutItemHelper.cs, Files/Interacts/BaseLayoutCommandImplementationModel.cs, Files/UserControls/MultitaskingControl/BaseMultitaskingControl.cs, Files/ViewModels/MainPageViewModel.cs, Files/ViewModels/NavToolbarViewModel.cs
this will make it possible to reopen tabs after update, crash, etc, without enabling 
- allow setting groups of previously opened tabs
- remove unneeded references to closed ITabItems and instead store the arguments (since those are whats used anyway)
- add previous session tabs to closed tabs list if not re-opening those tabs
- fix issue where share would be disabled for zip files
**Validation**
=> allow restoring tabs from previous instance using ctrl+shift+t

Files/Filesystem/ListedItem.cs, Files/Helpers/NativeDirectoryChangesHelper.cs, Files/ViewModels/ItemViewModel.cs, Files/Views/LayoutModes/GridViewBrowser.xaml
- Listen to size and date meta changes
**Validation**
=> Listen to size and date meta changes

Files/BaseLayout.cs, Files/Filesystem/FilesystemOperations/Helpers/FilesystemHelpers.cs, Files/Interacts/BaseLayoutCommandImplementationModel.cs, Files/UserControls/SidebarControl.xaml.cs, Files/ViewModels/NavToolbarViewModel.cs, Files/ViewModels/Widgets/Bundles/BundleContainerViewModel.cs
- Related #5980
- Added null check to avoid crash when dragging files from WinRAR
The issue is reproducible only in Azure/Release mode. This PR _only avoids the crash_, dragging Files from WinRAR is currently not working in Release.
**Validation**
=> Avoid crash when dragging files from WinRAR

Files/Files.csproj
- Modify CopyToOutputDirectory property on certain project items to PreserveNewest, preventing unnecessarily-delayed deployment
- Only applies to scenarios when no project item changes were made before running Files from VS
**Validation**
=> Fix an issue where a rebuild would be triggered despite unchanged project items

Files/UserControls/SidebarControl.xaml.cs
- Closes #5856
- Added the option to respect the move overflow items to a submenu on sidebar shell items to keep consistency.
- Added a min width when that option is enabled to avoid possible issues with a small context menu when adding shell items.
**Validation**
Setting enabled, works as does it now:
Setting disabled, works as added on this PR:
=> Respect Move overflow items to a submenu setting on sidebar shell items

Files/UserControls/InnerNavigationToolbar.xaml
Adds a separator in the Sort menu, to isolate the Ascending/Descending radio buttons.
A separator is already used for the same buttons in the context menu.
=> add Separator in menu Sort

Files/DataModels/FilesystemItemsOperationDataModel.cs, Files/Filesystem/FilesystemOperations/Helpers/FilesystemHelpers.cs, Files/Helpers/UIFilesystemHelpers.cs, Files/Interacts/BaseLayoutCommandImplementationModel.cs, Files/UserControls/Widgets/FolderWidget.xaml.cs, Files/ViewModels/Dialogs/FilesystemOperationDialogViewModel.cs, Files/Views/ColumnShellPage.xaml.cs, Files/Views/ModernShellPage.xaml.cs
- Closes #6108
- Fixed an issue preventing copy/paste to work for shortcuts & hidden items
- Avoid blocking UI when loading icons for the conflict dialog (dialog open faster when deleting many items)
**Validation**
=> Fix copy/paste for shortcuts

Files/ViewModels/ItemViewModel.cs, Files/ViewModels/Previews/ImagePreviewViewModel.cs
- An invalid cast to `FileRandomAccessStream` was being made, causing image previews to not be shown. The cast was unnecessary. This pr removes the cast and instead just uses the `IRandomAccessStream` return type, fixing the issue. 
- also removes some old code for svg previews that's no longer being used
- fix issue where header images would show item preview thumbnails instead of type thumbnails in zoomed out view when grouped by type. This issue was due to needing to get the thumbnail via the ftp in order to show just the app thumbnail. 
**Validation**
Add …
=> Fix issue where image previews in preview pane wouldn't work

Files/MultilingualResources/Files.ja-JP.xlf, Files/Strings/ja-JP/Resources.resw
* Added new translation resources that have not been updated (and changed statuses from `new` to `translated`).
* All translation is reviewed. (changed statuses from `needs-review-translation` to `translated`)
**Translation rules**
* `!` to `！`
* `?` to `？`
* Insert a half-width space between katakana words. (For example, `Drives Widget` translated to `ドライブ ウィジェット` )
* Insert a half-width space between English and Japanese ( For example `View Files privacy policy` translated to `Files のプライバシーポリシーを見る`).
**Validation**
**Status:**
Comitted in https://github.com/onein528/Files/commit/b0c74c5a90dbb156e28e930ca19f37fd42c1a452
=> Add and update Japanese translation resources

Files/ViewModels/SettingsViewModels/ExperimentalViewModel.cs, Files/ViewModels/SettingsViewModels/PreferencesViewModel.cs
=> Fix edit tags & edit terminals buttons in settings

Files/Views/ColumnShellPage.xaml, Files/Views/ColumnShellPage.xaml.cs, Files/Views/ModernShellPage.xaml, Files/Views/ModernShellPage.xaml.cs
- Closes #6213
- Ctrl+Shift+C will now copy the path at directory
**Validation**
=> Added Ctrl+Shift+C to copy path

Files/Extensions/DateTimeExtensions.cs
- Related #6116
- Added 9999 year to the not showing list. This fixes a bug that showed negative seconds on the dates. As I stated on #6116 I think we should hide those dates (1601 and 9999 years) since they are unreal and there isn't (or at least I can't imagine one) a scenario where having those dates are useful.
**Validation**
Before:
After:
=> Fixes a bug that showed negative dates when the year was 9999

Common/Extensions.cs, Files/App.xaml.cs, Files/DataModels/NavigationControlItems/LocationItem.cs, Files/Filesystem/Cloud/Providers/MegaCloudProvider.cs, Files/Filesystem/Drives.cs, Files/Views/ColumnShellPage.xaml.cs, Files/Views/ModernShellPage.xaml.cs
- Closes #6190
- Closes #6212
- Closes #6283
- Closes #6272
**Validation**
=> Close some issues

Files.Launcher/Helpers/DisposableDictionary.cs, Files.Launcher/MessageHandlers/FileOperationsHandler.cs, Files.Launcher/Program.cs, Files.Launcher/Win32API.cs, Files/App.xaml.cs, Files/Filesystem/FilesystemOperations/FilesystemOperations.cs, Files/Filesystem/FilesystemOperations/ShellFilesystemOperations.cs, Files/Helpers/AppServiceConnectionHelper.cs, Files/ViewModels/StatusCenterViewModel.cs, Files/Views/ColumnShellPage.xaml.cs, Files/Views/ModernShellPage.xaml.cs
- Closes #6266
- Closes #6171
- Show ongoing progress for file operations on taskbar
- Do not stop filesystem operations when Files window is minimized
- Fixes an issue where the progress ring would show on the toolbar after canceling an operation
- Fixes an issue where a tab would show the loading indicator indefinitely on app start
**Validation**
=> Show file operation progress on Taskbar & continue operations when minimized

Files/Filesystem/Search/FolderSearch.cs, Files/Services/Implementation/FileTagsSettingsService.cs, Files/Views/ModernShellPage.xaml.cs
- Closes #6618
- Closes #6396
- Closes #6487
- Closes #6068
- Enable Ctrl+F / F3 shortcut in home page (#6068)
- Shallow search in non indexed folders (#6487)
- Automatically add wildcard "*" at the end of the search string (#6396) and before the file extension (#6618)
**Validation**
=> Improved reliability of the search experience 

Files/Views/Pages/PropertiesGeneral.xaml
Items resolved/related issues by this PR.
- Closes #1225 Removing redundant information on properties dialogue when multiple items are selected.
- Based on comment https://github.com/files-community/Files/pull/6629#issuecomment-953947125
- Removing redundant information on properties dialogue when multiple items are selected.
**Validation**
**Before**
**After**
=> #1225 Removing redundant information on properties dialogue when multiple items are selected.

Files.Launcher/MessageHandlers/ApplicationLaunchHandler.cs
- Closes #6634
- Refresh env variables when launching a new terminal
**Validation**
=> Refresh env variables when launching terminal

Files.Launcher/Helpers/ShellFolderHelpers.cs, Files/Filesystem/ListedItem.cs, Files/Filesystem/StorageEnumerators/Win32StorageEnumerator.cs, Files/Filesystem/StorageItems/ZipStorageFile.cs, Files/Filesystem/StorageItems/ZipStorageFolder.cs, Files/Helpers/ZipHelpers.cs, Files/Services/Implementation/FileTagsSettingsService.cs
- Closes #6495
- Closes #6491
- Test fix for #6605
- Fixes 1152067677u
- Fixes 2989330824u
- Fixes 2009482836u
- Added try-catch when extracting files
- Compare zip extension ignoring case
- Regenerate file tags json file if invalid
**Validation**
=> Ignore case when checking zip extension

Files/BaseLayout.cs, Files/Filesystem/StorageFileHelpers/StorageFileExtensions.cs
- Closes #6697
- Provide dragged files as StorageFile when possible. Fixes dropping to some UWP apps, e.g Snip and Sketch.
**Validation**
=> Provide dragged files as StorageFile when possible

Files/UserControls/FilePreviews/MediaPreview.xaml, Files/UserControls/FilePreviews/MediaPreview.xaml.cs
- Closes #6287 
- Added a keyboard accelerator in MediaPreview user control that plays media on "ctrl+alt+p " as suggested.
**Validation**
=> Added a hotkey for playing audio and video in the preview pane

Files/Filesystem/FilesystemOperations/Helpers/FilesystemHelpers.cs, Files/Helpers/NavigationHelpers.cs
- Fixed a crash when dropping a shortcut over an executable file
**Validation**
=> Fixed a crash that would occur when dropping a shortcut over an executable file

Files.Launcher/MessageHandlers/Win32MessageHandler.cs
- Helps with #6729
- Fixed an issue where after reinstalling Files it was not possible to turn off the "Set Files As Default" option. The install/uninstall reg files were only copied when enabling the setting.
**Validation**
=> Fixed an issue where the option to reset the default file explorer wouldn't work after reinstalling Files

Files/MultilingualResources/Files.hr-HR.xlf
* Fixed one typo, optimized some expressions, chose "better" plural translation for "items" (there's more than one plural in Croatian for same words) and added translation for missing text
=> Updated Croatian translation

Files/Helpers/NativeFileOperationsHelper.cs
Fixes issues with deserialization where data exceeds buffer length.
This PR fixes native `ReadStringFromFile()` where it could only read a limited number of characters. With this PR 4095 bytes is no longer a limit. fyi @gave92
**Validation**
=> Increased Native Read > 4096 limit

Files/Extensions/DateTimeExtensions.cs
- Closes #6897
- Fixed the number of days comparison.
- If the difference is 7 then it was modified 8 days ago. If the difference is 14 then it was modified 15 days ago.
- Therefore "This week" is difference of 6 days or less and "Last week" is difference of 13 or less (between 7 to 13 inclusive)
**Validation**
=> Fix for #6897 - grouping by date might include files from previous week 

Files.Launcher/DeviceWatcher.cs, Files.Launcher/Helpers/ShellFolderHelpers.cs, Files.Launcher/MessageHandlers/FileOperationsHandler.cs, Files.Launcher/Program.cs
- Closes #6709
- File extensions would not show in recycle bin even when the option is turned on in Files. Disabling Show file extensions in File Explorer causes this issue, this PR fixes it. 
**Validation**
=> Fixed an issue where restoring items from recycle bin would remove the file extension

Files.Package/Package.appxmanifest, Files/Files.csproj
The WinUI 2.8 preview doesn't currently work in the store with apps that support ARM64 so this is a temporary workaround.
=> Rolled back to WinUI 2.7

Files/MultilingualResources/Files.de-DE.xlf, Files/MultilingualResources/Files.hu-HU.xlf, Files/MultilingualResources/Files.nl-NL.xlf
- Closes Appcenter: [3064744457u](https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/3064744457u)
- Fix string for de, hu, nl causing crash when opening conflicts dialog
**Validation**
=> Fix string for de, hu, nl causing crash when opening conflicts dialog

Files/Controllers/TerminalController.cs, Files/DataModels/TerminalFileModel.cs, Files/Helpers/NavigationHelpers.cs, Files/Models/JsonSettings/Implementation/DefaultJsonSettingsDatabase.cs, Files/Properties/Default.rd.xml, Files/Services/Implementation/FileTagsSettingsService.cs
- Closes #6605
- Closes (maybe) [1528823123u](https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/1528823123u/overview), [813232478u](https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/813232478u/overview), [4277801717u](https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/4277801717u/overview)
- Closes (maybe) [2261357081u](https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/2261357081u/overview)
- Added FileTag class to rd.xml. Without it file tags do not get serialized correctly in Release mode
- Fixed an issue where going to Preferences before sidebar is loaded crashed the app
**Validation**
=> Fixes an issue causing file tags list to be serialized wrong

Files/BaseLayout.cs, Files/Filesystem/ListedItem.cs, Files/Filesystem/Search/FolderSearch.cs, Files/Filesystem/StorageEnumerators/UniversalStorageEnumerator.cs, Files/Filesystem/StorageEnumerators/Win32StorageEnumerator.cs, Files/Filesystem/StorageItems/FtpStorageFile.cs, Files/Filesystem/StorageItems/FtpStorageFolder.cs, Files/Helpers/UIFilesystemHelpers.cs, Files/Interacts/BaseLayoutCommandImplementationModel.cs, Files/ViewModels/ItemViewModel.cs, Files/ViewModels/NavToolbarViewModel.cs, Files/ViewModels/Properties/SecurityProperties.cs, Files/Views/ColumnShellPage.xaml.cs, Files/Views/LayoutModes/ColumnViewBase.xaml.cs, Files/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs, Files/Views/LayoutModes/GridViewBrowser.xaml.cs, Files/Views/MainPage.xaml.cs, Files/Views/ModernShellPage.xaml.cs, Files/Views/Pages/PropertiesGeneral.xaml.cs
- Closes #7012
- May fix #5823
- Fixes an issue where file extension is lost when renaming a shortcut to a folder
- Adds an ItemNameRaw property to ListedItem, moves the logic to get the "Display" name from the raw name into ListedItem and subclasses.
- Fixes an issue where file extensions where shown in Search result page regardless of the "show file extensions" setting
- Fixes an issue where search results were loaded twice when submitting search
- Fixes an issue where a file with a random name shows when search yields no results
**Validation**
=> Fix file extension being lost when renaming, fixes for search

Files/ViewModels/Properties/FileProperties.cs
Performance improvements as `OrderBy` will operate on a smaller collection.
=> Move OrderBy after Where

Files.Launcher/Helpers/CloudDrivesDetector.cs
Using an array reduce allocations. Also, `Task.WhenAll` use a faster path when the argument is an array.
=> Use an array instead of a list

Files.Launcher/Helpers/CloudDrivesDetector.cs, Files/Filesystem/StorageItems/BaseStorageItem.cs, Files/Views/Pages/PropertiesCustomization.xaml.cs
Using `async` keyword generate a state machine which has perf impact. I removed it from methods where it's trivial to remove them and doesn't impact the readability of the code
=> Remove async when not needed

Common/Logger.cs
You should release the semaphore only if you have acquired it first. In case an exception occurs when acquiring it, the previous code was releasing it anyway.
=> Do not release the Semaphore if it was not acquired first

Files.Launcher/Win32API.cs
Comparing a struct with null is always false as a struct cannot be null.
=> Remove always true condition

Files/Extensions/ImageSourceExtensions.cs
`ReadAsync` doesn't guarantee to read the _requested_ bytes. The contract is to read at least 1 byte. So, you need to iterate until the stream is fully read.
=> Fix ToByteArrayAsync to read the result of ReadAsync

Files/UserControls/NavigationToolbar.xaml
Since #5969, the search is available in the homepage. However, in a small window, the search bar is replaced by a button to make it appear. This button is not active on the homepage. It is not possible to search all the drives in a small window.
The SearchButton, to display the search bar, is always active.
before/after
=> Fixed search button on home page

Files/Extensions/EnumerableExtensions.cs
`new List<T>` with a single item allocates an array of 4 items in addition to the `List<T>`. Using an array with a single item reduces allocation and is faster to create and iterate.
=> Reduce allocations in CreateEnumerable

Files/UserControls/InnerNavigationToolbar.xaml
Before, on startup, the icons are actives in the inner toolbar and the EmptyRecycleBin button is visible.
They are disabled when the viewmodel is loaded. It is not beautiful and it will become even less so when we add buttons only visible on certain pages. 
Add Fallback in the bindings.
**Validation**
=> Fix inner toolbar state on startup

Files/Extensions/EnumerableExtensions.cs, Files/Extensions/LinqExtensions.cs
EnumerableExtensions.AddIfNotPresent returns a Boolean. This result is never used.
This makes sense, because the purpose of this function is to avoid testing.
This pr change the return type by the input (list or dictionary).
This will allow this function to be placed in a modification chain, like LINQ
**Validation**
=> Change return type of AddIfNotPresent

Files.Launcher/Program.cs
- Simplify the code by using `ReadAsync`
- Fix a logic issue: Using `UTF8.GetString` on an incomplete buffer may generate invalid strings ([example](https://www.meziantou.net/how-not-to-read-a-string-from-an-utf-8-stream.htm)). The new code is using a `MemoryStream` to get the message content until the message is complete.
=> Use async/await to read from the named pipe

Files/Helpers/ItemListDisplayHelpers/BulkConcurrentObservableCollection.cs
Similar to the [ObservableCollection](https://source.dot.net/#System.ObjectModel/System/Collections/ObjectModel/ObservableCollection.cs,f63ea2601f5edbbb,references)
=> Cache event args to avoid allocations

Common/ShellLinkItem.cs, Files.Launcher/Helpers/ShellFolderHelpers.cs, Files.Launcher/MessageHandlers/FileOperationsHandler.cs, Files.Launcher/MessageHandlers/NetworkDrivesHandler.cs, Files/App.xaml.cs, Files/Filesystem/NetworkDrivesManager.cs, Files/Filesystem/StorageEnumerators/Win32StorageEnumerator.cs, Files/Helpers/NavigationHelpers.cs, Files/ViewModels/Properties/DriveProperties.cs
- Closes #7183
It's possible to manually add shortcuts (.lnk) to the `%AppData%\Roaming\Microsoft\Windows\Network Shortcuts` folder. These are shown in explorer under This PC > Network Locations. This PR adds support for showing these in the sidebar network section.
- Show network shortcuts on the sidebar
- Show icon for shortcut items
**Validation**
=> Show network shortcuts on the sidebar

Files/Helpers/ItemListDisplayHelpers/BulkConcurrentObservableCollection.cs, Files/ViewModels/ItemViewModel.cs
- Closes #7170
- Always specify starting index in CollectionChanged for Add operation
- Fixes an issue where items are not sorted if collection is grouped and an item DisplayName != Name
**Validation**
=> Always specify starting index in CollectionChanged

Files/ISearchBox.cs, Files/UserControls/SearchBox.xaml, Files/UserControls/SearchBox.xaml.cs, Files/ViewModels/NavToolbarViewModel.cs, Files/ViewModels/SearchBoxViewModel.cs, Files/Views/ColumnShellPage.xaml.cs, Files/Views/ModernShellPage.xaml.cs
The selection in search suggestions has a problem. The file is opened by selecting the item. If there are several suggestions and you want to open the second, moving with the keyboard will open the first by passing over it, and you cannot open the second.
The event SuggestionChosen is removed. The event QuerySubmitted opens the file when he receives a suggestion.
**Validation**
before/after for select the second item on the keyboard.
https://user-images.githubusercontent.com/46631671/144091046-0cac7c4f-97a6-401d-a758-d0de99f4bad1.mp4
https://user-images.githubusercontent.com/46631671/144091114-1535b239-fd5b-4c3d-bd19-8656671f2e9b.mp4
=> Fix select search suggestion

Files.Launcher/MessageHandlers/FileOperationsHandler.cs, Files/ViewModels/Properties/FileProperties.cs, Files/ViewModels/Properties/FolderProperties.cs, Files/ViewModels/SelectedItemsPropertiesViewModel.cs, Files/Views/Pages/PropertiesCompatibility.xaml, Files/Views/Pages/PropertiesShortcut.xaml, Files/Views/Pages/PropertiesShortcut.xaml.cs
- Follow up of #7006
- Closes #7209
- Set symlink target path in Properties as readonly and hide arguments, working directory
- Fixes an issue where Properties window does not close if Shortcut section is expanded
- Fixes #3524514594u (crash if fulltrust process fails to fetch Compatibility properties)
**Validation**
=> Fix properties window not closing on OK

Files.Launcher/Win32API.cs, Files/UserControls/NavigationToolbar.xaml.cs, Files/UserControls/PathBreadcrumb.xaml, Files/UserControls/PathBreadcrumb.xaml.cs, Files/ViewModels/NavToolbarViewModel.cs
- Closes #3667
- Added method to capture mouse clicks. Middle clicks are filtered and a new tab opened.
**Validation**
- [X ] Built and ran the app
- [X ] Tested the changes for accessibility
=> Mousewheel click opens new tab at selected path

Files/MultilingualResources/Files.de-DE.xlf
German: Fixed wrong labels for "Open files/folders with one click" and several other small corrections
Fixed mixed up labels:
Open files with one click > Dateien mit einem Klick öffnen
Open folders with one click > Ordner mit einem Klick öffnen
Plus several small language-corrections (grammar, punctuation etc.)
- Added...
- Fixed...
**Validation**
=> German: Fixed wrong labels and other corrections

Files/BaseLayout.cs
The statusbar always displays the cumulative size counting 0 for files whose size is not known. This impacts zip folders.
The cumulative size is no longer displayed if one of the elements does not have a known size.
**Validation**
=> Fix size column for archive files

Files/Helpers/AppUpdater.cs, Files/ViewModels/ItemViewModel.cs, Files/Views/SettingsPages/Preferences.xaml
Closes [#7227](https://github.com/files-community/Files/issues/7227)
Raise the position of the date format parameter below that of the language 
Removal of two unused variables which creates alerts during compilation 
**Validation**
=> Changing the position of the date parameter and removing two compilation warnings

Files/Helpers/NavigationHelpers.cs, Files/ViewModels/PreviewPaneViewModel.cs, Files/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs, Files/Views/LayoutModes/GridViewBrowser.xaml.cs
- Closes #7196
- Only show the basic preview for recycle bin items
- allow opening folders with double click when multiselect is enabled
**Validation**
I can't test that the previews work properly in the recycle bin because the full trust process is still broken, so if someone could test that it would be appreciated.
=> Show basic preview for recycle bin items

src/Files/UserControls/Selection/RectangleSelection_ListViewBase.cs
- Closes #7300 
Analyze the ListView viewport for item rectangles a single time, upfront, rather than every time the pointer is moved. Further, do this rather intensive work on selection rectangle y-axis dilation only when the scrolling gesture becomes determinate for 1 second. 
**English**: Drag-to-select will no longer lag in very large folders (e.g. System32), and similar safeguards are put in place when attempting to select more items outside the bottom (or top) of the ListView.
**Validation**
N/A
=> fix: Prevent repetitive viewport analysis in PointerMoved

src/Files/Views/PaneHolderPage.xaml, src/Files/Views/PaneHolderPage.xaml.cs
- Fixes an issue for which the secondary pane always gets loaded (even if it's closed)
- Fixes an issue where cycling elements with Tab key selects some invisible elements
- x:Load does not work on Page / UserControl elements, so add a Border around it and apply x:Load to that
**Validation**
=> Fix right pane being always loaded

src/Files.Launcher/MessageHandlers/ContextMenuHandler.cs
- Closes #7093
- Given that "Install" and "Install for all users" don't correctly install fonts, "manually" install fonts through powershell instead
**Validation**
=> Install fonts through powershell

src/Files/UserControls/Selection/RectangleSelection_ListViewBase.cs, src/Files/Views/LayoutModes/ColumnViewBase.xaml.cs, src/Files/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs, src/Files/Views/LayoutModes/GridViewBrowser.xaml.cs
- Closes #7449
- Do not focus filelist on pointer up when renaming
**Validation**
=> Fix text selection when renaming

src/Files/DataModels/NavigationControlItems/DriveItem.cs
- Closes #7453
- No need to await properties loading when creating DriveItem
**Validation**
=> Do not block while loading drive properties

src/Files/Views/Pages/PropertiesSecurity.xaml.cs
Opening advanced security properties a second time results in the advanced properties content to appear in the current properties window instead of opening a new window.
- Re-add some code removed in #5538. _Not_ adding back the call to "Window.Current.Close()" which was causing #2714
**Validation**
=> Fix advanced properties opening in the wrong window

src/Files/BaseLayout.cs, src/Files/Behaviors/StickyHeaderBehavior.cs, src/Files/Views/ColumnShellPage.xaml.cs, src/Files/Views/ModernShellPage.xaml.cs
- Fixes an issue causing focus in column view to move around on it's own when toggling some settings (e.g "show file extensions")
- Fixes an issue causing a crash when refreshing a folder after changing from column view to another layout
- Fixes an issue where the file list is invisible or cut after navigating while the list is scrolled
**Validation**
=> Fix focus cycle in column view when some settings change

src/Common/ShellOperationResult.cs, src/Files.Launcher/Helpers/FileUtils.cs, src/Files.Launcher/Helpers/ShellFolderHelpers.cs, src/Files.Launcher/MessageHandlers/FileOperationsHandler.cs, src/Files/Filesystem/FilesystemOperations/Helpers/FilesystemHelpers.cs, src/Files/Filesystem/FilesystemOperations/ShellFilesystemOperations.cs, src/Files/Helpers/RecycleBinHelpers.cs, src/Files/ViewModels/StatusCenterViewModel.cs
- Closes #7028
- Closes #7492
- Closes #7334
- Closes #6849
- Added a method to check whether deleting a file would move it to the recycle bin or not, the method e.g returns false in removable drives, network drives and if the recycle bin is disabled for a drive
- If recycle bin is not enabled, automatically check the "permanent delete" dialog option
- Call "UpdateBanner" when a banner is posted to fix #7028
Note: code in "FileUtils.cs" is currently not used and can be ignored, it's ground work to implement #1681.
**Validation**
=> Properly toggle "permanent delete" check in confirmation dialog

.github/CONTRIBUTING.md
Old URL referred to the old Files website. This PR is for fixing the link to the code style in Files docs.
=> fix link to Files docs in CONTRIBUTING.md

src/Files/ViewModels/Properties/FolderProperties.cs
- Closes #7525 (in the properties the size text doesn't show for hidden folders)
Class StorageFolder is not available for hidden items.
The GetFolderSize function has StorageFolder as a parameter, but only uses the path.
This pr modifies GetFolderSize to use the path and work with hidden folders. 
**Validation**
=> Fixed folder size visibility in properties for hidden folders

src/Files/Filesystem/FileTagsHelper.cs
- Closes #7534
- Folders with a custom icon are set as "read-only". To save the tag remove the RO attribute, write the tag and restore the attribute.
=> Ability to set tags on read-only folders

README.md
Discovered when trying to setup the project. No related issue defined.
Building according to the current prerequisites in the README on a fresh install of VS 2022 fails due to some missing prerequisites.
I added the required prerequisites to the list of prerequisites in the readme. These are the C++ UWP build tools as an option in the mentioned UWP kit (not checked by default) and the C++ ATL for build tools in "Individual components".
The required packages are seen here:
=> update README Prerequisites with required dependencies

src/Files/Helpers/NavigationHelpers.cs, src/Files/Helpers/Win32Helpers.cs
- Closes #7530
- If multiple files are selected, use FTP to open them together so e.g all selected music files will play in the default app.
=> When multiple files are selected, open them together

src/Files/ViewModels/ItemViewModel.cs, src/Files/Views/ColumnShellPage.xaml.cs, src/Files/Views/ModernShellPage.xaml.cs
- Resolves #7310 
- Recent file/folder creations are captured before batched to be handled in bulk
1. Capture the last item processed by the queue 
2. When the bulk operation ends, inform the UI thread with the latest item added
- Performant since the UI is only informed on new single file additions (not edits, replacements, etc.)
- Changes applied to both the modern and column-view; uncertain if columns needs this behavior though
**Validation**
=> Select newly created files or folders

src/Files/MultilingualResources/Files.zh-Hant.xlf
- None (Sorry I know that it's written in Contributing guidelines; however, translations seem not really required that?)
- Un-translated "Bundles" widget in order to differentiate from "favorites".
- Assumed the "Empty Recycle Bin" of No. 835 meant to empty it rather than meant it's an empty one.
- Fixed some mistakes.
- Made some of them more readable.
**Validation**
(None)
=> Improve zh-Hant translation

src/Files/Strings/en-US/Resources.resw, src/Files/Views/SettingsPages/Experimental.xaml
=> Added info bar to clarify the risks for the option to set Files as the default file manager

src/Files/MultilingualResources/Files.zh-Hans.xlf
- Closes #7765 
- Fixed translation.
Before: "列出和排序文件旁的目录";
After: "文件夹与文件一同分类排序";
**Validation**
=> Translation zh-Hans Updated

src/Files/Helpers/FileThumbnailHelper.cs, src/Files/ViewModels/ItemViewModel.cs, src/Files/ViewModels/Previews/BasePreviewModel.cs, src/Files/ViewModels/Previews/FolderPreviewViewModel.cs, src/Files/ViewModels/Properties/FileProperties.cs
- Closes #6512
- Closes #7770
- Closes #6130
- Closes #6966
Using "ThumbnailMode.DocumentsView" instead of "ThumbnailMode.SingleItem" appears to fix the missing thumbnails issue. Even #6512 (preview for .psd files) looks fixed. Could someone double-check?
**Validation**
=> Fixed image thumbnails not appearing

src/Files/Views/ColumnShellPage.xaml, src/Files/Views/ColumnShellPage.xaml.cs, src/Files/Views/MainPage.xaml, src/Files/Views/ModernShellPage.xaml, src/Files/Views/ModernShellPage.xaml.cs
- Closes https://github.com/files-community/Files/issues/6579
- Related PR to update files.community website documentation with this shortcut: https://github.com/files-community/Website/pull/119
- Added a keyboard shortcut (Ctrl + k) to duplicate tabs with current path
- If in "Home" it creates a new home tab, otherwise it takes the current path
**Validation**
=> add keybaord shortcut to duplicate tab

src/Files/UserControls/Widgets/DrivesWidget.xaml, src/Files/UserControls/Widgets/FolderWidget.xaml, src/Files/UserControls/Widgets/RecentFilesWidget.xaml, src/Files/Views/LayoutModes/DetailsLayoutBrowser.xaml, src/Files/Views/LayoutModes/GridViewBrowser.xaml, src/Files/Views/ModernShellPage.xaml, src/Files/Views/PaneHolderPage.xaml
- Closes #7820
- Added...
- Fixed...
**Validation**
=> Removed extra controls from the Visual Tree

src/Files/ViewModels/ItemViewModel.cs
- Fixes (maybe) #7897
- Fixed an issue for which renaming an item in a library would sometimes result in the new item appearing multiple times (or in a crash).
Problem was that in a library WatchForDirectoryChanges is called multiple times (one for every folder the library is pointing to) and each time the `aWatcherAction` variable used to cancel the watcher gets overwritten, so only one of the watcher threads can be canceled.
Now use CancellationToken.Register() method so that each watcher instance can register it's own cleanup.
**Validation**
=> Correctly cancel all directory watchers

src/Files.Launcher/MessageHandlers/InstallOperationsHandler.cs, src/Files.Launcher/Program.cs, src/Files/Helpers/FileExtensionHelpers.cs, src/Files/Interacts/BaseLayoutCommandImplementationModel.cs, src/Files/Interacts/BaseLayoutCommandsViewModel.cs, src/Files/Interacts/IBaseLayoutCommandImplementationModel.cs, src/Files/Strings/en-US/Resources.resw, src/Files/UserControls/InnerNavigationToolbar.xaml, src/Files/ViewModels/NavToolbarViewModel.cs, src/Files/Views/ColumnShellPage.xaml.cs, src/Files/Views/ModernShellPage.xaml.cs
- Related #7800
- Added IsFontFile extension helper.
- Added resource string (Install).
- Corrected spelling of HasAdditionalActions. 
- Added messager handler to install font (could be used for installing infs at a later stage)
**Validation**
**Comments**
Toolbar text might be better as Install font. I just went with what Windows had originally in the context menu.
=> Added Install Font button when selecting a font file

src/Files.Launcher/Helpers/ShellFolderHelpers.cs
- Closes #7627
- Closes #7826
- Adds a null check that fixes the "network" sidebar folder being always empty
**Validation**
=> Fixed loading of items under network

src/Files/Views/CustomFolderIcons.xaml.cs
- Closes #6737
- Disables the button with a short delay before re-enabling.
**Validation**
**Comment**
I was thinking maybe we could use events (as opposed to the delay) to restore the button once the RefreshItems() method had completed. But as it is running on a different thread I don't believe that is possible?
=> Fixed repeatedly clicking Restore Default button causing crash

src/Files/BaseLayout.cs, src/Files/ViewModels/ItemViewModel.cs
- Closes #5121
- Changed the `UpdateEmptyTextType()` method to public to allow being called from BaseLayout.cs `BaseFolderSettings_LayoutModeChangeRequested()`
**Validation**
=> Switching layouts in an empty folder correctly shows empty folder text.

src/Files/Dialogs/FilesystemOperationDialog.xaml, src/Files/Dialogs/FilesystemOperationDialog.xaml.cs
- Closes #5788
- Related #5584
- Fixed default focus of Primary button in ContentDialog by moving x:Bind tags to the dialog loaded event. 
- Deleting a file in the recycle bin and pressing enter now confirms the deletion.
**Validation**
=> Fixed delete dialog primary button focus issue

src/Files/Views/SettingsPages/Experimental.xaml
The text SettingsSetAsDefaultFileManagerDescription is localized but not used.
This pr uses the text SettingsSetAsDefaultFileManagerDescription in experimental settings.
**Validation**
=> Fixed missing description in experimental settings page

src/Files/Helpers/MultitaskingTabsHelpers.cs, src/Files/MultilingualResources/Files.it-IT.xlf, src/Files/Strings/en-US/Resources.resw, src/Files/Strings/it-IT/Resources.resw, src/Files/UserControls/MultitaskingControl/BaseMultitaskingControl.cs, src/Files/UserControls/MultitaskingControl/HorizontalMultitaskingControl.xaml, src/Files/UserControls/MultitaskingControl/HorizontalMultitaskingControl.xaml.cs
Closes #7714 .
- Added "Close tabs to the left" item, which is disabled when the selected tab is the first tab
- Added "Close others" item, which is disabled when there is only one tab open
- Added English and Italian localizations for the new voices.
**Validation**
=> Add "Close tabs to the left" and "Close others" to tab context menu

src/Files.Launcher/MessageHandlers/FileOperationsHandler.cs
- Fixes an issue for which deleting a single folder takes a long time to show the confirmation dialog
- When deleting a folder, only test the first file inside the folder to check if files can be sent to the recycle bin
- Small refactor of "Clipboard" FTP method
To test: try request deletion of the "Program Files" folder. Confirmation dialog should appear much quicker.
**Validation**
=> Improved performance of the delete confirmation dialog

src/Files/Strings/en-US/Resources.resw, src/Files/UserControls/Widgets/FolderWidget.xaml.cs, src/Files/ViewModels/MainPageViewModel.cs, src/Files/ViewModels/SettingsViewModels/PreferencesViewModel.cs
- Closes #8091
- Added missing resource string for 'SidebarDocuments'
**Validation**
=> Fixed an issue wher the tab title was missing in the documents library

src/Files/Filesystem/Search/FolderSearch.cs, src/Files/Filesystem/StorageEnumerators/Win32StorageEnumerator.cs, src/Files/Helpers/RegistryToJsonSettingsMerger.cs, src/Files/MultilingualResources/Files.es-ES.xlf, src/Files/MultilingualResources/Files.it-IT.xlf, src/Files/Services/IPreferencesSettingsService.cs, src/Files/Services/Implementation/PreferencesSettingsService.cs, src/Files/Strings/en-US/Resources.resw, src/Files/ViewModels/ItemViewModel.cs, src/Files/ViewModels/SettingsViewModels/PreferencesViewModel.cs, src/Files/Views/SettingsPages/Preferences.xaml
Closes #2587.
This is a simple implementation. It doesn't include advanced options, if anyone wants to implement them I am open to suggestions, or we can always open another PR in the future after having defined details better.
- Added an option to hide files and folders starting with a dot (off by default) in Settings>Preferences>Files and folders
- Changed some functions so that .*** files are hidden (even from search) when the new setting is enabled
**Validation**
=> Added an option to hide files starting with '.'

src/Files/MultilingualResources/Files.ja-JP.xlf
Long time no see!
- Fix weird translations
- Update translations
- Fix weird translations (ex. "抽出" was used as translations of "extract" though MS don't use this word as this mean.)
**Validation**
**Comments**
Sorry for suddenly PR. I found some weird translations on this app, so I'd like to fix.
For other translators and maintainers, if you don't like this edit, please ignore.
=> Update Japasese translations & Fix weird translations

src/Files/BaseLayout.cs
- Closes #8285
- Choose next item to be selected based on its position in the file list, not its lexicographical order (which causes some items to be skipped)
- Start looking for matching items after currently selected item
**Validation**
=> Improve JumpString behavior

src/Files/UserControls/MultitaskingControl/HorizontalMultitaskingControl.xaml.cs
- Closes #7246
- Probably related #7222
Currently, when there are 2 tabs open and one of them is torn off, the first window is closed because CloseTab() is called after the tab has already been removed and it finds only one remaining tab.
This PR fixes the problem.
**Validation**
=> Fixed issue that causes a window to close when a tab is torn off

src/Files/UserControls/NavigationToolbar.xaml
Adjust the SearchBox height. #8427
Modifiy the searchbox height (34 instead of 33) to match the address bar.
**Validation**
=> Fix SearchBox height

src/Files/Views/LayoutModes/ColumnViewBase.xaml, src/Files/Views/LayoutModes/DetailsLayoutBrowser.xaml, src/Files/Views/LayoutModes/GridViewBrowser.xaml
- Fixed an issue where  switching theme would make the group headers unreadable until app restart
**Validation**
=> Fix wrong foreground text color in zoomed-out Group headers

src/Files.Uwp/ViewModels/ItemViewModel.cs, src/Files.Uwp/Views/ColumnShellPage.xaml.cs, src/Files.Uwp/Views/ModernShellPage.xaml.cs
- Closes #8418 
- Select the item following the matched item to be deleted 
- If the item was the last item, choose the item right before it
- Reduce code complexity with selecting newly created items by reusing `OnSelectionRequestedEvent` 
- (I did this PR awhile back)
**Validation**
=> Select next item after deletion and reduce code complexity

src/Files.Uwp/Filesystem/StorageFileHelpers/FilesystemResult.cs
This pr fixes a small bug in the FilesystemTasks class. The NameTooLong error code is never returned because PathTooLongException is a subclass of IOException. The NameTooLong code is however tested by the caller. The order of the tests has been modified to manage the most specific in priority.
This function can still be improved: Unnecessary tests of FileLoadException and Generic, multiple casting of the same value, replacement by a switch expression, …. This pr only fixes the bug.
**Validation**
=> Fix FilesystemTasks error code

src/Files.Uwp/Helpers/BitmapHelper.cs, src/Files.Uwp/Views/ColumnShellPage.xaml.cs, src/Files.Uwp/Views/ModernShellPage.xaml.cs
- Closes #8658
- Related #8658
- Fixed a crash when user doubleclicks the "rotate image" button.
**Validation**
Multiple clicks on both "rotate left" and "rotate right" dont crash the app.
Side effect: spamming a billion clicks will produce unpredictable rotation of images. 
Seems I did not disable the buttons properly, but the debounce on CanExecute still works.
I had a lot of ideas TBH, but found that all of them are way beyond the current PR.
=> Added a debounce for image rotation command.

src/Files.Launcher/Helpers/ShellNewMenuHelper.cs
- Partially solves #8244 
This PR removes a check that prevented some files like .accdb (Microsoft Access) that have a template with a different extension from appearing in the "New" menu. The final file is still created with the correct extension.
I wasn't able to fix .txt and .bmp entries in Windows 11 because they don't have a ShellNew entry (this is somewhat related to the new Notepad and Paint apps).
**Validation**
=> Show more file types in "New" context menu

src/Files.Uwp/Controllers/SidebarPinnedController.cs, src/Files.Uwp/DataModels/NavigationControlItems/LocationItem.cs, src/Files.Uwp/DataModels/SidebarPinnedModel.cs, src/Files.Uwp/Filesystem/CloudDrivesManager.cs, src/Files.Uwp/Filesystem/Drives.cs, src/Files.Uwp/Filesystem/FileTagsManager.cs, src/Files.Uwp/Filesystem/LibraryManager.cs, src/Files.Uwp/Filesystem/NetworkDrivesManager.cs, src/Files.Uwp/Filesystem/WSLDistroManager.cs
- Resolves #8556
- Added watcher to pinned items config
- Fixed bug with items staying pinned when multiple items unpinned at once
- Caused by incorrect iteration order when mutating list while enumerating
- Fixed bug with incorrect pin order when favoriting multiple items
- Synchronize updates to `ChildItems` by using `BulkConcurrentObservableCollection`
- Watcher callback needs to marshal `RefreshAsync()` to UI thread which 
implies that modification to `ChildItems` now needs to be thread-safe
**Validation**
=> Notify when pinned items config changes

src/Files.OpenDialog/FilesLauncher/FilesLauncher.cpp, src/Files.Uwp/BaseLayout.cs, src/Files.Uwp/Dialogs/PropertiesDialog.xaml.cs, src/Files.Uwp/Dialogs/SettingsDialog.xaml.cs, src/Files.Uwp/UserControls/SidebarControl.xaml.cs, src/Files.Uwp/UserControls/StatusBarControl.xaml.cs, src/Files.Uwp/UserControls/Widgets/DrivesWidget.xaml.cs, src/Files.Uwp/UserControls/Widgets/RecentFilesWidget.xaml.cs, src/Files.Uwp/ViewModels/MainViewModel.cs, src/Files.Uwp/ViewModels/SettingsViewModel.cs, src/Files.Uwp/Views/MainPage.xaml
- Since #7939 adaptive triggers on MainPage do not work anymore (SearchBox does not collapse and Sidebar does not switch to minimal state).
- Adaptive triggers won't work if put on Page. Added back surrounding Border control.
- Fixed tabs  being drawn over Sidebar toggle button when in minimized state.
- Removed AppSettings where not referenced.
**Validation**
=> Fix MainPage adaptive triggers

src/Files.Uwp/Helpers/DynamicDialogFactory.cs
- Closes #8765 
- Regression from #8204
- Using `BeforeTextChanging` means that the textbox text is stale, `args.NewText` must be used instead
**Validation**
=> Fix new/rename dialog processing stale text

src/Files.Uwp/Views/Pages/PropertiesSecurity.xaml, src/Files.Uwp/Views/Pages/PropertiesSecurityAdvanced.xaml
=> Auto select first item in user list for permissions

src/Files.Uwp/Dialogs/FilesystemOperationDialog.xaml, src/Files.Uwp/Dialogs/FilesystemOperationDialog.xaml.cs
- Fix crash when using "apply to all" menu item in conflicts dialog
- Closes #8834
- "Apply to all" menu item Tag was incorrect (after #8792)
- Enable dialog primary button before the dialog is loaded (when the ViewModel is set)
**Validation**
=> Fix crash when using "apply to all" menu item in conflicts dialog

src/Files.Uwp/Controllers/SidebarPinnedController.cs, src/Files.Uwp/DataModels/SidebarPinnedModel.cs
- Fixed AppCenter [1010488437u](https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/1010488437u/overview)
- `favoritesSection` will be null if the favorites section is hidden. Added null check.
**Validation**
=> Fix crash when favorites section is hidden

src/Files.OpenDialog/FilesLauncher/FilesLauncher.vcxproj
- Closes #8771
- Statically link VC runtime so launcher works even if VD runtime is not installed on user PC
**Validation**
=> Statically link VC runtime

src/Files.Uwp/Filesystem/Drives.cs, src/Files.Uwp/Filesystem/FolderSizeProvider.cs
- Fixes an issue where the app occasionally hangs on start like:
Debugger is showing the app hung on this line L37 in FolderSizeProvider.cs => `private readonly CoreDispatcher dispatcher = CoreApplication.MainView.CoreWindow.Dispatcher;`.
Hunch is that the line is called too early on app startup, being invoked as a consequence of a static initializer in Drives.cs => `private static readonly IFolderSizeProvider folderSizeProvider = Ioc.Default.GetService<IFolderSizeProvider>();`).
I'm not certain this PR fixes the issue as the bug is hard to reproduce, but at worst it won't change anything.
**Validation**
=> Possibly fix app hung on start

src/Files.Uwp/UserControls/NavigationToolbar.xaml, src/Files.Uwp/UserControls/NavigationToolbar.xaml.cs, src/Files.Uwp/ViewModels/NavToolbarViewModel.cs, src/Files.Uwp/Views/ColumnShellPage.xaml.cs, src/Files.Uwp/Views/ModernShellPage.xaml.cs
- Closes #8800
- When the search textbox is active, a flag is set disabling the pasting command (in the shellpage). Textbox pasting still works.
- Corrected spelling of a method in the NavToolBarViewModel
**Validation**
=> Fix for pasting in search box

src/Files.Uwp/Filesystem/StorageFileHelpers/IStorageItemWithPath.cs, src/Files.Uwp/Filesystem/StorageFileHelpers/StorageFileExtensions.cs, src/Files.Uwp/Filesystem/StorageFileHelpers/StorageFileWithPath.cs, src/Files.Uwp/Filesystem/StorageFileHelpers/StorageFolderWithPath.cs, src/Files.Uwp/Helpers/NavigationHelpers.cs, src/Files.Uwp/ViewModels/ItemViewModel.cs, src/Files.Uwp/ViewModels/NavToolbarViewModel.cs
Tiny pr to clean up IStorageItemWithPath and its 2 implementations. Refactoring only.
- Deletes unused sets.
- Use 1 property instead of 2 which returns the same instance.
- More readable code.
**Validation**
=> Clean IStorageItemWithPath

src/Files.Uwp/UserControls/FilePreviews/MediaPreview.xaml, src/Files.Uwp/UserControls/FilePreviews/MediaPreview.xaml.cs, src/Files.Uwp/ViewModels/Previews/MediaPreviewViewModel.cs, src/Files.Uwp/Views/ColumnShellPage.xaml, src/Files.Uwp/Views/ColumnShellPage.xaml.cs, src/Files.Uwp/Views/ModernShellPage.xaml, src/Files.Uwp/Views/ModernShellPage.xaml.cs
- Resolves #7705
- Resolves #8108
- Shortcut to toggle playback (`TogglePlaybackAccelerator`) is now `ctrl + space`
- Add code-behind to allow toggle in details/column layout
- `Space` was being suppressed and not propagated in `KeyboardAccelerator`, now handled in `PreviewKeyDown`
- Refactor `PreviewKeyDown` to be similar in structure with `KeyboardAccelerator_Invoked`
**Validation**
- `` ctrl + ` `` still works as expected (open terminal with correct path) after refactor
- `ctrl + space` works as expected (item selected, preview pane shown)
- `space` key works when renaming and isn't disabled
- **QuickLook** works as expected with `space` and as well as all the same interactions listed above
=> Change preview pane play media toggle to 'ctrl + space'

src/Files.Uwp/Views/Pages/PropertiesDetails.xaml
- bind button content to the string resource
**Validation**
Before:
After:
Side note, really like this new string resource system.
=> Fix issue where clear all properties button wouldn't show any text

src/Files.Uwp/UserControls/MultitaskingControl/HorizontalMultitaskingControl.xaml
A recent WinUI update added a second layer of mica to the tab control causing it to have the wrong transparncy in Files. I worked around this by removing one of the visual states from the default template.
**Validation**
=> Fixed an issue where the tab control had the wrong color

src/Files.Uwp/BaseLayout.cs, src/Files.Uwp/Helpers/ContextFlyoutItemHelper.cs, src/Files.Uwp/ViewModels/CurrentInstanceViewModel.cs
- Closes #8986
- Show file tags menu in search page
- Fix overflow items not shown in search page
Currently right clicking on an item in search page shown a context menu where the last item is a separator, which is weird. Issue is that the "Overflow" menu item is hidden in search.
**Validation**
=> Fixes for item context menu in search page

src/Files.Uwp/UserControls/StatusBarControl.xaml
This fixes a small issue where in the Status bar when no items are selected and folder size is enabled there's a 24px space (instead of 12px) between element count and size.
- Put margin on each column content instead of using ColumnSpacing property
**Validation**
=> Fix spacing in status bar

src/Files.Uwp/BaseLayout.cs, src/Files.Uwp/DataModels/SidebarPinnedModel.cs, src/Files.Uwp/Filesystem/CloudDrivesManager.cs, src/Files.Uwp/Filesystem/Drives.cs, src/Files.Uwp/Filesystem/FileTagsManager.cs, src/Files.Uwp/Filesystem/LibraryManager.cs, src/Files.Uwp/Filesystem/NetworkDrivesManager.cs, src/Files.Uwp/Filesystem/WSLDistroManager.cs, src/Files.Uwp/UserControls/Widgets/DrivesWidget.xaml.cs
PR #8952 introduced a bug for which sometimes the app crashes on start due to the favorites list being concurrently modified.
- Add proper lock() statements when modifying favorites and other sidebar sections related lists (like was already the case with Drives)
- Remove a couple of extra "ToList()" calls when safe to do so.
**Validation**
=> Fix crash due to concurrent edits of sidebar lists

src/Files.OpenDialog/FilesLauncher/FilesLauncher.cpp, src/Files.Uwp/App.xaml.cs, src/Files.Uwp/Program.cs
- Closes #8951 (again)
This PR should fix the error that some users are reporting when setting Files as default. It does it by invoking Files by protocol ("files-uwp:") instead of command line ("files.exe") which appears to fix the issue.
It would be great if a couple of people could test this.
**Validation**
=> Execute Files by protocol in launcher

src/Files.Uwp/BaseLayout.cs, src/Files.Uwp/Filesystem/StorageItems/VirtualStorageItem.cs
N/A
Expands the capability of our new VirtualStorageItem impl to support instantiation solely from a filesystem path. For this feature, we leverage the fast FindFirstFileExFromApp() method to get enough item properties to construct the backing ListedItem which is used to set the properties on the IStorageItem contract. 
Additionally, a static data field for BasicProperties is created on the VirtualStorageItem class and is set, only initially, from a simple streamed storage file. This makes the present use of VirtualStorageFile (in BaseLayout for drag and drop) more concise. 
Lastly, path instantiation will allow us to leverage VirtualStorageItem for all filesystem operations, instead of having to create a StorageFile/Folder n number of …
=> feat(VirtualStorageItem): instantiation from filesystem path

src/Files.Uwp/BaseLayout.cs
- Fixes an issue preventing to drag&drop from 7zip/WinRar/etc to a folder in Files (dropping to the empty space already works, but not dropping into a folder)
- Match DragOver() if-checks to Item_DragOver(). The `handledByFtp` condition must be checked before `draggedItems.Any()`.
**Validation**
=> Fix dropping from 7zip to folder

src/Files.Uwp/BaseLayout.cs, src/Files.Uwp/Filesystem/FilesystemOperations/ShellFilesystemOperations.cs, src/Files.Uwp/Filesystem/StorageItems/ZipStorageFolder.cs
- Fixes an issue for which file operations involving zip files do not use ShellFileOperations. This is because IsZipPath() returns true also for the zip file itself, not only for items inside.
- Add a `includeRoot` parameter IsZipPath() to exclude the zip file itself from the check
**Validation**
=> Fix copying a zip file not using Shell file operations

src/Files.Uwp/Controllers/SidebarPinnedController.cs, src/Files.Uwp/Controllers/TerminalController.cs
- Closes #9022
- Avoid reloading favorites sidebar items if the config file contents have not changed
- Code taken from TerminalController.cs
**Validation**
=> Avoid favorite sidebar constant reloading

src/Files.Uwp/Dialogs/FilesystemOperationDialog.xaml, src/Files.Uwp/Dialogs/FilesystemOperationDialog.xaml.cs
- Closes #9059 
- Manually renaming items in conflicts dialog will remove any invalid file name characters. This PR also fixes the issue where aggregate conflict resolve option was visible in file in use dialog
**Validation**
=> Remove invalid characters in conflicts dialog

src/Files.Backend/Files.Backend.csproj, src/Files.Backend/Models/ByteSize.cs
New class ByteSize in Backend.Models.
This class encapsulates the ByteSize class from the external library to provide a structure more suited to our new backend: native localization, no negative values, possibility of later additions.
**Validation**
=> ByteSize class

src/Files.Uwp/Extensions/DateTimeExtensions.cs
The Application date format groups dates by periods (Today, This week, ...). The other formats use the same grouping but with a single date label (4/24/2022 for Last week). These labels misrepresent the content of the group.
This pr uses the same label as Application to group the other date formats. This does not change anything for the individual display of a file or folder.
**Validation**
Before/After (System date format). 75 items have a date between 4/24/2022 and 4/30/2022.
=> Fix the label of groupings by date

src/Files.Uwp/App.xaml.cs, src/Files.Uwp/Filesystem/CloudDrivesManager.cs, src/Files.Uwp/Filesystem/Drives.cs, src/Files.Uwp/Filesystem/FileTagsHelper.cs, src/Files.Uwp/Filesystem/FileTagsManager.cs, src/Files.Uwp/Filesystem/FtpManager.cs, src/Files.Uwp/Filesystem/LibraryLocationItem.cs, src/Files.Uwp/Filesystem/LibraryManager.cs, src/Files.Uwp/Filesystem/NetworkDrivesManager.cs, src/Files.Uwp/Filesystem/WSLDistroManager.cs
Here is a new batch of refactoring. I added ILogger as a service to eliminate dependency to App.
**Validation**
=> Refactor FileSystem

src/Files.Uwp/ViewModels/ToolbarViewModel.cs
When the RecycleBin is empty and appears at startup, the EmptyRecycleBin button can be active. This pr fixes this bug. This is visible with the "Continue where you left off" option when exiting Files on the RecycleBin tab.
Changes the initial value of HasItem to False. This value is not modified when there is no element, this is the reason for the bug.
**Validation**
Before/After
=> Fix EmptyRecycleBinButton state

src/Files.Uwp/Controllers/SidebarPinnedController.cs, src/Files.Uwp/Controllers/TerminalController.cs, src/Files.Uwp/DataModels/SidebarPinnedModel.cs
- Should resolve #8941
- Make adds to `SidebarItems` (model) and `sidebarList` (UI list) atomic (otherwise model and UI desync)
- Eliminate unnecessary refreshes by serializing model to `configContent` after every save
- `suppressChangeEvent` wasn't a good solution; `Query_ContentChanged` could be handled very late after many saves
- Refactor `AddItemToSidebarAsync`  to reuse existing methods
**Validation**
_(notice how add order is consistent instead of random)_
=> fix(sidebar): add items to favorites in a consistent order

src/Files.Uwp/BaseLayout.cs, src/Files.Uwp/Filesystem/FolderSizeProvider.cs, src/Files.Uwp/Filesystem/StorageEnumerators/Win32StorageEnumerator.cs, src/Files.Uwp/ViewModels/ItemViewModel.cs, src/Files.Uwp/Views/ColumnShellPage.xaml.cs, src/Files.Uwp/Views/ModernShellPage.xaml.cs
- Fixes an issue for which folder sizes are randomly not shown on some items
- Reduces occurrences of Appcenter [#97216821u](https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/97216821u/overview)
- Process folder size changed events after enumeration is complete to make sure the items has been added to the filesAndFolders collection
**Validation**
=> Fix folder size not shown for some items

src/Files.Uwp/Filesystem/FilesystemOperations/Helpers/FilesystemHelpers.cs
- Closes Appcenter [2806362965u](https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/2806362965u/overview), [2832023223u](https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/2806362965u/overview)
- Returned History can be null if the copy/move operations has failed -> added null check.
**Validation**
=> Fix crash when copy/move operation fails

src/Files.Uwp/Helpers/ContextFlyoutItemHelper.cs
Add missing primary icons in the context menu of current folder.
The added icons are Paste and Properties. #9088
**Validation**
Before/After
=> Add missing quick access

src/Files.Uwp/App.xaml.cs, src/Files.Uwp/Filesystem/CloudDrivesManager.cs, src/Files.Uwp/Filesystem/Drives.cs, src/Files.Uwp/Filesystem/FileTagsManager.cs, src/Files.Uwp/Filesystem/LibraryManager.cs, src/Files.Uwp/Filesystem/NetworkDrivesManager.cs, src/Files.Uwp/Filesystem/WSLDistroManager.cs, src/Files.Uwp/Helpers/LibraryHelper.cs, src/Files.Uwp/ViewModels/SidebarViewModel.cs
Storage class EnumerateThingAsync methods have 2 issues fixed here.
1) The name assumes it returns an enumerable, but it returns nothing. It updates a property. I renamed it UpdateThingAsync for clarity.
2) The method reads the parameters to run or not according to user preferences. It is not the role of storage to handle this, but the role of the front. I moved this role to the caller which removes the dependency on UserSettingsService.
This is to move Storage to Backend, which should not depend on settings.
**Validation**
=> Refactor EnumerateDrives

src/Files.Uwp/Views/MainPage.xaml.cs
The PreviewPane splitter sometimes shows the wrong cursor after changing direction (horizontal/vertical).
Change the cursor when the splitter changes of direction.
The property CursorBehavior="ChangeOnSplitterHover" of GridSplitter is not used because it does not work.
**Validation**
The bug.
=> Fixed an issue where the preview pane grid splitter sometimes used the wrong cursor 

src/Files.Uwp/Strings/en-US/Resources.resw, src/Files.Uwp/Views/LayoutModes/DetailsLayoutBrowser.xaml, src/Files.Uwp/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs
- Closes #8384
- Fix regression of #5506
- Add `Size All Columns to Fit` to details menu flyout in detail view header
- Make `ResizeColumnToFit` safe to call programmatically, previously only safe to call when user clicks on visible column
- Improve heuristic to calculate appropriate width since measuring `TextBlock` is expensive
- Measure longest text _first_ because we can expect that the width should be long enough for shorter texts 
regardless if they have wider letters or not
- This also allows the width to not overshoot, imagine if the first files were wide letters: 
**(e.g. AAA, BBB, DDD)** --> this would skew the average letter width
- Measure `TextBlock` using sample instance to avoid `Arrange` or other metadata to pollute & …
=> feat(details-view): add option to size all columns to fit

src/Files.Uwp/ViewModels/ItemViewModel.cs
- Closes #8159
File list randomly scrolls to top on renaming and deleting* (_especially_ if no confirmation dialog when deleting is on)
\* _deleting was fixed with (#8503), so couldn't reproduce on `main`_
- Select renamed files/folders (reuse code from selecting newly created items)
- Deduplicate code for handling changes `(anyEdits)` in operation queue
- Improve performance of finding selection item by only enumerating once
**Validation**
=> fix: file list randomly scrolling to top

src/Files.Uwp/UserControls/MultitaskingControl/HorizontalMultitaskingControl.xaml
- Closes #8504
Fixed an issue preventing users from dragging the app window from the empty space on top of the tab view
**Validation**
=> Fix: Fixed title bar drag area

src/Files.Uwp/Filesystem/LibraryManager.cs
- Closes Appcenter [2408931032u](https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/2408931032u/overview)
- Sidebar update event was being passed the wrong type of item
**Validation**
=> Avoid crash when creating a library

src/Files.Shared/Enums/FileOperationType.cs, src/Files.Shared/Enums/ReturnResult.cs, src/Files.Uwp/Filesystem/FilesystemOperations/Helpers/FilesystemHelpers.cs, src/Files.Uwp/Helpers/Convert/ErrorCodeConverter.cs
- Related #9159
- When using StorageAPI in file operations involving multiple items the last copy result overwrites the status shown in the banner. So if 29/30 operations fail but the 30th succeeds we show the "Success!" green banner, which is wrong.
- Changed callback function to only update the status if nothing has failed so far. 
- Remove the [Flags] attribute from enum whose values are not powers of 2 as required
**Validation**
=> Show failed banner if any items failed in a file operation

src/Files.Uwp/BaseLayout.cs
- Hide triple-dot button from empty space context menu to match items context menu
- Set AlwaysExpanded to true for BaseContextMenuFlyout
**Validation**
=> Hide triple-dot button from empty space context menu

src/Files.Uwp/ServicesImplementation/DialogService.cs
- Closes Appcenter [371833548u](https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/371833548u/overview)
- Add try-catch around dialog ShowAsync in DialogService to match DialogDisplayHelper. Return "DialogResult.None" if a dialog is already open.
**Validation**
=> Fix crash due to multiple dialogs opening

src/Files.Backend/Services/Settings/IPreferencesSettingsService.cs, src/Files.Uwp/ServicesImplementation/Settings/LayoutSettingsService.cs, src/Files.Uwp/ServicesImplementation/Settings/PreferencesSettingsService.cs, src/Files.Uwp/UserControls/InnerNavigationToolbar.xaml, src/Files.Uwp/ViewModels/FolderSettingsViewModel.cs, src/Files.Uwp/ViewModels/ItemViewModel.cs, src/Files.Uwp/ViewModels/SettingsViewModels/PreferencesViewModel.cs
- Small improvement over #9098
- Move default SortDirectoriesAlongsideFiles from PreferencesSettingsService to LayoutSettingsService so we don't have a duplicate setting
- Refresh sort order in current folder when the global setting changes
**Validation**
=> Move default SortDirectoriesAlongsideFiles to LayoutSettingsService

src/Files.Uwp/DataModels/SidebarPinnedModel.cs, src/Files.Uwp/UserControls/SidebarControl.xaml.cs, src/Files.Uwp/ViewModels/SidebarViewModel.cs
Move the Home item outside the favorites section.
Had to fix the commands to move Favorites, as it assumed the first item was Home.
**Validation**
=> Move the Home item outside the favorites section

src/Files.Uwp/Helpers/AsyncManualResetEvent.cs
To avoid unnecessary allocations.
=> Hoist TaskCompletionSource outside the loop

src/Files.Uwp/Views/ModernShellPage.xaml.cs
Drive roots use a path such as "C:\\". This is the path that is used when opening a drive from the sidebar or other. But when the Up button needs to return to C:\\, it actually calls C:, it's that path in the address bar.
This leads to not finding the drive, for example when we want to display the properties of the disk.
Closes #9227
This pr modifies the Up_Click method to add the trailing "\\" when the path ends with ":". This character is forbidden in paths, except to indicate the drive.
**Validation**
=> Fix up button

builds/azure-pipelines-release.yml, src/Files.Uwp/App.xaml.cs, src/Files.Uwp/Files.Uwp.csproj, src/Files.Uwp/ServicesImplementation/SideloadUpdateService.cs
- Added sideload update service.
**Validation**
=> Sideload update service

src/Files.Uwp/UserControls/Widgets/DrivesWidget.xaml.cs
- Closes #9218
- Use DriveItem icon data if could not load thumbnail
**Validation**
=> Fixes an issue preventing icon for MTP device from appearing on Drives Widget

src/Files.Uwp/ViewModels/FolderSettingsViewModel.cs, src/Files.Uwp/ViewModels/ItemViewModel.cs
- Closes #6586 
- With this code, the Downloads folder will be grouped by date modified on the first start.
**Validation**
=> Set downloads folder to group by date

src/Files.Uwp/Helpers/UIHelpers.cs
- Not a bug fix, just a small optimization
- Since we now use a custom icon for the favorites section, there's no need to load the quick access icon from shell32 dll on start.
**Validation**
=> Do not load quick access icon

src/Files.Uwp/Helpers/NativeFileOperationsHelper.cs
- Closes #9271
- Replace open_always with open_existing when opening a file for read so it does not create a file when the files does not exist.
**Validation**
=> Use OPEN_EXISTING when opening a file for read

src/Files.Uwp/ViewModels/ItemViewModel.cs
Fixes #8333 
**Validation**
Before:
https://user-images.githubusercontent.com/25117425/171063890-7f921d9c-7468-466e-80b1-3b69584bf49e.mp4
After:
https://user-images.githubusercontent.com/25117425/171063899-223eb360-da14-43b5-9dd4-38164e631681.mp4
=> After pasting, focus all pasted files/folders instead of just one

src/Files.Uwp/ViewModels/ItemViewModel.cs
Reverts files-community/Files#9299
=> Revert "After pasting, focus all pasted files/folders instead of just one"

src/Files.Uwp/Helpers/ItemListDisplayHelpers/BulkConcurrentObservableCollection.cs
- N/A
- `BulkConcurrentObservableCollection::Remove` should return `false` if the item was not found
- We currently have zero usages of `Remove`'s return value in the codebase, so this is to avoid bugs from arising in the future
**Validation**
=> fix: BulkConcurrentObservableCollection::Remove returns false if item not found

src/Files.FullTrust/Helpers/ShellFolderHelpers.cs
- Closes #9294
- Catch exception if ShellItem has no property store
**Validation**
=> Fix refresh not working when doing some files operations in network drives

src/Files.Uwp/BaseLayout.cs
Fixes #7640
Dragging items in the recycle bin is now disabled.
**Validation**
=> Disabled dragging in recycle bin

src/Files.FullTrust/Helpers/ShellFolderHelpers.cs, src/Files.Uwp/DataModels/NavigationControlItems/INavigationControlItem.cs, src/Files.Uwp/DataModels/SidebarPinnedModel.cs, src/Files.Uwp/Helpers/ContextFlyoutItemHelper.cs, src/Files.Uwp/UserControls/SidebarControl.xaml.cs, src/Files.Uwp/ViewModels/SettingsViewModels/AppearanceViewModel.cs
The favorite RecycleBin is particular. We can't move it. In the code, it is handled separately.
The context menu of the RecycleBin page does not offer an entry for Pin/Unpin.
- Closes #9191
- Closes #8227
- Related #9192
The RecycleBin favorite becomes a favorite like any other, stored like any other. It can be moved and retains its specific menu entries.
The setting to display it is retained. He has priority at the start of the session to add/remove the favorite if necessary. This makes it possible not to break the user's current preferences.
The context menu of the RecycleBin page offers an entry for Pin/Unpin.
**Validation**
=> [Post v2.3] Improves pinned RecycleBin

src/Files.Uwp/Helpers/FilePropertiesHelpers.cs
=> Properties window is now shown near mouse cursor position

src/Files.Backend/Services/Settings/IFileTagsSettingsService.cs, src/Files.Uwp/App.xaml.cs, src/Files.Uwp/CommandLine/CommandLineParser.cs, src/Files.Uwp/CommandLine/ParsedCommand.cs, src/Files.Uwp/CommandLine/ParsedCommandType.cs, src/Files.Uwp/Filesystem/Drives.cs, src/Files.Uwp/Filesystem/Search/FolderSearch.cs, src/Files.Uwp/Program.cs, src/Files.Uwp/ServicesImplementation/Settings/FileTagsSettingsService.cs
- Closes #9033
- Added "-tag" command line argument to allow setting/removing file tags from the command line
E.g `files /tag:blue "file1" "file2" "file3"` or `files -tag "orange" "file1" "file2"`
- Fixed an issue preventing command line args written as "/command" instead of "-command" from working
- Fixed an issue preventing shell folders from opening in explorer when "AlwaysOpenANewInstance=true"
**Notes**
Issuing the "-tag" command results in a Files window opening (and staying open). Given that there's no way to prevent the splash screen from appearing when invoking Files from the command line, I think it's better to leave the window open instead of causing it …
=> Allow to set file tags from command line

src/Files.Uwp/Files.Uwp.csproj, src/Files.Uwp/Filesystem/StorageItems/NativeStorageFile.cs, src/Files.Uwp/Filesystem/StorageItems/SystemStorageFile.cs
- Closes #9385
- Workaround for UnauthorizedAccessException when dealing with url and lnk
- NativeStorageFile class comes from PR #9234
**Validation**
=> Fixed an issue preventing to drag&drop a link from a browser addressbar to Files

src/Files.Uwp/DataModels/NavigationControlItems/DriveItem.cs, src/Files.Uwp/UserControls/SidebarControl.xaml.cs, src/Files.Uwp/UserControls/Widgets/DrivesWidget.xaml, src/Files.Uwp/UserControls/Widgets/DrivesWidget.xaml.cs
- Related #7321
Drives can now be pinned/unpinned to/from favorites either through sidebar or home page.
I used already existing localized texts, so should I add new ones where needed or leave it as it is?
**Validation**
=> Allow to pin drives to favorites

src/Files.Uwp/Filesystem/FilesystemOperations/FilesystemOperations.cs
- Closes #9277
- Removed code that doesn't seem necessary anymore as dragging from zip respects the GenerateUniqueName enum. This also fixes the issue with dragging from a browser.
**Validation**
=> Removed code to handle GenerateUniqueName bug

src/Files.FullTrust/Win32API.cs, src/Files.Shared/ShellOperationResult.cs, src/Files.Uwp/Filesystem/FilesystemOperations/FilesystemOperations.cs, src/Files.Uwp/Filesystem/FilesystemOperations/ShellFilesystemOperations.cs, src/Files.Uwp/Helpers/StorageHelpers.cs, src/Files.Uwp/Helpers/WallpaperHelpers.cs, src/Files.Uwp/Interacts/BaseLayoutCommandImplementationModel.cs, src/Files.Uwp/ViewModels/Properties/FileProperties.cs
- Fixes an issue preventing drag & drop from phone storage
- Fixes an issue causing a crash when dropping a file from a zip archive opened in Files and the destination already exists
- Fixes wrong filename when copy-pasting from a zip file opened in explorer and the destination already exists
- Fixed the GenerateUniquePath function so that a file named "test.txt" becomes "test (1).txt" instead of just "(1).txt" when copy-pasting from a zip file opened in explorer and the destination already exists.
- Take the most recent result for each source file at the end of a file operation. Fixes a crash due to duplicate key when calling "ToDictionary()" on file operation …
=> Fix issues with drag&drop from special locations

src/Files.Shared/Extensions/StringExtensions.cs, src/Files.Uwp/Extensions/StringExtensions.cs, src/Files.Uwp/Helpers/AdaptiveLayoutHelpers.cs, src/Files.Uwp/ViewModels/ItemViewModel.cs, src/Files.Uwp/ViewModels/PreviewPaneViewModel.cs, src/Files.Uwp/ViewModels/Previews/ArchivePreviewViewModel.cs, src/Files.Uwp/ViewModels/Previews/BasePreviewModel.cs, src/Files.Uwp/ViewModels/Previews/BasicPreviewViewModel.cs, src/Files.Uwp/ViewModels/Previews/CodePreviewViewModel.cs, src/Files.Uwp/ViewModels/Previews/FolderPreviewViewModel.cs, src/Files.Uwp/ViewModels/Previews/HtmlPreviewViewModel.cs, src/Files.Uwp/ViewModels/Previews/ImagePreviewViewModel.cs, src/Files.Uwp/ViewModels/Previews/MarkdownPreviewViewModel.cs, src/Files.Uwp/ViewModels/Previews/MediaPreviewViewModel.cs, src/Files.Uwp/ViewModels/Previews/PDFPreviewViewModel.cs, src/Files.Uwp/ViewModels/Previews/RichTextPreviewViewModel.cs, src/Files.Uwp/ViewModels/Previews/ShortcutPreviewViewModel.cs, src/Files.Uwp/ViewModels/Previews/TextPreviewViewModel.cs
Refactor preview view model
- More readable code that uses new syntaxes
- Avoids constantly re-instantiating the same objects.
- Improves visibility (private/protected/public)
- Remove unused code.
Also, I added new xml extensions (xsl, xslt, xlf, xsd)
**Validation**
=> Refactor PreviewViewModel

src/Files.Uwp/ViewModels/FolderSettingsViewModel.cs
- Closes Appcenter [3657153677u](https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/3657153677u/overview?q=ioexception&searchType=unhandlederror)
- Enable shared connection for layout prefs DB
Should fix the "System.IO.IOException: The process cannot access the file user_settings.db because it is being used by another process" error.
**Validation**
=> Enable shared connection for layout prefs DB

src/Files.Uwp/Views/CustomFolderIcons.xaml
Fixed an issue where text wouldn't wrap in some languages.
**Validation**
=> Fix: Added text wrapping to custom icon page

src/Files.Uwp/Helpers/LayoutPreferences/LayoutPreferences.cs
- Fixes an issue sometimes causing folders to use the wrong grouping option
- Added missing group option check to Equals method
**Validation**
=> Fix folders sometimes using wrong grouping option

src/Files.Shared/Extensions/LinqExtensions.cs, src/Files.Uwp/Filesystem/StorageItems/ZipStorageFile.cs, src/Files.Uwp/Filesystem/StorageItems/ZipStorageFolder.cs, src/Files.Uwp/UserControls/Menus/FileTagsContextMenu.xaml.cs
- Fixes [1163518263u](https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/1163518263u/overview) & friends
- Fixes [595421595u](https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/595421595u/overview)
- Fixes [2122662730u](https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/2122662730u/overview)
- 1163518263u -> crash when enumerating folder containing multiple zip files
- 595421595u -> crash when loading an archive and file could not be opened
- 2122662730u -> crash when removing last tag on a file
**Validation**
=> Appcenter fixes for 2.3.5

src/Files.Uwp/Views/Pages/Properties.xaml
This was discussed in the Files discord and there wasn't any issue related to this as far as I know, but I was told I can open it anyway.
- Tweaked the spacing between the indicator and the tabs
- Made security icon not always use MDL2 Assets (for consistency in 11)
**Validation**
Will add soon. I don't have access to my PC at the time this PR was created.
=> Add indicator spacing in properties page & make security icon use up to date font

src/Files.Uwp/App.xaml.cs, src/Files.Uwp/Filesystem/StorageHistory/Helpers/StorageHistoryHelpers.cs, src/Files.Uwp/Serialization/Implementation/CachingJsonSettingsDatabase.cs
- Fixed an issue causing settings to be repeatedly read from file in some cases
- Moved public SemaphoreSlim from App.cs to StorageHistoryHelpers (only place it's used)
**Validation**
=> Fix issue causing user settings to be repeatedly reloaded from file in some cases

src/Files.Uwp/DataModels/NavigationControlItems/DriveItem.cs, src/Files.Uwp/Filesystem/NetworkDrivesManager.cs
- Closes #9715 
- When adding a network drive item to drives section, so far we didn't attach an icon for it. 
- Fixed by adding an icon for the network folder
**Validation**
Before: 
After:
=> Fixed missing icon for network folder

builds/azure-pipelines-release.yml
Removed the x86 build from the pipeline, we should still support x86 but we no longer release x86 builds for users.
**Validation**
- No testing required 
=> Removed x86 build from pipeline

src/Files.Uwp/Views/MainPage.xaml.cs, src/Files.Uwp/Views/ModernShellPage.xaml.cs
- Closes #9760 
- Added an 'if' that checks if the selected item is a FileTagItem and if true sets it as the path to highlight
**Validation**
- Built and ran the app
=> Fix - Selecting a tag on the sidebar doesn't highlight it

src/Files.Uwp/UserControls/Selection/RectangleSelection_ListViewBase.cs
Closes #9075 
When selecting items by dragging the mouse, the selected items size details are now shown.
**Validation**
https://user-images.githubusercontent.com/25117425/171218690-a250daa4-0cda-43a4-b100-888ab0ccfa08.mp4
=> Show selected items size details when selecting by dragging the mouse

src/Files.Backend/Services/Settings/IPreferencesSettingsService.cs, src/Files.Uwp/Helpers/AdaptiveLayoutHelpers.cs, src/Files.Uwp/ServicesImplementation/Settings/PreferencesSettingsService.cs, src/Files.Uwp/Strings/en-US/Resources.resw, src/Files.Uwp/ViewModels/FolderSettingsViewModel.cs, src/Files.Uwp/ViewModels/ItemViewModel.cs, src/Files.Uwp/ViewModels/SettingsViewModels/PreferencesViewModel.cs, src/Files.Uwp/ViewModels/ToolbarViewModel.cs, src/Files.Uwp/Views/SettingsPages/Preferences.xaml
- Added support for setting which columns are shown by default
- Removed the option to use individual preferences and replaced it with an easier to understand option "Force these preferences on all directories".
**Validation**
=> Feature: Added an option to set default columns

src/Files.Shared/Extensions/LinqExtensions.cs
- Closes Appcenter 2855768364u
- Calling Add() on a ConcurrentDictionary cast to IDictionary breaks concurrency. Need to cast it to ConcurrentDictionary and call TryAdd explicitly.
**Validation**
=> Add cast from IDictionary to ConcurrentDictionary

src/Files.App/Extensions/StringExtensions.cs
- Fix the GetLocalizedResource() method to return empty string instead of throwing exception when the string resource is not found. This was the behavior on UWP and some code relies on this.
**Validation**
=> Fix localized strings appearing empty in Compatibility properties

src/Files.App/Filesystem/StorageEnumerators/Win32StorageEnumerator.cs, src/Files.App/Helpers/FileListCache/FileListCacheController.cs, src/Files.App/Helpers/FileListCache/IFileListCache.cs, src/Files.App/Shell/Win32API.cs, src/Files.App/Shell/Win32Shell.cs, src/Files.App/ViewModels/ItemViewModel.cs, src/Files.App/Views/CustomFolderIcons.xaml.cs
- Introduced a cache for icon and overlay
- Avoid using `Task.Run` for long-running tasks
**Validation**
=> Icon cache and Task.Run tweaks

src/Files.App/Strings/en-US/Resources.resw, src/Files.App/Views/SettingsPages/About.xaml
FluentUI isn't hard coded into Files so are no longer required to reference the license
**Validation**
=> Fix: Removed FluentUI reference

src/Files.App/UserControls/Settings/SettingsBlockControl.xaml, src/Files.App/UserControls/Settings/SettingsDisplayControl.xaml, src/Files.App/Views/SettingsPages/About.xaml, src/Files.App/Views/SettingsPages/Appearance.xaml, src/Files.App/Views/SettingsPages/Preferences.xaml
=> Feature: Reduce sub settings item height

src/Files.App/Helpers/FilePropertiesHelpers.cs
- Closes #9931 
**Changes**
- Now minimize and maximize buttons are hidden.
- Now the properties window can't be resized by the user
**Validation**
=> Feature: Hide minimize/maximize buttons on the properties window

src/Files.App/Helpers/ContextFlyoutItemHelper.cs, src/Files.App/Interacts/BaseLayoutCommandImplementationModel.cs, src/Files.App/UserControls/InnerNavigationToolbar.xaml, src/Files.App/ViewModels/ToolbarViewModel.cs
=> Feature: Added support for extracting multiple archives at same time.

src/Files.App/Views/MainPage.xaml.cs
- Fixes dragging the window on windows 10
Despite the docs, SetDragRectangles() still does not work on win10 with winappsdk "1.2.220902.1-preview1" :/
Confirmed on Discord.
The workaround is kinda ugly, if you prefer to just wait for a fix from winappsdk I'm ok to not merge this. Does not change things on win11.
**Validation**
=> Workaround for titlebar drag area on windows 10

src/Files.App/IBaseLayout.cs, src/Files.App/Interacts/BaseLayoutCommandImplementationModel.cs, src/Files.App/UserControls/SidebarControl.xaml.cs, src/Files.App/UserControls/Widgets/DrivesWidget.xaml, src/Files.App/UserControls/Widgets/DrivesWidget.xaml.cs, src/Files.App/UserControls/Widgets/FolderWidget.xaml, src/Files.App/UserControls/Widgets/FolderWidget.xaml.cs
- Closes #9926 
**Comments**
- The root of the problem was that, after the properties windows was opened, the focus returned to the main window because of the closing of the flyout context menu. I fixed the bug opening Properties after the menu gets closed
- If everything is ok, I'll proceed with code cleanup
**Validation**
=> Fixed: Properties window opens behind main app window

src/Files.Shared/ShellFileItem.cs, src/Files.Shared/ShellLibraryItem.cs, src/Files.Shared/ShellLinkItem.cs
- Fixes an issue where lnk to folders open in explorer instead of Files
**Changes**
Change fields that must be serialized to json into properties. System.Text.Json.JsonSerializer does not serialize fields by default (unlike JsonConvert).
**Validation**
=> Fix shortcuts to folders opening outside Files

src/Files.App/Helpers/ItemListDisplayHelpers/BulkConcurrentObservableCollection.cs
- Closes #9521
- Related #9895
- Fixed: when an element is removed from a group, if the group is empty, it is deleted
- Added null checks
**Validation**
- Built and ran the app
=> Fixed: Empty groups are still shown

src/Files.App/App.xaml.cs, src/Files.App/ViewModels/Properties/FileProperties.cs
- Related Issue #9881 
- Related Issue #9873 
**Validation**
=> Fixed problem with migration to System.Text.Json

src/Files.App/Filesystem/Cloud/Detector/DropBoxCloudDetector.cs, src/Files.App/Filesystem/FilesystemOperations/ShellFilesystemOperations.cs, src/Files.App/Helpers/TypesConverter.cs, src/Files.App/UserControls/MultitaskingControl/TabItem/TabItem.cs
- Related #10003 
- Related #9881 
- Related #9873 
- Related #10000 
**Validation**
**Comments**
Pls leave this open as I'm testing for other bugs/problems related to the migration to System.Text.Json
I apologize for not having tested this deeply before committing
=> Fix Migration to System.Text.Json

src/Files.App.Storage/IsExternalInit.cs, src/Files.App/IsExternalInit.cs
IsExternalInit classes were added to handle the init keyword. These classes are no longer needed for .NET 6 because this keyword is natively managed. This pr removes these files for .net 6 projects only. This has no effect on the software.
**Validation**
=> Remove unused class IsExternalInit

src/Files.App/Interacts/BaseLayoutCommandImplementationModel.cs
- Related #9926 
- Related #9973 
**Changes**
Because of #9973 , users couldn't open properties clicking on `InfoButton`, this PR fixs that.
**Validation**
=> Fix: Fixed issue blocking properties window from opening

src/Files.App/UserControls/InnerNavigationToolbar.xaml.cs, src/Files.App/ViewModels/MainPageViewModel.cs, src/Files.App/Views/MainPage.xaml.cs
- Closes #9928 
**Changes**
- Removed unused methods in `InnerNavigationToolbar.caml.cs` (`NavToolbarEnterCompactOverlay_Click()` and `SetAppBarButtonProps()`)
- Changed `Setter` of `IsWindowCompactOverlay` (`MainPageViewModel.cs`) as the existing one was not affecting the backing `DependencyProperty`
- Fixed logic-error in `SetCompactOverlay()` (`MainPage.xaml.cs`) line@ 508 and 513
**Validation**
=> Fix: Fixed issue where the option to leave compact overlay didn't work

src/Files.App/BaseLayout.cs, src/Files.App/Views/LayoutModes/ColumnViewBase.xaml, src/Files.App/Views/LayoutModes/ColumnViewBase.xaml.cs, src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml, src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs, src/Files.App/Views/LayoutModes/GridViewBrowser.xaml, src/Files.App/Views/LayoutModes/GridViewBrowser.xaml.cs
- Closes #9834 
**Comments**
I changed `RightTapped` event-area, applying it to items' container (same as #9977 )
If you think this is ok, I'll proceed with code cleanup (remove nullable warnings)
**Validation**
=> Fixed: Right click doesn't always select the file/folder hovered over

src/Files.App/Interacts/BaseLayoutCommandImplementationModel.cs
- Closes #10062 
**Validation**
**Comments**
There was a problem with `ShowAsync` and all `Dialogs`, it could be easily fixed by moving to `TryShowAsync`
@Josh-65 could you try this out (I'm not sure if this is the only needed fix)?
=> Fixed: Unable to extract archives from context menu

src/Files.App/Filesystem/BaseStorage/BaseStorageFile.cs
- Fixes an issue where preview for a text file with ANSI encoding (default for notepad) does not work
**Changes**
- Use StreamReader instead of DataReader as it auto-detects encoding
**Validation**
=> Fix: Fixed issue where preview of ANSI text didn't work

src/Files.App/Views/Pages/Properties.xaml.cs, src/Files.App/Views/Pages/PropertiesSecurity.xaml.cs
- Closes #9919 
**Changes Details**
I added a method that calculates `DragRectangles` for `TitleBar`. It's called once on load and then whenever you resize the window.
This method creates two rectangles:
- one over `NavigationViewItem`s (so that you can drag from the 8px margin)
- one on their right side
**Validation**
=> Fixed: Properties window has the wrong drag region on the title bar

src/Files.App/BaseLayout.cs
- Related: #6768 
**Comments**
- I fixed the bug delaying the selection at the end of the timer. This way, the hovered item is selected just before it's opened.
- There's still a problem with `ColumnsLayout`, where items have `SelectedStyle` even when they're not. I believe the bug affects `ListViewBase` since the code is the same as in `GridViewBase`, where the feature is working.
**Validation**
=> Fixed: Draging files over items select them

src/Files.App/Helpers/AdaptiveLayoutHelpers.cs, src/Files.App/Helpers/LayoutPreferences/LayoutPreferences.cs, src/Files.App/ServicesImplementation/Settings/LayoutSettingsService.cs, src/Files.App/ServicesImplementation/Settings/PreferencesSettingsService.cs, src/Files.App/Strings/en-US/Resources.resw, src/Files.App/ViewModels/FolderSettingsViewModel.cs, src/Files.App/ViewModels/SettingsViewModels/PreferencesViewModel.cs, src/Files.App/Views/SettingsPages/Preferences.xaml, src/Files.Backend/Services/Settings/ILayoutSettingsService.cs, src/Files.Backend/Services/Settings/IPreferencesSettingsService.cs, src/Files.Shared/Enums/FolderLayoutModes.cs
=> Feature: Added option to change default layout mode

src/Files.App/UserControls/AddressToolbar.xaml
- Closes #10150 
**Validation**
**Comments**
In #10116  the Property ItemName was removed. The property Name returns exactly the same value as ItemName did before.
Suggestions are displayed again
=> Fix: Folder suggestions are not showing in the Address bar

src/Files.App/UserControls/SidebarControl.xaml.cs
- Closes #9753 
**Comments**
I removed "move" option from all sidebar items that are not in the `Favourite Section` (I think this is the expected behavior)
**Validation**
=> Fix: Fixed issue where tags section showed "move" option

src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml, src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs
- Closes #9927 
**Comments**
It seems this is a <a href="https://github.com/microsoft/microsoft-ui-xaml/issues/4834">known bug</a> of WinUI3.
This is a workaround to fix that.
**Validation**
=> Fix: Fixed issue where GridSplitter style was missing on the details layout

src/Files.App/UserControls/SidebarControl.xaml.cs
The entries "Move on down" and "Move to bottom" of the favorites section is a bug (on the title, not on the items), without effect. This pr fix this. 
Fixes #10215
**Validation**
Before/After.
=> Fix: Fixed issue where right clicking on sidebar items showed the wrong menu options

src/Files.App/ServicesImplementation/Settings/FoldersSettingsService.cs
- Related #10117 #9867 
**Comments**
There was a bug involving hidden columns.
Steps to reproduce:
- Hide at least one column
- Set column widths as default
- Show one of the hidden columns
- See that its width is 0px
**Validation**
=> Fix: Fixed issue where columns sometimes had no width

src/Files.App/Helpers/FileExtensionHelpers.cs, src/Files.App/Interacts/BaseLayoutCommandImplementationModel.cs, src/Files.App/UserControls/InnerNavigationToolbar.xaml, src/Files.App/ViewModels/ToolbarViewModel.cs
- Closes #9822
**Comments**
I recycled the existing code and adapted it so that it works in both cases (inside and outside archives).
If you think I should implement this feature with brand new code, I'll find another workaround.
**Validation**
=> Feature: Added extract archive button inside archives

src/Files.App/ViewModels/ColumnsViewModel.cs, src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml
- Closes #10230 
**Validation**
=> Fix: Fixed an issue where the name column had a max width

src/Files.App/DataModels/NavigationControlItems/DriveItem.cs
When you connect a new drive and the homepage is displayed, the drive widget is displayed but without the progressbar. You have to refresh the page to display it. This pr fixes this so that the progressbar always shows.
**Validation**
Before/After
=> Fix: Fixed issue where the progress bar wasn't shown when connecting new drives

src/Files.App/DataModels/NavigationControlItems/DriveItem.cs, src/Files.App/UserControls/SidebarControl.xaml, src/Files.App/Views/Pages/PropertiesGeneral.xaml
Changes the sidebar drives template to match the property menu 
Closes #10214.
**Validation**
before/after
=> Feature: Improved the tooltip when hovering over drives

src/Files.App/UserControls/Widgets/DrivesWidget.xaml.cs, src/Files.App/ViewModels/SidebarViewModel.cs
Detected drives are always displayed at the end. It makes more sense to display them in order according to the path. Sometimes internal drives are not displayed in path order.  
Closes #10252.
This pr keeps drives sorted by path in the sidebar and homepage.
**Validation**
=> Fix: Fixed issue where drives had the wrong order in the sidebar

src/Files.App/UserControls/SidebarControl.xaml, src/Files.App/Views/Pages/PropertiesGeneral.xaml
Fix the bad position of the text Capacity in the properties of drives.
The correct padding is 25, not 28, as the rectangle (width 15 + margin 10).
**Validation**
Before/After
=> Fix: Fixed issue with the text alignment in the properties window

src/Files.App/DataModels/NavigationControlItems/DriveItem.cs
The access path of network disks which have a local access path is not displayed in their label, contrary to fixed disks. This is so in the item name received by .net and FileExplorer has the same problem. This pr adds this missing path for consistency and readability
Closes #10261.
**Validation**
Before/After
=> Feature: Display drive letter of the connected network drives

src/Files.App/UserControls/SidebarControl.xaml, src/Files.App/Views/Pages/PropertiesGeneral.xaml
This pr fixes the style of displaying drive sizes (Property and Tooltip).
- In the tooltip, the background of the ring was missing.
- In the tooltip, the 3 texts did not use exactly the same style.
- In light mode, the color of the free space legend did not match the color used by the ring. The color of the ring has been used because it is more readable and this corresponds to the progressbar of the Drive widget.
**Validation**
Before Property
After Property
Before Tooltip
After Tooltip
=> Fix: Fixed progress ring style in drive tooltip

src/Files.App/Filesystem/StorageItems/ZipStorageFile.cs, src/Files.App/Helpers/FileOperationsHelpers.cs, src/Files.App/Helpers/NativeFileOperationsHelper.cs
- Removes unnecessary OpenProtectedFileForRead function. The function was used when opening files from inside an archive due to UWP limitations but it's not necessary anymore.
**Validation**
=> Remove OpenProtectedFileForRead function

src/Files.App/Helpers/UIFilesystemHelpers.cs
- Closes #10157 
- Fixed the crash : the `Replace` function could not handle when `item.Name` was empty.
- Did some minor refactoring.
**Validation**
=> Fix: Fixed issue where renaming a shortcut that had a blank name would cause a crash

src/Files.App/UserControls/SidebarControl.xaml.cs
In the sidebar, the context menu may not be entirely visible. This pr changes its placement so that it is no longer obscured by the edge of the window.
**Validation**
Before
After
=> Fix: Fixed issue where the sidebars right click menu would sometimes get cut off

src/Files.App/UserControls/InnerNavigationToolbar.xaml
None
**Changes made**
This PR removes the icons from the archive extraction flyout, since they take up space and add clutter while adding little information.
**Validation**
=> Fix: Remove icons from extract flyout

src/Files.App/Views/ColumnShellPage.xaml.cs, src/Files.App/Views/LayoutModes/ColumnViewBase.xaml.cs, src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs, src/Files.App/Views/LayoutModes/GridViewBrowser.xaml.cs, src/Files.App/Views/ModernShellPage.xaml.cs
- Closes #9499 
- Added a shortcut so Ctrl+Enter opens all selected folders into news tab in GridViewBrowser and DetailsLayoutBrower.
- Did some minor refactoring.
**Validation**
=> Feature: Open selected folders in new tab using Ctrl+Enter

src/Files.App/UserControls/Widgets/DrivesWidget.xaml.cs, src/Files.App/UserControls/Widgets/FolderWidget.xaml.cs, src/Files.App/ViewModels/Pages/YourHomeViewModel.cs
- Closes #8441 
- Switching from `BulkConcurrentObservableCollection` to `ObservableCollection`.
- Minor refactoring.
**Validation**
=> Feature: Improve loading animations on the home page

src/Files.App/Views/Pages/PropertiesGeneral.xaml, src/Files.App/Views/Pages/PropertiesGeneral.xaml.cs
Improves PropertiesGeneral control:
- The code is more readable. Some warnings are fixed.
- When leaving the name field with an empty name, the previous name is returned.
- For drives, the letter of the name is removed during editing. #10263.
**Validation**
https://user-images.githubusercontent.com/46631671/198020958-e7927c35-3a52-45ce-a73c-1c6c67da5216.mp4
=> Fix: Fixed issue where the drive letter was included in the name

src/Files.App/App.xaml.cs, src/Files.App/Helpers/UniversalLogWriter.cs, src/Files.App/MainWindow.xaml.cs
- Initialize logger and components in the background
- Remove unnecessary async
- Activate the Window early and postpone activation arguments parsing
Suggestion: merge both #10283 and this PR to see the startup performance boost. 
**Validation**
=> Feature: Optimize startup speed

src/Files.App/ServicesImplementation/DateTimeFormatter/AbstractDateTimeFormatter.cs, src/Files.App/ServicesImplementation/DateTimeFormatter/ApplicationDateTimeFormatter.cs, src/Files.App/ServicesImplementation/DateTimeFormatter/SystemDateTimeFormatter.cs, src/Files.App/ServicesImplementation/DateTimeFormatter/UniversalDateTimeFormatter.cs
Some dates may display in the Windows culture (language and format) instead of the Files culture. This is fixed. 
The issue mentions other location issues. These are special folders whose names are provided by Windows. We cannot modify these texts according to the language in a simple way. I think it is useless to replace these texts according to the language.
**Validation**
=> Fix: Use date from Windows culture instead of Files culture

src/Files.App/Strings/en-US/Resources.resw
Column names no longer end with ":", except for the Type column. This pr fixes this in English. The translations will have to adapt because the problem exists in the other languages.
I did not create an issue because it would have taken me as long as creating the pr.
**Validation**
Before
After
=> Fix: Fixed column Type text

src/Files.App/Helpers/FileOperationsHelpers.cs, src/Files.OpenDialog/CustomOpenDialog/CustomOpenDialog.vcxproj, src/Files.OpenDialog/FilesLauncher/FilesLauncher.vcxproj, src/Files.OpenDialog/FilesLauncher/packages.config
- Fix build for FilesLauncher and CustomOpenDialog projects (updates paths from Files.Fulltrust -> Files.App, adds CppWinRT as an explicit dependency)
**Validation**
=> Fix FilesLauncher and CustomOpenDialog projects

src/Files.App/App.xaml.cs
- Fix crash when checking for updates. IUpdateService methods are supposed to be called from the UI thread.
- Wait for file transfers to complete before terminating process
- Restored call to UpdateTagsDb()
**Validation**
=> Fixed crash that would occur when checking for updates

src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs, src/Files.App/Views/LayoutModes/GridViewBrowser.xaml.cs
- Closes #10387
Find UI element by name instead of parent/child. Copied logic from Details layout.
**Validation**
=> Fix: Fixed crash when renaming in GridView

src/Files.App/App.xaml.cs, src/Files.App/DataModels/AppModel.cs
- Closes #10379
Issue was checking the Clipboard in the window Activated event. Doing so is not necessary in Winui3 (window receives Clipboard events also when minimized).
**Validation**
=> Fixed issue where the Files window wasn't being activated on Win+Num

src/Files.App/Views/ColumnShellPage.xaml.cs, src/Files.App/Views/ModernShellPage.xaml.cs
The help command (key F1) use the url instead of the constant. This pr uses the constant that already exists.
**Validation**
=> Code Quality: Use constant documentation for help command

src/Files.App/BaseLayout.cs, src/Files.App/Helpers/NavigationHelpers.cs, src/Files.App/Interacts/BaseLayoutCommandImplementationModel.cs, src/Files.App/Views/LayoutModes/ColumnViewBase.xaml.cs, src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs, src/Files.App/Views/LayoutModes/GridViewBrowser.xaml.cs
- Closes #9042 
- Related to #10438 (Example of bug that can be fixed if fixing `async void` method use)
- Now selecting the first item of a newly opened folder using Enter in DetailsLayout.
- Changed `OpenSelectedItems` from `async void` to `async Task`
- Minor refactoring.
**Validation**
=> Fix: Focus first item in folder when opening it with keyboard in DetailsLayout

src/Files.App/Helpers/ZipHelpers.cs
Compression fails when one of the selected items is a file (not a directory). This pr fixes this.
**Validation**
=> Fix: Fixed issue with compressing files

src/Files.App/Helpers/ZipHelpers.cs
- Closes #10414
- 7zip library doesn't distinct files and firectories. Because of this, they are all added to `fileEntries`
- I fixed this by removing the directories from the list after they are created
**Validation**
=> Fix: Fixed issue where 7z archives were not extracted correctly

src/Files.App/Filesystem/StorageItems/ZipStorageFolder.cs
- Closes #10529
**Validation**
**Explanation**
Zip files were not recognized as browsable zip because this method returned false if Files is set as default app.
`assoc` contains the full path to the associated app, for example “C:\\Program Files\\WindowsApps\\FilesPreview_2.3.61.0_x64__wvne1zexy08sa\\Files.App\\Files.exe”
The package `FamilyName` is in debug mode for example “FilesDev_ykqwq8d6ps0ag”
I also thought about comparing it with the current executing assembly path or to check if the associated path contains the Package Name, but that would not work in debug mode or if multiple files apps are installed (Store, Sideload, …)
=> Fix: Open archives in existing tab if files is set as default app

src/Files.App/ViewModels/ColumnsViewModel.cs, src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml
- Closes #10432 
**Changes**
- I added a column with `width=0`, since I discovered that you can't resize the last column
- I removed `BsonIgnore` from `NormalMaxLength`, as this prevented length constraints from being applied to custom folders
**Validation**
=> Feature: Allow resizing the status column

src/Files.App/ViewModels/ColumnsViewModel.cs
- None, small optimization
Currently we are serializing unnecessary/calculated fields of ColumnsViewModel to the preference DB. This PR adds [BsonIgnore] to those.
Before (each column per each folder):
```json
"NameColumn": 
{
"LengthIncludingGridSplitter": 
{
"Value": 248.0,
"GridUnitType": "Pixel",
"IsAbsolute": true,
"IsAuto": false,
"IsStar": false
},
"Length": 
{
"Value": 240.0,
"GridUnitType": "Pixel",
"IsAbsolute": true,
"IsAuto": false,
"IsStar": false
},
"UserCollapsed": false,
"UserLength": 
{
"Value": 240.0,
"GridUnitType": "Pixel",
"IsAbsolute": true,
"IsAuto": false,
"IsStar": false
},
"UserLengthPixels": 240.0
},
```
After:
```json
"NameColumn": 
{
"UserCollapsed": false,
"UserLengthPixels": 240.0
} …
```
=> Only save necessary info to folder preferences

src/Files.App/Filesystem/StorageItems/ZipStorageFolder.cs
- Fixes an issue with #10554
On my PC `assoc` contains exactly `FilesDev_ykqwq8d6ps0ag` (FamilyName). So the PR for me actually causes the issue it's supposed to solve.
Not sure where the difference is (OS version?) but leaving both checks (FamilyName + Files.exe path) should be good for everyone.
**Validation**
=> Check zip assoc against FamilyName

src/Files.App/UserControls/FilePreviews/HtmlPreview.xaml.cs
- Closes #10525
WebView2 must be initialized before use.
**Validation**
=> Fix: Fixed crash that would occur when previewing .svg files

src/Files.App/Filesystem/FilesystemOperations/ShellFilesystemOperations.cs
- Closes #10530
When it could not find which process was locking a file, code was calling ToList() on a null object.
**Validation**
=> Fix: Fixed issue where app would freeze when deleting a folder that had an open file

src/Files.App/Views/MainPage.xaml.cs, src/Files.App/Views/Pages/Properties.xaml, src/Files.App/Views/Pages/Properties.xaml.cs
Latest WinAppSdk appears to fix the titlebar issue on windows 10. This PR removes the workaround we had.
Also tries to solve #9919 aligning the code to what we do in MainPage (not sure if it works)
**Validation**
=> Remove workaround for drag area on Windows 10

src/Files.App/App.xaml.cs, src/Files.App/MainWindow.xaml.cs
- Closes #10370
This looks like a WinUI bug. When launching Files from command line I'd expect the launch arg to be of type ICommandLineActivatedEventArgs, but it's of type ILaunchActivatedEventArgs instead.
This PR adds a workaround by checking if the argument contains the files.exe executable path and treating it like a cmdline arg in case.
**Validation**
=> Fix: Fixed issue where it didn't work to open a path in Files using command line

src/Files.App/Filesystem/FileTagsHelper.cs, src/Files.App/Filesystem/ListedItem.cs, src/Files.App/Filesystem/Search/FolderSearch.cs, src/Files.App/Helpers/FileOperationsHelpers.cs, src/Files.App/Helpers/LayoutPreferences/LayoutPrefsDb.cs, src/Files.App/Helpers/NativeFileOperationsHelper.cs, src/Files.App/MainWindow.xaml.cs, src/Files.App/ViewModels/FolderSettingsViewModel.cs, src/Files.App/ViewModels/ItemViewModel.cs, src/Files.App/ViewModels/SettingsViewModels/AboutViewModel.cs, src/Files.App/ViewModels/SettingsViewModels/FoldersViewModel.cs, src/Files.Shared/FileTagsDb.cs, src/Files.Shared/Files.Shared.csproj
- Since #10250 file tags are loaded noticeably slower. This PR restores the previous code. LiteDB dependency is downgraded to v4 as v5 does not handle concurrent access from multiple processes for packaged apps.
**Validation**
=> Fix: Fixed issue where tags loaded slowly

src/Files.App/Helpers/ContextFlyoutItemHelper.cs, src/Files.App/Views/ModernShellPage.xaml.cs, src/Files.App/Views/PaneHolderPage.xaml.cs
- Closes #10663
- Fixes an issue causing "drive unplugged" dialog to appear when opening a tag from the sidebar in a new tab
- Fixes an issue causing context menu not to appear for tags in the sidebar
- Fixes an issue where "continue where you left off" would open the same folder in both panes
**Validation**
=> Fix: Fixed opening a tag from sidebar in a new tab

src/Files.App/Dialogs/CreateArchiveDialog.xaml
- Fixed an issue where the spacing in the create archive dialog was inconsistent with the spacing in properties and settings.
**Validation**
=> Fix: Fixed spacing in the create archive dialog

src/Files.App/Shell/ShellNewMenuHelper.cs
- Closes #9548
Adds entry for .txt "manually" since in windows11 the extension does not have a ShellNew key (but still appears in explorer new menu)
**Validation**
=> Fix: Added missing txt and zip options in the new file menu

src/Files.App/ViewModels/ItemViewModel.cs
- Closes #2436 
**Validation**
=> Feature: Show shortcuts & hidden files in network folders

src/Files.App/Helpers/FileOperationsHelpers.cs
In debug, Visual sSudio stops at a Win32Exception necessary to know if the recycle bin can be used. This pr disables Visual Studio stops for this exception.
**Validation**
=> Fix: Prevent Visual Studio from stopping when deleting an item

src/Files.App/App.xaml.cs
- Fixes crash notification being shown on non-critical exception.
**Validation**
=> Feature: Show notification only when app crashes

src/Files.App/Helpers/FilePropertiesHelpers.cs, src/Files.App/Views/Pages/PropertiesSecurityAdvanced.xaml
- Fixed issue where properties window was always on top
**Validation**
=> Fix: Fixed issue where properties window was always on top

src/Files.App/MainWindow.xaml.cs, src/Files.App/ViewModels/MainPageViewModel.cs
- Closes #10899
Instead of hardcoding the app name "Files", it takes the name from the SystemInformation class instead. In dev mode the title will be "Folder name - Files - Dev". I would recommend changing "Files - Dev" to "Files (Dev)" or simply "Files Dev" because it's cleaner.
**Validation**
=> Append app name to title

src/Files.Sdk.Storage/ModifiableStorage/IModifiableStorable.cs
The interface IModifiableStorable is not IStorable. This pr repairs this oversight.
**Validation**
=> Codebase: Made IModifiableStorable IStorable

src/Files.App/UserControls/SidebarControl.xaml.cs
- Related #10467 - A crash would occurs for some users when expanding/collapsing the sidebar since the refactoring, because of an access on a null object.
- Added back the null check that seemingly prevents the crash to occur for the concerned users.
=> Fix: Fixed crash from #10467

src/Files.App/UserControls/Widgets/WidgetsListControl.xaml, src/Files.App/Views/ModernShellPage.xaml.cs
=> Feature: Improved animations on the home page

src/Files.App/Helpers/WidgetsHelpers.cs, src/Files.App/ServicesImplementation/Settings/AppearanceSettingsService.cs, src/Files.App/ServicesImplementation/Settings/PreferencesSettingsService.cs, src/Files.App/Strings/en-US/Resources.resw, src/Files.App/UserControls/Widgets/BundlesWidget.xaml.cs, src/Files.App/UserControls/Widgets/DrivesWidget.xaml.cs, src/Files.App/UserControls/Widgets/FolderWidget.xaml.cs, src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml.cs, src/Files.App/ViewModels/SettingsViewModels/AppearanceViewModel.cs, src/Files.App/ViewModels/SettingsViewModels/PreferencesViewModel.cs, src/Files.App/ViewModels/ToolbarViewModel.cs, src/Files.App/Views/SettingsPages/Appearance.xaml, src/Files.App/Views/SettingsPages/Preferences.xaml, src/Files.App/Views/WidgetsPage.xaml.cs, src/Files.Backend/Services/Settings/IAppearanceSettingsService.cs, src/Files.Backend/Services/Settings/IPreferencesSettingsService.cs
- Moved widget settings to preferences
**Validation**
=> Feature: Moved widget settings to preferences

src/Files.App/Strings/en-US/Resources.resw, src/Files.App/Views/SettingsPages/Appearance.xaml, src/Files.App/Views/SettingsPages/Appearance/AppThemeResourcesFactory.cs
- Expand the background colors section by default
- Removed some of the unused color presets
- Renamed "Compact Styles" to "Compact Spacing"
**Validation**
=> Feature: Expand the background colors section by default

src/Files.App/BaseLayout.cs, src/Files.App/Filesystem/FilesystemOperations/Helpers/FilesystemHelpers.cs, src/Files.App/Filesystem/ListedItem.cs, src/Files.App/ServicesImplementation/Settings/FoldersSettingsService.cs, src/Files.App/ServicesImplementation/Settings/PreferencesSettingsService.cs, src/Files.App/Strings/en-US/Resources.resw, src/Files.App/UserControls/InnerNavigationToolbar.xaml, src/Files.App/ViewModels/ItemViewModel.cs, src/Files.App/ViewModels/SettingsViewModels/FoldersViewModel.cs, src/Files.App/ViewModels/SettingsViewModels/PreferencesViewModel.cs, src/Files.App/Views/LayoutModes/ColumnViewBase.xaml.cs, src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs, src/Files.App/Views/LayoutModes/GridViewBrowser.xaml.cs, src/Files.App/Views/SettingsPages/About.xaml, src/Files.App/Views/SettingsPages/Appearance.xaml, src/Files.App/Views/SettingsPages/Folders.xaml, src/Files.App/Views/SettingsPages/Preferences.xaml, src/Files.Backend/Services/Settings/IFoldersSettingsService.cs, src/Files.Backend/Services/Settings/IPreferencesSettingsService.cs
=> Feature: Rearranged folder options in the settings dialog

src/Files.App/ServicesImplementation/SideloadUpdateService.cs, src/Files.App/ServicesImplementation/UpdateService.cs, src/Files.App/Strings/en-US/Resources.resw, src/Files.App/UserControls/AddressToolbar.xaml, src/Files.Backend/Services/IUpdateService.cs
- Added progress ring when updating app
- Added icon to view release notes (teaching tip/flyout to be implemented later on)
**Validation**
=> Feature: Added progress ring when updating app

src/Files.App/Views/LayoutModes/ColumnViewBase.xaml, src/Files.App/Views/LayoutModes/ColumnViewBrowser.xaml
- Improved animations in the Columns layout
**Validation**
=> Feature: Improved animations in the Columns layout

src/Files.App/BaseLayout.cs, src/Files.App/Filesystem/StorageItems/VirtualStorageItem.cs
Reverts files-community/Files#10949
Closes #10961
=> Revert "Fix: Fixed issues with drag & drop from Files to other apps"

src/Files.App (Package)/Package.appxmanifest, src/Files.App/Views/LayoutModes/GridViewBrowser.xaml
- Closes #10983
**Validation**
=> Fix: Fixed thumbnails in grid layout

src/Files.App/ServicesImplementation/Settings/AppearanceSettingsService.cs, src/Files.App/ValueConverters/ColorToSolidColorBrushValueConverter.cs, src/Files.App/ViewModels/SettingsViewModels/AppearanceViewModel.cs, src/Files.App/Views/MainPage.xaml.cs, src/Files.App/Views/SettingsPages/Appearance.xaml, src/Files.App/Views/SettingsPages/Appearance/AppThemeResource.cs, src/Files.App/Views/SettingsPages/Appearance/AppThemeResourcesFactory.cs
=> Feature: Improved the background color preview

src/Files.App/Filesystem/FileTagsHelper.cs, src/Files.App/Filesystem/StorageItems/ZipStorageFile.cs, src/Files.App/Filesystem/StorageItems/ZipStorageFolder.cs, src/Files.App/Helpers/AdaptiveLayoutHelpers.cs, src/Files.App/Helpers/FileOperationsHelpers.cs, src/Files.App/Helpers/Fractions.cs, src/Files.App/Helpers/NaturalStringComparer.cs, src/Files.App/Helpers/StorageHelpers.cs, src/Files.App/UserControls/Selection/RectangleSelection_ListViewBase.cs, src/Files.App/ViewModels/SelectedItemsPropertiesViewModel.cs
-  Related to #10359 
Removes some unnecessary casts in the codebase
**Validation**
=> Codebase: Remove unnecessary casts

src/Files.App/Helpers/AppThemeResourcesHelper.cs, src/Files.App/ValueConverters/StringToSolidColorBrushValueConverter.cs, src/Files.App/ViewModels/MainPageViewModel.cs, src/Files.App/ViewModels/SettingsViewModels/AppearanceViewModel.cs, src/Files.App/Views/MainPage.xaml, src/Files.App/Views/MainPage.xaml.cs, src/Files.App/Views/SettingsPages/Appearance.xaml, src/Files.App/Views/SettingsPages/Appearance/AppThemeResource.cs, src/Files.App/Views/SettingsPages/Appearance/AppThemeResourcesFactory.cs
- Switched property in view model and resource factory to string. This accounts for empty strings which indicate the default value. If we didn't use blank strings to indicate default, we'd have to provide a separate value for light and dark mode.
- Added `LoadAppResources` method to `AppThemeResourcesHelper`
- Call `LoadAppResources` from the ViewModel instead of the View. 
**Validation**
=> Codebase: Refactored themes

src/Files.App/ServicesImplementation/Settings/FoldersSettingsService.cs, src/Files.App/Strings/en-US/Resources.resw, src/Files.App/ViewModels/SettingsViewModels/FoldersViewModel.cs, src/Files.App/Views/LayoutModes/ColumnViewBase.xaml.cs, src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs, src/Files.App/Views/LayoutModes/GridViewBrowser.xaml.cs, src/Files.App/Views/SettingsPages/Folders.xaml, src/Files.Backend/Services/Settings/IFoldersSettingsService.cs
Added option to configure if double clicking a blank space goes up a directory 
**Validation**
=> Feature: Added option to turn off double click gesture

src/Files.App/Filesystem/ListedItem.cs, src/Files.App/Strings/en-US/Resources.resw, src/Files.App/Views/LayoutModes/ColumnViewBase.xaml
**Changes**
- Added item size to the tooltip
- Display correct tooltip in the column layout
**Validation**
=> Feature: Display item size in tooltip

src/Files.App/Helpers/AdaptiveLayoutHelpers.cs, src/Files.App/ServicesImplementation/Settings/FoldersSettingsService.cs, src/Files.App/Strings/en-US/Resources.resw, src/Files.App/ViewModels/FolderSettingsViewModel.cs, src/Files.App/ViewModels/ItemViewModel.cs, src/Files.App/ViewModels/SettingsViewModels/FoldersViewModel.cs, src/Files.App/ViewModels/ToolbarViewModel.cs, src/Files.App/Views/SettingsPages/Folders.xaml, src/Files.Backend/Services/Settings/IFoldersSettingsService.cs
- Closes #11075
- Removes option to reset preferences manually, instead we automatically reset them when changing the setting 
**Validation**
=> Feature: Added setting to sync folder preferences across directories

src/Files.App/BaseLayout.cs, src/Files.App/Helpers/ContextFlyoutItemHelper.cs, src/Files.App/Helpers/ShellContextMenuHelper.cs, src/Files.App/ServicesImplementation/Settings/AppearanceSettingsService.cs, src/Files.App/Strings/en-US/Resources.resw, src/Files.App/UserControls/SidebarControl.xaml.cs, src/Files.App/ViewModels/SettingsViewModels/AppearanceViewModel.cs, src/Files.App/Views/SettingsPages/Appearance.xaml, src/Files.Backend/Services/Settings/IAppearanceSettingsService.cs
**About this change**
The goal of this change is to have a more predictable height for the context menu. Once we find a way to load extensions faster, we should look into reverting this change.
**Validation**
=> Feature: Move shell extensions to sub menu by default

src/Files.App/Filesystem/FilesystemOperations/Helpers/FilesystemHelpers.cs
- Closes #11096 
**Details**
7-zip returns a partially short path, so convert it to a full path so that duplicate path entry can be eliminated without fail.
**Validation**
=> Fix: Fixed app crash when copying file from 7-zip

src/Files.App/Strings/en-US/Resources.resw, src/Files.App/UserControls/Widgets/BundlesWidget.xaml, src/Files.App/ViewModels/SettingsViewModels/PreferencesViewModel.cs, src/Files.App/Views/SettingsPages/Preferences.xaml
**Notes**
Have fun with the tags and bundles widget toggles in settings.
**Validation**
=> Feature: Added InfoBar to the bundles widget

src/Files.App/ServicesImplementation/DateTimeFormatter/ApplicationDateTimeFormatter.cs, src/Files.App/Strings/en-US/Resources.resw, src/Files.App/ViewModels/SettingsViewModels/PreferencesViewModel.cs
- Closes #9755 
**Details**
If the timestamp is in the future due to time synchronization or other reasons, the timestamp itself is displayed instead of the elapsed time.
Additionally, '1 seconds ago' replaces '1 second ago' and '0 seconds ago' replaces 'Now'.
**Validation**
=> Fix: Fixed showing a negative elapsed time in case of a future timestamp

src/Files.App/Helpers/UIFilesystemHelpers.cs, src/Files.App/ViewModels/Properties/FolderProperties.cs
- Closes #10914
**Validation**
=> Fix: Fixed issue with environment variables not working for shortcuts

src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs, src/Files.App/Views/LayoutModes/GridViewBrowser.xaml.cs
- Closes #11052...
**Validation**
=> Fix: Fixed issue where multiselect broke open with single click

src/Files.App/BaseLayout.cs, src/Files.App/ServicesImplementation/Settings/AppearanceSettingsService.cs, src/Files.App/Strings/en-US/Resources.resw, src/Files.App/ViewModels/SettingsViewModels/AppearanceViewModel.cs, src/Files.App/Views/SettingsPages/Appearance.xaml, src/Files.Backend/Services/Settings/IAppearanceSettingsService.cs
- Closes #9856...
**Validation**
=> Feature: Added support for hiding the edit tags menu

src/Files.App/Filesystem/NetworkDrivesAPI.cs, src/Files.App/Helpers/DynamicDialogFactory.cs, src/Files.App/Helpers/NavigationHelpers.cs, src/Files.App/Strings/en-US/Resources.resw, src/Files.App/ViewModels/ToolbarViewModel.cs
- Closes #258 
- Typing in the toolbar or navigating from the Network folder to a SMB share which does not have cached/saved credentials, will prompt the user for a username and password, and whether or not they want to save their credentials (Screenshot 1).
- Credentials are stored directly to Windows Credential Manager, not in the application (Screenshot 4). The application also does not need to read the saved credentials in order to access a network share.
- Win32Errors are outputted in a dialog in the event of an error (Screenshots 2,3).
**Validation**
1.
2.
3.
4.
=> Feature: Prompt for credentials when connecting smb

src/Files.App/DataModels/SidebarPinnedModel.cs, src/Files.App/Filesystem/RecentItems.cs, src/Files.App/ServicesImplementation/QuickAccessService.cs, src/Files.App/Shell/Win32Shell.cs, src/Files.App/UserControls/Widgets/QuickAccessWidget.xaml.cs, src/Files.Backend/Services/IQuickAccessService.cs, src/Files.Shared/ShellFileItem.cs
Fixes an issue where the recent folders widgets misbehaves when there are few pinned folder.
Current code works assuming the non-pinned items are the last 4 which is not always the case.
This PR looks instead at the "System.Home.IsPinned" property.
**Validation**
=> Fix: Fixed quick access widgets when there are few items

src/Files.App/App.xaml.cs, src/Files.App/Constants.cs, src/Files.App/Helpers/FilePropertiesHelpers.cs, src/Files.App/MainWindow.xaml.cs
- Fixes logo not showing in preview and stable builds
**Validation**
=> Fix: Fixed icon not showing in stable and preview builds

src/Files.App/Views/ColumnShellPage.xaml.cs, src/Files.App/Views/ModernShellPage.xaml.cs
- Closes `TODO` task
**Validation**
=> Feature: Added shortcut to open folders in terminal

src/Files.App/Files.App.csproj, src/Files.App/Filesystem/StorageHistory/Helpers/StorageHistoryHelpers.cs, src/Files.App/Filesystem/StorageHistory/StorageHistoryOperations.cs
- Closes #11174
**Details**
A confirmation dialog will appear when the undo operation is to delete items to prevent unexpected deletion.
**TODO**
**Validation**
=> Feature: Show confirmation dialog when the undo operation is to delete items.

src/Files.App/Filesystem/FilesystemOperations/Helpers/FilesystemHelpers.cs, src/Files.App/Helpers/RecycleBinHelpers.cs, src/Files.App/Views/ColumnShellPage.xaml.cs, src/Files.App/Views/ModernShellPage.xaml.cs
- Closes #11200
**Validation**
=> Fix: Fixed the dialog may not be shown when undoing to delete items

src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml
=> Feature: Removed background color from tags in the details layout

src/Files.App/Filesystem/FilesystemOperations/Helpers/FilesystemHelpers.cs, src/Files.App/Filesystem/FilesystemOperations/Helpers/IFilesystemHelpers.cs, src/Files.App/Filesystem/StorageHistory/StorageHistoryOperations.cs, src/Files.App/Helpers/NavigationHelpers.cs, src/Files.App/Helpers/RecycleBinHelpers.cs, src/Files.App/ServicesImplementation/Settings/FoldersSettingsService.cs, src/Files.App/Strings/en-US/Resources.resw, src/Files.App/ViewModels/SettingsViewModels/FoldersViewModel.cs, src/Files.App/Views/ColumnShellPage.xaml.cs, src/Files.App/Views/ModernShellPage.xaml.cs, src/Files.App/Views/SettingsPages/Folders.xaml, src/Files.Backend/Services/Settings/IFoldersSettingsService.cs, src/Files.Shared/Enums/DeleteConfirmationPolicy.cs
- Closes #11126 
**Validation**
**Details**
* The setting to show a delete confirmation dialog now has three choices: Always, Permanent deletion only, Never.
* When "Never" is selected, the dialog to confirm emptying the recycle bin will also not appear.
* To avoid errors when updating, the setting will be "Always" after updating regardless of the previous setting.
=> Feature: Added option to confirm permanent deletion only

src/Files.App/Filesystem/ListedItem.cs, src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml
=> Feature: Display multiple tags in the details layout

src/Files.App/Helpers/LayoutPreferences/LayoutPreferences.cs, src/Files.App/ServicesImplementation/Settings/FoldersSettingsService.cs, src/Files.App/ServicesImplementation/Settings/LayoutSettingsService.cs, src/Files.App/Strings/en-US/Resources.resw, src/Files.App/ViewModels/FolderSettingsViewModel.cs, src/Files.App/ViewModels/ItemViewModel.cs, src/Files.App/ViewModels/SettingsViewModels/FoldersViewModel.cs, src/Files.App/Views/SettingsPages/Folders.xaml, src/Files.Backend/Services/Settings/IFoldersSettingsService.cs, src/Files.Backend/Services/Settings/ILayoutSettingsService.cs
- Closes #11053 
**Validation**
=> Feature: Added settings for default order directions

src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml, src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs
- Closes #11219
**Validation**
=> Feature: Start a search when clicking tags in the details layout

src/Files.App/App.xaml.cs, src/Files.App/DataModels/NavigationControlItems/LocationItem.cs, src/Files.App/Filesystem/Search/FolderSearch.cs, src/Files.App/Helpers/CommonPaths.cs, src/Files.App/Helpers/MultitaskingTabsHelpers.cs, src/Files.App/Helpers/NavigationHelpers.cs, src/Files.App/UserControls/SidebarControl.xaml.cs, src/Files.App/ViewModels/ItemViewModel.cs, src/Files.App/ViewModels/MainPageViewModel.cs, src/Files.App/ViewModels/SettingsViewModels/PreferencesViewModel.cs, src/Files.App/ViewModels/SidebarViewModel.cs, src/Files.App/ViewModels/ToolbarViewModel.cs, src/Files.App/Views/ColumnShellPage.xaml.cs, src/Files.App/Views/MainPage.xaml.cs, src/Files.App/Views/ModernShellPage.xaml.cs, src/Files.App/Views/PaneHolderPage.xaml.cs, src/Files.App/Views/WidgetsPage.xaml.cs
- Closes #11203 
**Details**
The path to the home screen is now "Home" regardless of the language though the display name is still localized.
**Validation**
=> Fix: Fixed "NotAFolder" error when changing the language

src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs, src/Files.App/Views/LayoutModes/GridViewBrowser.xaml.cs
- Closes #11092
**Details**
`ItemContainer.Content` appears to refer to the old item before the item was created or renamed.
Because of this, checked and unchecked events select wrong items.
These events are for (un)selecting (un)checked items and are not needed in this logic, so I disabled these events temporarily.
Deleteing items also selects another item, but this appears to be the intended specification so it is left as is at this time.
(ItemViewModel.cs:1850)
**Validation**
=> Fix: Fixed selecting wrong items when creating or renaming an item

src/Files.App/BaseLayout.cs
- Closes #11244 
**Validation**
=> Fix: Fixed issue where BaseContextFlyout was not closed after selecting an item

src/Files.App/BaseLayout.cs
- Closes #11252
**Validation**
=> Fix: Fixed double separator showing up when opening context menu for files

builds/azure-pipelines.yml, src/Files.App/BaseLayout.cs, src/Files.App/Helpers/ContextFlyoutItemHelper.cs, src/Files.App/ServicesImplementation/Settings/AppearanceSettingsService.cs, src/Files.App/Strings/en-US/Resources.resw, src/Files.App/UserControls/SidebarControl.xaml.cs, src/Files.App/UserControls/Widgets/DrivesWidget.xaml.cs, src/Files.App/UserControls/Widgets/QuickAccessWidget.xaml.cs, src/Files.App/ViewModels/SettingsViewModels/AppearanceViewModel.cs, src/Files.App/Views/SettingsPages/Appearance.xaml, src/Files.Backend/Services/Settings/IAppearanceSettingsService.cs
- Added support for hiding option to open folders in new tab and window.
**Validation**
=> Feature: Added support for hiding open in new tab/window options

src/Files.App/BaseLayout.cs, src/Files.App/Helpers/ContextFlyoutItemHelper.cs, src/Files.App/Helpers/NavigationHelpers.cs, src/Files.App/Helpers/ShellContextMenuHelper.cs, src/Files.App/ServicesImplementation/Settings/AppearanceSettingsService.cs, src/Files.App/ServicesImplementation/Settings/PreferencesSettingsService.cs, src/Files.App/Strings/en-US/Resources.resw, src/Files.App/UserControls/SidebarControl.xaml.cs, src/Files.App/UserControls/Widgets/DrivesWidget.xaml.cs, src/Files.App/UserControls/Widgets/HomePageWidget.cs, src/Files.App/UserControls/Widgets/QuickAccessWidget.xaml.cs, src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml.cs, src/Files.App/ViewModels/SettingsViewModels/AppearanceViewModel.cs, src/Files.App/ViewModels/SettingsViewModels/PreferencesViewModel.cs, src/Files.App/ViewModels/Widgets/Bundles/BundleItemViewModel.cs, src/Files.App/Views/PaneHolderPage.xaml.cs, src/Files.App/Views/SettingsPages/Appearance.xaml, src/Files.App/Views/SettingsPages/Preferences.xaml, src/Files.App/Views/WidgetsPage.xaml.cs, src/Files.Backend/Services/Settings/IAppearanceSettingsService.cs, src/Files.Backend/Services/Settings/IPreferencesSettingsService.cs
- Moved context menu settings to preferences page
- Dual pane feature is always on
- Added setting to hide "open folders in new pane"
**Validation**
=> Feature: Moved context menu settings to preferences page

src/Files.App/App.xaml.cs, src/Files.App/BaseLayout.cs, src/Files.App/UserControls/SidebarControl.xaml.cs, src/Files.App/UserControls/Widgets/FileTagsWidget.xaml.cs, src/Files.App/UserControls/Widgets/HomePageWidget.cs, src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml.cs
- Closes #10110
**Details**
For some reason, the application does not close properly when a CommandBarFlyout is open, so the open flyout is forced to close before closing app, and then the application is closed as the event after closing the flyout.
**Validation**
=> Fix: Fixed closing app when the item flyout is open to hang

src/Files.App/App.xaml, src/Files.App/Dialogs/SettingsDialog.xaml
- Fixed settings background in dark mode
**Validation**
=> Fix: Fixed settings background in dark mode

src/Files.App/Helpers/NavigationHelpers.cs, src/Files.App/ViewModels/ItemViewModel.cs, src/Files.App/ViewModels/ToolbarViewModel.cs
- Solves the following [discussion](https://github.com/files-community/Files/pull/11144#discussion_r1096732737).
-  Move the call to AuthenticateNetworkShare() to ItemViewModel.cs.
- Remove logic added to ToolbarViewModel.cs & NavigationHelpers.cs
**Validation**
=> Fix: Refactor smb credentials dialog logic

src/Files.App/Helpers/FileOperationsHelpers.cs
- Closes #11318 
**Details**
Online-only files cannot be tried for deletion probably because of Vanara or Win32 API, so they are treated as to be permanently deleted.
**Validation**
=> Fix: Fixed issue where online-only files deleted before confirmation

src/Files.App/Views/LayoutModes/ColumnViewBase.xaml.cs, src/Files.App/Views/LayoutModes/ColumnViewBrowser.xaml.cs
- Closes #6902 
- Closes #7589
- Closes #11128
**Details**
* When a directory is opened in column view, any folder pinned to favorites starts from the directory and everything else from root.
* When the navigation button is clicked or the application relaunches to show column view, the last opened directory is displayed (not the last focused directory).
**Validation**
=> Feature: Improve Column View

src/Files.App/ViewModels/Properties/CompatibilityProperties.cs, src/Files.Shared/CompatibilityOptions.cs
- Closes #11317 
**Notes**
- `CompatibilityOptions.FromString(options)` will always return an object even when `options is null`
- Since `CompatibilityOptions` will always have a value, the user will be able to interact with the `Compatibility` tab
- Changes are saved correctly
**Validation**
=> Fix: Fixed issue where compatibility settings weren't working

src/Files.App/Filesystem/LibraryManager.cs, src/Files.App/Views/Pages/PropertiesLibrary.xaml, src/Files.App/Views/Pages/PropertiesLibrary.xaml.cs
- Closes #8253 
**Validation**
=> Fix: Fixed issue where it didn't work to change the library default directory

src/Files.App/Shell/ContextMenu.cs
- Closes #11342 
- Closes #10592 
- Closes #11104 
**Details**
Here is another possible solution. This way, if "Cast to Device" is not a problem, it can be displayed in the menu.
I can't reproduce the error, so I would like someone to check if applying this PR will stop the error from occurring.
**Validation**
=> Fix: Catch COMException when creating submenus to avoid errors

src/Files.App/Strings/en-US/Resources.resw, src/Files.App/Views/SettingsPages/Tags.xaml, src/Files.App/Views/SettingsPages/Tags.xaml.cs
- Closes #11292 
**Work in Progress**
**Validation**
=> Feature: Add flyout to confirm tag deletion

src/Files.App/ResourceDictionaries/DefaultGridSplitterStyle.xaml, src/Files.App/Views/MainPage.xaml, src/Files.App/Views/MainPage.xaml.cs
- Closes #8856...
**Validation**
=> Fix: Fixed issue where the preview pane had the wrong cursor when resizing

src/Files.App/Shell/ContextMenu.cs
- This is a follow-up to #11363 
**Details**
* COMException is now caught wherever it occurs in shell extension loading. In this case, the context menu will appear without the shell extension.
* `GetContextMenuForFolder()` has been removed as it does not seem to be called from anywhere.
**Validation**
=> Fix: Catch COMException wherever it occurs in shell extension loading

src/Files.App/ViewModels/ItemViewModel.cs
- Closes #11413 
**Details**
- Problem was introduced with #11193. 
- Paths that start with `\\?\` are USB devices, not network folders
**Validation**
=> Fix: Fixed network folder error with phones

src/Files.App/Actions/FileSystem/EmptyRecycleBinAction.cs, src/Files.App/Actions/IAction.cs, src/Files.App/Commands/CommandCodes.cs, src/Files.App/Commands/HotKey.cs, src/Files.App/Commands/IRichCommand.cs, src/Files.App/Commands/Manager/CommandManager.cs, src/Files.App/Commands/Manager/ICommandManager.cs, src/Files.App/Commands/RichGlyph.cs, src/Files.App/Helpers/ContextFlyoutItemHelper.cs, src/Files.App/Interacts/BaseLayoutCommandImplementationModel.cs, src/Files.App/Interacts/BaseLayoutCommandsViewModel.cs, src/Files.App/Interacts/IBaseLayoutCommandImplementationModel.cs, src/Files.App/Strings/en-US/Resources.resw, src/Files.App/UserControls/InnerNavigationToolbar.xaml, src/Files.App/UserControls/InnerNavigationToolbar.xaml.cs, src/Files.App/UserControls/SidebarControl.xaml.cs, src/Files.App/ViewModels/ContextMenuFlyoutItemViewModel.cs, src/Files.App/ViewModels/SidebarViewModel.cs, src/Files.App/ViewModels/ToolbarViewModel.cs, src/Files.App/Views/BaseShellPage.cs, src/Files.App/Views/MainPage.xaml, src/Files.App/Views/MainPage.xaml.cs, tests/Files.InteractionTests/Tests/FolderTests.cs
* Usage of glyphs in IAction. This simplifies the use of icons with the FontIcon and ColoredIcon properties of IRichCommand.
* Simplifies the creation of context menus. It is possible to pass a RichCommand to ContextMenuFlyoutItemViewModel to initialize it.
* Added RichCommand EmptyRecycleBin, which uses glyphs. This command is used everywhere, including the sidebar. Old commands are deleted. This new action does not yet use the IsExecutable property. This requires the context class and will be the subject of a future pr.
* A behavior has changed slightly. In the context menu of the RecycleBin page, the RecycleBin command is no longer active if the RecycleBin is empty. This seemed like a bug to me.
* A bug has been fixed in the parser of HotKey (not yet …
=> RichCommand: Glyph + ContextMenu + EmptyRecycleBinAction

src/Files.App/UserControls/Widgets/DrivesWidget.xaml.cs, src/Files.App/UserControls/Widgets/HomePageWidget.cs, src/Files.App/UserControls/Widgets/QuickAccessWidget.xaml.cs
- Closes #11432 
**Validation**
=> Fix: Fixed issue where the properties window opened from widgets was hidden behind

src/Files.App/Strings/en-US/Resources.resw
- Closes #11446 
**Details**
The string resources in the attached file seem unused, so I deleted them.
[unused.txt](https://github.com/files-community/Files/files/10824309/unused.txt)
I have manually checked that they are not used, but it may not be perfect so please review it.
**Validation**
The following is the condition that generated the unused string resources list.
=> Code Quality: Deleted unused string resources

src/Files.App/Actions/FileSystem/CreateFolderAction.cs, src/Files.App/Actions/FileSystem/CreateShortcutAction.cs, src/Files.App/Actions/FileSystem/CreateShortcutFromDialogAction.cs, src/Files.App/Actions/Start/PinToStartAction.cs, src/Files.App/Actions/Start/UnpinFromStartAction.cs, src/Files.App/Commands/CommandCodes.cs, src/Files.App/Commands/Manager/CommandManager.cs, src/Files.App/Commands/Manager/ICommandManager.cs, src/Files.App/Helpers/ContextFlyoutItemHelper.cs, src/Files.App/Interacts/BaseLayoutCommandImplementationModel.cs, src/Files.App/Interacts/BaseLayoutCommandsViewModel.cs, src/Files.App/Interacts/IBaseLayoutCommandImplementationModel.cs
- Related to #11481 (I'm trying to do these in little chunks to make them easier to review)
**Validation**
=> Feature: Implement more RichCommands

src/Files.App/Helpers/FilePropertiesHelpers.cs, src/Files.App/Views/Properties/MainPropertiesPage.xaml.cs, src/Files.App/Views/Properties/SecurityAdvancedPage.xaml.cs, src/Files.App/Views/Properties/SecurityPage.xaml.cs
- Closes #11461 
**Validation**
=> Fix: Fixed highlights flickering after closing the properties window

src/Files.App/Commands/IRichCommand.cs, src/Files.App/Commands/Manager/CommandManager.cs, src/Files.App/Commands/RichGlyph.cs, src/Files.App/UserControls/InnerNavigationToolbar.xaml
Add Icon property to IRichCommand. The view no longer needs to know if it's a fontIcon or opacityIcon to display an icon as content.
**Validation**
=> Feature: Added icon property to RichCommand

src/Files.App/Helpers/ContextFlyoutItemHelper.cs
Creating a shortcut to a deleted item is useless. This pr removes the command in the Recycle Bin.
**Validation**
=> Fix: Fixed issue where create shortcut was visible in recycle bin

src/Files.App/ViewModels/Properties/CustomizationViewModel.cs
- Closes #11542
**Details**
* When selecting a file, only icons of that file appears in the list like Explorer, rather than adding icons to the icon list.
* Avoid crash when the selected file has no icons.
**Validation**
=> Fix: Fixed loading icons in Properties Customize page

src/Files.App/Dialogs/FilesystemOperationDialog.xaml, src/Files.App/Dialogs/FilesystemOperationDialog.xaml.cs, src/Files.Backend/ViewModels/Dialogs/FileSystemDialog/FileSystemDialogViewModel.cs
- Related to #11399 
**Details**
In #11399, I used `Visibility` instead of `x:Load` because the initial value of the combo box could not be set correctly.
But I found a way to set the initial value correctly for `x:Load`, so I changed `Visibility` back to `x:Load`.
**Validation**
=> Fix: Use x:Load in conflicts dialog again

src/Files.App/Commands/IRichCommand.cs, src/Files.App/Commands/Manager/CommandManager.cs, src/Files.App/Commands/RichGlyph.cs, src/Files.App/UserControls/InnerNavigationToolbar.xaml
Fixes #11540.
XAML treats bindings of a Content attribute badly. We have to pass the content as a tag. This pr adds IRichCommand.OpacityStyle. This allows to display the icon without knowing the style used. The downside is that you have to know if it's a fonticon or opacityicon. The advantage is to be able to change the size (this will be used for the layout icons). This solution is acceptable because the icon will rarely change, and never by the user. Additionally, FontIcon may be phased out in favor of the more generic OpacityStyle.
I also removed IsEnabled properties to IsExecutable. By default, the command already notifies its state using IsExecutable, and XAML reacts to it.
**Validation**
=> Fix: Fixed OpacityIcon visibility

src/Files.App/Views/ColumnShellPage.xaml, src/Files.App/Views/ColumnShellPage.xaml.cs, src/Files.App/Views/ModernShellPage.xaml, src/Files.App/Views/ModernShellPage.xaml.cs
Views still have code to perform SelectAll with the shortcut Ctrl+A. This pr removes this code because the SelectAll action triggers this hotkey. This avoids a bug if we change the hotkey of the action or the action of the hotkey.
**Validation**
=> Fix: Fixed SelectAll HotKey

src/Files.App/UserControls/Widgets/FileTagsWidget.xaml.cs
- Closes #11599 
**Validation**
=> Fix: Fixed Tags Widget Context Menu Uses Wrong Strings

src/Files.App/UserControls/InnerNavigationToolbar.xaml
- Related to #11588 
**Details**
In #11588, `IsEnabled` properties were removed in favor of `IsExecutable`. However, without `IsEnabled`, `IsExecutable` is not evaluated on initialization and icons are shown as 'Enabled', so Cut, Copy and Delete still need `IsEnabled` property.
I missed this behavior when I tested #11588. Sorry.
**Validation**
=> Fix: Fixed issue where toolbar icons were mistakenly enabled on startup

src/Files.App/UserControls/OpacityIcon.xaml, src/Files.App/UserControls/OpacityIcon.xaml.cs
The state of OpacityIcon is updated whenever its parent control's IsEnabled changes. But it is not initialized. It can therefore be active when its control is not.
This is the case when starting the application on the homepage. The Cut, Copy and Delete toolbar icons are shown as active while the button is inactive.
This pr updates the state of OpacityIcon when loaded. Fixes #11605.
This pr is not the same as #11539, which fixes the button. This pr fixes the icon.
**Validation**
=> Fix: Fixed OpacityIcon state

src/Files.App/Actions/Content/ImageEdition/RotateLeftAction.cs, src/Files.App/Actions/Content/ImageEdition/RotateRightAction.cs, src/Files.App/Commands/CommandCodes.cs, src/Files.App/Commands/Manager/CommandManager.cs, src/Files.App/Commands/Manager/ICommandManager.cs, src/Files.App/Helpers/ContextFlyoutItemHelper.cs, src/Files.App/Interacts/BaseLayoutCommandImplementationModel.cs, src/Files.App/Interacts/BaseLayoutCommandsViewModel.cs, src/Files.App/Interacts/IBaseLayoutCommandImplementationModel.cs, src/Files.App/UserControls/InnerNavigationToolbar.xaml, src/Files.App/Views/BaseShellPage.cs
- Related to #11481
**Validation**
=> Rich Commands: Rotate image as Rich Commands

src/Files.App/Helpers/ContextFlyoutItemHelper.cs
- Forgotten null refs checks would prevent the flyout menu to be correctly generated.
**Validation**
=> Fix: Add forgotten null ref checks for image rotations on flyout menu

src/Files.App/Commands/HotKey.cs, src/Files.App/Views/MainPage.xaml.cs
This method allows more keys to be used for keyboard shortcuts. Native textbox hotkeys are ignored.
**Validation**
=> Use KeyDown instead of KeyboardAccelerator for command's hotkeys.

src/Files.App/Shell/ShellNewMenuHelper.cs
In the New menu (toolbar or context menu), les items are not sorted. For example, different Office documents do not appear together. This pr sorts them alphabetically.
**Validation**
=> Alphabetical sorting of template files in the New menu.

src/Files.App/Actions/Content/ImageEdition/RotateLeftAction.cs, src/Files.App/Actions/Content/ImageEdition/RotateRightAction.cs
I had exceptions in these classes to use ShellPage when it is null. Here is a fix.
I improved readability and used distinct to avoid dealing with the same extension multiple times.
**Validation**
=> Fix: Fixed null error in RotateLeft/Right

src/Files.App/Actions/IAction.cs, src/Files.App/Commands/IRichCommand.cs, src/Files.App/Commands/Manager/CommandManager.cs, src/Files.App/Commands/Manager/ICommandManager.cs, src/Files.App/ViewModels/ContextMenuFlyoutItemViewModelBuilder.cs
This pr allows to use several hotkeys for the same action. Added SecondHotKey and MediaHotKey in addition to HotKey. They are optional.
If SecondHotKey is set, it also displays in menus (eg: Ctrl+T,Ctrl-Shit+B.
If MediaHotkey is set, it does not display. This allows to assign the optional media keys of some keyboards (GoBack, GoHome, ...).
The code to modify the HotKeys, which was not yet used, has been removed. It had been designed for a single hotkey per command. A multikey version will come later.
**Validation**
=> RichCommand: Added support for multiple hot keys

src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs, src/Files.App/Views/LayoutModes/GridViewBrowser.xaml.cs
Fixes renaming not working anymore with double click.
**Validation**
=> Fix: Fixed double tap to rename
