src/Files.App/Files.App.csproj
src/Files.Backend/Files.Backend.csproj
src/Files.FullTrust/Files.FullTrust.csproj

Added PublishReadyToRun
Do they need to be added to other PropertyGroups or is it good as is?

Feature: ReadyToRun

---

src/Files.App/Filesystem/RecentItemsManager.cs
src/Files.App/Helpers/CommonPaths.cs
src/Files.App/Helpers/NavigationHelpers.cs
src/Files.App/Program.cs
src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml.cs
src/Files.App/ViewModels/ItemViewModel.cs
src/Files.FullTrust/MessageHandlers/RecentItemsHandler.cs
src/Files.Package/Package.appxmanifest

Partially remove recent items handler

---

README.md

- Closes #9962 
**Validation**
[Add screenshots here.](https://i.imgur.com/aLmAaKD.png)

FIXED: Files Logo path in README.md

---

src/Files.App/UserControls/SidebarControl.xaml.cs
src/Files.App/UserControls/Widgets/DrivesWidget.xaml
src/Files.App/UserControls/Widgets/DrivesWidget.xaml.cs
src/Files.App/UserControls/Widgets/FolderWidget.xaml
src/Files.App/UserControls/Widgets/FolderWidget.xaml.cs

- No issue, just code preference
**Changes**
- Small edit to code added in #9973 to remove the need for a temporary variable and to make code more uniform & "self-contained". No changes expected in functionality.
**Validation**

Remove temp variable in code of #9973

---

src/Files.App/Filesystem/RecentItemsManager.cs

Run ListRecentFolders() in background

---

src/Files.App/App.xaml

- Added list/grid view styles to app.xaml
**Validation**

Fix: Fixed issue where ListView had the Win10 style

---

src/Files.App/App.xaml.cs
src/Files.App/DataModels/TerminalFileModel.cs
src/Files.App/Helpers/ExternalResourcesHelper.cs
src/Files.App/ServicesImplementation/DateTimeFormatter/DateTimeFormatterFactory.cs
src/Files.App/ServicesImplementation/DateTimeFormatter/UserDateTimeFormatter.cs
src/Files.App/ServicesImplementation/Settings/AppSettingsService.cs
src/Files.App/ServicesImplementation/Settings/PreferencesSettingsService.cs
src/Files.App/ServicesImplementation/Settings/UserSettingsService.cs
src/Files.App/UserControls/AddressToolbar.xaml
src/Files.App/UserControls/AddressToolbar.xaml.cs
src/Files.App/UserControls/MultitaskingControl/HorizontalMultitaskingControl.xaml.cs
src/Files.App/UserControls/RestartControl.xaml.cs
src/Files.App/ViewModels/MainPageViewModel.cs
src/Files.App/ViewModels/SettingsViewModel.cs
src/Files.App/ViewModels/SettingsViewModels/AppearanceViewModel.cs
src/Files.App/ViewModels/SettingsViewModels/PreferencesViewModel.cs
src/Files.App/ViewModels/SidebarViewModel.cs
src/Files.App/Views/MainPage.xaml
src/Files.App/Views/MainPage.xaml.cs
src/Files.App/Views/SettingsPages/Preferences.xaml
src/Files.Backend/Services/Settings/IAppSettingsService.cs
src/Files.Backend/Services/Settings/IPreferencesSettingsService.cs
src/Files.Backend/Services/Settings/IUserSettingsService.cs
src/Files.Shared/Enums/DateTimeFormats.cs
src/Files.Shared/Services/DateTimeFormatter/IDateTimeFormatterFactory.cs

- Made some improvements to the codebase
- Added AppSettingsService to keep track of app settings that don't belong in the regular setting services
- Fixed an issue where the title bar had the wrong drag region when the flow direction was RTL
**Validation**

Feature: Minor improvements and refactoring

---

src/Files.App/ViewModels/ItemViewModel.cs
src/Files.App/ViewModels/SettingsViewModels/PreferencesViewModel.cs

Auto refresh directory when setting changes.
**Validation**

Fix: Apply select files on hover setting without restarting app

---

src/Files.App/Files.App.csproj
src/Files.Backend/Files.Backend.csproj
src/Files.FullTrust/Files.FullTrust.csproj

Removed ready 2 run
**Validation**

Removed Ready2Run

---

src/Files.App/ViewModels/ItemViewModel.cs

Originally opened this PR to see if we could still use DocumentsView for non-images but it seemed to break thumbnails for Powerpoint and Word documents, so I reverted the changes and just made some general code improvements.
**Validation**

Fix: Improved thumbnail code

---

src/Files.App/ViewModels/ItemViewModel.cs

Fix: Fixed wasIconLoaded

---

src/Files.App/Files.App.csproj

Updated WinAppSdk to 1.2.220909.2-experimental2
**Validation**

Feature: Updated WinAppSdk to 1.2.220909.2-experimental2

---

src/Files.App/UserControls/AddressToolbar.xaml
src/Files.App/UserControls/SidebarControl.xaml

Fix: Fixed search box visual states

---

.github/CONTRIBUTING.md

Updated CONTRIBUTING.md to account for new project planning board

---

src/Files.App/ViewModels/ItemViewModel.cs

- Closes #10067...
**Before**:
**After**:
**File Explorer**
**Validation**

Fix: Improve sharpness of thumbnail previews

---

src/Files.App/Constants.cs
src/Files.App/DataModels/SidebarPinnedModel.cs
src/Files.App/Filesystem/RecentItem.cs
src/Files.App/Helpers/FileThumbnailHelper.cs
src/Files.App/Shell/ShellNewMenuHelper.cs
src/Files.App/UserControls/SidebarControl.xaml
src/Files.App/UserControls/Widgets/DrivesWidget.xaml.cs
src/Files.App/UserControls/Widgets/FolderWidget.xaml.cs
src/Files.App/UserControls/Widgets/IWidgetCardItem.cs
src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml
src/Files.App/ViewModels/ItemViewModel.cs
src/Files.App/Views/LayoutModes/GridViewBrowser.xaml.cs

**Before**
**After**
**Validation**

Feature: Improved thumbnail quality on the widgets screen

---

src/Files.App/Constants.cs
src/Files.App/DataModels/SidebarPinnedModel.cs
src/Files.App/Filesystem/RecentItem.cs
src/Files.App/Shell/ShellNewMenuHelper.cs
src/Files.App/UserControls/SidebarControl.xaml
src/Files.App/UserControls/Widgets/DrivesWidget.xaml.cs
src/Files.App/UserControls/Widgets/FolderWidget.xaml.cs
src/Files.App/UserControls/Widgets/IWidgetCardItem.cs
src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml
src/Files.App/ViewModels/ItemViewModel.cs
src/Files.App/Views/LayoutModes/GridViewBrowser.xaml.cs

Fix: Cleaned up thumbnail tweaks

---

src/Files.App/Constants.cs
src/Files.App/Filesystem/WSLDistroManager.cs
src/Files.App/ViewModels/MainPageViewModel.cs
src/Files.App/ViewModels/SidebarViewModel.cs

- Closes #10102 
**Validation**

Code quality: Reduced duplicate code for the sidebar

---

src/Files.App/ServicesImplementation/SideloadUpdateService.cs

- Fixes issue of not finding the downloaded bundle.
**Validation**

Fix: UpdateService Bundle Path

---

src/Files.App/Views/LayoutModes/ColumnViewBase.xaml.cs
src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs
src/Files.App/Views/LayoutModes/GridViewBrowser.xaml.cs

- Closes #10120
**Validation**

Fix: Fixed an issue where renaming a file would crash the app

---

src/Files.App/Files.App.csproj

Updated to WinAppSdk 1.2.220930.4-preview2
**Validation**

Nuget: WinAppSdk 1.2.220930.4-preview2

---

src/Files.App/Helpers/AdaptiveLayoutHelpers.cs
src/Files.App/Helpers/LayoutPreferences/LayoutPreferences.cs
src/Files.App/ServicesImplementation/Settings/FoldersSettingsService.cs

- Fix adaptive layout mode prediction not working
**Validation**

Fix: Fixed issue with adaptive layout

---

src/Files.App/Helpers/ExternalResourcesHelper.cs

Feature: Made compact mode even more compact

---

src/Files.App/DataModels/SidebarPinnedModel.cs

- Closes #9678...
**Validation**

Fix: Fixed issue where sidebar icons were blurry

---

src/Files.App/ServicesImplementation/Settings/FoldersSettingsService.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/ViewModels/SettingsViewModels/FoldersViewModel.cs
src/Files.App/Views/LayoutModes/ColumnViewBase.xaml.cs
src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs
src/Files.App/Views/LayoutModes/GridViewBrowser.xaml.cs
src/Files.App/Views/SettingsPages/Folders.xaml
src/Files.Backend/Services/Settings/IFoldersSettingsService.cs

- Merged option to open "files with a single click" with the option to "open folders with a single click"
**Validation**

Feature: Merged similar settings into "Open items with a single click"

---

src/Files.App/ViewModels/Properties/FolderProperties.cs
src/Files.App/ViewModels/SelectedItemsPropertiesViewModel.cs
src/Files.App/Views/Pages/PropertiesGeneral.xaml

Refactoring that replaces the word Visibiity with Visibility.
**Validation**

Code: Fixed typo

---

src/Files.App/Views/ModernShellPage.xaml.cs

- Closes #10217 
**Validation**

Fix: Fixed issue where untagged files were sometimes displayed in the search results

---

.github/ISSUE_TEMPLATE/code_quality_issue.yml

Fix: Changed label on code quality issue template to correct one

---

README.md

Fix: wrong logo path in README

---

builds/azure-pipelines-release.yml
src/Files.App (Package)/Package.appxmanifest

Feature: Added back ARM64 build

---

src/Files.App/Views/LayoutModes/ColumnViewBase.xaml.cs
src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs
src/Files.App/Views/LayoutModes/GridViewBrowser.xaml.cs

- Closes #10344 
**Validation**

Fix: Fixed issue where double tap to rename was no longer working

---

src/Files.App/Helpers/RecycleBinHelpers.cs
src/Files.App/Strings/en-US/Resources.resw

- Closes #8215
I'm not sure about titles and messages
**Validation**

Fix: Fixed issue where emptying recycle bin wouldn't display the operation in the status center

---

src/Files.App/ViewModels/ItemViewModel.cs

- Closes #10357
Restore null check on CurrentFolder. CurrentFolder is null when on homepage.
**Validation**

Fixed crash that would occur when emptying recycle bin from the sidebar

---

src/Files.App/Helpers/WallpaperHelpers.cs

- Closes #10255
**Validation**

Fix: Fixed issue where setting image as wallpaper would add image to the local state folder

---

src/Files.App/ServicesImplementation/Settings/FoldersSettingsService.cs

- Closes #6252
This PR reduces the default width of the type, size and tag columns and increases the width of the name column.
**Validation**

Feature: Improved default width of columns in details layout

---

src/Files.App/App.xaml.cs
src/Files.App/Helpers/FileOperationsHelpers.cs

- Closes #10383 
- Moved back the `WaitForCompletion()` method inside `EnsureSettingsAndConfigurationAreBootstrapped()`.
**Validation**

Fix: Resolving soft-lock issue in operations.

---

src/Files.App/Filesystem/BaseStorage/BaseStorageFile.cs

- Closes #10382
There was a mistake in how we read a string from a text file. Additional "\0" characters were added at the end.
**Validation**

Fixed issue where it wasn't working to import settings

---

src/Files.App/Filesystem/ListedItem.cs
src/Files.App/Filesystem/StorageEnumerators/Win32StorageEnumerator.cs
src/Files.App/Filesystem/StorageItems/FtpStorageFolder.cs
src/Files.App/Filesystem/StorageItems/ZipStorageFolder.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/ViewModels/ItemViewModel.cs
src/Files.App/Views/MainPage.xaml.cs

- Closes #5853 
**Validation**

Feature: Replaced 'File Folder' by 'Folder' use

---

src/Files.App/Filesystem/ListedItem.cs

- Closes #6622 
**Validation**

Feature: Add sync status to tooltip

---

src/Files.App/Filesystem/FilesystemOperations/ShellFilesystemOperations.cs

Fix: Fixed issue where ongoing tasks icon would show file transfers as complete when the operation failed

---

src/Files.App/UserControls/AddressToolbar.xaml
src/Files.App/UserControls/AddressToolbar.xaml.cs
src/Files.App/ViewModels/SearchBoxViewModel.cs
src/Files.App/ViewModels/ToolbarViewModel.cs

- Closes #9440 
**Validation**

Feature: Cancel search when pressing esc key

---

src/Files.App (Package)/Files.Package.wapproj
src/Files.App/Files.App.csproj
src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs
src/Files.OpenDialog/FilesLauncher/FilesLauncher.vcxproj
src/Files.OpenDialog/FilesLauncher/packages.config

Feature: WindowsAppSDK 1.2 and fix crashing issue 

---

src/Files.App/Filesystem/Search/FolderSearch.cs

- Closes #10502
**Validation**

Fix: Fixed an issue where TagDb gets disposed early

---

src/Files.App/Shell/ContextMenu.cs
src/Files.App/Shell/LaunchHelper.cs

- Closes #10423
Shell COM objects are not happy when passed between threads.
**Validation**

Fix: Fixed crash that would occur when opening multiple files at once

---

.github/FUNDING.yml

- Fixes #10589
I presume Files is pulling the link from this file to use with the sponsor button in about page.
**Validation**

Fix: Fixed sponsor link

---

src/Files.App/Helpers/ExternalResourcesHelper.cs

- Closes #10586
Reload resources when applying theme, like we do everywhere else.
Simple fix, can be put in while #10342 is being worked on.
**Validation**

Fix: Theme is not applied on launch

---

builds/azure-pipelines.yml

Fix: Fixed automation tests

---

src/Files.App/Constants.cs

- Related #10589
The link is hardcoded and not pulled from the sponsors.yml as assumed in #10590
**Validation**

Fix: Fixed sponsors link

---

src/Files.App/Filesystem/StorageItems/ShellStorageFile.cs
src/Files.App/Filesystem/StorageItems/ShellStorageFolder.cs

- Closes #9562
**Validation**
**Changes**
- case is now ignored for Recycle.Bin
before the changes
after the changes

Fix: Fixed issue where original date and path was missing from Recycle Bin

---

src/Files.App/Properties/PublishProfiles/win10-arm64.pubxml
src/Files.App/Properties/PublishProfiles/win10-x64.pubxml
src/Files.App/Properties/PublishProfiles/win10-x86.pubxml

Test: Remove self contained dependency for WASDK

---

src/Files.App/MainWindow.xaml
src/Files.App/UserControls/FilePreviews/MediaPreview.xaml

Feature: Updated MediaPreview to WinUI control

---

builds/azure-pipelines.yml

Pipeline: Switch to release config

---

src/Files.App/App.xaml
src/Files.App/Files.App.csproj
src/Files.App/MainWindow.xaml
src/Files.App/Themes/Bound to be Blue.xaml
src/Files.App/Themes/Bronze.xaml
src/Files.App/Themes/Burgundy.xaml
src/Files.App/Themes/Deep Sea.xaml
src/Files.App/Themes/Discord.xaml
src/Files.App/Themes/Dracula.xaml
src/Files.App/Themes/Green Grass.xaml
src/Files.App/Themes/Lavender.xaml
src/Files.App/Themes/Leaf Green.xaml
src/Files.App/Themes/Luxury Red.xaml
src/Files.App/Themes/Magentistic.xaml
src/Files.App/Themes/Middle Blue.xaml
src/Files.App/Themes/Nightshade.xaml
src/Files.App/Themes/Nord.xaml
src/Files.App/Themes/Red Wave.xaml
src/Files.App/Themes/Solarized.xaml
src/Files.App/Themes/Turquoise.xaml

Feature: Mica Alt

---

src/Files.App/Helpers/FilePropertiesHelpers.cs
src/Files.App/Views/Pages/PropertiesSecurity.xaml.cs

Fixed issue with mica backdrop in dark mode in the properties window
**Validation**

Fix: Fixed mica in properties window

---

src/Files.App/Themes/Bound to be Blue.xaml
src/Files.App/Themes/Bronze.xaml
src/Files.App/Themes/Burgundy.xaml
src/Files.App/Themes/Deep Sea.xaml
src/Files.App/Themes/Discord.xaml
src/Files.App/Themes/Dracula.xaml
src/Files.App/Themes/Green Grass.xaml
src/Files.App/Themes/Lavender.xaml
src/Files.App/Themes/Leaf Green.xaml
src/Files.App/Themes/Luxury Red.xaml
src/Files.App/Themes/Magentistic.xaml
src/Files.App/Themes/Middle Blue.xaml
src/Files.App/Themes/Nightshade.xaml
src/Files.App/Themes/Nord.xaml
src/Files.App/Themes/Red Wave.xaml
src/Files.App/Themes/Solarized.xaml
src/Files.App/Themes/Turquoise.xaml

Fixed issue where custom themes weren't displaying correctly in dark mode
**Validation**

Fix: Fixed themes

---

src/Files.App/Filesystem/Archive/ArchiveCreator.cs

- Closes #10609
**Validation**

Fix: Fixed error when compressing a single folder

---

src/Files.App/Filesystem/BaseStorage/BaseStorageFile.cs

- Closes #10622
**Validation**

Fix: Fixed issue where previewing css files caused app to crash

---

src/Files.App/Themes/Nord.xaml

Fix: Fixed colors in the Nord theme

---

src/Files.App (Package)/Package.appxmanifest

Bumped version number to v2.4
**Validation**

Release: v2.4

---

.github/ISSUE_TEMPLATE/bug_report.yml

Removed debug_fulltrust log from placeholder text and updated Files and Windows version placeholders

Updated bug report template

---

src/Files.App/Views/MainPage.xaml.cs

- Fixed issue where the prompt to review would crash the app [636092730u](https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/636092730u/overview)
**Validation**

Fix: Fixed issue where the prompt to review would crash the app

---

src/Files.App/Helpers/NavigationHelpers.cs

- [4254053855u](https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/4254053855u/overview)
**Validation**

Fix: Fixed crash with BundlesViewModel_OpenPathEvent

---

src/Files.App (Package)/Package.appxmanifest

Release: v2.4.1

---

src/Files.App (Package)/Files.Package.wapproj
src/Files.App/Files.App.csproj

- Updated WinAppSdk to 1.2.221209.1
**Validation**

Feature: Updated WinAppSdk to 1.2.221209.1

---

src/Files.App (Package)/Package.appxmanifest

- v2.4.2 release
**Validation**

Release: v2.4.2

---

.github/FUNDING.yml

Added Josh-65 to sponsor page

---

src/Files.App/ServicesImplementation/UpdateService.cs

- Fixes issue with store versions crashing when trying to show store update dialog window.
**Validation**

Fix: Fixed crash that would occur when updating from the store

---

src/Files.App/Constants.cs
src/Files.App/UserControls/Pane/PreviewPane.xaml

- Removed duplicate title from preview pane
**Validation**

Fix: Fixed an issue where the title was displayed twice in the preview pane

---

src/Files.App/Helpers/CloudDrivesDetector.cs
src/Files.Shared/Cloud/CloudProviders.cs

- Closes #10797
Same concept as google drive.
**Validation**

Feature: Add pCloud to the cloud drive section

---

src/Files.App (Package)/Package.appxmanifest

Release v2.4.8

---

src/Files.App/Helpers/CloudDrivesDetector.cs
src/Files.Shared/Cloud/CloudProviders.cs

- Closes #10835
**Validation**

Feature: Added support for Creative Cloud

---

src/Files.App/Filesystem/ListedItem.cs
src/Files.App/Helpers/ContextFlyoutItemHelper.cs
src/Files.App/Helpers/FileExtensionHelpers.cs
src/Files.App/Helpers/ShellContextMenuHelper.cs
src/Files.App/Program.cs
src/Files.App/Shell/LaunchHelper.cs
src/Files.App/ViewModels/Properties/FileProperties.cs
src/Files.App/Views/Pages/Properties.xaml.cs

- Closes #10831
**Validation**

Code quality: Use FileExtensionHelpers more widely

---

src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml.cs

- Closes part of #10820
**Validation**

Fix: Fixed issue where the wrong recent item was being removed

---

src/Files.App (Package)/Package.appxmanifest
src/Files.App/ServicesImplementation/Settings/AppearanceSettingsService.cs
src/Files.App/ViewModels/SettingsViewModels/AppearanceViewModel.cs
src/Files.App/Views/MainPage.xaml.cs
src/Files.Backend/Services/Settings/IAppearanceSettingsService.cs

Feature: Switched color customization to strings

---

src/Files.App/Shell/ShellNewMenuHelper.cs

- Fixes an crash that occours when parsing some new menu items
**Validation**

Fix: Fixed exception when parsing new menu items

---

src/Files.App/Views/SettingsPages/Preferences.xaml

- Closes #10794 
**Validation**

Fix: Fixed issue where it didn't work to edit/remove startup page

---

src/Files.App/Filesystem/FilesystemOperations/FileSystemProgress.cs
src/Files.App/Filesystem/FilesystemOperations/ShellFilesystemOperations.cs

Fix: Minor progress leftovers

---

src/Files.App/UserControls/MultitaskingControl/HorizontalMultitaskingControl.xaml

Feature: Added progress indicator when loading tabs

---

src/Files.App/ViewModels/MainPageViewModel.cs

- Closes #10859
**Validation**

Feature: Show drive name on tab header

---

src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml
src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs

- Merge after #10936
**Validation**

Fix: Resolve issue with column resizing

---

src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml
src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs

- Switched to StackPanel in the Details Layout template for better performance
**Issues**
These changes broke support for double clicking the grid splitter to resize the columns. This should be resolved before merging.
**Validation**

Feature: Switched to StackPanel in the Details Layout template

---

builds/azure-pipelines-release.yml
src/Files.App (Package)/Package.appxmanifest

Pipeline: Always use release icon for store build

---

builds/azure-pipelines-release.yml
src/Files.App (Package)/Package.appxmanifest

Fix: Fixed icons

---

src/Files.App/Views/SettingsPages/Folders.xaml

Fix: Fixed header in folder options

---

src/Files.App/UserControls/AddressToolbar.xaml
src/Files.App/ViewModels/ToolbarViewModel.cs

- Added placeholder for viewing release notes
**Validation**

Feature: Added placeholder for viewing release notes

---

src/Files.App/Views/LayoutModes/GridViewBrowser.xaml

Feature: Wrap file names in the grid layout

---

src/Files.App (Package)/Package.appxmanifest

Release: v2.4.20

---

LICENSE

Changed the copyright year from 2022 to 2023.

License: Updated the Copyright year in LICENSE.md

---

src/Files.App (Package)/Package.appxmanifest

Release: v2.4.24

---

src/Files.App/Views/SettingsPages/About.xaml

- Closes #11057...
**Validation**

Fix: Fixed issue where submit feature request linked to wrong location

---

src/Files.App/Helpers/DynamicDialogFactory.cs

- Closes #11059 
- Properly registering the additional data in the dynamic dialog factory.
**Validation**

Fix: Naming an item at its creation properly sets the name

---

src/Files.App (Package)/Package.appxmanifest
src/Files.App/UserControls/AddressToolbar.xaml

- Closes #11056...
**Validation**

Fix: Fixed issue where release notes were cut off

---

.github/ISSUE_TEMPLATE/bug_report.yml

- Hopefuly resolves the issue where users upload the text instead of attaching the log file in bug reports.
**Validation**

Updated bug request template

---

src/Files.App (Package)/Files.Package.wapproj
src/Files.App/Files.App.csproj

Feature: Updated WinAppSdk 1.2.230118.102

---

src/Files.App/Strings/en-US/Resources.resw

- Closes #11115 
**Validation**

Fix: Fixed GitHub repository typo

---

src/Files.App/ServicesImplementation/Settings/FileTagsSettingsService.cs
src/Files.Backend/ViewModels/FileTags/TagViewModel.cs

- Fixed an issue where each install generated random guids for the default tags
**Validation**

Fix: Fixed issue where default tags had random uids

---

src/Files.App/ServicesImplementation/Settings/LayoutSettingsService.cs

- Closes #11072...
**Validation**

Feature: Changed default grid view size to medium

---

src/Files.App/ServicesImplementation/QuickAccessService.cs

- Closes #11139 
**Validation**

Fix: Fixed crash that would sometimes occur when pinning folders to the sidebar

---

src/Files.App/Strings/en-US/Resources.resw

- Fixes a typo in Resources.resw
**Validation**

Fix: Fixed typo in resources.resw

---

src/Files.App/Helpers/CloudDrivesDetector.cs
src/Files.Shared/Cloud/CloudProviders.cs

- Closes #11147
**Validation**

Feature: Add support for Autodesk drive

---

src/Files.App/ViewModels/Properties/FileProperties.cs

- Closes #11164 
**Validation**

Fix: Fixed app crash when opening details tab in file properties

---

src/Files.App/Strings/en-US/Resources.resw

Feature: Rename recent files

---

src/Files.App (Package)/Package.appxmanifest

Release: 2.4.30

---

src/Files.App (Package)/Package.appxmanifest

Release: 2.4.31

---

src/Files.App/Filesystem/QuickAccessManager.cs
src/Files.App/ServicesImplementation/QuickAccessService.cs

- Closes #11184 
**Validation**

Fix: Fixed issue where it didn't work to unpin Recycle Bin from sidebar

---

src/Files.App/Strings/en-US/Resources.resw
src/Files.App/UserControls/Widgets/BundlesWidget.xaml.cs
src/Files.App/UserControls/Widgets/DrivesWidget.xaml
src/Files.App/UserControls/Widgets/DrivesWidget.xaml.cs
src/Files.App/UserControls/Widgets/FileTagsWidget.xaml.cs
src/Files.App/UserControls/Widgets/QuickAccessWidget.xaml.cs
src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml.cs
src/Files.App/UserControls/Widgets/WidgetsListControl.xaml
src/Files.App/ViewModels/Widgets/IWidgetItemModel.cs
src/Files.App/ViewModels/Widgets/WidgetsListControlItemViewModel.cs

- Closes #7287...
**Validation**

Feature: Add menu flyout to widget header

---

src/Files.App/Strings/en-US/Resources.resw
src/Files.App/ViewModels/SettingsViewModels/AboutViewModel.cs
src/Files.App/Views/SettingsPages/About.xaml

Feature: Added menu flyout for copying version information

---

src/Files.App/Strings/en-US/Resources.resw
src/Files.App/UserControls/AddressToolbar.xaml
src/Files.App/UserControls/OngoingTasksFlyout.xaml
src/Files.App/UserControls/Widgets/DrivesWidget.xaml
src/Files.App/UserControls/Widgets/QuickAccessWidget.xaml
src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml
src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml.cs
src/Files.App/ViewModels/StatusCenterViewModel.cs
src/Files.App/Views/SettingsPages/About.xaml
src/Files.App/Views/SettingsPages/Appearance.xaml
src/Files.App/Views/SettingsPages/Preferences.xaml

Feature: Xaml cleanup

---

src/Files.App/ViewModels/ColumnsViewModel.cs
src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml

- Closes #11025 
**Validation**

Fixed: DetailsLayout Margin/Padding is not set correctly

---

src/Files.App/Helpers/ItemListDisplayHelpers/GroupingHelper.cs
src/Files.App/ViewModels/ItemViewModel.cs

- Closes #11221 
**Validation**

Fix: Fixed issue where archive files were incorrectly grouped by size

---

src/Files.App/Interacts/BaseLayoutCommandImplementationModel.cs
src/Files.App/ServicesImplementation/Settings/ApplicationSettingsService.cs
src/Files.App/Views/MainPage.xaml.cs
src/Files.Backend/Services/Settings/IApplicationSettingsService.cs

Feature: Tweaked logic for prompt to review

---

src/Files.App (Package)/Package.appxmanifest

Release: v2.4.33

---

src/Files.App/UserControls/Pane/PreviewPane.xaml

- Fixed issue where option to hide details pane wasn't working
**Validation**

Fix: Fixed issue where option to hide details pane wasn't working

---

README.md

Repo: Updated readme file

---

src/Files.App/UserControls/AddressToolbar.xaml
src/Files.App/UserControls/SearchBox.xaml

**Before**
**After**
**Validation**

Feature: Tweaked border brush on path and search box

---

src/Files.App/Filesystem/StorageItems/ZipStorageFolder.cs

Fix: Fixed issue where the right click menu didn't load properly in folders that have archive extensions

---

src/Files.App/UserControls/SidebarControl.xaml.cs

- Fixes a bug in #11204 where the context menu items in the sidebar would not show up
**Validation**

Fix: Fixed sidebar context menu items not showing for recent files

---

src/Files.App/App.xaml.cs

- Closes #11235...
**Validation**

Fix: Fixed icon in preview build

---

builds/azure-pipelines-release.yml
src/Files.App/App.xaml.cs

Fix: Fixed CI AppCenter secret

---

src/Files.App/Dialogs/SettingsDialog.xaml

- Apply app theme to settings dialog
**Validation**

Feature: Apply app theme to settings dialog

---

builds/azure-pipelines-release.yml
src/Files.App (Package)/Package.appxmanifest

Preview build: 2.4.35

---

src/Files.App/Helpers/ShellContextMenuHelper.cs

- This PR is to avoid errors in #11304 .
**Validation**

Fix: Fixed showOpenWithMenu not working

---

src/Files.App (Package)/Package.appxmanifest

Release: 2.4.40

---

.editorconfig
Settings.XamlStyler

- Closes #11337 
**Validation**

Enforce tabs for Xaml in EditorConfig and Xaml Styler

---

src/Files.App/ViewModels/SettingsViewModels/AppearanceViewModel.cs

- Closes #11322 
**Validation**
**Screenshot**
Exception:

Fix: Fixed crash that would occur after changing background color

---

src/Files.App/Views/LayoutModes/ColumnViewBrowser.xaml.cs

This is a small fix for #11344 .
#11344 would probably still work, but theoretically it might cause timing problems, so I fixed it.
**Validation**

Fix: A small fix to Improve Column View

---

src/Files.App/Helpers/ContextFlyoutItemHelper.cs
src/Files.App/Helpers/ShellContextMenuHelper.cs

- Closes #11345
**Validation**

Feature: Show rotate options in main context menu

---

src/Files.App/UserControls/SidebarControl.xaml.cs
src/Files.App/UserControls/Widgets/HomePageWidget.cs

- Closes #11299 
**Validation**

Feature: Hardcode width for right click menu

---

src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml.cs

Fix: Fixed minimum menu width for recent files widget

---

src/Files.App/UserControls/SidebarControl.xaml

- Closes #5683...
**Validation**

Fix: Fixed issue where the sidebar scrollbar wasn't clickable

---

src/Files.App/Dialogs/FilesystemOperationDialog.xaml
src/Files.App/Strings/en-US/Resources.resw

- Closes #11389 
**Validation**

Fix: Added "Apply this action to all conflicting items" to Resouces.resw

---

src/Files.App/Helpers/ContextFlyoutItemHelper.cs

- Closes #11391 
**Validation**

Fixed: Right clicking empty space doesn't show context menu

---

src/Files.App/ResourceDictionaries/PathIcons.xaml
src/Files.App/ViewModels/ContextMenuFlyoutItemViewModel.cs

Feature: Opacity icon in context menu

---

tests/Files.InteractionTests/Tests/FolderTests.cs

CI: Updated folder tests

---

src/Files.App (Package)/Files.Package.wapproj
src/Files.App (Package)/Package.appxmanifest
src/Files.App/Files.App.csproj
src/Files.App/Strings/lt/Resources.resw

Setup Lithuanian translation

---

src/Files.App/Views/BaseShellPage.cs

- Closes #11443 
- Related #11281 
- Related #11034 
**Validation**

Fix: Fixed issue with open terminal as admin not working

---

src/Files.App/UserControls/Widgets/QuickAccessWidget.xaml.cs

- Refactors parts of quickaccesswidget according to its change of use (it is now not related to libraries anymore)
- Related to #4180
**Validation**

Codebase: Refactor QuickAccessWidget.xaml.cs

---

src/Files.App/Actions/Favorites/PinItemAction.cs
src/Files.App/Actions/Favorites/UnpinItemAction.cs
src/Files.App/Commands/CommandCodes.cs
src/Files.App/Commands/Manager/CommandManager.cs
src/Files.App/Commands/Manager/ICommandManager.cs
src/Files.App/Helpers/ContextFlyoutItemHelper.cs
src/Files.App/Interacts/BaseLayoutCommandImplementationModel.cs
src/Files.App/Interacts/BaseLayoutCommandsViewModel.cs
src/Files.App/Interacts/IBaseLayoutCommandImplementationModel.cs

- Related to #11481
**Validation**

Feature: Add RichCommand for pinning and unpinning items

---

src/Files.App/Actions/Favorites/PinItemAction.cs
src/Files.App/Actions/Favorites/UnpinItemAction.cs

- Fixes issue with #11492
**Validation**

Fix: Fixed pin/unpin command when no items are selected

---

src/Files.App/Dialogs/SettingsDialog.xaml
src/Files.App/Helpers/ContextFlyoutItemHelper.cs
src/Files.App/UserControls/InnerNavigationToolbar.xaml
src/Files.App/UserControls/MultitaskingControl/HorizontalMultitaskingControl.xaml
src/Files.App/UserControls/SidebarControl.xaml.cs
src/Files.App/UserControls/Widgets/BundlesWidget.xaml
src/Files.App/UserControls/Widgets/DrivesWidget.xaml.cs
src/Files.App/Views/LayoutModes/ColumnViewBase.xaml
src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml
src/Files.App/Views/LayoutModes/GridViewBrowser.xaml
src/Files.App/Views/Properties/MainPropertiesPage.xaml.cs
src/Files.App/Views/SettingsPages/Preferences.xaml

- Closes #11488.
**Validation**

Feature: Replaced old icons

---

src/Files.App/Helpers/ContextFlyoutItemHelper.cs
src/Files.App/ViewModels/ContextMenuFlyoutItemViewModelBuilder.cs

- Fixed primary commands in the context menu
**Validation**

Fix: Fixed primary commands in the context menu

---

src/Files.App/Filesystem/StorageFileHelpers/StorageFileExtensions.cs

- Closes #11508 
**Validation**

Fix: Fixed issue where the PathBox was not working in network folders

---

src/Files.App/Filesystem/QuickAccessManager.cs

- Removes the `PinnedItems.json` file which is now not used for storing favorite items
**Validation**

Feature: Remove the `PinnedItems.json` file

---

src/Files.App/ServicesImplementation/SideloadUpdateService.cs

Fix: Force create updated msix

---

.github/FUNDING.yml

Change my GitHub name so it need to be correct here
**Validation**

Fix: Josh65 Sponsor link

---

src/Files.App/UserControls/InnerNavigationToolbar.xaml

- Closes #11534 
**Validation**

Fix: Fixed issue where delete button didn't work on toolbar

---

src/Files.App/Views/Properties/MainPropertiesPage.xaml.cs
src/Files.App/Views/Properties/SecurityPage.xaml.cs

- Closes #11544
**Validation**

Fix: Fixed file properties when multiple files are selected

---

src/Files.App/Views/BaseShellPage.cs

- Closes #11555 
**Validation**

Fix: Fixed open in terminal not working for path with spaces

---

src/Files.App/Helpers/ContextFlyoutItemHelper.cs
src/Files.App/ViewModels/ContextMenuFlyoutItemViewModelBuilder.cs

Fix a bad visibility (public -> private)
**Validation**

Fix: Fixed ContextMenuFlyoutItemViewModelBuilder visibility

---

src/Files.App/Filesystem/FilesystemOperations/Helpers/FilesystemHelpers.cs

- Closes #11624
**Validation**

Fix: Fixed drag and drop from Desktop to throw COMException

---

src/Files.App/Views/Properties/MainPropertiesPage.xaml.cs

- Closes #11621 
**Validation**

Fix: Fixed displaying Hashes tab in multiple files properties

---

src/Files.App/Actions/FileSystem/DeleteItemAction.cs
src/Files.App/Views/ColumnShellPage.xaml
src/Files.App/Views/ColumnShellPage.xaml.cs
src/Files.App/Views/ModernShellPage.xaml
src/Files.App/Views/ModernShellPage.xaml.cs

* Use the good code for delete action
* Remove old hotkeys for cut/copy/delete command
* I left the shortcut Ctrl+D for Delete. Will be removed when it will be possible to assign 2 hotkeys to the same command (the pr is in preparation).
**Validation**

Fix Delete command

---

src/Files.App/Actions/FileSystem/DeleteItemAction.cs

Allow deletion from search results.
The view is refreshed naturally.
Fixes #11650.
**Validation**

Allow deletion from search results.

---

src/Files.App/Actions/FileSystem/DeleteItemAction.cs

- Closes #11654 
**Validation**

Fix: Fixed permanent deletion incorrectly defaulted

---

src/Files.App/Views/Properties/MainPropertiesPage.xaml.cs

- Closes #11663
**Validation**

Fix: Fixed issue where Hash tab was not displayed for archive files

---

src/Files.App/Views/MainPage.xaml.cs

- Closes #11680 
**Validation**

Fix: Fixed Windows key

---

src/Files.App/Helpers/ContextFlyoutItemHelper.cs
src/Files.App/ViewModels/ToolbarViewModel.cs

- Closes #11681 
**Validation**

Fix: Disable Rename in Recycle Bin

---

src/Files.App/Actions/Content/ImageEdition/RotateLeftAction.cs
src/Files.App/Actions/Content/ImageEdition/RotateRightAction.cs
src/Files.App/Helpers/ContextFlyoutItemHelper.cs

- No opened issue.
**Validation**

Fix: Fixed issue where rotate option was enabled in recycle bin

---

src/Files.App/Actions/Content/ImageEdition/RotateLeftAction.cs
src/Files.App/Actions/Content/ImageEdition/RotateRightAction.cs

- Closes #11683 
**Validation**

Fix: Fixed crash when switching between tabs

---

src/Files.App/Views/Properties/HashesPage.xaml
src/Files.Shared/Helpers/ChecksumHelpers.cs

- Related to #11668 
**Details**
* Fixed issue where tooltips were not updated from "Calculating...".
* Changed to output hash values in lower case except CRC32, because it is more common.
**Validation**

Fix: Follow-ups to Hashes tab

---

src/Files.App/Actions/FileSystem/DeleteItemAction.cs
src/Files.App/Views/MainPage.xaml.cs

- Closes #11696 
**Validation**

Fix: Fixed issue where delete button would delete file while editing filename

---

src/Files.App/Filesystem/FilesystemOperations/Helpers/FilesystemHelpers.cs

It seems to work to me, but I don't understand exactly what happens with this code change, so I would like someone who does understand to review it.
- Closes #11627
**Validation**

Fix: Fixed issue where items could go to the trash if copy/move was skipped

---

src/Files.App/Views/LayoutModes/ColumnViewBase.xaml.cs
src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs
src/Files.App/Views/LayoutModes/GridViewBrowser.xaml.cs
src/Files.App/Views/ModernShellPage.xaml.cs

- Closes #11709 
**Validation**

Fix: Disabled double-clicking to go up in the search results page

---

src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs

Remove old unused code.
**Validation**

Code Quality: Removed property AreAllItemsSelected

---

src/Files.App/Actions/Content/Background/SetAsLockscreenBackgroundAction.cs
src/Files.App/Actions/Content/Background/SetAsSlideshowBackgroundAction.cs
src/Files.App/Actions/Content/Background/SetAsWallpaperBackgroundAction.cs

Fix a nullable error when opening the column view.
**Validation**

Fix: Fixed set as background command in columns layout

---

.github/pull_request_template.md

GitHub: Update PR template

---

src/Files.App/UserControls/OpacityIcon.xaml
src/Files.App/UserControls/OpacityIcon.xaml.cs

- Added IsSelected state to opacity icon
**Validation**

Feature: Added selected state to opacity icon

---

src/Files.App/Views/LayoutModes/ColumnViewBase.xaml.cs

Fix: Fixed scrolling to the last item when typing name in the column layout

---

src/Files.App/Filesystem/ListedItem.cs

Fix: Fixed the size display of ftp folders

---

src/Files.App/DataModels/AppModel.cs
src/Files.App/DataModels/NavigationControlItems/LocationItem.cs
src/Files.App/DataModels/SidebarPinnedModel.cs
src/Files.App/ViewModels/SidebarViewModel.cs

**Validation**
2. Verify sidebar items load without crashing

Code Quality: Removed App.AppModel.SymbolFontFamily

---

src/Files.App/Views/LayoutModes/GridViewBrowser.xaml

Same as #11546 but for tiles layout.
**Validation**

Feature: Add checkbox pointer behavior for tiles layout

---

src/Files.App/Dialogs/FilesystemOperationDialog.xaml

Fix: Removed unnecessary focus in confirmation dialog

---

README.md

**Validation**
Visually through Github.

Github: Adding link to the task board

---

src/Files.App/ResourceDictionaries/PathIcons.xaml
src/Files.App/UserControls/InnerNavigationToolbar.xaml

**Validation**
2. Select an image file
3. Check the toolbar icon for "Set as background"

Feature: Added color icon for "Set as background"

---

src/Files.App/ResourceDictionaries/PathIcons.xaml

- Added contrast fill to the paste icon

Feature: Updated paste icon

---

src/Files.App/Actions/Content/Archives/CompressIntoArchiveAction.cs
src/Files.App/Actions/Content/Archives/CompressIntoSevenZipAction.cs
src/Files.App/Actions/Content/Archives/CompressIntoZipAction.cs
src/Files.App/Actions/Content/Archives/DecompressArchive.cs
src/Files.App/Actions/Content/Archives/DecompressArchiveHere.cs
src/Files.App/Actions/Content/Archives/DecompressArchiveToChildFolderAction.cs
src/Files.App/Actions/Content/Background/SetAsLockscreenBackgroundAction.cs
src/Files.App/Actions/Content/Background/SetAsSlideshowBackgroundAction.cs
src/Files.App/Actions/Content/Background/SetAsWallpaperBackgroundAction.cs
src/Files.App/Actions/Content/ImageEdition/RotateLeftAction.cs
src/Files.App/Actions/Content/ImageEdition/RotateRightAction.cs
src/Files.App/Actions/Favorites/PinItemAction.cs
src/Files.App/Commands/Manager/CommandManager.cs

Use the same namespace for all actions.
**Validation**

Fix: Fixed namespaces for actions

---

src/Files.App/BaseLayout.cs

Fix: Fixed issue with drag and drop making selected items wrong

---

src/Files.App/App.xaml.cs
src/Files.App/ViewModels/ItemViewModel.cs

Fix: Fire and forget add operations

---

src/Files.App/Actions/FileSystem/RenameAction.cs
src/Files.App/Commands/CommandCodes.cs
src/Files.App/Commands/Manager/CommandManager.cs
src/Files.App/Commands/Manager/ICommandManager.cs
src/Files.App/Helpers/ContextFlyoutItemHelper.cs
src/Files.App/Interacts/BaseLayoutCommandImplementationModel.cs
src/Files.App/Interacts/BaseLayoutCommandsViewModel.cs
src/Files.App/Interacts/IBaseLayoutCommandImplementationModel.cs
src/Files.App/UserControls/InnerNavigationToolbar.xaml
src/Files.App/ViewModels/ToolbarViewModel.cs
src/Files.App/Views/BaseShellPage.cs
src/Files.App/Views/ColumnShellPage.xaml
src/Files.App/Views/ColumnShellPage.xaml.cs
src/Files.App/Views/ModernShellPage.xaml
src/Files.App/Views/ModernShellPage.xaml.cs

Related #11481 
I'm not sure about the style I should use in `RenameAction.IsPageTypeValid()`
**Validation**
1. Open app and use F2 or toolbar button to rename files

RichCommands: Rename

---

src/Files.App/Views/BaseShellPage.cs

overriden -> overridden
**Validation**

Fix: Fixed typo in BaseShellPage.cs

---

src/Files.App/Helpers/WallpaperHelpers.cs

Fix: Fixed issue where "Set as desktop slideshow" didn't work

---

src/Files.App/Views/LayoutModes/ColumnViewBase.xaml

Closes #11372
**Validation**
1. Open app
2. Enable compact spacing
3. Switch to the column layout and verify that the text is properly aligned 

Fix: Fixed alignment in compact mode

---

src/Files.App/Filesystem/Drives.cs
src/Files.App/ViewModels/ItemViewModel.cs

Closes #11883 
**Validation**
This PR also fixes the issue with quick access widgets containing shell folders taking a long time to load.

Fix: Fixed invalid "Network folder error" when opening shell folders

---

src/Files.App/Views/LayoutModes/GridViewBrowser.xaml

Closes #11842...
**Validation**
1. Switch to the tiles layout
2. Add a tag to any item
3. Verify that the checkbox is on top of the tag

Feature: Fixed ZOrder of CheckBox

---

src/Files.App/UserControls/InnerNavigationToolbar.xaml

Fix: Fixed issue with no "Date deleted" in group option

---

src/Files.App/ViewModels/ItemViewModel.cs

This is the same behavior as in Explorer so it should be ok.
Closes #9429 
**Validation**

Fix: No items selected after deletion

---

builds/azure-pipelines-preview.yml
builds/azure-pipelines-release.yml

CI: Created release-preview pipeline

---

.github/ISSUE_TEMPLATE/bug_report.yml

GitHub: Fixed bug report template

---

.github/ISSUE_TEMPLATE/bug_report.yml
src/Files.App/Filesystem/FilesystemOperations/FileSystemProgress.cs

Closes #11919 
**Validation**
1. Open app and start copying a big item
2. Click `Clear All` in the status center

Fix: Fixed issue where clear all removed active tasks in Operation center

---

src/Files.App (Package)/Package.appxmanifest

Release: 2.4.61

---

src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml
src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml.cs

Fix: Fixed right-clickable area in the recent files widget

---

src/Files.App/Helpers/FileOperationsHelpers.cs

Closes #11973
**Validation**
1. Create an invalid url file and check that it appears in Files
2. Make sure that opening that shortcut shows the "invalid shortcut" dialog

Fix: Show invalid url files in the file list

---

src/Files.Shared/FileLogger.cs

Fix: Log exception stack traces

---

src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml
src/Files.App/Views/LayoutModes/ColumnViewBase.xaml

Fix: Fixed XAML format in the servicing branch

---

src/Files.Backend/Helpers/FileExtensionHelpers.cs

Closes #11466
**Validation**
1. Open app
2. Double click on iso file
3. Verify that the file is mounted

Feature: Auto mount ISO files

---

src/Files.App (Package)/Package.appxmanifest

Release: v2.4.66

---

src/Files.App/Views/ModernShellPage.xaml.cs

Fix: Fixed NullReferenceException in `ModernShellPage`

---

src/Files.App (Package)/Package.appxmanifest
src/Files.App/Actions/Content/Archives/DecompressArchive.cs
src/Files.App/Views/ColumnParam.cs
src/Files.App/Views/LayoutModes/ColumnViewBase.xaml.cs
src/Files.App/Views/LayoutModes/ColumnViewBrowser.xaml.cs
src/Files.App/Views/ModernShellPage.xaml.cs

Servicing: v2.4.67

---

src/Files.App/App.xaml.cs

Fix: Fixed infinite restart loop

---

src/Files.App/Helpers/ThemeHelper.cs

Feature: Reinitialize ThemeHelper

---

src/Files.App/UserControls/Widgets/DrivesWidget.xaml.cs

Fix: Fixed System.InvalidOperationException

---

src/Files.App/App.xaml.cs

Code Quality: Disable AppCenter on dev builds

---

src/Files.App (Package)/Package.appxmanifest
src/Files.App/Helpers/ShellContextMenuHelper.cs
src/Files.App/Shell/ContextMenu.cs
src/Files.App/ViewModels/ItemViewModel.cs

Also added a replacement for the remaining `EnqueueAsync()`.
**Validation**

Servicing v2.4.70

---

src/Files.App/Actions/Start/UnpinFromStartAction.cs
src/Files.App/ViewModels/Dialogs/CreateShortcutDialogViewModel.cs

Fix: Backported fixes for critical issues into the servicing branch

---

src/Files.App/Helpers/FilePropertiesHelpers.cs

Fix: Fixed build error in the servicing branch

---

src/Files.App/Helpers/FileOperationsHelpers.cs

Fix: Fixed crash with Win32Exception

---

src/Files.App/Resources/PreviewPanePropertiesInformation.json
src/Files.App/Resources/PropertiesInformation.json

Fix: Fixed wrong total editing time format

---

src/Files.App/Commands/Manager/CommandManager.cs

Fix: Fixed issue where some hotkeys were not working

---

src/Files.App/Views/HomePage.xaml.cs

Related #12316 
**Validation**
1. Navigate to a Git directory
2. See that branch button is visible
3. Navigate to "Home"
4. See that the status bar is empty

Fix: Don't show git info in Home

---

.github/ISSUE_TEMPLATE/config.yml

This will prevent any blank issues to be created. As seen in https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
> in order to properly manage the issues, we have to close issues that don't follow the issue templates.
https://github.com/files-community/Files/issues/12312#issuecomment-1540577114
**Validation**
- Neither needed or possible :)

GitHub: Create config.yml

---

src/Files.App/Views/Settings/AboutPage.xaml
src/Files.App/Views/Settings/AdvancedPage.xaml
src/Files.App/Views/Settings/AppearancePage.xaml
src/Files.App/Views/Settings/FoldersPage.xaml
src/Files.App/Views/Settings/GeneralPage.xaml
src/Files.App/Views/Settings/TagsPage.xaml

Revert "Feature: Switched to RepositionThemeTransition"

---

src/Files.App/Commands/HotKey/HotKeyCollection.cs
src/Files.App/Strings/en-US/Resources.resw

Fix: Fixed key labels

---

src/Files.App/Views/LayoutModes/BaseLayout.cs

Closes #12402 
**Validation**
1. Open app
2. Selected some items
3. Right click on white space

Fix: Fixed an issue where right clicking empty space didn't clear selection

---

src/Files.App/UserControls/Widgets/QuickAccessWidget.xaml.cs

Closes #12377
**Validation**
2. Pin item
3. See it doesn't duplicate

Fix: Fixed issue where pinned favorites were sometimes duplicated

---

.github/ISSUE_TEMPLATE/config.yml

Closes #12364
**Validation**
Approved via [comment](https://github.com/files-community/Files/issues/12364#issuecomment-1556062821)

GitHub: Added Crowdin link to issue config

---

src/Files.App/Helpers/GitHelpers.cs

Fixed git events
**Validation**

Analytics: Fixed git events

---

src/Files.App/Strings/en-US/Resources.resw
src/Files.App/UserControls/Pane/PreviewPane.xaml

Closes #12437...
**Validation**
2. Open details pane
3. Switch between the details and preview tabs

Feature: Added pivot to switch between details and preview pane

---

src/Files.App/ServicesImplementation/Settings/GeneralSettingsService.cs

Enabled the "continue where you left off" option by default.
**Validation**
3. Check that the default startup option is "continue where you left off"

Feature: Enable continue where you left off by default

---

src/Files.App/Shell/ContextMenu.cs

Fix: Fixed crash when right-clicking non-existing drive

---

src/Files.App/Views/Properties/LibraryPage.xaml

Fix: Fixed issue where Files crashed when trying to open the library page on the properties window

---

src/Files.App/Filesystem/StorageEnumerators/UniversalStorageEnumerator.cs
src/Files.App/Filesystem/StorageEnumerators/Win32StorageEnumerator.cs

Fix: Fixed issue where icons and names of library items were not displayed

---

src/Files.App (Package)/Package.appxmanifest

Preview: v2.4.84

---

src/Files.App/UserControls/Pane/PreviewPane.xaml
src/Files.App/UserControls/Pane/PreviewPane.xaml.cs

**Validation**
1. Open preview pane
2. Verify the preview is on top and the details on the bottom
3. Switch to the preview tab and verify the preview is centered
4. Resize app until the preview pane is moved to the bottom
5. Verify that the preview is shown on the left and the details on the right
6. Switch to the preview tab and verify that the preview is centered

Feature: Added horizontal layout to the preview pane

---

src/Files.App/Actions/Show/TogglePreviewPaneAction.cs
src/Files.App/ResourceDictionaries/PathIcons.xaml
src/Files.App/UserControls/InnerNavigationToolbar.xaml

Closes #12356...
**Validation**
1. Toggle preview pane icon and verify the icon updates to match the selected state

Fix: Fixed contrast issues with the preview pane icon

---

src/Files.App/Filesystem/Security/AccessControlEntry.cs

Fix: Fixed translation in Advanced Permissions page

---

src/Files.App/UserControls/Pane/PreviewPane.xaml

Closes #12509...
**Validation**

Fix: Fixed preview pane context menu

---

src/Files.App/UserControls/Pane/PreviewPane.xaml
src/Files.App/ViewModels/UserControls/PreviewPaneViewModel.cs

Closes #12511...
**Validation**
1. Select item and open details pane
2. Switch to the preview tab
3. Select a different file and switch to the details tab
4. Confirm that the details are correctly shown

Fix: Fixed issue where details pane would sometimes fail to load

---

src/Files.App/UserControls/AddressToolbar.xaml

Closes #12517
**Validation**
1. Open ongoing operations flyout and confirm it opens underneath the button

Fix: Fixed position of ongoing operations flyout

---

src/Files.App/Actions/FileSystem/AddItemAction.cs
src/Files.App/Actions/FileSystem/CreateFolderAction.cs

1. Fixed issue where "add item" action was disabled in secondary columns.
2. Fixed issue where "add item' was disabled when items were selected (it should still be hidden in the right click menu)
**Validation**
1. Open a second column in the columns layout
3. Confirm the new/add item action is enabled

Fix: Fixed issue where add item was disabled in column layout

---

src/Files.App/ServicesImplementation/PreviewPopupProviders/SeerProProvider.cs

Feature: SwitchPreview for SeerProProvider

---

src/Files.App (Package)/Package.appxmanifest

Preview: v2.4.85

---

src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml

Closes #12567...
**Validation**
1. Open details layout and confirm alignment is correct

Fix: Fixed column alignment in details layout

---

src/Files.App/UserControls/Pane/PreviewPane.xaml

**Validation**
1. Open preview pane and confirm the radio buttons have the correct style

Feature: Updated radio button design on the preview pane

---

src/Files.App/Data/Models/DirectoryPropertiesViewModel.cs
src/Files.App/ResourceDictionaries/PathIcons.xaml
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/UserControls/StatusBarControl.xaml

Feature: Added git icons

---

src/Files.App/Views/LayoutModes/BaseLayout.cs

Fix: Fixed issue with context menu sometimes not displaying

---

src/Files.App/ViewModels/Settings/AdvancedViewModel.cs
src/Files.App/ViewModels/Settings/GeneralViewModel.cs
src/Files.App/Views/Settings/AdvancedPage.xaml
src/Files.App/Views/Settings/GeneralPage.xaml

<!-- 
🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
I ACKNOWLEDGE THE FOLLOWING BEFORE PROCEEDING:
1. PR may be deleted if it is not following the template
2. Try not to make duplicates. Do a quick search before posting
3. Add a clear title starting with "Feature:" or "Fix:"
**Validation**

Feature: Moved "open on Windows startup" to advanced settings

---

src/Files.App (Package)/Package.appxmanifest

Release: v2.5

---

src/Files.App/ViewModels/Properties/Items/CombinedProperties.cs

Fix: Fixed issue where archive files were counted as folders

---

src/Files.App/Views/LayoutModes/ColumnViewBase.xaml.cs

Fix: Fixed issue where column layout items remained selected on certain startup settings

---

src/Files.App/UserControls/SidebarControl.xaml.cs

Closes #12595 
**Validation**
1. Open `C:\Program Files`.
2. Middle-click a sidebar item to open the location in new tab.
3. Click  `C:\Program Files` tab.
4. It will show `C:\Program Files`. Without this fix, it will open `C:`.

Fix: Fixed tab navigation when middle-clicking a sidebar item

---

src/Files.App/UserControls/StatusBarControl.xaml

Fix: Revert "Fix: Fixed crash in Dual Pane mode when switching away from Git folder (#12599)"

---

src/Files.App/Helpers/ContextFlyoutItemHelper.cs
src/Files.App/Strings/en-US/Resources.resw

Closes #12582...
**Validation**
1. Right click items and confirm the "Compress" option is shown
2. Right click archive and confirm the "Extract" option is shown

Feature: Separated the archive options in the right click menu

---

src/Files.App/Actions/FileSystem/CreateShortcutFromDialogAction.cs
src/Files.App/Helpers/ContextFlyoutItemHelper.cs

Closes #12668...
**Validation**
1. Right click empty space
2. Expand the "new" menu
3. Confirm the option for "shortcut" has an icon

Fix: Fixed issue where the icon was missing from the "new shortcut" option

---

src/Files.App/Shell/ShellNewMenuHelper.cs

Fix: Fixed an issue where the right-click menu would sometimes freeze the app

---

src/Files.App/Contexts/ContentPage/ContentPageContext.cs

Fix: Fixed NullReferenceException in ContentPageContext

---

src/Files.App/Strings/en-US/Resources.resw
src/Files.App/Views/Properties/SecurityAdvancedPage.xaml
src/Files.App/Views/Properties/SecurityPage.xaml

Fix: Translated missing strings in Properties

---

src/Files.App/Data/Models/DirectoryPropertiesViewModel.cs

Fix: Fixed ArgumentOutOfRangeException in DirectoryPropertiesViewModel

---

src/Files.App/UserControls/InnerNavigationToolbar.xaml

Fix: Fixed crash that would sometimes occur when navigating away from archives

---

src/Files.App (Package)/Package.appxmanifest

Release: 2.5.10

---

src/Files.App/Constants.cs

Fix: Fixed issue where `%temp%` and `%tmp%` were not replaced with the correct path

---

src/Files.App/Views/Shells/ColumnShellPage.xaml.cs

Fix: Fixed crash that would occur when navigating to Home in the column layout

---

src/Files.App/Resources/PreviewPanePropertiesInformation.json
src/Files.App/Resources/PropertiesInformation.json

Fix: Fixed issue where part of the path in properties was localized

---

src/Files.App/Actions/FileSystem/CopyPathAction.cs

Fix: Fixed crash that would occur when copying path

---

src/Files.App/Actions/Display/GroupAction.cs
src/Files.App/Actions/Display/SortAction.cs
src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml

Fix: Fixed issue where Sort/Group by original folder were disabled in the recycle bin

---

src/Files.App/Data/Models/ItemViewModel.cs

Closes #12731...
**Validation**
1. Open folder with readme file
2. Confirm the readme isn't auto selected

Feature: Removed behavior that auto selected readme files

---

src/Files.App (Package)/Package.appxmanifest

Preview: 2.5.11

---

src/Files.App/Dialogs/GitHubLoginDialog.xaml
src/Files.App/Strings/en-US/Resources.resw

Related #12633 
**Validation**
1. Login to GitHub

Code Quality: Updated Git login success icon & strings

---

src/Files.App/Views/Settings/TagsPage.xaml

Closes #12800...
**Validation**
1. Enter a long tag name and confirm it gets clipped

Fix: Fixed issue where long tag names weren't clipped

---

src/Files.App/Helpers/GitHelpers.cs

https://discord.com/channels/725513575971684472/1124348508913270877
**Validation**

Fix: Fixed issue where checking out a Git branch would sometimes crash the app

---

src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml

Related to #12802 
**Validation**

Feature: Trim tag names that are too long in the details layout

---

Files.sln
src/Files.App (Package)/Package.appxmanifest
src/Files.App.BackgroundTasks/Files.App.BackgroundTasks.csproj
src/Files.App.BackgroundTasks/UpdateTask.cs
src/Files.App/Files.App.csproj

- Improved readability
> **Warning**<br/>Please do not review code lines that I did not changed. I cannot make more diff. If there're more codes that are preferred to change, I will do that and mark that PR as the final one for that stage.
Related #4180
_None_

Code Quality: Rename BackgroundTasks to Files.App.BackgroundTasks

---

src/Files.App/Data/Models/ItemViewModel.cs
src/Files.App/Data/Models/SidebarPinnedModel.cs
src/Files.App/Filesystem/Search/FolderSearch.cs
src/Files.App/Helpers/FileThumbnailHelper.cs
src/Files.App/ViewModels/Previews/BasePreviewModel.cs
src/Files.App/ViewModels/Previews/FolderPreviewViewModel.cs
src/Files.App/ViewModels/Properties/Items/DriveProperties.cs

- Improved quality of the sidebar icons
**Validation**

Feature: Improved quality of the sidebar icons

---

src/Files.App/UserControls/Pane/PreviewPane.xaml

**Validation**
Left before fix, right after fix

Fix: Fixed issue where long texts in the details pane were cropped

---

specs/RichCommand/CommandList.md
src/Files.App/Actions/Display/GroupAction.cs
src/Files.App/Actions/Display/SortAction.cs
src/Files.App/Commands/CommandCodes.cs
src/Files.App/Commands/Manager/CommandManager.cs
src/Files.App/Commands/Manager/ICommandManager.cs
src/Files.App/Data/Models/ColumnsViewModel.cs
src/Files.App/Data/Models/FolderSettingsViewModel.cs
src/Files.App/Data/Models/ItemViewModel.cs
src/Files.App/Helpers/ContentLayout/LayoutPreferences.cs
src/Files.App/Helpers/MenuFlyout/ContextFlyoutItemHelper.cs
src/Files.App/Helpers/StorageItemCollection/SortingHelper.cs
src/Files.App/Services/Settings/FoldersSettingsService.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/UserControls/InnerNavigationToolbar.xaml
src/Files.App/Views/LayoutModes/BaseLayout.cs
src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml
src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs
src/Files.Core/Services/Settings/IFoldersSettingsService.cs
src/Files.Shared/Enums/SortOption.cs

Closes #7070 
**Validation**
Grouping:

Feature: Added path column to Details layout for search results

---

src/Files.App (Package)/Package.appxmanifest

Preview: v2.5.12

---

src/Files.App (Package)/Files.Package.wapproj
src/Files.App (Package)/Package.appinstaller
src/Files.App (Package)/Package.appxmanifest

Preview: v2.5.13

---

src/Files.App/Actions/Display/LayoutAction.cs
src/Files.App/Actions/Global/EnterCompactOverlayAction.cs
src/Files.App/Actions/Global/ExitCompactOverlayAction.cs
src/Files.App/ResourceDictionaries/PathIcons.xaml
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/UserControls/InnerNavigationToolbar.xaml

Feature: Updated the toolbar icons

---

src/Files.App/Utils/Cloud/CloudDrivesDetector.cs
src/Files.Shared/Cloud/CloudProviders.cs

Closes #12873
**Validation**
1. Install ownCloud server & desktop app :)

Feature: Added support for ownCloud drive

---

src/Files.App/Utils/Shell/Win32API.cs

Fix: Fixed crash that would occur when an Inf file installation timed out

---

src/Files.App/Actions/Navigation/OpenNewPaneAction.cs
src/Files.App/Actions/Show/TogglePreviewPaneAction.cs
src/Files.App/ResourceDictionaries/PathIcons.xaml
src/Files.App/UserControls/InnerNavigationToolbar.xaml
src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs

Feature: Updated more icons

---

src/Files.App/UserControls/DataGridHeader.xaml
src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml

Feature: Updated the DataGrid header design

---

src/Files.App/ResourceDictionaries/PathIcons.xaml

Code Quality: Added status icons

---

src/Files.App/UserControls/Menus/FileTagsContextMenu.cs

Feature: Updated icons in Edit Tags menu

---

src/Files.App/ViewModels/Previews/FolderPreviewViewModel.cs

Code Quality: Fixed build error

---

src/Files.App (Package)/Package.appxmanifest

Preview: 2.5.14

---

src/Files.App/ResourceDictionaries/PathIcons.xaml
src/Files.App/Utils/Cloud/CloudDriveSyncStatusUI.cs
src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml
src/Files.App/Views/LayoutModes/GridViewBrowser.xaml

Closes #12685...
**Validation**
1. Open cloud folder
2. Confirm the new icons are being used in all the layouts (except columns)

Feature: Updated status icons for cloud drives

---

src/Files.App/UserControls/InnerNavigationToolbar.xaml

Fix: Fixed icon size in the Layout flyout

---

src/Files.App (Package)/Package.appxmanifest

Preview: v2.5.15

---

src/Files.App/UserControls/Pane/PreviewPane.xaml

Closes #12963 
**Validation**
1. Open app
2. Open the preview pane
3. Select a folder

Feature: Delay loading Properties button until details are finished loading

---

src/Files.App (Package)/Package.appxmanifest

Preview: v2.5.17

---

NOTICE.md
src/Files.App/Utils/Storage/Helpers/DriveHelpers.cs

Fix: Fixed issue that sometimes prevented drives from being displayed

---

src/Files.App/Views/Shells/ColumnShellPage.xaml.cs

Fix: Fixed issue that prevented using dual pane in the Column layout

---

src/Files.App (Package)/Package.appxmanifest

Release: v2.5.20

---

src/Files.App/MainWindow.xaml.cs

Closes #13001
Closes #13012
**Validation**

Fix: Fixed issue where the app sometimes got stuck on splash screen

---

src/Files.App/UserControls/InnerNavigationToolbar.xaml
src/Files.App/ViewModels/UserControls/ToolbarViewModel.cs

Fix: Fixed an issue where the layout flyout sometimes didn't highlight the selected layout

---

src/Files.App (Package)/Package.appxmanifest

Release: v2.5.21

---

src/Files.App/Data/Models/ItemViewModel.cs

Related #12737 
**Validation**
1. Open a large git folder

Fix: Fixed an issue where Git columns would cause the CPU usage to increase

---

src/Files.App/Helpers/UI/ThemeHelper.cs
src/Files.App/Services/ResourcesService.cs

Closes #12504
**Validation**
1. Pin Files to the task bar.
2. Press Win+num repeatedly to open Files many times simultaneously.
3. See the correct theme is applied to all Files windows.

Fix: Fixed an issue where the theme sometimes reset to light mode

---

src/Files.App/Services/QuickAccessService.cs

Closes #13042 
**Validation**
Unpin Desktop, Downloads, Recycle bin and others. All should be work well.

Fix: Fixed crash that occurred when unpinning a favorite

---

src/Files.App/UserControls/Pane/PreviewPane.xaml

Closes #13025...
**Validation**
1. Open Details Pane
2. Select file without any tags
3. Confirm the tags section is visible

Fix: Fixed issue where Details Pane didn't always display the tags section

---

src/Files.App/Views/Settings/AboutPage.xaml
src/Files.App/Views/Settings/AdvancedPage.xaml
src/Files.App/Views/Settings/FoldersPage.xaml

Closes #10783...
**Validation**

Code Quality: Updated icon codes

---

src/Files.App/Data/Items/DriveItem.cs
src/Files.App/Data/Items/INavigationControlItem.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/UserControls/SidebarControl.xaml.cs
src/Files.App/Utils/Storage/Helpers/StorageFileExtensions.cs

Fix: Fixed issue where volume labels were not displayed in the path bar

---

src/Files.App/Utils/RecycleBin/RecycleBinHelpers.cs

Fix: Fixed issue where emptying Recycle Bin would freeze the app

---

src/Files.App/Utils/Storage/StorageItems/ZipStorageFolder.cs

Fix: Fixed issue where exporting settings didn't overwrite existing files

---

src/Files.App/App.xaml
src/Files.App/ResourceDictionaries/App.Theme.TextBlockStyles.xaml
src/Files.App/ResourceDictionaries/PropertiesStyles.xaml
src/Files.App/Views/LayoutModes/ColumnViewBase.xaml
src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml
src/Files.App/Views/LayoutModes/GridViewBrowser.xaml
src/Files.App/Views/Properties/DetailsPage.xaml
src/Files.App/Views/Properties/HashesPage.xaml
src/Files.App/Views/Properties/MainPropertiesPage.xaml
src/Files.App/Views/Properties/SecurityAdvancedPage.xaml
src/Files.App/Views/Properties/SecurityPage.xaml

Closes #12553...
**Validation**
1. Set a custom font
2. Opened properties window and confirmed the custom font is being used

Fix: Fixed support for custom fonts in the properties window

---

src/Files.App/Data/Factories/PropertiesNavigationViewItemFactory.cs

Fix: Fixed issue where files without extensions didn't display details in the Propeties Window

---

src/Files.App/UserControls/DataGridHeader.xaml

Closes #13084...
**Validation**
1. Open folder with the details layout
2. Hover over the data grid headers
3. Confirm the background color doesn't flash

Fix: Fixed issue where DataGrid headers would sometimes blink when hovering over them

---

src/Files.App/UserControls/DataGridHeader.xaml

Fix: Fixed issue where clicking DataGrid headers didn't change the sort direction
**Validation**
1. Open folder using the Details Layout
2. Click data grid header to change the sort direction

Fix: Fixed issue where clicking DataGrid headers didn't change the sort direction

---

src/Files.App/Services/Settings/FoldersSettingsService.cs

- Increased the default width of the Git status column
- Hid some columns by default for better performance
**Validation**

Feature: Increased the default width of the Git status column

---

src/Files.App/Views/Properties/GeneralPage.xaml

Closes #13177 
**Validation**
2. Open properties window for a drive
3. Confirm the details section has the correct corner radius

Fix: Fixed the corner radius on the drive details page

---

src/Files.App (Package)/Package.appxmanifest
src/Files.App/App.xaml.cs

Preview: v2.5.22

---

src/Files.App/Services/Settings/ApplicationSettingsService.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/Views/MainPage.xaml.cs
src/Files.Core/Services/Settings/IApplicationSettingsService.cs

Closes #13209...
**Validation**
1. Open app as admin
2. Confirm that clicking "don't show again" works as expected

Feature: Display prompt when running Files as admin

---

src/Files.App/ResourceDictionaries/SideBarResources.xaml

Closes #13191...
**Validation**
1. Change the font in the settings file
2. Restart Files and confirm the sidebar uses the correct font

Fix: Fixed an issue where the sidebar didn't respect the custom font setting

---

src/Files.App/Helpers/MenuFlyout/ContextFlyoutItemHelper.cs
src/Files.App/Views/LayoutModes/BaseLayout.cs

Fix: Fixed issue where context menu icons wouldn't load in archives or FTP servers

---

src/Files.App/UserControls/SideBar/SideBarControls.xaml

Code Quality: Fix XAML Binding errors in Sidebar

---

src/Files.App (Package)/Package.appxmanifest

Preview: v2.5.24

---

src/Files.App/Views/Properties/DetailsPage.xaml

Closes #13073...
**Validation**
1. Open properties window on a file with read only properties

Feature: Added TextBlock for read only properties

---

src/Files.App/ViewModels/Properties/Items/CombinedFileProperties.cs

Related to #13278 
**Validation**

Code Quality: Show "(multiple values)" on read-only properties

---

src/Files.App (Package)/Package.appxmanifest

Preview: v2.5.25

---

src/Files.Shared/Helpers/FileExtensionHelpers.cs

Closes #10094...
**Validation**
1. Opened each archive format and confirmed the files were displayed

Feature: Added support for additional archive formats

---

src/Files.App/ViewModels/UserControls/PreviewPaneViewModel.cs

Closes #13296...
**Validation**
1. Select font file
2. Open preview pane and confirm it shows thumbnail instead of a broken preview

Code Quality: Disable font previews

---

src/Files.App/ViewModels/UserControls/ToolbarViewModel.cs

Fix: Fixed issue where some elements couldn't be clicked on when search is focused

---

src/Files.App/App.xaml.cs
src/Files.App/MainWindow.xaml.cs
src/Files.App/Program.cs

Fix: Fixed issue where parameters were ignored when resuming the app

---

src/Files.App/UserControls/MultitaskingControl/HorizontalMultitaskingControl.xaml.cs

Fix: Fixed NullReferenceException at launch

---

src/Files.App/Views/LayoutModes/BaseLayout.cs

Fix: Fixed issue where the "loading more" sub menu wouldn't always hide

---

src/Files.App/Utils/Archives/ArchiveCreator.cs
src/Files.App/Utils/StatusCenter/StatusCenterItem.cs
src/Files.App/Utils/StatusCenter/StatusCenterItemProgressModel.cs
src/Files.App/ViewModels/UserControls/StatusCenterViewModel.cs

Contributes to #11265
This PR provides the fundamental support needed by transfer speed implementation. 
/cc: @0x5bfa 
**Validation**

Code Quality: Improve the implementation of StatusCenterItemProgressModel

---

src/Files.App/UserControls/SideBar/SideBarItem.cs
src/Files.App/UserControls/SideBar/SideBarView.xaml.cs

Fix: Fixed issue where sidebar items could be selected unexpectedly

---

src/Files.App/Views/LayoutModes/BaseLayout.cs

Add null check on command string
**Validation**

Fix: Fixed an issue where the context menu didn't show all shell items

---

src/Files.App/App.xaml.cs
src/Files.App/Program.cs

Code Quality: Fixed semaphore to change for each type of build

---

src/Files.App/Strings/en-US/Resources.resw

Closes #12854...
**Validation**

Feature: Updated strings

---

src/Files.App/Strings/en-US/Resources.resw

Code Quality: Fixed a typo

---

src/Files.App/Data/Models/ItemViewModel.cs

Closes #13495 
**Validation**
1. Enter `\\wsl$` or `\\wsl.localhost` in the path bar.
2. Distros will be displayed without errors.

Fix: Fixed error when trying to open the root of WSL directories

---

src/Files.App (Package)/Package.appxmanifest

Preview: v2.5.30

---

src/Files.App (Package)/Package.appxmanifest

Preview: 2.5.31

---

.github/workflows/deploy-preview.yml

As the title.
_N/A_
1. https://github.com/files-community/Files/actions/workflows/deploy-preview.yml
_N/A_

CI: Update CD action

---

.github/workflows/deploy-preview.yml

_N/A_
_N/A_
2. Go to ...
_N/A_

Deploy: Update deployment actions

---

src/Files.App (Package)/Package.appxmanifest

Preview: 2.5.32

---

src/Files.App/Views/SplashScreenPage.xaml

- Fixed an issue where the splash screen text was hard coded
**Validation**

Fix: Fixed splash screen text in dev env

---

src/Files.App (Package)/Package.appxmanifest

Preview: v2.5.33

---

src/Files.App/Utils/RecentItem/RecentItems.cs

Removed logging from `ListRecentFoldersAsync` to clean up the noise from the log files.

Code Quality: Stop logging ListRecentFoldersAsync

---

.github/workflows/deploy-preview.yml

GitHub: Upload to blog storage

---

src/Files.App (Package)/Package.appxmanifest

Preview: 2.5.34

---

src/Files.App/Views/LayoutModes/ColumnViewBase.xaml.cs
src/Files.App/Views/LayoutModes/DetailsLayoutBrowser.xaml.cs
src/Files.App/Views/LayoutModes/GridViewBrowser.xaml.cs

https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/2349352020u/overview

Fix: Fix possible null exception with renaming items

---

src/Files.App/UserControls/StatusBarControl.xaml

Fix: Fixed issue where a crash would occur when navigating through Git repositories

---

src/Files.App/Data/Contexts/Multitasking/MultitaskingContext.cs

Code Quality: Fixed possible ArgumentOutOfRangeException

---

src/Files.App/Views/NavigationInteractionTracker.cs

https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/1629098285u/overview
https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/1293093855u/overview
https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/3382098107u/overview
**Validation**

Fix: Fixed ObjectDisposedException

---

src/Files.App/ViewModels/UserControls/PreviewPaneViewModel.cs

Closes #12564...
**Validation**
1. Select Office file
2. Display details pane
3. Confirm basic thumbnail is shown
4. Switch to preview pane
5. Confirm the full preview is displayed

Feature: Display basic preview in Details pane

---

src/Files.App/Dialogs/FilesystemOperationDialog.xaml.cs

There were no issues open in relation to this fix.
**Validation**
- [ X ] Did you build the app and test your changes?

Fix: Fixed theming issue in the confirm delete dialog 

---

src/Files.App/Utils/Storage/Operations/FilesystemHelpers.cs

https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/2623248240u/overview
**Validation**

Fix: Fixed Shell32.GetData COMException

---

src/Files.App/Utils/Serialization/Implementation/CachingJsonSettingsDatabase.cs
src/Files.App/Utils/Serialization/Implementation/DefaultJsonSettingsDatabase.cs

Closes #13682 
Related to #12617 
**Validation**

Fix: Fixed possible crash when adding a new settings value

---

src/Files.App (Package)/Package.appxmanifest
src/Files.Shared/Helpers/FileExtensionHelpers.cs

Feature: Added support for opening Jar archives in Files

---

src/Files.App/ViewModels/Settings/AdvancedViewModel.cs

Fix: Fixed crash that could occur when trying to open the settings file

---

src/Files.App/Actions/FileSystem/AddItemAction.cs

Added `Ctrl+ Shift+ I` shortcut to create new item
**Validation**
1. Confirm shortcut opens the create item dialog

Feature: Added `Ctrl+ Shift+ I` shortcut to create new item

---

src/Files.App/Views/LayoutModes/ColumnViewBrowser.xaml.cs

Related to #13691 
**Validation**

Fix: Fixed NullReferenceException with SetSelectedPathOrNavigate

---

src/Files.App/Utils/Storage/Collection/ConcurrentCollection.cs

Fix: Fixed possible crash when adding files and folders

---

src/Files.App/Services/Settings/GeneralSettingsService.cs

Changed the default value of `LeaveAppRunning` to false on dev builds.

Code Quality: Don't leave running in background in dev

---

src/Files.App/MainWindow.xaml.cs

Fix: Fixed issue where "Open Files on Windows startup" didn't work

---

src/Files.App/Helpers/ContentLayout/AdaptiveLayoutHelpers.cs
src/Files.App/ViewModels/Previews/MediaPreviewViewModel.cs
src/Files.App/ViewModels/UserControls/PreviewPaneViewModel.cs
src/Files.Shared/Helpers/FileExtensionHelpers.cs

Added extension helper for media files

Code Quality: Added extension helper for media files

---

src/Files.App/Actions/Navigation/OpenInNewWindowItemAction.cs

Closes #6539...
**Validation**
1. Select folder or folders
2. Use ctrl + alt + enter shortcut to open them in new windows

Feature: Open folder in new window via `ctrl` + `alt` + `enter`

---

src/Files.App/Views/LayoutModes/GridViewBrowser.xaml

Closes #1033...
This isn't the ideal solution because it makes the items taller even when it's not needed but it's better than nothing.

Fix: Always wrap text in grid layout

---

src/Files.App/Utils/Serialization/Implementation/DefaultJsonSettingsDatabase.cs

Closes #13816...
**Validation**
1. Mess up the settings file
2. Open Files and confirm the settings file is fixed up

Fix: Fixed crash that would occur when settings file was invalid

---

src/Files.App/Services/Settings/UserSettingsService.cs

Fix: Fixed issue where exporting settings didn't work

---

src/Files.App/Actions/Content/Selection/SelectAllAction.cs

Fixed null exception with isRenaming

Fix: Fixed null exception with isRenaming

---

src/Files.App/Views/LayoutModes/ColumnViewBrowser.xaml.cs
src/Files.App/Views/Shells/ColumnShellPage.xaml.cs

Related to: #13916 
**Validation**

Fix: Fixed NullReferenceException in SetSelectedPathOrNavigate

---

src/Files.App/Views/Shells/BaseShellPage.cs

- Fixed null ref warnings in BaseShellPage

Fix: Fixed null ref warnings in BaseShellPage

---

src/Files.Core/ViewModels/Dialogs/ReleaseNotesDialogViewModel.cs

- Fixed null ref warnings in release notes dialog

Fix: Fixed null ref warnings in release notes dialog

---

src/Files.App/Data/Models/SidebarPinnedModel.cs

- Fixed null ref in sidebar pinned model

Fix: Fixed null ref in sidebar pinned model

---

src/Files.App/Data/Items/ListedItem.cs

Closes #12774...
**Validation**

Fix: Don't check admin rights for cloud items

---

src/Files.App/Views/HomePage.xaml.cs
src/Files.App/Views/Shells/BaseShellPage.cs

- Fixed xamlRoot in the ConsentDialog

Fix: Fixed xamlRoot in the ConsentDialog

---

src/Files.App/Actions/Content/Archives/Compress/CompressIntoSevenZipAction.cs
src/Files.App/Actions/Content/Archives/Compress/CompressIntoZipAction.cs

- Fixed NullReferenceException in GetCompressDestination

Fix: Fixed NullReferenceException in GetCompressDestination

---

src/Files.App/ViewModels/UserControls/InfoPaneViewModel.cs
src/Files.Core.SourceGenerator/Files.Core.SourceGenerator.csproj

- Disable media preview for archive items

Fix: Disable media preview for archive items

---

src/Files.App/Helpers/Environment/ElevationHelpers.cs

Fix: Fixed check for admin

---

src/Files.App/Actions/FileSystem/OpenItemAction.cs
src/Files.App/Data/Models/ItemViewModel.cs
src/Files.App/Views/Layouts/DetailsLayoutPage.xaml.cs

- Added null reference checks to resolve warnings in Details Layout Page

Code Quality: Fixed Null Ref warnings in DetailsLayout

---

src/Files.App/Data/Models/ItemViewModel.cs
src/Files.App/Utils/Storage/StorageBaseItems/BaseBasicProperties.cs
src/Files.App/Utils/Storage/StorageBaseItems/BaseBasicStorageItemExtraProperties.cs
src/Files.App/Utils/Storage/StorageItems/FtpStorageFile.cs
src/Files.App/Utils/Storage/StorageItems/FtpStorageFolder.cs
src/Files.App/Utils/Storage/StorageItems/ShellStorageFile.cs
src/Files.App/Utils/Storage/StorageItems/ShellStorageFolder.cs
src/Files.App/Utils/Storage/StorageItems/SystemStorageFile.cs
src/Files.App/Utils/Storage/StorageItems/SystemStorageFolder.cs
src/Files.App/Utils/Storage/StorageItems/ZipStorageFile.cs
src/Files.App/Utils/Storage/StorageItems/ZipStorageFolder.cs
src/Files.App/ViewModels/UserControls/Previews/FolderPreviewViewModel.cs

Fix: Fixed issue where date created is updated when the file is updated

---

src/Files.App/Helpers/MenuFlyout/ItemModelListToContextFlyoutHelper.cs
src/Files.App/ResourceDictionaries/MenuFlyoutSubItemWithImageStyle.xaml
src/Files.App/UserControls/Menus/MenuFlyoutItemWithImage.xaml

Related to #14070 
**Validation**

Code Quality: Use ControlCornerRadius

---

src/Files.App/Helpers/Navigation/NavigationHelpers.cs

Fix: Fixed issue where tab icons and labels were sometimes not displayed when resuming

---

.github/workflows/ci.yml

Closes #14054  
**Validation**

GitHub: Fixed XAML formatting workflow

---

src/Files.App/UserControls/AddressToolbar.xaml

Closes #14072...
**Validation**
1. Start a couple of file operations
2. Confirm the item count is displayed in the center of the progress ring

Feature: Display operation count in the middle of the progress ring

---

src/Files.App/Utils/Storage/Operations/FileOperationsHelpers.cs

Closes #13978...
**Validation**
1. Open properties for an item that requires admin access to modify
2. Navigate to the compatibility page and confirm that it works to change the compatibility mode

Fix: Fixed issue where compatibility toggle wouldn't work for some files

---

src/Files.App/Views/Settings/AboutPage.xaml.cs

Fix: Fixed issue where third party licenses were not displayed

---

src/Files.App/Views/Settings/TagsPage.xaml

Closes #14162...
**Validation**
1. Open settings page for Tags
2. Click "Delete" button and confirm the text isn't cut off

Fix: Fixed issue where text was cut off in Tags flyout

---

src/Files.App/Helpers/CredentialsHelpers.cs

Fix: Fixed crash when trying to open Git settings

---

src/Files.App/Views/Layouts/ColumnsLayoutPage.xaml.cs

Closes #14189...
**Validation**
1. Set the layout mode for all folders to Columns
2. Enable the libraries section on the sidebar and open one of the libraries
3. Confirm it treats the folder as root

Feature: Treat libraries as root in Columns Layout

---

src/Files.App/UserControls/SideBar/SideBarItem.cs

- Fix animation being choppy, especially for single item sections
- Code cleanup
Closes #13245...
**Validation**

Fix Sidebar animation not being smooth when sections are sufficiently small

---

src/Files.App/Actions/Content/PreviewPopup/LaunchPreviewPopupAction.cs

Fix: Fixed NullReferenceException in LaunchPreviewPopupAction

---

src/Files.App/Utils/Git/GitHelpers.cs

Fix: Fixed crash when unable to connect to GitHub

---

src/Files.App/App.xaml.cs

This fixes the issue discussed in https://github.com/files-community/Files/pull/14115#discussion_r1421834603 where `LastOpenedFlyout` was not garbage collected.
**Validation**

Code Quality: Fixed issue where LastOpenedFlyout was not garbage collected

---

src/Files.App (Package)/Package.appxmanifest

Bumped version number for v3.1

Release: v3.1

---

src/Files.App/UserControls/Widgets/DrivesWidget.xaml.cs
src/Files.App/UserControls/Widgets/FileTagsWidget.xaml.cs
src/Files.App/UserControls/Widgets/HomePageWidget.cs
src/Files.App/UserControls/Widgets/QuickAccessWidget.xaml.cs
src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml.cs

Fix: Fixed issue where the properties window could not be opened on the home page

---

src/Files.App/Utils/Archives/DecompressHelper.cs

Fix: Fixed issue where smart extraction would not work correctly for one folder

---

src/Files.App/Helpers/MenuFlyout/ContextFlyoutItemHelper.cs
src/Files.App/Services/Settings/GeneralSettingsService.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/ViewModels/Settings/GeneralViewModel.cs
src/Files.App/Views/Settings/GeneralPage.xaml
src/Files.Core/Services/Settings/IGeneralSettingsService.cs

Closes #14389...
**Validation**
1. Open right click menu and confirm the menu options match the selected settings
2. Hide some of the context menu settings and confirm they still match

Feature: Added support for hiding more items from the context menu

---

src/Files.App/Views/Layouts/BaseLayoutPage.cs

I'm not able to repro, but I think this PR will fix the issue.
Closes #14074 
**Validation**

Fix: Fixed COMException with BaseLayoutPage.GetAllItems

---

src/Files.App/UserControls/Widgets/QuickAccessWidget.xaml.cs

LINQ operations are not thread-safe, so I made sure to make a copy of the list when performing LINQ operations.
Closes #13983 (Perhaps)
**Validation**

Fix: Fixed COMException in ItemsAdded_CollectionChanged

---

src/Files.App/Views/Layouts/GridLayoutPage.xaml.cs

Fix: Fixed issue where switching from Details to Tiles didn't reload thumbnails

---

src/Files.App/App.xaml.cs
src/Files.App/Helpers/Application/AppLifecycleHelper.cs

Related to #14309 
**Validation**

Code Quality: Faster background launch at Windows startup

---

src/Files.App/Helpers/UI/UIFilesystemHelpers.cs

Closes #5118...
**Validation**
1. Create new text file and confirm it's added to the recent items list

Feature: Add newly created items to Recent Files list

---

src/Files.App/Files.App.csproj
src/Files.Core.SourceGenerator/Files.Core.SourceGenerator.csproj
src/Files.Core/Files.Core.csproj

Dependabot doesn't seem to work due to a bug, so update the packages manually.
**Validation**

Code Quality: Update dependency packages

---

src/Files.App/ViewModels/Properties/Items/BaseProperties.cs

Closes #14487 
**Validation**
1. Right-click a pinned folder from the sidebar
2. Click on "Properties"

Fix: Fixed issue where modified date was missing from the properties window

---

src/Files.App/Utils/Storage/Collection/BulkConcurrentObservableCollection.cs

Code Quality: Fixed non-thread-safe code in BulkConcurrentObservableCollection.cs

---

src/Files.App/Utils/Storage/Collection/BulkConcurrentObservableCollection.cs

Code Quality: Fixed non-thread-safe code in BulkConcurrentObservableCollection.cs - part 2

---

src/Files.Shared/Helpers/FileExtensionHelpers.cs

Closes #14527 
**Validation**
1. Open app 
2. Navigate to file with .jfif extension
3. Right click, select set as wallpaper
4. Verify desktop wallpaper was set
5. Rotated both left and right, both work as expected

Feature: Added support for setting jfif files as the wallpaper

---

src/Files.App/Utils/Storage/Collection/BulkConcurrentObservableCollection.cs

Related to #14508 
Related to #14529 
**Validation**

Code Quality: Fixed non-thread-safe code in BulkConcurrentObservableCollection.cs - part 3

---

src/Files.App/UserControls/Pane/InfoPane.xaml
src/Files.App/UserControls/Pane/InfoPane.xaml.cs

Closes #13316...
**Validation**
1. Enable Details Pane
2. Select item with a tag
3. Click the tag in the Details Pane and confirm it starts a search for that tag

Feature: Added support for starting tag search from the Details Pane

---

src/Files.App/Data/Models/ItemViewModel.cs

Code Quality: Remove arg from LoadItemThumbnailAsync

---

src/Files.App/Data/Models/ItemViewModel.cs

Fixed issues where icons would keep refreshing while trying to load a cached thumbnail

Fix: Fixed issues where icons would keep refreshing

---

src/Files.App/Utils/Shell/Win32API.cs

Fixed issue where custom folder icons weren't loading
**Validation**
1. Set layout to grid view
2. Change the icon for a folder and confirm it's displayed in the grid view

Fix: Fixed issue where custom folder icons weren't loading

---

src/Files.App/Data/Models/ContextMenuFlyoutItemViewModelBuilder.cs
src/Files.App/Data/Models/OpacityIconModel.cs
src/Files.App/Helpers/MenuFlyout/ContextFlyoutItemHelper.cs
src/Files.App/Helpers/MenuFlyout/ShellContextMenuHelper.cs
src/Files.App/UserControls/Widgets/DrivesWidget.xaml.cs
src/Files.App/UserControls/Widgets/FileTagsWidget.xaml.cs
src/Files.App/UserControls/Widgets/QuickAccessWidget.xaml.cs
src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml.cs
src/Files.App/ViewModels/UserControls/SidebarViewModel.cs

Reverts files-community/Files#14603

Revert "Code Quality: Improved the way of instancing OpacityIconModel"

---

src/Files.App/Data/Models/ItemViewModel.cs

Related to #14573 
**Validation**

Code Quality: Improved loading speed of thumbnails - part 2

---

src/Files.App/Data/Models/ItemViewModel.cs

Revert "Fix: Fixed issue where the app could crash when adding items from external apps"

---

src/Files.App/Data/Models/ItemViewModel.cs
src/Files.App/Views/Layouts/BaseLayoutPage.cs
src/Files.App/Views/Layouts/ColumnLayoutPage.xaml.cs
src/Files.App/Views/Shells/BaseShellPage.cs
src/Files.App/Views/Shells/ModernShellPage.xaml.cs

Code Quality: Fixed non-thread-safe access to ItemViewModel.FilesAndFolders

---

src/Files.App/Views/Layouts/BaseLayoutPage.cs

Code Quality: Avoid generation of superfluous CollectionViewSource

---

src/Files.App/Views/MainPage.xaml.cs

Fixed COMException in LoadPaneChanged
`The WinUI Desktop Window object has already been closed`

Fix: Fixed COMException in LoadPaneChanged

---

src/Files.App/Services/SideloadUpdateService.cs

- Fixed FileLoadException when failing to update app
**Stacktrace**
```
WinRT.BaseActivationFactory
WinRT.BaseActivationFactory..ctor(String typeNamespace, String typeFullName)
WinRT.ActivationFactory`1
WinRT.ActivationFactory`1..cctor()
```

Fix: Fixed FileLoadException when failing to update app

---

src/Files.App/ViewModels/UserControls/InfoPaneViewModel.cs

Fix: Fixed issue where batch files couldn't be previewed inside archives

---

src/Files.App/Utils/Git/GitHelpers.cs

Code Quality: Improved error handling in RequireGitAuthenticationAsync

---

src/Files.App/Data/Models/ItemViewModel.cs

Closes #13456 
**Validation**
1. Do a search and rename one of the files
2. Check that the name is automatically updated

Fix: Fixed issue where file names wouldn't update in the search results page

---

src/Files.App/Data/Models/AppModel.cs

Code Quality: Use volatile for isMainWindowClosed

---

src/Files.App/Actions/Start/PinToStartAction.cs
src/Files.App/Actions/Start/UnpinFromStartAction.cs
src/Files.App/Data/Factories/ContentPageContextFlyoutFactory.cs
src/Files.App/Data/Items/ListedItem.cs

Closes #13738...
**Validation**
1. Right click shortcut targetting executable file
2. Confirmed the "short more options" menu displays option to "pin to start"
3. Confirmed the pinned item opens correctly
4. Confirmed the options aren't displayed for non-executable shortcuts

Feature: Added support for pinning executable shortcuts to start

---

src/Files.App (Package)/Package.appxmanifest

Release: v3.2

---

src/Files.App/Views/Layouts/BaseLayoutPage.cs

This reverts commit 826e00ecd3bdacb359dc4b1253f0186ba1cc9b2c.
Closes #14674 
**Validation**

Fix: Fixed issue where switching directory while renaming item wouldn't cancel rename

---

src/Files.App/Utils/Shell/ContextMenu.cs

Fix: Fixed ArgumentException in ContextMenu

---

src/Files.App/Files.App.csproj
tests/Files.InteractionTests/Files.InteractionTests.csproj

Code Quality: Update dependencies

---

.github/workflows/ci.yml

- Not to run the CI on fork repos
- Exclude some dirs
_None_
_None_

GitHub: Update CI

---

src/Files.App/Views/Shells/BaseShellPage.cs

Fix: Fixed NullReferenceException in DirectoryInfoUpdated

---

src/Files.App (Package)/Files.Package.wapproj
src/Files.App/Files.App.csproj
tests/Files.InteractionTests/Files.InteractionTests.csproj

Code Quality: Updated Windows App SDK to 1.4.5

---

src/Files.App (Package)/Package.appxmanifest

Release: v3.2.1

---

src/Files.App/Views/Shells/BaseShellPage.cs

https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/4293020710u/overview
**Validation**

Fix: Fixed crash that would occur when navigating folders continuously in a short period of time

---

src/Files.App/Helpers/UI/AppThemeResourcesHelper.cs
src/Files.App/ViewModels/Settings/AppearanceViewModel.cs

https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/1508523439u/overview
**Validation**

Fix: Fixed ArgumentException when wrong color was specified

---

src/Files.App (Package)/Package.appxmanifest

Release: v3.2.2

---

src/Files.App/Data/Items/DriveItem.cs
src/Files.App/Data/Items/SidebarLibraryItem.cs
src/Files.App/Data/Items/WidgetDriveCardItem.cs
src/Files.App/Data/Items/WidgetFolderCardItem.cs
src/Files.App/Data/Models/AppModel.cs
src/Files.App/Data/Models/ItemViewModel.cs
src/Files.App/Data/Models/SidebarPinnedModel.cs
src/Files.App/Helpers/Interop/InteropHelpers.cs
src/Files.App/Helpers/Navigation/NavigationHelpers.cs
src/Files.App/UserControls/Widgets/DrivesWidget.xaml
src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml
src/Files.App/Utils/Cloud/CloudDrivesManager.cs
src/Files.App/Utils/RecentItem/RecentItem.cs
src/Files.App/Utils/Storage/Helpers/FileThumbnailHelper.cs
src/Files.App/ViewModels/Properties/BasePropertiesPage.cs
src/Files.App/ViewModels/Properties/Items/DriveProperties.cs
src/Files.App/ViewModels/Properties/Items/FileProperties.cs
src/Files.App/ViewModels/Properties/Items/FolderProperties.cs
src/Files.App/ViewModels/Properties/Items/LibraryProperties.cs
src/Files.App/ViewModels/UserControls/Previews/BasePreviewModel.cs
src/Files.App/ViewModels/UserControls/Previews/FolderPreviewViewModel.cs
src/Files.App/ViewModels/UserControls/Previews/ShortcutPreviewViewModel.cs

Closes #14772
Closes #14499
**Validation**

Fix: Use correct DPI settings when requesting icons

---

src/Files.App/Utils/Git/GitHelpers.cs

https://appcenter.ms/orgs/FilesApp/apps/Files/crashes/errors/3810949528u/overview
**Validation**

Fix: Fixed SocketException in GitHelpers.RequireGitAuthenticationAsync

---

src/Files.App/UserControls/TabBar/BaseTabBar.cs

Fix: Fixed NullReferenceException in CloseTab

---

src/Files.App/Helpers/ShareItemHelpers.cs

Fix: Fixed NullReferenceException in ShareItemsAsync

---

src/Files.App (Package)/Files.Package.wapproj
src/Files.App (Package)/Package.appinstaller

Sideload: Disable update prompt

---

src/Files.App/Views/Layouts/GridLayoutPage.xaml
src/Files.App/Views/Layouts/GridLayoutPage.xaml.cs

Fix: Fixed issue where item selection couldn't work properly in List layout

---

.github/ISSUE_TEMPLATE/config.yml

As the title. For someone show wants to question or join our discussion.
_None_
_None_

GitHub: Added Discord link to New Issue

---

src/Files.App/Utils/Storage/Operations/ShellFilesystemOperations.cs

Closes #13898 
Closes #14216  
**Validation**

Fix: Fixed issue where copy and paste out of archive file didn't work

---

src/Files.App/Utils/Cloud/CloudDriveSyncStatusUI.cs

Fix: Fixed issue where hashes weren't able to calculate

---

src/Files.App/Actions/Display/LayoutAction.cs
src/Files.App/ResourceDictionaries/PathIcons.xaml
src/Files.App/UserControls/InnerNavigationToolbar.xaml

For #10492
**Validation**
1. Confirm the toolbar icon displays for each layout

Feature: Updated layout icons in the toolbar

---

src/Files.App/UserControls/Widgets/DrivesWidget.xaml.cs
src/Files.App/UserControls/Widgets/FileTagsWidget.xaml.cs
src/Files.App/UserControls/Widgets/QuickAccessWidget.xaml.cs
src/Files.App/ViewModels/UserControls/SidebarViewModel.cs

I've missed. Sorry!
Closes #issue
_None_
_None_

Fix: Fixed an issue where pin/unpin string is not shown

---

src/Files.App/Data/Factories/ShellContextFlyoutHelper.cs
src/Files.App/UserControls/Widgets/FileTagsWidget.xaml.cs
src/Files.App/UserControls/Widgets/RecentFilesWidget.xaml.cs

Fix: Fixed issue where Open with and Send to submenus didn't appear properly in Widgets

---

src/Files.App/ViewModels/Layouts/BaseLayoutViewModel.cs

Closes #14125 
Closes #14636 
**Validation**

Fix: Fixed issue where items couldn't be dropped from 7-zip

---

src/Files.App (Package)/Package.appxmanifest

Release: v3.3

---

src/Files.App/Data/Items/WidgetDriveCardItem.cs
src/Files.App/Data/Items/WidgetFolderCardItem.cs
src/Files.App/Data/Models/ItemViewModel.cs
src/Files.App/Data/Models/PinnedFoldersManager.cs

**Validation**
1. Opened app
2. Confirmed thumbnails loaded properly in sidebar

Code Quality: Increase thread priority for thumbnails

---

src/Files.App/Views/Shells/BaseShellPage.cs

Fix: Fixed issue where "Scroll to previous folder" didn't work on some locations

---

src/Files.App/Utils/Storage/Helpers/StorageFileExtensions.cs

Fix: Fixed issue where ftp addresses were not displayed in the path bar

---

src/Files.App/ViewModels/UserControls/InfoPaneViewModel.cs

Closes #15055 
**Validation**
1. See video
Dark mode - Current Preview (3.3)
Light mode - Version of this PR
https://github.com/files-community/Files/assets/56681014/71782022-f7de-4cd0-b15d-e244dc68e9ea

Fixed: Fixed issue where holding the arrow key would cause preview pane to freeze

---

.github/README.md
src/Files.App (Package)/Files.Package.wapproj
src/Files.App/Files.App.csproj
tests/Files.InteractionTests/Files.InteractionTests.csproj

Code Quality: Updated Windows App SDK and others

---

src/Files.App/ViewModels/MainPageViewModel.cs

Fix: Fixed issue where open tabs were duplicated when opening a folder from the outside of Files

---

src/Files.App/ViewModels/UserControls/AddressToolbarViewModel.cs

Fix: Fixed possible crash when entering characters into path bar

---

src/Files.App.Server/Program.cs

This adds exception log for Files.App.Server, which can help us to identify issues happening on the server.
A log example:
```
2024/04/15 20:59:00|System.Exception: Exception of type 'System.Exception' was thrown.
at Files.App.Server.AppInstanceMonitor.StartMonitor(Int32 processId)
```

Code Quality: Add exception log for server

---

src/Files.App/Data/Models/CurrentInstanceViewModel.cs
src/Files.App/Views/HomePage.xaml.cs
src/Files.App/Views/Shells/BaseShellPage.cs

Fix: Fixed issue where Git submenu was shown for non-GitHub repos

---

src/Files.App/Utils/Global/QuickAccessManager.cs

Fix: Fixed issue where Recycle Bin wasn't pinned by default

---

src/Files.App/Data/Items/ListedItem.cs

Code Quality: Fixed the way tags were initialized

---

src/Files.App/Data/Items/WidgetFileTagsContainerItem.cs

Fix: Fixed issue where View more and Open all in Tags widget were disabled

---

src/Files.App/MainWindow.xaml.cs
src/Files.App/NativeMethods.txt

Closes #15234
Restore window if on launch the existing instance is minimized.
**Validation**

Fix: Fixed an issue where the window wasn't refocused if minimized on launch

---

src/Files.App/Data/Models/ItemManipulationModel.cs
src/Files.App/Views/Layouts/BaseGroupableLayoutPage.cs
src/Files.App/Views/Layouts/ColumnLayoutPage.xaml.cs
src/Files.App/Views/Layouts/DetailsLayoutPage.xaml.cs
src/Files.App/Views/Layouts/GridLayoutPage.xaml.cs
src/Files.App/Views/Shells/BaseShellPage.cs

Closes #5825 
**Validation**
Try steps described in #15279. Now it should work as expected.

Fix: Fixed issue where scroll position wasn't always in the correct position

---

src/Files.App (Package)/Files.Package.wapproj
src/Files.App/Files.App.csproj

Code Quality: Update WindowsAppSDK and Vanara

---

src/Files.App/Files.App.csproj
src/Files.App/UserControls/TabBar/TabBar.xaml.cs
src/Files.App/Utils/Storage/Helpers/FilePropertiesHelpers.cs
src/Files.App/Utils/Taskbar/SystemTrayIcon.cs

Looks like we're referencing an old CsWin32 version. This PR updates it.

Code Quality: Update CsWin32 to latest version

---

src/Files.App/ViewModels/Settings/AppearanceViewModel.cs

Code Quality: Fix horizontal alignment labels

---

src/Files.App/Helpers/Layout/LayoutPreferencesManager.cs

Code Quality: Ignore exceptions to return default layout preferences in GetLayoutPreferencesForPath

---

src/Files.App/Actions/Content/Background/SetAsAppBackgroundAction.cs
src/Files.App/Data/Commands/Manager/CommandCodes.cs
src/Files.App/Data/Commands/Manager/CommandManager.cs
src/Files.App/Data/Commands/Manager/ICommandManager.cs
src/Files.App/Data/Factories/ContentPageContextFlyoutFactory.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/UserControls/InnerNavigationToolbar.xaml

Closes #15313...
**Validation**
1. Confirmed the "Set as app background" option is visible in the toolbar (for images)
2. Confirmed the "Set as app background" option is visible in the context menu (for images)
3. Confirmed the action sets the app background
**Documentation**
- Added this action to the website repo (to be published when v3.4 goes live)
- Added a screenshot to Crowdin

Feature: Added set as app background action

---

src/Files.App/Helpers/Layout/LayoutPreferencesManager.cs

```
WinRT
ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0 (Int32 hr)
ABI.Files.App.Server.Database
ILayoutPreferencesDatabaseClassMethods.GetPreferences (IObjectReference _obj, String filePath, Nullable`1 frn)
Files.App.Data.Models
LayoutPreferencesManager.SetLayoutPreferencesToDatabase (String path, Nullable`1 frn, LayoutPreferencesItem preferencesItem)
Files.App.Data.Models
LayoutPreferencesManager.SetLayoutPreferencesForPath (String path, LayoutPreferencesItem preferencesItem)
Files.App.Views.Shells
ModernShellPage.FolderSettings_LayoutPreferencesUpdateRequired (Object sender, LayoutPreferenceEventArgs e)
Files.App.Data.Models
LayoutPreferencesManager.set_DirectorySortOption (SortOption value)
Files.App.Views.Layouts
DetailsLayoutPage.<ctor>b__23_0 (String x) …
```

Fix: Fixed COMException in LayoutPreferencesManager.SetLayoutPreferencesForPath

---

src/Files.App/ViewModels/Settings/AppearanceViewModel.cs

As the title.
https://discordapp.com/channels/725513575971684472/1070771912797597917/1236967189815230538
_None_
_None_

Fix: Fixed an issue where "Custom" wasn't localized in the settings appearance page

---

src/Files.App/Helpers/Layout/LayoutPreferencesManager.cs

Reverts files-community/Files#15314

Revert "Code Quality: Ignore exceptions to return default layout preferences in GetLayoutPreferencesForPath"

---

src/Files.App/Helpers/Layout/LayoutPreferencesManager.cs

Reverts files-community/Files#15321

Revert "Fix: Fixed COMException in LayoutPreferencesManager.SetLayoutPreferencesForPath"

---

src/Files.App/ViewModels/Settings/AppearanceViewModel.cs
src/Files.Shared/Helpers/FileExtensionHelpers.cs

1. Opened Appearance settings page
2. Click browse button to choose image
3. Confirm tiff and tif are in the list of files

Feature: Added support for setting tif files as the Background Image

---

src/Files.Shared/Helpers/FileExtensionHelpers.cs

- Closes #15365
1. Select multiple `.mkv` extension files
2. See play all on the toolbar

Feature: Added toolbar button to play mkv files

---

src/Files.App/Utils/Global/WindowsStorageDeviceWatcher.cs

- Closes #15317
Added handling of the COMExtception listed in the debug log.
2. ...

Fix: Fixed crash when connecting some removable drives

---

src/Files.App/Files.App.csproj
src/Files.App/NativeMethods.txt
src/Files.App/ViewModels/UserControls/Previews/ShellPreviewViewModel.cs

- Closes #
@0x5bfa turns out it's possible :)
1. Test preview pane with different extensions

Code Quality: Switch DirectN to CsWin32

---

src/Files.App/UserControls/StatusBar.xaml
src/Files.App/UserControls/StatusBar.xaml.cs
src/Files.App/ViewModels/UserControls/StatusBarViewModel.cs
src/Files.App/Views/Layouts/BaseLayoutPage.cs
src/Files.App/Views/Layouts/IBaseLayoutPage.cs
src/Files.App/Views/MainPage.xaml.cs
src/Files.App/Views/Shells/BaseShellPage.cs

- Reanmed the view model
- Formatted codebase around it
_None_
_None_

Code Quality: Renamed DirectoryPropertiesViewModel to StatusBarViewModel

---

src/Files.App/Data/Enums/OpenInIDEOption.cs
src/Files.App/Data/Enums/SettingsPageKind.cs
src/Files.App/Data/Models/DirectoryPropertiesViewModel.cs
src/Files.App/Dialogs/SettingsDialog.xaml
src/Files.App/Dialogs/SettingsDialog.xaml.cs
src/Files.App/Helpers/Application/AppLifecycleHelper.cs
src/Files.App/Services/Settings/DevToolsSettingsService.cs
src/Files.App/Services/Settings/IDevToolsSettingsService.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/UserControls/StatusBar.xaml
src/Files.App/UserControls/StatusBar.xaml.cs
src/Files.App/ViewModels/Settings/DevToolsViewModel.cs
src/Files.App/Views/HomePage.xaml.cs
src/Files.App/Views/Layouts/BaseLayoutPage.cs
src/Files.App/Views/Layouts/IBaseLayoutPage.cs
src/Files.App/Views/MainPage.xaml.cs
src/Files.App/Views/Settings/DevToolsPage.xaml
src/Files.App/Views/Settings/DevToolsPage.xaml.cs
src/Files.App/Views/Shells/BaseShellPage.cs
tests/Files.InteractionTests/Tests/SettingsTests.cs

- Related to #12857
1. Confirmed the "Open" button on the status bar is shown correctly based on the selected setting
2. Confirmed the "Open repo" option only shows for Git repos
3. Confirmed the status bar design and margins are the same as `main`

Feature: Added a setting to configure the "Open in ide" button on the status bar

---

src/Files.App/Views/Layouts/ColumnLayoutPage.xaml
src/Files.App/Views/Layouts/DetailsLayoutPage.xaml
src/Files.App/Views/Layouts/GridLayoutPage.xaml

- Closes #15182
2. Go to cloud drive folder
3. Hover on

Feature: Added a tooltip when hovering over OneDrive status icons

---

src/Files.App/Actions/Content/Run/BaseRunAsAction.cs
src/Files.App/Actions/Content/Run/RunAsAdminAction.cs
src/Files.App/Actions/Content/Run/RunAsAnotherUserAction.cs
src/Files.Shared/Helpers/FileExtensionHelpers.cs

Code Quality: Disable run as user for AHK files

---

src/Files.App/Actions/Content/Run/RunAsAdminAction.cs
src/Files.App/Actions/Content/Run/RunAsAnotherUserAction.cs
src/Files.App/Actions/FileSystem/CreateFolderWithSelectionAction.cs
src/Files.App/Actions/Open/EditInNotepadAction.cs
src/Files.App/Data/Factories/ContentPageContextFlyoutFactory.cs
src/Files.Shared/Helpers/FileExtensionHelpers.cs

- Closes #15412
1. Right clicked batch file and confirmed the "Edit in notepad" option is displayed on the main page
**Notes**
The sub menu still displays the "Edit in notepad" shell extension. We could filter it out but that'll require some more changes and it's out of scope for this PR.

Feature: Added "Edit in notepad" action to the right click context menu

---

src/Files.App/Services/Settings/GeneralSettingsService.cs
src/Files.App/ViewModels/HomeViewModel.cs

This enables but hides Network locations widget by default.
Also, this fixes the issue where the widget is added at the bottom when adding regardless of the widget kind.
- Closes #
2. ...

Code Quality: Changed default settings for Network locations widget

---

src/Files.App/UserControls/SideBar/SideBarView.xaml
src/Files.App/Views/MainPage.xaml

- In case we decide to support #9348

Code Quality: Moved toolbar background to MainPage

---

src/Files.App/App.xaml
src/Files.App/Data/Contracts/IResourcesService.cs
src/Files.App/Helpers/UI/AppThemeResourcesHelper.cs
src/Files.App/Services/ResourcesService.cs
src/Files.App/Services/Settings/AppearanceSettingsService.cs
src/Files.App/Services/Settings/IAppearanceSettingsService.cs
src/Files.App/UserControls/SideBar/SideBarView.properties.cs
src/Files.App/UserControls/SideBar/SideBarView.xaml
src/Files.App/UserControls/SideBar/SideBarView.xaml.cs
src/Files.App/Views/MainPage.xaml
src/Files.App/Views/MainPage.xaml.cs

- Closes #
- Preview Pane resizing has been verified.
- Dark mode and various backdrops have been tested.
- The visual states have been confirmed to function properly in small window sizes.

Feature: Updated the design of the Preview Pane

---

src/Files.App/ViewModels/Settings/AdvancedViewModel.cs

I had checked only availablity of the common dialog but hadn't check if settings are saved or not. Sorry!
Now it successfully exports/imports.
- Closes #15465
2. Export settings
3. Import setting

Fix: Fixed an issue where import/export settings didn't work

---

src/Files.App/UserControls/Pane/InfoPane.xaml
src/Files.App/Views/Layouts/ColumnLayoutPage.xaml

Fix: Fixed Column View chevron color in high contrast

---

src/Files.App/Dialogs/SettingsDialog.xaml
src/Files.App/Styles/PathIcons.xaml
src/Files.App/UserControls/AddressToolbar.xaml
src/Files.App/UserControls/InnerNavigationToolbar.xaml
src/Files.App/UserControls/Settings/SettingsDisplayControl.xaml

Code Quality: Update default base and alt brushes

---

src/Files.App/App.xaml.cs
src/Files.App/Files.App.csproj
src/Files.App/Helpers/Application/AppLifecycleHelper.cs
src/Files.App/Helpers/Application/AppToastNotificationHelper.cs
src/Files.App/Helpers/NotificationHelpers.cs
src/Files.App/Helpers/UI/UIHelpers.cs

- Closes #15528
2. Closed window with background enabled
3. Intentionally crashed the app
4. Ejected a drive

Code Quality: Replace Community Toolkit notifications with WinAppSdk

---

src/Files.App/Extensions/MessageFormatExtensions.cs

- From #15508
- Closes #15554
Test with C:/Windows/System32

Code Quality: Disabling cache in MessageFormat

---

src/Files.App/UserControls/SideBar/SideBarControls.xaml
src/Files.App/UserControls/SideBar/SideBarItem.cs
src/Files.App/UserControls/SideBar/SideBarView.xaml
src/Files.App/UserControls/SideBar/SideBarView.xaml.cs

Internal
2. Try as many states as possible (ItemCollapse, PaneCollapse, Minimal, etc)

Code Quality: Fixed Sidebar alignment

---

src/Files.App/Helpers/UI/AppSystemBackdrop.cs

Fix: Fixed potential crash on startup

---

src/Files.App/Data/Items/ShellLibraryItem.cs
src/Files.App/Helpers/Win32/Win32PInvoke.Methods.cs
src/Files.App/Utils/Library/LibraryManager.cs

- Closes https://files-org.sentry.io/issues/5472102996/events/dd9fe91b32134e1eaaae5fe6a1375e0d/
NA

Fix: Fixed crash that could occur if the Libraries folder wasn't located

---

src/Files.App/Data/Models/DirectoryPropertiesViewModel.cs

Fix: Fixed NullReferenceException in StatusBarViewModel.UpdateGitInfo

---

src/Files.App/Utils/Git/GitHelpers.cs

Fix: Fixed HttpRequestException in GitHelpers.RequireGitAuthenticationAsync

---

src/Files.App/Helpers/Application/AppLifecycleHelper.cs
src/Files.App/Utils/Logger/SentryLogger.cs
src/Files.App/Utils/Logger/SentryLoggerProvider.cs
src/Files.App/ViewModels/UserControls/InfoPaneViewModel.cs
src/Files.App/Views/MainPage.xaml.cs

Code Quality: Added a logger to send exception reports to Sentry

---

src/Files.App/Views/Layouts/ColumnLayoutPage.xaml
src/Files.App/Views/Layouts/DetailsLayoutPage.xaml
src/Files.App/Views/Layouts/GridLayoutPage.xaml

- Closes #
1. Open OneDrive location
2. Hover over status (Eg. check icon) and confirm the tooltip is displayed even when hovered directly over the icon
3. Confirm this behavior in every layout

Code Quality: Wrap sync icon in border

---

src/Files.App/Data/Items/ListedItem.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/Views/Layouts/DetailsLayoutPage.xaml

- Closes #15610 
2. Hover over an image file
3. Hover over a file stored in the cloud

Code Quality: Formatting Issue with Dimensions and Synchronization Labels

---

src/Files.App/Utils/Global/WallpaperHelpers.cs

- Closes #15568
1. Confirmed it works on a single display
2. We need to test on multiple displays

Fix: Fixed an issue where setting the desktop wallpaper didn't work on multiple monitors

---

src/Files.App/Helpers/Application/AppLifecycleHelper.cs
src/Files.App/Utils/Logger/SentryLogger.cs

Code Quality: Fixed capturing exceptions by Sentry

---

src/Files.App/Views/ShellPanesPage.xaml.cs

- Closes https://files-org.sentry.io/issues/5509702937/events/15ad9c8f52f94d0187dae68525f58508/
2. ...

Code Quality: Fixed COMException with WinUI Desktop Window

---

src/Files.App/Utils/Storage/Operations/FileOperationsHelpers.cs

- Closes #15518
1. Check that deletion from a zip file works

Fix: Fixed an issue with deleting items from zip files

---

src/Files.App/Utils/Storage/Operations/FileOperationsHelpers.cs

Fix: Fixed an issue where changing icons didn't work when admin access was required

---

src/Files.App/Utils/FileTags/FileTagsDatabase.cs

This prevents crashes due to the exception, but the tags feature doesn't work properly in that case.
It may be better to define the registry key statically instead of using `Package.Current`, though migration is required.
- Closes #15601 
2. ...

Fix: Fixed System.TypeInitializationException in FileTagsDatabase

---

src/Files.App/Actions/Show/ToggleToolbarAction.cs
src/Files.App/Data/Commands/Manager/CommandCodes.cs
src/Files.App/Data/Commands/Manager/CommandManager.cs
src/Files.App/Data/Commands/Manager/ICommandManager.cs
src/Files.App/Strings/en-US/Resources.resw

- Closes #15651
1. Used `ctrl` + `shift` + `b` shortcut to toggle toolbar on and off

Feature: Added `ctrl` + `shift` + `b` shortcut to toggle the toolbar

---

src/Files.App/Utils/Global/WSLDistroManager.cs

Fix: Fixed a WSL popup from displaying on startup

---

src/Files.App/Services/App/AppUpdateStoreService.cs

- https://files-org.sentry.io/issues/5528766149/events/79d6ba6b53e647aab5576e02105c02a7/
2. ...

Fix: Fixed crash that could occur when checking for updates

---

src/Files.App/Services/Windows/WindowsJumpListService.cs

- https://files-org.sentry.io/issues/5461933781/events/298838d246a84ccda2706468c3fba438
2. ...

Fix: Fixed crash that could occur when adding items to the jumplist

---

src/Files.App/UserControls/TabBar/TabBar.xaml.cs
src/Files.App/Views/Layouts/BaseLayoutPage.cs

- Closes #15200
1. Hover item over folder
2. Confirm the folder doesn't open right away

Fix: Fixed an issue where hover to open was too sensitive

---

src/Files.App/Helpers/Application/AppLifecycleHelper.cs

Fix: Fixed ArgumentNullException in AppLifecycleHelper.HandleAppUnhandledException

---

src/Files.App/Data/Models/AppModel.cs
src/Files.App/Views/Layouts/BaseGroupableLayoutPage.cs
src/Files.App/Views/Shells/BaseShellPage.cs

- https://files-org.sentry.io/issues/5463612608/events/79a0bb9c84c54f7e8ad055f904d061af/
2. ...

Fix: Fixed COMException when renaming files

---

src/Files.App/Utils/CommandLine/ParsedCommand.cs

Fix: Fixed crash that would occur when entering invalid parameters via command line

---

src/Files.App/ViewModels/ShellViewModel.cs

Fix: Fixed an issue where quick search filtering wasn't cleared when navigating to another folder

---

src/Files.App/ViewModels/Settings/AdvancedViewModel.cs

- Closes #15737
2. Export as `A`
3. A.zip will be produced

Fix: Fixed an issue where settings weren't exported in the correct format

---

src/Files.App/Services/App/AppUpdateSideloadService.cs

- Closes https://files-org.sentry.io/issues/5553355845/events/5f92b7534ed84cdcbea397aa9be3b55a/
2. ...

Fix: Fixed potential crash that could occur when updating Files

---

src/Files.App/Helpers/PathNormalization.cs

Fix: Fixed ArgumentException in PathNormalization.NormalizePath

---

src/Files.App/Services/Windows/WindowsIniService.cs

- https://files-org.sentry.io/issues/5607198096/events/825bbc12a01b4d2887d72ff542cb49bd

Code Quality: Fixed FileNotFoundException in WindowsIniService

---

src/Files.App.Launcher/FilesLauncher.cpp
src/Files.App.OpenDialog/FilesOpenDialog.cpp
src/Files.App.SaveDialog/FilesSaveDialog.cpp
src/Files.App/Data/Items/DriveItem.cs
src/Files.App/Dialogs/CreateShortcutDialog.xaml
src/Files.App/Services/Storage/StorageDevicesService.cs
src/Files.App/Utils/Cloud/Detector/LucidLinkCloudDetector.cs
src/Files.App/Utils/Shell/ContextMenu.cs
src/Files.App/Utils/Storage/Helpers/StorageSenseHelper.cs
src/Files.App/ViewModels/Dialogs/CreateShortcutDialogViewModel.cs
src/Files.App/ViewModels/Properties/BasePropertiesPage.cs
tests/Files.InteractionTests/SessionManager.cs

Code Quality: Use `%SYSTEMDRIVE%` environment variable instead of `C:`

---

src/Files.App/Data/Models/PinnedFoldersManager.cs
src/Files.App/Services/Windows/WindowsJumpListService.cs
src/Files.App/Utils/Global/QuickAccessManager.cs

This may also fix #14555.
- Closes #
2. ...

Fix: Fixed ArgumentException in PinnedFoldersManager

---

src/Files.App/Files.App.csproj
src/Files.App/Utils/Storage/Operations/FileOperationsHelpers.cs

Code Quality: Reverted Vanara

---

src/Files.App/Actions/Display/LayoutAction.cs

- Closes #15836 
1. Set the layout to Adaptive.
2. Hold down Ctrl and turn the mouse wheel.
3. See the layout size is changing.

Fix: Fixed an issue where changing the layout size wouldn't work in the adaptive layout

---

src/Files.App/Files.App.csproj
src/Files.Shared/Files.Shared.csproj
tests/Files.InteractionTests/Files.InteractionTests.csproj

I don't think these are the cause of the crash.
- Closes #
2. ...

Code Quality: Update dependencies - part 1

---

src/Files.App/Actions/Start/PinToStartAction.cs
src/Files.App/Actions/Start/UnpinFromStartAction.cs

Code Quality: Follow up for Fixed DirectoryNotFoundException when pinning items

---

src/Files.App/Views/Shells/BaseShellPage.cs

- For https://files-org.sentry.io/issues/5453730063/events/9b36f9e4a9b847b690de7ee22a6e865b/
2. ...

Code Quality: Added extra protection when navigating pages

---

src/Files.App/MainWindow.xaml.cs

Code Quality: Ensure content before setting backdrop

---

src/Files.App/Helpers/UI/UIHelpers.cs

Fix: Fixed TypeInitializationException in UIHelpers

---

src/Files.App/Utils/Storage/Collection/SortingHelper.cs

Fix: Fixed ArgumentNullException in SortingHelper.OrderFileList

---

src/Files.App/Services/Settings/FileTagsSettingsService.cs
src/Files.App/Services/Settings/UserSettingsService.cs

Fix: Fixed ArgumentNullException in DefaultSettingsSerializer.ReadFromFile

---

src/Files.App.BackgroundTasks/Files.App.BackgroundTasks.csproj
src/Files.App.Controls/Files.App.Controls.csproj
src/Files.App.Server/Files.App.Server.csproj
src/Files.App/Files.App.csproj
tests/Files.App.UITests/Files.App.UITests.csproj

Code Quality: Update dependencies except for Windows App SDK

---

src/Files.App/Helpers/Navigation/NavigationHelpers.cs

Fix: Fixed an issue where the tab title was empty when opening a folder in a new tab

---

src/Files.App/UserControls/AddressToolbar.xaml
src/Files.App/Views/MainPage.xaml.cs

Code Quality: Follow up for #15876

---

src/Files.App.BackgroundTasks/Files.App.BackgroundTasks.csproj
src/Files.App.Server/Files.App.Server.csproj
src/Files.App/Files.App.csproj

Code Quality: Reverted CsWinRT update

---

src/Files.App/Data/Items/DriveItem.cs

Fix: Fixed NullReferenceException in DriveItem.LoadThumbnailAsync

---

src/Files.App/Utils/Logger/SentryLogger.cs

Code Quality: Filter out LogLevel.Information

---

src/Files.App/ViewModels/ShellViewModel.cs

Prevent crash and log error when creating URI from FolderBackgroundImageSource

Code Quality: Log errors when setting FolderBackgroundImageSource

---

src/Files.App/Utils/Taskbar/SystemTrayIcon.cs

Fix: Fixed NullReferenceException in SystemTrayIcon.OnQuitClicked

---

.github/NOTICE.md
src/Files.App/NativeMethods.txt
src/Files.App/Services/PreviewPopupProviders/SeerProProvider.cs
src/Files.App/ViewModels/Settings/AboutViewModel.cs

As the title.
- https://github.com/files-community/Files/issues/15000
1. Install SeerPro
2. Launch it from Start and check if it's now in system tray
3. Launch Files
4. Select an image file
5. Enter <kbd>Space</kbd>
6. See SeerPro preview launches and the image is shown
Messaging is doing well:

Code Quality: Removed Vanara from SeerProProvider class

---

src/Files.App/Services/PreviewPopupProviders/SeerProProvider.cs

- Follow up for #15912 
_None_

Code Quality: Removed unnecessary using of Vanara

---

src/Files.App/Services/App/AppUpdateSideloadService.cs

Fix: Fixed InvalidOperationException in SideloadUpdateService.CheckForUpdatesAsync

---

src/Files.App/Data/Items/LocationItem.cs

https://files-org.sentry.io/issues/5461186594/?project=4507376940351488
- Closes #
2. ...

Fix: Fixed NullReferenceException in RecycleBinLocationItem.RefreshSpaceUsed

---

src/Files.App/MainWindow.xaml.cs

https://files-org.sentry.io/issues/5653153316/?project=4507376940351488
- Closes #
2. ...

Fix: Fixed COMException in MainWindow.EnsureWindowIsInitialized

---

.github/workflows/format-xaml.yml

Now that this command will run in Files.App, Files.App.Controls and Files.App.UITests
1. Run '/format' after we merged this.

Code Quality: Update format action to include missing projects

---

src/Files.App/Views/ShellPanesPage.xaml.cs

- Closes https://files-org.sentry.io/issues/5671317297/events/a55b72bbbea3484fa3d94e9c08a89378/
2. ...

Code Quality: Handle COMException in ShellPanesPage

---

src/Files.App/Utils/Storage/Operations/FilesystemHelpers.cs

Fix: Fixed COMException in SidebarItem.ItemGrid_Drop

---

src/Files.App/ViewModels/UserControls/SidebarViewModel.cs

This may fix #15945 and #15950.
- Closes #
2. ...

Code Quality: Fixed an issue where CollectionChanged events were not unsubscribed correctly

---

src/Files.App/Helpers/Application/AppLifecycleHelper.cs

This would prevent the exception described in #15657.
- Closes #
2. ...

Code Quality: Ignore exceptions in AppLifecycleHelper.HandleAppUnhandledException

---

src/Files.App/Styles/SidebarStyles.xaml
src/Files.App/UserControls/Sidebar/SidebarItem.cs

- Removed spacing from between sidebar items and added a margin instead.

Code Quality: Remove spacing from SidebarItems

---

src/Files.App/App.xaml.cs
src/Files.App/Data/Contracts/IGeneralSettingsService.cs
src/Files.App/Helpers/Application/AppLifecycleHelper.cs
src/Files.App/Services/Settings/GeneralSettingsService.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/Utils/Taskbar/SystemTrayIcon.cs
src/Files.App/ViewModels/Settings/AdvancedViewModel.cs
src/Files.App/Views/Settings/AdvancedPage.xaml

- Closes #15907
1. Confirmed that changing the setting updates the icon visibility
2. Confirmed the setting persists across sessions

Feature: Added a setting to hide the System Tray icon

---

src/Files.App/Actions/Open/OpenTerminalAction.cs
src/Files.App/Actions/Open/OpenTerminalFromHomeAction.cs
src/Files.App/Actions/Open/OpenTerminalFromSidebarAction.cs
src/Files.App/Data/Commands/Manager/CommandCodes.cs
src/Files.App/Data/Commands/Manager/CommandManager.cs
src/Files.App/Data/Commands/Manager/ICommandManager.cs
src/Files.App/Data/Factories/ContentPageContextFlyoutFactory.cs
src/Files.App/Data/Factories/ShellContextFlyoutHelper.cs
src/Files.App/ViewModels/UserControls/SidebarViewModel.cs
src/Files.App/ViewModels/UserControls/Widgets/DrivesWidgetViewModel.cs
src/Files.App/ViewModels/UserControls/Widgets/FileTagsWidgetViewModel.cs
src/Files.App/ViewModels/UserControls/Widgets/QuickAccessWidgetViewModel.cs

Feature: Added Terminal action to context menu

---

src/Files.App/Data/Factories/ContentPageContextFlyoutFactory.cs

- Closes #15969
1. Confirmed "Close pane" is only shown when right clicking the folder
2. Confirmed option is only shown when dual pane is active

Feature: Added option to close active pane from the right click context menu

---

src/Files.App/ViewModels/Layouts/BaseLayoutViewModel.cs

- Closes #16014
1. Confirmed the icon size is correctly changed when scrolling up & down

Fix: Corrected inverted scrolling behavior for icon size adjustment

---

src/Files.App/MainWindow.xaml.cs

- Closes #6925
1. Set Files as default file manager
2. Confirmed opening path from external location focuses on existing tabs
3. Confirmed opening path from external location adds a new tab if needed

Feature: Focus existing tab when opening location from external process

---

src/Files.Shared/Extensions/SafetyExtensions.cs

This is a follow up to #15958.
- Closes #
2. ...

Code Quality: Ignore exceptions in AppLifecycleHelper.HandleAppUnhandledException - part 2

---

src/Files.App/UserControls/PathBreadcrumb.xaml
src/Files.App/ViewModels/UserControls/AddressToolbarViewModel.cs

- Closes #15061
1. Opened Files 
2. Expanded breadcrumb flyout
3. Confirmed the thumbnails are properly displayed
**Screenshot**

Feature: Improved breadcrumb flyout with folder thumbnails

---

src/Files.App/Utils/Storage/Operations/FileOperationsHelpers.cs

Fix: Fixed an issue where a shortcut to a folder couldn't be created

---

src/Files.App/App.xaml
src/Files.App/Styles/MenuFlyoutSubItemWithImageStyle.xaml
src/Files.App/UserControls/Menus/MenuFlyoutItemWithImage.xaml
src/Files.App/UserControls/Menus/MenuFlyoutItemWithThemedIcon.xaml
src/Files.App/UserControls/Menus/ToggleMenuFlyoutItemWithThemedIcon.xaml

- Closes #12026
1. Set custom font
2. Confirmed menu items use the correct font

Fix: Fixed an issue where context menus didn't follow the custom font setting

---

src/Files.App/Utils/Storage/Helpers/FilePropertiesHelpers.cs

Code Quality: Properly scale properties window

---

src/Files.App/Helpers/Layout/LayoutPreferencesDatabase.cs
src/Files.App/Utils/FileTags/FileTagsDatabase.cs

- Closes #15797
1. Confirmed the registry path no longer contains the version number

Fix: Fixed an issue where layout setting didn't persist across updates

---

src/Files.App/Utils/Storage/Operations/FilesystemHelpers.cs

- Closes #15105 
- Closes #16026 
2. ...

Fix: Fixed COMException when drag-and-dropping items

---

src/Files.App (Package)/Package.appxmanifest
src/Files.App/Helpers/UI/UIHelpers.cs

Code Quality: Added null check to UIHelpers.CloseAllDialogs

---

src/Files.App/Data/Items/WindowEx.cs

Code Quality: Potential fix for NullReferenceException in App.OnLaunched

---

src/Files.App/Helpers/Application/AppLifecycleHelper.cs
src/Files.Shared/Extensions/SafetyExtensions.cs

Code Quality: Revert "Ignore exceptions in AppLifecycleHelper.HandleAppUnhandledException"

---

src/Files.App/Helpers/Layout/AdaptiveLayoutHelpers.cs

- https://files-org.sentry.io/issues/5623019520/events/1b0d726aa08b42f0ab458561979378eb/
2. ...

Fix: Fixed null ref in AdaptiveLayoutHelpers

---

src/Files.App/Actions/Content/Archives/Compress/CompressIntoArchiveAction.cs
src/Files.App/Actions/Content/Archives/Compress/CompressIntoSevenZipAction.cs
src/Files.App/Actions/Content/Archives/Compress/CompressIntoZipAction.cs
src/Files.App/Data/Contracts/ICompressArchiveModel.cs
src/Files.App/Data/Models/CompressArchiveModel.cs
src/Files.App/Dialogs/CreateArchiveDialog.xaml
src/Files.App/Dialogs/CreateArchiveDialog.xaml.cs
src/Files.App/Strings/en-US/Resources.resw

Feature: Added thread selection option when creating archives

---

src/Files.App/Services/App/AppThemeModeService.cs

I can't reliably reproduce the issue, but I encountered this issue when debugging Files.

Code Quality: Fixed null ref in SetAppThemeMode

---

src/Files.App/Views/Shells/ModernShellPage.xaml.cs

Code Quality: Removed extra SuppressNavigationTransitionInfo

---

src/Files.App/App.xaml.cs
src/Files.App/Data/Items/WindowEx.cs
src/Files.App/Helpers/Application/AppLifecycleHelper.cs
src/Files.App/Helpers/UI/AppSystemBackdrop.cs

2. Close
3. Resume from the Taskbar icon
4. See SystemBackdrop is working normally without any further interactions

Code Quality: Fixed an issue where backdrop was not active when resuming from background

---

src/Files.App/Data/Items/ListedItem.cs
src/Files.App/ViewModels/UserControls/AddressToolbarViewModel.cs

- Closes #15892
- Closes #15886
1. Created folder ending in `zip` and a folder ending in `exe`
2. Confirmed they are treated as folders

Fix: Fixed an issue where folders with file extensions were sometimes treated as files

---

src/Files.App/Data/Items/DriveItem.cs
src/Files.App/Utils/Storage/Helpers/DriveHelpers.cs
src/Files.App/ViewModels/UserControls/AddressToolbarViewModel.cs
src/Files.App/ViewModels/UserControls/SidebarViewModel.cs
src/Files.App/ViewModels/UserControls/Widgets/DrivesWidgetViewModel.cs
src/Files.App/ViewModels/UserControls/Widgets/NetworkLocationsWidgetViewModel.cs

- Closes #10719
- Closes #15320
- Closes #11091
1. Confirmed the eject option works properly

Fix: Fixed an issue where ejecting drives would sometimes fail

---

src/Files.App/Data/Commands/ActionCommand.cs
src/Files.App/Files.App.csproj
src/Files.App/Utils/Git/GitHelpers.cs
src/Files.Core.SourceGenerator/Files.Core.SourceGenerator.csproj
tests/Files.InteractionTests/Files.InteractionTests.csproj

Code Quality: Update package references

---

src/Files.App/Actions/FileSystem/OpenItemAction.cs

Feature: Removed limit that prevented opening more than ten files at the same time

---

src/Files.App/Utils/Git/GitHelpers.cs

- Closes https://files-org.sentry.io/issues/5549705044/events/95f583157753427d9838cdb159b84d32/
2. ...

Fix: Fixed crash when opening folders with invalid git configs

---

src/Files.App/ViewModels/ShellViewModel.cs

- https://files-org.sentry.io/issues/5497293589/events/97d0f7a7cda546d19e51e5ca2ebe4c3d/
2. ...

Code Quality: Suppressed NullReferenceException caused by EnableRaisingEvents

---

src/Files.App/Utils/Shell/ShellFileOperations2.cs

Fix: Fixed NullReferenceException with ShellFileOperations2

---

src/Files.App/Strings/en-US/Resources.resw
src/Files.App/Views/Settings/AppearancePage.xaml

Feature: Improved UX for toolbar settings

---

src/Files.App/Data/Models/SelectedItemsPropertiesViewModel.cs
src/Files.App/Extensions/StringExtensions.cs
src/Files.App/Views/Layouts/BaseLayoutPage.cs

Fix: Fixed OverflowException in UpdateSelectionSize

---

src/Files.App/Services/PreviewPopupProviders/QuickLookProvider.cs

- Fixed a regression caused with #16163
2. ...

Fix: Fixed QuickLook support

---

src/Files.App/ViewModels/Properties/Items/CombinedFileProperties.cs

- https://files-org.sentry.io/issues/5546684093/events/dfab593805d74678a4a9e073a946ea0e/
2. ...

Fix: Fixed InvalidOperationException in GetSystemFilePropertiesAsync

---

src/Files.App/Data/Contracts/IInfoPaneSettingsService.cs
src/Files.App/Services/Settings/InfoPaneSettingsService.cs
src/Files.App/ViewModels/UserControls/InfoPaneViewModel.cs
src/Files.App/Views/MainPage.xaml.cs

Code Quality: Fixed the setting name for InfoPane

---

src/Files.App/Data/Commands/Manager/CommandManager.cs
src/Files.App/Helpers/PathNormalization.cs
src/Files.App/Services/App/AppThemeModeService.cs
src/Files.App/Services/App/AppUpdateSideloadService.cs
src/Files.App/Utils/Cloud/CloudDrivesManager.cs
src/Files.App/Utils/Storage/Operations/FileOperationsHelpers.cs
src/Files.App/ViewModels/Layouts/BaseLayoutViewModel.cs

- https://files-org.sentry.io/issues/5512246531/events/3cd1ff17ebd34bbd81a5f3b2a8944c8f/
- https://files-org.sentry.io/issues/5515345913/events/573446f4b79d459c9d1db5e42b0fb029/
- https://files-org.sentry.io/issues/5833478165/events/ed325d08115440fe978f91e2a41a06bd/
- https://files-org.sentry.io/issues/5532296438/events/53aa0c6a83ea4364893350f8a4b6a623/
- https://files-org.sentry.io/issues/5833504869/events/a32230ee8261466e80aa8d9a52cd0d92/
- https://files-org.sentry.io/issues/5833462955/events/7398ae8ff92d42df9e82b343b75fad3c/
- https://files-org.sentry.io/issues/5833469890/events/8acdc13ae2ea4648af9c4ff4bacb27d9/
- https://files-org.sentry.io/issues/5833466595/events/d12e6d1f144540d29974c5db51d6d4f0/
- …

CodeQuality: Removed logging for known exceptions

---

src/Files.App/Utils/Storage/StorageItems/BaseQueryResults.cs

- https://files-org.sentry.io/issues/5591413943/events/2175772058444b3bb27118354aebd0d4/
2. ...

Code Quality: Fix RegexParseException when getting search results

---

src/Files.App/UserControls/Menus/FileTagsContextMenu.cs

Reverts files-community/Files#16168

Fix: Fixed a crash when right clicking

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/ViewModels/Settings/AboutViewModel.cs
src/Files.App/Views/Settings/AboutPage.xaml

**Copy User Id**
1. Opened about page
2. Confirmed Copy > User Id works as expected
**Report Bug**
- Reporting a bug from the about page automatically passes the user id to GitHub

Feature: Added an option to copy the User ID from the about page

---

.github/scripts/Configure-AppxManifest.ps1
builds/azure-pipelines-release.yml
src/Files.App (Package)/Package.appxmanifest

- Closes #
2. Confirmed the Start Menu tile matched the app title

Fix: Fixed an issue where the Start Menu tile didn't specify the branch

---

src/Files.App/Helpers/Navigation/NavigationHelpers.cs

- Partial revert #16102
2. ...

Fix: Fixed issue with navigating photos on Windows 10

---

src/Files.App/Actions/FileSystem/RestoreAllRecycleBinAction.cs
src/Files.App/Data/Contracts/IStorageTrashBinService.cs
src/Files.App/Services/Storage/StorageTrashBinService.cs
src/Files.App/Services/Windows/WindowsDialogService.cs
src/Files.App/Services/Windows/WindowsWallpaperService.cs
src/Files.App/ViewModels/Dialogs/DecompressArchiveDialogViewModel.cs
src/Files.App/ViewModels/Settings/AdvancedViewModel.cs
src/Files.App/ViewModels/Settings/GeneralViewModel.cs

I forgot dispose some com instances before. Diposed using ComPtr
~~You can't check anything.~~

Code Quality: Dispose all com instances

---

src/Files.App/MainWindow.xaml.cs

- Closes #16265
1. Resized Files and confirmed the minimum size is correct

Feature: Reduced minimum window dimensions

---

src/Files.App/Views/Shells/BaseShellPage.cs
src/Files.App/Views/Shells/ColumnShellPage.xaml.cs
src/Files.App/Views/Shells/ModernShellPage.xaml.cs

- Closes #14801 
1. Open a folder with the columns layout.
2. Open some columns and change their sorting preferences.
3. Close the columns and reopen them.
4. See sorting preferences are saved and applied.

Fix: Fixed an issue where sorting preferences didn't save when changed in the columns layout

---

src/Files.App/Actions/FileSystem/Transfer/BaseTransferItemAction.cs

https://sentry.io/organizations/files-org/issues/5849700935/?project=4507376940351488
2. ...

Fix: Fixed NullReferenceException in BaseTransferItemAction.ExecuteTransferAsync

---

.github/ISSUE_TEMPLATE/bug_report.yml

GitHub: Update bug report type

---

.github/ISSUE_TEMPLATE/feature_request.yml

GitHub: Update feature request type

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/code_quality_issue.yml
.github/ISSUE_TEMPLATE/feature_request.yml

GitHub: Added default titles to all issue templates

---

src/Files.App/MainWindow.xaml.cs

Fix: Fixed window placement

---

src/Files.App/Helpers/UI/UIFilesystemHelpers.cs

Sorry, I didn't check.
- Related to #16317 
2. ...

Code Quality: Lowercase item type

---

src/Files.App/Data/Contracts/IGeneralSettingsService.cs
src/Files.App/Dialogs/CreateArchiveDialog.xaml.cs
src/Files.App/Services/Settings/GeneralSettingsService.cs

- Closes #16340
1. Confirmed the selected archive creation options are correctly saved

Feature: Save archive creation settings

---

src/Files.App (Package)/Package.appxmanifest

I resolved that this was too small a change to make it worth opening an issue.
N/A
---
```diff
-    
+    
```

Code Quality: Fix strange capitalization in `Package.appxmanifest`

---

crowdin.yml

I resolved that this was too small a change to make it worth opening an issue.
N/A
---
I noticed that the commit message for Crowdin resource sync in `crowdin.yml` did not match that of Files's contribution style, which requires that each commit be in the present tense and not be lower case.

Code Quality: Updated commit message in `crowdin.yml` to match contribution guidelines

---

src/Files.App/ViewModels/Dialogs/BulkRenameDialogViewModel.cs

- Closes #16376
1. Confirmed the items are renamed in the correct order

Fix: Fixed an issue where bulk rename didn't follow the sort order

---

.github/ISSUE_TEMPLATE/bug_report.yml

GitHub: Changed bug report log upload tip

---

src/Files.App/ViewModels/Layouts/BaseLayoutViewModel.cs

- Closes #16388
1. Selected some items
2. Started dragging them
3. Canceled drag & drop
4. Items remained selected

Fix: Fixed an issue where canceling drag & dropped cleared the selected items

---

src/Files.App/Utils/Global/WSLDistroManager.cs

- Closes #
2. Confirmed prompt to install WSL didn't show

Fix: Fixed an issue where a WSL prompt would sometimes display on startup

---

.github/PRIVACY.md
src/Files.App/Constants.cs

- Closes #
1. Confirmed link in about page opened correct page

Feature: Updated the privacy policy url

---

src/Files.App (Package)/Files.Package.wapproj
src/Files.App.Controls/Files.App.Controls.csproj
src/Files.App/Files.App.csproj
tests/Files.App.UITests/Files.App.UITests.csproj

Code Quality: Updated WindowsAppSDK to 1.5.241107002

---

src/Files.App (Package)/Package.appxmanifest

Feature: Added support for making Files default app for opening gz archives

---

src/Files.App/UserControls/TabBar/TabBar.xaml.cs

- Closes #14568 
https://github.com/user-attachments/assets/13cf1573-9b3a-40aa-93cf-c4ff253be620

Fix: Fixed an issue where tabs weren't placed in the correct order when dragged from other windows

---

.github/workflows/ci.yml

Code Quality: Auto delete artifacts within CI

---

src/Files.App/Utils/Cloud/CloudDrivesDetector.cs
src/Files.App/Utils/Cloud/CloudProviders.cs

> as motioned by Yair in the website repo
There isn't exactly a way for me to *download* Amazon Drive and test it since its discontinuation. 😅

Fix: Removed unsupported Amazon Drive from cloud providers

---

src/Files.App/Utils/Shell/LaunchHelper.cs

Fix #16591.
Already tested disk "clean up" action.

Fix: Fixed crash that would occur when using the 'Storage sense' action

---

src/Files.App/Helpers/MenuFlyout/ContextFlyoutModelToElementHelper.cs

- Closes #16193
1. Set a folder in column view mode
2. Right click on empty space, check it does not crash

Fix: Fixed a crash in the Column Layout context menu

---

src/Files.App/Actions/Content/Tags/OpenAllTaggedActions.cs
src/Files.App/Actions/Navigation/OpenInNewTab/OpenInNewTabFromHomeAction.cs
src/Files.App/Actions/Navigation/OpenInNewTab/OpenInNewTabFromSidebarAction.cs
src/Files.App/Data/Contracts/IGeneralSettingsService.cs
src/Files.App/Helpers/Navigation/NavigationHelpers.cs
src/Files.App/Services/Settings/GeneralSettingsService.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/UserControls/Widgets/DrivesWidget.xaml.cs
src/Files.App/UserControls/Widgets/NetworkLocationsWidget.xaml.cs
src/Files.App/UserControls/Widgets/QuickAccessWidget.xaml.cs
src/Files.App/ViewModels/Layouts/BaseLayoutViewModel.cs
src/Files.App/ViewModels/Settings/GeneralViewModel.cs
src/Files.App/ViewModels/UserControls/SidebarViewModel.cs
src/Files.App/ViewModels/UserControls/Widgets/DrivesWidgetViewModel.cs
src/Files.App/ViewModels/UserControls/Widgets/NetworkLocationsWidgetViewModel.cs
src/Files.App/ViewModels/UserControls/Widgets/QuickAccessWidgetViewModel.cs
src/Files.App/Views/Layouts/DetailsLayoutPage.xaml.cs
src/Files.App/Views/Layouts/GridLayoutPage.xaml.cs
src/Files.App/Views/Settings/GeneralPage.xaml

- Closes #16474
1. Enable setting to auto switch to newly created tab
2. Right click item in sidebar and open in new tab
3. Confirm the focus is switched to the new tab

Feature: Added option to always switch to newly created tab

---

src/Files.App/Helpers/Application/AppLifecycleHelper.cs
src/Files.App/ViewModels/MainPageViewModel.cs

- Closes #15772
1. Run "files-dev.exe ." from wsl

Fix: Fixed crash that would occur when starting Files from WSL directories

---

src/Files.App/UserControls/Pane/ShelfPane.xaml
src/Files.App/Views/MainPage.xaml

Code Quality: Design polish for the upcoming Shelf feature

---

src/Files.App/Data/Contracts/IAppearanceSettingsService.cs
src/Files.App/Services/Settings/AppearanceSettingsService.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/UserControls/AddressToolbar.xaml
src/Files.App/ViewModels/Settings/AdvancedViewModel.cs
src/Files.App/ViewModels/Settings/AppearanceViewModel.cs
src/Files.App/ViewModels/UserControls/AddressToolbarViewModel.cs
src/Files.App/Views/Settings/AdvancedPage.xaml
src/Files.App/Views/Settings/AppearancePage.xaml

Code Quality: Toolbar toggle button for Shelf

---

src/Files.App/UserControls/Widgets/FileTagsWidget.xaml

Feature: Updated styling in the Tags widget

---

src/Files.App/Actions/Show/ToggleDetailsPaneAction.cs
src/Files.App/Actions/Show/TogglePreviewPaneAction.cs

Code Quality: Updated existing pane toggles to prepare for upcoming Shelf feature

---

src/Files.App/Views/Layouts/GridLayoutPage.xaml
src/Files.App/Views/Layouts/GridLayoutPage.xaml.cs

Feature: Improved contrast for selected items in the Grid View layout

---

src/Files.App/Data/Items/DetailsLayoutColumnItem.cs
src/Files.App/Views/Layouts/DetailsLayoutPage.xaml.cs

The first follow up PR to #16741 
Workaround CsWinRT AV issue by updating each property of the view model instead of replacing the entire view model.

Code Quality: Workaround for CsWinRT access violation

---

src/Files.App.CsWin32/NativeMethods.txt
src/Files.App.CsWin32/Windows.Win32.Extras.cs

Coped with an issue where building with x86 fails.
1. build on x86

Code Quality: Defined manual SetWindowLongPtr

---

Directory.Build.props
src/Files.App.BackgroundTasks/Files.App.BackgroundTasks.csproj
src/Files.App.Controls/Files.App.Controls.csproj
src/Files.App.CsWin32/Files.App.CsWin32.csproj
src/Files.App.Server/Files.App.Server.csproj
src/Files.App.Storage/Files.App.Storage.csproj
src/Files.App/Files.App.csproj
tests/Files.App.UITests/Files.App.UITests.csproj

- Related #16741 
1. Built Files
---
Replaces the explicit `$(TargetFrameworkVersion)-windows$(TargetWindowsVersion)` with a global `$(WindowsTargetFramework)` switch.

Code Quality: Removed `$(TargetFrameworkVersion)-windows$(TargetWindowsVersion)`

---

src/Files.App/Actions/FileSystem/AddItemAction.cs
src/Files.App/Actions/FileSystem/CreateFolderAction.cs
src/Files.App/Actions/FileSystem/CreateFolderWithSelectionAction.cs
src/Files.App/Actions/FileSystem/CreateShortcutAction.cs
src/Files.App/Actions/FileSystem/CreateShortcutFromDialogAction.cs

This pull request aims to improve code quality and maintainability in the Files App by centralizing localization strings and replacing string literals with string constants. The changes enhance consistency, reduce the risk of typos, and streamline future updates and localization efforts.
#16718 
1. Created a centralized `Strings` class to manage all localization strings.
2. Refactored localization strings in the following actions:
- `AddItemAction`
- `CreateFolderAction`
- `CreateFolderWithSelectionAction`
- `CreateShortcutAction`
- `CreateShortcutFromDialogAction`
3. Updated label, descriptions for improved user experience.
4. Replaced string literals with corresponding string constants throughout the Files App codebase.
- Improved maintainability: All strings are now managed in one …

Code Quality: Update localization strings in action classes

---

src/Files.App/ViewModels/HomeViewModel.cs
src/Files.App/Views/HomePage.xaml.cs

- Closes #16870 
1. Open the home page
2. Note the free space on the C drive
3. Download a large file
4. Navigate to the home page in the same or new tab

Fix: Fixed an issue where the Home Page didn't properly refresh

---

.github/workflows/cd-sideload-preview.yml
.github/workflows/cd-sideload-stable.yml
.github/workflows/cd-store-preview.yml
.github/workflows/cd-store-stable.yml

Code Quality: Fixed package restore for launcher project

---

.github/workflows/cd-store-preview.yml
.github/workflows/cd-store-stable.yml

GitHub: Publish store upload packages to Microsoft Store directly

---

Directory.Packages.props

Code Quality: WinAppSdk 1.7.250310001

---

Directory.Packages.props

Code Quality: Revert Vanara update

---

src/Files.App/ViewModels/Settings/AboutViewModel.cs

Code Quality: Updated WCT attribution in license notice

---

src/Files.App/Files.App.csproj

Code Quality: Added WCT SettingsControls package reference to Files.App.csproj

---

src/Files.App/ViewModels/UserControls/NavigationToolbarViewModel.cs

- #16029
Just check the afterwards: https://github.com/0x5bfa/Files/blob/fd2b1bb30b39d907a38b522c75ab423061269789/src/Files.App/ViewModels/UserControls/NavigationToolbarViewModel.cs

Code Quality: Improved the code quality of NavigationToolbarViewModel

---

Directory.Packages.props
src/Files.App.Launcher/Files.App.Launcher.vcxproj
src/Files.App.Launcher/packages.config

Code Quality: Updated dependencies

---

.github/NOTICE.md
src/Files.App/ViewModels/Settings/AboutViewModel.cs

Code Quality: Added a credit for Dongle.GuidRVAGen

---

src/Files.App/UserControls/NavigationToolbar.xaml
src/Files.App/ViewModels/UserControls/NavigationToolbarViewModel.cs

- #16029
2. Enable Omnibar from Settings > Advanced

Code Quality: Fixed a crash when focusing on Omnibar

---

src/Files.App/UserControls/NavigationToolbar.xaml

Code Quality: Include shortcuts in mode tooltips

---

src/Files.App.CsWin32/NativeMethods.txt
src/Files.App/Data/Commands/HotKey/HotKey.cs
src/Files.App/Helpers/Win32/Win32PInvoke.Methods.cs

- Related #15000 
2. Tested hotkey functions

Code Quality: Replaced DllImport calls with CsWin32 generations for keyboard character enumerations

---

src/Files.App/Utils/Storage/Operations/FileOperationsHelpers.cs

Fix: Fixed issue with deleting items that don't fit in Recycle Bin 

---

src/Files.App/Actions/Content/Install/InstallCertificateAction.cs
src/Files.App/Actions/Content/Install/InstallFontAction.cs
src/Files.App/Actions/Content/Install/InstallInfDriverAction.cs
src/Files.App/Actions/FileSystem/CopyItemPathAction.cs
src/Files.App/Actions/FileSystem/PasteItemToSelectionAction.cs
src/Files.App/Actions/Show/ToggleShowHiddenItemsAction.cs
src/Files.App/Actions/Show/ToggleToolbarAction.cs
src/Files.App/Dialogs/SettingsDialog.xaml.cs
src/Files.App/Strings/en-US/Resources.resw
src/Files.App/ViewModels/Settings/ActionsViewModel.cs
src/Files.App/Views/Settings/ActionsPage.xaml
src/Files.App/Views/Settings/ActionsPage.xaml.cs

- Closes #17134
- Closes #17090
- For #15151
1. Reviewed updated strings
2. Confirmed that entering a search query filters actions in settings
3. Confirmed that resizing the app window with the settings dialog no longer causes a crash

Feature: Added support for searching commands on the actions page

---

src/Files.App/app.manifest

- Closes #17065
- For #14865
1. Confirmed that Files can open and modify items in directories with long paths

Feature: Added support for long paths

---

Directory.Packages.props

Code Quality: Updated Directory.Packages.props

---

src/Files.App/Data/Factories/ContentPageContextFlyoutFactory.cs
src/Files.App/Data/Models/ContextMenuFlyoutItemViewModel.cs
src/Files.App/Data/Models/ContextMenuFlyoutItemViewModelBuilder.cs
src/Files.App/Helpers/MenuFlyout/ContextFlyoutModelToElementHelper.cs

- Closes #7505
1. Opened context menu and pressed the 'alt' key

Feature: Added access keys to the right click context menu

---

src/Files.App.Controls/BreadcrumbBar/BreadcrumbBar.xaml

- For #16029
1. Confirmed breadcrumb chevrons have the correct state when resuming from sleep

Code Quality: Animated chevron

---

src/Files.App/Views/Layouts/DetailsLayoutPage.xaml.cs

- Closes #13774
1. Opened folder containing single item
2. Confirmed that pressing down key selects the item

Fix: Fixed issue preventing file selection via keyboard

---

src/Files.App/ViewModels/UserControls/NavigationToolbarViewModel.cs

- For #16029
- Fixes 'Breadcrumb bar doesn't work in search results page'

Code Quality: Fixed Omnibar navigation in search results

---

src/Files.App/ViewModels/ShellViewModel.cs
src/Files.App/Views/Shells/ModernShellPage.xaml
src/Files.App/Views/Shells/ModernShellPage.xaml.cs

- Closes #
1. Confirmed that navigating or refreshing while items are filtered clears the query and doesn't freeze

Code Quality: Fixed two way binding for filter header

---

src/Files.App/Views/Layouts/BaseLayoutPage.cs

Code Quality: Fixed columns view navigation

---

src/Files.App (Package)/Package.appxmanifest

Release: v4.0
